"use client";

import { useCallback, useEffect, useState, type CSSProperties, type FormEvent } from "react";
import { money } from "@/lib/payroll/ui-labels";
import type { PayrollInsuranceSettingVersion } from "@/lib/payroll/insurance";

function month(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit"}).format(new Date()).slice(0,7)}
export default function EmployeeInsuranceSettings({userId,vi}:{userId:number;vi:boolean}){const[history,setHistory]=useState<PayrollInsuranceSettingVersion[]>([]);const[current,setCurrent]=useState<PayrollInsuranceSettingVersion|null>(null);const[enrolled,setEnrolled]=useState(false);const[base,setBase]=useState("0");const[effectiveMonth,setEffectiveMonth]=useState(month);const[note,setNote]=useState("");const[saving,setSaving]=useState(false);const[error,setError]=useState("");const load=useCallback(async()=>{const response=await fetch(`/api/admin/payroll/insurance?userId=${userId}`,{cache:"no-store"});const data=await response.json();if(response.ok){setHistory(data.history??[]);setCurrent(data.current??null)}},[userId]);useEffect(()=>{const controller=new AbortController();fetch(`/api/admin/payroll/insurance?userId=${userId}`,{cache:"no-store",signal:controller.signal}).then(async response=>({ok:response.ok,data:await response.json()})).then(({ok,data})=>{if(ok){setHistory(data.history??[]);setCurrent(data.current??null)}}).catch(()=>undefined);return()=>controller.abort()},[userId]);async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");const response=await fetch("/api/admin/payroll/insurance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId,isEnrolled:enrolled,insuranceBaseAmount:enrolled?Number(base):0,effectiveMonth,note})});setSaving(false);if(!response.ok){setError(vi?"Không thể lưu cài đặt bảo hiểm.":"보험 설정을 저장하지 못했습니다.");return}await load();setNote("")}
return <section style={s.card}><h2 style={s.title}>{vi?"Bảo hiểm nhân viên":"직원 보험"}</h2>{current?<div style={s.current}><b>{current.isEnrolled?(vi?"Đang tham gia":"가입"):(vi?"Không tham gia":"미가입")}</b><span>{vi?"Mức cơ sở":"기준급여"} {money(current.insuranceBaseAmount)}</span><small>{current.effectiveMonth.slice(0,7)} · #{current.revision}</small></div>:<p>{vi?"Không có cài đặt; được xử lý là không tham gia.":"설정 없음 · 자동 미가입 0원 처리"}</p>}<form style={s.form} onSubmit={submit}><label style={s.field}><span>{vi?"Tham gia":"가입 여부"}</span><input type="checkbox" checked={enrolled} onChange={e=>{setEnrolled(e.target.checked);if(e.target.checked&&Number(base)<1)setBase("5000000")}}/></label><label style={s.field}>{vi?"Mức lương cơ sở bảo hiểm":"보험 기준급여"}<input style={s.input} disabled={!enrolled} required={enrolled} type="number" min={enrolled?1:0} step="1" value={base} onChange={e=>setBase(e.target.value)}/></label><label style={s.field}>{vi?"Tháng áp dụng":"적용 월"}<input style={s.input} required type="month" value={effectiveMonth} onChange={e=>setEffectiveMonth(e.target.value)}/></label><label style={s.field}>{vi?"Lý do thay đổi":"변경 사유"}<textarea style={s.input} required value={note} onChange={e=>setNote(e.target.value)}/></label><button style={s.button} disabled={saving}>{saving?(vi?"Đang lưu…":"저장 중…"):(vi?"Thêm phiên bản":"새 revision 등록")}</button></form>{error&&<p role="alert" style={s.error}>{error}</p>}<details><summary>{vi?"Lịch sử cài đặt":"설정 이력"}</summary>{history.map(item=><article style={s.history} key={item.id}><b>{item.effectiveMonth.slice(0,7)} · #{item.revision}</b><span>{item.isEnrolled?(vi?"Tham gia":"가입"):(vi?"Không tham gia":"미가입")} · {money(item.insuranceBaseAmount)}</span>{item.note&&<small>{item.note}</small>}</article>)}</details></section>}
const s={card:{padding:14,border:"1px solid #e5e7eb",borderRadius:14,background:"#fff",display:"grid",gap:10},title:{margin:0,fontSize:17},current:{display:"grid",gap:3,padding:10,borderRadius:10,background:"#eff6ff",fontSize:13},form:{display:"grid",gap:9},field:{display:"grid",gap:5,fontSize:13,fontWeight:700},input:{width:"100%",minHeight:40,padding:8,border:"1px solid #d1d5db",borderRadius:9},button:{minHeight:42,border:0,borderRadius:10,background:"#111827",color:"#fff",fontWeight:800},error:{color:"#b91c1c"},history:{display:"grid",gap:3,padding:9,marginTop:6,border:"1px solid #e5e7eb",borderRadius:9,fontSize:12}} satisfies Record<string,CSSProperties>;
