"use client";

import { useEffect, useState, type CSSProperties } from "react";
import { calculateInsuranceAmount, percentToBasisPoints } from "@/lib/payroll/insurance";
import { money } from "@/lib/payroll/ui-labels";

type Settings={payment_day:number;employee_insurance_rate_bp:number;employer_insurance_rate_bp:number;director_insurance_enabled:boolean;director_insurance_base_amount:number;director_insurance_rate_bp:number};
export default function PayrollInsuranceSettings({vi}:{vi:boolean}){const[data,setData]=useState<Settings|null>(null);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");useEffect(()=>{void fetch("/api/admin/payroll/settings",{cache:"no-store"}).then(r=>r.json()).then(result=>setData(result.settings??null))},[]);if(!data)return null;const settings=data;const director=calculateInsuranceAmount(data.director_insurance_enabled?data.director_insurance_base_amount:0,data.director_insurance_rate_bp);async function save(){setSaving(true);setMessage("");const response=await fetch("/api/admin/payroll/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({paymentDay:settings.payment_day,employeeInsuranceRateBp:settings.employee_insurance_rate_bp,employerInsuranceRateBp:settings.employer_insurance_rate_bp,directorInsuranceEnabled:settings.director_insurance_enabled,directorInsuranceBaseAmount:settings.director_insurance_base_amount,directorInsuranceRateBp:settings.director_insurance_rate_bp})});setSaving(false);setMessage(response.ok?(vi?"Đã lưu cài đặt bảo hiểm.":"보험 설정을 저장했습니다."):(vi?"Không thể lưu cài đặt bảo hiểm.":"보험 설정을 저장하지 못했습니다."));}
return <section style={s.card}><h2 style={s.title}>{vi?"Cài đặt bảo hiểm toàn cục":"전역 보험 설정"}</h2><Rate label={vi?"Tỷ lệ nhân viên":"직원 부담률"} value={data.employee_insurance_rate_bp} change={v=>setData({...data,employee_insurance_rate_bp:v})}/><Rate label={vi?"Tỷ lệ công ty":"회사 부담률"} value={data.employer_insurance_rate_bp} change={v=>setData({...data,employer_insurance_rate_bp:v})}/><label style={s.field}><span>{vi?"Áp dụng bảo hiểm giám đốc pháp nhân":"법인장 보험 사용"}</span><input type="checkbox" checked={data.director_insurance_enabled} onChange={e=>setData({...data,director_insurance_enabled:e.target.checked})}/></label><NumberField label={vi?"Mức cơ sở bảo hiểm giám đốc":"법인장 보험 기준금액"} value={data.director_insurance_base_amount} change={v=>setData({...data,director_insurance_base_amount:v})}/><Rate label={vi?"Tỷ lệ bảo hiểm giám đốc":"법인장 보험 부담률"} value={data.director_insurance_rate_bp} change={v=>setData({...data,director_insurance_rate_bp:v})}/><div style={s.total}><span>{vi?"Chi phí bảo hiểm giám đốc hàng tháng":"법인장 월 보험비용"}</span><b>{money(director)}</b></div><button type="button" style={s.button} disabled={saving} onClick={save}>{saving?(vi?"Đang lưu…":"저장 중…"):(vi?"Lưu bảo hiểm":"보험 설정 저장")}</button>{message&&<p role="status">{message}</p>}</section>}
function Rate({label,value,change}:{label:string;value:number;change:(value:number)=>void}){return <label style={s.field}><span>{label}</span><span><input style={s.input} type="number" min="0" max="100" step="0.01" value={value/100} onChange={e=>{const bp=percentToBasisPoints(e.target.value);if(bp!==null)change(bp)}}/> %</span></label>}
function NumberField({label,value,change}:{label:string;value:number;change:(value:number)=>void}){return <label style={s.field}><span>{label}</span><input style={s.input} type="number" min="0" step="1" value={value} onChange={e=>change(Number(e.target.value))}/></label>}
const s={card:{padding:16,border:"1px solid #e5e7eb",borderRadius:16,background:"#fff",display:"grid",gap:10},title:{margin:0,fontSize:18},field:{display:"grid",gap:5,fontSize:13,fontWeight:700},input:{width:"100%",minHeight:40,padding:8,border:"1px solid #d1d5db",borderRadius:9},total:{display:"flex",justifyContent:"space-between",padding:10,borderRadius:10,background:"#f8fafc"},button:{minHeight:42,border:0,borderRadius:10,background:"#111827",color:"#fff",fontWeight:800}} satisfies Record<string,CSSProperties>;
