import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import {PGlite} from '@electric-sql/pglite';
const sql=readFileSync('supabase/migrations/20261001172556_support_unspecified_partner_payment_mode.sql','utf8');
const old=readFileSync('supabase/migrations/202608230001_add_business_partner_settlement_policy.sql','utf8');
const oldConstraint=old.slice(old.indexOf('add constraint business_partners_settlement_policy'),old.indexOf('comment on column public.business_partners.settlement_mode'));
async function fixture(){
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create role service_role;
 create table users(id bigint primary key,role text,is_active boolean,app_login_enabled boolean);
 insert into users values(1,'owner',true,true),(2,'staff',true,true);
 create table business_partners(id bigint generated by default as identity primary key,name text not null unique,partner_type text,payment_mode text not null constraint business_partners_payment_mode_check check(payment_mode in ('immediate','postpaid')),settlement_mode text,settlement_rule text,default_payment_term_days integer,default_fund_account_id bigint,partner_subtype_id bigint,phone text,contact_name text,memo text,is_active boolean,updated_at timestamptz default now());
 alter table business_partners ${oldConstraint}
 create table business_partner_ledger_parties(business_partner_id bigint primary key,ledger_party_id bigint);
 create table business_partner_audit_logs(business_partner_id bigint,actor_user_id bigint,action text,before_snapshot jsonb,after_snapshot jsonb);
 create table inventory_supplier_aliases(id bigint primary key,business_partner_id bigint,supplier_name text);
 create function business_partner_fund_account_is_eligible_v1(bigint) returns boolean language sql as $$ select true $$;
 create function business_partner_subtype_is_eligible_v1(bigint,text,bigint default null) returns boolean language sql as $$ select true $$;
 create function business_partner_ensure_ledger_party_v1(bigint) returns bigint language plpgsql as $$ begin insert into business_partner_ledger_parties values($1,$1+100) on conflict do nothing;return $1+100;end; $$;
 insert into business_partners(name,partner_type,payment_mode,settlement_mode,is_active) values('kh\u00e1c','other','postpaid','ad_hoc',true),('Regular','food','postpaid','ad_hoc',true);
 insert into business_partner_ledger_parties values(1,101),(2,102);
 insert into inventory_supplier_aliases values(1,1,'kh\u00e1c');`);
 await db.exec(sql);return db;
}
async function rpc(db,mode,settlement=null,rule=null,term=null,update=false,actor=1){
 const args=['Test','other',mode,settlement,rule,term,null,null,null,null,null,true,null,actor];if(update)args.unshift(3);
 const params=args.map((_,index)=>`$${index+1}`).join(',');
 return (await db.query(`select business_partner_${update?'update':'create'}_v4(${params}) as result`,args)).rows[0].result;
}
test('migration only changes regular khac policy and preserves bridges and supplier aliases',async()=>{
 const db=await fixture();try{
 assert.deepEqual((await db.query('select name,payment_mode,settlement_mode,settlement_rule,default_payment_term_days from business_partners order by id')).rows,[{name:'kh\u00e1c',payment_mode:'unspecified',settlement_mode:null,settlement_rule:null,default_payment_term_days:null},{name:'Regular',payment_mode:'postpaid',settlement_mode:'ad_hoc',settlement_rule:null,default_payment_term_days:null}]);
 assert.equal((await db.query('select count(*)::int as n from business_partner_ledger_parties')).rows[0].n,2);
 assert.deepEqual((await db.query('select * from inventory_supplier_aliases')).rows,[{id:1,business_partner_id:1,supplier_name:'kh\u00e1c'}]);
 await db.exec(sql);assert.equal((await db.query('select count(*)::int as n from business_partners')).rows[0].n,2);
 }finally{await db.close();}
});
test('constraints reject invalid unspecified combinations and retain existing payment policies',async()=>{
 const db=await fixture();try{
 for(const [mode,settlement,rule,term,valid] of [['unspecified',null,null,null,true],['unspecified','ad_hoc',null,null,false],['unspecified',null,null,30,false],['unspecified',null,'net_days',null,false],['immediate',null,null,null,true],['immediate','ad_hoc',null,null,false],['postpaid','ad_hoc',null,null,true],['postpaid','scheduled','net_days',30,true],['postpaid','scheduled','monthly_once',null,true],['postpaid',null,null,30,true],[null,null,null,null,false],['unknown',null,null,null,false]]){
 const query=()=>db.query('insert into business_partners(name,payment_mode,settlement_mode,settlement_rule,default_payment_term_days) values($1,$2,$3,$4,$5)',['case'+Math.random(),mode,settlement,rule,term]);
 if(valid)await query();else await assert.rejects(query);
 }
 }finally{await db.close();}
});
test('v4 create/update support unspecified, audit and retain auto-link and authorization',async()=>{
 const db=await fixture();try{
 const created=await rpc(db,'unspecified');assert.equal(created.status,'created');assert.equal(Number(created.ledgerPartyId),103);
 assert.equal((await rpc(db,'unspecified','ad_hoc',null,null,true)).status,'invalid_input');
 assert.equal((await rpc(db,'unspecified',null,null,30,true)).status,'invalid_input');
 assert.equal((await rpc(db,'postpaid','ad_hoc',null,null,true)).status,'updated');
 assert.equal((await rpc(db,'immediate',null,null,null,true)).status,'updated');
 assert.equal((await rpc(db,'unspecified',null,null,null,true)).status,'updated');
 assert.equal((await rpc(db,'unspecified',null,null,null,true,2)).status,'forbidden');
 assert.equal((await db.query('select count(*)::int as n from business_partner_audit_logs where business_partner_id=3')).rows[0].n,4);
 for(const fn of ['business_partner_create_v4','business_partner_update_v4']){
 const row=(await db.query('select prosecdef,proconfig,proacl::text as acl from pg_proc where proname=$1',[fn])).rows[0];assert.equal(row.prosecdef,true);assert.ok(row.proconfig.includes('search_path=pg_catalog, public'));assert.match(row.acl,/service_role=X/);assert.doesNotMatch(row.acl,/anon=|authenticated=|\{=X/);
 }
 }finally{await db.close();}
});
