import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
// @ts-expect-error Node strips TypeScript extensions in tests.
import { groupPartnersByTypeAndSubtype, parsePartnerInput, parsePartnerSubtypeCreateInput, parsePartnerSubtypeUpdateInput, PARTNER_TYPES } from "../lib/partners/policy.ts";
// @ts-expect-error Node strips TypeScript extensions in tests.
import { formatPartnerSubtypeName } from "../lib/partners/text.ts";

const read = (path: string) => readFileSync(join(process.cwd(), path), "utf8");
const sha256 = (path: string) => createHash("sha256").update(read(path)).digest("hex");
const migration = read("supabase/migrations/202608240002_add_business_partner_subtypes.sql");
const deleteMigration = read("supabase/migrations/202608240003_add_business_partner_subtype_delete.sql");
const foodSubtypeMigration = read("supabase/migrations/202608240004_update_food_partner_subtypes.sql");
const partnerServer = read("lib/partners/server.ts");
const partnerForm = read("components/PartnerForm.tsx");
const candidateForm = read("components/CandidatePartnerReviewForm.tsx");
const subtypeManager = read("components/PartnerSubtypeManager.tsx");
const collectionApi = read("app/api/admin/partners/route.ts");
const detailApi = read("app/api/admin/partners/[id]/route.ts");
const aliasApi = read("app/api/admin/partners/aliases/[id]/route.ts");
const subtypeCreateApi = read("app/api/admin/partners/subtypes/route.ts");
const subtypeUpdateApi = read("app/api/admin/partners/subtypes/[id]/route.ts");
const adminPage = read("app/(protected)/admin/partners/page.tsx");
const infoPage = read("app/(protected)/admin/partners/info/page.tsx");
const candidatePage = read("app/(protected)/admin/partners/candidates/[id]/page.tsx");
const partnerStyles = read("app/(protected)/admin/partners/partners.module.css");

const base = { name: "Fresh Foods", partnerType: "food", paymentMode: "immediate", settlementMode: null, settlementRule: null, defaultPaymentTermDays: null, defaultFundAccountId: null, partnerSubtypeId: null, phone: null, contactName: null, memo: null, isActive: true, ledgerPartyId: null };
const parse = (changes: Record<string, unknown>) => parsePartnerInput({ ...base, ...changes });

// ===================== A. DB / migration =====================

test("1: business_partner_subtypes table exists with the documented columns", () => {
  assert.match(migration, /create table public\.business_partner_subtypes \(/);
  for (const column of ["id bigint generated by default as identity primary key", "code text not null", "partner_type text not null", "name_ko text null", "name_vi text null", "sort_order integer not null default 0", "is_active boolean not null default true", "created_at timestamptz not null default now\\(\\)", "updated_at timestamptz not null default now\\(\\)"]) {
    assert.match(migration, new RegExp(column));
  }
});

test("2: code is unique (case/whitespace-insensitive, matching business_partners.name's own unique index style)", () => {
  assert.match(migration, /create unique index business_partner_subtypes_code_unique\s*\n\s*on public\.business_partner_subtypes \(lower\(btrim\(code\)\)\)/);
});

test("3/4: both name_ko and name_vi blank is rejected; either language alone is enough", () => {
  assert.match(migration, /constraint business_partner_subtypes_name_present check \(\s*\n\s*nullif\(btrim\(name_ko\), ''\) is not null\s*\n\s*or\s*\n\s*nullif\(btrim\(name_vi\), ''\) is not null\s*\n\s*\)/);
});

test("5/6: business_partners.partner_subtype_id is a nullable FK with ON DELETE RESTRICT", () => {
  assert.match(migration, /alter table public\.business_partners\s*\n\s*add column partner_subtype_id bigint null\s*\n\s*references public\.business_partner_subtypes\(id\) on delete restrict;/);
});

test("7: no backfill DML -- existing Partner rows all stay NULL, and this migration never assigns a subtype to any Partner", () => {
  const schemaAndSeed = migration.slice(0, migration.indexOf("alter table public.business_partners\n  add column partner_subtype_id"));
  assert.doesNotMatch(schemaAndSeed, /update public\.business_partners/i);
  assert.doesNotMatch(migration, /update public\.business_partners set partner_subtype_id/i);
  assert.match(migration, /existing Partner is assigned a subtype|it never assigns any existing Partner a subtype/);
});

test("8/9: every seeded subtype has a unique code and a partner_type from the app's PARTNER_TYPES contract", () => {
  const seedBlock = migration.slice(migration.indexOf("insert into public.business_partner_subtypes (code, partner_type"), migration.indexOf("-- business_partners FK"));
  const rows = [...seedBlock.matchAll(/\('([a-z_]+)', '([a-z_]+)', '[^']*', '[^']*', \d+\)/g)];
  assert.ok(rows.length >= 41, `expected at least 41 seed rows, found ${rows.length}`);
  const codes = rows.map(row => row[1]);
  assert.equal(new Set(codes).size, codes.length, "seed codes must be unique");
  for (const row of rows) assert.ok((PARTNER_TYPES as readonly string[]).includes(row[2]), `unknown seed partner_type: ${row[2]}`);
});

test("subtype indexes support the future partner_type -> partner_subtype_id comparison path", () => {
  assert.match(migration, /create index business_partner_subtypes_type_idx\s*\n\s*on public\.business_partner_subtypes \(partner_type, is_active, sort_order\)/);
  assert.match(migration, /create index business_partners_type_subtype_idx\s*\n\s*on public\.business_partners \(partner_type, partner_subtype_id, is_active\)/);
});

test("RLS/grants mirror the existing business_partners lockdown: no direct table access for anon/authenticated, service_role select only", () => {
  assert.match(migration, /alter table public\.business_partner_subtypes enable row level security;/);
  assert.match(migration, /revoke all on table public\.business_partner_subtypes from public, anon, authenticated, service_role;/);
  assert.match(migration, /grant select on table public\.business_partner_subtypes to service_role;/);
});

// ===================== B. KO/VI fallback =====================

test("10-14: formatPartnerSubtypeName follows the current-language-first, other-language-fallback, then unclassified-string pattern", () => {
  assert.equal(formatPartnerSubtypeName({ nameKo: "병맥주", nameVi: "Bia chai" }, "ko"), "병맥주");
  assert.equal(formatPartnerSubtypeName({ nameKo: "병맥주", nameVi: "Bia chai" }, "vi"), "Bia chai");
  assert.equal(formatPartnerSubtypeName({ nameKo: null, nameVi: "Bia chai" }, "ko"), "Bia chai");
  assert.equal(formatPartnerSubtypeName({ nameKo: "병맥주", nameVi: null }, "vi"), "병맥주");
  assert.equal(formatPartnerSubtypeName(null, "ko"), "미분류");
  assert.equal(formatPartnerSubtypeName(null, "vi"), "Chưa phân loại");
  assert.equal(formatPartnerSubtypeName(undefined, "ko"), "미분류");
  assert.equal(formatPartnerSubtypeName({ nameKo: null, nameVi: null }, "vi"), "Chưa phân loại");
});

// ===================== C. Partner mutation =====================

test("V1/V2/V3 create/update/review-alias signatures are untouched by this migration", () => {
  assert.doesNotMatch(migration, /create (or replace )?function public\.business_partner_(create|update)_v[123]\(/);
  assert.doesNotMatch(migration, /create (or replace )?function public\.business_partner_review_supplier_alias_v[123]\(/);
});

test("V4 adds p_partner_subtype_id to the full V3 contract for create/update/review_supplier_alias", () => {
  for (const name of ["business_partner_create_v4", "business_partner_update_v4", "business_partner_review_supplier_alias_v4"]) {
    assert.match(migration, new RegExp(`create function public\\.${name}`));
  }
  const createBody = migration.slice(migration.indexOf("create function public.business_partner_create_v4"), migration.indexOf("create function public.business_partner_update_v4"));
  const updateBody = migration.slice(migration.indexOf("create function public.business_partner_update_v4"), migration.indexOf("create function public.business_partner_review_supplier_alias_v4"));
  assert.match(createBody, /p_default_fund_account_id bigint,\s*\n\s*p_partner_subtype_id bigint,/);
  assert.match(updateBody, /p_default_fund_account_id bigint,\s*\n\s*p_partner_subtype_id bigint,/);
});

test("15/17/18/19: eligibility helper requires the subtype to exist, be active (or already-assigned), and belong to the target partner_type", () => {
  assert.match(migration, /create function public\.business_partner_subtype_is_eligible_v1/);
  const body = migration.slice(migration.indexOf("create function public.business_partner_subtype_is_eligible_v1"), migration.indexOf("alter function public.business_partner_subtype_is_eligible_v1"));
  assert.match(body, /select p_partner_subtype_id is null or exists \(/);
  assert.match(body, /where id = p_partner_subtype_id\s*\n\s*and partner_type = p_partner_type\s*\n\s*and \(is_active = true or id = p_current_subtype_id\)/);

  // Mirrors the SQL above in JS so the eligibility contract is pinned by a fast pure test.
  type Subtype = { id: number; partnerType: string; isActive: boolean };
  const subtypes: Subtype[] = [
    { id: 1, partnerType: "alcohol", isActive: true },
    { id: 2, partnerType: "alcohol", isActive: false },
    { id: 3, partnerType: "food", isActive: true },
  ];
  const isEligible = (subtypeId: number | null, partnerType: string, currentSubtypeId: number | null = null) =>
    subtypeId === null || subtypes.some(s => s.id === subtypeId && s.partnerType === partnerType && (s.isActive || s.id === currentSubtypeId));

  assert.equal(isEligible(null, "alcohol"), true); // 16. null always allowed
  assert.equal(isEligible(1, "alcohol"), true); // active + matching type
  assert.equal(isEligible(2, "alcohol"), false); // 18. inactive, no current-value carve-out -> blocked for new assignment
  assert.equal(isEligible(2, "alcohol", 2), true); // update keeping its own already-assigned inactive subtype
  assert.equal(isEligible(1, "food"), false); // 19. partner_type mismatch -> blocked
  assert.equal(isEligible(999, "alcohol"), false); // nonexistent id
});

test("create_v4/update_v4/review_supplier_alias_v4(create_partner) all reject an ineligible subtype before writing, with invalid_partner_subtype", () => {
  const createBody = migration.slice(migration.indexOf("create function public.business_partner_create_v4"), migration.indexOf("create function public.business_partner_update_v4"));
  const updateBody = migration.slice(migration.indexOf("create function public.business_partner_update_v4"), migration.indexOf("create function public.business_partner_review_supplier_alias_v4"));
  const reviewBody = migration.slice(migration.indexOf("create function public.business_partner_review_supplier_alias_v4"), migration.indexOf("alter function public.business_partner_create_v4"));
  const createPartnerBranch = reviewBody.slice(reviewBody.indexOf("if p_action = 'create_partner' then"), reviewBody.indexOf("elsif p_action = 'link_existing'"));
  for (const body of [createBody, updateBody, createPartnerBranch]) {
    assert.match(body, /business_partner_subtype_is_eligible_v1\(p_partner_subtype_id, btrim\(p_partner_type\)/);
    assert.match(body, /invalid_partner_subtype/);
  }
  // 20: update passes the row's own current subtype id so an unchanged, now-inactive value survives
  assert.match(updateBody, /v_current_subtype_id := \(v_before->>'partner_subtype_id'\)::bigint;/);
  assert.match(updateBody, /business_partner_subtype_is_eligible_v1\(p_partner_subtype_id, btrim\(p_partner_type\), v_current_subtype_id\)/);
  assert.match(createBody, /default_fund_account_id, partner_subtype_id, phone, contact_name, memo, is_active\s*\n\s*\) values \(/);
  assert.match(updateBody, /partner_subtype_id = p_partner_subtype_id,/);
});

test("create_v4 and review_supplier_alias_v4(create_partner) call the eligibility helper with exactly 2 args (no current-subtype carve-out); update_v4 alone passes the 3rd arg", () => {
  const createBody = migration.slice(migration.indexOf("create function public.business_partner_create_v4"), migration.indexOf("create function public.business_partner_update_v4"));
  const updateBody = migration.slice(migration.indexOf("create function public.business_partner_update_v4"), migration.indexOf("create function public.business_partner_review_supplier_alias_v4"));
  const reviewBody = migration.slice(migration.indexOf("create function public.business_partner_review_supplier_alias_v4"), migration.indexOf("alter function public.business_partner_create_v4"));
  const createPartnerBranch = reviewBody.slice(reviewBody.indexOf("if p_action = 'create_partner' then"), reviewBody.indexOf("elsif p_action = 'link_existing'"));
  // Exactly 2 args: closing paren immediately after btrim(p_partner_type) -- no current-subtype
  // id is ever threaded into create or into the Candidate "create new Partner" branch, so
  // p_current_subtype_id there always falls back to its SQL `default null`.
  assert.match(createBody, /business_partner_subtype_is_eligible_v1\(p_partner_subtype_id, btrim\(p_partner_type\)\)/);
  assert.match(createPartnerBranch, /business_partner_subtype_is_eligible_v1\(p_partner_subtype_id, btrim\(p_partner_type\)\)/);
  assert.match(updateBody, /business_partner_subtype_is_eligible_v1\(p_partner_subtype_id, btrim\(p_partner_type\), v_current_subtype_id\)/);
});

// Pure-JS mirror of the deployed SQL (business_partner_subtype_is_eligible_v1):
//   select p_partner_subtype_id is null or exists (
//     select 1 from business_partner_subtypes
//     where id = p_partner_subtype_id
//       and partner_type = p_partner_type
//       and (is_active = true or id = p_current_subtype_id)
//   );
// Because the EXISTS subquery is already scoped to `id = p_partner_subtype_id`, the
// `or id = p_current_subtype_id` carve-out only ever fires when the NEW value equals the
// OLD value -- it can never wave through a *different* inactive subtype. update_v4 always
// supplies its own pre-update partner_subtype_id (locked via `for update`) as that 3rd arg;
// create_v4 and the Candidate create_partner branch never supply a 3rd arg at all, so they
// always fall back to the SQL default `null`, which no subtype id can ever equal.
function isSubtypeEligible(
  subtypes: ReadonlyArray<{ id: number; partnerType: string; isActive: boolean }>,
  partnerSubtypeId: number | null,
  partnerType: string,
  currentSubtypeId: number | null = null,
) {
  return partnerSubtypeId === null || subtypes.some(s => s.id === partnerSubtypeId && s.partnerType === partnerType && (s.isActive || s.id === currentSubtypeId));
}

test("required scenarios 1-8: update may only keep its OWN current inactive subtype -- never swap to a different inactive one, and partner_type changes void that carve-out", () => {
  const subtypes = [
    { id: 5, partnerType: "alcohol", isActive: false },  // Partner's current subtype
    { id: 8, partnerType: "alcohol", isActive: true },
    { id: 9, partnerType: "alcohol", isActive: false },  // a *different* inactive subtype
    { id: 20, partnerType: "food", isActive: true },
  ];

  // 1. create_v4 (no current-subtype arg) + inactive -> reject
  assert.equal(isSubtypeEligible(subtypes, 5, "alcohol"), false);
  // 2. review_supplier_alias_v4 create_partner branch (same 2-arg call, no current-subtype id) + inactive -> reject
  assert.equal(isSubtypeEligible(subtypes, 5, "alcohol"), false);
  // 3. update_v4: current inactive subtype resubmitted unchanged (5 -> 5) -> allow
  assert.equal(isSubtypeEligible(subtypes, 5, "alcohol", 5), true);
  // 4. update_v4: current inactive (5) -> a *different* inactive (9) -> reject
  assert.equal(isSubtypeEligible(subtypes, 9, "alcohol", 5), false);
  // 5. update_v4: current inactive (5) -> an active subtype (8) -> allow
  assert.equal(isSubtypeEligible(subtypes, 8, "alcohol", 5), true);
  // 6. update_v4: current inactive (5) -> null -> allow
  assert.equal(isSubtypeEligible(subtypes, null, "alcohol", 5), true);
  // 7. partner_type changed to "food" while resending the stale alcohol-only inactive id (5) -> reject
  assert.equal(isSubtypeEligible(subtypes, 5, "food", 5), false);
  // 8. partner_type changed to "food" + a valid active subtype of the NEW type (20) -> allow
  assert.equal(isSubtypeEligible(subtypes, 20, "food", 5), true);
});

test("V4 RPCs keep the same security pattern as V1/V2/V3: owner postgres, security definer, search_path, restricted execute", () => {
  const v4Block = migration.slice(migration.indexOf("create function public.business_partner_create_v4"), migration.indexOf("-- Subtype management"));
  assert.equal((v4Block.match(/security definer/g) ?? []).length, 3);
  assert.equal((v4Block.match(/owner to postgres/g) ?? []).length, 3);
  assert.equal((v4Block.match(/revoke all on function/g) ?? []).length, 3);
  assert.equal((v4Block.match(/grant execute on function/g) ?? []).length, 3);
  assert.doesNotMatch(v4Block, /grant execute[\s\S]*to (public|anon|authenticated)\b/);
});

test("15: valid, matching subtype input passes parsePartnerInput through unchanged", () => {
  assert.equal(parse({ partnerSubtypeId: 4 })?.partnerSubtypeId, 4);
  assert.equal(parse({ partnerSubtypeId: "4" })?.partnerSubtypeId, 4);
});

test("16: null subtype is always allowed", () => {
  assert.equal(parse({})?.partnerSubtypeId, null);
  assert.equal(parse({ partnerSubtypeId: null })?.partnerSubtypeId, null);
});

test("parser rejects non-safe-integer or non-positive subtype ids client-side, before the DB round-trip", () => {
  assert.equal(parse({ partnerSubtypeId: 0 }), null);
  assert.equal(parse({ partnerSubtypeId: -1 }), null);
  assert.equal(parse({ partnerSubtypeId: 1.5 }), null);
});

test("21: app mutations call the V4 RPC and forward p_partner_subtype_id", () => {
  assert.match(collectionApi, /business_partner_create_v4/);
  assert.match(detailApi, /business_partner_update_v4/);
  assert.match(aliasApi, /business_partner_review_supplier_alias_v4/);
  for (const source of [collectionApi, detailApi, aliasApi]) assert.match(source, /p_partner_subtype_id/);
});

// ===================== D. UI =====================

test("21/22/23: PartnerForm renders a full-width 중분류 select scoped to the current partnerType, resetting on partnerType change", () => {
  assert.match(partnerForm, /<BarField compact={slim} label={t\.subtype}>/);
  assert.match(partnerForm, /const subtypeOptions = partnerSubtypes\s*\n\s*\.filter\(subtype => subtype\.partnerType === value\.partnerType && \(subtype\.isActive \|\| subtype\.id === value\.partnerSubtypeId\)\)/);
  assert.match(partnerForm, /function changePartnerType\(partnerType: PartnerType\) \{/);
  assert.match(partnerForm, /partnerSubtypeId: stillValid \? value\.partnerSubtypeId : null/);
  assert.match(partnerForm, /onChange={event => changePartnerType\(event\.target\.value as PartnerType\)}/);
});

test("11: 거래처명/대분류 stay on one row, 중분류 is its own full-width row below (390px layout)", () => {
  const basicSection = partnerForm.slice(partnerForm.indexOf('<BarSection title={sectionLabels.basic}'), partnerForm.indexOf('<BarSection title={sectionLabels.payment}'));
  const nameFieldIdx = basicSection.indexOf("t.name");
  const typeFieldIdx = basicSection.indexOf("t.type");
  const subtypeFieldIdx = basicSection.indexOf("t.subtype");
  assert.ok(nameFieldIdx < typeFieldIdx && typeFieldIdx < subtypeFieldIdx);
  assert.match(basicSection, /<div style=\{\{ \.\.\.basicGridStyle, gap: slim \? 8 : 10 \}\}>[\s\S]*<\/div>\s*\n\s*<BarField compact={slim} label={t\.subtype}>/);
});

test("13: KO/VI select labels show one language with fallback, never both languages concatenated", () => {
  assert.match(partnerForm, /formatPartnerSubtypeName\(subtype, lang\)/);
  assert.doesNotMatch(partnerForm, /nameKo\}\s*\/\s*\{subtype\.nameVi/);
});

test("24: Candidate create form also exposes a 중분류 select, defaulting to null (never auto-selected from dominantInventoryGroup)", () => {
  assert.match(candidateForm, /<BarField label={t\.subtype}>/);
  assert.match(candidateForm, /Never auto-selected from dominantInventoryGroup/);
  assert.match(candidatePage, /partnerSubtypeId: null/);
  assert.doesNotMatch(candidatePage, /dominantInventoryGroup[\s\S]{0,80}partnerSubtypeId/);
});

test("both forms share the same subtype-filter/reset logic (no per-page duplicate fallback implementation)", () => {
  for (const source of [partnerForm, candidateForm]) {
    assert.match(source, /import \{ formatPartnerSubtypeName, partnerText(, partnerTypeLabels)? \}|formatPartnerSubtypeName/);
    assert.doesNotMatch(source, /nameKo \|\| nameVi \|\| "미분류"/); // fallback must go through the shared helper, not be reimplemented inline
  }
});

// ===================== E. info grouping =====================

const subtypes = [
  { id: 1, partnerType: "alcohol" as const, sortOrder: 10 },
  { id: 2, partnerType: "alcohol" as const, sortOrder: 20 },
  { id: 3, partnerType: "food" as const, sortOrder: 10 },
];
const groupingPartners = [
  { name: "Carlsberg", partnerType: "alcohol" as const, partnerSubtypeId: 1, isActive: true },
  { name: "Phương", partnerType: "alcohol" as const, partnerSubtypeId: 1, isActive: true },
  { name: "Khang Mỹ", partnerType: "alcohol" as const, partnerSubtypeId: 2, isActive: true },
  { name: "Wow Spirit", partnerType: "alcohol" as const, partnerSubtypeId: null, isActive: true },
  { name: "Rượu Minh Anh", partnerType: "alcohol" as const, partnerSubtypeId: 999, isActive: true }, // stale/unknown subtype id
  { name: "Dabaco", partnerType: "food" as const, partnerSubtypeId: 3, isActive: true },
  { name: "Old Vendor", partnerType: "alcohol" as const, partnerSubtypeId: 1, isActive: false },
];

test("26/27: groups nest 대분류 -> 중분류(sort_order asc) -> Partner", () => {
  const groups = groupPartnersByTypeAndSubtype(groupingPartners, true, "ko", subtypes);
  const alcohol = groups.find(g => g.type === "alcohol")!;
  assert.deepEqual(alcohol.subgroups.map(g => g.subtype.id), [1, 2]);
});

test("28: 미분류 (null or stale/unresolvable subtype id) is always a trailing subgroup, never dropped", () => {
  const groups = groupPartnersByTypeAndSubtype(groupingPartners, true, "ko", subtypes);
  const alcohol = groups.find(g => g.type === "alcohol")!;
  assert.deepEqual(alcohol.unclassified.map(p => p.name).sort(), ["Rượu Minh Anh", "Wow Spirit"]);
});

test("29: partners within the same subtype are name-sorted", () => {
  const groups = groupPartnersByTypeAndSubtype(groupingPartners, true, "ko", subtypes);
  const alcohol = groups.find(g => g.type === "alcohol")!;
  const draftBeer = alcohol.subgroups.find(g => g.subtype.id === 1)!;
  assert.deepEqual(draftBeer.partners.map(p => p.name), ["Carlsberg", "Phương"]);
});

test("active/inactive filter still applies per Partner before grouping", () => {
  const inactiveGroups = groupPartnersByTypeAndSubtype(groupingPartners, false, "ko", subtypes);
  assert.deepEqual(inactiveGroups.find(g => g.type === "alcohol")?.subgroups[0]?.partners.map(p => p.name), ["Old Vendor"]);
});

test("26: info page renders the group -> subtype-divider -> row structure with the shared row/payment/tag formatting kept", () => {
  assert.match(infoPage, /groupPartnersByTypeAndSubtype\(partners, filter === "active", lang, partnerSubtypes\)/);
  assert.match(infoPage, /group\.subgroups\.map\(sub =>/);
  assert.match(infoPage, /<h3 className={styles\.subtypeDivider}>{formatPartnerSubtypeName\(sub\.subtype, lang\)}<\/h3>/);
  assert.match(infoPage, /group\.unclassified\.length > 0/);
  assert.match(infoPage, /<h3 className={styles\.subtypeDivider}>{formatPartnerSubtypeName\(null, lang\)}<\/h3>/);
  // 30/31: tag badge and payment summary formatting stay exactly as before
  assert.match(infoPage, /partner\.displayTag \? <span className={styles\.tagBadge}>{partner\.displayTag}<\/span> : null/);
  assert.match(infoPage, /formatPartnerPaymentSummary\(partner, lang\)/);
  assert.match(infoPage, /formatInventoryItemCount\(partner\.inventoryCount, partner\.activeInventoryCount, lang\)/);
});

test("15: subtype text-divider is a plain left-aligned label, not another colored header card", () => {
  assert.match(partnerStyles, /\.subtypeDivider\{margin:0;padding:0 2px;color:#6b7280;font-size:12px;font-weight:700;line-height:1\.3;text-align:left\}/);
  assert.doesNotMatch(partnerStyles, /\.subtypeDivider\{[^}]*border-left|\.subtypeDivider\{[^}]*background:#/);
});

// ===================== F. subtype management =====================

test("32/33/34: subtype create/update RPCs exist; either KO or VI name alone is accepted", () => {
  assert.match(migration, /create function public\.business_partner_subtype_create_v1/);
  assert.match(migration, /create function public\.business_partner_subtype_update_v1/);
  const createBody = migration.slice(migration.indexOf("create function public.business_partner_subtype_create_v1"), migration.indexOf("create function public.business_partner_subtype_update_v1"));
  const updateBody = migration.slice(migration.indexOf("create function public.business_partner_subtype_update_v1"), migration.indexOf("alter function public.business_partner_subtype_create_v1"));
  for (const body of [createBody, updateBody]) {
    assert.match(body, /if nullif\(btrim\(p_name_ko\), ''\) is null and nullif\(btrim\(p_name_vi\), ''\) is null then\s*\n\s*return jsonb_build_object\('status', 'invalid_name'\);/);
  }
});

test("35: both names blank is rejected by parsePartnerSubtypeCreateInput/UpdateInput", () => {
  assert.equal(parsePartnerSubtypeCreateInput({ partnerType: "alcohol", nameKo: "", nameVi: "  ", sortOrder: 0 }), null);
  assert.equal(parsePartnerSubtypeUpdateInput({ nameKo: null, nameVi: undefined, sortOrder: 0, isActive: true }), null);
});

test("34: either language alone is accepted by the parsers", () => {
  assert.deepEqual(parsePartnerSubtypeCreateInput({ partnerType: "alcohol", nameKo: "생맥주", nameVi: "", sortOrder: 10 }), { partnerType: "alcohol", nameKo: "생맥주", nameVi: null, sortOrder: 10 });
  assert.deepEqual(parsePartnerSubtypeCreateInput({ partnerType: "alcohol", nameKo: "", nameVi: "Bia tươi", sortOrder: 10 }), { partnerType: "alcohol", nameKo: null, nameVi: "Bia tươi", sortOrder: 10 });
});

test("36: deactivate goes through the same update RPC (isActive:false), not a separate delete", () => {
  assert.deepEqual(parsePartnerSubtypeUpdateInput({ nameKo: "생맥주", nameVi: null, sortOrder: 10, isActive: false }), { nameKo: "생맥주", nameVi: null, sortOrder: 10, isActive: false });
});

test("37: physical delete is added only in a follow-up migration and route", () => {
  assert.doesNotMatch(migration, /drop function public\.business_partner_subtype/i);
  assert.doesNotMatch(migration, /delete from public\.business_partner_subtypes/i);
  assert.match(deleteMigration, /create function public\.business_partner_subtype_delete_v1\(\s*\n\s*p_subtype_id bigint,\s*\n\s*p_actor_user_id bigint/);
  assert.match(subtypeUpdateApi, /export async function DELETE/);
});

test("unused subtype delete is race-safe and never nulls or rewrites Partner references", () => {
  assert.match(deleteMigration, /from public\.business_partner_subtypes[\s\S]*for update/);
  assert.match(deleteMigration, /if exists \(\s*\n\s*select 1 from public\.business_partners\s*\n\s*where partner_subtype_id = p_subtype_id/);
  assert.match(deleteMigration, /delete from public\.business_partner_subtypes\s*\n\s*where id = p_subtype_id/);
  assert.match(deleteMigration, /when foreign_key_violation then\s*\n\s*return jsonb_build_object\('status', 'in_use'\)/);
  assert.doesNotMatch(deleteMigration, /update public\.business_partners|partner_subtype_id\s*=\s*null/);
});

test("delete RPC handles authorization, missing rows, usage, and restricted execution deterministically", () => {
  assert.match(deleteMigration, /coalesce\(v_role, ''\) not in \('owner', 'master'\)[\s\S]*'status', 'forbidden'/);
  assert.match(deleteMigration, /v_subtype_id is null[\s\S]*'status', 'not_found'/);
  assert.match(deleteMigration, /'status', 'in_use'/);
  assert.match(deleteMigration, /'status', 'deleted'/);
  assert.match(deleteMigration, /security definer/);
  assert.match(deleteMigration, /set search_path = pg_catalog, public/);
  assert.match(deleteMigration, /owner to postgres/);
  assert.match(deleteMigration, /revoke all on function public\.business_partner_subtype_delete_v1\(bigint,bigint\) from public, anon, authenticated, service_role/);
  assert.match(deleteMigration, /grant execute on function public\.business_partner_subtype_delete_v1\(bigint,bigint\) to postgres, service_role/);
});

test("delete API performs an early reference check but delegates the final decision to the RPC", () => {
  assert.match(subtypeUpdateApi, /from\("business_partners"\)[\s\S]*count: "exact", head: true[\s\S]*eq\("partner_subtype_id", id\)/);
  assert.match(subtypeUpdateApi, /business_partner_subtype_delete_v1/);
  assert.match(subtypeUpdateApi, /SUBTYPE_IN_USE/);
});

test("23: code is server-generated (custom_<id>), never accepted as free client input", () => {
  const createBody = migration.slice(migration.indexOf("create function public.business_partner_subtype_create_v1"), migration.indexOf("create function public.business_partner_subtype_update_v1"));
  assert.match(createBody, /'custom_' \|\| v_id/);
  assert.doesNotMatch(createBody, /p_code/);
  assert.doesNotMatch(subtypeCreateApi, /p_code\b/);
  assert.doesNotMatch(subtypeCreateApi, /input\.code\b/);
});

test("22/38: partner_type and code are immutable on update -- an inactive subtype's own KO/VI/sort_order are preserved and editable", () => {
  const updateBody = migration.slice(migration.indexOf("create function public.business_partner_subtype_update_v1"), migration.indexOf("alter function public.business_partner_subtype_create_v1"));
  assert.doesNotMatch(updateBody, /partner_type = p_partner_type|code = p_code/);
  assert.match(updateBody, /name_ko = nullif\(btrim\(p_name_ko\), ''\),/);
  assert.match(updateBody, /is_active = p_is_active,/);
});

test("subtype management RPCs are owner/master gated with the same security pattern", () => {
  const mgmtBlock = migration.slice(migration.indexOf("-- Subtype management"));
  assert.equal((mgmtBlock.match(/security definer/g) ?? []).length, 2);
  assert.equal((mgmtBlock.match(/owner to postgres/g) ?? []).length, 2);
  assert.match(mgmtBlock, /coalesce\(v_role, ''\) not in \('owner', 'master'\)/g);
  assert.doesNotMatch(mgmtBlock, /grant execute[\s\S]*to (public|anon|authenticated)\b/);
});

test("subtype management UI reuses the shared BarSheet chrome, same as the existing add-partner dialog", () => {
  assert.match(subtypeManager, /import \{ BarField, BarSection, BarSegmentedControl, BarSheet, keepingInputStyle, primaryButtonStyle, secondaryButtonStyle \} from "@\/components\/bar\/keeping\/KeepingUi"/);
  assert.doesNotMatch(adminPage, /PartnerSubtypeManager|manageSubtypes|중분류 관리/);
  assert.match(infoPage, /import PartnerSubtypeManager from "@\/components\/PartnerSubtypeManager"/);
  assert.match(infoPage, /<PartnerSubtypeManager lang={lang} open={showSubtypeManager} partnerSubtypes={partnerSubtypes} onClose={\(\) => setShowSubtypeManager\(false\)} onReload={load}/);
  assert.match(infoPage, /중분류 관리/);
});

test("info-page subtype manager entry is a full-width mobile-safe action with an icon", () => {
  assert.match(infoPage, /<span aria-hidden="true">🗂️<\/span>/);
  assert.match(partnerStyles, /\.infoActions\{width:100%;min-width:0\}/);
  assert.match(partnerStyles, /\.infoActions button\{[^}]*box-sizing:border-box[^}]*grid-template-columns:auto minmax\(0,1fr\) auto[^}]*width:100%[^}]*min-width:0/);
});

test("partner create and detail update use an immediate success alert instead of a trailing success banner", () => {
  const partnerDetailPage = read("app/(protected)/admin/partners/[id]/page.tsx");
  for (const page of [adminPage, partnerDetailPage]) {
    assert.match(page, /alert\(t\.saved\)/);
    assert.doesNotMatch(page, /setMessage\(|styles\.notice/);
  }
});

test("food subtype labels are updated additively while stable identities remain intact", () => {
  assert.match(foodSubtypeMigration, /where lower\(btrim\(code\)\) = 'dry_food'/);
  assert.match(foodSubtypeMigration, /name_ko = '건어물'/);
  assert.match(foodSubtypeMigration, /name_vi = 'Đồ khô'/);
  assert.doesNotMatch(foodSubtypeMigration, /set\s+code\s*=/i);
  assert.match(foodSubtypeMigration, /select 'general_food', 'food', '종합 식자재', 'Thực phẩm tổng hợp', 75, true/);
  assert.match(foodSubtypeMigration, /where not exists \([\s\S]*lower\(btrim\(code\)\) = 'general_food'/);
});

test("delete UI has a separate confirmation danger area, localized errors, and reloads without closing on failure", () => {
  assert.match(subtypeManager, /dangerTitle: "중분류 삭제"/);
  assert.match(subtypeManager, /deleteConfirm: "정말 이 중분류를 삭제하시겠습니까\?"/);
  assert.match(subtypeManager, /Không thể xóa vì có đối tác đang sử dụng danh mục phụ này/);
  assert.match(subtypeManager, /method: "DELETE"/);
  assert.match(subtypeManager, /if \(!response\.ok\) \{[\s\S]*setError[\s\S]*return;[\s\S]*\}\s*\n\s*await onReload\(\);\s*\n\s*setEditing\(null\)/);
});

// ===================== G. compatibility =====================

test("previously applied partner migrations remain byte-for-byte unchanged", () => {
  assert.equal(sha256("supabase/migrations/202608220001_create_business_partner_master.sql"), "fb894247d95313b3bf1dc8a64f0235860740d71b421228c1d6eec680480a754c");
  assert.equal(sha256("supabase/migrations/202608220002_add_inventory_supplier_candidates.sql"), "b0c2763eca694c5b50a84f923380c4a697a41c56720faff160195bb3cd96c8ac");
  assert.equal(sha256("supabase/migrations/202608220003_fix_supplier_alias_ignore_behavior.sql"), "4c07d19209b844e30c8525e3a76724efdd8801bf1d5ef3d28f87fcded36ea444");
  assert.equal(sha256("supabase/migrations/202608230001_add_business_partner_settlement_policy.sql"), "9fc2981b6f38ad783d6a2e9cfabe5c09f7db8b70b525e88874fa7c55314e91c3");
  assert.equal(sha256("supabase/migrations/202608230002_add_supplier_alias_candidate_archive.sql"), "755a20caf4090ee8d67690e9f1827647bf8ac186ccf072b52595f820ffe76c9b");
  assert.equal(sha256("supabase/migrations/202608230003_add_business_partner_default_fund_account.sql"), "bd4f41eff8f1decd3c6e37a65cafd833e69a7683bd2bb649a3bee750cae6d598");
  assert.equal(sha256("supabase/migrations/202608230004_fix_business_partner_fund_account_eligibility.sql"), "ccc6ea8e2086102f63fe5a39d66fd3febed541920e9306b8bbb20744cc1e9e2d");
  assert.equal(sha256("supabase/migrations/202608240001_add_business_partner_display_tag.sql"), "5560fd11011bb980647ef13d3401f45e3abd51e6e076529c42f66a98cd4692c3");
  assert.equal(sha256("supabase/migrations/202608240002_add_business_partner_subtypes.sql"), "5c0decda9e0109645da398aa5296035bf562832f8bcb05c16559c6333cf3db2e");
});

test("39: display_tag stays independent -- role separation from partner_subtype_id is preserved everywhere", () => {
  assert.match(partnerServer, /displayTag: row\.display_tag,/);
  assert.match(partnerServer, /partnerSubtypeId,/);
  // display_tag is only mentioned in this migration's own doc comments (to explain the role
  // split from partner_subtype_id) -- it is never ALTERed, UPDATEd, SELECTed, or read/written
  // by any RPC body here.
  assert.doesNotMatch(migration, /alter table public\.business_partners[\s\S]*display_tag/);
  assert.doesNotMatch(migration, /update[^;]*display_tag/i);
});

test("40: defaultFundAccount plumbing is untouched by this migration/route changes", () => {
  assert.match(partnerServer, /defaultFundAccountCode: defaultFundAccountId === null \? null : fundAccountCodeById\.get\(defaultFundAccountId\) \?\? null,/);
  for (const source of [collectionApi, detailApi, aliasApi]) assert.match(source, /p_default_fund_account_id/);
});

test("41: immediate/postpaid canonicalization in parsePartnerInput is untouched by adding partnerSubtypeId", () => {
  assert.deepEqual(parse({ paymentMode: "postpaid" }), { ...base, paymentMode: "postpaid", settlementMode: "ad_hoc" });
  assert.deepEqual(parse({ paymentMode: "postpaid", settlementMode: "scheduled", settlementRule: "net_days", defaultPaymentTermDays: 30 }), { ...base, paymentMode: "postpaid", settlementMode: "ad_hoc" });
});

test("42: Candidate archive/reactivate RPC and route are untouched by this feature", () => {
  assert.match(aliasApi, /business_partner_archive_supplier_alias_v1/);
  assert.doesNotMatch(migration, /business_partner_archive_supplier_alias/);
});

test("43: V1/V2/V3 create/update/review-alias function bodies remain in their own original migrations, unedited", () => {
  const oldPartnerMigration = read("supabase/migrations/202608220001_create_business_partner_master.sql");
  const settlementMigration = read("supabase/migrations/202608230001_add_business_partner_settlement_policy.sql");
  const fundAccountMigration = read("supabase/migrations/202608230003_add_business_partner_default_fund_account.sql");
  assert.match(oldPartnerMigration, /create function public\.business_partner_create_v1/);
  assert.match(settlementMigration, /create function public\.business_partner_create_v2/);
  assert.match(fundAccountMigration, /create function public\.business_partner_create_v3/);
});

test("API responses expose partnerSubtypeId/partnerSubtypeCode on each Partner and a partnerSubtypes master list, N+1-free", () => {
  assert.match(partnerServer, /partnerSubtypeId,\s*\n\s*partnerSubtypeCode: partnerSubtype\?\.code \?\? null,\s*\n\s*partnerSubtype,/);
  assert.match(partnerServer, /supabaseServer\.from\("business_partner_subtypes"\)\.select\("id,code,partner_type,name_ko,name_vi,sort_order,is_active"\)/);
  assert.match(partnerServer, /const \[partnerResult, mappingResult, ledgerResult, inventoryResult, fundAccountResult, subtypeResult\] = await Promise\.all\(\[/);
  assert.match(collectionApi, /partnerJson\(\{ ok: true, \.\.\.partnerData, supplierAliases \}\)/); // partnerSubtypes rides along via ...partnerData
  assert.match(detailApi, /partnerSubtypes: data\.partnerSubtypes/);
  assert.match(aliasApi, /partnerSubtypes: partnerData\.partnerSubtypes/);
});
