import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";// @ts-expect-error Node direct TS tests use explicit extension.
import{calculateBep}from"../lib/ledger/bep-core.ts";
const migration=readFileSync("supabase/migrations/202608210007_add_recurring_reserves_bep.sql","utf8"),bepSource=readFileSync("lib/ledger/bep.ts","utf8"),reserveApi=readFileSync("app/api/admin/ledger/reserves/route.ts","utf8"),reserveCore=readFileSync("lib/ledger/reserve-balances.ts","utf8"),ui=readFileSync("app/(protected)/admin/ledger/RecurringReserveBepPanel.tsx","utf8"),foundation=readFileSync("tests/ledger-v1-foundation.test.ts","utf8"),pos=readFileSync("tests/ledger-pos-sales.test.ts","utf8"),inventory=readFileSync("tests/ledger-inventory-candidates.test.ts","utf8"),payable=readFileSync("tests/ledger-payable-payments.test.ts","utf8"),meal=readFileSync("tests/ledger-meal-payroll.test.ts","utf8"),card=readFileSync("tests/ledger-card-settlements.test.ts","utf8");
test("monthly rent plan is seeded",()=>assert.match(migration,/'매장 임대료'.*60000000.*'monthly'/));
test("rent category is fixed",()=>assert.match(migration,/values\('임대료','expense','fixed'\)/));
test("60M monthly recognition uses plan amount",()=>assert.match(migration,/v_plan\.amount.*v_plan\.category_id/));
test("same month recurring source is idempotent",()=>assert.match(migration,/recurring:'\|\|v_plan\.id\|\|':'\|\|to_char\(p_month,'YYYY-MM'\)/));
test("annual payment is outside expense",()=>assert.match(migration,/'prepaid_expense_payment'/));
test("actual payment creates negative movement",()=>assert.match(migration,/v_id,p_fund_account_id,-p_amount/));
test("monthly recognition creates no movement",()=>assert.doesNotMatch(migration,/recurring_expense'[^;]+insert into public\.ledger_movements/i));
test("coverage link records period and paid amount",()=>assert.match(migration,/ledger_recurring_expense_payments\(recurring_plan_id,payment_transaction_id,covered_from,covered_to,paid_amount\)/));
test("plan effective period is month bounded",()=>assert.match(migration,/effective_from=date_trunc\('month',effective_from\)/));
test("plan drift updates open month with audit",()=>assert.match(migration,/recurring_expense_drift_updated/));
test("closed month correction extension is documented",()=>assert.match(migration,/future month closure uses correction/));
test("reserve allocate is supported",()=>assert.match(migration,/when'allocate'then amount/));
test("reserve release subtracts",()=>assert.match(migration,/when'release'then-amount/));
test("reserve consume subtracts",()=>assert.match(migration,/when'consume'then-amount/));
test("reserve adjustment keeps signed amount",()=>assert.match(migration,/else amount end/));
test("reserve creates no fund movement",()=>assert.doesNotMatch(migration,/ledger_create_reserve_entry_v1[\s\S]*?insert into public\.ledger_movements/));
test("reserve creates no profit transaction",()=>assert.doesNotMatch(migration,/ledger_create_reserve_entry_v1[\s\S]*?insert into public\.ledger_transactions/));
test("current reserve derives from entries",()=>assert.match(reserveCore,/entry\.entry_type === "allocate"/));
test("target remaining is derived",()=>assert.match(reserveApi,/Math\.max\(0, targetAmount - currentAmount\)/));
test("target date is nullable",()=>assert.match(migration,/target_date date null/));
test("free cash subtracts active reserves",()=>assert.match(reserveApi,/freeCash: liquidFunds - activeReserve/));
test("card clearing is excluded from liquid funds",()=>assert.match(reserveApi,/account\.code !== "card_clearing"/));
test("reserve is not double counted in P and L",()=>assert.doesNotMatch(bepSource,/ledger_reserve_entries/));
test("fixed cost uses fixed categories",()=>assert.match(bepSource,/cost_behavior==="fixed"/));
test("variable cost uses variable categories",()=>assert.match(bepSource,/cost_behavior==="variable"/));
test("rent monthly recognition is fixed input",()=>assert.match(migration,/'임대료','expense','fixed'/));
test("prepaid cash payment is excluded from BEP query",()=>assert.doesNotMatch(bepSource,/prepaid_expense_payment/));
test("contribution margin ratio",()=>{const r=calculateBep({referenceMonths:[{month:"2026-07",revenue:100,variableCost:40}],fixedCost:60,currentSales:0,remainingBusinessDays:1});assert.equal(r.contributionMarginRatio,.6)});
test("BEP formula",()=>{const r=calculateBep({referenceMonths:[{month:"2026-07",revenue:100,variableCost:40}],fixedCost:120,currentSales:0,remainingBusinessDays:1});assert.equal(r.bepRevenue,200)});
test("three month rolling average",()=>{const r=calculateBep({referenceMonths:[{month:"a",revenue:100,variableCost:40},{month:"b",revenue:100,variableCost:38},{month:"c",revenue:100,variableCost:40}],fixedCost:1,currentSales:0,remainingBusinessDays:1});assert.ok(Math.abs((r.variableCostRatio??0)-.393333)<.00001)});
test("two month fallback",()=>assert.equal(calculateBep({referenceMonths:[{month:"a",revenue:100,variableCost:40},{month:"b",revenue:100,variableCost:30}],fixedCost:1,currentSales:0,remainingBusinessDays:1}).referenceMonths.length,2));
test("one month fallback",()=>assert.equal(calculateBep({referenceMonths:[{month:"a",revenue:100,variableCost:40}],fixedCost:1,currentSales:0,remainingBusinessDays:1}).referenceMonths.length,1));
test("no data is unavailable",()=>assert.equal(calculateBep({referenceMonths:[],fixedCost:1,currentSales:0,remainingBusinessDays:1}).unavailableReason,"INSUFFICIENT_REVENUE"));
test("non-positive revenue is unavailable",()=>assert.equal(calculateBep({referenceMonths:[{month:"a",revenue:0,variableCost:1}],fixedCost:1,currentSales:0,remainingBusinessDays:1}).unavailableReason,"INSUFFICIENT_REVENUE"));
test("semi variable is classification needed",()=>assert.match(bepSource,/cost_behavior==="semi_variable"/));
test("POS sales alone is revenue",()=>assert.match(bepSource,/type==="sales"&&r\.source_type==="pos_sales_daily_payment"/));
test("other income is not BEP revenue",()=>assert.doesNotMatch(bepSource,/type==="income"/));
test("BEP gap",()=>assert.equal(calculateBep({referenceMonths:[{month:"a",revenue:100,variableCost:0}],fixedCost:100,currentSales:40,remainingBusinessDays:2}).gap,60));
test("BEP exceeded",()=>assert.equal(calculateBep({referenceMonths:[{month:"a",revenue:100,variableCost:0}],fixedCost:100,currentSales:140,remainingBusinessDays:2}).exceeded,40));
test("required daily sales",()=>assert.equal(calculateBep({referenceMonths:[{month:"a",revenue:100,variableCost:0}],fixedCost:100,currentSales:40,remainingBusinessDays:3}).requiredDailySales,20));
test("remaining days reuse Store Settings helper",()=>assert.match(bepSource,/resolveStoreClosedByDate/));
test("all management APIs use owner master gate",()=>{for(const file of["app/api/admin/ledger/bep/route.ts","app/api/admin/ledger/recurring-expenses/route.ts","app/api/admin/ledger/recurring-expenses/sync/route.ts","app/api/admin/ledger/recurring-expenses/payments/route.ts","app/api/admin/ledger/reserves/route.ts","app/api/admin/ledger/reserves/[id]/route.ts","app/api/admin/ledger/reserves/[id]/entries/route.ts"])assert.match(readFileSync(file,"utf8"),/requireLedgerActor/)});
test("Card Settlement regression remains",()=>assert.match(card,/card deposit registration RPC/));
test("Payroll regression remains",()=>assert.match(meal,/company cost parity/));
test("Payable regression remains",()=>assert.match(payable,/one payment allocates to multiple payables/));
test("Inventory regression remains",()=>assert.match(inventory,/purchase inventory log becomes a candidate/));
test("POS parity regression remains",()=>assert.match(pos,/shared helper preserves legacy bucket and total parity/));
test("Foundation P and L balance regression remains",()=>assert.match(foundation,/balances accumulate only confirmed signed movements/));
test("new tables enable RLS",()=>{for(const table of["ledger_recurring_expense_plans","ledger_recurring_expense_payments","ledger_reserve_plans","ledger_reserve_entries"])assert.match(migration,new RegExp(`${table} enable row level security`))});
test("browser CRUD and RPC execution are denied",()=>{assert.match(migration,/revoke all on table[\s\S]+from public,anon,authenticated,service_role/);assert.match(migration,/revoke all on function[\s\S]+from public,anon,authenticated/)});
test("UI exposes required dashboard",()=>{for(const label of["이번 달 임대료","임대료 준비금","Free Cash","BEP","실제 임대료 지급"])assert.match(ui,new RegExp(label))});
