import assert from "node:assert/strict";import {readFileSync} from "node:fs";import {join} from "node:path";import test from "node:test";
// @ts-expect-error Node strips TypeScript extensions in tests.
import {calculateInventoryPurchaseAmount} from "../lib/inventory/purchase-cost.ts";
const read=(p:string)=>readFileSync(join(process.cwd(),p),"utf8");const migration=read("supabase/migrations/202608210003_add_inventory_purchase_candidates.sql"),source=read("lib/ledger/inventory-candidates.ts"),monthly=read("app/api/inventory/monthly/route.ts"),sync=read("app/api/admin/ledger/inventory-candidates/sync/route.ts"),list=read("app/api/admin/ledger/candidates/route.ts"),resolve=read("app/api/admin/ledger/candidates/[id]/route.ts"),payables=read("app/api/admin/ledger/payables/route.ts"),page=read("app/(protected)/admin/ledger/InventoryCandidatePanel.tsx"),ledger=read("app/api/admin/ledger/route.ts"),pos=read("lib/sales/payment-summary.ts");
test("purchase amount uses existing quantity times price and three decimals",()=>assert.equal(calculateInventoryPurchaseAmount(1.2345,1000),1234.5));
test("purchase inventory log becomes a candidate row",()=>{assert.match(source,/normalizeInventoryReason\(log\.reason\) !== "purchase"/);assert.match(migration,/'inventory_purchase','inventory_purchase_log'/)});
test("non-purchase logs are ignored",()=>assert.match(source,/normalizeInventoryReason\(log\.reason\) !== "purchase"/));
test("zero and negative quantities are ignored",()=>{assert.equal(calculateInventoryPurchaseAmount(0,10),null);assert.equal(calculateInventoryPurchaseAmount(-1,10),null)});
test("one pending candidate per inventory log",()=>{assert.match(migration,/ledger_candidates_pending_source_unique/);assert.match(source,/inventory-log:\$\{log\.id\}/)});
test("changed pending source is superseded",()=>{assert.match(migration,/status='superseded'/);assert.match(migration,/source_fingerprint=v_fingerprint/)});
test("confirmed candidates are never overwritten",()=>assert.match(migration,/v_latest\.status='confirmed'.*continue/));
test("immediate resolution creates expense",()=>assert.match(migration,/insert into public\.ledger_transactions[\s\S]*'expense'/));
test("immediate resolution creates negative movement",()=>assert.match(migration,/p_resolution='immediate'[\s\S]*-v_candidate\.proposed_amount/));
test("candidate expense participates in profit",()=>assert.match(ledger,/\.in\("type", \["income", "expense", "sales"\]\)/));
test("payable resolution creates expense",()=>assert.match(migration,/p_resolution not in\('immediate','payable'\)/));
test("payable resolution creates no movement",()=>assert.match(migration,/if p_resolution='immediate' then insert into public\.ledger_movements[\s\S]*else insert into public\.ledger_payables/));
test("payable record is created and listed",()=>{assert.match(migration,/create table public\.ledger_payables/);assert.match(payables,/outstandingAmount/)});
test("payable requires an active party in DB and API input",()=>{assert.match(migration,/then return jsonb_build_object\('status','party_required'\)/);assert.match(resolve,/p_party_id: body\.partyId \|\| null/)});
test("dismiss sets status and writes audit",()=>{assert.match(migration,/status='dismissed'/);assert.match(migration,/'candidate_dismissed'/)});
test("dismiss does not create an expense",()=>assert.ok(migration.indexOf("if p_resolution='dismiss'")<migration.indexOf("insert into public.ledger_transactions")));
test("supplier remains in immutable snapshot",()=>assert.match(source,/supplier: log\.new_supplier/));
test("category mapping supplies the default",()=>{assert.match(migration,/ledger_inventory_category_mappings/);assert.match(migration,/ledger_category_id into v_category_id/)});
test("resolution is one atomic security-definer RPC",()=>{assert.match(resolve,/ledger_resolve_inventory_candidate_v1/);assert.match(migration,/security definer/);assert.doesNotMatch(resolve,/\.from\("ledger_(transactions|movements|payables)"\)/)});
test("all inventory ledger endpoints use owner-master server gate",()=>{for(const route of[sync,list,resolve,payables])assert.match(route,/requireLedgerActor\(\)/)});
test("inventory source is SELECT-only",()=>{assert.match(source,/\.from\("inventory_logs"\)[\s\S]*\.select/);assert.doesNotMatch(source,/\.from\("inventory_logs"\)\.(insert|update|delete|upsert)/)});
test("monthly inventory report reuses the same purchase helper",()=>assert.match(monthly,/calculateInventoryPurchaseAmount\(changeQuantity,purchasePrice\)/));
test("candidate UI exposes sync, three resolutions and source detail",()=>{for(const label of["재고 동기화","즉시 결제","외상 등록","장부 제외","Inventory log"])assert.match(page,new RegExp(label))});
test("candidate filters include month status and type",()=>{assert.match(list,/params\.get\("month"\)/);assert.match(list,/params\.get\("status"\)/);assert.match(list,/params\.get\("type"\)/)});
test("new tables have RLS and no browser grants",()=>{for(const table of["ledger_candidates","ledger_payables","ledger_payable_allocations","ledger_inventory_category_mappings","ledger_supplier_party_mappings"])assert.match(migration,new RegExp(`alter table public\\.${table} enable row level security`));assert.match(migration,/revoke all on table[\s\S]*from public,anon,authenticated,service_role/)});
test("POS helper and recognition behavior remain present",()=>{assert.match(pos,/export function buildPaymentSummary/);assert.match(ledger,/row\.type === "income" \|\| row\.type === "sales"/)});
