import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";

const migration = readFileSync("supabase/migrations/20260929125839_split_welfare_and_correct_historical_ledger_display.sql", "utf8");
const welfareIds = [1644, 1649, 1650, 1651, 1659, 1671, 1672, 1767];
const augustIds = [1104, 1110, 1111, 1446, 1447];

async function database(closeSeptember = false) {
  const db = new PGlite();
  await db.exec([
    "create table users(id bigint primary key, role text, is_active boolean, app_login_enabled boolean);",
    "create table ledger_categories(id bigint generated by default as identity primary key, name text, kind text, parent_id bigint, cost_behavior text, is_active boolean);",
    "create table ledger_parties(id bigint primary key, name text);",
    "create table ledger_fund_accounts(id bigint primary key, code text, type text);",
    "create table ledger_transactions(id bigint primary key, type text, status text, business_date date, amount numeric, category_id bigint, party_id bigint, source_type text, memo text, display_snapshot jsonb default '{}'::jsonb, source_snapshot jsonb default '{}'::jsonb, updated_at timestamptz default now());",
    "create table ledger_movements(id bigint primary key, transaction_id bigint, fund_account_id bigint, amount numeric);",
    "create table ledger_payables(id bigint primary key, expense_transaction_id bigint, original_amount numeric, party_id bigint);",
    "create table ledger_payable_allocations(id bigint primary key, payable_id bigint, payment_transaction_id bigint, allocated_amount numeric);",
    "create table ledger_audit_logs(id bigint generated always as identity primary key, actor_user_id bigint, action text, entity_type text, entity_id bigint, before_snapshot jsonb, after_snapshot jsonb, reason text);",
    "create table closed_months(month date primary key);",
    "create function ledger_month_is_closed_v1(p_month date) returns boolean language sql as $$ select exists(select 1 from closed_months where month=p_month) $$;",
    "insert into users values(1,'owner',true,true);",
    "insert into ledger_categories(id,name,kind,parent_id,cost_behavior,is_active) values(20,'인건비','expense',null,'none',true),(21,'보험·복리후생','expense',20,'fixed',true),(3,'임대료','expense',null,'fixed',true),(26,'설비·비품','expense',null,'none',true),(30,'기타 비용','expense',null,'none',true);",
    "insert into ledger_parties values(5,'Mega Market');",
    "insert into ledger_fund_accounts values(1,'store_cash','cash'),(2,'baba_corporate_bank','bank');",
    "insert into ledger_transactions(id,type,status,business_date,amount,category_id,source_type,memo) values(1104,'expense','confirmed','2026-08-10',1000,21,'legacy_sheet_detail','old welfare'),(1110,'expense','confirmed','2026-08-11',2000,21,'legacy_sheet_detail','old welfare'),(1111,'expense','confirmed','2026-08-12',3000,21,'legacy_sheet_detail','old welfare'),(1446,'expense','confirmed','2026-08-20',10000,21,'legacy_sheet_detail','bhxh'),(1447,'expense','confirmed','2026-08-21',20000,21,'legacy_sheet_detail','bhxh');",
    "insert into ledger_transactions(id,type,status,business_date,amount,category_id,source_type,memo,display_snapshot,source_snapshot) values(1767,'expense','confirmed','2026-09-06',515000,21,'manual','7~8일 직원 야유회용 시장 구매','{\"titleOverride\":\"야유회 돼지고기 구입\"}','{\"sheet\":\"September\"}');",
    "insert into ledger_transactions(id,type,status,business_date,amount,category_id,source_type,memo) values(1644,'expense','confirmed','2026-09-11',1000,21,'legacy_sheet_detail','구옌 조의금'),(1649,'expense','confirmed','2026-09-11',2000,21,'legacy_sheet_detail','회식'),(1650,'expense','confirmed','2026-09-11',3000,21,'legacy_sheet_detail','여행 숙박'),(1651,'expense','confirmed','2026-09-11',4000,21,'legacy_sheet_detail','여행 차량'),(1659,'expense','confirmed','2026-09-11',5000,21,'legacy_sheet_detail','Uyen 생일'),(1671,'expense','confirmed','2026-09-11',6000,21,'legacy_sheet_detail','직원 팁 추석'),(1672,'expense','confirmed','2026-09-11',7000,21,'legacy_sheet_detail','추석 월병'),(1800,'expense','confirmed','2026-09-08',8000,21,'manual','unlisted welfare'),(1801,'expense','confirmed','2026-09-08',1500,21,'manual','법인 보험료');",
    "insert into ledger_transactions(id,type,status,business_date,amount,category_id,party_id,source_type) values(931,'expense','confirmed','2026-09-11',11862000,30,5,'inventory_purchase_candidate');",
    "insert into ledger_transactions(id,type,status,business_date,amount,party_id,source_type,memo) values(1640,'payable_payment','confirmed','2026-09-11',11862000,5,'payable_payment','old memo');",
    "insert into ledger_transactions(id,type,status,business_date,amount,category_id,source_type,memo) values(1643,'expense','confirmed','2026-09-11',600,30,'manual','차액');",
    "insert into ledger_transactions(id,type,status,business_date,amount,category_id,source_type,memo) values(1657,'expense','confirmed','2026-09-11',2100000,3,'manual','pji thue msy loc');",
    "insert into ledger_movements values(1,1767,1,-515000),(2,1800,1,-8000),(3,1640,2,-11862000),(4,1643,2,-600),(5,1657,2,-2100000),(6,1644,1,-1000),(7,1649,1,-2000),(8,1650,1,-3000),(9,1651,1,-4000),(10,1659,1,-5000),(11,1671,1,-6000),(12,1672,1,-7000);",
    "insert into ledger_payables values(1,931,11862000,5);",
    "insert into ledger_payable_allocations values(1,1,1640,11862000);",
    "insert into closed_months values('2026-08-01');",
    "create function ledger_transaction_month_guard_v1() returns trigger language plpgsql as $$ begin if exists(select 1 from closed_months where month=date_trunc('month',old.business_date)::date) then raise exception 'LEDGER_MONTH_CLOSED'; end if; return new; end $$;",
    "create trigger ledger_transaction_month_guard before update on ledger_transactions for each row execute function ledger_transaction_month_guard_v1();",
  ].join("\n"));
  if (closeSeptember) await db.exec("insert into closed_months values('2026-09-01')");
  return db;
}

test("closed August remains untouched; exactly eight September rows move; Mega and equipment preserve accounting", async () => {
  const db = await database();
  try {
    const augustBefore = (await db.query("select * from ledger_transactions where id in (1104,1110,1111,1446,1447) order by id")).rows;
    const accountingBefore = (await db.query("select id,amount,business_date,source_snapshot from ledger_transactions order by id")).rows;
    const movementsBefore = (await db.query("select * from ledger_movements order by id")).rows;
    const allocationsBefore = (await db.query("select * from ledger_payable_allocations")).rows;
    await db.exec(migration);
    const categories = (await db.query("select * from ledger_categories order by id")).rows;
    const legacy = categories.find(row => row.id === 21);
    const insurance = categories.find(row => row.name === "보험");
    const welfare = categories.find(row => row.name === "복리후생");
    assert.equal(legacy.name, "보험·복리후생");
    assert.equal(legacy.is_active, false);
    for (const category of [insurance, welfare]) {
      assert.equal(category.is_active, true);
      assert.equal(category.parent_id, legacy.parent_id);
      assert.equal(category.cost_behavior, legacy.cost_behavior);
    }
    assert.deepEqual((await db.query("select * from ledger_transactions where id in (1104,1110,1111,1446,1447) order by id")).rows, augustBefore);
    const rows = (await db.query("select * from ledger_transactions order by id")).rows;
    const byId = id => rows.find(row => row.id === id);
    for (const id of augustIds) assert.equal(byId(id).category_id, 21);
    for (const id of welfareIds) assert.equal(byId(id).category_id, welfare.id);
    assert.equal(byId(1800).category_id, 21);
    assert.equal(byId(1801).category_id, 21);
    assert.equal((await db.query("select count(*)::int as n from ledger_transactions where category_id=$1", [welfare.id])).rows[0].n, 8);
    assert.equal(Number(byId(931).amount), 11862000);
    assert.equal(Number(byId(1640).amount), 11862000);
    assert.equal(byId(1640).display_snapshot.actualPaidAmount, 11862600);
    assert.equal(byId(1640).display_snapshot.paymentDifferenceAmount, 600);
    assert.equal(byId(1640).display_snapshot.linkedDifferenceTransactionId, 1643);
    assert.equal(Number(byId(1643).amount), 600);
    assert.equal(byId(1657).category_id, 26);
    assert.equal(byId(1657).display_snapshot.titleOverride, "정수기·필터기 임대");
    assert.deepEqual((await db.query("select id,amount,business_date,source_snapshot from ledger_transactions order by id")).rows, accountingBefore);
    assert.deepEqual((await db.query("select * from ledger_movements order by id")).rows, movementsBefore);
    assert.deepEqual((await db.query("select * from ledger_payable_allocations")).rows, allocationsBefore);
    assert.equal((await db.query("select count(*)::int as n from ledger_audit_logs")).rows[0].n, 13);
  } finally { await db.close(); }
});

test("closed September or changed Mega movement rolls back the entire migration", async () => {
  for (const closed of [true, false]) {
    const db = await database(closed);
    try {
      if (!closed) await db.exec("update ledger_movements set amount=-11861999 where transaction_id=1640");
      await assert.rejects(db.exec(migration), closed ? /HISTORICAL_LEDGER_DISPLAY_MONTH_CLOSED/ : /HISTORICAL_LEDGER_DISPLAY_MEGA_PRECONDITION_FAILED/);
      const legacy = (await db.query("select name,is_active from ledger_categories where id=21")).rows[0];
      assert.equal(legacy.name, "보험·복리후생");
      assert.equal(legacy.is_active, true);
      assert.equal((await db.query("select count(*)::int as n from ledger_audit_logs")).rows[0].n, 0);
    } finally { await db.close(); }
  }
});
