import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";

const migration = readFileSync("supabase/migrations/20260929090000_add_ledger_payroll_advance_payment.sql", "utf8");

// Minimal mirror of the production objects the RPC touches: same columns,
// (source_type, source_key) unique indexes, recognition policy, advance
// category check and the paid-month payroll lock (errcode 55000).
const schema = `
  create role anon; create role authenticated; create role service_role;
  create table public.users (
    id bigint primary key, name text, full_name text, username text not null, role text,
    is_active boolean not null default true, app_login_enabled boolean not null default true,
    is_system_account boolean not null default false, payroll_eligible_override boolean
  );
  create table public.ledger_fund_accounts (
    id bigint primary key, code text, type text not null default 'cash',
    is_active boolean not null default true, is_business_fund boolean not null default true
  );
  create table public.payroll_monthly_adjustments (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    payroll_month date not null, kind text not null check (kind in ('incentive','penalty','advance')),
    category text not null, amount numeric(16,0) not null check (amount >= 1),
    business_date date not null, reason text not null, note text,
    source_type text not null default 'manual', source_key text,
    created_by bigint not null, created_at timestamptz not null default now(), cancelled_at timestamptz,
    cancelled_by bigint, cancellation_reason text,
    constraint payroll_adjustment_cancel_audit check (
      (cancelled_at is null and cancelled_by is null and cancellation_reason is null)
      or (cancelled_at is not null and cancelled_by is not null and length(btrim(cancellation_reason)) > 0)),
    constraint payroll_monthly_adjustments_advance_category_check check ((kind = 'advance') = (category = 'advance')),
    constraint payroll_adjustment_business_month check (date_trunc('month', business_date)::date = payroll_month)
  );
  create unique index payroll_monthly_adjustments_source_unique on public.payroll_monthly_adjustments(source_type, source_key) where source_key is not null;
  create table public.paid_payroll_months (user_id bigint, payroll_month date);
  create function public.payroll_lock_paid_month_adjustments_v1() returns trigger language plpgsql as $$
  begin
    if exists(select 1 from public.paid_payroll_months p where p.user_id = new.user_id and p.payroll_month = new.payroll_month)
      then raise exception 'PAYROLL_ADJUSTMENT_LOCKED_FOR_PAID_EMPLOYEE' using errcode = '55000'; end if;
    return new;
  end $$;
  create trigger payroll_monthly_adjustments_paid_lock before insert or update on public.payroll_monthly_adjustments
    for each row execute function public.payroll_lock_paid_month_adjustments_v1();
  create table public.ledger_transactions (
    id bigint generated by default as identity primary key, operation_id uuid not null, type text not null,
    occurred_at timestamptz, business_date date not null, recognition_month date, amount numeric not null check (amount > 0),
    category_id bigint, party_id bigint, status text not null, source_type text not null, source_key text,
    source_snapshot jsonb not null default '{}'::jsonb, memo text, created_by bigint, confirmed_by bigint,
    source_fingerprint text, source_synced_at timestamptz, correction_of_id bigint references public.ledger_transactions(id),
    economic_effect_sign integer not null default 1 check (economic_effect_sign in (-1, 1)),
    constraint ledger_transaction_source_sync_metadata check (
      (source_type = 'manual' and source_fingerprint is null and source_synced_at is null)
      or (source_type <> 'manual' and source_fingerprint is not null and source_synced_at is not null)),
    constraint ledger_transaction_recognition_policy check (
      (type in ('income','expense','sales','expense_recognition') and recognition_month is not null and category_id is not null)
      or (type not in ('income','expense','sales','expense_recognition') and recognition_month is null))
  );
  create unique index ledger_transactions_source_key_unique on public.ledger_transactions(source_type, source_key) where source_key is not null;
  create table public.ledger_movements (
    id bigint generated by default as identity primary key,
    transaction_id bigint not null references public.ledger_transactions(id), fund_account_id bigint not null, amount numeric not null
  );
  create table public.ledger_audit_logs (
    id bigint generated by default as identity primary key, actor_user_id bigint, action text not null,
    entity_type text not null, entity_id bigint, before_snapshot jsonb, after_snapshot jsonb, reason text
  );
  create table public.closed_months (month date primary key);
  create function public.ledger_month_is_closed_v1(p_month date) returns boolean language sql as
    $$ select exists(select 1 from public.closed_months where month = p_month) $$;
  insert into public.users(id, name, username, role) values (1, 'Owner', 'owner', 'owner'), (4, 'Quan', 'quan', 'staff'), (10, 'Triem', 'triem', 'staff');
  insert into public.ledger_fund_accounts(id, code, type, is_business_fund) values
    (1, 'store_cash', 'cash', true), (2, 'baba_corporate_bank', 'bank', true),
    (4, 'card_clearing', 'card_clearing', false);
  -- Historical advance with the original key format and a payroll cost recognized once for the month.
  insert into public.ledger_transactions(operation_id, type, occurred_at, business_date, amount, status, source_type, source_key, memo)
    values (gen_random_uuid(), 'payroll_payment', '2026-09-02T05:00:00Z', '2026-09-02', 2000000, 'confirmed', 'manual', 'payroll-advance-payment:2026-09-02:user:4', 'historical');
  insert into public.ledger_transactions(operation_id, type, occurred_at, business_date, recognition_month, category_id, amount, status, source_type, source_key, source_fingerprint, source_synced_at)
    values (gen_random_uuid(), 'expense_recognition', '2026-09-30T05:00:00Z', '2026-09-30', '2026-09-01', 7, 9000000, 'confirmed', 'payroll_completed_batch', 'payroll-batch:2026-09', 'f', now());
  insert into public.users(id, name, username, role) values (2, 'Staff', 'staff', 'staff');
`;

const REQ_A = "11111111-1111-4111-8111-111111111111";
const REQ_B = "22222222-2222-4222-8222-222222222222";

async function setup() {
  const db = new PGlite();
  await db.exec(schema);
  await db.exec(migration);
  return db;
}

async function advance(db, requestId, { userId = 4, amount = 2_000_000, occurredAt = "2026-09-29T12:00:00+07:00", accountId = 1, memo = "Quan 급여 가불" } = {}) {
  const { rows } = await db.query(
    "select public.ledger_create_payroll_advance_payment_v1($1, $2, $3, $4, $5, $6, $7) as r",
    [requestId, userId, amount, occurredAt, accountId, memo, 1],
  );
  return rows[0].r;
}

async function counts(db) {
  const { rows } = await db.query(`select
    (select count(*)::int from public.payroll_monthly_adjustments) adjustments,
    (select count(*)::int from public.ledger_transactions where type = 'payroll_payment') payments,
    (select count(*)::int from public.ledger_movements) movements,
    (select count(*)::int from public.ledger_audit_logs) audits`);
  return rows[0];
}

test("one request creates adjustment + payroll_payment + movement + audit with request-scoped keys", async () => {
  const db = await setup();
  const result = await advance(db, REQ_A);
  assert.equal(result.status, "created");
  assert.equal(result.sourceKey, `payroll-advance-payment:2026-09-29:user:4:${REQ_A}`);
  assert.deepEqual(await counts(db), { adjustments: 1, payments: 2, movements: 1, audits: 1 });
  const adjustment = (await db.query("select user_id, payroll_month::text, kind, category, amount::int, business_date::text, source_key from public.payroll_monthly_adjustments")).rows[0];
  assert.deepEqual(adjustment, { user_id: 4, payroll_month: "2026-09-01", kind: "advance", category: "advance", amount: 2_000_000, business_date: "2026-09-29", source_key: `ledger-payroll-advance:${REQ_A}` });
  const tx = (await db.query("select type, recognition_month, category_id, party_id, source_type, source_snapshot from public.ledger_transactions where id = $1", [result.transactionId])).rows[0];
  assert.deepEqual({ ...tx, source_snapshot: undefined }, { type: "payroll_payment", recognition_month: null, category_id: null, party_id: null, source_type: "manual", source_snapshot: undefined });
  assert.equal(tx.source_snapshot.userId, 4);
  assert.equal(tx.source_snapshot.paymentKind, "advance");
  assert.equal(tx.source_snapshot.requestId, REQ_A);
  assert.equal(tx.source_snapshot.payrollAdjustmentId, result.payrollAdjustmentId);
  const movement = (await db.query("select fund_account_id::int, amount::int from public.ledger_movements where transaction_id = $1", [result.transactionId])).rows[0];
  assert.deepEqual(movement, { fund_account_id: 1, amount: -2_000_000 });
  const audit = (await db.query("select action from public.ledger_audit_logs where entity_id = $1", [result.transactionId])).rows[0];
  assert.equal(audit.action, "payroll_advance_payment_created");
  // The historical key format is left as it was.
  assert.equal((await db.query("select count(*)::int c from public.ledger_transactions where source_key = 'payroll-advance-payment:2026-09-02:user:4'")).rows[0].c, 1);
});

test("replaying the same requestId creates nothing new; reusing it for a different advance is a conflict", async () => {
  const db = await setup();
  const first = await advance(db, REQ_A);
  const replay = await advance(db, REQ_A.toUpperCase());
  assert.equal(replay.status, "duplicate");
  assert.equal(replay.transactionId, first.transactionId);
  assert.equal(replay.payrollAdjustmentId, first.payrollAdjustmentId);
  assert.deepEqual(await counts(db), { adjustments: 1, payments: 2, movements: 1, audits: 1 });
  assert.equal((await advance(db, REQ_A, { amount: 3_000_000 })).status, "request_conflict");
  assert.equal((await advance(db, REQ_A, { accountId: 2 })).status, "request_conflict");
  assert.deepEqual(await counts(db), { adjustments: 1, payments: 2, movements: 1, audits: 1 });
  assert.equal((await advance(db, "not-a-uuid")).status, "invalid_request_id");
});

test("same employee and same day with different requestIds creates two advances; totals add up", async () => {
  const db = await setup();
  const a = await advance(db, REQ_A, { amount: 2_000_000 });
  const b = await advance(db, REQ_B, { amount: 1_500_000 });
  assert.equal(a.status, "created");
  assert.equal(b.status, "created");
  assert.notEqual(a.transactionId, b.transactionId);
  // advanceAmount for the month = sum of the employee's active advance adjustments.
  const advanceAmount = (await db.query("select sum(amount)::int s from public.payroll_monthly_adjustments where user_id = 4 and payroll_month = '2026-09-01' and kind = 'advance' and cancelled_at is null")).rows[0].s;
  assert.equal(advanceAmount, 3_500_000);
  // P&L expense (recognition rows) is unchanged by the advances.
  const pnl = (await db.query("select sum(amount)::int s from public.ledger_transactions where type in ('expense', 'expense_recognition') and recognition_month = '2026-09-01'")).rows[0].s;
  assert.equal(pnl, 9_000_000);
  // Actual cash outflow rises only by the advances actually paid through the new path.
  const outflow = (await db.query("select -sum(amount)::int s from public.ledger_movements")).rows[0].s;
  assert.equal(outflow, 3_500_000);
});

test("any failure rolls back every row of the advance", async () => {
  const db = await setup();
  // Force the last write (audit) to fail: adjustment, payment and movement must disappear too.
  await db.exec(`create function public.fail_audit() returns trigger language plpgsql as $$
    begin raise check_violation using message = 'audit failed'; end $$;
    create trigger fail_audit before insert on public.ledger_audit_logs for each row execute function public.fail_audit();`);
  assert.equal((await advance(db, REQ_A)).status, "invalid_input");
  assert.deepEqual(await counts(db), { adjustments: 0, payments: 1, movements: 0, audits: 0 });
  await db.exec("drop trigger fail_audit on public.ledger_audit_logs");
  // Paid payroll month: the lock trigger fires on the adjustment and nothing is written.
  await db.exec("insert into public.paid_payroll_months values (4, '2026-09-01')");
  assert.equal((await advance(db, REQ_A)).status, "payroll_locked");
  assert.deepEqual(await counts(db), { adjustments: 0, payments: 1, movements: 0, audits: 0 });
  // Closed ledger month and ineligible employee are refused before any write.
  await db.exec("delete from public.paid_payroll_months; insert into public.closed_months values ('2026-09-01')");
  assert.equal((await advance(db, REQ_A)).status, "month_closed");
  assert.equal((await advance(db, REQ_B, { userId: 1 })).status, "employee_not_payroll_eligible");
  assert.deepEqual(await counts(db), { adjustments: 0, payments: 1, movements: 0, audits: 0 });
});

test("the function is callable only by service_role", async () => {
  const db = await setup();
  const { rows } = await db.query(`select
    has_function_privilege('anon', 'public.ledger_create_payroll_advance_payment_v1(text,bigint,numeric,timestamptz,bigint,text,bigint)', 'execute') anon,
    has_function_privilege('authenticated', 'public.ledger_create_payroll_advance_payment_v1(text,bigint,numeric,timestamptz,bigint,text,bigint)', 'execute') authenticated,
    has_function_privilege('service_role', 'public.ledger_create_payroll_advance_payment_v1(text,bigint,numeric,timestamptz,bigint,text,bigint)', 'execute') service_role`);
  assert.deepEqual(rows[0], { anon: false, authenticated: false, service_role: true });
});

async function cancel(db, transactionId, { reason = "잘못 입력", actor = 1 } = {}) {
  const { rows } = await db.query(
    "select public.ledger_cancel_payroll_advance_payment_v1($1, $2, $3) as r",
    [transactionId, reason, actor],
  );
  return rows[0].r;
}

const snapshotOf = async (db, id) => (await db.query(
  "select type, amount::int, source_type, source_key, status, business_date::text, memo from public.ledger_transactions where id = $1", [id])).rows[0];

test("cancel cancels the adjustment and appends one reversal; original, P&L and cash net are consistent", async () => {
  const db = await setup();
  const created = await advance(db, REQ_A, { accountId: 2 });
  const before = await snapshotOf(db, created.transactionId);
  const result = await cancel(db, created.transactionId, { reason: "  중복 입력  " });
  assert.equal(result.status, "cancelled");
  // Adjustment cancelled with actor and trimmed reason; it no longer counts toward advanceAmount.
  const adjustment = (await db.query("select cancelled_at is not null cancelled, cancelled_by::int, cancellation_reason from public.payroll_monthly_adjustments where id = $1", [created.payrollAdjustmentId])).rows[0];
  assert.deepEqual(adjustment, { cancelled: true, cancelled_by: 1, cancellation_reason: "중복 입력" });
  const advanceAmount = (await db.query("select coalesce(sum(amount), 0)::int s from public.payroll_monthly_adjustments where user_id = 4 and kind = 'advance' and cancelled_at is null")).rows[0].s;
  assert.equal(advanceAmount, 0);
  // Original preserved exactly, with its movement untouched.
  assert.deepEqual(await snapshotOf(db, created.transactionId), before);
  assert.deepEqual((await db.query("select fund_account_id::int, amount::int from public.ledger_movements where transaction_id = $1", [created.transactionId])).rows, [{ fund_account_id: 2, amount: -2_000_000 }]);
  // Exactly one reversal on the same date and fund account, restoring the balance.
  const reversals = (await db.query("select id::int, type, amount::int, economic_effect_sign, correction_of_id::int, source_type, source_key, business_date::text, recognition_month, category_id from public.ledger_transactions where correction_of_id = $1", [created.transactionId])).rows;
  assert.equal(reversals.length, 1);
  assert.deepEqual({ ...reversals[0], id: undefined }, {
    id: undefined, type: "payroll_payment", amount: 2_000_000, economic_effect_sign: -1, correction_of_id: created.transactionId,
    source_type: "payroll_advance_payment_reversal", source_key: `ledger-payroll-advance:${REQ_A}:reversal`,
    business_date: "2026-09-29", recognition_month: null, category_id: null,
  });
  assert.deepEqual((await db.query("select fund_account_id::int, amount::int from public.ledger_movements where transaction_id = $1", [reversals[0].id])).rows, [{ fund_account_id: 2, amount: 2_000_000 }]);
  assert.equal((await db.query("select sum(amount)::int s from public.ledger_movements where fund_account_id = 2")).rows[0].s, 0);
  // P&L unchanged.
  assert.equal((await db.query("select sum(amount)::int s from public.ledger_transactions where type in ('expense', 'expense_recognition')")).rows[0].s, 9_000_000);
  // Audit log for the cancellation.
  const audit = (await db.query("select entity_id::int, reason, before_snapshot ? 'transaction' has_before, after_snapshot->>'reversalTransactionId' reversal from public.ledger_audit_logs where action = 'payroll_advance_payment_cancelled'")).rows;
  assert.deepEqual(audit, [{ entity_id: created.transactionId, reason: "중복 입력", has_before: true, reversal: String(reversals[0].id) }]);
});

test("cancelling twice is idempotent and never writes a second reversal", async () => {
  const db = await setup();
  const created = await advance(db, REQ_A);
  const first = await cancel(db, created.transactionId);
  const second = await cancel(db, created.transactionId, { reason: "다시" });
  assert.equal(second.status, "already_cancelled");
  assert.equal(second.reversalTransactionId, first.reversalTransactionId);
  assert.equal((await db.query("select count(*)::int c from public.ledger_transactions where correction_of_id = $1", [created.transactionId])).rows[0].c, 1);
  assert.equal((await db.query("select count(*)::int c from public.ledger_audit_logs where action = 'payroll_advance_payment_cancelled'")).rows[0].c, 1);
});

test("closed ledger month and paid payroll month block the cancel with nothing written", async () => {
  const db = await setup();
  const created = await advance(db, REQ_A);
  const state = async () => (await db.query(`select
    (select count(*)::int from public.ledger_transactions where correction_of_id = ${created.transactionId}) reversals,
    (select count(*)::int from public.payroll_monthly_adjustments where cancelled_at is not null) cancelled,
    (select count(*)::int from public.ledger_audit_logs where action = 'payroll_advance_payment_cancelled') audits`)).rows[0];
  await db.exec("insert into public.closed_months values ('2026-09-01')");
  assert.equal((await cancel(db, created.transactionId)).status, "month_closed");
  assert.deepEqual(await state(), { reversals: 0, cancelled: 0, audits: 0 });
  await db.exec("delete from public.closed_months; insert into public.paid_payroll_months values (4, '2026-09-01')");
  assert.equal((await cancel(db, created.transactionId)).status, "payroll_locked");
  assert.deepEqual(await state(), { reversals: 0, cancelled: 0, audits: 0 });
});

test("only ledger-created advances can be cancelled, by owner/master, with a reason", async () => {
  const db = await setup();
  const created = await advance(db, REQ_A);
  const historical = (await db.query("select id::int from public.ledger_transactions where source_key = 'payroll-advance-payment:2026-09-02:user:4'")).rows[0].id;
  const payrollCost = (await db.query("select id::int from public.ledger_transactions where type = 'expense_recognition'")).rows[0].id;
  const payable = (await db.query("insert into public.ledger_transactions(operation_id, type, occurred_at, business_date, amount, status, source_type, source_key) values (gen_random_uuid(), 'payable_payment', now(), '2026-09-10', 500000, 'confirmed', 'manual', null) returning id::int")).rows[0].id;
  for (const id of [historical, payrollCost, payable]) assert.equal((await cancel(db, id)).status, "not_ledger_payroll_advance", String(id));
  assert.equal((await cancel(db, 999999)).status, "not_found");
  assert.equal((await cancel(db, created.transactionId, { reason: "   " })).status, "reason_required");
  assert.equal((await cancel(db, created.transactionId, { actor: 2 })).status, "forbidden");
  assert.equal((await db.query("select count(*)::int c from public.ledger_transactions where correction_of_id is not null")).rows[0].c, 0);
});

test("a failure during cancel rolls back the adjustment cancellation and the reversal", async () => {
  const db = await setup();
  const created = await advance(db, REQ_A);
  await db.exec(`create function public.fail_cancel_audit() returns trigger language plpgsql as $$
    begin if new.action = 'payroll_advance_payment_cancelled' then raise exception 'audit down'; end if; return new; end $$;
    create trigger fail_cancel_audit before insert on public.ledger_audit_logs for each row execute function public.fail_cancel_audit();`);
  await assert.rejects(cancel(db, created.transactionId), /audit down/);
  assert.equal((await db.query("select count(*)::int c from public.payroll_monthly_adjustments where cancelled_at is not null")).rows[0].c, 0);
  assert.equal((await db.query("select count(*)::int c from public.ledger_transactions where correction_of_id is not null")).rows[0].c, 0);
  assert.equal((await db.query("select count(*)::int c from public.ledger_movements where amount > 0")).rows[0].c, 0);
});

test("the cancel function is callable only by service_role", async () => {
  const db = await setup();
  const signature = "public.ledger_cancel_payroll_advance_payment_v1(bigint,text,bigint)";
  const { rows } = await db.query(`select has_function_privilege('anon', '${signature}', 'execute') anon,
    has_function_privilege('authenticated', '${signature}', 'execute') authenticated,
    has_function_privilege('service_role', '${signature}', 'execute') service_role`);
  assert.deepEqual(rows[0], { anon: false, authenticated: false, service_role: true });
});

test("card_clearing (and any non-business or inactive fund) cannot fund an advance; nothing is written", async () => {
  const db = await setup();
  // Active in production, but not a business fund: must be refused.
  assert.equal((await advance(db, REQ_A, { accountId: 4 })).status, "invalid_accounts");
  assert.deepEqual(await counts(db), { adjustments: 0, payments: 1, movements: 0, audits: 0 });
  assert.equal((await db.query("select count(*)::int c from public.ledger_transactions where source_key like '%' || $1", [REQ_A])).rows[0].c, 0);
  // Guard each condition independently.
  await db.exec("insert into public.ledger_fund_accounts(id, type, is_business_fund) values (6, 'card_clearing', true), (7, 'bank', false)");
  await db.exec("insert into public.ledger_fund_accounts(id, type, is_active) values (8, 'cash', false)");
  for (const accountId of [6, 7, 8, 999]) assert.equal((await advance(db, REQ_A, { accountId })).status, "invalid_accounts", String(accountId));
  assert.deepEqual(await counts(db), { adjustments: 0, payments: 1, movements: 0, audits: 0 });
  // A real business fund still works.
  assert.equal((await advance(db, REQ_A, { accountId: 2 })).status, "created");
});
