import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import ts from 'typescript';
const require=createRequire(import.meta.url);
function fixture(){
 const feeName='\uce74\ub4dc \uc815\uc0b0 \ucc28\uc561';
 const tx=(id,type,date,recognition,amount,source,movements,category='POS')=>({id,type,business_date:date,recognition_month:recognition,amount,status:'confirmed',economic_effect_sign:1,source_type:source,source_key:source==='pos_sales_daily_payment'?'pos:'+date+':card':null,category:{name:category},movements});
 const tables={ledger_transactions:[tx(1,'sales','2026-09-20','2026-09-01',100000000,'pos_sales_daily_payment',[{fund_account_id:1,amount:100000000}]),tx(2,'card_settlement_deposit','2026-09-25',null,95000000,'card_settlement_deposit',[{fund_account_id:1,amount:-95000000},{fund_account_id:2,amount:95000000}])],ledger_fund_accounts:[{id:1,code:'card_clearing',type:'card_clearing',display_name:'Card',is_active:true},{id:2,code:'baba_corporate_bank',type:'bank',display_name:'Bank',is_active:true}],ledger_card_reconciliations:[{id:1,status:'auto_allocated',deposit_date:'2026-09-25',deposit_amount:95000000,matched_gross_amount:95000000,difference_amount:0}],ledger_card_reconciliation_lines:[{id:1,pos_card_transaction_id:1,reconciliation_id:1,allocated_gross_amount:95000000,reconciliation:{status:'auto_allocated',deposit_date:'2026-09-25'}}],ledger_card_fee_closures:[],ledger_card_fee_allocation_lines:[],ledger_month_closures:[]};
 const field=(row,key)=>key.split('.').reduce((v,k)=>v?.[k],row);
 const db={from(table){const filters=[];let start=0,end=999;const rows=()=> (tables[table]??[]).filter(row=>filters.every(f=>f(row)));const q={select(){return q;},order(){return q;},range(a,b){start=a;end=b;return q;},eq(k,v){filters.push(r=>field(r,k)===v);return q;},neq(k,v){filters.push(r=>field(r,k)!==v);return q;},lt(k,v){filters.push(r=>field(r,k)<v);return q;},lte(k,v){filters.push(r=>field(r,k)<=v);return q;},in(k,v){filters.push(r=>v.includes(field(r,k)));return q;},or(value){if(table==='ledger_transactions'){const match=value.match(/recognition_month\.eq\.([^,]+),business_date\.lt\.(.+)/);filters.push(r=>r.recognition_month===match[1]||r.business_date<match[2]);}return q;},maybeSingle(){return Promise.resolve({data:rows()[0]??null,error:null});},limit(n){return Promise.resolve({data:rows().slice(0,n),error:null});},then(resolve,reject){return Promise.resolve({data:rows().slice(start,end+1),error:null}).then(resolve,reject);}};return q;},rpc(){return Promise.resolve({data:{status:'ok',canClose:true,blockers:[],warnings:[]},error:null});}};
 const deps={'server-only':{},'node:crypto':require('node:crypto'),'@/lib/supabase/server':{supabaseServer:db},'@/lib/ledger/server':{requireLedgerActor:async()=>({actor:{id:1}}),ledgerJson:(body,status=200)=>Response.json(body,{status})}};
 function load(path){const mod={exports:{}};new Function('require','module','exports',ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(name=>name in deps?deps[name]:require('../'+name.replace(/^@\//,'')+'.ts'),mod,mod.exports);return mod.exports;}
 deps['@/lib/ledger/card-settlement-data']=load('lib/ledger/card-settlement-data.ts');const snapshot=load('lib/ledger/month-close.ts');deps['@/lib/ledger/month-close']=snapshot;const route=load('app/api/admin/ledger/month-close/route.ts');
 function confirm(){tables.ledger_transactions.push(tx(3,'card_settlement_deposit','2026-10-02',null,2850000,'card_settlement_deposit',[{fund_account_id:1,amount:-2850000},{fund_account_id:2,amount:2850000}]),tx(4,'expense_recognition','2026-10-02','2026-09-01',2150000,'card_fee_month_close',[{fund_account_id:1,amount:-2150000}],feeName));tables.ledger_card_reconciliation_lines.push({id:2,pos_card_transaction_id:1,reconciliation_id:2,allocated_gross_amount:2850000,reconciliation:{status:'auto_allocated',deposit_date:'2026-10-02'}});tables.ledger_card_fee_closures.push({id:1,fee_month:'2026-09-01',fee_amount:2150000,status:'confirmed',confirmed_at:'2026-10-02T05:00:00Z',confirmed_by:1,expense_transaction_id:4,finalization_business_date:'2026-10-02'});tables.ledger_card_fee_allocation_lines.push({id:1,closure_id:1,pos_card_transaction_id:1,allocated_fee_amount:2150000,closure:tables.ledger_card_fee_closures[0]});}
 function cancel(){tables.ledger_card_fee_closures[0].status='cancelled';const reversal=structuredClone(tables.ledger_transactions[3]);reversal.id=5;reversal.economic_effect_sign=-1;reversal.source_type='card_fee_month_close_reversal';reversal.movements[0].amount=2150000;tables.ledger_transactions.push(reversal);}
 return {tables,snapshot,route,confirm,cancel};
}
test('real snapshot builder and closed GET preserve September holdings/hash, suppress expected fee drift, and recognize no October fee',async()=>{
 const f=fixture();const stored=await f.snapshot.buildMonthCloseSnapshot('2026-09');const hash=f.snapshot.snapshotHash(stored);f.tables.ledger_month_closures.push({id:1,month:'2026-09-01',status:'closed',revision:1,summary_snapshot:structuredClone(stored),snapshot_hash:hash});const original=structuredClone(f.tables.ledger_month_closures);f.confirm();
 const september=await f.snapshot.buildMonthCloseSnapshot('2026-09'),october=await f.snapshot.buildMonthCloseSnapshot('2026-10');assert.deepEqual(september.funds,stored.funds);assert.equal(september.card.unsettledGross,stored.card.unsettledGross);assert.equal(september.operatingResult.operatingProfit,stored.operatingResult.operatingProfit-2150000);assert.equal(september.expense.total,2150000);assert.equal(october.expense.total,0);
 const response=await f.route.GET(new Request('http://localhost/api/admin/ledger/month-close?month=2026-09'));assert.equal(response.status,200);const body=await response.json();assert.equal(body.snapshotDrift,false);assert.equal(body.cardFeeStatus,'confirmed');assert.equal(body.finalizedOperatingResult.expense,2150000);assert.deepEqual(f.tables.ledger_month_closures,original);assert.equal(body.closure.snapshot_hash,hash);
 f.tables.ledger_transactions[1].movements[1].amount+=1;const drift=await (await f.route.GET(new Request('http://localhost/?month=2026-09'))).json();assert.equal(drift.snapshotDrift,true);assert.deepEqual(f.tables.ledger_month_closures,original);
});

test('automatic fee cancellation has no net historical expense or error snapshot drift',async()=>{
 const f=fixture(),stored=await f.snapshot.buildMonthCloseSnapshot('2026-09');f.tables.ledger_month_closures.push({id:1,month:'2026-09-01',status:'closed',summary_snapshot:structuredClone(stored),snapshot_hash:f.snapshot.snapshotHash(stored)});const original=structuredClone(f.tables.ledger_month_closures);f.confirm();f.cancel();
 const summary=await f.snapshot.buildMonthCloseSnapshot('2026-09');assert.deepEqual(summary.funds,stored.funds);assert.equal(summary.expense.total,0);assert.equal((await f.snapshot.buildMonthCloseSnapshot('2026-10')).expense.total,0);
 const response=await (await f.route.GET(new Request('http://localhost/?month=2026-09'))).json();assert.equal(response.snapshotDrift,false);assert.deepEqual(f.tables.ledger_month_closures,original);
});
