import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{join}from"node:path";import test from"node:test";
// @ts-expect-error Node strips TypeScript extensions in tests.
import{calculateCurrentMealAllowanceCost,selectMealAllowancePolicyAt}from"../lib/payroll/meal-allowance.ts";
const read=(p:string)=>readFileSync(join(process.cwd(),p),"utf8"),source=read("lib/ledger/employee-costs.ts"),migration=read("supabase/migrations/202608210005_add_ledger_meal_payroll_sync.sql"),mealRoute=read("app/api/admin/ledger/meal-candidates/sync/route.ts"),payrollRoute=read("app/api/admin/ledger/payroll/sync/route.ts"),resolve=read("app/api/admin/ledger/candidates/[id]/route.ts"),drill=read("app/api/admin/ledger/transactions/[id]/employee-cost-drilldown/route.ts"),page=read("app/(protected)/admin/ledger/InventoryCandidatePanel.tsx"),ledger=read("app/api/admin/ledger/route.ts"),overview=read("lib/payroll/overview.ts"),mealServer=read("lib/payroll/meal-allowance-server.ts"),payable=read("supabase/migrations/202608210004_add_ledger_payable_payments.sql"),inventory=read("supabase/migrations/202608210003_add_inventory_purchase_candidates.sql"),pos=read("lib/sales/payment-summary.ts");
const mealInput={attendanceDays:[{userId:1,workDate:"2026-08-20"}],users:new Map([[1,{hireDate:null,terminationDate:null}]]),eligibilityVersionsByUser:new Map([[1,[{id:1,userId:1,isEligible:true,effectiveFrom:"2026-08-01",revision:1}]]]),policyVersions:[{id:1,dailyAmount:30000,effectiveFrom:"2026-08-01",revision:1}]};
test("checked-in employee is included",()=>assert.equal(calculateCurrentMealAllowanceCost(mealInput).totalAmount,30000));
test("employee without check-in day is excluded",()=>assert.equal(calculateCurrentMealAllowanceCost({...mealInput,attendanceDays:[]}).totalAmount,0));
test("meal-ineligible employee is excluded",()=>{const input={...mealInput,eligibilityVersionsByUser:new Map([[1,[{id:1,userId:1,isEligible:false,effectiveFrom:"2026-08-01",revision:1}]]])};assert.equal(calculateCurrentMealAllowanceCost(input).totalAmount,0)});
test("effective dated meal policy is selected",()=>assert.equal(selectMealAllowancePolicyAt([{id:1,dailyAmount:20000,effectiveFrom:"2026-07-01",revision:1},{id:2,dailyAmount:30000,effectiveFrom:"2026-08-01",revision:2}],"2026-08-20")?.dailyAmount,30000));
test("one meal candidate per business date",()=>assert.match(source,/sourceKey:`meal:\$\{date\}`/));
test("pending meal drift supersedes old candidate",()=>assert.match(migration,/status='superseded'/));
test("confirmed meal is not overwritten",()=>assert.match(migration,/v_existing\.status='confirmed'[\s\S]*source_drift_detected_at/));
test("meal total is sum of employee policy amounts",()=>{const input={...mealInput,attendanceDays:[{userId:1,workDate:"2026-08-20"},{userId:2,workDate:"2026-08-20"}],users:new Map([[1,{hireDate:null,terminationDate:null}],[2,{hireDate:null,terminationDate:null}]]),eligibilityVersionsByUser:new Map([[1,[{id:1,userId:1,isEligible:true,effectiveFrom:"2026-08-01",revision:1}]],[2,[{id:2,userId:2,isEligible:true,effectiveFrom:"2026-08-01",revision:1}]]])};assert.equal(calculateCurrentMealAllowanceCost(input).totalAmount,60000)});
test("meal immediate payment creates expense and movement",()=>assert.match(migration,/candidate_type='payroll_employee_payment'[\s\S]*else[\s\S]*'expense'[\s\S]*ledger_movements/));
test("meal payable creates expense without immediate movement",()=>assert.match(migration,/if p_resolution='immediate'.*ledger_movements.*else insert into public\.ledger_payables/));
test("meal dismissal remains available",()=>assert.match(migration,/p_resolution='dismiss'/));
test("meal ledger source reuses payroll meal selectors",()=>{assert.match(source,/selectMealAllowanceEligibilityVersionAt/);assert.match(source,/selectMealAllowancePolicyAt/);assert.match(mealServer,/calculateCurrentMealAllowanceCost/)});
test("meal drilldown parity sums daily amounts",()=>assert.match(drill,/reduce\(\(sum,row\)=>sum\+Number\(row\.daily_amount\),0\)/));
test("incomplete payroll batch creates no company-cost transaction",()=>assert.match(migration,/if not v_completed or v_amount<=0/));
test("completed batch creates company-cost recognition",()=>assert.match(migration,/'expense_recognition'/));
test("company cost uses actual_company_cost_total unchanged",()=>{assert.match(source,/actual_company_cost_total:Number\(batch\.actual_company_cost_total\)/);assert.match(source,/amount:Number\(batch\.actual_company_cost_total\)/)});
test("payroll recognition has no movement",()=>{assert.match(migration,/ledger_sync_payroll_company_cost_v1/);const block=migration.slice(migration.indexOf("ledger_sync_payroll_company_cost_v1"));assert.doesNotMatch(block,/insert into public\.ledger_movements/)});
test("payroll recognition participates in its payroll month P and L",()=>{assert.match(ledger,/"expense_recognition"/);assert.match(ledger,/row\.type === "expense" \|\| row\.type === "expense_recognition"/)});
test("employee payroll payment is not expense",()=>assert.match(migration,/v_type:='payroll_payment'/));
test("paid employee payment creates candidate",()=>assert.match(source,/payment_status==="paid"&&Number\(payment\.actual_paid_amount\)>0&&Boolean\(payment\.payment_date\)/));
test("unpaid employee payment is inactive",()=>assert.match(source,/const active=payment\.payment_status==="paid"/));
test("paid row without payment date is rejected as inactive",()=>assert.match(source,/&&Boolean\(payment\.payment_date\)/));
test("confirmed payroll payment creates selected-account movement",()=>assert.match(migration,/v_type:='payroll_payment'[\s\S]*-v_c\.proposed_amount/));
test("payroll candidate amount equals actual paid amount",()=>assert.match(source,/amount:Number\(payment\.actual_paid_amount\?\?0\)/));
test("employee payment source key prevents duplicates",()=>{assert.match(source,/payroll-payment:\$\{payment\.id\}/);assert.match(inventory,/ledger_candidates_pending_source_unique/)});
test("pending cancelled or changed payroll payment supersedes",()=>{assert.match(source,/active,snapshot/);assert.match(migration,/if not v_active then continue/)});
test("confirmed payroll payment records drift without overwrite",()=>assert.match(migration,/'candidate_confirmed_source_drift'/));
test("company cost parity API compares batch total",()=>assert.match(drill,/actual_company_cost_total\)===Number\(transaction\.amount\)/));
test("employee cash parity preserves actual paid snapshot",()=>assert.match(source,/actual_paid_amount:payment\.actual_paid_amount/));
test("insurance remittance never creates automatic movement",()=>{assert.match(source,/insurance_remittance_total/);assert.doesNotMatch(source,/ledger_movements/)});
test("Payroll and Attendance source access is SELECT only",()=>{assert.doesNotMatch(source,/\.from\("(payroll_|attendance_records)[^)]*\)\.(insert|update|delete|upsert)/);assert.match(source,/\.from\("attendance_records"\)\.select/)});
test("all meal payroll APIs use owner master gate",()=>{for(const route of[mealRoute,payrollRoute,resolve,drill])assert.match(route,/requireLedgerActor\(\)/)});
test("candidate UI includes all three source filters and syncs",()=>{for(const value of["inventory_purchase","employee_meal","payroll_employee_payment","meal-candidates/sync","payroll/sync"])assert.match(page,new RegExp(value))});
test("existing POS parity remains",()=>assert.match(pos,/export function buildPaymentSummary/));
test("existing Inventory candidate remains",()=>assert.match(inventory,/ledger_resolve_inventory_candidate_v1/));
test("existing Payable payment remains",()=>assert.match(payable,/ledger_pay_payables_v1/));
test("meal is not part of payroll net payout calculation",()=>{assert.doesNotMatch(overview,/mealAllowance.*netPayoutAmount/);assert.match(overview,/netPayoutAmount=preInsurancePayoutAmount-employeeInsuranceDeductionAmount/)});
