import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import test from 'node:test';
import { PGlite } from '@electric-sql/pglite';
import ts from 'typescript';
const require = createRequire(import.meta.url);
const { buildLedgerEntries } = require('../lib/ledger/entries.ts');
const migration = readFileSync('supabase/migrations/20261001131334_review_meal_source_drift_without_financial_changes.sql', 'utf8');
const fp = digit => digit.repeat(64);
async function database(original = 330000, effective = original, latest = 360000) {
  const db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create table public.users(id bigint primary key,role text,is_active boolean,app_login_enabled boolean);
    create table public.ledger_categories(id bigint primary key,name text,kind text);
    create table public.ledger_transactions(
      id bigint generated by default as identity primary key,operation_id uuid,type text,
      occurred_at timestamptz,business_date date,recognition_month date,amount numeric,
      category_id bigint,party_id bigint,status text,source_type text,source_key text,
      source_snapshot jsonb,source_fingerprint text,source_synced_at timestamptz,
      correction_of_id bigint,memo text,created_by bigint,confirmed_by bigint,economic_effect_sign int,
      display_snapshot jsonb not null default '{}'::jsonb
    );
    create table public.ledger_candidates(id bigint primary key,candidate_type text,source_type text,status text,
      resolved_transaction_id bigint,source_snapshot jsonb,source_drift_snapshot jsonb,source_drift_fingerprint text);
    create table public.ledger_movements(id bigint generated always as identity primary key,transaction_id bigint,fund_account_id bigint,amount numeric);
    create table public.ledger_audit_logs(id bigint generated always as identity primary key,
      actor_user_id bigint,action text,entity_type text,entity_id bigint,before_snapshot jsonb,after_snapshot jsonb,reason text);
    create table public.ledger_fund_accounts(id bigint primary key,code text,is_active boolean,is_business_fund boolean,active_from date,active_to date);
    create table public.closed_months(month date primary key);
    create function public.ledger_month_is_closed_v1(p_month date) returns boolean language sql as $$
      select exists(select 1 from public.closed_months where month=p_month) $$;
    insert into public.users values(1,'owner',true,true),(2,'staff',true,true),(3,'master',true,true);
    insert into public.ledger_categories values(7,'직원 식대','expense');
    insert into public.ledger_fund_accounts values(5,'store_cash',true,true,'2026-01-01',null);
  `);
  await db.query(`insert into ledger_transactions(id,type,business_date,recognition_month,amount,category_id,status,source_type,source_key,source_snapshot,source_fingerprint,economic_effect_sign,display_snapshot)
    values(2135,'expense','2026-09-30','2026-09-01',$1,7,'confirmed','attendance_meal_daily_candidate','candidate:7',$2,$3,1,'{"preserved":"display"}')`,
    [original,{ total_amount: original, employee_count: original / 30000 },fp('a')]);
  await db.query(`insert into ledger_candidates values(7,'employee_meal','attendance_meal_daily','confirmed',2135,$1,$2,$3)`,
    [{ total_amount: original, employee_count: original / 30000 },latest == null ? null : { total_amount: latest, employee_count: latest / 30000 },latest == null ? null : fp('b')]);
  await db.query('insert into ledger_movements(transaction_id,fund_account_id,amount) values(2135,5,$1)',[-original]);
  if (effective !== original) {
    await db.query(`insert into ledger_transactions(id,type,business_date,recognition_month,amount,category_id,status,source_type,correction_of_id,source_snapshot,economic_effect_sign)
      values(2147,'expense','2026-09-30','2026-09-01',$1,7,'confirmed','ledger_correction',2135,'{"adjustmentType":"employee_meal"}',$2)`,[Math.abs(effective-original),effective>original?1:-1]);
    await db.query('insert into ledger_movements(transaction_id,fund_account_id,amount) values(2147,5,$1)',[original-effective]);
  }
  await db.exec(migration);
  return db;
}
async function save(db, amount, reason = 'Actual expenditure checked', actor = 1) {
  return (await db.query('select public.ledger_adjust_open_meal_transaction_v1(2135,$1,$2,$3) as result',[amount,reason,actor])).rows[0].result;
}
async function counts(db) {
  return (await db.query(`select (select count(*)::int from ledger_transactions) as transactions,
    (select count(*)::int from ledger_movements) as movements,(select count(*)::int from ledger_audit_logs) as audits`)).rows[0];
}
async function entry(db) {
  const transactions = (await db.query('select *,business_date::text as business_date,recognition_month::text as recognition_month,occurred_at::text as occurred_at from ledger_transactions')).rows;
  const candidate = (await db.query('select * from ledger_candidates where id=7')).rows[0];
  return buildLedgerEntries(transactions,[],new Map(),[{
    resolvedTransactionId:2135,sourceSnapshot:candidate.source_snapshot,
    sourceDriftSnapshot:candidate.source_drift_snapshot,sourceDriftFingerprint:candidate.source_drift_fingerprint,
  }]).find(row=>row.transactionId===2135);
}
test('production 360 + manual 30 / latest 360 is non-economic drift without resaving',async()=>{
  const db=await database(360000,390000,360000);
  try {
    const before=await counts(db);
    const row=await entry(db);
    assert.equal(row.requiresCorrection,false);
    assert.equal(row.originalAmount,360000);
    assert.equal(row.adjustmentAmount,30000);
    assert.equal(row.effectiveAmount,390000);
    assert.equal(row.adjustmentCount,1);
    assert.equal((await save(db,390000)).status,'unchanged');
    assert.deepEqual(await counts(db),before);
  } finally { await db.close(); }
});
test('economic drift review creates exactly one +60 correction, then a new fingerprint reopens review',async()=>{
  const db=await database();
  try {
    assert.equal((await entry(db)).requiresCorrection,true);
    const original=(await db.query('select * from ledger_transactions where id=2135')).rows[0];
    const candidateBefore=(await db.query('select * from ledger_candidates where id=7')).rows[0];
    const before=await counts(db);
    const result=await save(db,390000);
    assert.equal(result.status,'created');
    assert.equal(result.economicDelta,60000);
    assert.equal(result.storeCashMovement,-60000);
    assert.equal((await counts(db)).transactions,before.transactions+1);
    assert.equal((await counts(db)).movements,before.movements+1);
    const correction=(await db.query('select * from ledger_transactions where correction_of_id=2135')).rows;
    assert.equal(correction.length,1);
    assert.equal(Number(correction[0].amount),60000);
    assert.equal(Number(correction[0].economic_effect_sign),1);
    assert.equal(correction[0].source_snapshot.reviewedSourceDriftFingerprint,fp('b'));
    assert.equal((await entry(db)).effectiveAmount,390000);
    assert.equal((await entry(db)).requiresCorrection,false);
    const after=(await db.query('select * from ledger_transactions where id=2135')).rows[0];
    assert.deepEqual({...after,display_snapshot:original.display_snapshot},original);
    assert.equal(after.display_snapshot.preserved,'display');
    assert.deepEqual((await db.query('select * from ledger_candidates where id=7')).rows[0],candidateBefore);
    const stable=await counts(db);
    assert.equal((await save(db,390000)).status,'unchanged');
    assert.deepEqual(await counts(db),stable);
    await db.query('update ledger_candidates set source_drift_snapshot=$1,source_drift_fingerprint=$2 where id=7',[{total_amount:370000},fp('c')]);
    assert.equal((await entry(db)).requiresCorrection,true);
  } finally { await db.close(); }
});
test('maintaining current amount reviews genuine drift with metadata and audit only, idempotently',async()=>{
  const db=await database(330000,390000,360000);
  try {
    assert.equal((await entry(db)).requiresCorrection,true);
    const before=await counts(db);
    const movementsBefore=(await db.query('select * from ledger_movements order by id')).rows;
    assert.equal((await save(db,390000,'Keep verified sheet actual',3)).status,'reviewed');
    assert.deepEqual(await counts(db),{...before,audits:before.audits+1});
    assert.deepEqual((await db.query('select * from ledger_movements order by id')).rows,movementsBefore);
    const metadata=(await db.query('select display_snapshot from ledger_transactions where id=2135')).rows[0].display_snapshot;
    assert.equal(metadata.mealSourceDriftReviewedFingerprint,fp('b'));
    assert.ok(metadata.mealSourceDriftReviewedAt);
    const audit=(await db.query('select * from ledger_audit_logs')).rows[0];
    assert.equal(Number(audit.actor_user_id),3);
    assert.equal(audit.reason,'Keep verified sheet actual');
    assert.equal(audit.action,'meal_source_drift_reviewed');
    assert.equal(audit.after_snapshot.currentDriftFingerprint,fp('b'));
    assert.equal(audit.after_snapshot.finalAmount,390000);
    assert.equal(audit.after_snapshot.economicDelta,0);
    assert.equal((await entry(db)).requiresCorrection,false);
    assert.equal((await save(db,390000)).status,'unchanged');
    assert.deepEqual(await counts(db),{...before,audits:before.audits+1});
    // Same latest total, new attendance fingerprint: requires a fresh review.
    await db.query('update ledger_candidates set source_drift_fingerprint=$1 where id=7',[fp('c')]);
    assert.equal((await entry(db)).requiresCorrection,true);
  } finally { await db.close(); }
});
test('source equals effective, or no drift: no review and unchanged creates no records',async()=>{
  for (const latest of [330000,null]) {
    const db=await database(330000,330000,latest);
    try {
      const before=await counts(db);
      assert.equal((await entry(db)).requiresCorrection,false);
      assert.equal((await save(db,330000)).status,'unchanged');
      assert.deepEqual(await counts(db),before);
    } finally { await db.close(); }
  }
});
test('decreases, fractional amounts, authorization, blank reason, month locks and service-only grants remain intact',async()=>{
  const db=await database(330000,390000,null);
  try {
    assert.equal((await save(db,330000,'   ')).status,'reason_required');
    assert.equal((await save(db,330000,'Unauthorized',2)).status,'forbidden');
    const result=await save(db,300000.125);
    assert.equal(result.status,'created');
    assert.equal(result.economicDelta,-89999.875);
    assert.equal(result.storeCashMovement,89999.875);
    assert.equal((await entry(db)).effectiveAmount,300000.125);
    for (const role of ['anon','authenticated','service_role']) {
      const allowed=(await db.query(`select has_function_privilege($1,'public.ledger_adjust_open_meal_transaction_v1(bigint,numeric,text,bigint)','EXECUTE') as allowed`,[role])).rows[0].allowed;
      assert.equal(allowed,role==='service_role');
    }
    await db.exec("insert into closed_months values('2026-09-01')");
    const before=await counts(db);
    assert.equal((await save(db,300000.125)).status,'original_month_closed');
    assert.deepEqual(await counts(db),before);
  } finally { await db.close(); }
});
// Actual API handler: reviewed is a successful 200, blank reasons never reach RPC.
const apiSource=readFileSync('app/api/admin/ledger/transactions/[id]/meal-adjust/route.ts','utf8');
function apiFixture(status) {
  const calls=[];const testModule={exports:{}};
  const deps={
    '@/lib/ledger/server':{ requireLedgerActor:async()=>({actor:{id:1}}),ledgerJson:(body,status=200)=>Response.json(body,{status}) },
    '@/lib/ledger/meal-adjust-input':require('../lib/ledger/meal-adjust-input.ts'),
    '@/lib/supabase/server':{supabaseServer:{rpc:async(name,args)=>{calls.push({name,args});return {data:{status},error:null};}}},
  };
  const code=ts.transpileModule(apiSource,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
  new Function('require','module','exports',code)(name=>deps[name],testModule,testModule.exports);
  return {calls,post:reason=>testModule.exports.POST(new Request('http://local/meal-adjust',{method:'POST',body:JSON.stringify({finalAmount:'390000',reason})}),{params:Promise.resolve({id:'2135'})})};
}
test('API accepts reviewed/unchanged/created and retains blank reason validation',async()=>{
  for (const status of ['reviewed','unchanged','created']) {
    const api=apiFixture(status);
    assert.equal((await api.post('   ')).status,400);
    assert.equal(api.calls.length,0);
    const response=await api.post(' Checked ');
    assert.equal(response.status,status==='created'?201:200);
    assert.equal((await response.json()).result.status,status);
    assert.equal(api.calls.length,1);
    assert.equal(api.calls[0].args.p_reason,'Checked');
  }
});

test('same amount without drift succeeds unchanged even when store_cash is unavailable', async () => {
  const db = await database(330000,330000,null);
  try {
    await db.exec('update ledger_fund_accounts set is_active=false');
    const before = await counts(db);
    const original = (await db.query('select * from ledger_transactions where id=2135')).rows[0];
    assert.equal((await save(db,330000)).status,'unchanged');
    assert.deepEqual(await counts(db),before);
    assert.deepEqual((await db.query('select * from ledger_transactions where id=2135')).rows[0],original);
  } finally { await db.close(); }
});

test('same amount with genuine drift succeeds reviewed without store_cash and creates no financial records', async () => {
  const db = await database(330000,390000,360000);
  try {
    await db.exec('update ledger_fund_accounts set is_active=false');
    const before = await counts(db);
    const movements = (await db.query('select * from ledger_movements order by id')).rows;
    assert.equal((await save(db,390000,'Keep actual',3)).status,'reviewed');
    assert.deepEqual(await counts(db),{...before,audits:before.audits+1});
    assert.deepEqual((await db.query('select * from ledger_movements order by id')).rows,movements);
    const original = (await db.query('select * from ledger_transactions where id=2135')).rows[0];
    assert.equal(Number(original.amount),330000);
    assert.equal(original.display_snapshot.mealSourceDriftReviewedFingerprint,fp('b'));
    assert.ok(original.display_snapshot.mealSourceDriftReviewedAt);
    const audit = (await db.query('select * from ledger_audit_logs')).rows[0];
    assert.equal(Number(audit.actor_user_id),3);
    assert.equal(audit.reason,'Keep actual');
    assert.equal(audit.after_snapshot.currentDriftFingerprint,fp('b'));
    assert.equal(audit.after_snapshot.finalAmount,390000);
    assert.equal(audit.after_snapshot.economicDelta,0);
    assert.equal((await entry(db)).requiresCorrection,false);
  } finally { await db.close(); }
});

test('financial change without store_cash fails without review metadata or audit, then succeeds when restored', async () => {
  const db = await database();
  try {
    await db.exec('update ledger_fund_accounts set is_active=false');
    const before = await counts(db);
    const original = (await db.query('select * from ledger_transactions where id=2135')).rows[0];
    assert.equal((await save(db,390000)).status,'store_cash_unavailable');
    assert.deepEqual(await counts(db),before);
    assert.deepEqual((await db.query('select * from ledger_transactions where id=2135')).rows[0],original);
    assert.equal((await entry(db)).requiresCorrection,true);
    await db.exec('update ledger_fund_accounts set is_active=true');
    const result = await save(db,390000);
    assert.equal(result.status,'created');
    assert.equal(result.economicDelta,60000);
    assert.equal(result.storeCashMovement,-60000);
    const after = await counts(db);
    assert.equal(after.transactions,before.transactions+1);
    assert.equal(after.movements,before.movements+1);
    assert.equal((await entry(db)).requiresCorrection,false);
  } finally { await db.close(); }
});

async function closeAdjustmentMonth(db) {
  // Keep the source month open and distinct from the adjustment month on any test date.
  await db.exec(`
    update ledger_transactions set
      recognition_month=(date_trunc('month',(now() at time zone 'Asia/Ho_Chi_Minh')-interval '3 hours')-interval '1 month')::date,
      business_date=(date_trunc('month',(now() at time zone 'Asia/Ho_Chi_Minh')-interval '3 hours')-interval '1 month')::date;
    insert into closed_months values(date_trunc('month',(now() at time zone 'Asia/Ho_Chi_Minh')-interval '3 hours')::date);
  `);
}

test('review-only and unchanged ignore a closed adjustment business month', async () => {
  for (const drift of [false,true]) {
    const db = await database(330000,330000,drift?360000:null);
    try {
      await closeAdjustmentMonth(db);
      const before = await counts(db);
      assert.equal((await save(db,330000)).status,drift?'reviewed':'unchanged');
      assert.deepEqual(await counts(db),{...before,audits:before.audits+(drift?1:0)});
      assert.equal((await entry(db)).requiresCorrection,false);
    } finally { await db.close(); }
  }
});

test('financial changes still fail for a closed adjustment month without leaving review metadata', async () => {
  const db = await database();
  try {
    await closeAdjustmentMonth(db);
    const before = await counts(db);
    const original = (await db.query('select * from ledger_transactions where id=2135')).rows[0];
    assert.equal((await save(db,390000)).status,'adjustment_business_month_closed');
    assert.deepEqual(await counts(db),before);
    assert.deepEqual((await db.query('select * from ledger_transactions where id=2135')).rows[0],original);
    assert.equal((await entry(db)).requiresCorrection,true);
  } finally { await db.close(); }
});

test('closed source month still blocks unchanged, reviewed and financial correction paths', async () => {
  for (const [latest,finalAmount] of [[null,330000],[360000,330000],[360000,390000]]) {
    const db = await database(330000,330000,latest);
    try {
      await db.exec("insert into closed_months values('2026-09-01'); update ledger_fund_accounts set is_active=false;");
      const before = await counts(db);
      const original = (await db.query('select * from ledger_transactions where id=2135')).rows[0];
      assert.equal((await save(db,finalAmount)).status,'original_month_closed');
      assert.deepEqual(await counts(db),before);
      assert.deepEqual((await db.query('select * from ledger_transactions where id=2135')).rows[0],original);
    } finally { await db.close(); }
  }
});

test('a downstream movement failure rolls back review metadata, audits and correction together', async () => {
  const db = await database();
  try {
    await db.exec(`create function reject_movement() returns trigger language plpgsql as $$
      begin raise exception 'TEST_MOVEMENT_REJECTED'; end $$;
      create trigger reject_movement before insert on ledger_movements for each row execute function reject_movement();`);
    const before = await counts(db);
    const original = (await db.query('select * from ledger_transactions where id=2135')).rows[0];
    await assert.rejects(save(db,390000),/TEST_MOVEMENT_REJECTED/);
    assert.deepEqual(await counts(db),before);
    assert.deepEqual((await db.query('select * from ledger_transactions where id=2135')).rows[0],original);
    assert.equal((await entry(db)).requiresCorrection,true);
  } finally { await db.close(); }
});
