import assert from "node:assert/strict";import{readFileSync}from"node:fs";import{join}from"node:path";import test from"node:test";
// @ts-expect-error Node strips TypeScript extensions in tests.
import{buildOldestFirstAllocations}from"../lib/ledger/payables.ts";
const read=(p:string)=>readFileSync(join(process.cwd(),p),"utf8"),migration=read("supabase/migrations/202608210004_add_ledger_payable_payments.sql"),pay=read("app/api/admin/ledger/payables/pay/route.ts"),dashboard=read("app/api/admin/ledger/payables/route.ts"),detail=read("app/api/admin/ledger/payables/[partyId]/route.ts"),party=read("app/api/admin/ledger/parties/route.ts"),mapping=read("app/api/admin/ledger/supplier-party-mappings/route.ts"),page=read("app/(protected)/admin/ledger/payables/page.tsx"),ledger=read("app/api/admin/ledger/route.ts"),inventoryMigration=read("supabase/migrations/202608210003_add_inventory_purchase_candidates.sql"),pos=read("lib/sales/payment-summary.ts");
test("unpaid payable can be fully paid",()=>assert.match(migration,/least\(v_remaining,v_outstanding\)/));
test("payable supports partial payment",()=>assert.match(migration,/'partially_paid'/));
test("partial payment changes status to partially paid",()=>assert.match(migration,/when v_outstanding=0 then 'paid' else 'partially_paid'/));
test("zero outstanding changes status to paid",()=>assert.match(migration,/when v_outstanding=0 then 'paid'/));
test("one payment allocates to multiple payables",()=>assert.match(migration,/for v_item in select value from jsonb_array_elements\(v_plan\)/));
test("one payable supports multiple payments",()=>{assert.match(inventoryMigration,/unique\(payable_id,payment_transaction_id\)/);assert.doesNotMatch(inventoryMigration,/unique\(payable_id\)/)});
test("oldest first allocation is stable",()=>assert.deepEqual(buildOldestFirstAllocations([{id:3,businessDate:"2026-08-10",outstandingAmount:4},{id:1,businessDate:"2026-08-01",outstandingAmount:3},{id:2,businessDate:"2026-08-05",outstandingAmount:5}],6),{allocations:[{payableId:1,allocatedAmount:3},{payableId:2,allocatedAmount:3}],unallocatedAmount:0}));
test("custom allocations are accepted and validated",()=>{assert.match(migration,/jsonb_typeof\(p_allocations\)<>'array'/);assert.match(pay,/p_allocations:body\.allocations\?\?null/)});
test("zero allocation is rejected",()=>assert.match(migration,/v_allocate<=0/));
test("allocation above current outstanding is rejected",()=>assert.match(migration,/v_allocate>v_outstanding/));
test("payables from another party are rejected",()=>assert.match(migration,/v_payable\.party_id<>p_party_id/));
test("allocation sum must equal payment amount",()=>assert.match(migration,/v_sum<>p_amount.*allocation_sum_mismatch/));
test("movement absolute amount equals payment amount",()=>assert.match(migration,/ledger_movements\(transaction_id,fund_account_id,amount\) values\(v_payment_id,p_fund_account_id,-p_amount\)/));
test("payment reduces existing fund balance through signed movement",()=>{assert.match(ledger,/sum \+ Number\(row\.amount\)/);assert.match(migration,/-p_amount/)});
test("payable payment never enters P and L",()=>{assert.match(migration,/'payable_payment'/);assert.match(ledger,/\.in\("type", \["income", "expense", "sales"\]\)/)});
test("payment transaction movement allocations and statuses share one RPC",()=>{assert.match(pay,/ledger_pay_payables_v1/);assert.doesNotMatch(pay,/\.from\("ledger_/);assert.match(migration,/insert into public\.ledger_transactions[\s\S]*insert into public\.ledger_movements[\s\S]*ledger_payable_allocations[\s\S]*update public\.ledger_payables/)});
test("payables lock in deterministic order",()=>{assert.match(migration,/order by t\.business_date,p\.id for update/);assert.match(migration,/order by p\.id for update/)});
test("status derives from allocation sum",()=>assert.match(migration,/original_amount-coalesce\(sum\(a\.allocated_amount\),0\)/));
test("party dashboard aggregates outstanding and dates",()=>{for(const field of["outstandingAmount","openCount","oldestDate","nearestDueDate","recentPaymentDate"])assert.match(dashboard,new RegExp(field))});
test("party detail returns payable and allocation payment history",()=>{assert.match(detail,/ledger_payable_allocations\(allocated_amount,payment_transaction_id\)/);assert.match(detail,/type","payable_payment/);assert.match(page,/지급 내역/)});
test("lower roles are rejected by the shared server gate",()=>{for(const route of[pay,dashboard,detail,party,mapping])assert.match(route,/requireLedgerActor\(\)/)});
test("party creation is owner-master RPC only",()=>{assert.match(party,/ledger_create_party_v1/);assert.match(migration,/ledger_create_party_v1[\s\S]*not in\('owner','master'\)/)});
test("supplier party mapping can be saved",()=>{assert.match(mapping,/ledger_upsert_supplier_party_mapping_v1/);assert.match(migration,/'supplier_party_mapping_saved'/)});
test("payment precision remains numeric 16 comma 3",()=>{assert.match(inventoryMigration,/allocated_amount numeric\(16,3\)/);assert.match(migration,/round\(p_amount,3\)<>p_amount/)});
test("payment audit includes actor transaction party fund allocations and before after",()=>{for(const value of["p_actor_user_id","v_payment_id","p_party_id","p_amount","p_fund_account_id","allocations","v_before","v_after"])assert.match(migration,new RegExp(value))});
test("payment UI previews oldest first",()=>{assert.match(page,/buildOldestFirstAllocations/);assert.match(page,/오래된 외상부터 배분/)});
test("inventory candidate regression remains",()=>assert.match(inventoryMigration,/ledger_resolve_inventory_candidate_v1/));
test("POS parity regression remains",()=>assert.match(pos,/export function buildPaymentSummary/));
