import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";
const migration=readFileSync("supabase/migrations/202608210006_add_ledger_card_settlements.sql","utf8"),api=readFileSync("app/api/admin/ledger/card-settlements/route.ts","utf8"),matchApi=readFileSync("app/api/admin/ledger/card-settlements/[id]/match/route.ts","utf8"),ui=readFileSync("app/(protected)/admin/ledger/card-settlements/page.tsx","utf8"),posMigration=readFileSync("supabase/migrations/202608210002_add_ledger_pos_sales_sync.sql","utf8"),posSource=readFileSync("lib/ledger/pos-sales.ts","utf8"),foundation=readFileSync("tests/ledger-v1-foundation.test.ts","utf8"),inventory=readFileSync("tests/ledger-inventory-candidates.test.ts","utf8"),payable=readFileSync("tests/ledger-payable-payments.test.ts","utf8"),meal=readFileSync("tests/ledger-meal-payroll.test.ts","utf8");
test("card deposit registration RPC",()=>assert.match(api,/ledger_create_card_deposit_v1/));
test("deposit subtracts card pending",()=>assert.match(migration,/v_transaction,v_clearing,-p_amount/));
test("deposit adds destination bank",()=>assert.match(migration,/v_transaction,p_destination_account_id,p_amount/));
test("card deposit is not income",()=>assert.match(migration,/values\(v_operation,'card_settlement_deposit'/));
test("new deposit is unmatched",()=>assert.match(migration,/default 'unmatched'/));
test("partial status is supported",()=>assert.match(migration,/else'partial'end/));
test("matched status is supported",()=>assert.match(migration,/status='matched'/));
test("one deposit supports several sales",()=>assert.match(migration,/jsonb_array_elements\(p_allocations\)/));
test("one sale supports several deposits",()=>assert.match(migration,/r.id<>v_rec.id/));
test("gross overallocation is rejected",()=>assert.match(migration,/gross_overallocated/));
test("allocations are keyed by reconciliation and sale",()=>assert.match(migration,/unique\(reconciliation_id,pos_card_transaction_id\)/));
test("gross below deposit cannot complete",()=>assert.match(migration,/gross_below_deposit/));
test("five million less 4.91 million is 90 thousand",()=>assert.equal(5_000_000-4_910_000,90_000));
test("difference expense is created",()=>assert.match(migration,/'expense_recognition'[\s\S]*v_diff/));
test("difference additionally subtracts pending",()=>assert.match(migration,/v_diff_tx,v_clearing,-v_diff/));
test("difference has one unique source key",()=>assert.match(migration,/card-reconciliation:'\|\|v_rec.id\|\|':difference/));
test("no fixed 1.8 percent exists",()=>assert.doesNotMatch(migration+api+ui,/1\.8\s*%|0\.018/));
test("rate uses completed reconciliation only",()=>assert.match(api,/r.status==="matched"/));
test("unmatched and partial do not enter rate",()=>assert.match(api,/completedDifference\/completedGross/));
test("card sales lock in id order",()=>assert.match(migration,/id=any\(v_ids\) order by id for update/));
test("matching is one atomic RPC",()=>assert.match(matchApi,/ledger_match_card_reconciliation_v1/));
test("pending balance is validated",()=>assert.match(migration,/insufficient_card_pending/));
test("POS card transaction is read only",()=>assert.doesNotMatch(migration,/update public\.ledger_transactions set[^;]+pos_sales_daily_payment/i));
test("POS source is never mutated",()=>assert.doesNotMatch(api+matchApi,/from\("pos_sales_[^"]+"\)\.(insert|update|delete)/));
test("all endpoints use owner master server gate",()=>assert.match(api+matchApi,/requireLedgerActor/));
test("POS parity remains",()=>assert.match(posSource,/loadPosLedgerParity/));
test("Inventory regression remains",()=>assert.match(inventory,/purchase inventory log becomes a candidate/));
test("Payable regression remains",()=>assert.match(payable,/one payment allocates to multiple payables/));
test("Meal Payroll regression remains",()=>assert.match(meal,/company cost parity/));
test("Foundation balance and profit regression remains",()=>assert.match(foundation,/balances accumulate only confirmed signed movements/));
test("card clearing mapping remains",()=>assert.match(posMigration,/\('card','card_clearing'\)/));
test("new tables enable RLS and deny browser CRUD",()=>{assert.match(migration,/ledger_card_reconciliations enable row level security/);assert.match(migration,/revoke all on table[^;]+from public,anon,authenticated,service_role/)});
test("RPC execution is service role only",()=>{assert.match(migration,/revoke all on function public\.ledger_match_card_reconciliation_v1[^;]+from public,anon,authenticated/);assert.match(migration,/grant execute on function public\.ledger_match_card_reconciliation_v1[^;]+to service_role/)});
test("audit preserves deposit and settlement facts",()=>{for(const fact of["depositTransactionId","bankAccountId","depositAmount","allocations","matchedGrossAmount","differenceAmount","beforePendingBalance","afterPendingBalance","status"])assert.match(migration,new RegExp(fact))});
