import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { PGlite } from "@electric-sql/pglite";

const sql = readFileSync("supabase/migrations/20260928225900_add_partner_subtype_emoji.sql", "utf8");

async function database() {
  const db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create table public.users(id bigint primary key, role text, is_active boolean, app_login_enabled boolean);
    insert into public.users values(1,'owner',true,true),(2,'staff',true,true);
    create table public.business_partner_subtypes(
      id bigint generated by default as identity primary key, code text not null unique,
      partner_type text not null, name_ko text, name_vi text, sort_order integer not null default 0,
      is_active boolean not null default true, updated_at timestamptz default now()
    );
    insert into public.business_partner_subtypes(id,code,partner_type,name_ko,name_vi) values
      (1,'meat','food','육류','Thịt'),(2,'vegetable_fruit','food','채소·과일','Rau củ'),
      (3,'dry_food','food','건어물','Đồ khô'),(4,'general_food','food','종합 식자재','Tổng hợp'),
      (5,'alcohol_other','alcohol','일반 주류(표시명 변경)','Rượu thông thường'),
      (6,'wine','alcohol','와인','Rượu vang');
    select setval('public.business_partner_subtypes_id_seq',99);
    create function public.business_partner_subtype_create_v1(text,text,text,integer,bigint)
      returns jsonb language sql as $$select '{}'::jsonb$$;
    create function public.business_partner_subtype_update_v1(bigint,text,text,integer,boolean,bigint)
      returns jsonb language sql as $$select '{}'::jsonb$$;
  `);
  await db.exec(sql);
  return db;
}

test("migration assigns only the requested existing subtype codes and preserves IDs", async () => {
  const db = await database();
  try {
    const rows = (await db.query("select id,code,name_ko,emoji from business_partner_subtypes order by id")).rows;
    assert.deepEqual(rows.map(row => [Number(row.id), row.code, row.name_ko, row.emoji]), [
      [1,"meat","육류","🥩"],[2,"vegetable_fruit","채소·과일","🥬"],[3,"dry_food","건어물","🦑"],
      [4,"general_food","종합 식자재",null],[5,"alcohol_other","일반 주류(표시명 변경)","🍺"],[6,"wine","와인",null],
    ]);
    const signatures = (await db.query("select proname,pronargs from pg_proc where proname in ('business_partner_subtype_create_v1','business_partner_subtype_update_v1') order by proname")).rows;
    assert.deepEqual(signatures.map(row => [row.proname,Number(row.pronargs)]), [
      ["business_partner_subtype_create_v1",6],["business_partner_subtype_update_v1",7],
    ]);
  } finally { await db.close(); }
});

test("create and update save optional emoji; old update calls preserve it", async () => {
  const db = await database();
  try {
    const created = (await db.query("select business_partner_subtype_create_v1('food','신규','Mới',80,1,'🍺') as result")).rows[0].result;
    assert.equal(created.status,"created");
    const id = Number(created.subtypeId);
    assert.equal((await db.query("select emoji from business_partner_subtypes where id=$1",[id])).rows[0].emoji,"🍺");
    assert.equal((await db.query("select business_partner_subtype_update_v1($1,'신규','Mới',81,true,1,'🥩') as result",[id])).rows[0].result.status,"updated");
    assert.equal((await db.query("select emoji from business_partner_subtypes where id=$1",[id])).rows[0].emoji,"🥩");
    await db.query("select business_partner_subtype_update_v1($1,'신규','Mới',82,true,1)",[id]);
    assert.equal((await db.query("select emoji from business_partner_subtypes where id=$1",[id])).rows[0].emoji,"🥩");
    await db.query("select business_partner_subtype_update_v1($1,'신규','Mới',82,true,1,null)",[id]);
    assert.equal((await db.query("select emoji from business_partner_subtypes where id=$1",[id])).rows[0].emoji,null);
    assert.equal((await db.query("select business_partner_subtype_update_v1($1,'신규','Mới',82,true,2,'🍾') as result",[id])).rows[0].result.status,"forbidden");
    assert.equal((await db.query("select code from business_partner_subtypes where id=$1",[id])).rows[0].code,created.code);
  } finally { await db.close(); }
});