import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const read=(file:string)=>fs.readFileSync(path.join(process.cwd(),file),"utf8");

test("insurance migration is append-only, private, snapshotted, and keeps v2 RPCs",()=>{const sql=read("supabase/migrations/202607310001_add_payroll_insurance_v5.sql");assert.match(sql,/create table public\.payroll_insurance_setting_versions/);assert.match(sql,/unique\(user_id,revision\)/);assert.match(sql,/enable row level security/);assert.match(sql,/revoke all on table public\.payroll_insurance_setting_versions from public,anon,authenticated,service_role/);assert.match(sql,/grant select,insert on table public\.payroll_insurance_setting_versions to service_role/);assert.doesNotMatch(sql,/grant[^;]*(update|delete)[^;]*payroll_insurance_setting_versions/i);assert.match(sql,/username in\('quyen','linh_h','uyen','nhon'\)/);assert.doesNotMatch(sql,/username\s*=\s*'mjk'/);assert.match(sql,/insurance_employee_deduction/);assert.match(sql,/create function public\.payroll_create_run_v3/);assert.match(sql,/create function public\.payroll_recalculate_run_v3/);assert.match(sql,/p_copy_manual_from_run_id/);assert.match(sql,/i\.item_type='manual'/);assert.match(sql,/where item_type='automatic' and category='insurance_employee_deduction'/);assert.doesNotMatch(sql,/drop function public\.payroll_.*_v2/);});

test("v6 APIs use v4 paths while v3 insurance functions remain",()=>{const create=read("app/api/admin/payroll/runs/route.ts"),run=read("app/api/admin/payroll/runs/[runId]/route.ts"),items=read("app/api/admin/payroll/runs/[runId]/employees/[employeeId]/items/route.ts"),reviews=read("app/api/admin/payroll/runs/[runId]/employees/[employeeId]/reviews/route.ts"),v6=read("supabase/migrations/202608010001_add_payroll_work_policy_penalties_v6.sql");assert.match(create,/payroll_create_run_v4/);assert.match(run,/payroll_recalculate_run_v4/);assert.match(items,/payroll_mutate_item_v4/);assert.match(reviews,/payroll_resolve_review_v4/);assert.match(v6,/payroll_transition_run_v3/);});

test("insurance is not folded into generic deductions and UI avoids double-counting company cost",()=>{const overview=read("lib/payroll/overview.ts"),card=read("components/payroll/CompensationCard.tsx"),page=read("app/(protected)/admin/payroll/page.tsx");assert.match(overview,/entry\.category!=="insurance_employee_deduction"/);assert.match(overview,/netPayoutAmount=preInsurancePayoutAmount-employeeInsuranceDeductionAmount/);assert.match(card,/employeeInsuranceDeductionAmount/);assert.match(card,/employerInsuranceHelp/);assert.match(page,/totalCompanyCostAmount/);assert.match(page,/payrollCostTableText/);assert.match(page,/projectionHelp/);});

test("insurance setting mutation is owner-master guarded and director account is excluded",()=>{const sql=read("supabase/migrations/202607310001_add_payroll_insurance_v5.sql"),api=read("app/api/admin/payroll/insurance/route.ts"),settings=read("app/(protected)/admin/payroll/settings/page.tsx");assert.match(sql,/perform public\.payroll_assert_actor_v2\(p_actor_user_id\)/);assert.match(sql,/username<>'mjk'/);assert.match(api,/requirePayrollActor/);assert.match(settings,/selected\.username\s*!==\s*"mjk"/);});

test("finalize and force-finalize cannot bypass stale v5 insurance snapshots",()=>{const sql=read("supabase/migrations/202607310001_add_payroll_insurance_v5.sql"),api=read("app/api/admin/payroll/runs/[runId]/route.ts"),v6=read("supabase/migrations/202608010001_add_payroll_work_policy_penalties_v6.sql");assert.match(sql,/create function public\.payroll_transition_run_v3/);assert.match(sql,/p_action in\('finalize','force_finalize'\)/);assert.match(sql,/PAYROLL_INSURANCE_SNAPSHOT_STALE/);assert.match(sql,/order by v\.effective_month desc,v\.revision desc limit 1/);assert.match(sql,/payroll_transition_run_v2/);assert.match(v6,/payroll_transition_run_v3/);assert.match(api,/payroll_transition_run_v4/);assert.match(api,/PAYROLL_INSURANCE_SNAPSHOT_STALE/);});

const transitionSql=()=>{const sql=read("supabase/migrations/202607310001_add_payroll_insurance_v5.sql");return sql.slice(sql.indexOf("create function public.payroll_transition_run_v3"),sql.indexOf("revoke all on function",sql.indexOf("create function public.payroll_transition_run_v3")));};
test("payment-day-only changes do not stale an insurance snapshot",()=>{const sql=transitionSql();assert.doesNotMatch(sql,/payment_day|payment_month_offset|v_settings\.updated_at|settingsUpdatedAt/);assert.match(sql,/perform public\.payroll_transition_run_v2/);});
test("employee rate changes stale the insurance snapshot",()=>{const sql=transitionSql();assert.match(sql,/employeeRateBp'\)::smallint is distinct from v_settings\.employee_insurance_rate_bp/);});
test("employer rate changes stale the insurance snapshot",()=>{const sql=transitionSql();assert.match(sql,/employerRateBp'\)::smallint is distinct from v_settings\.employer_insurance_rate_bp/);});
test("every director insurance value participates in stale detection",()=>{const sql=transitionSql();assert.match(sql,/enabled'\)::boolean is distinct from v_settings\.director_insurance_enabled/);assert.match(sql,/baseAmount'\)::numeric is distinct from v_settings\.director_insurance_base_amount/);assert.match(sql,/rateBp'\)::smallint is distinct from v_settings\.director_insurance_rate_bp/);});
test("recalculation captures current insurance settings before a later finalize",()=>{const sql=read("supabase/migrations/202607310001_add_payroll_insurance_v5.sql"),route=read("app/api/admin/payroll/runs/[runId]/route.ts"),v6=read("supabase/migrations/202608010001_add_payroll_work_policy_penalties_v6.sql");assert.match(sql,/payroll_recalculate_run_v3[\s\S]*v_insurance_snapshot:=coalesce\(p_source_snapshot->'insuranceSettings'/);assert.match(v6,/payroll_recalculate_run_v4[\s\S]*v_insurance_snapshot:=coalesce\(p_source_snapshot->'insuranceSettings'/);assert.match(route,/loadPayrollMonthSnapshot\([\s\S]*payroll_recalculate_run_v4/);assert.doesNotMatch(route,/rpc\("payroll_recalculate_run_v3"/);assert.match(route,/payroll_transition_run_v4/);assert.match(route,/payroll_transition_run_v3/);});
test("payment-day and insurance changes are blocked only by insurance values",()=>{const sql=transitionSql();assert.doesNotMatch(sql,/payment_day|payment_month_offset/);assert.match(sql,/employee_insurance_rate_bp|employer_insurance_rate_bp/);assert.match(sql,/PAYROLL_INSURANCE_SNAPSHOT_STALE/);});

test("v3 totals preserve all insurance reconciliation invariants without rerating",()=>{const sql=read("supabase/migrations/202607310001_add_payroll_insurance_v5.sql");assert.match(sql,/employee_insurance_deduction_amount=coalesce\(x\.employee_insurance_deduction,0\)/);assert.match(sql,/net_amount=coalesce\(x\.base_amount,0\)\+coalesce\(x\.additions,0\)-coalesce\(x\.non_insurance_deductions,0\)-coalesce\(x\.employee_insurance_deduction,0\)/);assert.match(sql,/total_company_cost_amount=x\.pre_insurance\+x\.employer_insurance\+/);assert.doesNotMatch(sql,/insurance_base_amount[^;]*\*[^;]*employee_insurance_rate_bp/);});

test("global settings PATCH reads current state and changes only supplied validated fields",()=>{const route=read("app/api/admin/payroll/settings/route.ts");assert.match(route,/select\(FIELDS\)\.eq\("id",1\)\.single\(\)/);assert.match(route,/if\("paymentDay" in body\)/);assert.match(route,/if\("employeeInsuranceRateBp" in \(body\?\?\{\}\)\)/);assert.match(route,/Number\.isInteger\(value\)/);assert.match(route,/Number\.isSafeInteger\(value\)/);assert.match(route,/updated_at:new Date\(\)\.toISOString\(\),updated_by:auth\.actor\.id/);});
