import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const read=(file:string)=>fs.readFileSync(path.join(process.cwd(),file),"utf8");
const migration=read("supabase/migrations/202608050001_add_employee_payment_batches.sql");
const payments=read("app/api/admin/payroll/payments/route.ts");
const adjustments=read("app/api/admin/payroll/adjustments/route.ts");
const overview=read("app/api/admin/payroll/overview/route.ts");
const page=read("app/(protected)/admin/payroll/page.tsx");
const detail=read("app/(protected)/admin/payroll/[runId]/page.tsx");
const card=read("components/payroll/CompensationCard.tsx");

test("migration adds isolated payment tables without changing the deployed ledger schema",()=>{assert.ok(migration.startsWith("begin;"));for(const table of["payroll_payment_batches","payroll_employee_payments","payroll_payment_audit_logs"])assert.match(migration,new RegExp(`create table public\\.${table}`));for(const legacy of["payroll_runs","payroll_run_employees","payroll_run_items","payroll_run_reviews","payroll_run_audit_logs"])assert.doesNotMatch(migration,new RegExp(`(?:drop|alter) table public\\.${legacy}`));assert.doesNotMatch(migration,/drop function/);assert.ok(migration.trimEnd().endsWith("commit;"))});
test("new schema has only paying/completed batches and immutable paid snapshots",()=>{assert.match(migration,/status in\('paying','completed'\)/);assert.match(migration,/payment_status in\('unpaid','paid'\)/);assert.match(migration,/unique\(payroll_batch_id,user_id\)/);for(const field of["employee_snapshot","part_snapshot","position_snapshot","calculation_snapshot","calculation_hash","calculated_net_amount","actual_paid_amount","difference_amount","difference_reason","payment_date","paid_by","paid_at","engine_version","common_settings_snapshot"])assert.match(migration,new RegExp(field));assert.match(migration,/difference_amount=actual_paid_amount-calculated_net_amount/)});
test("payment transaction freezes targets, locks concurrency, blocks duplicates and completes exactly on the last employee",()=>{assert.match(migration,/pg_advisory_xact_lock\(82118/);assert.match(migration,/where payroll_month=p_month for update/);assert.match(migration,/jsonb_array_elements\(p_targets\)/);assert.match(migration,/PAYROLL_EMPLOYEE_NOT_IN_BATCH/);assert.match(migration,/PAYROLL_EMPLOYEE_ALREADY_PAID/);assert.match(migration,/if v_paid=v_run\.target_employee_count then[\s\S]*status='completed'/);for(const action of["batch_started","employee_paid","batch_completed"])assert.match(migration,new RegExp(`'${action}'`))});
test("payment difference and cancellation policies are enforced inside RPCs",()=>{assert.match(migration,/p_actual_paid_amount<>p_calculated_net_amount[\s\S]*PAYROLL_PAYMENT_REASON_REQUIRED/);assert.match(migration,/PAYROLL_PAYMENT_CANCEL_REASON_REQUIRED/);assert.match(migration,/v_run\.status<>'paying'[\s\S]*PAYROLL_BATCH_COMPLETED/);assert.match(migration,/employee_payment_cancelled/);assert.match(migration,/before_snapshot,after_snapshot/)});
test("actual company cost restores employee insurance withheld from net pay",()=>{assert.match(migration,/actual_company_cost_total=x\.actual\+x\.employee_insurance\+x\.employer_insurance\+r\.director_insurance_amount/g)});
test("paid employee adjustments are locked only for the matching payroll month",()=>{assert.match(migration,/r\.payroll_month=new\.payroll_month and e\.user_id=new\.user_id and e\.payment_status='paid'/);assert.match(migration,/before insert or update on public\.payroll_monthly_adjustments/);assert.match(adjustments,/PAYROLL_ADJUSTMENT_LOCKED_FOR_PAID_EMPLOYEE[\s\S]*409/)});
test("server recomputes and hashes the current overview instead of trusting client amounts",()=>{assert.match(payments,/loadPayrollOverview\(month\)/);assert.match(payments,/payrollPaymentSnapshotHash\(calculationSnapshot\)/);assert.match(payments,/calculationHash!==expectedHash/);assert.match(payments,/PAYROLL_CALCULATION_STALE/);assert.match(payments,/p_calculated_net_amount:employee\.amounts\.netPayoutAmount/);assert.match(overview,/calculationHash/)});
test("first payment preflight reports every unavailable employee and sends no RPC first",()=>{assert.match(payments,/preflightFailures=existingBatch\?\[\]:overview\.employees\.flatMap/);assert.match(payments,/PAYROLL_BATCH_PREFLIGHT_FAILED/);assert.match(payments,/unavailableEmployeeCount:preflightFailures\.length/);assert.match(payments,/employeeName:item\.name,reasonCodes/);assert.ok(payments.indexOf("preflightFailures.length>0")<payments.indexOf('supabaseServer.rpc("payroll_pay_employee_v1"'));assert.match(migration,/PAYROLL_BATCH_PREFLIGHT_FAILED/)});
test("current and future months are blocked in API, RPC, and UI",()=>{assert.match(payments,/!isClosedPayrollMonth\(month\)[\s\S]*PAYROLL_MONTH_NOT_CLOSED/);assert.match(migration,/p_month>=date_trunc\('month',timezone\('Asia\/Ho_Chi_Minh',now\(\)\)\)::date[\s\S]*PAYROLL_MONTH_NOT_CLOSED/);assert.match(overview,/monthClosed:isClosedPayrollMonth\(month\)/);assert.match(card,/!monthClosed[\s\S]*급여 월 미종료/)});
test("employee card and read-only ledger expose bilingual payment flow without draft actions",()=>{for(const source of[page,detail])for(const removed of["급여 초안 생성","force_finalize","recalculate","mutate_item","resolve_review"])assert.doesNotMatch(source,new RegExp(removed));for(const label of["급여 지급","지급 내역 확인","지급 불가","미지급","지급완료","조정지급","Chi trả lương","Xem chi tiết chi trả"])assert.match(card,new RegExp(label));assert.match(page,/지급 중/);assert.match(page,/급여장부/);assert.match(detail,/calculation_snapshot/)});
test("header amount keeps the original resolver before and after payment",()=>{assert.match(card,/const headerAmount = getPayrollHeaderAmount\(employee, future\)/);assert.match(card,/>\s*\{header\}\s*<\/b>/);assert.doesNotMatch(card,/payment_status === "paid" \? formatVnd\(employee\.payment\.actual_paid_amount/)});
test("application routes use only new payment tables and legacy removal is deferred",()=>{for(const source of[overview,read("app/api/admin/payroll/runs/route.ts"),read("app/api/admin/payroll/runs/[runId]/route.ts")])assert.match(source,/payroll_(?:payment_batches|employee_payments|payment_audit_logs)/);assert.doesNotMatch(migration,/drop table|drop function/);assert.doesNotMatch(migration,/drop table public\.payroll_monthly_adjustments/)});
