import assert from "node:assert/strict";
import test from "node:test";
// @ts-expect-error Node's strip-types test runner requires the explicit extension.
import { buildPayrollSourceExport } from "../lib/payroll/source-export/build-export.ts";

function fixture(options?:{reviewCodes?:string[];contract?:boolean;extraStatus?:"approved"|"rejected"|"review_required"|"stale";taxReview?:boolean;unresolved?:boolean}){
  const contract=options?.contract===false?null:{id:10,userId:1,payType:"hourly",calculationBasis:"minute",baseSalary:35_000,fixedRaiseAmount:0,standardWorkdays:null,standardMinutesPerDay:300,timeBlockMinutes:1,roundingMode:"none",lateAdjustmentMode:"separate",earlyLeaveAdjustmentMode:"ignore",overtimeMode:"requires_approval",paidLeaveMode:"unpaid",effectiveFrom:"2026-08-01",effectiveTo:null,revision:2};
  const status=options?.extraStatus;
  const sourceFact={businessDate:"2026-08-09",attendanceRecordId:7,classification:options?.unresolved?"unresolved":"completed_work",recognizedAttendanceDay:!options?.unresolved,attendanceStatus:options?.unresolved?"unresolved":"done",approvalStatus:null,checkInAt:"2026-08-09T11:00:00Z",checkOutAt:options?.unresolved?null:"2026-08-09T16:00:00Z",sourceUpdatedAt:"2026-08-09T16:00:00Z",actualMinutes:options?.unresolved?null:300,scheduledMinutes:300,scheduledOverlapMinutes:300,lateMinutes:0,rawLateMinutes:0,effectiveLateMinutes:0,lateThresholdMinutes:0,earlyLeaveMinutes:0,earlyLeaveThresholdMinutes:0,manualLateNormalized:false,leaveApproved:false,unauthorizedAbsence:false,schedule:{id:5,revision:3,startTime:"18:00",endTime:"23:00",unpaidBreakMinutes:0},storePolicyRevision:4,warningCodes:options?.unresolved?["MISSING_CHECK_OUT"]:[]};
  const decision=status?{id:30,attendanceRecordId:7,decision:status==="rejected"?"rejected":"approved",sourceHash:"a".repeat(64),decisionReason:null,decidedBy:2,decidedAt:"2026-09-01T00:00:00Z"}:null;
  const raw={userId:1,employeeName:"Đức",contractSnapshot:contract?[contract]:[],attendanceSnapshot:{month:"2026-08",engineVersion:"monthly-payroll-v9",days:[{date:"2026-08-09",sourceFact}]},insuranceSnapshot:{settingVersionId:40,revision:1,effectiveMonth:"2026-08-01",isEnrolled:true,insuranceBaseAmount:1_000_000,employeeRateBp:100,employerRateBp:200,employeeDeductionAmount:10_000,employerAmount:20_000},recognizedWorkdays:1,recognizedMinutes:300,lateMinutes:0,earlyLeaveMinutes:0,overtimeCandidateMinutes:0,partTimeExtraWork:status?[{attendanceRecordId:7,userId:1,businessDate:"2026-08-09",checkInAt:"2026-08-09T10:00:00Z",checkOutAt:"2026-08-09T16:00:00Z",contractId:10,contractRevision:2,minuteRateAmount:35_000/60,hourlyRateAmount:35_000,scheduleId:5,scheduleRevision:3,scheduleStartTime:"18:00",scheduleEndTime:"23:00",storeSettingId:6,storeSettingRevision:4,storeOpenTime:"16:00",storeCloseTime:"01:00",beforeScheduleMinutes:120,afterScheduleMinutes:0,excludedBeforeOpenMinutes:0,excludedAfterCloseMinutes:0,candidateMinutes:120,candidateAmount:70_000,sourceSnapshot:{contractId:10,contractRevision:2},sourceHash:"a".repeat(64),decision,status}]:[],items:[],reviews:(options?.reviewCodes??[]).map(code=>({warningCode:code,reviewLevel:"blocking",businessDate:"2026-08-09",sourceSnapshot:{}}))};
  const taxReview=options?.taxReview===true;
  const employee={userId:1,name:"Đức",username:"duc",birthDate:null,part:"bar",position:"staff",role:"staff",levelInfo:{eligible:true,reason:"ELIGIBLE",level:2,displayLabel:"L2",earnedRaiseCount:1,raiseAmountPerStep:100_000},calculationStatus:taxReview?"requires_review":"calculable",recognizedWorkdays:1,recognizedMinutes:300,insuranceEnrolled:true,tax:{status:taxReview?"requires_review":"calculated",warningCodes:taxReview?["TAX_PROFILE_REQUIRES_REVIEW"]:[],taxMode:"resident_progressive",taxBurdenMode:"employee_deducted",taxPolicyId:50,taxPolicyRevision:1,taxProfileId:51,taxProfileRevision:1,personalDeductionAmount:0,dependentCount:0,dependentDeductionAmount:0,taxableCompensationAmount:100_000,deductibleInsuranceAmount:10_000,taxableIncomeBeforeGrossUpAmount:90_000,taxableIncomeAmount:90_000,calculatedPitAmount:5_000,employeePitDeductionAmount:5_000,companyPitAmount:0,accountingName:"DUC",insuranceDeductionMode:"payroll",manualInsuranceDeductionAmount:0,policySnapshot:null,profileSnapshot:null},contract,levelApplication:{currentLevel:2,earnedRaiseCount:1,raiseAmountPerStep:100_000,accruedRaiseAmount:100_000,status:"applied"},amounts:{levelRaiseAmount:100_000},adjustments:[],automaticPenalties:[],automaticIncentives:[],partTimeExtraWork:raw.partTimeExtraWork,unresolvedAttendanceCount:options?.unresolved?1:0,attendanceMetrics:{lateCount:0,lateMinutes:0,earlyLeaveCount:0,earlyLeaveMinutes:0},reviewCount:raw.reviews.length,blockingCount:raw.reviews.length,warningCodes:options?.reviewCodes??[]};
  const overview={period:{asOfDate:"2026-08-31"},employees:[employee],rawByUser:new Map([[1,raw]]),adjustmentLedgerByUser:new Map([[1,[]]]),snapshot:{context:{attendance:[{id:7,user_id:1,status:"done",work_date:"2026-08-09",check_in_at:"2026-08-09T11:00:00Z",check_out_at:"2026-08-09T16:00:00Z",late_minutes:0,early_leave_minutes:0,work_minutes:300,note:null,approval_status:null,updated_at:"2026-08-09T16:00:00Z"}]},sourceSnapshot:{levelProgramVersions:[{userId:1,id:60,revision:2}]}}};
  return {month:"2026-08",overview:overview as never,mealAllowance:{currentByUser:[{userId:1,eligibleDays:1,referenceAmount:30_000}]}};
}

test("normal source employee is ready and exports explicit source facts",()=>{const result=buildPayrollSourceExport(fixture());assert.equal(result.employees[0].readiness.readyForAccounting,true);assert.equal(result.employees[0].attendance.recognizedAttendanceDays,1);assert.equal(result.employees[0].contract?.baseSalaryAmount,35_000);assert.equal(result.employees[0].contractVersions[0].effectiveFrom,"2026-08-01");assert.equal(result.readiness.readyEmployeeCount,1)});
test("missing contract is blocked",()=>{const result=buildPayrollSourceExport(fixture({contract:false,reviewCodes:["NO_PAYROLL_CONTRACT"]}));assert.equal(result.employees[0].readiness.readyForAccounting,false);assert.ok(result.employees[0].readiness.blockingCodes.includes("NO_PAYROLL_CONTRACT"))});
test("unresolved attendance is blocked",()=>{const result=buildPayrollSourceExport(fixture({unresolved:true,reviewCodes:["MISSING_CHECK_OUT"]}));assert.equal(result.employees[0].readiness.readyForAccounting,false);assert.ok(result.employees[0].readiness.blockingCodes.includes("UNRESOLVED_ATTENDANCE"))});
for(const status of ["review_required","stale"] as const)test(`${status} extra work is blocked`,()=>{const result=buildPayrollSourceExport(fixture({extraStatus:status,reviewCodes:[status==="stale"?"PART_TIME_EXTRA_WORK_DECISION_STALE":"PART_TIME_EXTRA_WORK_REVIEW_REQUIRED"]}));assert.equal(result.employees[0].readiness.readyForAccounting,false);assert.equal(status==="stale"?result.employees[0].extraWork.staleCount:result.employees[0].extraWork.pendingCount,1)});
test("tax setting requiring review blocks accounting readiness",()=>{const result=buildPayrollSourceExport(fixture({taxReview:true}));assert.equal(result.employees[0].readiness.readyForAccounting,false);assert.ok(result.employees[0].readiness.blockingCodes.includes("TAX_SETTING_REQUIRES_REVIEW"))});
test("advisory warning keeps readiness",()=>{const result=buildPayrollSourceExport(fixture({reviewCodes:["STORED_WORK_MINUTES_MISMATCH"]}));assert.equal(result.employees[0].readiness.readyForAccounting,true);assert.ok(result.employees[0].readiness.warningCodes.includes("STORED_WORK_MINUTES_MISMATCH"))});
test("employee and month hashes are stable across generation timestamps",()=>{const first=buildPayrollSourceExport({...fixture(),generatedAt:"2026-09-09T01:00:00Z"});const second=buildPayrollSourceExport({...fixture(),generatedAt:"2026-09-09T02:00:00Z"});assert.equal(first.employees[0].sourceHash,second.employees[0].sourceHash);assert.equal(first.sourceHash,second.sourceHash)});
