import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
const sql=fs.readFileSync(path.join(process.cwd(),'supabase/migrations/202607270001_create_payroll_shadow_foundation.sql'),'utf8');
test('migration creates effective-dated non-overlapping foundations',()=>{for(const table of ['employee_work_schedule_versions','payroll_contract_versions','payroll_contract_audit_logs'])assert.match(sql,new RegExp(`create table public\\.${table}`));assert.match(sql,/employee_schedule_no_overlap exclude using gist/);assert.match(sql,/payroll_contract_no_overlap exclude using gist/);assert.match(sql,/date '2026-08-01'/);});
test('migration locks tables to service role and keeps contract writes in owner-master RPC',()=>{assert.match(sql,/enable row level security/g);assert.match(sql,/revoke all on table public\.payroll_contract_versions from public, anon, authenticated, service_role/);assert.match(sql,/grant select on table public\.payroll_contract_versions to service_role/);assert.match(sql,/role in \('owner', 'master'\)/);assert.match(sql,/grant execute on function public\.payroll_create_contract_version_v1[\s\S]*to service_role/);});
test('schedule changes also use an owner-master version creation RPC',()=>{assert.match(sql,/employee_create_work_schedule_version_v1/);assert.match(sql,/update public\.employee_work_schedule_versions set effective_to = p_effective_from where id/);assert.match(sql,/update public\.users[\s\S]*work_start_time[\s\S]*work_end_time/);assert.match(sql,/grant execute on function public\.employee_create_work_schedule_version_v1[\s\S]*to service_role/);});
test('migration seeds only schedules and never mutates attendance data',()=>{assert.match(sql,/insert into public\.employee_work_schedule_versions/);assert.doesNotMatch(sql,/(insert into|update|delete from) public\.attendance_records/i);assert.doesNotMatch(sql,/insert into public\.payroll_contract_versions[\s\S]*select.*from public\.users/i);});
test('contract API and shadow API require payroll actor and no-store responses',()=>{for(const file of ['app/api/admin/payroll/contracts/route.ts','app/api/admin/payroll/shadow/route.ts']){const source=fs.readFileSync(path.join(process.cwd(),file),'utf8');assert.match(source,/requirePayrollActor\(\)/);assert.match(source,/payrollJson\(/);}const shadow=fs.readFileSync(path.join(process.cwd(),'app/api/admin/payroll/shadow/route.ts'),'utf8');assert.doesNotMatch(shadow,/\.insert\(|\.update\(|\.delete\(|\.rpc\("payroll_create/);});

test('all payroll SECURITY DEFINER functions use a locked search path and service-role-only execute',()=>{const functions=[...sql.matchAll(/create or replace function public\.(\w+)[\s\S]*?security definer[\s\S]*?set search_path = public[\s\S]*?\$\$;/g)];assert.equal(functions.length,2);for(const match of functions){const name=match[1];assert.match(sql,new RegExp(`revoke all on function public\\.${name}\\([\\s\\S]*?from public, anon, authenticated`));assert.match(sql,new RegExp(`grant execute on function public\\.${name}\\([\\s\\S]*?to service_role`));assert.match(match[0],/is_active = true and role in \('owner', 'master'\)/);}});
test('schedule and contract periods use exclusive effective_to boundaries without gaps',()=>{assert.match(sql,/daterange\(effective_from, coalesce\(effective_to, 'infinity'::date\), '\[\)'\)/g);assert.doesNotMatch(sql,/effective_to \+ 1|p_effective_from - 1/);assert.match(sql,/update public\.employee_work_schedule_versions set effective_to = p_effective_from/);assert.match(sql,/update public\.payroll_contract_versions set effective_to = p_effective_from/);});
test('hourly day contracts and non-integer VND salary are rejected',()=>{assert.match(sql,/numeric\(16,0\)/);assert.match(sql,/not \(pay_type = 'hourly' and calculation_basis = 'day'\)/);assert.match(sql,/invalid_pay_basis/);});
test('schedule seed is null-safe, unique, and carries break defaults',()=>{assert.match(sql,/unpaid_break_minutes integer not null default 0/);assert.match(sql,/where work_start_time ~[\s\S]*and work_end_time ~/);assert.match(sql,/employee_schedule_revision_unique unique \(user_id, revision\)/);});
test('schedule API blocks future dates and never trusts a client actor id',()=>{const route=fs.readFileSync(path.join(process.cwd(),'app/api/admin/payroll/schedules/route.ts'),'utf8');assert.match(route,/requirePayrollActor\(\)/);assert.match(route,/body\?\.effectiveFrom!==vietnamDate\(\)/);assert.match(route,/p_actor_user_id:auth\.actor\.id/);assert.doesNotMatch(route,/body.*actorUserId|actorUsername/);});
test('btree_gist exists and the initial schedule seed remains scheduled before its date',()=>{assert.match(sql,/create extension if not exists btree_gist with schema extensions/);const route=fs.readFileSync(path.join(process.cwd(),'app/api/admin/payroll/schedules/route.ts'),'utf8');assert.match(route,/current:history\.find\(item=>item\.effectiveFrom<=today/);assert.match(route,/scheduled:history\.find\(item=>item\.effectiveFrom>today/);assert.doesNotMatch(route,/current:[^\n]*2026-08-01/);});
