import assert from "node:assert/strict";
import test from "node:test";
// @ts-expect-error Node direct TypeScript tests require extensions.
import { classifyMonthlyAttendanceDay, evaluateMonthlyAttendanceStanding, resolveAttendanceStoreClosed } from "../lib/attendance/monthly-standing.ts";
// @ts-expect-error Node direct TypeScript tests require extensions.
import { qualifiesForAttendanceBonus, selectAttendanceBonusEligibilityAt, selectAttendanceBonusPolicyAt } from "../lib/payroll/attendance-bonus.ts";
import type { AttendanceDayFacts } from "../lib/payroll/types";
// @ts-expect-error Node direct TypeScript tests require extensions.
import { normalizeAttendanceDayFacts } from "../lib/payroll/attendance-facts.ts";
// @ts-expect-error Node direct TypeScript tests require extensions.
import { resolveStoreClosedByDate } from "../lib/store-settings/business-time-adapter-core.ts";
// @ts-expect-error Node direct TypeScript tests require extensions.
import { isBabaPremiumHoliday } from "../lib/store-settings/holidays-policy.ts";

function facts(overrides:Partial<AttendanceDayFacts>={}):AttendanceDayFacts{return {userId:1,businessDate:"2026-08-01",scheduledMinutes:540,actualMinutes:540,scheduledOverlapMinutes:540,manualLateNormalized:false,lateMinutes:0,earlyLeaveMinutes:0,rawEarlyLeaveMinutes:0,earlyLeaveThresholdMinutes:0,isEarlyLeave:false,overtimeCandidateMinutes:0,attendanceStatus:"done",payrollStatus:"calculable",warningCodes:[],stored:{status:"done",lateMinutes:0,earlyLeaveMinutes:0,workMinutes:540},source:{attendanceRecordId:1,scheduleVersionId:1,scheduleRevision:1,storeSettingsRevision:1,engineVersion:"attendance-facts-v1"},...overrides};}
const day=(date:string,value:AttendanceDayFacts|null,extra:Record<string,unknown>={})=>({date,facts:value,hasSchedule:true,completedBusinessDay:true,...extra});
test("standing counts each worked date once",()=>{const result=evaluateMonthlyAttendanceStanding({attendanceTrackingEnabled:true,days:[day("2026-08-01",facts()),day("2026-08-01",facts())]});assert.equal(result.actualWorkDays,1);assert.equal(result.perfectAttendanceCurrent,true)});
test("late and early leave use normalized facts",()=>{const result=evaluateMonthlyAttendanceStanding({attendanceTrackingEnabled:true,days:[day("2026-08-01",facts({lateMinutes:1})),day("2026-08-02",facts({earlyLeaveMinutes:1}))]});assert.equal(result.lateCount,1);assert.equal(result.earlyLeaveCount,1);assert.equal(result.perfectAttendanceCurrent,false)});
test("approved leave and exempt dates are not blocking",()=>{const result=evaluateMonthlyAttendanceStanding({attendanceTrackingEnabled:true,days:[day("2026-08-01",facts()),day("2026-08-02",facts({attendanceStatus:"leave",actualMinutes:null}),{approvedLeave:true}),day("2026-08-03",null,{exempt:true})]});assert.equal(result.actualWorkDays,1);assert.equal(result.blockingCount,0)});
test("store hours, not a holiday row, decide whether an expected workday is exempt",()=>{const open=classifyMonthlyAttendanceDay({employed:true,storeClosed:false,scheduleCount:1});assert.equal(open.exempt,false);const missed=evaluateMonthlyAttendanceStanding({attendanceTrackingEnabled:true,days:[{date:"2026-08-01",facts:null,completedBusinessDay:true,...open}]});assert.equal(missed.blockingCount,1);const worked=evaluateMonthlyAttendanceStanding({attendanceTrackingEnabled:true,days:[{date:"2026-08-01",facts:facts(),completedBusinessDay:true,...open}]});assert.equal(worked.actualWorkDays,1);const normalizedLate=normalizeAttendanceDayFacts({userId:1,businessDate:"2026-08-01",attendanceRecord:{id:1,status:"done",checkInAt:"2026-08-01T16:10:00+07:00",checkOutAt:"2026-08-02T01:00:00+07:00",approvalStatus:null},schedule:{id:1,userId:1,startTime:"16:00",endTime:"01:00",unpaidBreakMinutes:0,effectiveFrom:"2026-08-01",effectiveTo:null,revision:1,changeReason:null},lateGraceMinutes:0,earlyLeaveGraceMinutes:0});const late=evaluateMonthlyAttendanceStanding({attendanceTrackingEnabled:true,days:[{date:"2026-08-01",facts:normalizedLate,completedBusinessDay:true,...open}]});assert.equal(late.lateCount,1)});
test("single and multi-day premium holiday operation follows the existing store-open policy",()=>{const single=isBabaPremiumHoliday({holidayGroup:"NEW_YEAR",internalPayMultiplier:null},1);const multiSelected=isBabaPremiumHoliday({holidayGroup:"TET",internalPayMultiplier:2},5);const multiUnselected=isBabaPremiumHoliday({holidayGroup:"TET",internalPayMultiplier:null},5);assert.equal(single,true);assert.equal(multiSelected,true);assert.equal(multiUnselected,false);assert.equal(resolveAttendanceStoreClosed({weeklyStoreClosed:true,babaPremiumHoliday:single}),false);assert.equal(resolveAttendanceStoreClosed({weeklyStoreClosed:true,babaPremiumHoliday:multiSelected}),false);assert.equal(resolveAttendanceStoreClosed({weeklyStoreClosed:true,babaPremiumHoliday:multiUnselected}),true);assert.equal(resolveAttendanceStoreClosed({weeklyStoreClosed:false,babaPremiumHoliday:multiUnselected}),false)});
test("effective store business hours exempt only an actually closed weekday",()=>{const timeline=[{id:1,effectiveFromBusinessDate:"2026-08-01",hours:[{weekday:0,isClosed:false,openTime:"16:00",closeTime:"01:00"},{weekday:1,isClosed:true,openTime:null,closeTime:null}]}];const result=resolveStoreClosedByDate(["2026-08-02","2026-08-03"],timeline);assert.equal(result.get("2026-08-02"),false);assert.equal(result.get("2026-08-03"),true);assert.equal(classifyMonthlyAttendanceDay({employed:true,storeClosed:true,scheduleCount:1}).exempt,true)});
test("schedule cardinality distinguishes no schedule, one schedule, and overlap",()=>{const none=classifyMonthlyAttendanceDay({employed:true,storeClosed:false,scheduleCount:0});assert.equal(none.exempt,true);assert.equal(evaluateMonthlyAttendanceStanding({attendanceTrackingEnabled:true,days:[{date:"2026-08-01",facts:null,completedBusinessDay:true,...none}]}).blockingCount,0);const one=classifyMonthlyAttendanceDay({employed:true,storeClosed:false,scheduleCount:1});assert.equal(one.exempt,false);const overlap=classifyMonthlyAttendanceDay({employed:true,storeClosed:false,scheduleCount:2});const result=evaluateMonthlyAttendanceStanding({attendanceTrackingEnabled:true,days:[{date:"2026-08-01",facts:facts(),completedBusinessDay:true,...overlap}]});assert.equal(overlap.exempt,false);assert.equal(result.blockingCount,1);assert.deepEqual(result.blockingReasons,[{date:"2026-08-01",code:"SCHEDULE_OVERLAP"}])});
test("missing, pending leave, checkout and invalid ranges block completed days",()=>{for(const code of ["MISSING_CHECK_IN","MISSING_CHECK_OUT","PENDING_LEAVE_APPROVAL","INVALID_TIME_RANGE"] as const){const result=evaluateMonthlyAttendanceStanding({attendanceTrackingEnabled:true,days:[day("2026-08-01",facts({actualMinutes:null,warningCodes:[code]}))]});assert.equal(result.blockingCount,1)}});
test("open record on an uncompleted business day is not blocking",()=>{const result=evaluateMonthlyAttendanceStanding({attendanceTrackingEnabled:true,days:[{...day("2026-08-11",facts({actualMinutes:null,attendanceStatus:"working",warningCodes:["MISSING_CHECK_OUT"]})),completedBusinessDay:false}]});assert.equal(result.blockingCount,0)});
test("policy and eligibility resolve by month then revision",()=>{const policies=[{id:1,effectiveMonth:"2026-08",minimumActualWorkdays:24,allowedLateCount:0,allowedEarlyLeaveCount:0,bonusAmount:500000,revision:1},{id:2,effectiveMonth:"2026-09",minimumActualWorkdays:20,allowedLateCount:1,allowedEarlyLeaveCount:1,bonusAmount:600000,revision:2}];assert.equal(selectAttendanceBonusPolicyAt(policies,"2026-08")?.id,1);assert.equal(selectAttendanceBonusPolicyAt(policies,"2026-09")?.id,2);assert.equal(selectAttendanceBonusEligibilityAt([{id:1,userId:1,isEligible:true,effectiveMonth:"2026-08",revision:1},{id:2,userId:1,isEligible:false,effectiveMonth:"2026-09",revision:2}],"2026-09")?.isEligible,false)});
test("same-month eligibility resolves the latest revision",()=>{const versions=[{id:1,userId:1,isEligible:true,effectiveMonth:"2026-08",revision:1},{id:2,userId:1,isEligible:false,effectiveMonth:"2026-08",revision:2}];assert.equal(selectAttendanceBonusEligibilityAt(versions,"2026-08")?.isEligible,false)});
test("future eligibility revisions preserve only real eligible intervals",()=>{const sameMonth=[{id:1,userId:1,isEligible:true,effectiveMonth:"2026-09",revision:1},{id:2,userId:1,isEligible:false,effectiveMonth:"2026-09",revision:2}];assert.equal(selectAttendanceBonusEligibilityAt(sameMonth,"2026-09")?.isEligible,false);const interval=[{id:3,userId:1,isEligible:true,effectiveMonth:"2026-09",revision:1},{id:4,userId:1,isEligible:false,effectiveMonth:"2026-10",revision:2}];assert.equal(selectAttendanceBonusEligibilityAt(interval,"2026-09")?.isEligible,true);assert.equal(selectAttendanceBonusEligibilityAt(interval,"2026-10")?.isEligible,false)});
test("closed month qualification honors allowance counts and minimum workdays",()=>{const policy={id:1,effectiveMonth:"2026-08",minimumActualWorkdays:24,allowedLateCount:1,allowedEarlyLeaveCount:1,bonusAmount:500000,revision:1};const eligibility={id:1,userId:1,isEligible:true,effectiveMonth:"2026-08",revision:1};assert.equal(qualifiesForAttendanceBonus({monthClosed:true,attendanceTrackingEnabled:true,policy,eligibility,standing:{actualWorkDays:24,lateCount:1,earlyLeaveCount:1,blockingCount:0,perfectAttendanceCurrent:false}}),true);assert.equal(qualifiesForAttendanceBonus({monthClosed:false,attendanceTrackingEnabled:true,policy,eligibility,standing:{actualWorkDays:24,lateCount:0,earlyLeaveCount:0,blockingCount:0,perfectAttendanceCurrent:true}}),false)});
