import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";

const migration = readFileSync(
  join(process.cwd(), "supabase/migrations/20260909231222_fix_contract_correction_payment_snapshot.sql"),
  "utf8",
);

async function database() {
  const db = new PGlite();
  await db.exec(`
    create role anon;
    create role authenticated;
    create role service_role;
    create table public.users (
      id bigint generated by default as identity primary key,
      is_active boolean not null,
      role text not null,
      is_system_account boolean not null default false
    );
    create table public.payroll_contract_versions (
      id bigint primary key,
      user_id bigint not null,
      pay_type text not null,
      calculation_basis text not null,
      base_salary numeric not null,
      fixed_raise_amount numeric not null,
      standard_workdays numeric,
      standard_minutes_per_day integer not null,
      time_block_minutes integer not null,
      rounding_mode text not null,
      late_adjustment_mode text not null,
      early_leave_adjustment_mode text not null,
      overtime_mode text not null,
      paid_leave_mode text not null,
      effective_from date not null,
      effective_to date,
      revision bigint not null,
      note text
    );
    create table public.payroll_contract_audit_logs (
      id bigint generated by default as identity primary key,
      contract_version_id bigint not null,
      user_id bigint not null,
      action text not null,
      actor_user_id bigint not null,
      snapshot jsonb,
      reason text
    );
    create table public.payroll_payment_batches (id bigint primary key);
    create table public.payroll_employee_payments (
      id bigint primary key,
      payroll_batch_id bigint not null,
      user_id bigint not null,
      payment_status text not null,
      calculation_snapshot jsonb
    );
    create table public.payroll_payment_audit_logs (
      id bigint primary key,
      payroll_batch_id bigint not null,
      employee_payment_id bigint,
      action text not null,
      before_snapshot jsonb,
      after_snapshot jsonb
    );
    create function public.payroll_correct_latest_unused_contract_core_v2(
      bigint,bigint,bigint,bigint,date,text,text,numeric,numeric,numeric,
      integer,integer,text,text,text,text,text,date,bigint,text,text
    ) returns jsonb language sql as $$ select '{}'::jsonb $$;
  `);
  await db.exec(migration);
  await db.exec(`
    insert into public.users(id,is_active,role,is_system_account) values
      (1,true,'owner',false),(10,true,'staff',false),(20,true,'staff',false),(30,true,'staff',false);
    insert into public.payroll_contract_versions(
      id,user_id,pay_type,calculation_basis,base_salary,fixed_raise_amount,
      standard_workdays,standard_minutes_per_day,time_block_minutes,rounding_mode,
      late_adjustment_mode,early_leave_adjustment_mode,overtime_mode,paid_leave_mode,
      effective_from,effective_to,revision,note
    ) values
      (100,10,'hourly','minute',35000,0,null,300,1,'none','separate','ignore','requires_approval','unpaid','2026-08-01',null,1,null),
      (200,20,'hourly','minute',35000,0,null,300,1,'none','separate','ignore','requires_approval','unpaid','2026-08-01',null,1,null),
      (300,30,'hourly','minute',35000,0,null,300,1,'none','separate','ignore','requires_approval','unpaid','2026-08-01',null,1,null);
    insert into public.payroll_contract_audit_logs(id,contract_version_id,user_id,action,actor_user_id)
      values (1000,100,10,'created',1),(2000,200,20,'created',1),(3000,300,30,'created',1);
    insert into public.payroll_payment_batches(id) values (1),(2);
    insert into public.payroll_employee_payments(id,payroll_batch_id,user_id,payment_status,calculation_snapshot) values
      (11,1,20,'paid','{"contractSnapshot":[{"id":200,"revision":1}]}'),
      (12,2,30,'unpaid',null);
    insert into public.payroll_payment_audit_logs(id,payroll_batch_id,employee_payment_id,action,before_snapshot,after_snapshot) values
      (21,2,12,'employee_payment_cancelled',
       '{"calculation_snapshot":{"contractSnapshot":[{"id":300,"revision":1}]}}',
       '{"calculation_snapshot":null}');
  `);
  return db;
}

async function correct(db, contractId, userId, auditId) {
  const result = await db.query(`
    select public.payroll_correct_latest_unused_contract_core_v2(
      $1,$2,1,$3,date '2026-08-01','hourly','minute',36000,0,null,
      300,1,'none','separate','ignore','requires_approval','unpaid',
      date '2026-08-01',1,'correction','test correction'
    ) as result
  `, [contractId, userId, auditId]);
  return result.rows[0].result;
}

test("unused latest contract remains correctable with optimistic revision protection", async () => {
  const db = await database();
  assert.equal((await correct(db, 100, 10, 1000)).status, "corrected");
  const salary = await db.query("select base_salary from public.payroll_contract_versions where id=100");
  assert.equal(Number(salary.rows[0].base_salary), 36000);
  await db.close();
});

test("contract used by a current paid calculation snapshot is immutable", async () => {
  const db = await database();
  assert.equal((await correct(db, 200, 20, 2000)).status, "locked_payroll_contract");
  await db.close();
});

test("contract used by a later-cancelled payment remains immutable through audit", async () => {
  const db = await database();
  assert.equal((await correct(db, 300, 30, 3000)).status, "locked_payroll_contract");
  await db.close();
});
