import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const read=(file:string)=>fs.readFileSync(path.join(process.cwd(),file),"utf8");
const migration=read("supabase/migrations/202608010001_add_payroll_work_policy_penalties_v6.sql");
const engine=read("lib/payroll/monthly-run.ts");
const settings=read("components/payroll/PayrollCommonSettings.tsx");
const contractUi=read("app/(protected)/admin/payroll/settings/page.tsx");
const labels=read("lib/payroll/ui-labels.ts");
const runDetail=read("app/(protected)/admin/payroll/[runId]/page.tsx");

test("v6 settings and immutable penalty snapshot are constrained",()=>{for(const field of ["late_major_threshold_minutes","late_minor_penalty_minutes","late_major_penalty_rate_bp","unauthorized_absence_penalty_days","penalty_settings_snapshot"])assert.match(migration,new RegExp(field));assert.match(migration,/default 20/);assert.match(migration,/default 60/);assert.match(migration,/default 5000/);assert.match(migration,/default 3/);assert.match(migration,/PAYROLL_PENALTY_SNAPSHOT_STALE/);assert.match(migration,/p_action in\('finalize','force_finalize'\)/);assert.doesNotMatch(migration,/drop function public\.payroll_.*_v[23]/);});
test("v6 RPCs are private and preserve v3 insurance transition",()=>{for(const fn of ["payroll_create_run_v4","payroll_recalculate_run_v4","payroll_mutate_item_v4","payroll_resolve_review_v4","payroll_transition_run_v4"])assert.match(migration,new RegExp(`create function public\\.${fn}`));assert.match(migration,/from public,anon,authenticated/);assert.match(migration,/to service_role/);assert.match(migration,/perform public\.payroll_transition_run_v3/);assert.match(migration,/monthly-payroll-v6/);});
test("missing attendance requires admin resolution and never creates an automatic absence item",()=>{assert.match(engine,/const recordsByDate=new Map/);assert.match(engine,/if\(!record&&!schedule\)continue/);assert.match(engine,/MISSING_CHECK_IN/);assert.match(migration,/confirm_unauthorized_absence','exclude_absence_penalty/);assert.match(migration,/item_type,category,direction/);assert.match(migration,/'review_adjustment','unauthorized_absence_deduction','deduction'/);assert.match(migration,/v_day_rate\*v_penalty_days/);assert.match(migration,/payroll_run_item_unauthorized_absence_unique/);assert.match(runDetail,/무단결근 확정/);assert.match(runDetail,/Xác nhận nghỉ không phép/);assert.match(runDetail,/패널티 제외/);assert.match(runDetail,/Không áp dụng phạt/);});
test("actual-time and workday modes use v6 semantics without overtime review",()=>{assert.match(engine,/calculationBasis==="minute"\?facts\.actualMinutes/);assert.match(engine,/contract\.calculationBasis==="hour"&&contract\.overtimeMode/);assert.match(engine,/monthly-payroll-v6/);assert.match(engine,/calculateLatePenalty/);assert.match(engine,/penaltyTier/);});
test("contract UI offers only actual-time and workday modes with legacy hour labels",()=>{assert.match(contractUi,/\["minute", "day"\]/);assert.match(contractUi,/\["minute"\]/);assert.doesNotMatch(contractUi,/\["minute", "hour"/);assert.match(contractUi,/급여 산정 방식/);assert.match(contractUi,/Cách tính lương/);assert.match(labels,/실근무 정산/);assert.match(labels,/Theo giờ thực tế/);assert.match(labels,/근무일 정산/);assert.match(labels,/Theo ngày công/);assert.match(labels,/기존 시간 블록 정산/);assert.match(labels,/Cách tính theo khối giờ cũ/);});
test("common settings keeps one save for ten fields and compact bilingual sections",()=>{for(const field of ["lateMajorThresholdMinutes","lateMinorPenaltyMinutes","lateMajorPenaltyRateBp","unauthorizedAbsencePenaltyDays"])assert.match(settings,new RegExp(field));for(const heading of ["💰","🛡️","⚠️","Lương","Bảo hiểm","Phạt"])assert.match(settings,new RegExp(heading));for(const label of ["Mốc phân loại","Đi muộn 1~","Đi muộn quá","Nghỉ không phép"])assert.match(settings,new RegExp(label));assert.equal((settings.match(/method: "PATCH"/g)??[]).length,1);assert.match(settings,/width: 56/);assert.match(settings,/height: 34/);assert.match(settings,/textAlign: "right"/);});
test("duplicate automatic penalties and postflight checks are present",()=>{const postflight=read("supabase/payroll_work_policy_penalties_v6_postflight.sql");assert.match(migration,/payroll_run_item_automatic_late_unique/);assert.match(migration,/payroll_run_item_unauthorized_absence_unique/);assert.match(postflight,/public_execute_revoked/);assert.doesNotMatch(postflight,/has_function_privilege\('PUBLIC'/);assert.doesNotMatch(postflight,/to_regrole\('PUBLIC'/);assert.match(postflight,/aclexplode\(coalesce\(p\.proacl,acldefault\('f',p\.proowner\)\)\)/);assert.match(postflight,/acl\.grantee=0/);assert.match(postflight,/acl\.privilege_type='EXECUTE'/);assert.match(postflight,/has_function_privilege\('anon',p\.oid,'EXECUTE'\)/);assert.match(postflight,/has_function_privilege\('authenticated',p\.oid,'EXECUTE'\)/);assert.match(postflight,/has_function_privilege\('service_role',p\.oid,'EXECUTE'\)/);assert.match(postflight,/service_role_execute/);assert.match(postflight,/expected_initial_insurance_rows/);assert.match(postflight,/mjk_insurance_version_rows/);assert.match(postflight,/payroll_run_rows/);});
