import assert from "node:assert/strict";
import test from "node:test";
// @ts-expect-error Node test execution needs explicit TypeScript extensions.
import { normalizeAttendanceDayFacts } from "../lib/payroll/attendance-facts.ts";
// @ts-expect-error Node test execution needs explicit TypeScript extensions.
import { projectPayrollAttendanceDay, roundMinutes } from "../lib/payroll/projection.ts";
import type { PayrollContract, WorkScheduleVersion } from "../lib/payroll/types.ts";

const schedule: WorkScheduleVersion={id:1,userId:7,startTime:'16:00',endTime:'01:00',unpaidBreakMinutes:0,effectiveFrom:'2026-08-01',effectiveTo:null,revision:1,changeReason:'seed'};
const contract: PayrollContract={id:1,userId:7,payType:'daily',calculationBasis:'minute',baseSalary:900,fixedRaiseAmount:0,standardWorkdays:26,standardMinutesPerDay:540,timeBlockMinutes:60,roundingMode:'floor',lateAdjustmentMode:'separate',earlyLeaveAdjustmentMode:'separate',overtimeMode:'requires_approval',paidLeaveMode:'manual_review',effectiveFrom:'2026-08-01',effectiveTo:null,revision:1};

test('normalizes facts in integer minutes and separates out-of-schedule work',()=>{const facts=normalizeAttendanceDayFacts({userId:7,businessDate:'2026-08-03',schedule,attendanceRecord:{id:4,status:'done',checkInAt:'2026-08-03T08:50:00.000Z',checkOutAt:'2026-08-03T18:10:00.000Z',approvalStatus:'approved'}});assert.equal(facts.scheduledMinutes,540);assert.equal(facts.actualMinutes,560);assert.equal(facts.scheduledOverlapMinutes,540);assert.equal(facts.overtimeCandidateMinutes,20);assert.ok(facts.warningCodes.includes('OVERTIME_APPROVAL_UNAVAILABLE'));});
test('warns instead of backfilling schedules before automation start',()=>{const facts=normalizeAttendanceDayFacts({userId:7,businessDate:'2026-07-31',schedule:null,attendanceRecord:null});assert.ok(facts.warningCodes.includes('SCHEDULE_HISTORY_UNAVAILABLE'));assert.equal(facts.payrollStatus,'requires_review');});
test('hour block rounding stays in integer minutes',()=>{assert.equal(roundMinutes(539,60,'floor'),480);assert.equal(roundMinutes(539,60,'ceil'),540);assert.equal(roundMinutes(511,60,'nearest'),540);});
test('day projection keeps a full day and exposes late adjustment separately',()=>{const facts=normalizeAttendanceDayFacts({userId:7,businessDate:'2026-08-03',schedule,attendanceRecord:{id:4,status:'late',checkInAt:'2026-08-03T09:10:00.000Z',checkOutAt:'2026-08-03T18:00:00.000Z',approvalStatus:'approved'}});const result=projectPayrollAttendanceDay(facts,contract,'day');assert.equal(result.recognizedDays,1);assert.equal(result.recognizedMinutes,540);assert.equal(result.adjustmentMinutes,10);});
test('missing checkout and contract never produce an estimated amount',()=>{const facts=normalizeAttendanceDayFacts({userId:7,businessDate:'2026-08-03',schedule,attendanceRecord:{id:4,status:'working',checkInAt:'2026-08-03T09:00:00.000Z',checkOutAt:null,approvalStatus:'approved'}});const result=projectPayrollAttendanceDay(facts,null,'minute');assert.equal(result.payrollStatus,'requires_review');assert.equal(result.estimatedAmount,null);assert.ok(result.warningCodes.includes('MISSING_CHECK_OUT'));assert.ok(result.warningCodes.includes('NO_PAYROLL_CONTRACT'));});
test('all three projections can consume the exact same facts object',()=>{const facts=normalizeAttendanceDayFacts({userId:7,businessDate:'2026-08-03',schedule,attendanceRecord:{id:4,status:'done',checkInAt:'2026-08-03T09:00:00.000Z',checkOutAt:'2026-08-03T18:00:00.000Z',approvalStatus:'approved'}});const results=(['minute','hour','day'] as const).map(b=>projectPayrollAttendanceDay(facts,contract,b));assert.equal(results[0].recognizedMinutes,540);assert.equal(results[1].recognizedMinutes,540);assert.equal(results[2].recognizedMinutes,540);assert.equal(facts.source.engineVersion,'attendance-facts-v1');});

test('Asia/Ho_Chi_Minh overnight schedule and attendance grace remain stable',()=>{const facts=normalizeAttendanceDayFacts({userId:7,businessDate:'2026-08-03',schedule,lateGraceMinutes:10,earlyLeaveGraceMinutes:10,attendanceRecord:{id:4,status:'done',checkInAt:'2026-08-03T09:10:00.000Z',checkOutAt:'2026-08-03T17:50:00.000Z',approvalStatus:'approved'}});assert.equal(facts.scheduledMinutes,540);assert.equal(facts.lateMinutes,0);assert.equal(facts.earlyLeaveMinutes,0);const day=projectPayrollAttendanceDay(facts,contract,'day');assert.equal(day.recognizedDays,1);assert.equal(day.adjustmentMinutes,0);});

test('monthly and daily contracts support minute, hour, and day projections while hourly supports minute and hour',()=>{const facts=normalizeAttendanceDayFacts({userId:7,businessDate:'2026-08-03',schedule,attendanceRecord:{id:4,status:'done',checkInAt:'2026-08-03T09:00:00.000Z',checkOutAt:'2026-08-03T18:00:00.000Z',approvalStatus:'approved'}});for(const payType of ['monthly','daily'] as const){for(const basis of ['minute','hour','day'] as const){const result=projectPayrollAttendanceDay(facts,{...contract,payType,calculationBasis:basis},basis);assert.equal(result.payrollStatus,'calculable');assert.ok(Number.isInteger(result.estimatedAmount));}}for(const basis of ['minute','hour'] as const){const result=projectPayrollAttendanceDay(facts,{...contract,payType:'hourly',baseSalary:10001,calculationBasis:basis},basis);assert.equal(result.payrollStatus,'calculable');assert.ok(Number.isInteger(result.estimatedAmount));}});

test('actual-time projection ignores unpaid breaks and rounds VND once',()=>{const facts=normalizeAttendanceDayFacts({userId:7,businessDate:'2026-08-03',schedule:{...schedule,unpaidBreakMinutes:539},attendanceRecord:{id:4,status:'done',checkInAt:'2026-08-03T09:00:00.000Z',checkOutAt:'2026-08-03T18:00:00.000Z',approvalStatus:'approved'}});const result=projectPayrollAttendanceDay(facts,{...contract,payType:'hourly',baseSalary:10001,timeBlockMinutes:1,roundingMode:'none'},'minute');assert.equal(result.recognizedMinutes,540);assert.equal(result.estimatedAmount,90009);assert.ok(Number.isInteger(result.estimatedAmount));});

test('leave without payroll treatment is never calculated automatically',()=>{const pending=normalizeAttendanceDayFacts({userId:7,businessDate:'2026-08-03',schedule,attendanceRecord:{id:1,status:'leave',checkInAt:null,checkOutAt:null,approvalStatus:'pending'}});assert.equal(pending.payrollStatus,'pending');assert.ok(pending.warningCodes.includes('PENDING_LEAVE_APPROVAL'));const approved=normalizeAttendanceDayFacts({userId:7,businessDate:'2026-08-04',schedule,attendanceRecord:{id:2,status:'leave',checkInAt:null,checkOutAt:null,approvalStatus:'approved'}});assert.equal(approved.payrollStatus,'requires_review');assert.ok(approved.warningCodes.includes('LEAVE_PAYROLL_TREATMENT_UNSPECIFIED'));assert.equal(projectPayrollAttendanceDay(approved,contract,'day').estimatedAmount,null);});

test('stored attendance differences are exposed as policy mismatch warnings',()=>{const facts=normalizeAttendanceDayFacts({userId:7,businessDate:'2026-08-03',schedule,attendanceRecord:{id:4,status:'late',checkInAt:'2026-08-03T09:00:00.000Z',checkOutAt:'2026-08-03T18:00:00.000Z',approvalStatus:'approved',storedLateMinutes:10,storedEarlyLeaveMinutes:3,storedWorkMinutes:500}});assert.deepEqual(facts.stored,{status:'late',lateMinutes:10,earlyLeaveMinutes:3,workMinutes:500});assert.ok(facts.warningCodes.includes('STORED_STATUS_POLICY_MISMATCH'));assert.ok(facts.warningCodes.includes('STORED_LATE_MINUTES_MISMATCH'));assert.ok(facts.warningCodes.includes('STORED_EARLY_LEAVE_MINUTES_MISMATCH'));assert.ok(facts.warningCodes.includes('STORED_WORK_MINUTES_MISMATCH'));});
