import assert from 'node:assert/strict';import test from 'node:test';import {createRequire} from 'node:module';import {mkdir} from 'node:fs/promises';
const require=createRequire(import.meta.url);
test('utilities group, existing subtype 43, add and existing gas partner edit KO/VI desktop/mobile',{skip:!process.env.PLAYWRIGHT_MODULE_PATH||!process.env.QA_UTILITIES_BASE_URL},async()=>{
 const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH);const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 try{for(const lang of ['ko','vi'])for(const mobile of [false,true]){
 const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},isMobile:mobile,hasTouch:mobile});const page=await context.newPage();page.setDefaultTimeout(10000);const calls=[];const subtype={id:43,code:'utility_gas',partnerType:'utilities',nameKo:'가스',nameVi:'Gas',emoji:null,sortOrder:0,isActive:true};const partner={id:21,name:'Cửa hàng gas petrolimex chính hãng',partnerType:'utilities',partnerSubtypeId:43,partnerSubtype:subtype,paymentMode:'postpaid',settlementMode:null,settlementRule:null,defaultPaymentTermDays:null,defaultFundAccountId:null,defaultFundAccountCode:null,phone:null,contactName:null,memo:null,isActive:true,ledgerPartyId:21,inventoryCount:1,activeInventoryCount:1,displayTag:null};
 await page.route('**/api/**',async route=>{const request=route.request();const url=new URL(request.url());calls.push({path:url.pathname,method:request.method(),body:request.method()==='GET'?null:request.postDataJSON()});await route.fulfill({status:request.method()==='POST'?201:200,contentType:'application/json',body:JSON.stringify(request.method()==='GET'?{ok:true,partners:[partner],partnerSubtypes:[subtype],supplierAliases:[],fundAccounts:[]}:{ok:true,result:{status:'updated',partnerId:21}})});});page.on('dialog',d=>d.accept());
 await page.goto(process.env.QA_UTILITIES_BASE_URL+'/admin/ledger/settings?tab=partners&view=active&lang='+lang);
 const group=page.locator('[data-partner-type="utilities"]');await group.waitFor();assert.match(await group.innerText(),lang==='ko'?/⚡.*공과금/s:/⚡.*Điện nước & gas/s);assert.match(await page.locator('h3').first().innerText(),lang==='ko'?/가스/:/Gas/);assert.ok(await page.getByRole('link',{name:/Cửa hàng gas petrolimex/}).isVisible());
 await page.getByRole('button',{name:lang==='ko'?'+ 거래처 추가':'+ Thêm đối tác',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.waitFor();await dialog.getByLabel(lang==='ko'?'거래처명 *':'Tên đối tác *',{exact:true}).fill('QA Utility');await dialog.getByLabel(lang==='ko'?'업종/종류':'Ngành / loại').selectOption('utilities');const gas=dialog.getByLabel(lang==='ko'?'중분류':'Danh mục phụ');assert.equal(await gas.locator('option[value="43"]').count(),1);await gas.selectOption('43');await dialog.getByRole('button',{name:lang==='ko'?'거래처 등록':'Thêm đối tác',exact:true}).click();await dialog.waitFor({state:'hidden'});const create=calls.find(r=>r.method==='POST');assert.equal(create.body.partnerType,'utilities');assert.equal(create.body.partnerSubtypeId,43);
 await page.getByRole('button',{name:'QA edit #21'}).click();const editor=page.getByTestId('editor');await editor.getByLabel(lang==='ko'?'업종/종류':'Ngành / loại').selectOption('utilities');await editor.getByLabel(lang==='ko'?'중분류':'Danh mục phụ').selectOption('43');const saved=page.waitForResponse(r=>r.url().endsWith('/api/admin/partners/21'));await editor.getByRole('button',{name:lang==='ko'?'저장':'Lưu',exact:true}).click();await saved;const edit=calls.find(r=>r.method==='PATCH');assert.ok(edit);assert.equal(edit.body.partnerType,'utilities');assert.equal(edit.body.partnerSubtypeId,43);assert.equal(edit.body.ledgerPartyId,21);assert.equal(edit.body.paymentMode,'postpaid');assert.equal(edit.body.isActive,true);
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);await mkdir('.qa-review/utilities-browser',{recursive:true});await page.screenshot({path:'.qa-review/utilities-browser/'+lang+'-'+(mobile?'mobile':'desktop')+'.png',fullPage:true});assert.equal(calls.filter(r=>/subtypes/.test(r.path)&&r.method==='POST').length,0);
 console.log('PASS utilities #43 register/edit/group '+lang+' '+(mobile?'mobile':'desktop'));await context.close();
 }}finally{await browser.close();}
});
