import "server-only";
import { supabaseServer } from "@/lib/supabase/server";
import { resolveStoreClosedByDate } from "@/lib/store-settings/business-time-adapter-core";
import { calculateBep } from "@/lib/ledger/bep-core";

const MONTH=/^\d{4}-(0[1-9]|1[0-2])$/;
export const validBepMonth=(value:unknown):value is string=>typeof value==="string"&&MONTH.test(value);
const nextMonth=(month:string,offset=1)=>{const d=new Date(`${month}-01T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+offset);return d.toISOString().slice(0,7)};
const monthDates=(month:string)=>{const end=new Date(`${nextMonth(month)}-01T00:00:00Z`),dates:string[]=[];for(let d=new Date(`${month}-01T00:00:00Z`);d<end;d.setUTCDate(d.getUTCDate()+1))dates.push(d.toISOString().slice(0,10));return dates};
const vietnamToday=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
type CostRow={type:string;amount:number|string;economic_effect_sign?:number;source_type:string;category:{name:string;cost_behavior:string}|null};

export async function loadLedgerBep(month:string){
 if(!validBepMonth(month))throw new Error("INVALID_MONTH");
 const calendarMonths=[nextMonth(month,-3),nextMonth(month,-2),nextMonth(month,-1)],closureResult=await supabaseServer.from("ledger_month_closures").select("month").lt("month",`${month}-01`).order("month",{ascending:false}).limit(3),closedMonths=(closureResult.data??[]).map(row=>String(row.month).slice(0,7)).reverse(),referenceMonths=closedMonths.length?closedMonths:calendarMonths,referenceMonthSource=closedMonths.length?"closed_months":"calendar_fallback",queryStart=`${referenceMonths[0]}-01`,queryEnd=`${nextMonth(month)}-01`,monthStart=`${month}-01`,monthEnd=`${nextMonth(month)}-01`;
 const[transactionResult,settingResult,overrideResult]=await Promise.all([supabaseServer.from("ledger_transactions").select("type,amount,economic_effect_sign,recognition_month,source_type,category:ledger_categories(name,cost_behavior)").eq("status","confirmed").gte("recognition_month",queryStart).lt("recognition_month",queryEnd).in("type",["sales","expense","expense_recognition"]),supabaseServer.from("store_setting_versions").select("id,effective_from_business_date,store_business_hours(weekday,is_closed,open_time,close_time)").eq("state","active").lte("effective_from_business_date",monthDates(month).at(-1)??monthStart).order("effective_from_business_date").order("id"),supabaseServer.from("store_business_day_overrides").select("business_date,actual_close_time").eq("state","active").gte("business_date",monthStart).lt("business_date",monthEnd)]);
 if(closureResult.error||transactionResult.error||settingResult.error||overrideResult.error)throw new Error("BEP_SOURCE_LOAD_FAILED");
 const rows=(transactionResult.data??[])as unknown as Array<CostRow&{recognition_month:string}>,effect=(row:CostRow)=>Number(row.amount)*Number(row.economic_effect_sign??1),ratios=referenceMonths.map(referenceMonth=>{const monthRows=rows.filter(row=>String(row.recognition_month).slice(0,7)===referenceMonth);return{month:referenceMonth,revenue:monthRows.filter(r=>r.type==="sales"&&r.source_type==="pos_sales_daily_payment").reduce((sum,row)=>sum+effect(row),0),variableCost:monthRows.filter(row=>["expense","expense_recognition"].includes(row.type)&&row.category?.cost_behavior==="variable").reduce((sum,row)=>sum+effect(row),0)}}),selected=rows.filter(row=>String(row.recognition_month).slice(0,7)===month),fixedCost=selected.filter(row=>["expense","expense_recognition"].includes(row.type)&&row.category?.cost_behavior==="fixed").reduce((sum,row)=>sum+effect(row),0),currentSales=selected.filter(r=>r.type==="sales"&&r.source_type==="pos_sales_daily_payment").reduce((sum,row)=>sum+effect(row),0),classificationNeeded=[...new Set(selected.filter(row=>row.category?.cost_behavior==="semi_variable").map(row=>row.category?.name).filter(Boolean))];
 const timeline=(settingResult.data??[]).map(row=>{const hours=(Array.isArray(row.store_business_hours)?row.store_business_hours:[])as Array<Record<string,unknown>>;return{id:Number(row.id),effectiveFromBusinessDate:String(row.effective_from_business_date),hours:hours.map(hour=>({weekday:Number(hour.weekday),isClosed:Boolean(hour.is_closed),openTime:hour.open_time==null?null:String(hour.open_time).slice(0,5),closeTime:hour.close_time==null?null:String(hour.close_time).slice(0,5)}))}}),dates=monthDates(month),closed=resolveStoreClosedByDate(dates,timeline),today=vietnamToday(),remainingBusinessDays=dates.filter(date=>date>today&&!closed.get(date)).length,calculated=calculateBep({referenceMonths:ratios,fixedCost,currentSales,remainingBusinessDays});
 return{month,...calculated,referenceMonthSource,revenue:calculated.referenceMonths.reduce((sum,row)=>sum+row.revenue,0),variableCost:calculated.referenceMonths.reduce((sum,row)=>sum+row.variableCost,0),fixedCost,currentSales,remainingBusinessDays,classificationNeeded,storeCalendar:{source:"store_setting_versions",activeEarlyCloseOverrides:(overrideResult.data??[]).length}};
}
