import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";

const migration = readFileSync("supabase/migrations/20260927122430_add_owner_investment_cash_event.sql", "utf8");

async function database() {
  const db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create table ledger_fund_accounts(id bigint primary key, is_active boolean, is_business_fund boolean, type text);
    create table ledger_transactions(
      id bigint generated by default as identity primary key, operation_id uuid, type text,
      occurred_at timestamptz, business_date date, amount numeric, status text,
      source_type text, source_snapshot jsonb, source_fingerprint text, source_synced_at timestamptz,
      memo text, created_by bigint, confirmed_by bigint
    );
    create table ledger_movements(id bigint generated by default as identity primary key, transaction_id bigint, fund_account_id bigint, amount numeric);
    create table ledger_owner_participants(
      id bigint primary key, user_id bigint, effective_from date, effective_to date,
      is_eligible boolean
    );
    create table ledger_owner_investments(
      id bigint generated by default as identity primary key, participant_id bigint, entry_type text,
      signed_amount numeric, occurred_at timestamptz, transaction_id bigint,
      reason text, source_snapshot jsonb, created_by bigint,
      constraint ledger_owner_investments_check check (
        (entry_type='contribution' and signed_amount>0 and transaction_id is not null)
        or (entry_type in('opening','adjustment') and transaction_id is null)
      )
    );
    create table ledger_owner_settlements(id bigint primary key, status text);
    create table ledger_owner_settlement_allocations(id bigint primary key, settlement_id bigint, participant_id bigint, recovery_amount numeric);
    create table ledger_audit_logs(
      id bigint generated by default as identity primary key, actor_user_id bigint, action text,
      entity_type text, entity_id bigint, before_snapshot jsonb, after_snapshot jsonb, reason text
    );
    create table ledger_month_closures(month date primary key, status text);
    create function ledger_owner_role_v1(bigint) returns boolean language sql set search_path=pg_catalog,public as $$ select true $$;
    create function ledger_month_is_closed_v1(p_month date) returns boolean language sql set search_path=pg_catalog,public as $$
      select exists(select 1 from public.ledger_month_closures where month=date_trunc('month',p_month)::date and status='closed')
    $$;
    create function ledger_assert_month_open_v1(p_month date) returns void language plpgsql set search_path=pg_catalog,public as $$
    begin
      if ledger_month_is_closed_v1(p_month) then raise exception 'LEDGER_MONTH_CLOSED'; end if;
    end $$;
    insert into ledger_fund_accounts values (10,true,true,'bank'),(11,false,true,'bank');
    insert into ledger_owner_participants values (20,200,'2026-09-01',null,true);
  `);
  await db.exec(migration);
  return db;
}

async function call(db, action, amount, account = 10, reason = "test") {
  return callAt(db, action, amount, "2026-09-20T12:00:00+07:00", account, reason);
}

async function callAt(db, action, amount, occurredAt, account = 10, reason = "test") {
  return db.query(`select ledger_create_owner_investment_cash_event_v1(
    20, $1, $2, $3, $4, $5, 'memo', 1
  ) result`, [action, amount, occurredAt, account, reason]);
}

test("contribution and recovery atomically change principal and the selected fund", async () => {
  const db = await database();
  await call(db, "contribution", 1000);
  await call(db, "recovery", 400);
  const investments = await db.query("select entry_type,signed_amount,transaction_id from ledger_owner_investments order by id");
  const movements = await db.query("select amount from ledger_movements order by id");
  const transactions = await db.query("select type,source_type from ledger_transactions order by id");
  assert.deepEqual(investments.rows.map((row) => [row.entry_type, Number(row.signed_amount), row.transaction_id !== null]), [
    ["contribution", 1000, true], ["adjustment", -400, true],
  ]);
  assert.deepEqual(movements.rows.map((row) => Number(row.amount)), [1000, -400]);
  assert.deepEqual(transactions.rows.map((row) => row.type), ["investment", "owner_settlement_payment"]);
  await db.close();
});

test("a failure after transaction creation rolls back transaction, movement, and investment together", async () => {
  const db = await database();
  await call(db, "contribution", 1000);
  await db.exec(`create function reject_test_investment() returns trigger language plpgsql as $$
    begin if new.reason='force failure' then raise exception 'forced'; end if; return new; end $$;
    create trigger reject_test_investment before insert on ledger_owner_investments
    for each row execute function reject_test_investment();`);
  await assert.rejects(() => call(db, "recovery", 100, 10, "force failure"));
  const counts = await db.query(`select
    (select count(*) from ledger_transactions)::int transactions,
    (select count(*) from ledger_movements)::int movements,
    (select count(*) from ledger_owner_investments)::int investments`);
  assert.deepEqual(counts.rows[0], { transactions: 1, movements: 1, investments: 1 });
  await db.close();
});

test("recovery guards reject over-recovery, closed month, obligation floor, and invalid account", async () => {
  const db = await database();
  await call(db, "contribution", 1000);
  let result = await call(db, "recovery", 1001);
  assert.equal(result.rows[0].result.status, "negative_cumulative_investment");
  await db.exec("insert into ledger_owner_settlements values (1,'confirmed'); insert into ledger_owner_settlement_allocations values (1,1,20,900);");
  result = await call(db, "recovery", 200);
  assert.equal(result.rows[0].result.status, "investment_below_recovery_obligation");
  result = await call(db, "recovery", 10, 11);
  assert.equal(result.rows[0].result.status, "invalid_fund_account");
  await db.exec("insert into ledger_month_closures values ('2026-09-01','closed');");
  result = await call(db, "recovery", 10);
  assert.equal(result.rows[0].result.status, "closed_month");
  await db.close();
});

test("a backdated recovery ignores deposits after its occurred_at", async () => {
  const db = await database();
  await callAt(db, "contribution", 10_000_000, "2026-09-10T12:00:00+07:00");
  await callAt(db, "contribution", 100_000_000, "2026-09-20T12:00:00+07:00");
  const result = await callAt(db, "recovery", 50_000_000, "2026-09-10T18:00:00+07:00");
  assert.equal(result.rows[0].result.status, "insufficient_fund");
  assert.equal(Number(result.rows[0].result.balance), 10_000_000);
  await db.close();
});
