// KO/VI display text for /admin/ledger/settings (기본설정 · 준비금). Only the
// visible copy is translated; enum values sent to or read from the API are unchanged.
const ko = {
  loadFailed: (reason: string) => `설정을 불러오지 못했습니다: ${reason}`,
  saved: "설정을 저장했습니다.",
  saveFailed: (reason: string) => `저장하지 못했습니다: ${reason}`,
  userFallback: (id: number) => `사용자 #${id}`,
  // 자금계정
  activeInactive: (active: number, inactive: number) => `활성 ${active} · 비활성 ${inactive}`,
  accountInactive: "사용 안 함",
  // 사장 정산
  participantChangeMonth: "변경 적용월",
  participantStartMonth: "투자자 구성 시작월",
  selectedOfThree: (count: number) => `${count} / 3명`,
  participantStartHelp: "가게 운영 시작 당시 투자자 구성이 시작된 월을 선택하세요.",
  saveParticipants: "투자자 구성 저장",
  compositionStart: "구성 시작월",
  notSet: "미설정",
  investors: "투자자",
  peopleCount: (count: number) => `${count}명`,
  recoveryBasis: "투자금 회수 기준",
  recoveryBasisValue: "미회수 원금 비례",
  profitShareRate: "이익 배분 비율",
  configured: "설정됨",
  investorComposition: "투자자 구성",
  investorsFirst: "먼저 투자자 3명을 설정해주세요.",
  profitShareHelp: "※ 이 비율은 투자금 회수 완료 후 이익 배분에 적용됩니다.",
  // compact setting rows (view ↔ edit)
  change: "변경",
  setup: "설정",
  close: "닫기",
  selectInvestors: "투자자 선택",
  appliedFrom: (month: string) => `${month}부터 적용`,
  applyMonth: "적용월",
  rateTotalOf: (total: string) => `${total} / 100%`,
  rateMustBe100: "합계가 100%여야 저장할 수 있습니다.",
  profitShareTotal: "이익 배분 비율 합계",
  saveProfitShare: "이익 배분 비율 저장",
  // 준비금
  reserves: "준비금",
  closeAdd: "추가 닫기",
  addReserve: "+ 준비금 추가",
  reserveInfo: "ℹ️ 준비금은 실제 계좌 잔액이나 장부 비용을 변경하지 않습니다. 실제 지급은 장부작성에서 별도로 기록합니다.",
  reserveName: "준비금 이름",
  targetAmount: "목표 금액",
  targetDate: "목표일",
  linkedAccount: "연결 계좌",
  unlinked: "미연결",
  memo: "메모",
  createPlanHelp: "계획을 추가하거나 계좌를 연결해도 목표 금액이 자동으로 적립되지 않습니다. 실제 확보 금액은 적립 기록 또는 pending 확정으로만 늘어납니다.",
  createPlan: "준비금 계획 추가",
  planOverline: "준비금 계획",
  accountNotSet: "연결 계좌 미설정",
  recurringOn: "정기 적립 설정됨",
  recurringOff: "정기 적립 미설정",
  currentAmount: "현재 확보 금액",
  shortfallAria: "부족 금액",
  remainingAmount: "남은 금액",
  pendingTitle: "확정 대기 중",
  pendingPlanned: (month: string, amount: string) => `${month} 적립 예정 · ${amount}`,
  pendingHelp: "확정하면 실제 준비금이 증가합니다.",
  confirmAllocation: "적립 확정",
  skipReasonPrompt: "건너뛰기 사유",
  skip: "건너뛰기",
  sectionPlan: "계획 정보",
  sectionRecurring: "정기 적립",
  sectionEntry: "직접 조정",
  sectionHistory: "이력",
  accountLocked: "확보된 준비금이 있어 연결 계좌를 변경할 수 없습니다. 먼저 준비금을 전액 해제하세요.",
  accountLinkHelp: "계좌 연결만으로 준비금이 자동 적립되지는 않습니다.",
  updatePlan: "계획 수정",
  amount: "금액",
  occurredAt: "일시",
  recordEntry: (label: string) => `${label} 기록`,
  entryDescriptions: {
    allocate: "준비금으로 금액을 확보합니다.",
    release: "묶어둔 준비금을 다시 사용 가능 상태로 돌립니다.",
    consume: "준비금 사용 기록이며 실제 장부 지출을 생성하는 기능이 아니며, 실제 비용 지급은 기존 장부 거래 흐름에서 별도 처리합니다.",
    adjustment: "관리상 필요한 준비금 보정 기록입니다.",
  } as Record<string, string>,
  recurringInfoLine1: "ℹ️ 정기 적립 예정이 생성되어도 준비금은 바로 증가하지 않습니다.",
  recurringInfoLine2: "관리자가 확정한 경우에만 실제 준비금에 반영됩니다.",
  monthlyAmount: "월 적립액",
  recurringDay: "매월 적립일",
  startMonth: "시작월",
  endMonth: "종료월",
  endMonthAria: "종료월(선택)",
  autoGenerate: "자동 예정 생성",
  autoGenerateHelp: "매월 적립일 이후 예정이 자동으로 생성됩니다.",
  autoGenerateNeedsAccount: "자동 예정 생성은 연결 계좌가 필요합니다. 계획 정보에서 계좌를 먼저 연결하세요.",
  manualGenerateHelp: "자동 예정 생성이 꺼져 있어도 “이번 달 예정 생성” 버튼으로 수동 생성할 수 있습니다.",
  saveRecurring: "정기 적립 저장",
  clearRecurring: "설정 해제",
  generateThisMonth: "이번 달 예정 생성",
  targetReached: "목표 금액을 달성하여 신규 정기 적립 예정이 생성되지 않습니다.",
  scheduledCount: "정기 예정",
  entryCount: "준비금 기록",
  itemCount: (count: number) => `${count}건`,
  noHistory: "아직 준비금 이력이 없습니다.",
  scheduledHistory: "정기 적립 예정",
  noNote: "비고 없음",
  noMemo: "메모 없음",
  scheduleStatus: { pending: "확정 대기", confirmed: "확정됨", skipped: "건너뜀", superseded: "대체됨" } as Record<string, string>,
  dateLocale: "ko-KR",
};

const vi: typeof ko = {
  loadFailed: (reason: string) => `Không thể tải cài đặt: ${reason}`,
  saved: "Đã lưu cài đặt.",
  saveFailed: (reason: string) => `Không thể lưu: ${reason}`,
  userFallback: (id: number) => `Người dùng #${id}`,
  activeInactive: (active: number, inactive: number) => `Đang dùng ${active} · Ngừng dùng ${inactive}`,
  accountInactive: "Ngừng dùng",
  participantChangeMonth: "Tháng áp dụng thay đổi",
  participantStartMonth: "Tháng bắt đầu cơ cấu nhà đầu tư",
  selectedOfThree: (count: number) => `${count} / 3 người`,
  participantStartHelp: "Chọn tháng bắt đầu cơ cấu nhà đầu tư khi cửa hàng bắt đầu hoạt động.",
  saveParticipants: "Lưu cơ cấu nhà đầu tư",
  compositionStart: "Tháng bắt đầu cơ cấu",
  notSet: "Chưa thiết lập",
  investors: "Nhà đầu tư",
  peopleCount: (count: number) => `${count} người`,
  recoveryBasis: "Cơ sở thu hồi vốn",
  recoveryBasisValue: "Theo tỷ lệ vốn chưa thu hồi",
  profitShareRate: "Tỷ lệ chia lợi nhuận",
  configured: "Đã thiết lập",
  investorComposition: "Cơ cấu nhà đầu tư",
  investorsFirst: "Hãy thiết lập 3 nhà đầu tư trước.",
  profitShareHelp: "※ Tỷ lệ này áp dụng khi chia lợi nhuận sau khi đã thu hồi xong vốn đầu tư.",
  change: "Thay đổi",
  setup: "Thiết lập",
  close: "Đóng",
  selectInvestors: "Chọn nhà đầu tư",
  appliedFrom: (month: string) => `Áp dụng từ ${month}`,
  applyMonth: "Tháng áp dụng",
  rateTotalOf: (total: string) => `${total} / 100%`,
  rateMustBe100: "Tổng phải bằng 100% mới lưu được.",
  profitShareTotal: "Tổng tỷ lệ chia lợi nhuận",
  saveProfitShare: "Lưu tỷ lệ chia lợi nhuận",
  reserves: "Quỹ dự phòng",
  closeAdd: "Đóng",
  addReserve: "+ Thêm quỹ dự phòng",
  reserveInfo: "ℹ️ Quỹ dự phòng không thay đổi số dư tài khoản thực tế hay chi phí trong sổ. Khoản chi thực tế được ghi riêng ở Ghi sổ.",
  reserveName: "Tên quỹ dự phòng",
  targetAmount: "Số tiền mục tiêu",
  targetDate: "Ngày mục tiêu",
  linkedAccount: "Tài khoản liên kết",
  unlinked: "Chưa liên kết",
  memo: "Ghi chú",
  createPlanHelp: "Thêm kế hoạch hoặc liên kết tài khoản không tự động trích lập số tiền mục tiêu. Số tiền thực có chỉ tăng khi ghi trích lập hoặc xác nhận khoản chờ.",
  createPlan: "Thêm kế hoạch quỹ dự phòng",
  planOverline: "Kế hoạch quỹ dự phòng",
  accountNotSet: "Chưa liên kết tài khoản",
  recurringOn: "Đã thiết lập trích lập định kỳ",
  recurringOff: "Chưa thiết lập trích lập định kỳ",
  currentAmount: "Số tiền hiện có",
  shortfallAria: "Số tiền còn thiếu",
  remainingAmount: "Còn lại",
  pendingTitle: "Đang chờ xác nhận",
  pendingPlanned: (month: string, amount: string) => `Dự kiến trích lập ${month} · ${amount}`,
  pendingHelp: "Khi xác nhận, quỹ dự phòng thực tế sẽ tăng.",
  confirmAllocation: "Xác nhận trích lập",
  skipReasonPrompt: "Lý do bỏ qua",
  skip: "Bỏ qua",
  sectionPlan: "Thông tin kế hoạch",
  sectionRecurring: "Trích lập định kỳ",
  sectionEntry: "Điều chỉnh trực tiếp",
  sectionHistory: "Lịch sử",
  accountLocked: "Đã có quỹ dự phòng nên không thể đổi tài khoản liên kết. Hãy giải phóng toàn bộ quỹ trước.",
  accountLinkHelp: "Chỉ liên kết tài khoản sẽ không tự động trích lập quỹ dự phòng.",
  updatePlan: "Sửa kế hoạch",
  amount: "Số tiền",
  occurredAt: "Thời điểm",
  recordEntry: (label: string) => `Ghi ${label.toLocaleLowerCase("vi-VN")}`,
  entryDescriptions: {
    allocate: "Dành riêng số tiền vào quỹ dự phòng.",
    release: "Trả quỹ dự phòng đã giữ về trạng thái có thể sử dụng.",
    consume: "Đây là ghi nhận sử dụng quỹ dự phòng, không tạo khoản chi thực tế trong sổ; khoản chi thực tế được xử lý riêng theo luồng giao dịch sổ hiện có.",
    adjustment: "Ghi nhận điều chỉnh quỹ dự phòng khi cần cho quản lý.",
  },
  recurringInfoLine1: "ℹ️ Khi có lịch trích lập định kỳ, quỹ dự phòng chưa tăng ngay.",
  recurringInfoLine2: "Chỉ khi quản lý xác nhận thì mới được ghi vào quỹ dự phòng thực tế.",
  monthlyAmount: "Số tiền mỗi tháng",
  recurringDay: "Ngày trích lập hằng tháng",
  startMonth: "Tháng bắt đầu",
  endMonth: "Tháng kết thúc",
  endMonthAria: "Tháng kết thúc (tùy chọn)",
  autoGenerate: "Tự tạo lịch",
  autoGenerateHelp: "Lịch sẽ tự được tạo sau ngày trích lập hằng tháng.",
  autoGenerateNeedsAccount: "Tự tạo lịch cần tài khoản liên kết. Hãy liên kết tài khoản trong Thông tin kế hoạch trước.",
  manualGenerateHelp: "Dù tắt tự tạo lịch, vẫn có thể tạo thủ công bằng nút “Tạo lịch tháng này”.",
  saveRecurring: "Lưu trích lập định kỳ",
  clearRecurring: "Hủy thiết lập",
  generateThisMonth: "Tạo lịch tháng này",
  targetReached: "Đã đạt số tiền mục tiêu nên không tạo lịch trích lập định kỳ mới.",
  scheduledCount: "Lịch định kỳ",
  entryCount: "Ghi nhận quỹ",
  itemCount: (count: number) => `${count} mục`,
  noHistory: "Chưa có lịch sử quỹ dự phòng.",
  scheduledHistory: "Lịch trích lập định kỳ",
  noNote: "Không có ghi chú",
  noMemo: "Không có ghi chú",
  scheduleStatus: { pending: "Chờ xác nhận", confirmed: "Đã xác nhận", skipped: "Đã bỏ qua", superseded: "Đã thay thế" },
  dateLocale: "vi-VN",
};

export const ledgerSettingsText = { ko, vi };
export type LedgerSettingsCopy = typeof ko;
