export const INVENTORY_REASON_VALUES = [
  "purchase",
  "stock_check",
  "service",
  "other",
  "sale_deduction",
  "unclassified",
] as const;

export type InventoryReasonValue = (typeof INVENTORY_REASON_VALUES)[number];

export const INVENTORY_SOURCE_VALUES = [
  "quick_save",
  "edit_form",
  "create",
  "delete",
  "photo",
  "pos_sales",
  "keg_replace",
  "system",
] as const;

export type InventorySourceValue = (typeof INVENTORY_SOURCE_VALUES)[number];

export const INVENTORY_REGISTRATION_TYPES = [
  "existing_stock",
  "new_purchase",
] as const;

export type InventoryRegistrationType =
  (typeof INVENTORY_REGISTRATION_TYPES)[number];

export type QuickReasonValue = Exclude<
  InventoryReasonValue,
  "sale_deduction" | "unclassified"
>;

export const QUICK_REASON_VALUES = [
  "purchase",
  "stock_check",
  "service",
  "other",
] as const satisfies readonly QuickReasonValue[];

export const INVENTORY_REASON_EMOJIS = {
  purchase: "🛒",
  stock_check: "✅",
  service: "🎁",
  other: "✏️",
  sale_deduction: "🔴",
  unclassified: "❔",
} satisfies Record<InventoryReasonValue, string>;

export const INVENTORY_REASON_META = {
  purchase: { emoji: INVENTORY_REASON_EMOJIS.purchase },
  stock_check: { emoji: INVENTORY_REASON_EMOJIS.stock_check },
  service: { emoji: INVENTORY_REASON_EMOJIS.service },
  other: { emoji: INVENTORY_REASON_EMOJIS.other },
  sale_deduction: { emoji: INVENTORY_REASON_EMOJIS.sale_deduction },
  unclassified: { emoji: INVENTORY_REASON_EMOJIS.unclassified },
} satisfies Record<InventoryReasonValue, { emoji: string }>;

export const INVENTORY_REASON_LABELS = {
  ko: {
    purchase: "구매입고",
    stock_check: "재고확인",
    service: "서비스/증정",
    other: "기타",
    sale_deduction: "판매차감",
    unclassified: "미분류",
  },
  vi: {
    purchase: "Nhap mua",
    stock_check: "Kiem tra kho",
    service: "Dich vu/tang",
    other: "Khac",
    sale_deduction: "Trừ kho bán hàng",
    unclassified: "Chua phan loai",
  },
} satisfies Record<
  "ko" | "vi",
  Record<InventoryReasonValue, string>
>;

export function normalizeInventoryReason(
  value: unknown,
  fallback: InventoryReasonValue = "unclassified"
): InventoryReasonValue {
  if (value === "check") return "stock_check";
  return INVENTORY_REASON_VALUES.includes(value as InventoryReasonValue)
    ? (value as InventoryReasonValue)
    : fallback;
}

export function normalizeInventorySource(
  value: unknown,
  fallback: InventorySourceValue = "system"
): InventorySourceValue {
  return INVENTORY_SOURCE_VALUES.includes(value as InventorySourceValue)
    ? (value as InventorySourceValue)
    : fallback;
}

export function getReasonByRegistrationType(
  value: unknown
): InventoryReasonValue {
  if (value === "new_purchase") return "purchase";
  return "stock_check";
}

export function isPurchaseReason(value: unknown) {
  return normalizeInventoryReason(value) === "purchase";
}

export function getCompactReasonLabel(
  reason: InventoryReasonValue | null | undefined,
  lang: "ko" | "vi"
): string {
  if (lang === "vi") {
    if (reason === "purchase") return "Nhập";
    if (reason === "stock_check") return "Kiểm";
    if (reason === "service") return "Tặng";
    if (reason === "other") return "Khác";
    if (reason === "sale_deduction") return "Trừ bán";
    return "Khác";
  }
  if (reason === "purchase") return "입고";
  if (reason === "stock_check") return "확인";
  if (reason === "service") return "증정";
  if (reason === "other") return "기타";
  if (reason === "sale_deduction") return "판매차감";
  return "기타";
}

export type InventoryReasonBadgeMeta = {
  text: string;
  style: { background: string; color: string; border: string };
};

const REASON_BADGE_STYLE = {
  background: "#f3f4f6",
  color: "#374151",
  border: "1px solid #e5e7eb",
} as const;

export function getInventoryReasonBadgeMeta(
  reason: string | null | undefined,
  source: string | null | undefined,
  lang: "ko" | "vi"
): InventoryReasonBadgeMeta | null {
  const effectiveReason: InventoryReasonValue =
    source === "pos_sales"
      ? "sale_deduction"
      : INVENTORY_REASON_VALUES.includes(reason as InventoryReasonValue)
      ? (reason as InventoryReasonValue)
      : "unclassified";

  if (effectiveReason === "unclassified") return null;

  return {
    text: `${INVENTORY_REASON_EMOJIS[effectiveReason]} ${getCompactReasonLabel(effectiveReason, lang)}`,
    style: REASON_BADGE_STYLE,
  };
}

const AUTO_NOTE_REASON_LABELS: ReadonlySet<string> = new Set([
  // Full labels from INVENTORY_REASON_LABELS (both langs)
  "구매입고", "재고확인", "서비스/증정", "기타", "판매차감", "미분류",
  "Nhap mua", "Kiem tra kho", "Dich vu/tang", "Khac", "Trừ kho bán hàng", "Chua phan loai",
  // Compact labels (getCompactReasonLabel)
  "입고", "확인", "증정", "Nhập", "Kiểm", "Tặng", "Trừ bán",
  // Additional variants seen in stored notes
  "서비스", "Kiểm tra kho", "Khác", "v.v.",
]);

export function isAutoGeneratedInventoryNote(note: string): boolean {
  if (!note) return false;
  const match = note.trim().match(/^[+\-][\d.,]+ \(([^)]+)\)$/);
  if (!match) return false;
  return AUTO_NOTE_REASON_LABELS.has(match[1].trim());
}
