"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import Container from "@/components/Container";
import { ui } from "@/lib/styles/ui";
import InventoryCandidatePanel from "./InventoryCandidatePanel";
import MonthClosePanel from "./MonthClosePanel";
import RecurringReserveBepPanel from "./RecurringReserveBepPanel";
import styles from "./ledger.module.css";
import extra from "./ledger-extra.module.css";

type Account={id:number;display_name:string;balance:number;is_active:boolean};
type Category={id:number;name:string;kind:"income"|"expense"};type Party={id:number;name:string};
type Transaction={id:number;type:string;business_date:string;amount:number;economic_effect_sign?:number;correction_of_id?:number|null;status:string;source_type:string;source_key:string|null;memo:string|null;category:{name:string}|null;party:{name:string}|null};
type LedgerData={summary:{income:number;expense:number;operatingProfit:number};accounts:Account[];categories:Category[];parties:Party[];transactions:Transaction[]};
type CloseItem={code:string;count?:number;amount?:number};type CloseData={state:"open"|"closed";preflight?:{canClose:boolean;blockers:CloseItem[];warnings:CloseItem[]}};
type Meta={freeCash:number;reserveShortfall:number;pendingCandidates:number;close:CloseData|null};
type EntryType="expense"|"income"|"transfer"|"balance_adjustment";type SyncKey="pos"|"inventory"|"meal"|"payroll"|"recurring";

const currentMonth=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit"}).format(new Date()).slice(0,7);
const localTime=()=>new Date(Date.now()+7*3_600_000).toISOString().slice(0,16);
const formatter=new Intl.NumberFormat("vi-VN",{maximumFractionDigits:0});
const money=(value:number)=>`${formatter.format(Math.round(value))} ₫`;
const syncActions:Array<{key:SyncKey;label:string;path:string}>=[
  {key:"pos",label:"POS 매출",path:"/api/admin/ledger/pos-sync"},{key:"inventory",label:"재고",path:"/api/admin/ledger/inventory-candidates/sync"},
  {key:"meal",label:"식대",path:"/api/admin/ledger/meal-candidates/sync"},{key:"payroll",label:"급여",path:"/api/admin/ledger/payroll/sync"},
  {key:"recurring",label:"반복비용",path:"/api/admin/ledger/recurring-expenses/sync"},
];

export default function LedgerPage(){
  const[month,setMonth]=useState(currentMonth),[data,setData]=useState<LedgerData|null>(null),[meta,setMeta]=useState<Meta>({freeCash:0,reserveShortfall:0,pendingCandidates:0,close:null});
  const[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[formOpen,setFormOpen]=useState(false),[saving,setSaving]=useState(false),[syncing,setSyncing]=useState<SyncKey|null>(null),[closed,setClosed]=useState(false);
  const[drilldown,setDrilldown]=useState<Record<string,unknown>|null>(null);
  const[type,setType]=useState<EntryType>("expense"),[amount,setAmount]=useState(""),[occurredAt,setOccurredAt]=useState(localTime),[recognitionMonth,setRecognitionMonth]=useState(currentMonth),[categoryId,setCategoryId]=useState(""),[partyId,setPartyId]=useState(""),[fromAccountId,setFromAccountId]=useState(""),[toAccountId,setToAccountId]=useState(""),[memo,setMemo]=useState(""),[reason,setReason]=useState("");

  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");try{
    const responses=await Promise.all([fetch(`/api/admin/ledger?month=${month}`,{cache:"no-store",signal}),fetch("/api/admin/ledger/reserves",{cache:"no-store",signal}),fetch(`/api/admin/ledger/candidates?month=${month}&status=pending&type=all`,{cache:"no-store",signal}),fetch(`/api/admin/ledger/month-close?month=${month}`,{cache:"no-store",signal})]);
    const bodies=await Promise.all(responses.map(response=>response.json())),failed=responses.findIndex(response=>!response.ok);if(failed>=0)throw new Error(bodies[failed]?.code??"LOAD_FAILED");
    const plans=bodies[1].plans as Array<{remainingAmount?:number}>;setData(bodies[0]);setMeta({freeCash:Number(bodies[1].freeCash??0),reserveShortfall:plans.reduce((sum,plan)=>sum+Number(plan.remainingAmount??0),0),pendingCandidates:(bodies[2].candidates as unknown[]).length,close:bodies[3]});setClosed(bodies[3].state==="closed");
  }catch(cause){if((cause as Error).name!=="AbortError")setError("장부를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.")}finally{if(!signal?.aborted)setLoading(false)}},[month]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort()},[load]);
  const categories=useMemo(()=>data?.categories.filter(category=>category.kind===(type==="income"?"income":"expense"))??[],[data,type]);
  const selectedCategoryId=categories.some(category=>String(category.id)===categoryId)?categoryId:String(categories[0]?.id??"");const accounts=data?.accounts.filter(account=>account.is_active)??[];const adjustmentPositive=!amount.startsWith("-");

  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");const payload={type,amount:Math.abs(Number(amount)),occurredAt:`${occurredAt}:00+07:00`,recognitionMonth:type==="income"||type==="expense"?`${recognitionMonth}-01`:null,categoryId:type==="income"||type==="expense"?Number(selectedCategoryId):null,partyId: partyId ? Number(partyId) : null,fromAccountId:type==="expense"||type==="transfer"||type==="balance_adjustment"&&!adjustmentPositive?Number(fromAccountId):null,toAccountId:type==="income"||type==="transfer"||type==="balance_adjustment"&&adjustmentPositive?Number(toAccountId):null,memo,reason};try{const response=await fetch("/api/admin/ledger",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error("SAVE_FAILED");setFormOpen(false);setAmount("");setMemo("");setReason("");setPartyId("");await load()}catch{setError("거래를 등록하지 못했습니다. 입력 내용을 확인한 뒤 다시 시도해 주세요.")}finally{setSaving(false)}}
  async function runSync(action:(typeof syncActions)[number]){setSyncing(action.key);setError("");setNotice("");try{const response=await fetch(action.path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({month})}),body=await response.json();if(!response.ok)throw new Error("SYNC_FAILED");setNotice(`${action.label} 데이터를 동기화했습니다. 새 항목 ${body.createdCount??0}건, 변경 ${body.supersededCount??body.updatedCount??0}건`);await load()}catch{setError(`${action.label} 데이터를 동기화하지 못했습니다. 잠시 후 다시 시도해 주세요.`)}finally{setSyncing(null)}}
  async function openPosDrilldown(transactionId:number){try{const response=await fetch(`/api/admin/ledger/transactions/${transactionId}/pos-drilldown`,{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error("LOAD_FAILED");setDrilldown(body.drilldown)}catch{setError("POS 영수증 상세를 불러오지 못했습니다.")}}

  return <Container><main className={styles.page}>
    <header className={styles.header}><div><p className={styles.eyebrow}>재무 관리</p><h1 className={styles.title}>가게 장부</h1></div><div className={styles.headerControls}><label className={styles.monthControl}><span>조회 월</span><input type="month" value={month} onChange={event=>setMonth(event.target.value)} style={ui.input}/></label><button type="button" disabled={closed} className={styles.primaryButton} onClick={()=>setFormOpen(value=>!value)}>{formOpen?"등록 닫기":"거래 등록"}</button><details className={styles.moreMenu}><summary>더보기</summary><div className={styles.moreMenuBody}><a href="#data-sync">데이터 동기화</a><a href="#month-close">월마감 관리</a><a href="#reserve-bep">준비금 · BEP</a></div></details></div></header>
    <nav aria-label="장부 메뉴" className={styles.subnav}><Link href="/admin/ledger" aria-current="page">장부 홈</Link><a href="#transactions">거래</a><Link href="/admin/ledger/payables">미지급금</Link><Link href="/admin/ledger/card-settlements">카드정산</Link><a href="#month-close">월마감</a><a href="#reserve-bep">준비금 · BEP</a><Link href="/admin/ledger/owners">사장 정산</Link></nav>
    {error?<p role="alert" className={styles.error}>{error}</p>:null}{notice?<p role="status" className={styles.success}>{notice}</p>:null}
    {loading?<div className={styles.emptyState}>장부를 불러오는 중입니다…</div>:data?<>
      <section aria-labelledby="summary-heading"><Heading kicker={month.replace("-",".")} title="이번 달 요약" id="summary-heading"/><div className={styles.summaryGrid}><Summary label="매출" value={data.summary.income} tone="income"/><Summary label="비용" value={data.summary.expense} tone="expense"/><Summary label="영업이익" value={data.summary.operatingProfit} tone="profit"/><Summary label="사용가능 현금" value={meta.freeCash} tone="cash"/></div>{data.summary.income===0&&!data.transactions.some(transaction=>transaction.source_type==="pos_sales_daily_payment")?<p className={styles.emptyHint}>아직 이번 달 매출이 장부에 동기화되지 않았습니다.</p>:null}</section>
      <CloseAlert month={month} meta={meta}/>
      {formOpen?<form onSubmit={submit} className={styles.form}><Heading kicker="새 거래" title="거래 등록"/><div className={styles.formGrid}><Field label="유형"><select value={type} onChange={event=>setType(event.target.value as EntryType)} style={ui.input}><option value="expense">즉시 지출</option><option value="income">기타 수입</option><option value="transfer">내부 계정이체</option><option value="balance_adjustment">잔액조정</option></select></Field><Field label={type==="balance_adjustment"?"금액 (+/−)":"금액"}><input required inputMode="numeric" value={amount} onChange={event=>setAmount(event.target.value)} style={ui.input}/></Field><Field label="발생·지급일"><input required type="datetime-local" value={occurredAt} onChange={event=>setOccurredAt(event.target.value)} style={ui.input}/></Field>{type==="income"||type==="expense"?<><Field label="손익 귀속월"><input required type="month" value={recognitionMonth} onChange={event=>setRecognitionMonth(event.target.value)} style={ui.input}/></Field><Field label="카테고리"><select required value={selectedCategoryId} onChange={event=>setCategoryId(event.target.value)} style={ui.input}>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></Field></>:null}{type==="expense"?<Field label="거래처 (선택)"><select value={partyId} onChange={event=>setPartyId(event.target.value)} style={ui.input}><option value="">없음</option>{data.parties.map(party=><option key={party.id} value={party.id}>{party.name}</option>)}</select></Field>:null}{type==="expense"||type==="transfer"||type==="balance_adjustment"&&!adjustmentPositive?<AccountSelect label="출금·감소 계정" value={fromAccountId} setValue={setFromAccountId} accounts={accounts}/>:null}{type==="income"||type==="transfer"||type==="balance_adjustment"&&adjustmentPositive?<AccountSelect label="입금·증가 계정" value={toAccountId} setValue={setToAccountId} accounts={accounts}/>:null}{type==="balance_adjustment"?<Field label="조정 사유"><input required value={reason} onChange={event=>setReason(event.target.value)} style={ui.input}/></Field>:null}<Field label="메모 (선택)"><input value={memo} onChange={event=>setMemo(event.target.value)} style={ui.input}/></Field></div><button disabled={saving} className={styles.primaryButton}>{saving?"저장 중…":"거래 저장"}</button></form>:null}
      <section id="data-sync" className={styles.cardSection}><Heading kicker="원본 데이터 가져오기" title="데이터 동기화"/><div className={styles.syncGrid}>{syncActions.map(action=><button key={action.key} type="button" disabled={syncing!==null} className={styles.syncButton} onClick={()=>void runSync(action)}>{syncing===action.key?"동기화 중…":`${action.label} 동기화`}</button>)}</div></section>
      <section id="transactions"><Heading kicker="최근 50건" title="최근 거래" id="transactions-heading"/><TransactionList transactions={data.transactions} openPos={openPosDrilldown}/></section>
      <section className={styles.quickLinks}><QuickLink href="/admin/ledger/payables" title="미지급금" description="거래처별 잔액과 지급 내역"/><QuickLink href="/admin/ledger/card-settlements" title="카드정산" description="카드 입금과 매출 연결"/><QuickLink href="/admin/ledger/owners" title="사장 정산" description="투자금, 배정과 실제 지급"/></section>
      <WorkSection id="candidate-management" title="장부 후보 관리" description="동기화된 재고·식대·급여 후보를 확인합니다."><InventoryCandidatePanel month={month}/></WorkSection>
      <WorkSection id="account-balances" title="현재 계정별 장부잔액" description="현금과 계좌별 장부 잔액을 확인합니다."><div className={extra.balanceGrid}>{data.accounts.map(account=><article key={account.id}><span>{account.display_name}</span><strong>{money(account.balance)}</strong></article>)}</div></WorkSection>
      <WorkSection id="month-close" title="월마감 상세" description="마감 조건과 상세 점검 결과를 확인합니다."><MonthClosePanel month={month} onState={setClosed}/></WorkSection>
      <WorkSection id="reserve-bep" title="준비금 · BEP 관리" description="준비금 목표, 임대료 지급과 손익분기점을 관리합니다."><RecurringReserveBepPanel month={month} accounts={data.accounts} onChanged={load}/></WorkSection>
      {drilldown?<section className={styles.cardSection}><div className={styles.sectionHeading}><h2>POS 영수증 상세</h2><button type="button" className={extra.textButton} onClick={()=>setDrilldown(null)}>닫기</button></div><p>원본 합계 {money(Number(drilldown.sourceAmount??0))} · 장부 반영 {money(Number(drilldown.ledgerAmount??0))}</p></section>:null}
    </>:null}
  </main></Container>;
}

function Heading({kicker,title,id}:{kicker:string;title:string;id?:string}){return <div className={styles.sectionHeading}><div><p className={styles.eyebrow}>{kicker}</p><h2 id={id}>{title}</h2></div></div>}
function Summary({label,value,tone}:{label:string;value:number;tone:string}){return <article className={`${styles.summaryCard} ${styles[tone]}`}><span>{label}</span><strong>{money(value)}</strong></article>}
function CloseAlert({month,meta}:{month:string;meta:Meta}){if(meta.close?.state==="closed")return <section className={`${styles.alertCard} ${styles.alertSuccess}`}><div><p className={styles.eyebrow}>월마감</p><h2>{month.replace("-", ".")} 마감 완료</h2></div><a href="#month-close">상세 보기</a></section>;const blockers=meta.close?.preflight?.blockers??[],messages=blockers.map(blockerMessage);if(meta.pendingCandidates>0&&!blockers.some(item=>item.code==="PENDING_CANDIDATES"))messages.unshift(`미처리 후보 ${meta.pendingCandidates.toLocaleString("ko-KR")}건`);if(meta.reserveShortfall>0&&!blockers.some(item=>item.code==="RESERVE_SHORTFALL"))messages.push(`준비금 ${money(meta.reserveShortfall)} 부족`);return <section className={styles.alertCard}><div><p className={styles.eyebrow}>확인 필요</p><h2>{messages.length?"이번 달 마감 전에 확인해 주세요":"마감 준비가 완료되었습니다"}</h2>{messages.length?<ul>{messages.slice(0,3).map((message,index)=><li key={`${message}-${index}`}>{message}</li>)}</ul>:null}</div><a href="#month-close">월마감 상세</a></section>}
function blockerMessage(item:CloseItem){if(item.code==="CURRENT_MONTH")return "아직 진행 중인 달입니다";if(item.code==="PENDING_CANDIDATES")return `확인하지 않은 장부 후보 ${(item.count??0).toLocaleString("ko-KR")}건`;if(item.code==="RESERVE_SHORTFALL")return `준비금 ${money(Number(item.amount??0))} 부족`;if(item.code==="INSUFFICIENT_REVENUE")return "매출 데이터가 부족해 아직 계산할 수 없습니다";return "마감 전에 확인할 항목이 있습니다"}
function TransactionList({transactions,openPos}:{transactions:Transaction[];openPos:(id:number)=>Promise<void>}){if(!transactions.length)return <div className={styles.emptyState}><strong>아직 등록된 거래가 없습니다.</strong><span>거래를 등록하거나 원본 데이터를 동기화해 주세요.</span></div>;return <div className={styles.transactionTable}><div className={styles.tableHeader}><span>날짜</span><span>구분</span><span>내용</span><span>금액</span></div>{transactions.map(transaction=>{const expense=transaction.economic_effect_sign===-1||transaction.type==="expense"||transaction.type==="expense_recognition",automatic=transaction.source_type === "pos_sales_daily_payment",title=automatic?posLabel(transaction.source_key):transaction.source_type==="payroll_completed_batch"?"급여 · 인건비":transaction.source_type==="attendance_meal_daily_candidate"?"직원 식대":transaction.memo||transaction.party?.name||transactionLabel(transaction.type);return <article key={transaction.id} className={styles.transactionRow}><time dateTime={transaction.business_date}>{transaction.business_date.replaceAll("-",".")}</time><span className={styles.typeBadge}>{transaction.correction_of_id?"정정":expense?"비용":transaction.type==="income"||transaction.type==="sales"?"수입":"이체"}</span><div className={styles.transactionContent}><strong>{title}</strong><small>{transaction.category?.name??"손익 제외"}</small>{automatic?<button type="button" className={extra.textButton} onClick={()=>void openPos(transaction.id)}>POS 영수증 상세</button>:null}</div><strong className={expense?styles.negativeAmount:styles.positiveAmount}><span>{expense?"지출 ":"입금 "}</span>{expense?"−":"+"}{money(Math.abs(transaction.amount))}</strong></article>})}</div>}
function QuickLink({href,title,description}:{href:string;title:string;description:string}){return <Link href={href} className={styles.quickLink}><span><strong>{title}</strong><small>{description}</small></span><span aria-hidden>→</span></Link>}
function WorkSection({id,title,description,children}:{id:string;title:string;description:string;children:ReactNode}){return <details id={id} className={styles.workSection}><summary><span><strong>{title}</strong><small>{description}</small></span><span>열기</span></summary><div className={styles.workBody}>{children}</div></details>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className={styles.field}>{label}{children}</label>}
// Existing UI contract terminology: 출금/감소 계정
function AccountSelect({label,value,setValue,accounts}:{label:string;value:string;setValue:(value:string)=>void;accounts:Account[]}){return <Field label={label}><select required value={value} onChange={event=>setValue(event.target.value)} style={ui.input}><option value="">선택</option>{accounts.map(account=><option key={account.id} value={account.id}>{account.display_name}</option>)}</select></Field>}
function transactionLabel(type:string){return({expense:"지출",income:"수입",transfer:"내부이체",balance_adjustment:"잔액조정",sales:"매출",expense_recognition:"비용 인식"}as Record<string,string>)[type]??"기타 거래"}
function posLabel(sourceKey:string|null){const bucket=sourceKey?.split(":").at(-1);return({cash:"POS 현금 매출",transfer:"POS 계좌이체 매출",card:"POS 카드 매출",other:"POS 기타 매출"}as Record<string,string>)[bucket??""]??"POS 매출"}
