import {ledgerJson,requireLedgerActor} from "@/lib/ledger/server";
import {supabaseServer} from "@/lib/supabase/server";
export const dynamic="force-dynamic";
const MONTH=/^\d{4}-(0[1-9]|1[0-2])$/;

export async function GET(request:Request){const auth=await requireLedgerActor();if(auth.response)return auth.response;const month=new URL(request.url).searchParams.get("month")??"";if(!MONTH.test(month))return ledgerJson({ok:false,code:"INVALID_MONTH"},400);try{const start=`${month}-01`,next=new Date(`${start}T00:00:00Z`);next.setUTCMonth(next.getUTCMonth()+1);const end=next.toISOString().slice(0,10);const[accountResult,movementResult,saleResult,reconciliationResult,lineResult]=await Promise.all([
 supabaseServer.from("ledger_fund_accounts").select("id,code,display_name,type,is_active").eq("is_active",true).order("sort_order"),
 supabaseServer.from("ledger_movements").select("fund_account_id,amount,transaction:ledger_transactions!inner(status)").eq("transaction.status","confirmed"),
 supabaseServer.from("ledger_transactions").select("id,business_date,amount,source_key,memo").eq("source_type","pos_sales_daily_payment").like("source_key","pos:%:card").eq("status","confirmed").order("business_date"),
 supabaseServer.from("ledger_card_reconciliations").select("id,deposit_transaction_id,deposit_date,destination_fund_account_id,deposit_amount,matched_gross_amount,difference_amount,status,confirmed_at,memo,destination:ledger_fund_accounts(display_name)").neq("status","cancelled").order("deposit_date",{ascending:false}),
 supabaseServer.from("ledger_card_reconciliation_lines").select("id,reconciliation_id,pos_card_transaction_id,allocated_gross_amount")]);
 for(const result of[accountResult,movementResult,saleResult,reconciliationResult,lineResult])if(result.error)throw result.error;const accounts=accountResult.data??[],lines=lineResult.data??[],reconciliations=reconciliationResult.data??[],activeIds=new Set(reconciliations.map(r=>Number(r.id)));const allocated=new Map<number,number>();for(const line of lines)if(activeIds.has(Number(line.reconciliation_id)))allocated.set(Number(line.pos_card_transaction_id),(allocated.get(Number(line.pos_card_transaction_id))??0)+Number(line.allocated_gross_amount));const sales=(saleResult.data??[]).map(row=>({...row,allocatedGrossAmount:allocated.get(Number(row.id))??0,outstandingGrossAmount:Math.max(0,Number(row.amount)-(allocated.get(Number(row.id))??0))}));const clearing=accounts.find(a=>a.code==="card_clearing"),cardPendingBalance=(movementResult.data??[]).filter(m=>Number(m.fund_account_id)===Number(clearing?.id)).reduce((sum,m)=>sum+Number(m.amount),0);const completed=reconciliations.filter(r=>r.status==="matched"&&r.deposit_date>=start&&r.deposit_date<end),completedGross=completed.reduce((s,r)=>s+Number(r.matched_gross_amount),0),completedDeposit=completed.reduce((s,r)=>s+Number(r.deposit_amount),0),completedDifference=completed.reduce((s,r)=>s+Number(r.difference_amount),0);return ledgerJson({ok:true,month,accounts,reconciliations,sales,summary:{cardPendingBalance,unsettledCardGross:sales.reduce((s,r)=>s+r.outstandingGrossAmount,0),unmatchedDeposits:reconciliations.filter(r=>r.status!=="matched").reduce((s,r)=>s+Number(r.deposit_amount),0),completedGross,completedDeposit,completedDifference,actualDifferenceRate:completedGross>0?completedDifference/completedGross:null}})}catch(error){console.error("[LEDGER_CARD_SETTLEMENTS_GET_FAILED]",error);return ledgerJson({ok:false,code:"CARD_SETTLEMENTS_LOAD_FAILED"},500)}}

export async function POST(request:Request){const auth=await requireLedgerActor();if(auth.response||!auth.actor)return auth.response;const body=await request.json().catch(()=>null)as Record<string,unknown>|null,allowed=new Set(["depositAt","amount","destinationAccountId","reference","memo"]);if(!body||Object.keys(body).some(k=>!allowed.has(k))||!body.depositAt||!Number.isInteger(Number(body.destinationAccountId))||Number(body.amount)<=0)return ledgerJson({ok:false,code:"INVALID_BODY"},400);try{const{data,error}=await supabaseServer.rpc("ledger_create_card_deposit_v1",{p_deposit_at:body.depositAt,p_amount:body.amount,p_destination_account_id:body.destinationAccountId,p_reference:body.reference||null,p_memo:body.memo||null,p_actor_user_id:auth.actor.id});if(error)throw error;const result=data as{status?:string};if(result.status!=="created")return ledgerJson({ok:false,code:String(result.status??"CARD_DEPOSIT_FAILED").toUpperCase(),result},result.status==="forbidden"?403:400);return ledgerJson({ok:true,result},201)}catch(error){console.error("[LEDGER_CARD_DEPOSIT_FAILED]",error);return ledgerJson({ok:false,code:"CARD_DEPOSIT_FAILED"},500)}}
