"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import KeepingImageInput,{type KeepingImageFiles} from "@/components/bar/keeping/KeepingImageInput";import KeepingProductAutocomplete,{type KeepingProduct} from "@/components/bar/keeping/KeepingProductAutocomplete";import {BarField,BarSection,BarSegmentedControl,KeepingPercentSelector,KeepingZoneSelector,keepingInputStyle,primaryButtonStyle} from "@/components/bar/keeping/KeepingUi";import {handleBarApiUnauthorized} from "@/lib/bar/client-auth";import {vietnamToday} from "@/lib/bar/keeping";import type{BarZoneRecord}from"@/lib/bar/types";import{keepingText}from"@/lib/text/bar-keeping";import{keepingNewText}from"@/lib/text/bar-keeping-new";
type Source="inventory"|"external";
export default function KeepingForm({lang}:{lang:"ko"|"vi"}){const t=keepingText[lang],nt=keepingNewText[lang],router=useRouter();const[values,setValues]=useState({customerName:"",customerIdentifier:"",liquorName:"",remainingPercent:"100",zoneCode:"",storedAt:vietnamToday(),note:""});const[source,setSource]=useState<Source>("inventory"),[product,setProduct]=useState<KeepingProduct|null>(null),[image,setImage]=useState<KeepingImageFiles|null>(null),[imageBusy,setImageBusy]=useState(false),[zones,setZones]=useState<BarZoneRecord[]>([]),[saving,setSaving]=useState(false),[error,setError]=useState("");
useEffect(()=>{fetch("/api/bar/zones",{cache:"no-store"}).then(async r=>{if(await handleBarApiUnauthorized(r))return null;if(!r.ok)throw new Error();return r.json()}).then(result=>setZones(result?.zones??[])).catch(()=>setError(t.error))},[t.error]);const update=(key:keyof typeof values,value:string)=>setValues(current=>({...current,[key]:value}));const changeSource=(next:Source)=>{setSource(next);setProduct(null);update("liquorName","");setError("")};
async function submit(event:React.FormEvent){event.preventDefault();const percent=Number(values.remainingPercent);if(source==="inventory"&&!product){setError(nt.selectProduct);return}if(!image||!values.customerName.trim()||!values.liquorName.trim()||!values.zoneCode||!Number.isInteger(percent)||percent<0||percent>100){setError(!image?t.photoRequired:t.invalid);return}setSaving(true);setError("");try{const form=new FormData();Object.entries(values).forEach(([key,value])=>form.set(key,value));form.set("liquorSource",source);if(product)form.set("inventoryItemId",String(product.id));form.set("image",image.detail);form.set("thumbnail",image.thumbnail);const response=await fetch("/api/bar/keepings",{method:"POST",body:form});if(await handleBarApiUnauthorized(response))return;const result=await response.json();if(!response.ok)throw new Error(result.error||t.error);router.replace(`/bar/keeping/${result.id}`)}catch(caught){setError(caught instanceof Error?caught.message:t.error);setSaving(false)}}
return <form onSubmit={submit} style={{paddingBottom:"calc(76px + env(safe-area-inset-bottom))"}}><div style={{padding:"15px 15px 16px",border:"1px solid #dcdfe4",borderRadius:18,background:"#fff",boxShadow:"0 6px 20px rgba(0,0,0,.04)"}}><BarSection title={t.customerInfo} first><BarField label={t.customerName} required>{({id,describedBy})=><input id={id} aria-describedby={describedBy} disabled={saving} value={values.customerName} maxLength={120} placeholder={nt.customerNamePlaceholder} onChange={e=>update("customerName",e.target.value)} style={keepingInputStyle}/>}</BarField><BarField label={nt.customerFeature}>{({id,describedBy})=><input id={id} aria-describedby={describedBy} disabled={saving} value={values.customerIdentifier} maxLength={120} placeholder={nt.customerFeaturePlaceholder} onChange={e=>update("customerIdentifier",e.target.value)} style={keepingInputStyle}/>}</BarField></BarSection>
<BarSection title={t.liquorInfo}><BarSegmentedControl label={nt.liquorSource} value={source} disabled={saving} onChange={changeSource} options={[{value:"inventory",label:nt.soldProduct},{value:"external",label:nt.outsideBottle}]}/><BarField label={t.liquorName} required>{({id})=>source==="inventory"?<div id={id}><KeepingProductAutocomplete lang={lang} disabled={saving} onSelect={(item,name)=>{setProduct(item);update("liquorName",name)}}/></div>:<input id={id} disabled={saving} value={values.liquorName} maxLength={160} placeholder={nt.outsidePlaceholder} onChange={e=>update("liquorName",e.target.value)} style={keepingInputStyle}/>}</BarField><KeepingImageInput lang={lang} required disabled={saving} onBusyChange={setImageBusy} onChange={setImage}/><KeepingPercentSelector label={t.remaining} value={values.remainingPercent} onChange={value=>update("remainingPercent",value)} disabled={saving}/></BarSection>
<BarSection title={t.storageInfo}><KeepingZoneSelector label={t.zone} value={values.zoneCode} onChange={value=>update("zoneCode",value)} zones={zones} lang={lang} disabled={saving}/><BarField label={t.storedAt} required>{({id})=><input id={id} type="date" disabled={saving} value={values.storedAt} onChange={e=>update("storedAt",e.target.value)} style={keepingInputStyle}/>}</BarField><p style={{margin:0,color:"#6b7280",fontSize:11,lineHeight:1.45}}>{lang==="vi"?"Thời hạn lưu giữ là 3 tháng kể từ ngày bắt đầu.":"보관기간은 보관 시작일로부터 3개월입니다."}</p><BarField label={t.note}>{({id})=><textarea id={id} disabled={saving} value={values.note} maxLength={3000} onChange={e=>update("note",e.target.value)} style={{...keepingInputStyle,minHeight:76,padding:"10px 12px",resize:"vertical",fontFamily:"inherit"}}/>}</BarField></BarSection>
{error?<p role="alert" style={{margin:"0 0 10px",padding:"9px 10px",borderRadius:9,background:"#fef2f2",color:"#b91c1c",fontSize:12}}>{error}</p>:null}<button disabled={saving||imageBusy} style={{...primaryButtonStyle,width:"100%",opacity:saving||imageBusy?0.6:1}}>{saving?t.saving:t.register}</button></div></form>}

export const Percent=({value,set,label,disabled}:{value:string;set:(value:string)=>void;label:string;disabled?:boolean})=><KeepingPercentSelector label={label} value={value} onChange={set} disabled={disabled}/>;
