"use client";

import { useEffect, useId, useRef } from "react";

export const keepingInputStyle: React.CSSProperties = { width:"100%",minWidth:0,minHeight:44,boxSizing:"border-box",padding:"0 12px",border:"1px solid #d1d5db",borderRadius:10,background:"#fff",color:"#111827",fontSize:13,outline:"2px solid transparent",outlineOffset:1 };
export const primaryButtonStyle: React.CSSProperties = { minHeight:44,padding:"9px 13px",border:"1px solid #111827",borderRadius:10,background:"#111827",color:"#fff",fontSize:13,fontWeight:750,cursor:"pointer" };
export const secondaryButtonStyle: React.CSSProperties = { ...primaryButtonStyle,border:"1px solid #d1d5db",background:"#fff",color:"#374151" };
export const dangerButtonStyle: React.CSSProperties = { ...primaryButtonStyle,border:"1px solid #b91c1c",background:"#b91c1c" };

export function BarSection({title,icon,description,first=false,children}:{title:string;icon?:string;description?:string;first?:boolean;children:React.ReactNode}){
  return <section style={{padding:first?"0 0 16px":"16px 0",borderTop:first?0:"1px solid #e5e7eb",display:"grid",gap:11}}><div><h2 style={{margin:0,fontSize:15,lineHeight:1.35,display:"flex",alignItems:"center",gap:6}}>{icon?<span aria-hidden="true">{icon}</span>:null}<span>{title}</span></h2>{description?<p style={{margin:"3px 0 0",color:"#6b7280",fontSize:11,lineHeight:1.4}}>{description}</p>:null}</div>{children}</section>;
}
export function BarField({label,required,help,error,children}:{label:string;required?:boolean;help?:string;error?:string;children:(props:{id:string;describedBy?:string})=>React.ReactNode}){
  const id=useId(),messageId=`${id}-message`;return <div style={{minWidth:0,display:"grid",gap:5}}><label htmlFor={id} style={{color:"#4b5563",fontSize:12,fontWeight:700,lineHeight:1.35}}>{label}{required?" *":""}</label>{children({id,describedBy:help||error?messageId:undefined})}{help||error?<div id={messageId} role={error?"alert":undefined} style={{color:error?"#b91c1c":"#6b7280",fontSize:11,lineHeight:1.4}}>{error||help}</div>:null}</div>;
}
export function BarSegmentedControl<T extends string>({label,value,options,onChange,disabled}:{label:string;value:T;options:Array<{value:T;label:string}>;onChange:(value:T)=>void;disabled?:boolean}){
  return <div role="radiogroup" aria-label={label} style={{display:"grid",gridTemplateColumns:`repeat(${options.length},minmax(0,1fr))`,gap:3,padding:3,border:"1px solid #d1d5db",borderRadius:11,background:"#f3f4f6"}}>{options.map(option=><button key={option.value} type="button" role="radio" aria-checked={value===option.value} disabled={disabled} onClick={()=>onChange(option.value)} style={{minHeight:40,padding:"6px 9px",border:0,borderRadius:8,background:value===option.value?"#111827":"transparent",color:value===option.value?"#fff":"#4b5563",fontSize:12,fontWeight:800}}>{option.label}</button>)}</div>;
}

export function KeepingPercentSelector({label,value,onChange,disabled,error}:{label:string;value:string;onChange:(value:string)=>void;disabled?:boolean;error?:string}){
  return <BarField label={label} required error={error}>{({id,describedBy})=><div><div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(0,1fr))",gap:6}}>{[100,75,50,25,10].map(number=><button key={number} type="button" disabled={disabled} aria-pressed={value===String(number)} onClick={()=>onChange(String(number))} style={{minWidth:0,minHeight:43,padding:4,border:value===String(number)?"1px solid #111827":"1px solid #d1d5db",borderRadius:9,background:value===String(number)?"#111827":"#fff",color:value===String(number)?"#fff":"#4b5563",fontSize:12,fontWeight:800}}>{number}</button>)}</div><div style={{display:"flex",alignItems:"center",gap:7,marginTop:7}}><input id={id} aria-describedby={describedBy} type="number" inputMode="numeric" min={0} max={100} step={1} disabled={disabled} value={value} onChange={event=>onChange(event.target.value)} style={{...keepingInputStyle,width:112,textAlign:"right",paddingRight:28,fontWeight:700}}/><span style={{marginLeft:-31,color:"#6b7280",fontSize:12,pointerEvents:"none"}}>%</span></div></div>}</BarField>;
}

export function KeepingRegistrationPercentSelector({label,directInputLabel,value,onChange,disabled,error}:{label:string;directInputLabel:string;value:string;onChange:(value:string)=>void;disabled?:boolean;error?:string}){
  return <BarField label={label} required error={error}>{({id,describedBy})=><div><div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(0,1fr))",gap:6}}>{[100,75,50,25,10].map(number=><button key={number} type="button" disabled={disabled} aria-pressed={value===String(number)} onClick={()=>onChange(String(number))} style={{minWidth:0,minHeight:43,padding:4,border:value===String(number)?"1px solid #111827":"1px solid #d1d5db",borderRadius:9,background:value===String(number)?"#111827":"#fff",color:value===String(number)?"#fff":"#4b5563",fontSize:12,fontWeight:800,whiteSpace:"nowrap"}}>{number}%</button>)}</div><div style={{position:"relative",marginTop:7}}><input id={id} aria-describedby={describedBy} aria-label={directInputLabel} placeholder={directInputLabel} type="number" inputMode="numeric" min={0} max={100} step={1} disabled={disabled} value={value} onChange={event=>onChange(event.target.value)} style={{...keepingInputStyle,width:"100%",paddingRight:34,fontWeight:700}}/><span aria-hidden="true" style={{position:"absolute",right:12,top:"50%",transform:"translateY(-50%)",color:"#6b7280",fontSize:12,pointerEvents:"none"}}>%</span></div></div>}</BarField>;
}

type Zone={code:string;isActive:boolean;selectableForKeeping:boolean};
export function KeepingZoneSelector({label,value,onChange,zones,lang,disabled,currentZone,hideLabel=false}:{label:string;value:string;onChange:(value:string)=>void;zones:Zone[];lang:"ko"|"vi";disabled?:boolean;currentZone?:string;hideLabel?:boolean}){
  const groups=[{key:"A",label:lang==="vi"?"Trên":"상단"},{key:"B",label:lang==="vi"?"Giữa":"중단"},{key:"C",label:lang==="vi"?"Dưới":"하단"}];
  const available=zones.filter(zone=>zone.isActive&&zone.selectableForKeeping&&zone.code!=="A2");
return <div role="group" aria-label={label}>{hideLabel?null:<div style={{marginBottom:7,color:"#4b5563",fontSize:12,fontWeight:700}}>{label} *</div>}<div style={{display:"grid",gap:8}}>{groups.map(group=>{const items=available.filter(zone=>zone.code.startsWith(group.key));return <div key={group.key}><div style={{marginBottom:4,color:"#6b7280",fontSize:11,fontWeight:700,textAlign:"center"}}>{group.label}</div><div style={{display:"grid",gridTemplateColumns:group.key==="A"?"repeat(2,44px)":"repeat(8,minmax(0,1fr))",justifyContent:"center",gap:group.key==="A"?7:3}}>{items.map(zone=>{const unavailable=disabled||zone.code===currentZone;return <button key={zone.code} type="button" disabled={unavailable} aria-pressed={value===zone.code} onClick={()=>onChange(zone.code)} style={{minWidth:0,minHeight:43,padding:"5px 0",border:value===zone.code?"1px solid #111827":"1px solid #d1d5db",borderRadius:8,background:value===zone.code?"#111827":"#fff",color:value===zone.code?"#fff":"#374151",opacity:unavailable?0.45:1,fontSize:12,fontWeight:800}}>{zone.code}</button>})}</div></div>})}</div></div>;
}

export function BarSheet({kind,title,closeLabel,open=true,saving=false,compact=false,onClose,returnFocusRef,children,footer}:{kind:"bottom"|"full";title:string;closeLabel:string;open?:boolean;saving?:boolean;compact?:boolean;onClose:()=>void;returnFocusRef?:React.RefObject<HTMLElement|null>;children:React.ReactNode;footer:React.ReactNode}){
  const closeRef=useRef<HTMLButtonElement>(null);useEffect(()=>{if(!open)return;const old=document.body.style.overflow,focus=returnFocusRef?.current;document.body.style.overflow="hidden";closeRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!saving)onClose()};window.addEventListener("keydown",key);return()=>{document.body.style.overflow=old;window.removeEventListener("keydown",key);focus?.focus()}},[onClose,open,returnFocusRef,saving]);if(!open)return null;
  return <div role="dialog" aria-modal="true" aria-label={title} onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)onClose()}} style={{position:"fixed",inset:0,zIndex:1400,padding:kind==="bottom"?"12px 12px 0":"12px",background:"rgba(15,23,42,.68)",display:"flex",alignItems:kind==="bottom"?"flex-end":"center",justifyContent:"center"}}><div style={{width:"100%",maxWidth:540,height:kind==="full"&&!compact?"min(92dvh,820px)":"auto",maxHeight:kind==="bottom"?"86dvh":compact?"92dvh":undefined,overflow:"hidden",borderRadius:kind==="bottom"?"18px 18px 0 0":16,background:"#fff",boxShadow:"0 24px 70px rgba(15,23,42,.3)",display:"flex",flexDirection:"column"}}><header style={{flexShrink:0,minHeight:54,padding:"8px 14px 8px 16px",borderBottom:"1px solid #e5e7eb",display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><strong style={{fontSize:15}}>{title}</strong><button ref={closeRef} type="button" disabled={saving} onClick={onClose} aria-label={closeLabel} style={{width:42,height:42,border:"1px solid #e5e7eb",borderRadius:10,background:"#fff",fontSize:20}}>×</button></header><div style={{minHeight:0,overflowY:"auto",padding:16,display:"grid",gap:13,WebkitOverflowScrolling:"touch"}}>{children}</div><footer style={{flexShrink:0,padding:"11px 16px calc(11px + env(safe-area-inset-bottom))",borderTop:"1px solid #e5e7eb",background:"#fff"}}>{footer}</footer></div></div>;
}
