"use client";
import { useEffect, useRef, useState } from "react";
import KeepingImageInput, { type KeepingImageFiles } from "@/components/bar/keeping/KeepingImageInput";
import KeepingZonePicker from "@/components/bar/keeping/KeepingZonePicker";
import { Percent } from "@/components/bar/keeping/KeepingForm";
import type { BarKeeping } from "@/lib/bar/keeping-types";
import { keepingText } from "@/lib/text/bar-keeping";
import { ui } from "@/lib/styles/ui";
import { handleBarApiUnauthorized } from "@/lib/bar/client-auth";
export type KeepingAction = "update" | "use" | "correct_remaining" | "move" | "replace_photo" | "close" | "reactivate";

export default function KeepingActionModal({ item, action, lang, onClose, onSaved }: { item: BarKeeping; action: KeepingAction; lang: "ko" | "vi"; onClose: () => void; onSaved: () => Promise<void> }) {
  const t = keepingText[lang]; const closeRef = useRef<HTMLButtonElement>(null); const [image, setImage] = useState<KeepingImageFiles | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const [values, setValues] = useState<Record<string, string | boolean>>({ customerName: item.customerName, customerIdentifier: item.customerIdentifier ?? "", liquorName: item.liquorName, note: item.note ?? "", storedAt: item.storedAt, expiresAt: item.expiresAt ?? "", remainingPercent: String(item.remainingPercent), usedAt: localDateTime(new Date()), zoneCode: "", reason: "", finish: item.remainingPercent === 0, closeReason: "finished", closedAt: localDateTime(new Date()), closeNote: "" });
  useEffect(() => { const old = document.body.style.overflow; document.body.style.overflow = "hidden"; closeRef.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !saving) onClose(); }; window.addEventListener("keydown", key); return () => { document.body.style.overflow = old; window.removeEventListener("keydown", key); }; }, [onClose, saving]);
  const set = (key: string, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }));
  async function save(event: React.FormEvent) {
    event.preventDefault(); if (action === "replace_photo" && !image) { setError(t.photoRequired); return; } setSaving(true); setError("");
    try { const form = new FormData(); form.set("action", action); form.set("version", String(item.version)); form.set("payload", JSON.stringify(values)); if (image) { form.set("image", image.detail); form.set("thumbnail", image.thumbnail); }
      const response = await fetch(`/api/bar/keepings/${item.id}/actions`, { method: "POST", body: form }); if (await handleBarApiUnauthorized(response)) return; const result = await response.json();
      if (response.status === 409 && result.code === "VERSION_CONFLICT") { setError(t.conflict); setSaving(false); return; } if (!response.ok) throw new Error(result.error || t.error); await onSaved(); onClose();
    } catch (caught) { setError(caught instanceof Error ? caught.message : t.error); setSaving(false); }
  }
  const title = action === "update" ? t.edit : action === "use" ? t.use : action === "correct_remaining" ? t.correct : action === "move" ? t.move : action === "replace_photo" ? t.photo : action === "close" ? t.close : t.reactivate;
  return <div role="dialog" aria-modal="true" aria-label={title} onClick={() => !saving && onClose()} style={overlay}><form onSubmit={save} onClick={(event) => event.stopPropagation()} style={modal}><header style={header}><strong>{title}</strong><button ref={closeRef} type="button" disabled={saving} onClick={onClose} aria-label={t.cancel} style={icon}>×</button></header><div style={content}>
    {action === "update" ? <><Input label={t.customerName} value={String(values.customerName)} set={(v) => set("customerName", v)} /><Input label={t.identifier} value={String(values.customerIdentifier)} set={(v) => set("customerIdentifier", v)} /><Input label={t.liquorName} value={String(values.liquorName)} set={(v) => set("liquorName", v)} /><Input type="date" label={t.storedAt} value={String(values.storedAt)} set={(v) => set("storedAt", v)} /><Input type="date" label={t.expiresAt} value={String(values.expiresAt)} set={(v) => set("expiresAt", v)} /><Input area label={t.note} value={String(values.note)} set={(v) => set("note", v)} /></> : null}
    {action === "use" ? <><Percent value={String(values.remainingPercent)} set={(v) => { set("remainingPercent", v); if (Number(v) === 0) set("finish", true); }} label={t.remaining} disabled={saving} /><Input type="datetime-local" label={t.usedAt} value={String(values.usedAt)} set={(v) => set("usedAt", v)} /><Input area label={t.note} value={String(values.note)} set={(v) => set("note", v)} /><KeepingImageInput lang={lang} disabled={saving} onChange={setImage} />{Number(values.remainingPercent) === 0 ? <label style={field}><span><input type="checkbox" checked={Boolean(values.finish)} onChange={(event) => set("finish", event.target.checked)} /> {t.finishTogether}</span></label> : null}</> : null}
    {action === "correct_remaining" ? <><Percent value={String(values.remainingPercent)} set={(v) => set("remainingPercent", v)} label={t.remaining} disabled={saving} /><Input area required label={t.correctionReason} value={String(values.reason)} set={(v) => set("reason", v)} /></> : null}
    {action === "move" ? <><div style={{ fontSize: 13 }}>{t.zone}: <strong>{item.zoneCode}</strong></div><KeepingZonePicker value={String(values.zoneCode)} onChange={(v) => set("zoneCode", v)} lang={lang} excludeCode={item.zoneCode} disabled={saving} /><Input area required label={t.moveReason} value={String(values.reason)} set={(v) => set("reason", v)} /></> : null}
    {action === "replace_photo" ? <KeepingImageInput lang={lang} required disabled={saving} onChange={setImage} /> : null}
    {action === "close" ? <><label style={field}>{t.closeReason}<select value={String(values.closeReason)} onChange={(event) => set("closeReason", event.target.value)} style={ui.input}><option value="finished">{t.finished}</option><option value="returned">{t.returned}</option><option value="discarded">{t.discarded}</option><option value="expired">{t.expiredReason}</option><option value="other">{t.other}</option></select></label><Input type="datetime-local" label={t.closedAt} value={String(values.closedAt)} set={(v) => set("closedAt", v)} /><Input area label={t.closeNote} value={String(values.closeNote)} set={(v) => set("closeNote", v)} /><KeepingImageInput lang={lang} disabled={saving} onChange={setImage} /></> : null}
    {action === "reactivate" ? <><KeepingZonePicker value={String(values.zoneCode)} onChange={(v) => set("zoneCode", v)} lang={lang} disabled={saving} /><Percent value={String(values.remainingPercent)} set={(v) => set("remainingPercent", v)} label={t.remaining} disabled={saving} /><Input type="date" label={t.expiresAt} value={String(values.expiresAt)} set={(v) => set("expiresAt", v)} /><KeepingImageInput lang={lang} disabled={saving} onChange={setImage} /><Input area required label={t.reactivateReason} value={String(values.reason)} set={(v) => set("reason", v)} /></> : null}
    {error ? <p role="alert" style={{ margin: 0, color: "#b91c1c", fontSize: 12 }}>{error}</p> : null}</div><footer style={footer}><button type="button" disabled={saving} onClick={onClose} style={ui.subButton}>{t.cancel}</button><button disabled={saving} style={ui.button}>{saving ? t.saving : t.save}</button></footer></form></div>;
}
function Input({ label, value, set, type = "text", area = false, required = false }: { label: string; value: string; set: (value: string) => void; type?: string; area?: boolean; required?: boolean }) { return <label style={field}>{label}{area ? <textarea value={value} required={required} onChange={(event) => set(event.target.value)} style={{ ...ui.input, minHeight: 84 }} /> : <input type={type} value={value} required={required} onChange={(event) => set(event.target.value)} style={ui.input} />}</label>; }
function localDateTime(date: Date) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(date); const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value ?? ""; return `${get("year")}-${get("month")}-${get("day")}T${get("hour")}:${get("minute")}`; }
const field: React.CSSProperties = { display: "grid", gap: 6, fontSize: 12, fontWeight: 700 }; const overlay: React.CSSProperties = { position: "fixed", inset: 0, zIndex: 1400, padding: 12, background: "rgba(15,23,42,.68)", display: "flex", alignItems: "center", justifyContent: "center" }; const modal: React.CSSProperties = { width: "100%", maxWidth: 540, maxHeight: "92vh", overflow: "hidden", borderRadius: 15, background: "#fff", display: "flex", flexDirection: "column" }; const header: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 16px", borderBottom: "1px solid #e5e7eb" }; const content: React.CSSProperties = { padding: 16, overflowY: "auto", display: "grid", gap: 12 }; const footer: React.CSSProperties = { padding: "12px 16px calc(12px + env(safe-area-inset-bottom))", borderTop: "1px solid #e5e7eb", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }; const icon: React.CSSProperties = { width: 40, height: 40, border: "1px solid #d1d5db", borderRadius: 10, background: "#fff", fontSize: 20 };
