import "server-only";

import { supabaseServer } from "@/lib/supabase/server";
import { normalizeAttendanceDayFacts } from "./attendance-facts";
import { mapContract, mapSchedule } from "./db-mappers";
import { roundMinutes } from "./projection";
import { getEmployeeLevelInfo } from "@/lib/employee-level/server";
import { calculateCombinedSalary } from "./compensation";
import { applyPayrollWorkPolicy, calculatePayrollRates } from "./work-policy";
import { isPayrollUserCandidate } from "./eligibility";
import type { PayrollContract, WorkScheduleVersion } from "./types";
import { buildEmployeeInsuranceSnapshot, calculateDirectorInsurance, selectInsuranceSetting, type PayrollInsuranceGlobalSettings, type PayrollInsuranceSettingVersion } from "./insurance";
import { calculateLatePenalty, type PayrollPenaltySettings } from "./penalties";
import { getLastCompletedBusinessDate, getPayrollOverviewPeriod } from "./overview-period";
import { addStoreDays } from "@/lib/store-settings/business-time-core";
import { isMissingAttendanceCandidateDate } from "./missing-attendance";

export const PAYROLL_RUN_ENGINE_VERSION = "monthly-payroll-v6";
export const PAYROLL_RUN_START_MONTH = "2026-07";

export const CRITICAL_WARNING_CODES = [
  "NO_PAYROLL_CONTRACT", "MISSING_CHECK_IN", "MISSING_CHECK_OUT", "INVALID_TIME_RANGE",
  "SCHEDULE_HISTORY_UNAVAILABLE", "PENDING_LEAVE_APPROVAL", "LEAVE_PAYROLL_TREATMENT_UNSPECIFIED",
  "OVERTIME_APPROVAL_UNAVAILABLE", "CONTRACT_OVERLAP", "CALCULATION_FAILED",
  "STORED_STATUS_POLICY_MISMATCH", "STORED_LATE_MINUTES_MISMATCH",
  "STORED_EARLY_LEAVE_MINUTES_MISMATCH", "STORED_WORK_MINUTES_MISMATCH",
  "LATE_POLICY_REVIEW", "EARLY_LEAVE_POLICY_REVIEW",
  "EMPLOYEE_LEVEL_BASE_DATE_REQUIRED",
] as const;
const BLOCKING_WARNING_CODES=new Set<string>(["NO_PAYROLL_CONTRACT","MISSING_CHECK_IN","MISSING_CHECK_OUT","INVALID_TIME_RANGE","SCHEDULE_HISTORY_UNAVAILABLE","CONTRACT_OVERLAP","CALCULATION_FAILED","EMPLOYEE_LEVEL_BASE_DATE_REQUIRED"]);
const ACTIONABLE_WARNING_CODES=new Set<string>(["PENDING_LEAVE_APPROVAL","LEAVE_PAYROLL_TREATMENT_UNSPECIFIED","OVERTIME_APPROVAL_UNAVAILABLE"]);

type CriticalWarning = typeof CRITICAL_WARNING_CODES[number];
export type PayrollSnapshotUserRow={id:number;name:string|null;full_name:string|null;username:string;is_active:boolean;role:string;part:string|null;position:string|null;birth_date:string|null;hire_date:string|null;termination_date:string|null;is_system_account:boolean;payroll_eligible_override:boolean|null;level_program_enabled:boolean|null;level_base_date_override:string|null};
type AttendanceRow={id:number;user_id:number;status:string;work_date:string;check_in_at:string|null;check_out_at:string|null;late_minutes:number|null;early_leave_minutes:number|null;work_minutes:number|null;approval_status:string|null;updated_at:string|null};
type AutoCategory="base_work"|"paid_leave"|"overtime"|"late_deduction"|"early_leave_deduction"|"unauthorized_absence_deduction"|"insurance_employee_deduction";
export type PayrollRunItemInput={itemType:"automatic"|"manual"|"review_adjustment";category:AutoCategory|string;direction:"addition"|"deduction";amount:number;originalAmount:number|null;businessDate:string|null;description:string;sourceSnapshot:Record<string,unknown>};
export type PayrollRunReviewInput={warningCode:CriticalWarning;reviewLevel:"blocking"|"actionable"|"advisory";businessDate:string|null;sourceSnapshot:Record<string,unknown>};
export type PayrollRunEmployeeInput={userId:number;employeeName:string;contractSnapshot:PayrollContract[];attendanceSnapshot:Record<string,unknown>;insuranceSnapshot:ReturnType<typeof buildEmployeeInsuranceSnapshot>;recognizedWorkdays:number;recognizedMinutes:number;lateMinutes:number;earlyLeaveMinutes:number;overtimeCandidateMinutes:number;items:PayrollRunItemInput[];reviews:PayrollRunReviewInput[]};
type BatchInput={month:string;dates:string[];users:PayrollSnapshotUserRow[];attendance:AttendanceRow[];lateNormalizedRecordIds:Set<number>;contracts:PayrollContract[];schedules:WorkScheduleVersion[];settingsByDate:Map<string,{revision:number|null;lateGraceMinutes:number;earlyLeaveGraceMinutes:number}>;insuranceVersionsByUser:Map<number,PayrollInsuranceSettingVersion[]>;insuranceGlobal:PayrollInsuranceGlobalSettings;penaltySettings:PayrollPenaltySettings};

export function validPayrollMonth(value:string|null){return value&&/^\d{4}-(0[1-9]|1[0-2])$/.test(value)?value:null;}
export function isOfficialPayrollMonth(month:string){return month>=PAYROLL_RUN_START_MONTH;}
export function payrollMonthDates(month:string){const[y,m]=month.split("-").map(Number);const count=new Date(Date.UTC(y,m,0)).getUTCDate();return Array.from({length:count},(_,index)=>`${month}-${String(index+1).padStart(2,"0")}`);}
export async function resolvePayrollOverviewPeriod(month:string){const{data,error}=await supabaseServer.rpc("store_business_date_for_timestamp_v1",{p_timestamp:new Date().toISOString()});const completed=!error&&typeof data==="string"?addStoreDays(data,-1):getLastCompletedBusinessDate();return getPayrollOverviewPeriod(month,completed);}
function activeOn<T extends{effectiveFrom:string;effectiveTo:string|null}>(rows:T[],date:string){return rows.filter(row=>row.effectiveFrom<=date&&(!row.effectiveTo||row.effectiveTo>date));}
function intersectsMonth(row:{effectiveFrom:string;effectiveTo:string|null},start:string,endExclusive:string){return row.effectiveFrom<endExclusive&&(!row.effectiveTo||row.effectiveTo>start);}
function employeeName(user:PayrollSnapshotUserRow){return user.name||user.full_name||user.username;}
function vnd(value:number){return Math.round(value);}
function item(category:AutoCategory,direction:"addition"|"deduction",amount:number,date:string|null,description:string,sourceSnapshot:Record<string,unknown>):PayrollRunItemInput{return{itemType:"automatic",category,direction,amount:vnd(Math.max(0,amount)),originalAmount:vnd(Math.max(0,amount)),businessDate:date,description,sourceSnapshot};}
function review(warningCode:CriticalWarning,businessDate:string|null,sourceSnapshot:Record<string,unknown>,reviewLevel?:PayrollRunReviewInput["reviewLevel"]):PayrollRunReviewInput{return{warningCode,reviewLevel:reviewLevel??(BLOCKING_WARNING_CODES.has(warningCode)?"blocking":ACTIONABLE_WARNING_CODES.has(warningCode)?"actionable":"advisory"),businessDate,sourceSnapshot};}
function isCritical(code:string):code is CriticalWarning{return(CRITICAL_WARNING_CODES as readonly string[]).includes(code);}

export function selectPayrollUsers(input:{users:PayrollSnapshotUserRow[];attendance:AttendanceRow[];contracts:PayrollContract[];month:string}){
  const start=`${input.month}-01`;const next=new Date(`${start}T00:00:00Z`);next.setUTCMonth(next.getUTCMonth()+1);const endExclusive=next.toISOString().slice(0,10);
  const attendanceIds=new Set(input.attendance.map(row=>Number(row.user_id)));const contractIds=new Set(input.contracts.filter(row=>intersectsMonth(row,start,endExclusive)).map(row=>row.userId));
  const monthEnd=new Date(`${endExclusive}T00:00:00Z`);monthEnd.setUTCDate(monthEnd.getUTCDate()-1);const monthEndDate=monthEnd.toISOString().slice(0,10);
  return input.users.filter(user=>{
    const intersects=Boolean(user.hire_date)&&user.hire_date!<=monthEndDate&&(!user.termination_date||user.termination_date>=start);
    return isPayrollUserCandidate({
      user,
      employmentIntersects:intersects,
      hasAttendance:attendanceIds.has(user.id),
      hasContract:contractIds.has(user.id),
    });
  });
}

export function calculatePayrollBatch(input:BatchInput):PayrollRunEmployeeInput[]{
  const users=selectPayrollUsers(input);const attendanceByUser=new Map<number,AttendanceRow[]>();for(const row of input.attendance){const list=attendanceByUser.get(Number(row.user_id))??[];list.push(row);attendanceByUser.set(Number(row.user_id),list);}
  return users.map(user=>{try{return calculateEmployee(user,attendanceByUser.get(user.id)??[],input);}catch(error){const insuranceSnapshot=buildEmployeeInsuranceSnapshot(selectInsuranceSetting(input.insuranceVersionsByUser.get(user.id)??[],input.month),input.insuranceGlobal);const insuranceItems=insuranceSnapshot.isEnrolled?[item("insurance_employee_deduction","deduction",insuranceSnapshot.employeeDeductionAmount,null,"직원 보험 공제",{insuranceSettingVersionId:insuranceSnapshot.settingVersionId,insuranceSettingRevision:insuranceSnapshot.revision,effectiveMonth:insuranceSnapshot.effectiveMonth,insuranceBaseAmount:insuranceSnapshot.insuranceBaseAmount,employeeRateBp:insuranceSnapshot.employeeRateBp,employerRateBp:insuranceSnapshot.employerRateBp,employeeDeductionAmount:insuranceSnapshot.employeeDeductionAmount,employerContributionAmount:insuranceSnapshot.employerAmount})]:[];return{userId:user.id,employeeName:employeeName(user),contractSnapshot:[],attendanceSnapshot:{month:input.month,engineVersion:PAYROLL_RUN_ENGINE_VERSION,error:error instanceof Error?error.message:"CALCULATION_FAILED"},insuranceSnapshot,recognizedWorkdays:0,recognizedMinutes:0,lateMinutes:0,earlyLeaveMinutes:0,overtimeCandidateMinutes:0,items:insuranceItems,reviews:[review("CALCULATION_FAILED",null,{message:error instanceof Error?error.message:"CALCULATION_FAILED"})]};}});
}

function calculateEmployee(user:PayrollSnapshotUserRow,records:AttendanceRow[],input:BatchInput):PayrollRunEmployeeInput{
  const contracts=input.contracts.filter(row=>row.userId===user.id);const schedules=input.schedules.filter(row=>row.userId===user.id);const items:PayrollRunItemInput[]=[];const reviews:PayrollRunReviewInput[]=[];const days:Record<string,unknown>[]=[];let recognizedMinutes=0,recognizedWorkdays=0,lateMinutes=0,earlyLeaveMinutes=0,overtimeCandidateMinutes=0;
  const recordsByDate=new Map(records.map(row=>[row.work_date,row]));
  const eligibleDates=input.dates.filter(date=>(!user.hire_date||date>=user.hire_date)&&(!user.termination_date||date<=user.termination_date));
  if(contracts.length===0)reviews.push(review("NO_PAYROLL_CONTRACT",null,{userId:user.id,month:input.month}));
  for(const date of eligibleDates){const record=recordsByDate.get(date)??null;const contractMatches=activeOn(contracts,date);const scheduleMatches=activeOn(schedules,date);const contract=contractMatches.length===1?contractMatches[0]:null;const schedule=scheduleMatches.length===1?scheduleMatches[0]:null;if(!record&&!schedule)continue;const settings=input.settingsByDate.get(date)??{revision:null,lateGraceMinutes:0,earlyLeaveGraceMinutes:0};
    const facts=normalizeAttendanceDayFacts({userId:user.id,businessDate:date,attendanceRecord:record?{id:Number(record.id),status:record.status,checkInAt:record.check_in_at,checkOutAt:record.check_out_at,approvalStatus:record.approval_status,storedLateMinutes:record.late_minutes,storedEarlyLeaveMinutes:record.early_leave_minutes,storedWorkMinutes:record.work_minutes}:null,schedule,hireDate:user.hire_date,storeSettingsRevision:settings.revision,lateGraceMinutes:settings.lateGraceMinutes,earlyLeaveGraceMinutes:settings.earlyLeaveGraceMinutes,manualLateNormalized:record?input.lateNormalizedRecordIds.has(Number(record.id)):false});
    if(contractMatches.length>1&&!facts.warningCodes.includes("CONTRACT_OVERLAP"))facts.warningCodes.push("CONTRACT_OVERLAP");
    if(!contract&&!facts.warningCodes.includes("NO_PAYROLL_CONTRACT"))facts.warningCodes.push("NO_PAYROLL_CONTRACT");
    for(const code of facts.warningCodes){if(code==="OVERTIME_APPROVAL_UNAVAILABLE")continue;if(isCritical(code)&&!(code==="LEAVE_PAYROLL_TREATMENT_UNSPECIFIED"&&contract?.paidLeaveMode!=="manual_review")){const missingCandidate=code==="MISSING_CHECK_IN"&&isMissingAttendanceCandidateDate({date,hireDate:user.hire_date,terminationDate:user.termination_date,calculationEndDate:input.dates.at(-1)??null,hasActiveSchedule:Boolean(schedule),hasAttendanceRecord:Boolean(record)});reviews.push(review(code,date,{attendanceRecordId:record?.id??null,stored:facts.stored,recalculated:{status:facts.attendanceStatus,lateMinutes:facts.lateMinutes,earlyLeaveMinutes:facts.earlyLeaveMinutes,workMinutes:facts.actualMinutes},candidateMinutes:facts.overtimeCandidateMinutes,approvedLeave:record?.status==="leave"&&record.approval_status==="approved",missingAttendanceCandidate:missingCandidate,requiresDayOffOrMissingEntryConfirmation:missingCandidate},missingCandidate?"actionable":undefined));}}
    if(!contract||!schedule||contractMatches.length!==1||scheduleMatches.length!==1){days.push({date,facts,contractRevision:contract?.revision??null,scheduleRevision:schedule?.revision??null});continue;}
    const levelInfo=getEmployeeLevelInfo(user,date);const compensation=calculateCombinedSalary(contract,levelInfo);if(compensation.combinedSalary===null){reviews.push(review("EMPLOYEE_LEVEL_BASE_DATE_REQUIRED",date,{contractRevision:contract.revision}));continue;}const rate=calculatePayrollRates(contract,compensation.combinedSalary);
    for(const entry of reviews){if(entry.businessDate===date&&entry.warningCode==="MISSING_CHECK_IN")entry.sourceSnapshot={...entry.sourceSnapshot,dayRate:rate.dayRate,minuteRate:rate.minuteRate,penaltyDays:input.penaltySettings.unauthorizedAbsencePenaltyDays,engineVersion:PAYROLL_RUN_ENGINE_VERSION};}
    const storedWorkMinutes=Number(facts.stored.workMinutes??0);const recalculatedWorkMinutes=Number(facts.actualMinutes??0);
    if(facts.warningCodes.includes("STORED_WORK_MINUTES_MISMATCH"))reviews.push(review("STORED_WORK_MINUTES_MISMATCH",date,{attendanceRecordId:record?.id??null,stored:facts.stored,recalculated:{workMinutes:recalculatedWorkMinutes},amountDelta:vnd(rate.minuteRate*(storedWorkMinutes-recalculatedWorkMinutes))}));
    if(facts.warningCodes.includes("STORED_LATE_MINUTES_MISMATCH"))reviews.push(review("STORED_LATE_MINUTES_MISMATCH",date,{attendanceRecordId:record?.id??null,stored:facts.stored,recalculated:{lateMinutes:facts.lateMinutes},amountDelta:0}));
    if(facts.warningCodes.includes("STORED_EARLY_LEAVE_MINUTES_MISMATCH"))reviews.push(review("STORED_EARLY_LEAVE_MINUTES_MISMATCH",date,{attendanceRecordId:record?.id??null,stored:facts.stored,recalculated:{earlyLeaveMinutes:facts.earlyLeaveMinutes},amountDelta:0}));
    const blocking=facts.warningCodes.some(code=>["MISSING_CHECK_IN","MISSING_CHECK_OUT","INVALID_TIME_RANGE","PENDING_LEAVE_APPROVAL"].includes(code));
    if(record?.status==="leave"){
      if(record.approval_status!=="approved"){days.push({date,facts,contractRevision:contract.revision,scheduleRevision:schedule.revision});continue;}
      // No per-record paid-leave marker exists yet, so approved leave remains unpaid by default.
      days.push({date,facts,contractRevision:contract.revision,scheduleRevision:schedule.revision});continue;
    }
    if(blocking||facts.actualMinutes===null){days.push({date,facts,contractRevision:contract.revision,scheduleRevision:schedule.revision});continue;}
    let actualRecognizedMinutes=contract.calculationBasis==="minute"?facts.actualMinutes:facts.scheduledOverlapMinutes??facts.actualMinutes;if(contract.calculationBasis==="hour")actualRecognizedMinutes=roundMinutes(actualRecognizedMinutes,contract.timeBlockMinutes,contract.roundingMode);
    const workPolicy=applyPayrollWorkPolicy({contract,actualRecognizedMinutes,dayRate:rate.dayRate,minuteRate:rate.minuteRate,lateMinutes:facts.lateMinutes,earlyLeaveMinutes:facts.earlyLeaveMinutes});const minutes=workPolicy.recognizedMinutes;const daysRecognized=workPolicy.recognizedWorkdays;items.push(item("base_work","addition",workPolicy.workAmount,date,"기본 근무",{recognizedMinutes:minutes,recognizedDays:daysRecognized,lateMinutes:facts.lateMinutes,earlyLeaveMinutes:facts.earlyLeaveMinutes,overtimeCandidateMinutes:facts.overtimeCandidateMinutes,minuteRate:rate.minuteRate,dayRate:rate.dayRate,contractRevision:contract.revision}));recognizedMinutes+=minutes;recognizedWorkdays+=daysRecognized;lateMinutes+=facts.lateMinutes;earlyLeaveMinutes+=facts.earlyLeaveMinutes;overtimeCandidateMinutes+=facts.overtimeCandidateMinutes;
    const latePenalty=calculateLatePenalty({lateMinutes:facts.lateMinutes,minuteRate:rate.minuteRate,dayRate:rate.dayRate,thresholdMinutes:input.penaltySettings.lateMajorThresholdMinutes,minorPenaltyMinutes:input.penaltySettings.lateMinorPenaltyMinutes,majorPenaltyRateBp:input.penaltySettings.lateMajorPenaltyRateBp});
    if(latePenalty.amount>0)items.push(item("late_deduction","deduction",latePenalty.amount,date,"지각 패널티",{attendanceRecordId:record?.id??null,lateMinutes:facts.lateMinutes,penaltyTier:latePenalty.tier,thresholdMinutes:input.penaltySettings.lateMajorThresholdMinutes,minorPenaltyMinutes:input.penaltySettings.lateMinorPenaltyMinutes,majorPenaltyRateBp:input.penaltySettings.lateMajorPenaltyRateBp,minuteRate:rate.minuteRate,dayRate:rate.dayRate,calculatedAmount:latePenalty.amount,engineVersion:PAYROLL_RUN_ENGINE_VERSION}));
    const earlyLeaveSource={rawEarlyLeaveMinutes:facts.rawEarlyLeaveMinutes,earlyLeaveThresholdMinutes:facts.earlyLeaveThresholdMinutes,isEarlyLeave:facts.isEarlyLeave,deductionEarlyLeaveMinutes:workPolicy.deductionEarlyLeaveMinutes,calculationBasis:contract.calculationBasis,minuteRate:rate.minuteRate,calculatedAmount:vnd(workPolicy.automaticEarlyLeavePenalty),attendanceRecordId:record?.id??null,scheduleRevision:schedule.revision,storeSettingsRevision:settings.revision,engineVersion:PAYROLL_RUN_ENGINE_VERSION};
    for(const entry of reviews){if(entry.businessDate===date&&entry.warningCode==="STORED_EARLY_LEAVE_MINUTES_MISMATCH")entry.sourceSnapshot={...entry.sourceSnapshot,...earlyLeaveSource};}
    if(workPolicy.automaticEarlyLeavePenalty>0&&!facts.warningCodes.includes("STORED_EARLY_LEAVE_MINUTES_MISMATCH"))items.push(item("early_leave_deduction","deduction",workPolicy.automaticEarlyLeavePenalty,date,"조퇴 공제",earlyLeaveSource));else if(workPolicy.earlyLeaveRequiresReview)reviews.push(review("EARLY_LEAVE_POLICY_REVIEW",date,{...earlyLeaveSource,suggestedDeduction:vnd(rate.minuteRate*facts.earlyLeaveMinutes)}));
    if(facts.overtimeCandidateMinutes>0&&contract.calculationBasis==="hour"&&contract.overtimeMode==="requires_approval")reviews.push(review("OVERTIME_APPROVAL_UNAVAILABLE",date,{candidateMinutes:facts.overtimeCandidateMinutes,minuteRate:rate.minuteRate,suggestedAmount:vnd(rate.minuteRate*facts.overtimeCandidateMinutes)}));
    const recalculatedAutomaticItems=items.filter(entry=>entry.itemType==="automatic"&&entry.businessDate===date);
    const storedRaw=Math.max(0,Number(facts.stored.workMinutes??0));const storedRecognizedMinutes=contract.payType==="monthly"?contract.standardMinutesPerDay:contract.calculationBasis==="hour"?roundMinutes(storedRaw,contract.timeBlockMinutes,contract.roundingMode):contract.calculationBasis==="day"?contract.standardMinutesPerDay:storedRaw;const storedDays=contract.payType==="monthly"||contract.calculationBasis==="day"?1:storedRecognizedMinutes/contract.standardMinutesPerDay;
    const storedAutomaticItems=recalculatedAutomaticItems.filter(entry=>!["base_work","late_deduction","early_leave_deduction"].includes(entry.category));
    if(record?.status!=="leave"&&storedRaw>0){const storedPolicy=applyPayrollWorkPolicy({contract,actualRecognizedMinutes:storedRecognizedMinutes,dayRate:rate.dayRate,minuteRate:rate.minuteRate,lateMinutes:Number(facts.stored.lateMinutes??0),earlyLeaveMinutes:Number(facts.stored.earlyLeaveMinutes??0)});storedAutomaticItems.push(item("base_work","addition",storedPolicy.workAmount,date,"기본 근무",{recognizedMinutes:storedPolicy.recognizedMinutes,recognizedDays:storedPolicy.recognizedWorkdays,lateMinutes:Number(facts.stored.lateMinutes??0),earlyLeaveMinutes:Number(facts.stored.earlyLeaveMinutes??0),overtimeCandidateMinutes:facts.overtimeCandidateMinutes,minuteRate:rate.minuteRate,dayRate:rate.dayRate,contractRevision:contract.revision,attendanceSource:"stored"}));const storedLate=calculateLatePenalty({lateMinutes:Number(facts.stored.lateMinutes??0),minuteRate:rate.minuteRate,dayRate:rate.dayRate,thresholdMinutes:input.penaltySettings.lateMajorThresholdMinutes,minorPenaltyMinutes:input.penaltySettings.lateMinorPenaltyMinutes,majorPenaltyRateBp:input.penaltySettings.lateMajorPenaltyRateBp});if(storedLate.amount>0)storedAutomaticItems.push(item("late_deduction","deduction",storedLate.amount,date,"지각 패널티",{lateMinutes:Number(facts.stored.lateMinutes??0),penaltyTier:storedLate.tier,minuteRate:rate.minuteRate,dayRate:rate.dayRate,attendanceSource:"stored",engineVersion:PAYROLL_RUN_ENGINE_VERSION}));if(storedPolicy.automaticEarlyLeavePenalty>0)storedAutomaticItems.push(item("early_leave_deduction","deduction",storedPolicy.automaticEarlyLeavePenalty,date,"조퇴 공제",{minutes:Number(facts.stored.earlyLeaveMinutes),minuteRate:rate.minuteRate,attendanceSource:"stored"}));}
    const recalculatedNet=recalculatedAutomaticItems.reduce((sum,entry)=>sum+(entry.direction==="addition"?entry.amount:-entry.amount),0);const storedNet=storedAutomaticItems.reduce((sum,entry)=>sum+(entry.direction==="addition"?entry.amount:-entry.amount),0);
    for(const entry of reviews){if(entry.businessDate===date&&entry.warningCode.startsWith("STORED_")){entry.sourceSnapshot={...entry.sourceSnapshot,recalculatedAutomaticItems,storedAutomaticItems,recalculatedSummary:{recognizedMinutes:minutes,recognizedDays:daysRecognized,lateMinutes:facts.lateMinutes,earlyLeaveMinutes:facts.earlyLeaveMinutes,overtimeCandidateMinutes:facts.overtimeCandidateMinutes},storedSummary:{recognizedMinutes:storedRecognizedMinutes,recognizedDays:storedDays,lateMinutes:Number(facts.stored.lateMinutes??0),earlyLeaveMinutes:Number(facts.stored.earlyLeaveMinutes??0),overtimeCandidateMinutes:facts.overtimeCandidateMinutes},amountDelta:storedNet-recalculatedNet};}}
    days.push({date,facts,contractRevision:contract.revision,scheduleRevision:schedule.revision,recognizedMinutes:minutes});
  }
  const deduped=[...new Map(reviews.map(entry=>[`${entry.businessDate??"none"}:${entry.warningCode}`,entry])).values()];
  const insuranceSetting=selectInsuranceSetting(input.insuranceVersionsByUser.get(user.id)??[],input.month);const insuranceSnapshot=buildEmployeeInsuranceSnapshot(insuranceSetting,input.insuranceGlobal);
  if(insuranceSnapshot.isEnrolled)items.push(item("insurance_employee_deduction","deduction",insuranceSnapshot.employeeDeductionAmount,null,"직원 보험 공제",{insuranceSettingVersionId:insuranceSnapshot.settingVersionId,insuranceSettingRevision:insuranceSnapshot.revision,effectiveMonth:insuranceSnapshot.effectiveMonth,insuranceBaseAmount:insuranceSnapshot.insuranceBaseAmount,employeeRateBp:insuranceSnapshot.employeeRateBp,employerRateBp:insuranceSnapshot.employerRateBp,employeeDeductionAmount:insuranceSnapshot.employeeDeductionAmount,employerContributionAmount:insuranceSnapshot.employerAmount}));
  return{userId:user.id,employeeName:employeeName(user),contractSnapshot:contracts,attendanceSnapshot:{month:input.month,engineVersion:PAYROLL_RUN_ENGINE_VERSION,days},insuranceSnapshot,recognizedWorkdays,recognizedMinutes,lateMinutes,earlyLeaveMinutes,overtimeCandidateMinutes,items,reviews:deduped};
}

export async function loadPayrollMonthSnapshot(month:string,options?:{calculationEndDate?:string|null}){
  const monthDates=payrollMonthDates(month);const start=monthDates[0];const calculationEndDate=options&&"calculationEndDate" in options?options.calculationEndDate:(await resolvePayrollOverviewPeriod(month)).calculationEndDate;const dates=calculationEndDate?monthDates.filter(date=>date<=calculationEndDate):[];const dayBeforeMonth=new Date(`${start}T00:00:00Z`);dayBeforeMonth.setUTCDate(dayBeforeMonth.getUTCDate()-1);const attendanceEnd=dates.at(-1)??dayBeforeMonth.toISOString().slice(0,10);const nextMonth=new Date(`${start}T00:00:00Z`);nextMonth.setUTCMonth(nextMonth.getUTCMonth()+1);const endExclusive=nextMonth.toISOString().slice(0,10);
  const[userResult,attendanceResult,overrideResult,contractResult,scheduleResult,settingsResults,insuranceResult,payrollSettingsResult]=await Promise.all([
    supabaseServer.from("users").select("id,name,full_name,username,is_active,role,part,position,birth_date,hire_date,termination_date,is_system_account,payroll_eligible_override,level_program_enabled,level_base_date_override").order("id"),
    supabaseServer.from("attendance_records").select("id,user_id,status,work_date,check_in_at,check_out_at,late_minutes,early_leave_minutes,work_minutes,approval_status,updated_at").gte("work_date",start).lte("work_date",attendanceEnd),
    supabaseServer.from("attendance_record_manual_overrides").select("attendance_record_id").eq("override_metric","late").eq("override_action","normalize").is("revoked_at",null),
    supabaseServer.from("payroll_contract_versions").select("id,user_id,pay_type,calculation_basis,base_salary,fixed_raise_amount,standard_workdays,standard_minutes_per_day,time_block_minutes,rounding_mode,late_adjustment_mode,early_leave_adjustment_mode,overtime_mode,paid_leave_mode,effective_from,effective_to,revision").lt("effective_from",endExclusive).or(`effective_to.is.null,effective_to.gt.${start}`),
    supabaseServer.from("employee_work_schedule_versions").select("id,user_id,start_time,end_time,unpaid_break_minutes,effective_from,effective_to,revision,change_reason").lt("effective_from",endExclusive).or(`effective_to.is.null,effective_to.gt.${start}`),
    Promise.all(dates.map(date=>supabaseServer.rpc("store_get_settings_overview_v1",{p_business_date:date}))),
    supabaseServer.from("payroll_insurance_setting_versions").select("id,user_id,is_enrolled,insurance_base_amount,effective_month,revision,created_by,created_at,note").lte("effective_month",start).order("effective_month",{ascending:false}).order("revision",{ascending:false}),
    supabaseServer.from("payroll_settings").select("employee_insurance_rate_bp,employer_insurance_rate_bp,director_insurance_enabled,director_insurance_base_amount,director_insurance_rate_bp,late_major_threshold_minutes,late_minor_penalty_minutes,late_major_penalty_rate_bp,unauthorized_absence_penalty_days,updated_at").eq("id",1).single(),
  ]);
  if(userResult.error||attendanceResult.error||overrideResult.error||contractResult.error||scheduleResult.error||settingsResults.some(result=>result.error)||insuranceResult.error||payrollSettingsResult.error)throw new Error("PAYROLL_MONTH_SNAPSHOT_READ_FAILED");
  const settingsByDate=new Map(dates.map((date,index)=>{const overview=settingsResults[index].data as{current?:{revision?:number;attendancePolicy?:{lateGraceMinutes?:number;earlyLeaveGraceMinutes?:number}}|null}|null;return[date,{revision:overview?.current?.revision??null,lateGraceMinutes:overview?.current?.attendancePolicy?.lateGraceMinutes??0,earlyLeaveGraceMinutes:overview?.current?.attendancePolicy?.earlyLeaveGraceMinutes??0}];}));
  const insuranceGlobal:PayrollInsuranceGlobalSettings={employeeRateBp:Number(payrollSettingsResult.data.employee_insurance_rate_bp),employerRateBp:Number(payrollSettingsResult.data.employer_insurance_rate_bp),directorEnabled:Boolean(payrollSettingsResult.data.director_insurance_enabled),directorBaseAmount:Number(payrollSettingsResult.data.director_insurance_base_amount),directorRateBp:Number(payrollSettingsResult.data.director_insurance_rate_bp),settingsUpdatedAt:String(payrollSettingsResult.data.updated_at??"")||null};
  const penaltySettings:PayrollPenaltySettings={lateMajorThresholdMinutes:Number(payrollSettingsResult.data.late_major_threshold_minutes),lateMinorPenaltyMinutes:Number(payrollSettingsResult.data.late_minor_penalty_minutes),lateMajorPenaltyRateBp:Number(payrollSettingsResult.data.late_major_penalty_rate_bp),unauthorizedAbsencePenaltyDays:Number(payrollSettingsResult.data.unauthorized_absence_penalty_days)};
  const insuranceVersionsByUser=new Map<number,PayrollInsuranceSettingVersion[]>();for(const row of insuranceResult.data??[]){const version:PayrollInsuranceSettingVersion={id:Number(row.id),userId:Number(row.user_id),isEnrolled:Boolean(row.is_enrolled),insuranceBaseAmount:Number(row.insurance_base_amount),effectiveMonth:String(row.effective_month),revision:Number(row.revision),createdBy:Number(row.created_by),createdAt:String(row.created_at),note:row.note?String(row.note):null};const list=insuranceVersionsByUser.get(version.userId)??[];list.push(version);insuranceVersionsByUser.set(version.userId,list);}
  const input:BatchInput={month,dates,users:(userResult.data??[]) as PayrollSnapshotUserRow[],attendance:(attendanceResult.data??[]) as AttendanceRow[],lateNormalizedRecordIds:new Set((overrideResult.data??[]).map(row=>Number(row.attendance_record_id))),contracts:(contractResult.data??[]).map(row=>mapContract(row as Record<string,unknown>)),schedules:(scheduleResult.data??[]).map(row=>mapSchedule(row as Record<string,unknown>)),settingsByDate,insuranceVersionsByUser,insuranceGlobal,penaltySettings};
  const directorInsuranceAmount=calculateDirectorInsurance(insuranceGlobal);const insuranceSettingsSnapshot={employeeRateBp:insuranceGlobal.employeeRateBp,employerRateBp:insuranceGlobal.employerRateBp,director:{enabled:insuranceGlobal.directorEnabled,baseAmount:insuranceGlobal.directorBaseAmount,rateBp:insuranceGlobal.directorRateBp,calculatedAmount:directorInsuranceAmount,settingsUpdatedAt:insuranceGlobal.settingsUpdatedAt}};
  return{employees:calculatePayrollBatch(input),context:{users:input.users,contracts:input.contracts},sourceSnapshot:{engineVersion:PAYROLL_RUN_ENGINE_VERSION,calculatedAt:new Date().toISOString(),calculationEndDate,attendanceRecordIds:input.attendance.map(row=>row.id),contractRevisions:[...new Set(input.contracts.map(row=>row.revision))],scheduleRevisions:[...new Set(input.schedules.map(row=>row.revision))],storeSettingRevisions:[...new Set([...settingsByDate.values()].map(value=>value.revision).filter(value=>value!==null))],insuranceSettings:insuranceSettingsSnapshot,penaltySettings:{...penaltySettings,capturedAt:new Date().toISOString()}}};
}
