export type PayrollUiLang="ko"|"vi";

const labels={
 ko:{monthly:"월급",daily:"일급",hourly:"시간급",minute:"분 단위",hour:"시간 단위",day:"일 단위",none:"반올림 안 함",floor:"내림",ceil:"올림",nearest:"가까운 단위",ignore:"반영하지 않음",deduct_minutes:"분 단위 공제",separate:"별도 확인",requires_approval:"승인 후 반영",manual_review:"직접 확인",paid:"유급",unpaid:"무급",draft:"작성 중",finalized:"확정",paid_status:"지급 완료",cancelled:"취소",calculated:"계산 완료",requires_review:"확인 필요"},
 vi:{monthly:"Lương tháng",daily:"Lương ngày",hourly:"Lương giờ",minute:"Theo phút",hour:"Theo giờ",day:"Theo ngày",none:"Không làm tròn",floor:"Làm tròn xuống",ceil:"Làm tròn lên",nearest:"Làm tròn gần nhất",ignore:"Không điều chỉnh",deduct_minutes:"Khấu trừ theo phút",separate:"Kiểm tra riêng",requires_approval:"Chỉ tính sau khi duyệt",manual_review:"Kiểm tra thủ công",paid:"Có lương",unpaid:"Không lương",draft:"Đang soạn",finalized:"Đã chốt",paid_status:"Đã thanh toán",cancelled:"Đã hủy",calculated:"Đã tính",requires_review:"Cần kiểm tra"}
} as const;
export function payrollLabel(lang:PayrollUiLang,value:string){if(value==="fixed_monthly")return lang==="vi"?"Trả cố định hàng tháng":"매월 고정 지급";if(value==="minute")return lang==="vi"?"Theo giờ thực tế":"실근무 정산";if(value==="day")return lang==="vi"?"Theo ngày công":"근무일 정산";if(value==="hour")return lang==="vi"?"Cách tính theo khối giờ cũ":"기존 시간 블록 정산";const key=value==="paid"?"paid_status":value;return(labels[lang] as Record<string,string>)[key]??value;}
export function money(value:number|null|undefined){return `${Number(value??0).toLocaleString("en-US")} VND`;}
export function minutesLabel(lang:PayrollUiLang,value:number){return value>0?`${value.toLocaleString()}${lang==="vi"?" phút":"분"}`:lang==="vi"?"Không có":"없음";}
export function monthLabel(lang:PayrollUiLang,value:string){const[y,m]=value.slice(0,7).split("-");return lang==="vi"?`Phần công tháng ${Number(m)}/${y}`:`${y}년 ${Number(m)}월 근무분`;}
export function dateLabel(lang:PayrollUiLang,value:string){const[y,m,d]=value.slice(0,10).split("-");return lang==="vi"?`${Number(d)}/${Number(m)}/${y}`:`${y}년 ${Number(m)}월 ${Number(d)}일`;}
export const categoryLabels={ko:{base_work:"기본 근무",paid_leave:"유급휴무",overtime:"추가근무",late_deduction:"지각 공제",early_leave_deduction:"조퇴 공제",incentive:"인센티브",meal:"식대",transport:"교통비",housing:"주거수당",insurance_tax:"수동 보험·세금 공제",insurance_employee_deduction:"자동 직원 보험 공제",advance:"가불",penalty:"벌금",other_addition:"기타 추가",other_deduction:"기타 공제"},vi:{base_work:"Lương cơ bản",paid_leave:"Nghỉ có lương",overtime:"Làm thêm giờ",late_deduction:"Trừ đi muộn",early_leave_deduction:"Trừ về sớm",incentive:"Thưởng",meal:"Tiền ăn",transport:"Đi lại",housing:"Nhà ở",insurance_tax:"Khấu trừ bảo hiểm·thuế thủ công",insurance_employee_deduction:"Khấu trừ bảo hiểm nhân viên tự động",advance:"Tạm ứng",penalty:"Phạt",other_addition:"Cộng khác",other_deduction:"Trừ khác"}} as const;
export function categoryLabel(lang:PayrollUiLang,value:string){if(value==="late_deduction")return lang==="vi"?"Phạt đi muộn":"지각 패널티";if(value==="unauthorized_absence_deduction")return lang==="vi"?"Phạt nghỉ không phép":"무단결근 패널티";return(categoryLabels[lang] as Record<string,string>)[value]??value;}
export function roleLabel(lang:PayrollUiLang,value:string|null|undefined){const map=lang==="vi"?{staff:"Nhân viên",leader:"Tổ trưởng",manager:"Quản lý",owner:"Chủ quán",master:"Quản trị viên"}:{staff:"직원",leader:"리더",manager:"매니저",owner:"사장",master:"마스터"};return(map as Record<string,string>)[String(value??"").toLowerCase()]??(value||"-");}
export function partLabel(lang:PayrollUiLang,value:string|null|undefined){const map=lang==="vi"?{owner:"Chủ quán",hall:"Sảnh",bar:"Quầy bar",kitchen:"Bếp",etc:"Khác"}:{owner:"사장",hall:"홀",bar:"바",kitchen:"주방",etc:"기타"};return(map as Record<string,string>)[String(value??"").toLowerCase()]??(value||"-");}
export function reviewLabel(lang:PayrollUiLang,code:string){const ko:Record<string,string>={NO_PAYROLL_CONTRACT:"적용 가능한 급여계약이 없습니다.",MISSING_CHECK_IN:"출근 기록이 없습니다.",MISSING_CHECK_OUT:"퇴근 기록이 없습니다.",INVALID_TIME_RANGE:"출퇴근 시간이 올바르지 않습니다.",SCHEDULE_HISTORY_UNAVAILABLE:"해당 날짜의 근무시간 이력이 없습니다.",CONTRACT_OVERLAP:"급여계약 적용기간이 겹칩니다.",CALCULATION_FAILED:"급여 계산 중 오류가 발생했습니다.",PENDING_LEAVE_APPROVAL:"아직 승인되지 않은 휴무입니다.",LEAVE_PAYROLL_TREATMENT_UNSPECIFIED:"승인 휴무의 급여 처리 방식이 정해지지 않았습니다.",OVERTIME_APPROVAL_UNAVAILABLE:"추가근무 반영 여부를 확인해야 합니다.",LATE_POLICY_REVIEW:"일 단위 급여의 지각 처리를 확인해야 합니다.",EARLY_LEAVE_POLICY_REVIEW:"일 단위 급여의 조퇴 처리를 확인해야 합니다.",STORED_STATUS_POLICY_MISMATCH:"저장된 근태 상태와 재계산 결과가 다릅니다.",STORED_LATE_MINUTES_MISMATCH:"저장된 지각시간과 재계산 결과가 다릅니다.",STORED_EARLY_LEAVE_MINUTES_MISMATCH:"저장된 조퇴시간과 재계산 결과가 다릅니다.",STORED_WORK_MINUTES_MISMATCH:"저장된 근무시간과 재계산 결과가 다릅니다."};const vi:Record<string,string>={NO_PAYROLL_CONTRACT:"Không có hợp đồng lương phù hợp.",MISSING_CHECK_IN:"Thiếu giờ vào ca.",MISSING_CHECK_OUT:"Thiếu giờ ra ca.",INVALID_TIME_RANGE:"Khoảng thời gian chấm công không hợp lệ.",SCHEDULE_HISTORY_UNAVAILABLE:"Không có lịch làm việc cho ngày này.",CONTRACT_OVERLAP:"Thời gian áp dụng hợp đồng bị trùng.",CALCULATION_FAILED:"Có lỗi khi tính lương.",PENDING_LEAVE_APPROVAL:"Ngày nghỉ chưa được duyệt.",LEAVE_PAYROLL_TREATMENT_UNSPECIFIED:"Chưa xác định cách tính lương cho ngày nghỉ.",OVERTIME_APPROVAL_UNAVAILABLE:"Cần xác nhận thời gian làm thêm.",LATE_POLICY_REVIEW:"Cần xác nhận cách xử lý đi muộn theo ngày.",EARLY_LEAVE_POLICY_REVIEW:"Cần xác nhận cách xử lý về sớm theo ngày.",STORED_STATUS_POLICY_MISMATCH:"Trạng thái đã lưu khác kết quả tính lại.",STORED_LATE_MINUTES_MISMATCH:"Số phút đi muộn đã lưu khác kết quả tính lại.",STORED_EARLY_LEAVE_MINUTES_MISMATCH:"Số phút về sớm đã lưu khác kết quả tính lại.",STORED_WORK_MINUTES_MISMATCH:"Số phút làm việc đã lưu khác kết quả tính lại."};return(lang==="vi"?vi:ko)[code]??(lang==="vi"?"Cần kiểm tra dữ liệu lương.":"급여 데이터를 확인해야 합니다.");}
