import { supabaseServer } from "@/lib/supabase/server";
import { payrollJson, requirePayrollActor } from "@/lib/payroll/server";
import { selectInsuranceSetting, type PayrollInsuranceSettingVersion } from "@/lib/payroll/insurance";

export const dynamic = "force-dynamic";
const FIELDS="id,user_id,is_enrolled,insurance_base_amount,effective_month,revision,created_by,created_at,note";
function validId(value:unknown){const id=Number(value);return Number.isSafeInteger(id)&&id>0?id:null;}
function map(row:Record<string,unknown>):PayrollInsuranceSettingVersion{return{id:Number(row.id),userId:Number(row.user_id),isEnrolled:Boolean(row.is_enrolled),insuranceBaseAmount:Number(row.insurance_base_amount),effectiveMonth:String(row.effective_month),revision:Number(row.revision),createdBy:Number(row.created_by),createdAt:String(row.created_at),note:row.note?String(row.note):null};}

export async function GET(request:Request){const auth=await requirePayrollActor();if(auth.response)return auth.response;const userId=validId(new URL(request.url).searchParams.get("userId"));if(!userId)return payrollJson({ok:false,code:"INVALID_USER_ID"},400);const month=new URL(request.url).searchParams.get("month")??new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit"}).format(new Date()).slice(0,7);const[{data:user,error:userError},{data,error}]=await Promise.all([supabaseServer.from("users").select("id,username").eq("id",userId).eq("is_system_account",false).maybeSingle(),supabaseServer.from("payroll_insurance_setting_versions").select(FIELDS).eq("user_id",userId).order("effective_month",{ascending:false}).order("revision",{ascending:false})]);if(userError||error)return payrollJson({ok:false,code:"PAYROLL_INSURANCE_READ_FAILED"},500);if(!user)return payrollJson({ok:false,code:"USER_NOT_FOUND"},404);const history=(data??[]).map(row=>map(row as Record<string,unknown>));return payrollJson({ok:true,current:selectInsuranceSetting(history,month),history,directorAccount:user.username==="mjk"});}

export async function POST(request:Request){const auth=await requirePayrollActor();if(auth.response||!auth.actor)return auth.response;const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const userId=validId(body?.userId),enrolled=body?.isEnrolled,base=Number(body?.insuranceBaseAmount),month=String(body?.effectiveMonth??"");if(!userId||typeof enrolled!=="boolean"||!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)||!Number.isSafeInteger(base)||(enrolled?base<1:base!==0))return payrollJson({ok:false,code:"INVALID_INSURANCE_SETTING"},400);const{data,error}=await supabaseServer.rpc("payroll_create_insurance_setting_version_v1",{p_user_id:userId,p_is_enrolled:enrolled,p_insurance_base_amount:base,p_effective_month:`${month}-01`,p_actor_user_id:auth.actor.id,p_note:body?.note??null});if(error){const status=error.message.includes("FORBIDDEN")?403:error.message.includes("NOT_FOUND")?404:400;return payrollJson({ok:false,code:status===403?"FORBIDDEN":status===404?"USER_NOT_FOUND":"INVALID_INSURANCE_SETTING"},status)}return payrollJson({ok:true,setting:map(data as Record<string,unknown>)},201);}
