"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, type CSSProperties } from "react";
import Container from "@/components/Container";
import { CompensationCard, CombinedPartTotal } from "@/components/payroll/CompensationCard";
import { EmployeeLevelDisabledBadgeScope } from "@/components/employee/EmployeeNameWithLevel";
import { useLanguage } from "@/lib/language-context";
import { getPartKey, getPartMeta } from "@/lib/common/parts";
import { comparePayrollEmployees } from "@/lib/payroll/employee-sort";
import { monthLabel, partLabel, type PayrollUiLang } from "@/lib/payroll/ui-labels";
import { formatVnd } from "@/lib/payroll/payroll-page-money";
import { sortPayrollEmployeesByHeaderAmount } from "@/lib/payroll/payroll-page-display";
import type { PayrollOverviewEmployee } from "@/lib/payroll/overview";
import type { PayrollOverviewProjectedSummary } from "@/lib/payroll/overview-projection";
import { payrollCostTableText, payrollOverviewText } from "@/lib/text/payroll-overview";
import { attendanceText } from "@/lib/text";

type InsuranceSummary = { totalPreInsurancePayoutAmount:number; totalEmployeeInsuranceDeductionAmount:number; totalNetAmount:number; totalEmployerInsuranceAmount:number; directorInsuranceAmount:number; totalInsuranceRemittanceAmount:number; totalCompanyCostAmount:number; mealAllowanceAmount:number };
type ProjectedSummaryWithMeal = PayrollOverviewProjectedSummary & { mealAllowanceAmount:number };
type Run = { id:number; payroll_month:string; status:"paying"|"completed"; target_employee_count:number; paid_employee_count:number; calculated_net_total:number; actual_paid_total:number; difference_total:number; employee_insurance_total:number; employer_insurance_total:number; director_insurance_amount:number; insurance_remittance_total:number; actual_company_cost_total:number; started_at:string; completed_at:string|null };
type OverviewResponse = { ok:true; month:string; asOfDate:string; future:boolean; monthClosed:boolean; employees:PayrollOverviewEmployee[]; summary:InsuranceSummary; projectedSummary:ProjectedSummaryWithMeal|null; mealAllowancePolicyMissing:boolean; mealAllowanceEligibleUserIds:number[]; paymentBatch:Run|null };

function currentMonth() { return new Intl.DateTimeFormat("en-CA", { timeZone:"Asia/Ho_Chi_Minh", year:"numeric", month:"2-digit" }).format(new Date()).slice(0, 7); }
function monthText(month:string, format:string) { return format.replace("{year}",month.slice(2,4)).replace("{month}",String(Number(month.slice(5)))); }

export default function AdminPayrollPage() {
  const { lang }=useLanguage(); const l=lang as PayrollUiLang; const vi=l==="vi";
  const attendance=attendanceText[lang]; const overviewText=payrollOverviewText[lang];
  const [month,setMonth]=useState(currentMonth); const [overview,setOverview]=useState<OverviewResponse|null>(null);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [expandedUserId,setExpandedUserId]=useState<number|null>(null);
  const refresh=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");try{const response=await fetch(`/api/admin/payroll/overview?month=${month}`,{cache:"no-store",signal});const data=await response.json();if(!response.ok)throw new Error(data.code);setOverview(data);return true}catch(cause){if((cause as Error).name!=="AbortError")setError(overviewText.loadError);return false}finally{if(!signal?.aborted)setLoading(false)}},[month,overviewText.loadError]);
  useEffect(()=>{const controller=new AbortController();setOverview(null);setExpandedUserId(null);void refresh(controller.signal);return()=>controller.abort()},[refresh]);
  const groups=useMemo(()=>{const map=new Map<string,PayrollOverviewEmployee[]>();for(const employee of overview?.employees??[]){const key=getPartKey(employee.part);map.set(key,[...(map.get(key)??[]),employee])}return [...map.entries()].map(([part,employees])=>({part,meta:getPartMeta(part),employees:sortPayrollEmployeesByHeaderAmount(employees.sort(comparePayrollEmployees),overview?.future===true)})).sort((a,b)=>a.meta.rank-b.meta.rank||a.part.localeCompare(b.part))},[overview]);
  const mealAllowanceEligibleUserIds=useMemo(()=>new Set(overview?.mealAllowanceEligibleUserIds??[]),[overview]);
  function moveMonth(amount:number){const[y,m]=month.split("-").map(Number);const next=new Date(Date.UTC(y,m-1+amount,1));setMonth(`${next.getUTCFullYear()}-${String(next.getUTCMonth()+1).padStart(2,"0")}`)}

  return <Container noPaddingTop><section style={styles.page}>
    <div style={styles.monthHeader}><button type="button" style={styles.monthButton} onClick={()=>moveMonth(-1)} aria-label={vi?"Tháng trước":"이전 달"}>‹</button><div style={styles.monthTitle}>{monthText(month,attendance.monthFormat)}</div><button type="button" style={styles.monthButton} onClick={()=>moveMonth(1)} aria-label={vi?"Tháng sau":"다음 달"}>›</button></div>
    <section style={styles.overviewSection} aria-busy={loading}>
      {loading?<div style={styles.state}>{overviewText.loading}</div>:error?<div role="alert" style={styles.error}>{error}</div>:groups.length===0?<div style={styles.state}>{overviewText.empty}</div>:groups.map(group=><section key={group.part} style={styles.partGroup}>
        <div style={{...styles.partTitle,color:group.meta.color,background:group.meta.bg,borderLeft:`4px solid ${group.meta.border}`}}><span>{group.meta.emoji}</span><span>{partLabel(l,group.part)}</span><span style={styles.partCount}>{group.employees.length}</span></div>
        <EmployeeLevelDisabledBadgeScope><div style={styles.staffList}>{group.employees.map(employee=><CompensationCard key={employee.userId} employee={employee} expanded={expandedUserId===employee.userId} toggle={()=>setExpandedUserId(expandedUserId===employee.userId?null:employee.userId)} lang={lang} month={month} future={overview?.future===true} monthClosed={overview?.monthClosed===true} refresh={()=>refresh()} mealAllowanceEligible={mealAllowanceEligibleUserIds.has(employee.userId)}/>)}</div></EmployeeLevelDisabledBadgeScope>
        {group.part!=="owner"&&<CombinedPartTotal employees={group.employees} lang={lang} partName={partLabel(l,group.part)} future={overview?.future===true}/>}
      </section>)}
    </section>
    {overview&&<InsuranceSummaryCard current={overview.future?null:overview.summary} projected={overview.projectedSummary} mealAllowancePolicyMissing={overview.mealAllowancePolicyMissing} lang={lang}/>}
    <PaymentBatchCard run={overview?.paymentBatch??null} month={month} lang={lang}/>
  </section></Container>;
}

function PaymentBatchCard({run,month,lang}:{run:Run|null;month:string;lang:"ko"|"vi"}){
  const vi=lang==="vi"; const label=monthLabel(lang as PayrollUiLang,month);
  if(!run)return <section style={styles.ledgerSection}><h2 style={styles.ledgerTitle}>{vi?"Sổ lương tháng":"월 급여장부"}</h2><div style={styles.selected}><b>{vi?`${label} chưa có lịch sử chi trả lương.`:`${label} 급여 지급 내역이 없습니다.`}</b><small style={styles.help}>{vi?"Lần chi trả đầu tiên sẽ cố định danh sách nhân viên của tháng này.":"첫 직원 지급 시 해당 월의 급여 대상자가 고정됩니다."}</small></div></section>;
  return <section style={styles.ledgerSection}><h2 style={styles.ledgerTitle}>{run.status==="completed"?(vi?`${label} sổ lương`:`${label} 급여장부`):(vi?`${label} đang chi trả lương`:`${label} 급여 지급 중`)}</h2><div style={styles.selected}>
    <b>{run.paid_employee_count} / {run.target_employee_count}{vi?" người đã trả":"명 지급완료"}</b>
    {run.status==="completed"&&run.completed_at?<small>{vi?"Hoàn tất":"완료일"} {new Date(run.completed_at).toLocaleDateString(vi?"vi-VN":"ko-KR")}</small>:null}
    <div style={styles.amounts}><Metric label={vi?"Tổng lương tính":"계산 실수령 합계"} value={formatVnd(run.calculated_net_total)}/><Metric label={vi?"Tổng thực trả":"실제 지급 합계"} value={formatVnd(run.actual_paid_total)}/><Metric label={vi?"Tổng chênh lệch":"차액 합계"} value={formatVnd(run.difference_total)}/>{run.status==="completed"&&<><Metric label={vi?"Bảo hiểm công ty":"회사 보험부담"} value={formatVnd(run.employer_insurance_total)}/><Metric label={vi?"Bảo hiểm giám đốc":"법인장 보험비"} value={formatVnd(run.director_insurance_amount)}/><Metric label={vi?"Nộp cơ quan bảo hiểm":"보험기관 납부액"} value={formatVnd(run.insurance_remittance_total)}/><Metric label={vi?"Tổng chi phí nhân công":"실제 총인건비"} value={formatVnd(run.actual_company_cost_total)} strong/></>}</div>
    <Link style={styles.primaryLink} href={`/admin/payroll/${run.id}`}>{vi?"Xem chi tiết":"상세 보기"}</Link>
  </div></section>;
}

function InsuranceSummaryCard({current,projected,mealAllowancePolicyMissing,lang}:{current:InsuranceSummary|null;projected:ProjectedSummaryWithMeal|null;mealAllowancePolicyMissing:boolean;lang:"ko"|"vi"}){const t=payrollOverviewText[lang];const table=payrollCostTableText[lang];const amount=(summary:InsuranceSummary|null,key:keyof InsuranceSummary)=>summary?formatVnd(summary[key]):"—";return <section style={styles.summaryCard}><div style={costStyles.grid} role="table" aria-label={t.companyCost}><div style={{...costStyles.cell,...costStyles.header,...costStyles.descriptionHeader}} role="columnheader">{table.description}</div><div style={{...costStyles.cell,...costStyles.header}} role="columnheader">{table.current}</div><div style={{...costStyles.cell,...costStyles.header}} role="columnheader">{table.projected}</div><CostGroup title={table.payrollGroup}/><CostRow label={table.preInsurancePayout} fullLabel={t.preInsurancePayout} current={amount(current,"totalPreInsurancePayoutAmount")} projected={amount(projected,"totalPreInsurancePayoutAmount")}/><CostRow label={table.employeeInsuranceDeduction} fullLabel={t.employeeInsuranceDeduction} current={amount(current,"totalEmployeeInsuranceDeductionAmount")} projected={amount(projected,"totalEmployeeInsuranceDeductionAmount")}/><CostRow label={table.netPayout} fullLabel={t.netPayout} current={amount(current,"totalNetAmount")} projected={amount(projected,"totalNetAmount")} emphasis="net"/><CostGroup title={table.companyGroup}/><CostRow label={table.mealAllowance} fullLabel={t.mealAllowance} current={amount(current,"mealAllowanceAmount")} projected={amount(projected,"mealAllowanceAmount")}/><CostRow label={table.employerInsurance} fullLabel={t.employerInsurance} current={amount(current,"totalEmployerInsuranceAmount")} projected={amount(projected,"totalEmployerInsuranceAmount")}/><CostRow label={table.directorInsurance} fullLabel={t.directorInsurance} current={amount(current,"directorInsuranceAmount")} projected={amount(projected,"directorInsuranceAmount")}/><CostRow label={table.insuranceRemittance} fullLabel={t.insuranceRemittance} current={amount(current,"totalInsuranceRemittanceAmount")} projected={amount(projected,"totalInsuranceRemittanceAmount")}/><CostRow label={table.companyCost} fullLabel={t.companyCost} current={amount(current,"totalCompanyCostAmount")} projected={amount(projected,"totalCompanyCostAmount")} emphasis="total"/></div><small style={costStyles.help}>{table.projectionHelp}{projected?.partial?` ${table.partialProjection} (${projected.includedEmployeeCount}/${projected.includedEmployeeCount+projected.unavailableEmployeeCount})`:projected?"":` ${table.unavailableProjection}`}</small><small style={costStyles.help}>{table.mealAllowanceProjectionHelp}</small>{mealAllowancePolicyMissing?<small role="alert" style={costStyles.mealAllowanceWarning}>{table.mealAllowancePolicyMissing}</small>:null}</section>}
function CostGroup({title}:{title:string}){return <div role="rowheader" style={costStyles.group}>{title}</div>}
function CostRow({label,fullLabel,current,projected,emphasis}:{label:string;fullLabel:string;current:string;projected:string;emphasis?:"net"|"total"}){return <><div style={{...costStyles.cell,...costStyles.label,...(emphasis?costStyles.emphasisLabel:{})}} role="cell" title={fullLabel} aria-label={fullLabel}>{label}</div><div style={{...costStyles.cell,...costStyles.number,...(emphasis==="net"?costStyles.net:{}),...(emphasis==="total"?costStyles.total:{})}} role="cell">{current}</div><div style={{...costStyles.cell,...costStyles.number,...(emphasis==="net"?costStyles.net:{}),...(emphasis==="total"?costStyles.total:{})}} role="cell">{projected}</div></>}
function Metric({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div style={styles.detailRow}><span>{label}</span><b style={strong?styles.net:undefined}>{value}</b></div>}

const costStyles={grid:{display:"grid",gridTemplateColumns:"minmax(0,32%) minmax(0,34%) minmax(0,34%)",minWidth:0,borderRadius:9,overflow:"hidden",border:"1px solid #dbeafe",background:"#fff"},cell:{minWidth:0,padding:"7px 5px",borderBottom:"1px solid #e5e7eb",fontSize:10.5,lineHeight:1.25},header:{background:"#f8fafc",fontWeight:900,textAlign:"center",color:"#475569"},descriptionHeader:{textAlign:"left"},number:{textAlign:"right",whiteSpace:"nowrap",fontVariantNumeric:"tabular-nums",fontSize:10.5},group:{gridColumn:"1 / -1",padding:"7px 5px",background:"#eff6ff",borderBottom:"1px solid #bfdbfe",fontSize:10.5,fontWeight:900,color:"#334155"},label:{color:"#475569",overflowWrap:"anywhere"},emphasisLabel:{fontWeight:900,color:"#1e3a8a"},net:{fontWeight:900,color:"#1d4ed8",background:"#f8fbff"},total:{fontWeight:950,color:"#0f172a",background:"#dbeafe"},help:{color:"#64748b",fontSize:10,lineHeight:1.4},mealAllowanceWarning:{display:"block",marginTop:2,padding:"6px 7px",borderRadius:8,background:"#fffbeb",color:"#92400e",fontSize:10.5,lineHeight:1.4}} satisfies Record<string,CSSProperties>;
const styles={page:{display:"grid",gap:14,paddingBottom:32},monthHeader:{display:"grid",gridTemplateColumns:"36px 1fr 36px",alignItems:"center",gap:8,marginTop:8},monthButton:{height:34,borderRadius:10,border:"1px solid #d1d5db",background:"#fff",fontSize:20,fontWeight:900},monthTitle:{textAlign:"center",fontSize:16,fontWeight:900},overviewSection:{display:"grid",gap:12},state:{padding:20,border:"1px solid #e5e7eb",borderRadius:14,background:"#fff",textAlign:"center",color:"#6b7280",fontSize:13},error:{padding:12,borderRadius:10,background:"#fef2f2",color:"#b91c1c"},partGroup:{display:"grid",gap:6},partTitle:{display:"flex",alignItems:"center",gap:6,borderRadius:10,padding:"7px 9px",fontSize:13,fontWeight:900},partCount:{marginLeft:"auto",fontSize:11,opacity:.75},staffList:{display:"grid",gap:6},summaryCard:{display:"grid",gap:7,padding:14,border:"1px solid #bfdbfe",borderRadius:12,background:"#eff6ff"},ledgerSection:{display:"grid",gap:10,marginTop:8,paddingTop:16,borderTop:"2px solid #e5e7eb"},ledgerTitle:{margin:0,fontSize:18},selected:{display:"grid",gap:9,padding:14,border:"1px solid #e5e7eb",borderRadius:12,background:"#fff"},amounts:{display:"grid",gap:6},detailRow:{display:"flex",justifyContent:"space-between",alignItems:"baseline",gap:10,fontSize:12},net:{fontSize:14},primaryLink:{padding:"11px 14px",borderRadius:11,background:"#111827",color:"#fff",textAlign:"center",fontWeight:800},help:{color:"#64748b",fontSize:11,lineHeight:1.4}} satisfies Record<string,CSSProperties>;
