export const CORE_STORE_TIMEZONE = "Asia/Ho_Chi_Minh";
export const CORE_STORE_CUTOFF = "03:00";
export type CoreBusinessHour = { weekday: number; isClosed: boolean; openTime: string | null; closeTime: string | null };
export const CORE_DEFAULT_HOURS: CoreBusinessHour[] = [{weekday:0,isClosed:false,openTime:"17:00",closeTime:"01:00"},...Array.from({length:6},(_,index)=>({weekday:index+1,isClosed:false,openTime:"16:00",closeTime:"01:00"}))];
const DATE_RE=/^\d{4}-\d{2}-\d{2}$/,TIME_RE=/^(?:[01]\d|2[0-3]):[0-5]\d$/;
function partsAt(value:Date,timeZone:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(value);const get=(type:Intl.DateTimeFormatPartTypes)=>Number(parts.find(part=>part.type===type)?.value);return{year:get("year"),month:get("month"),day:get("day"),hour:get("hour"),minute:get("minute")}}
function key(parts:{year:number;month:number;day:number}){return`${parts.year}-${String(parts.month).padStart(2,"0")}-${String(parts.day).padStart(2,"0")}`}
export function addStoreDays(value:string,days:number){if(!DATE_RE.test(value))throw new Error("Invalid date key");const[y,m,d]=value.split("-").map(Number),date=new Date(Date.UTC(y,m-1,d));date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
export function calculateStoreBusinessDate(value:Date|string,cutoff=CORE_STORE_CUTOFF,timeZone=CORE_STORE_TIMEZONE){if(!TIME_RE.test(cutoff))throw new Error("Invalid cutoff time");const date=value instanceof Date?value:new Date(value);if(!Number.isFinite(date.getTime()))throw new Error("Invalid timestamp");const parts=partsAt(date,timeZone),[h,m]=cutoff.split(":").map(Number),dateKey=key(parts);return parts.hour*60+parts.minute<h*60+m?addStoreDays(dateKey,-1):dateKey}
function minutes(value:string){if(!TIME_RE.test(value))throw new Error("Invalid time");const[h,m]=value.split(":").map(Number);return h*60+m}
export function getStoreOperationState(value:Date|string,hours:CoreBusinessHour[]=CORE_DEFAULT_HOURS,cutoff=CORE_STORE_CUTOFF,timeZone=CORE_STORE_TIMEZONE){const date=value instanceof Date?value:new Date(value);if(!Number.isFinite(date.getTime()))throw new Error("Invalid timestamp");const p=partsAt(date,timeZone),now=p.hour*60+p.minute,todayDay=new Date(Date.UTC(p.year,p.month-1,p.day)).getUTCDay(),previousDay=(todayDay+6)%7,today=hours.find(x=>x.weekday===todayDay),previous=hours.find(x=>x.weekday===previousDay);const inWindow=(item:CoreBusinessHour|undefined,afterMidnight:boolean)=>{if(!item||item.isClosed||!item.openTime||!item.closeTime)return false;const open=minutes(item.openTime),close=minutes(item.closeTime);return close>open?!afterMidnight&&now>=open&&now<close:afterMidnight?now<close:now>=open};const isOpen=inWindow(today,false)||inWindow(previous,true);return{isOpen,isAfterCloseBeforeCutoff:!isOpen&&now<minutes(cutoff)}}
export function validateStoreHours(hours:CoreBusinessHour[]){return hours.length===7&&new Set(hours.map(x=>x.weekday)).size===7&&hours.every(x=>x.weekday>=0&&x.weekday<=6&&(x.isClosed?x.openTime===null&&x.closeTime===null:Boolean(x.openTime&&x.closeTime&&TIME_RE.test(x.openTime)&&TIME_RE.test(x.closeTime)&&x.openTime!==x.closeTime)))}
export function isStoreDateKey(value:unknown):value is string{return typeof value==="string"&&DATE_RE.test(value)&&addStoreDays(value,0)===value}
export function isStoreTime(value:unknown):value is string{return typeof value==="string"&&TIME_RE.test(value)}
