"use client";

import Link from "next/link";
import { use, useEffect, useState, type CSSProperties } from "react";
import Container from "@/components/Container";
import { useLanguage } from "@/lib/language-context";
import { formatVnd } from "@/lib/payroll/payroll-page-money";

type Run={id:number;payroll_month:string;status:"paying"|"completed";target_employee_count:number;paid_employee_count:number;calculated_net_total:number;actual_paid_total:number;difference_total:number;employee_insurance_total:number;employer_insurance_total:number;director_insurance_amount:number;insurance_remittance_total:number;actual_company_cost_total:number;started_at:string;completed_at:string|null};
type Employee={id:number;employee_name:string;part_snapshot:string|null;position_snapshot:string|null;payment_status:"unpaid"|"paid";calculated_net_amount:number|null;actual_paid_amount:number|null;difference_amount:number|null;difference_reason:string|null;payment_date:string|null;paid_at:string|null;calculation_snapshot:Record<string,unknown>|null;paid_actor?:{name:string|null;full_name:string|null;username:string|null}|null};

export default function PayrollRunPage({params}:{params:Promise<{runId:string}>}){
  const {runId}=use(params);const{lang}=useLanguage();const vi=lang==="vi";const[run,setRun]=useState<Run|null>(null);const[employees,setEmployees]=useState<Employee[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();void(async()=>{try{const response=await fetch(`/api/admin/payroll/runs/${runId}`,{cache:"no-store",signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.code);setRun(data.run);setEmployees(data.employees??[])}catch(cause){if((cause as Error).name!=="AbortError")setError(vi?"Không thể tải sổ lương.":"급여장부를 불러오지 못했습니다.")}finally{if(!controller.signal.aborted)setLoading(false)}})();return()=>controller.abort()},[runId,vi]);
  if(loading)return <Container><p>{vi?"Đang tải…":"불러오는 중…"}</p></Container>;
  if(error||!run)return <Container><p role="alert" style={styles.error}>{error|| (vi?"Không tìm thấy.":"장부를 찾을 수 없습니다.")}</p><Link href="/admin/payroll">{vi?"Quay lại":"돌아가기"}</Link></Container>;
  const month=run.payroll_month.slice(0,7);const title=vi?`Sổ lương ${month.slice(5)}/${month.slice(0,4)}`:`${month.slice(0,4)}년 ${Number(month.slice(5))}월 급여장부`;
  return <Container><main style={styles.page}><Link href="/admin/payroll">← {vi?"Quản lý lương":"급여관리"}</Link><header style={styles.header}><div><h1 style={styles.title}>{title}</h1><span style={styles.badge}>{run.status==="completed"?(vi?"Hoàn tất":"완료"):(vi?"Đang chi trả":"지급 중")}</span></div><b>{run.paid_employee_count} / {run.target_employee_count}{vi?" người":"명"}</b></header>
    <section style={styles.card}><Row label={vi?"Bắt đầu":"시작일"} value={new Date(run.started_at).toLocaleString(vi?"vi-VN":"ko-KR")}/>{run.completed_at&&<Row label={vi?"Hoàn tất":"완료일"} value={new Date(run.completed_at).toLocaleString(vi?"vi-VN":"ko-KR")}/>}<Row label={vi?"Tổng lương tính":"계산 실수령 총액"} value={formatVnd(run.calculated_net_total)}/><Row label={vi?"Tổng thực trả":"실제 지급 총액"} value={formatVnd(run.actual_paid_total)}/><Row label={vi?"Tổng chênh lệch":"전체 차액"} value={formatVnd(run.difference_total)}/><Row label={vi?"Bảo hiểm công ty":"회사 보험부담"} value={formatVnd(run.employer_insurance_total)}/><Row label={vi?"Bảo hiểm giám đốc":"법인장 보험비"} value={formatVnd(run.director_insurance_amount)}/><Row label={vi?"Nộp cơ quan bảo hiểm":"보험기관 납부액"} value={formatVnd(run.insurance_remittance_total)}/><Row label={vi?"Tổng chi phí nhân công":"실제 총인건비"} value={formatVnd(run.actual_company_cost_total)} strong/></section>
    <section style={styles.list}><h2 style={styles.subtitle}>{vi?"Chi trả theo nhân viên":"직원별 지급 내역"}</h2>{employees.map(employee=><article key={employee.id} style={styles.employee}><div style={styles.employeeHead}><div><b>{employee.employee_name}</b><small style={styles.meta}>{[employee.part_snapshot,employee.position_snapshot].filter(Boolean).join(" · ")}</small></div><span style={employee.payment_status==="paid"?styles.paid:styles.unpaid}>{employee.payment_status==="paid"?(vi?"Đã trả":"지급완료"):(vi?"Chưa trả":"미지급")}</span></div>{employee.payment_status==="paid"?<><Row label={vi?"Lương tính":"계산 실수령액"} value={formatVnd(employee.calculated_net_amount??0)}/><Row label={vi?"Thực trả":"실제 지급액"} value={formatVnd(employee.actual_paid_amount??0)} strong/><Row label={vi?"Chênh lệch":"차액"} value={formatVnd(employee.difference_amount??0)}/>{employee.difference_reason&&<Row label={vi?"Lý do chênh lệch":"차액 사유"} value={employee.difference_reason}/>}<Row label={vi?"Ngày trả":"지급일"} value={employee.payment_date??"—"}/><Row label={vi?"Người xử lý":"지급 처리자"} value={actorName(employee.paid_actor)}/><Row label={vi?"Thời gian xử lý":"지급 시각"} value={employee.paid_at?new Date(employee.paid_at).toLocaleString(vi?"vi-VN":"ko-KR"):"—"}/>{employee.calculation_snapshot&&<details><summary style={styles.summary}>{vi?"Xem dữ liệu tính lương đã cố định":"지급 당시 계산 snapshot 보기"}</summary><pre style={styles.snapshot}>{JSON.stringify(employee.calculation_snapshot,null,2)}</pre></details>}</>:<p style={styles.muted}>{vi?"Chưa xử lý chi trả.":"아직 지급되지 않았습니다."}</p>}</article>)}</section>
  </main></Container>;
}
function actorName(actor:Employee["paid_actor"]){return actor?.name||actor?.full_name||actor?.username||"—"}
function Row({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div style={styles.row}><span>{label}</span><b style={strong?styles.strong:undefined}>{value}</b></div>}
const styles={page:{display:"grid",gap:14,paddingBottom:32},header:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12},title:{margin:"0 0 7px",fontSize:20},badge:{display:"inline-block",padding:"4px 8px",borderRadius:999,background:"#e0f2fe",color:"#075985",fontSize:11,fontWeight:800},card:{display:"grid",gap:7,padding:14,border:"1px solid #bfdbfe",borderRadius:12,background:"#eff6ff"},row:{display:"flex",justifyContent:"space-between",alignItems:"baseline",gap:12,minWidth:0,fontSize:12},strong:{fontSize:14,color:"#1d4ed8"},list:{display:"grid",gap:8},subtitle:{margin:0,fontSize:17},employee:{display:"grid",gap:7,padding:12,border:"1px solid #e5e7eb",borderRadius:11,background:"#fff"},employeeHead:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:8},meta:{display:"block",marginTop:2,color:"#64748b",fontSize:10},paid:{padding:"3px 7px",borderRadius:999,background:"#dcfce7",color:"#166534",fontSize:10,fontWeight:800},unpaid:{padding:"3px 7px",borderRadius:999,background:"#f1f5f9",color:"#475569",fontSize:10,fontWeight:800},muted:{margin:0,color:"#64748b",fontSize:12},summary:{cursor:"pointer",fontSize:11,fontWeight:700,color:"#475569"},snapshot:{maxWidth:"100%",overflow:"auto",padding:8,borderRadius:8,background:"#0f172a",color:"#e2e8f0",fontSize:9},error:{color:"#b91c1c"}} satisfies Record<string,CSSProperties>;
