create table public.store_setting_versions (
  id bigint generated by default as identity primary key,
  timezone text not null,
  business_day_cutoff_time time without time zone not null,
  effective_from_business_date date not null,
  revision bigint not null,
  state text not null default 'active',
  created_by bigint not null references public.users(id),
  created_at timestamptz not null default now(),
  cancelled_by bigint null references public.users(id),
  cancelled_at timestamptz null,
  cancel_reason text null,
  constraint store_setting_versions_timezone_check check (timezone = 'Asia/Ho_Chi_Minh'),
  constraint store_setting_versions_revision_check check (revision > 0),
  constraint store_setting_versions_state_check check (state in ('active', 'cancelled')),
  constraint store_setting_versions_cancel_state_check check (
    (state = 'active' and cancelled_by is null and cancelled_at is null and cancel_reason is null)
    or (state = 'cancelled' and cancelled_by is not null and cancelled_at is not null)
  ),
  constraint store_setting_versions_revision_unique unique (revision)
);

create table public.store_business_hours (
  id bigint generated by default as identity primary key,
  setting_version_id bigint not null references public.store_setting_versions(id) on delete cascade,
  weekday smallint not null,
  is_closed boolean not null default false,
  open_time time without time zone null,
  close_time time without time zone null,
  created_at timestamptz not null default now(),
  constraint store_business_hours_weekday_check check (weekday between 0 and 6),
  constraint store_business_hours_weekday_unique unique (setting_version_id, weekday),
  constraint store_business_hours_values_check check (
    (is_closed and open_time is null and close_time is null)
    or (not is_closed and open_time is not null and close_time is not null and open_time <> close_time)
  )
);

create table public.store_setting_audit_logs (
  id bigint generated by default as identity primary key,
  setting_version_id bigint not null references public.store_setting_versions(id),
  action text not null,
  actor_user_id bigint not null references public.users(id),
  before_snapshot jsonb null,
  after_snapshot jsonb null,
  created_at timestamptz not null default now(),
  constraint store_setting_audit_logs_action_check check (action in ('created', 'cancelled'))
);

create index store_setting_versions_active_effective_idx
  on public.store_setting_versions (effective_from_business_date desc, id desc)
  where state = 'active';
create unique index store_setting_versions_active_effective_unique
  on public.store_setting_versions (effective_from_business_date)
  where state = 'active';
create index store_setting_audit_logs_created_idx
  on public.store_setting_audit_logs (created_at desc, id desc);

alter table public.store_setting_versions enable row level security;
alter table public.store_business_hours enable row level security;
alter table public.store_setting_audit_logs enable row level security;

revoke all on table public.store_setting_versions from public, anon, authenticated;
revoke all on table public.store_business_hours from public, anon, authenticated;
revoke all on table public.store_setting_audit_logs from public, anon, authenticated;
grant select, insert, update on table public.store_setting_versions to service_role;
grant select, insert on table public.store_business_hours to service_role;
grant select, insert on table public.store_setting_audit_logs to service_role;
grant usage, select on sequence public.store_setting_versions_id_seq to service_role;
grant usage, select on sequence public.store_business_hours_id_seq to service_role;
grant usage, select on sequence public.store_setting_audit_logs_id_seq to service_role;

create or replace function public.store_business_date_v1(
  p_timestamp timestamptz,
  p_timezone text default 'Asia/Ho_Chi_Minh',
  p_cutoff time without time zone default '03:00'
) returns date
language sql
stable
security invoker
set search_path = pg_catalog, public
as $$
  select case
    when (p_timestamp at time zone p_timezone)::time < p_cutoff
      then ((p_timestamp at time zone p_timezone)::date - 1)
    else (p_timestamp at time zone p_timezone)::date
  end
$$;

do $$
begin
  if public.store_business_date_v1('2026-07-20 02:59:00+07'::timestamptz) <> '2026-07-19'::date
    or public.store_business_date_v1('2026-07-20 03:00:00+07'::timestamptz) <> '2026-07-20'::date
    or public.store_business_date_v1('2024-03-01 02:59:00+07'::timestamptz) <> '2024-02-29'::date
  then raise exception 'store_business_date_v1 boundary self-check failed';
  end if;
end $$;

create or replace function public.store_setting_snapshot_v1(p_version_id bigint)
returns jsonb
language sql
stable
security invoker
set search_path = pg_catalog, public
as $$
  select jsonb_build_object(
    'id', v.id,
    'timezone', v.timezone,
    'businessDayCutoffTime', to_char(v.business_day_cutoff_time, 'HH24:MI'),
    'effectiveFromBusinessDate', to_char(v.effective_from_business_date, 'YYYY-MM-DD'),
    'revision', v.revision,
    'state', v.state,
    'createdBy', v.created_by,
    'createdAt', v.created_at,
    'cancelledBy', v.cancelled_by,
    'cancelledAt', v.cancelled_at,
    'hours', coalesce((
      select jsonb_agg(jsonb_build_object(
        'weekday', h.weekday,
        'isClosed', h.is_closed,
        'openTime', case when h.open_time is null then null else to_char(h.open_time, 'HH24:MI') end,
        'closeTime', case when h.close_time is null then null else to_char(h.close_time, 'HH24:MI') end
      ) order by h.weekday)
      from public.store_business_hours h where h.setting_version_id = v.id
    ), '[]'::jsonb)
  )
  from public.store_setting_versions v where v.id = p_version_id
$$;

create or replace function public.store_business_date_for_timestamp_v1(p_timestamp timestamptz)
returns date
language plpgsql
stable
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_candidate date := public.store_business_date_v1(p_timestamp);
  v_timezone text;
  v_cutoff time;
  v_effective date;
  v_result date;
begin
  select timezone, business_day_cutoff_time, effective_from_business_date into v_timezone, v_cutoff, v_effective
  from public.store_setting_versions
  where state='active' and effective_from_business_date <= v_candidate
  order by effective_from_business_date desc,id desc limit 1;
  if v_timezone is null then return v_candidate; end if;
  v_result := public.store_business_date_v1(p_timestamp,v_timezone,v_cutoff);
  -- A new cutoff cannot move a timestamp back before the version's first
  -- business date. This removes the otherwise circular transition ambiguity.
  return greatest(v_result, v_effective);
end $$;

create or replace function public.store_get_settings_overview_v1(p_business_date date)
returns jsonb
language plpgsql
stable
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_current_id bigint;
  v_scheduled_id bigint;
  v_latest_revision bigint;
begin
  select id into v_current_id from public.store_setting_versions
  where state = 'active' and effective_from_business_date <= p_business_date
  order by effective_from_business_date desc, id desc limit 1;

  select id into v_scheduled_id from public.store_setting_versions
  where state = 'active' and effective_from_business_date > p_business_date
  order by effective_from_business_date asc, id asc limit 1;

  select coalesce(max(revision), 0) into v_latest_revision from public.store_setting_versions;
  return jsonb_build_object(
    'businessDate', to_char(p_business_date, 'YYYY-MM-DD'),
    'latestRevision', v_latest_revision,
    'current', case when v_current_id is null then null else public.store_setting_snapshot_v1(v_current_id) end,
    'scheduled', case when v_scheduled_id is null then null else public.store_setting_snapshot_v1(v_scheduled_id) end
  );
end $$;

create or replace function public.store_schedule_settings_v1(
  p_effective_from_business_date date,
  p_expected_revision bigint,
  p_timezone text,
  p_business_day_cutoff_time time without time zone,
  p_hours jsonb,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_current_business_date date := public.store_business_date_for_timestamp_v1(now());
  v_latest_revision bigint;
  v_version_id bigint;
  v_item jsonb;
  v_weekday integer;
  v_is_closed boolean;
  v_open time;
  v_close time;
begin
  perform pg_advisory_xact_lock(hashtext('store_settings_schedule_v1'));
  select role::text into v_role from public.users where id = p_actor_user_id and is_active = true;
  if lower(coalesce(v_role, '')) not in ('owner', 'master') then return jsonb_build_object('status', 'forbidden'); end if;
  select coalesce(max(revision), 0) into v_latest_revision from public.store_setting_versions;
  if p_expected_revision is distinct from v_latest_revision then return jsonb_build_object('status', 'version_conflict', 'latestRevision', v_latest_revision); end if;
  if p_effective_from_business_date <= v_current_business_date then return jsonb_build_object('status', 'invalid_effective_date'); end if;
  if p_timezone <> 'Asia/Ho_Chi_Minh' then return jsonb_build_object('status', 'invalid_timezone'); end if;
  if p_hours is null or jsonb_typeof(p_hours) <> 'array' then return jsonb_build_object('status', 'invalid_hours'); end if;
  if jsonb_array_length(p_hours) <> 7 then return jsonb_build_object('status', 'invalid_hours'); end if;
  if exists (select 1 from public.store_setting_versions where state='active' and effective_from_business_date > v_current_business_date) then return jsonb_build_object('status', 'scheduled_exists'); end if;

  insert into public.store_setting_versions(timezone,business_day_cutoff_time,effective_from_business_date,revision,created_by)
  values (p_timezone,p_business_day_cutoff_time,p_effective_from_business_date,v_latest_revision+1,p_actor_user_id)
  returning id into v_version_id;

  for v_item in select value from jsonb_array_elements(p_hours) loop
    if jsonb_typeof(v_item) <> 'object' then
      raise check_violation using message='invalid hours object';
    end if;
    if not (v_item ?& array['weekday','isClosed','openTime','closeTime'])
      or (select count(*) from jsonb_object_keys(v_item)) <> 4
      or jsonb_typeof(v_item->'weekday') <> 'number'
      or jsonb_typeof(v_item->'isClosed') <> 'boolean'
    then raise check_violation using message='invalid hours object'; end if;
    v_weekday := (v_item->>'weekday')::integer;
    v_is_closed := (v_item->>'isClosed')::boolean;
    v_open := nullif(v_item->>'openTime','')::time;
    v_close := nullif(v_item->>'closeTime','')::time;
    insert into public.store_business_hours(setting_version_id,weekday,is_closed,open_time,close_time)
    values(v_version_id,v_weekday,v_is_closed,v_open,v_close);
  end loop;
  if (select count(*) from public.store_business_hours where setting_version_id=v_version_id) <> 7 then raise check_violation using message='seven weekdays required'; end if;

  insert into public.store_setting_audit_logs(setting_version_id,action,actor_user_id,after_snapshot)
  values(v_version_id,'created',p_actor_user_id,public.store_setting_snapshot_v1(v_version_id));
  return jsonb_build_object('status','ok','setting',public.store_setting_snapshot_v1(v_version_id),'latestRevision',v_latest_revision+1);
exception when check_violation or unique_violation or not_null_violation
  or invalid_text_representation or invalid_datetime_format or datetime_field_overflow then
  return jsonb_build_object('status','invalid_hours');
end $$;

create or replace function public.store_cancel_scheduled_settings_v1(
  p_setting_version_id bigint,
  p_expected_revision bigint,
  p_actor_user_id bigint,
  p_cancel_reason text default null
) returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_current_business_date date := public.store_business_date_for_timestamp_v1(now());
  v_latest_revision bigint;
  v_before jsonb;
  v_version_id bigint;
begin
  perform pg_advisory_xact_lock(hashtext('store_settings_schedule_v1'));
  select role::text into v_role from public.users where id=p_actor_user_id and is_active=true;
  if lower(coalesce(v_role,'')) not in ('owner','master') then return jsonb_build_object('status','forbidden'); end if;
  select coalesce(max(revision),0) into v_latest_revision from public.store_setting_versions;
  if p_expected_revision is distinct from v_latest_revision then return jsonb_build_object('status','version_conflict','latestRevision',v_latest_revision); end if;
  select id into v_version_id from public.store_setting_versions
  where id=p_setting_version_id and state='active' and effective_from_business_date>v_current_business_date for update;
  if v_version_id is null then return jsonb_build_object('status','not_found'); end if;
  v_before := public.store_setting_snapshot_v1(v_version_id);
  update public.store_setting_versions set state='cancelled',revision=v_latest_revision+1,cancelled_by=p_actor_user_id,cancelled_at=now(),cancel_reason=nullif(btrim(p_cancel_reason),'') where id=p_setting_version_id;
  insert into public.store_setting_audit_logs(setting_version_id,action,actor_user_id,before_snapshot,after_snapshot)
  values(p_setting_version_id,'cancelled',p_actor_user_id,v_before,public.store_setting_snapshot_v1(p_setting_version_id));
  return jsonb_build_object('status','ok','latestRevision',v_latest_revision+1);
end $$;

create or replace function public.store_list_setting_audit_logs_v1(p_limit integer default 50)
returns setof public.store_setting_audit_logs
language sql stable security invoker set search_path = pg_catalog, public
as $$ select * from public.store_setting_audit_logs order by created_at desc,id desc limit least(greatest(p_limit,1),100) $$;

revoke all on function public.store_business_date_v1(timestamptz,text,time) from public,anon,authenticated;
revoke all on function public.store_setting_snapshot_v1(bigint) from public,anon,authenticated;
revoke all on function public.store_business_date_for_timestamp_v1(timestamptz) from public,anon,authenticated;
revoke all on function public.store_get_settings_overview_v1(date) from public,anon,authenticated;
revoke all on function public.store_schedule_settings_v1(date,bigint,text,time,jsonb,bigint) from public,anon,authenticated;
revoke all on function public.store_cancel_scheduled_settings_v1(bigint,bigint,bigint,text) from public,anon,authenticated;
revoke all on function public.store_list_setting_audit_logs_v1(integer) from public,anon,authenticated;
grant execute on function public.store_business_date_v1(timestamptz,text,time) to service_role;
grant execute on function public.store_setting_snapshot_v1(bigint) to service_role;
grant execute on function public.store_business_date_for_timestamp_v1(timestamptz) to service_role;
grant execute on function public.store_get_settings_overview_v1(date) to service_role;
grant execute on function public.store_schedule_settings_v1(date,bigint,text,time,jsonb,bigint) to service_role;
grant execute on function public.store_cancel_scheduled_settings_v1(bigint,bigint,bigint,text) to service_role;
grant execute on function public.store_list_setting_audit_logs_v1(integer) to service_role;

comment on column public.store_business_hours.weekday is 'JavaScript/PostgreSQL application convention: 0=Sunday through 6=Saturday.';
comment on table public.store_setting_versions is 'Versioned store policy. Current/scheduled state is derived from effective_from_business_date; state only records active/cancelled.';
comment on function public.store_business_date_v1(timestamptz,text,time) is 'Cutoff-only business date calculation; opening hours do not affect business_date.';
