-- 베트남 법정공휴일 원본과 BABA 내부 운영 지침(200% 적용)을 완전히 분리한다.
--
-- 배경
--   BABA 내부 운영 지침: "관리자가 선택한 공휴일 날짜 = 매장 영업 + 내부 200% 적용".
--   이것은 베트남 노동법상 법정 지급률이 아니라 BABA 고유의 내부 정책이다. 그래서
--   법정공휴일 원본(store_holidays)과 절대 같은 필드로 표현하지 않는다 — 새 테이블
--   store_holiday_operation_policies로 분리하고, 컬럼명에도 법률적 의미를 암시하는
--   이름(statutory_pay_rate, legal_pay_multiplier, legally_paid 등)을 쓰지 않는다.
--
-- 두 데이터의 관계
--   store_holidays        = 베트남 법정공휴일 원본(변경 없음, 이번 Migration에서 건드리지 않음)
--   store_holiday_operation_policies = 그 중 BABA가 "매장 영업 + 내부 200% 적용"으로
--     실제 선택한 날짜만. 정책 row가 없으면 기본적으로 200% 미적용이다(선택 해제 시
--     store_holidays 원본을 지우지 않고 이 테이블의 row만 삭제한다).
--
--   즉 관리자가 어떤 법정공휴일 날짜의 선택을 해제해도 store_holidays의 해당 행은
--   절대 DELETE하지 않는다 — 법정공휴일 원본과 BABA 내부 정책은 생명주기가 다르다.
--
-- 202608080003(이미 운영 적용됨)과의 관계 — 중요
--   store_holiday_calendars.tet_option / national_day_adjacent_date / status /
--   confirmed_by / confirmed_at 와 store_set_holiday_tet_option_v1 RPC는 "음력설
--   날짜 묶음을 선택해 그 해 공휴일을 확정한다"는 이전 UX를 위한 것이었다. 이번
--   변경으로 그 UX(묶음 선택 + 연도 확정)를 완전히 제거하고, 이후에는 store_holidays에
--   이미 존재하는 개별 법정공휴일 날짜마다 BABA가 200% 적용 여부를 개별 토글하는
--   방식으로 대체한다.
--
--   202608080003은 이미 운영 DB에 적용되어 실제 이력(예: 2026년 tet_option이 실제로
--   선택된 기록)을 담고 있으므로, 이번 Migration에서 그 테이블/컬럼/RPC를 DROP하거나
--   ALTER하지 않는다 — 과거 사실을 지우는 것은 이득이 없고 위험만 크다. 애플리케이션
--   코드(API/UI)만 더 이상 이 컬럼들을 읽거나 store_set_holiday_tet_option_v1을
--   호출하지 않도록 바꾼다. 이 컬럼/RPC는 이후 사용되지 않는 채로 남는다(제거하지
--   않지만 활성 경로에서는 완전히 빠진다).
--
-- 202608080003 이후 실제로 선택되었던 음력설(2026-02-16~02-20, one_before_four_after)은
-- 이 Migration이 자동으로 store_holiday_operation_policies에 옮겨 심지 않는다 —
-- "BABA가 200% 적용을 선택했다"는 이제 새 정책 하에서 다시 내려야 하는 별도의
-- 명시적 결정이기 때문이다(정책 row가 없으면 기본적으로 200% 미적용이 안전한 기본값).

begin;

-- ---------------------------------------------------------------------------
-- 0. Preflight
-- ---------------------------------------------------------------------------
do $$
begin
  if to_regclass('public.store_holidays') is null then
    raise exception 'preflight failed: missing dependency public.store_holidays';
  end if;
  if to_regclass('public.users') is null then
    raise exception 'preflight failed: missing dependency public.users';
  end if;
  if to_regclass('public.store_holiday_operation_policies') is not null then
    raise exception 'preflight failed: store_holiday_operation_policies already exists';
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 1. store_holiday_operation_policies — BABA 내부 200% 적용 대상 날짜만.
--    holiday_id는 store_holidays.id를 직접 참조한다(법정공휴일 원본과의 1:0..1
--    관계 — 정책 row가 없으면 그 법정공휴일은 200% 미적용이라는 뜻).
-- ---------------------------------------------------------------------------

create table public.store_holiday_operation_policies (
  id bigint generated by default as identity primary key,
  holiday_id bigint not null references public.store_holidays(id) on delete cascade,
  -- BABA 내부 운영 지침 배율이다 — 베트남 노동법상 법정 지급률이 아니다. 1차에서는
  -- 항상 2.0(200%)만 쓰지만, 향후 급여 연동에서 다른 배율이 필요해질 수 있어 boolean이
  -- 아니라 numeric으로 둔다.
  internal_pay_multiplier numeric not null,
  updated_by bigint not null references public.users(id) on delete restrict,
  updated_at timestamptz not null default now(),
  constraint store_holiday_operation_policies_holiday_unique unique (holiday_id),
  constraint store_holiday_operation_policies_multiplier_check check (internal_pay_multiplier > 0)
);

alter table public.store_holiday_operation_policies enable row level security;

revoke all on table public.store_holiday_operation_policies from public, anon, authenticated, service_role;
revoke all on sequence public.store_holiday_operation_policies_id_seq from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.store_holiday_operation_policies to service_role;
grant usage, select on sequence public.store_holiday_operation_policies_id_seq to service_role;

comment on table public.store_holiday_operation_policies is
  'BABA-internal operational pay policy per statutory holiday date — NOT a statutory/legal pay rate. A row means the store owner/master has chosen "store open + internal Nx pay" for that specific store_holidays row; absence of a row means no internal premium applies (default-deny). Deselecting never deletes the underlying store_holidays row (the legal holiday source is independent and permanent). Superseded the previous tet_option bundle-selection UX (store_holiday_calendars / store_set_holiday_tet_option_v1 from 202608080003), which is left in place unused for historical accuracy rather than dropped.';

-- ---------------------------------------------------------------------------
-- 2. store_toggle_holiday_operation_policy_v1 — 날짜 1개를 선택/해제한다(즉시 저장
--    UX, 단일 row 연산이라 함수 자체가 이미 원자적이다). owner/master만 실행 가능.
-- ---------------------------------------------------------------------------

create function public.store_toggle_holiday_operation_policy_v1(
  p_holiday_id bigint,
  p_selected boolean,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_holiday_exists boolean;
  v_multiplier constant numeric := 2.0; -- BABA 내부 운영 지침 고정값(법정 지급률 아님). 향후 배율이 여러 개 필요해지면 파라미터화한다.
begin
  perform pg_advisory_xact_lock(hashtext('store_holiday_operation_policy_v1:' || p_holiday_id::text));

  select role::text into v_role
  from public.users
  where id = p_actor_user_id and is_active = true;

  if lower(coalesce(v_role, '')) not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;

  select exists(select 1 from public.store_holidays where id = p_holiday_id) into v_holiday_exists;
  if not v_holiday_exists then
    return jsonb_build_object('status', 'not_found');
  end if;

  if p_selected then
    insert into public.store_holiday_operation_policies (holiday_id, internal_pay_multiplier, updated_by, updated_at)
    values (p_holiday_id, v_multiplier, p_actor_user_id, now())
    on conflict (holiday_id) do update set
      internal_pay_multiplier = excluded.internal_pay_multiplier,
      updated_by = excluded.updated_by,
      updated_at = excluded.updated_at;
  else
    -- store_holidays 원본은 절대 지우지 않는다 — 이 정책 row만 제거한다.
    delete from public.store_holiday_operation_policies where holiday_id = p_holiday_id;
  end if;

  return jsonb_build_object(
    'status', 'ok',
    'holidayId', p_holiday_id,
    'selected', p_selected,
    'internalPayMultiplier', case when p_selected then v_multiplier else null end
  );
exception
  when check_violation or unique_violation or not_null_violation then
    return jsonb_build_object('status', 'invalid_request');
end
$$;

revoke all on function public.store_toggle_holiday_operation_policy_v1(bigint, boolean, bigint) from public;
revoke all on function public.store_toggle_holiday_operation_policy_v1(bigint, boolean, bigint) from anon;
revoke all on function public.store_toggle_holiday_operation_policy_v1(bigint, boolean, bigint) from authenticated;
grant execute on function public.store_toggle_holiday_operation_policy_v1(bigint, boolean, bigint) to service_role;

-- ---------------------------------------------------------------------------
-- 3. Postflight — 새 테이블은 빈 상태로 시작해야 한다(과거 tet_option 선택을
--    자동으로 이전하지 않음 — BABA가 새 UI에서 다시 명시적으로 선택해야 한다).
-- ---------------------------------------------------------------------------
do $$
begin
  if (select count(*) from public.store_holiday_operation_policies) <> 0 then
    raise exception 'postflight failed: store_holiday_operation_policies must start empty (no automatic carry-over from the old tet_option selection)';
  end if;
  if not exists (
    select 1 from public.store_holidays where calendar_year = 2026
  ) then
    raise exception 'postflight failed: expected store_holidays to already contain 2026 rows from 202608080003';
  end if;
end
$$;

commit;
