begin;

do $$
begin
  if to_regprocedure('public.payroll_assert_actor_v2(bigint)') is null then
    raise exception 'preflight failed: missing public.payroll_assert_actor_v2(bigint)';
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'users'
      and column_name = 'attendance_tracking_enabled'
  ) then
    raise exception 'preflight failed: missing public.users.attendance_tracking_enabled';
  end if;
end
$$;

create table public.payroll_attendance_bonus_policy_versions (
  id bigint generated by default as identity primary key,
  effective_month date not null,
  minimum_actual_workdays integer not null,
  allowed_late_count integer not null,
  allowed_early_leave_count integer not null,
  bonus_amount numeric(16,0) not null,
  revision bigint not null,
  created_by bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  note text null,
  constraint payroll_attendance_bonus_policy_month_first_check
    check (effective_month = date_trunc('month', effective_month)::date),
  constraint payroll_attendance_bonus_policy_workdays_check
    check (minimum_actual_workdays > 0),
  constraint payroll_attendance_bonus_policy_late_count_check
    check (allowed_late_count >= 0),
  constraint payroll_attendance_bonus_policy_early_count_check
    check (allowed_early_leave_count >= 0),
  constraint payroll_attendance_bonus_policy_amount_check
    check (bonus_amount > 0 and bonus_amount = trunc(bonus_amount)),
  constraint payroll_attendance_bonus_policy_revision_check check (revision >= 1),
  constraint payroll_attendance_bonus_policy_revision_unique unique (revision)
);

create index payroll_attendance_bonus_policy_lookup_idx
  on public.payroll_attendance_bonus_policy_versions (effective_month desc, revision desc);
create index payroll_attendance_bonus_policy_created_by_idx
  on public.payroll_attendance_bonus_policy_versions (created_by);

alter table public.payroll_attendance_bonus_policy_versions enable row level security;
revoke all on table public.payroll_attendance_bonus_policy_versions
  from public, anon, authenticated, service_role;
revoke all on sequence public.payroll_attendance_bonus_policy_versions_id_seq
  from public, anon, authenticated, service_role;
grant select, insert on table public.payroll_attendance_bonus_policy_versions to service_role;
grant usage, select on sequence public.payroll_attendance_bonus_policy_versions_id_seq to service_role;

comment on table public.payroll_attendance_bonus_policy_versions is
  'Append-only monthly company attendance bonus policy. The latest effective_month/revision at or before a payroll month applies.';

create table public.payroll_attendance_bonus_eligibility_versions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  is_eligible boolean not null,
  effective_month date not null,
  revision bigint not null,
  created_by bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  note text null,
  constraint payroll_attendance_bonus_eligibility_month_first_check
    check (effective_month = date_trunc('month', effective_month)::date),
  constraint payroll_attendance_bonus_eligibility_revision_check check (revision >= 1),
  constraint payroll_attendance_bonus_eligibility_revision_unique unique (user_id, revision)
);

create index payroll_attendance_bonus_eligibility_lookup_idx
  on public.payroll_attendance_bonus_eligibility_versions
  (user_id, effective_month desc, revision desc);
create index payroll_attendance_bonus_eligibility_created_by_idx
  on public.payroll_attendance_bonus_eligibility_versions (created_by);

alter table public.payroll_attendance_bonus_eligibility_versions enable row level security;
revoke all on table public.payroll_attendance_bonus_eligibility_versions
  from public, anon, authenticated, service_role;
revoke all on sequence public.payroll_attendance_bonus_eligibility_versions_id_seq
  from public, anon, authenticated, service_role;
grant select, insert on table public.payroll_attendance_bonus_eligibility_versions to service_role;
grant usage, select on sequence public.payroll_attendance_bonus_eligibility_versions_id_seq to service_role;

comment on table public.payroll_attendance_bonus_eligibility_versions is
  'Append-only monthly per-employee attendance bonus eligibility. No row means not eligible.';

create function public.payroll_create_attendance_bonus_policy_version_v1(
  p_effective_month date,
  p_minimum_actual_workdays integer,
  p_allowed_late_count integer,
  p_allowed_early_leave_count integer,
  p_bonus_amount numeric,
  p_actor_user_id bigint,
  p_note text default null
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_current_month date := date_trunc('month', now() at time zone 'Asia/Ho_Chi_Minh')::date;
  v_revision bigint;
  v_created public.payroll_attendance_bonus_policy_versions%rowtype;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);
  if p_effective_month is null
    or p_effective_month <> date_trunc('month', p_effective_month)::date
    or p_effective_month < v_current_month then
    raise exception 'ATTENDANCE_BONUS_INVALID_EFFECTIVE_MONTH' using errcode = '22023';
  end if;
  if p_minimum_actual_workdays is null or p_minimum_actual_workdays <= 0 then
    raise exception 'ATTENDANCE_BONUS_INVALID_MINIMUM_WORKDAYS' using errcode = '22023';
  end if;
  if p_allowed_late_count is null or p_allowed_late_count < 0
    or p_allowed_early_leave_count is null or p_allowed_early_leave_count < 0 then
    raise exception 'ATTENDANCE_BONUS_INVALID_ALLOWANCE_COUNTS' using errcode = '22023';
  end if;
  if p_bonus_amount is null or p_bonus_amount <= 0 or p_bonus_amount <> trunc(p_bonus_amount) then
    raise exception 'ATTENDANCE_BONUS_INVALID_AMOUNT' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtext('payroll_attendance_bonus_policy_versions'));
  select coalesce(max(revision), 0) + 1 into v_revision
  from public.payroll_attendance_bonus_policy_versions;
  insert into public.payroll_attendance_bonus_policy_versions (
    effective_month, minimum_actual_workdays, allowed_late_count,
    allowed_early_leave_count, bonus_amount, revision, created_by, note
  ) values (
    p_effective_month, p_minimum_actual_workdays, p_allowed_late_count,
    p_allowed_early_leave_count, p_bonus_amount, v_revision, p_actor_user_id,
    nullif(btrim(p_note), '')
  ) returning * into v_created;
  return to_jsonb(v_created);
end;
$$;

revoke all on function public.payroll_create_attendance_bonus_policy_version_v1(
  date, integer, integer, integer, numeric, bigint, text
) from public, anon, authenticated;
grant execute on function public.payroll_create_attendance_bonus_policy_version_v1(
  date, integer, integer, integer, numeric, bigint, text
) to service_role;

create function public.payroll_create_attendance_bonus_eligibility_version_v1(
  p_user_id bigint,
  p_is_eligible boolean,
  p_effective_month date,
  p_actor_user_id bigint,
  p_note text default null
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_current_month date := date_trunc('month', now() at time zone 'Asia/Ho_Chi_Minh')::date;
  v_revision bigint;
  v_target public.users%rowtype;
  v_created public.payroll_attendance_bonus_eligibility_versions%rowtype;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);
  if p_is_eligible is null then
    raise exception 'ATTENDANCE_BONUS_INVALID_ELIGIBILITY' using errcode = '22023';
  end if;
  if p_effective_month is null
    or p_effective_month <> date_trunc('month', p_effective_month)::date
    or p_effective_month < v_current_month then
    raise exception 'ATTENDANCE_BONUS_INVALID_EFFECTIVE_MONTH' using errcode = '22023';
  end if;

  select * into v_target from public.users
  where id = p_user_id and is_system_account = false for share;
  if not found then raise exception 'USER_NOT_FOUND' using errcode = 'P0002'; end if;
  if p_is_eligible and v_target.attendance_tracking_enabled is distinct from true then
    raise exception 'ATTENDANCE_BONUS_REQUIRES_ATTENDANCE_TRACKING' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtext('payroll_attendance_bonus_eligibility_versions:' || p_user_id::text));
  select coalesce(max(revision), 0) + 1 into v_revision
  from public.payroll_attendance_bonus_eligibility_versions where user_id = p_user_id;
  insert into public.payroll_attendance_bonus_eligibility_versions (
    user_id, is_eligible, effective_month, revision, created_by, note
  ) values (
    p_user_id, p_is_eligible, p_effective_month, v_revision, p_actor_user_id,
    nullif(btrim(p_note), '')
  ) returning * into v_created;
  return to_jsonb(v_created);
end;
$$;

revoke all on function public.payroll_create_attendance_bonus_eligibility_version_v1(
  bigint, boolean, date, bigint, text
) from public, anon, authenticated;
grant execute on function public.payroll_create_attendance_bonus_eligibility_version_v1(
  bigint, boolean, date, bigint, text
) to service_role;

create function public.users_block_attendance_tracking_disable_when_bonus_eligible()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_current_month date := date_trunc('month', now() at time zone 'Asia/Ho_Chi_Minh')::date;
  v_has_eligible boolean;
begin
  if old.attendance_tracking_enabled is distinct from true
    or new.attendance_tracking_enabled is distinct from false then
    return new;
  end if;
  select exists (
    select 1 from (
      (select is_eligible
       from public.payroll_attendance_bonus_eligibility_versions
       where user_id = new.id and effective_month <= v_current_month
       order by effective_month desc, revision desc limit 1)
      union all
      (select distinct on (effective_month) is_eligible
       from public.payroll_attendance_bonus_eligibility_versions
       where user_id = new.id and effective_month > v_current_month
       order by effective_month, revision desc)
    ) resolved where resolved.is_eligible
  ) into v_has_eligible;
  if v_has_eligible then
    raise exception 'ATTENDANCE_BONUS_ELIGIBLE_BLOCKS_ATTENDANCE_TRACKING_DISABLE'
      using errcode = '55000';
  end if;
  return new;
end;
$$;

create trigger users_block_attendance_tracking_disable_when_bonus_eligible
  before update on public.users for each row
  execute function public.users_block_attendance_tracking_disable_when_bonus_eligible();

revoke all on function public.users_block_attendance_tracking_disable_when_bonus_eligible()
  from public, anon, authenticated;

commit;

-- Postflight (read only, run after applying):
-- select relname, relrowsecurity from pg_class where oid in (
--   'public.payroll_attendance_bonus_policy_versions'::regclass,
--   'public.payroll_attendance_bonus_eligibility_versions'::regclass
-- );
-- select grantee, table_name, privilege_type from information_schema.role_table_grants
-- where table_schema = 'public' and table_name like 'payroll_attendance_bonus_%';
-- select routine_name, grantee, privilege_type from information_schema.role_routine_grants
-- where routine_schema = 'public' and routine_name like '%attendance_bonus%';
-- select indexname from pg_indexes where schemaname = 'public'
-- and tablename like 'payroll_attendance_bonus_%' order by indexname;
