-- Preserve each prior close while allowing the same month row to be reopened and closed again.
-- No operational rows are changed by this migration.
alter table public.ledger_month_closures drop constraint ledger_month_closures_status_check;
alter table public.ledger_month_closures add constraint ledger_month_closures_status_check
  check (status in ('closed', 'reopened'));
alter table public.ledger_month_closures
  add column reopened_at timestamptz,
  add column reopened_by bigint references public.users(id) on delete restrict,
  add column reopen_reason text,
  add column revision integer not null default 1;
alter table public.ledger_month_closures add constraint ledger_month_closures_revision_check check (revision >= 1);

create table public.ledger_month_closure_history (
  id bigint generated by default as identity primary key,
  closure_id bigint not null references public.ledger_month_closures(id) on delete restrict,
  month date not null check (month = date_trunc('month', month)::date),
  revision integer not null check (revision >= 1),
  closed_at timestamptz not null,
  closed_by bigint not null references public.users(id) on delete restrict,
  preflight_snapshot jsonb not null check (jsonb_typeof(preflight_snapshot) = 'object'),
  summary_snapshot jsonb not null check (jsonb_typeof(summary_snapshot) = 'object'),
  snapshot_hash text not null check (snapshot_hash ~ '^[0-9a-f]{64}$'),
  warning_snapshot jsonb not null check (jsonb_typeof(warning_snapshot) = 'array'),
  archived_reason text not null check (btrim(archived_reason) <> ''),
  archived_at timestamptz not null default now(),
  archived_by bigint not null references public.users(id) on delete restrict,
  unique (closure_id, revision)
);
alter table public.ledger_month_closure_history owner to postgres;
alter sequence public.ledger_month_closure_history_id_seq owner to postgres;
alter table public.ledger_month_closure_history enable row level security;
revoke all on table public.ledger_month_closure_history from public, anon, authenticated, service_role;
revoke all on sequence public.ledger_month_closure_history_id_seq from public, anon, authenticated, service_role;
grant select on table public.ledger_month_closure_history to service_role;

create or replace function public.ledger_reopen_month_v1(
  p_month date, p_reason text, p_actor_user_id bigint
) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_month date;
  v_reason text;
  v_role text;
  v_closure public.ledger_month_closures%rowtype;
  v_reopened_at timestamptz;
begin
  select lower(role::text) into v_role from public.users
  where id=p_actor_user_id and is_active=true and app_login_enabled=true;
  if coalesce(v_role,'') not in ('owner','master') then
    return jsonb_build_object('status','forbidden');
  end if;
  if p_month is null then return jsonb_build_object('status','invalid_month'); end if;
  v_month:=date_trunc('month',p_month)::date;
  v_reason:=btrim(coalesce(p_reason,''));
  if v_reason='' then return jsonb_build_object('status','reason_required'); end if;

  -- Serialize cross-month closes too, so a later month cannot close during this check.
  perform pg_advisory_xact_lock(hashtext('ledger_month_close_serial'));
  perform pg_advisory_xact_lock(hashtext('ledger_month_close'),hashtext(v_month::text));
  select * into v_closure from public.ledger_month_closures
  where month=v_month for update;
  if v_closure.id is null then return jsonb_build_object('status','not_closed'); end if;
  if v_closure.status='reopened' then return jsonb_build_object('status','already_reopened'); end if;
  if exists(select 1 from public.ledger_month_closures where month>v_month and status='closed') then
    return jsonb_build_object('status','later_month_closed');
  end if;

  insert into public.ledger_month_closure_history(
    closure_id,month,revision,closed_at,closed_by,preflight_snapshot,
    summary_snapshot,snapshot_hash,warning_snapshot,archived_reason,archived_by
  ) values (
    v_closure.id,v_closure.month,v_closure.revision,v_closure.closed_at,v_closure.closed_by,
    v_closure.preflight_snapshot,v_closure.summary_snapshot,v_closure.snapshot_hash,
    v_closure.warning_snapshot,v_reason,p_actor_user_id
  );
  v_reopened_at:=now();
  update public.ledger_month_closures
  set status='reopened',reopened_at=v_reopened_at,reopened_by=p_actor_user_id,reopen_reason=v_reason
  where id=v_closure.id;
  insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,before_snapshot,after_snapshot,reason)
  values(p_actor_user_id,'month_reopen','month_closure',v_closure.id,
    jsonb_build_object('status',v_closure.status,'month',v_month,'revision',v_closure.revision,
      'snapshotHash',v_closure.snapshot_hash,'closedAt',v_closure.closed_at,'closedBy',v_closure.closed_by),
    jsonb_build_object('status','reopened','month',v_month,'revision',v_closure.revision,
      'reopenedAt',v_reopened_at,'reopenedBy',p_actor_user_id,'reason',v_reason),v_reason);
  return jsonb_build_object('status','reopened','closureId',v_closure.id,'month',v_month,'revision',v_closure.revision);
end$$;

create or replace function public.ledger_close_month_v1(
  p_month date,p_expected_preflight_hash text,p_preflight_snapshot jsonb,
  p_summary_snapshot jsonb,p_snapshot_hash text,p_actor_user_id bigint
) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_check jsonb;
  v_month date;
  v_closure public.ledger_month_closures%rowtype;
  v_id bigint;
  v_revision integer;
  v_closed_at timestamptz;
begin
  -- The reopen RPC takes these locks in the same order before locking the row.
  if p_month is null then return jsonb_build_object('status','invalid_month'); end if;
  v_month:=date_trunc('month',p_month)::date;
  perform pg_advisory_xact_lock(hashtext('ledger_month_close_serial'));
  perform pg_advisory_xact_lock(hashtext('ledger_month_close'),hashtext(v_month::text));
  select * into v_closure from public.ledger_month_closures where month=v_month for update;
  if v_closure.status='closed' then return jsonb_build_object('status','already_closed'); end if;
  if exists(select 1 from public.ledger_month_closures where month<v_month and status='reopened') then
    return jsonb_build_object('status','blocked','blockers',
      jsonb_build_array(jsonb_build_object('code','EARLIER_MONTH_REOPENED')));
  end if;

  -- Recompute under the lock for both the first close and every reclose.
  v_check:=public.ledger_close_preflight_v1(p_month,p_actor_user_id);
  if v_check->>'status'<>'ok' then return v_check; end if;
  if v_check->>'preflightHash' is distinct from p_expected_preflight_hash then
    return jsonb_build_object('status','preflight_stale','code','LEDGER_CLOSE_PREFLIGHT_STALE');
  end if;
  if not (v_check->>'canClose')::boolean then
    return jsonb_build_object('status','blocked','blockers',v_check->'blockers');
  end if;
  if coalesce(jsonb_typeof(p_preflight_snapshot),'')<>'object'
    or coalesce(jsonb_typeof(p_summary_snapshot),'')<>'object'
    or p_snapshot_hash is null or p_snapshot_hash!~'^[0-9a-f]{64}$' then
    return jsonb_build_object('status','invalid_snapshot');
  end if;

  if v_closure.id is null then
    insert into public.ledger_month_closures(
      month,closed_by,preflight_snapshot,summary_snapshot,snapshot_hash,warning_snapshot,revision
    ) values (
      p_month,p_actor_user_id,p_preflight_snapshot,p_summary_snapshot,p_snapshot_hash,
      coalesce(v_check->'warnings','[]'::jsonb),1
    ) returning id into v_id;
    insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,after_snapshot,reason)
    values(p_actor_user_id,'month_closed','month_closure',v_id,
      jsonb_build_object('status','closed','month',p_month,'revision',1,
        'preflightHash',p_expected_preflight_hash,'snapshotHash',p_snapshot_hash),
      'Initial month close');
    return jsonb_build_object('status','closed','closureId',v_id,'month',p_month,
      'revision',1,'snapshotHash',p_snapshot_hash);
  end if;

  v_id:=v_closure.id;
  v_revision:=v_closure.revision+1;
  v_closed_at:=now();
  update public.ledger_month_closures set
    status='closed',closed_at=v_closed_at,closed_by=p_actor_user_id,
    preflight_snapshot=p_preflight_snapshot,summary_snapshot=p_summary_snapshot,
    snapshot_hash=p_snapshot_hash,warning_snapshot=coalesce(v_check->'warnings','[]'::jsonb),
    revision=v_revision
  where id=v_id;
  insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,before_snapshot,after_snapshot,reason)
  values(p_actor_user_id,'month_reclose','month_closure',v_id,
    jsonb_build_object('status','reopened','month',v_month,'revision',v_closure.revision,
      'snapshotHash',v_closure.snapshot_hash,'reopenedAt',v_closure.reopened_at,
      'reopenedBy',v_closure.reopened_by,'reopenReason',v_closure.reopen_reason),
    jsonb_build_object('status','closed','month',v_month,'revision',v_revision,
      'snapshotHash',p_snapshot_hash,'closedAt',v_closed_at,'closedBy',p_actor_user_id),
    'Month reclosed after review');
  return jsonb_build_object('status','closed','closureId',v_id,'month',v_month,
    'revision',v_revision,'snapshotHash',p_snapshot_hash);
exception when unique_violation then
  return jsonb_build_object('status','already_closed');
end$$;

alter function public.ledger_reopen_month_v1(date,text,bigint) owner to postgres;
alter function public.ledger_close_month_v1(date,text,jsonb,jsonb,text,bigint) owner to postgres;
revoke all on function public.ledger_reopen_month_v1(date,text,bigint) from public,anon,authenticated;
revoke all on function public.ledger_close_month_v1(date,text,jsonb,jsonb,text,bigint) from public,anon,authenticated;
grant execute on function public.ledger_reopen_month_v1(date,text,bigint) to service_role,postgres;
grant execute on function public.ledger_close_month_v1(date,text,jsonb,jsonb,text,bigint) to service_role,postgres;

-- Keep the current profit-capacity contract, excluding retained snapshots while reopened.
create or replace function public.ledger_owner_financial_capacity_v1(p_through_month date)
returns jsonb language plpgsql security definer
set search_path = pg_catalog, public as $$
declare
  v_start date; v_opening numeric; v_profit numeric; v_settled numeric;
  v_liquid numeric; v_reserve numeric; v_payable numeric; v_owner_unpaid numeric;
  v_safe numeric; v_undistributed numeric;
begin
  select profit_tracking_start_month, opening_undistributed_profit
  into v_start, v_opening from public.ledger_owner_profit_settings where singleton;
  if v_start is null then
    return jsonb_build_object('status', 'profit_tracking_not_configured');
  end if;
  select coalesce(sum((summary_snapshot#>>'{operatingResult,operatingProfit}')::numeric), 0)
  into v_profit from public.ledger_month_closures
  where status = 'closed'
    and month between v_start and p_through_month;
  select coalesce(sum(confirmed_pool), 0) into v_settled
  from public.ledger_owner_settlements
  where status in ('confirmed', 'partially_paid', 'paid')
    and settlement_type = 'profit_distribution'
    and through_month between v_start and p_through_month;
  v_undistributed := v_opening + v_profit - v_settled;
  select coalesce(sum(m.amount), 0) into v_liquid
  from public.ledger_movements m
  join public.ledger_transactions t on t.id = m.transaction_id
  join public.ledger_fund_accounts f on f.id = m.fund_account_id
  where t.status = 'confirmed' and t.occurred_at <= now()
    and f.is_active and f.is_business_fund
    and f.type in ('cash', 'bank', 'personal_custody');
  select coalesce(sum(case entry_type when 'allocate' then amount
    when 'release' then -amount when 'consume' then -amount else amount end), 0)
  into v_reserve from public.ledger_reserve_entries where occurred_at <= now();
  select coalesce(sum(greatest(0, p.original_amount -
    coalesce((select sum(a.allocated_amount) from public.ledger_payable_allocations a
              where a.payable_id = p.id), 0))), 0)
  into v_payable from public.ledger_payables p where p.status <> 'cancelled';
  select coalesce(sum(a.assigned_amount - a.paid_amount), 0)
  into v_owner_unpaid from public.ledger_owner_settlement_allocations a
  join public.ledger_owner_settlements s on s.id = a.settlement_id
  where s.status in ('confirmed', 'partially_paid');
  v_safe := greatest(0, v_liquid - v_reserve - v_payable - v_owner_unpaid);
  return jsonb_build_object(
    'status', 'ok', 'throughMonth', p_through_month,
    'openingUndistributedProfit', v_opening, 'closedOperatingProfit', v_profit,
    'confirmedSettlementPool', v_settled, 'undistributedProfit', v_undistributed,
    'liquidFunds', v_liquid, 'activeReserve', v_reserve,
    'vendorPayables', v_payable, 'confirmedUnpaidOwnerSettlements', v_owner_unpaid,
    'safeCashCapacity', v_safe,
    'recommendedMax', greatest(0, least(v_undistributed, v_safe)));
end$$;

alter function public.ledger_owner_financial_capacity_v1(date) owner to postgres;
revoke all on function public.ledger_owner_financial_capacity_v1(date) from public,anon,authenticated;
grant execute on function public.ledger_owner_financial_capacity_v1(date) to service_role,postgres;
