alter table public.ledger_transactions drop constraint ledger_transactions_type_check;
alter table public.ledger_transactions add constraint ledger_transactions_type_check check(type in('expense','income','sales','transfer','opening','balance_adjustment','investment','owner_settlement','card_settlement','card_settlement_deposit','payable_payment','expense_recognition','payroll_payment'));

insert into public.ledger_categories(name,kind,cost_behavior)
values('카드 정산 차액','expense','none') on conflict(kind,name) do nothing;

create table public.ledger_card_reconciliations(
 id bigint generated by default as identity primary key,
 deposit_transaction_id bigint not null unique references public.ledger_transactions(id) on delete restrict,
 deposit_date date not null,
 destination_fund_account_id bigint not null references public.ledger_fund_accounts(id) on delete restrict,
 deposit_amount numeric(16,3) not null check(deposit_amount>0),
 matched_gross_amount numeric(16,3) not null default 0 check(matched_gross_amount>=0),
 difference_amount numeric(16,3) not null default 0 check(difference_amount>=0),
 status text not null default 'unmatched' check(status in('unmatched','partial','matched','cancelled')),
 confirmed_at timestamptz null,
 confirmed_by bigint null references public.users(id) on delete restrict,
 memo text null,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 constraint ledger_card_reconciliation_confirmation check((status='matched' and confirmed_at is not null and confirmed_by is not null and matched_gross_amount>=deposit_amount and difference_amount=matched_gross_amount-deposit_amount)or(status<>'matched' and confirmed_at is null and confirmed_by is null and difference_amount=0))
);
create table public.ledger_card_reconciliation_lines(
 id bigint generated by default as identity primary key,
 reconciliation_id bigint not null references public.ledger_card_reconciliations(id) on delete restrict,
 pos_card_transaction_id bigint not null references public.ledger_transactions(id) on delete restrict,
 allocated_gross_amount numeric(16,3) not null check(allocated_gross_amount>0),
 created_at timestamptz not null default now(),
 constraint ledger_card_reconciliation_line_unique unique(reconciliation_id,pos_card_transaction_id)
);
create index ledger_card_reconciliations_deposit_date_idx on public.ledger_card_reconciliations(deposit_date desc,status);
create index ledger_card_reconciliations_destination_idx on public.ledger_card_reconciliations(destination_fund_account_id);
create index ledger_card_reconciliations_confirmed_by_idx on public.ledger_card_reconciliations(confirmed_by);
create index ledger_card_reconciliation_lines_reconciliation_idx on public.ledger_card_reconciliation_lines(reconciliation_id);
create index ledger_card_reconciliation_lines_pos_transaction_idx on public.ledger_card_reconciliation_lines(pos_card_transaction_id);
alter table public.ledger_card_reconciliations enable row level security;
alter table public.ledger_card_reconciliation_lines enable row level security;
revoke all on table public.ledger_card_reconciliations,public.ledger_card_reconciliation_lines from public,anon,authenticated,service_role;
revoke all on sequence public.ledger_card_reconciliations_id_seq,public.ledger_card_reconciliation_lines_id_seq from public,anon,authenticated,service_role;
grant select on table public.ledger_card_reconciliations,public.ledger_card_reconciliation_lines to service_role;

create or replace function public.ledger_create_card_deposit_v1(p_deposit_at timestamptz,p_amount numeric,p_destination_account_id bigint,p_reference text,p_memo text,p_actor_user_id bigint)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_role text;v_clearing bigint;v_balance numeric;v_transaction bigint;v_reconciliation bigint;v_operation uuid:=gen_random_uuid();v_date date;v_tx public.ledger_transactions%rowtype;
begin
 select lower(role::text) into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;
 if coalesce(v_role,'') not in('owner','master') then return jsonb_build_object('status','forbidden');end if;
 if p_deposit_at is null or p_amount is null or p_amount<=0 or scale(p_amount)>3 then return jsonb_build_object('status','invalid_amount');end if;
 select id into v_clearing from public.ledger_fund_accounts where code='card_clearing' and is_active=true for update;
 if v_clearing is null then return jsonb_build_object('status','card_clearing_missing');end if;
 if p_destination_account_id=v_clearing or not exists(select 1 from public.ledger_fund_accounts where id=p_destination_account_id and is_active=true) then return jsonb_build_object('status','invalid_destination');end if;
 perform pg_advisory_xact_lock(hashtext('ledger_card_clearing_balance'));
 select coalesce(sum(m.amount),0) into v_balance from public.ledger_movements m join public.ledger_transactions t on t.id=m.transaction_id where m.fund_account_id=v_clearing and t.status='confirmed';
 if v_balance<p_amount then return jsonb_build_object('status','insufficient_card_pending','pendingBalance',v_balance);end if;
 v_date:=((p_deposit_at at time zone 'Asia/Ho_Chi_Minh')-interval '3 hours')::date;
 insert into public.ledger_transactions(operation_id,type,occurred_at,business_date,amount,status,source_type,source_snapshot,source_fingerprint,source_synced_at,memo,created_by,confirmed_by)
 values(v_operation,'card_settlement_deposit',p_deposit_at,v_date,p_amount,'confirmed','card_settlement_deposit',jsonb_build_object('reference',nullif(btrim(p_reference),''),'depositAmount',p_amount,'destinationFundAccountId',p_destination_account_id),md5(v_operation::text||':'||p_amount::text),now(),nullif(btrim(p_memo),''),p_actor_user_id,p_actor_user_id)returning * into v_tx;
 v_transaction:=v_tx.id;
 insert into public.ledger_movements(transaction_id,fund_account_id,amount)values(v_transaction,v_clearing,-p_amount),(v_transaction,p_destination_account_id,p_amount);
 insert into public.ledger_card_reconciliations(deposit_transaction_id,deposit_date,destination_fund_account_id,deposit_amount,memo)values(v_transaction,v_date,p_destination_account_id,p_amount,nullif(btrim(p_memo),''))returning id into v_reconciliation;
 insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,after_snapshot,reason)values(p_actor_user_id,'card_deposit_created','card_reconciliation',v_reconciliation,jsonb_build_object('depositTransactionId',v_transaction,'bankAccountId',p_destination_account_id,'depositAmount',p_amount,'beforePendingBalance',v_balance,'afterPendingBalance',v_balance-p_amount,'status','unmatched'),coalesce(nullif(btrim(p_reference),''),nullif(btrim(p_memo),'')));
 return jsonb_build_object('status','created','reconciliationId',v_reconciliation,'transactionId',v_transaction);
exception when check_violation or foreign_key_violation or not_null_violation then return jsonb_build_object('status','invalid_input');end$$;

create or replace function public.ledger_match_card_reconciliation_v1(p_reconciliation_id bigint,p_allocations jsonb,p_confirm boolean,p_actor_user_id bigint)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_role text;v_rec public.ledger_card_reconciliations%rowtype;v_item jsonb;v_id bigint;v_amount numeric;v_gross numeric:=0;v_other numeric;v_sale public.ledger_transactions%rowtype;v_clearing bigint;v_balance numeric;v_diff numeric;v_category bigint;v_diff_tx bigint;v_before jsonb;v_ids bigint[]:=array[]::bigint[];
begin
 select lower(role::text) into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;if coalesce(v_role,'') not in('owner','master') then return jsonb_build_object('status','forbidden');end if;
 if jsonb_typeof(p_allocations)<>'array' or jsonb_array_length(p_allocations)=0 then return jsonb_build_object('status','invalid_allocations');end if;
 select * into v_rec from public.ledger_card_reconciliations where id=p_reconciliation_id for update;if v_rec.id is null then return jsonb_build_object('status','not_found');end if;if v_rec.status in('matched','cancelled') then return jsonb_build_object('status','immutable');end if;
 v_before:=to_jsonb(v_rec);select array_agg(distinct (x->>'transactionId')::bigint order by (x->>'transactionId')::bigint) into v_ids from jsonb_array_elements(p_allocations)x;
 if cardinality(v_ids)<>jsonb_array_length(p_allocations) then return jsonb_build_object('status','duplicate_card_sale');end if;
 perform 1 from public.ledger_transactions where id=any(v_ids) order by id for update;
 for v_item in select value from jsonb_array_elements(p_allocations)loop
  begin v_id:=(v_item->>'transactionId')::bigint;v_amount:=(v_item->>'allocatedGrossAmount')::numeric;exception when others then return jsonb_build_object('status','invalid_allocations');end;
  if v_amount<=0 or scale(v_amount)>3 then return jsonb_build_object('status','invalid_allocations');end if;
  select * into v_sale from public.ledger_transactions where id=v_id and status='confirmed' and source_type='pos_sales_daily_payment' and source_key like 'pos:%:card';if v_sale.id is null then return jsonb_build_object('status','invalid_card_sale');end if;
  select coalesce(sum(l.allocated_gross_amount),0) into v_other from public.ledger_card_reconciliation_lines l join public.ledger_card_reconciliations r on r.id=l.reconciliation_id where l.pos_card_transaction_id=v_id and r.status<>'cancelled' and r.id<>v_rec.id;
  if v_other+v_amount>v_sale.amount then return jsonb_build_object('status','gross_overallocated','transactionId',v_id);end if;v_gross:=v_gross+v_amount;
 end loop;
 if p_confirm and v_gross<v_rec.deposit_amount then return jsonb_build_object('status','gross_below_deposit','matchedGrossAmount',v_gross);end if;
 if p_confirm then
  v_diff:=v_gross-v_rec.deposit_amount;select id into v_clearing from public.ledger_fund_accounts where code='card_clearing' and is_active=true for update;perform pg_advisory_xact_lock(hashtext('ledger_card_clearing_balance'));
  select coalesce(sum(m.amount),0) into v_balance from public.ledger_movements m join public.ledger_transactions t on t.id=m.transaction_id where m.fund_account_id=v_clearing and t.status='confirmed';if v_balance<v_diff then return jsonb_build_object('status','insufficient_card_pending','pendingBalance',v_balance);end if;
  if v_diff>0 then select id into v_category from public.ledger_categories where kind='expense' and name='카드 정산 차액' and is_active=true;if v_category is null then return jsonb_build_object('status','category_missing');end if;end if;
 end if;
 delete from public.ledger_card_reconciliation_lines where reconciliation_id=v_rec.id;
 insert into public.ledger_card_reconciliation_lines(reconciliation_id,pos_card_transaction_id,allocated_gross_amount)select v_rec.id,(x->>'transactionId')::bigint,(x->>'allocatedGrossAmount')::numeric from jsonb_array_elements(p_allocations)x;
 if not p_confirm then
  update public.ledger_card_reconciliations set matched_gross_amount=v_gross,status=case when v_gross=0 then'unmatched' else'partial'end,updated_at=now() where id=v_rec.id;
  insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,before_snapshot,after_snapshot,reason)values(p_actor_user_id,'card_reconciliation_partial','card_reconciliation',v_rec.id,v_before,jsonb_build_object('depositTransactionId',v_rec.deposit_transaction_id,'bankAccountId',v_rec.destination_fund_account_id,'depositAmount',v_rec.deposit_amount,'allocations',p_allocations,'matchedGrossAmount',v_gross,'differenceAmount',0,'status','partial'),'Card settlement partial match');
  return jsonb_build_object('status','partial','matchedGrossAmount',v_gross);
 end if;
 if v_diff>0 then
  insert into public.ledger_transactions(operation_id,type,occurred_at,business_date,recognition_month,amount,category_id,status,source_type,source_key,source_snapshot,source_fingerprint,source_synced_at,memo,created_by,confirmed_by)
  select d.operation_id,'expense_recognition',d.occurred_at,v_rec.deposit_date,date_trunc('month',v_rec.deposit_date)::date,v_diff,v_category,'confirmed','card_settlement_difference','card-reconciliation:'||v_rec.id||':difference',jsonb_build_object('reconciliationId',v_rec.id,'depositAmount',v_rec.deposit_amount,'matchedGrossAmount',v_gross,'differenceAmount',v_diff,'sales',(select jsonb_agg(jsonb_build_object('transactionId',l.pos_card_transaction_id,'businessDate',t.business_date,'allocatedGrossAmount',l.allocated_gross_amount))from public.ledger_card_reconciliation_lines l join public.ledger_transactions t on t.id=l.pos_card_transaction_id where l.reconciliation_id=v_rec.id)),md5(v_rec.id::text||':'||v_gross::text||':'||v_rec.deposit_amount::text),now(),'카드 정산 차액',p_actor_user_id,p_actor_user_id from public.ledger_transactions d where d.id=v_rec.deposit_transaction_id returning id into v_diff_tx;
  insert into public.ledger_movements(transaction_id,fund_account_id,amount)values(v_diff_tx,v_clearing,-v_diff);
 end if;
 update public.ledger_card_reconciliations set matched_gross_amount=v_gross,difference_amount=v_diff,status='matched',confirmed_at=now(),confirmed_by=p_actor_user_id,updated_at=now() where id=v_rec.id;
 insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,before_snapshot,after_snapshot,reason)values(p_actor_user_id,'card_reconciliation_matched','card_reconciliation',v_rec.id,v_before,jsonb_build_object('depositTransactionId',v_rec.deposit_transaction_id,'bankAccountId',v_rec.destination_fund_account_id,'depositAmount',v_rec.deposit_amount,'allocations',p_allocations,'matchedGrossAmount',v_gross,'differenceAmount',v_diff,'beforePendingBalance',v_balance,'afterPendingBalance',v_balance-v_diff,'status','matched'),'Card settlement confirmed');
 return jsonb_build_object('status','matched','matchedGrossAmount',v_gross,'differenceAmount',v_diff,'differenceTransactionId',v_diff_tx);
end$$;

revoke all on function public.ledger_create_card_deposit_v1(timestamptz,numeric,bigint,text,text,bigint) from public,anon,authenticated;
revoke all on function public.ledger_match_card_reconciliation_v1(bigint,jsonb,boolean,bigint) from public,anon,authenticated;
grant execute on function public.ledger_create_card_deposit_v1(timestamptz,numeric,bigint,text,text,bigint) to service_role;
grant execute on function public.ledger_match_card_reconciliation_v1(bigint,jsonb,boolean,bigint) to service_role;
comment on table public.ledger_card_reconciliation_lines is 'N:M gross allocations between actual card deposits and POS card sales; remaining gross is derived from active allocation sums.';
