begin;

-- Older successful runs have unknown completeness and cannot authorize final close.
alter table public.pos_sales_sync_runs add column source_complete boolean null;
create index pos_sales_sync_runs_complete_final_idx
  on public.pos_sales_sync_runs(business_date, finished_at desc)
  where status = 'success' and source_complete is true;

create table public.pos_sales_business_day_close_checks (
  id bigint generated by default as identity primary key,
  business_date date not null,
  closure_id bigint null references public.pos_sales_business_day_closures(id) on delete restrict,
  checked_at timestamptz not null default now(),
  check_type text not null check (check_type in ('scheduled_final', 'manual_refresh')),
  result text not null check (result in ('verified_unchanged', 'metadata_changed_only', 'financial_drift', 'sync_failed', 'source_invalid', 'month_closed')),
  sync_run_id bigint null references public.pos_sales_sync_runs(id) on delete restrict,
  closed_fingerprint text null check (closed_fingerprint ~ '^[0-9a-f]{64}$'),
  current_fingerprint text null check (current_fingerprint ~ '^[0-9a-f]{64}$'),
  closed_total numeric(16,0) null check (closed_total >= 0),
  current_total numeric(16,0) null check (current_total >= 0),
  total_delta numeric(16,0) null,
  closed_buckets jsonb null check (jsonb_typeof(closed_buckets) = 'object'),
  current_buckets jsonb null check (jsonb_typeof(current_buckets) = 'object'),
  bucket_delta jsonb null check (jsonb_typeof(bucket_delta) = 'object'),
  detail_snapshot jsonb not null default '{}'::jsonb check (jsonb_typeof(detail_snapshot) = 'object'),
  idempotency_key text not null unique check (idempotency_key ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  constraint pos_sales_close_check_result_evidence check (
    result in ('sync_failed','source_invalid','month_closed') or (
      closure_id is not null and sync_run_id is not null and closed_fingerprint is not null
      and current_fingerprint is not null and closed_total is not null and current_total is not null
      and total_delta = current_total - closed_total and total_delta is not null
      and closed_buckets is not null and current_buckets is not null and bucket_delta is not null
    )
  )
);
create index pos_sales_close_checks_latest_idx
  on public.pos_sales_business_day_close_checks(business_date, checked_at desc, id desc);
create index pos_sales_close_checks_closure_idx on public.pos_sales_business_day_close_checks(closure_id);
create index pos_sales_close_checks_run_idx on public.pos_sales_business_day_close_checks(sync_run_id);
alter table public.pos_sales_business_day_close_checks enable row level security;
revoke all on table public.pos_sales_business_day_close_checks from public, anon, authenticated, service_role;
revoke all on sequence public.pos_sales_business_day_close_checks_id_seq from public, anon, authenticated, service_role;
grant select on table public.pos_sales_business_day_close_checks to service_role;
create trigger pos_sales_close_check_immutable before update or delete on public.pos_sales_business_day_close_checks
for each row execute function pos_sales_close_private.immutable_closure();
create trigger pos_sales_close_check_no_truncate before truncate on public.pos_sales_business_day_close_checks
for each statement execute function pos_sales_close_private.immutable_closure();

-- Lease protects network refresh orchestration, not Ledger projection permissions.
create table pos_sales_close_private.final_check_leases (
  business_date date primary key, token uuid not null, actor_user_id bigint not null references public.users(id),
  expires_at timestamptz not null
);
revoke all on table pos_sales_close_private.final_check_leases from public, anon, authenticated, service_role;

create function pos_sales_close_private.require_final_actor(p_actor bigint)
returns void language plpgsql security invoker set search_path = pg_catalog, public as $$
begin
  if not exists(select 1 from public.users where id=p_actor and username='pos'
    and is_active=true and app_login_enabled=true and lower(btrim(role::text)) in ('owner','master')) then
    raise exception 'POS_CLOSE_FORBIDDEN' using errcode='42501';
  end if;
end $$;

create function public.sales_claim_business_day_final_check_v1(p_business_date date,p_actor_user_id bigint)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_token uuid := gen_random_uuid();
begin
  perform pos_sales_close_private.require_final_actor(p_actor_user_id);
  if p_business_date is null then raise exception 'INVALID_POS_BUSINESS_DATE' using errcode='22023'; end if;
  perform pg_advisory_xact_lock(hashtext('pos_sales_business_day_final_check:'||p_business_date::text));
  if exists(select 1 from pos_sales_close_private.final_check_leases where business_date=p_business_date and expires_at>clock_timestamp()) then
    return jsonb_build_object('status','in_progress');
  end if;
  insert into pos_sales_close_private.final_check_leases values(p_business_date,v_token,p_actor_user_id,clock_timestamp()+interval '10 minutes')
  on conflict(business_date) do update set token=excluded.token,actor_user_id=excluded.actor_user_id,expires_at=excluded.expires_at;
  return jsonb_build_object('status','claimed','token',v_token);
end $$;

create function public.sales_release_business_day_final_check_v1(p_business_date date,p_token uuid,p_actor_user_id bigint)
returns void language plpgsql security definer set search_path = pg_catalog, public as $$
begin
  perform pos_sales_close_private.require_final_actor(p_actor_user_id);
  delete from pos_sales_close_private.final_check_leases where business_date=p_business_date and token=p_token and actor_user_id=p_actor_user_id;
end $$;

create function public.sales_close_business_day_after_sync_v1(
  p_business_date date,p_source_fingerprint text,p_source_snapshot jsonb,p_rows jsonb,
  p_actor_user_id bigint,p_close_method text default 'manual',p_manual_reclose boolean default false,p_sync_run_id bigint default null
) returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
begin
  if p_close_method is distinct from 'manual' then raise exception 'INVALID_POS_SALES_CLOSE_REQUEST' using errcode='22023'; end if;
  if not exists(select 1 from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true
    and lower(btrim(role::text)) in ('owner','master','manager')) then return jsonb_build_object('status','forbidden'); end if;
  perform pg_advisory_xact_lock(hashtext('ledger_month_close:'||to_char(p_business_date,'YYYY-MM')));
  perform pg_advisory_xact_lock(hashtext('pos_sales_business_day_close:'||p_business_date::text));
  lock table public.pos_sales_receipts,public.pos_sales_receipt_payments in share mode;
  if exists(select 1 from public.pos_sales_sync_runs where business_date=p_business_date and source='cukcuk' and status='running') then
    raise exception 'POS_CLOSE_SOURCE_INVALID' using errcode='40001';
  end if;
  if not exists(select 1 from public.pos_sales_sync_runs where id=p_sync_run_id and business_date=p_business_date
    and source='cukcuk' and status='success' and source_complete is true and error_message is null
    and finished_at<=clock_timestamp() and finished_at>=clock_timestamp()-interval '30 minutes') then
    raise exception 'POS_CLOSE_SOURCE_INVALID' using errcode='22023';
  end if;
  return public.sales_close_business_day_v1(p_business_date,p_source_fingerprint,p_source_snapshot,p_rows,
    p_actor_user_id,'manual',p_manual_reclose,p_sync_run_id);
end $$;

create function public.sales_finalize_business_day_v1(
  p_business_date date,p_actor_user_id bigint,p_token uuid,p_cutoff_at timestamptz,
  p_sync_run_id bigint default null,p_source_fingerprint text default null,
  p_source_snapshot jsonb default null,p_rows jsonb default null,
  p_failure text default null,p_detail jsonb default '{}'::jsonb
) returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  v_closure public.pos_sales_business_day_closures%rowtype; v_close_result jsonb;
  v_result text; v_closed_buckets jsonb; v_current_buckets jsonb; v_delta jsonb := '{}'::jsonb;
  v_closed_total numeric; v_current_total numeric; v_bucket text; v_key text; v_id bigint;
begin
  perform pos_sales_close_private.require_final_actor(p_actor_user_id);
  if p_business_date is null or p_cutoff_at is null or p_cutoff_at>clock_timestamp()
    or (p_cutoff_at at time zone 'Asia/Ho_Chi_Minh')::date<>p_business_date+1
    or jsonb_typeof(p_detail) is distinct from 'object'
    or (p_failure is not null and p_failure not in ('sync_failed','source_invalid')) then
    raise exception 'INVALID_POS_FINAL_CHECK_REQUEST' using errcode='22023';
  end if;
  -- Same month/day locks as phase 1. Final-check lease is independent of these locks.
  perform pg_advisory_xact_lock(hashtext('ledger_month_close:'||to_char(p_business_date,'YYYY-MM')));
  perform pg_advisory_xact_lock(hashtext('pos_sales_business_day_close:'||p_business_date::text));
  perform 1 from pos_sales_close_private.final_check_leases
    where business_date=p_business_date and token=p_token and actor_user_id=p_actor_user_id and expires_at>clock_timestamp() for update;
  if not found then raise exception 'POS_FINAL_CHECK_LEASE_EXPIRED' using errcode='55000'; end if;
  select * into v_closure from public.pos_sales_business_day_closures
    where business_date=p_business_date order by revision desc limit 1 for update;

  if p_failure is not null then
    v_result := p_failure;
  else
    if not exists(select 1 from public.pos_sales_sync_runs where id=p_sync_run_id
      and business_date=p_business_date and source='cukcuk' and status='success'
      and source_complete is true and error_message is null
      and started_at>=p_cutoff_at and started_at<p_cutoff_at+interval '1 day'
      and finished_at>=started_at and finished_at<=clock_timestamp()
      and finished_at>=clock_timestamp()-interval '30 minutes') then
      raise exception 'POS_FINAL_SYNC_REQUIRED' using errcode='22023';
    end if;
    lock table public.pos_sales_receipts,public.pos_sales_receipt_payments in share mode;
    if exists(select 1 from public.pos_sales_sync_runs where business_date=p_business_date and source='cukcuk' and status='running') then
      raise exception 'POS_FINAL_SOURCE_SYNC_RUNNING' using errcode='40001';
    end if;
    perform pos_sales_close_private.validate_source(p_business_date,p_source_fingerprint,p_source_snapshot,p_rows);
    if v_closure.id is null then
      v_close_result := public.sales_close_business_day_v1(p_business_date,p_source_fingerprint,p_source_snapshot,p_rows,
        p_actor_user_id,'automatic',false,p_sync_run_id);
      if v_close_result->>'status' not in ('closed','already_closed') then
        v_result := case when v_close_result->>'status'='month_closed' then 'month_closed' else 'source_invalid' end;
      else
        select * into v_closure from public.pos_sales_business_day_closures where id=(v_close_result->>'closureId')::bigint;
      end if;
    end if;
    -- Existing manual OR automatic closure: compare only. Never call generic sync/reclose.
    if v_result is null then
    v_closed_total := (v_closure.source_snapshot->>'receiptTotal')::numeric;
    v_current_total := (p_source_snapshot->>'receiptTotal')::numeric;
    v_closed_buckets := v_closure.source_snapshot->'totalsByBucket';
    v_current_buckets := p_source_snapshot->'totalsByBucket';
    if v_closed_total is null or v_current_total is null or jsonb_typeof(v_closed_buckets) is distinct from 'object' then
      raise exception 'POS_SOURCE_SNAPSHOT_INCOMPLETE' using errcode='22023';
    end if;
    foreach v_bucket in array array['cash','transfer','card','other'] loop
      if v_closed_buckets->>v_bucket is null or v_current_buckets->>v_bucket is null then
        raise exception 'POS_SOURCE_SNAPSHOT_INCOMPLETE' using errcode='22023';
      end if;
      v_delta := v_delta||jsonb_build_object(v_bucket,(v_current_buckets->>v_bucket)::numeric-(v_closed_buckets->>v_bucket)::numeric);
    end loop;
    if v_closed_total<>v_current_total or exists(select 1 from jsonb_each_text(v_delta) where value::numeric<>0) then
      v_result := 'financial_drift';
    elsif v_closure.source_fingerprint=p_source_fingerprint then v_result := 'verified_unchanged';
    else v_result := 'metadata_changed_only'; end if;
    end if;
  end if;

  v_key := encode(sha256(convert_to(jsonb_build_array(p_business_date,'scheduled_final',v_closure.id,p_sync_run_id,
    p_source_fingerprint,v_result)::text,'UTF8')),'hex');
  insert into public.pos_sales_business_day_close_checks(business_date,closure_id,check_type,result,sync_run_id,
    closed_fingerprint,current_fingerprint,closed_total,current_total,total_delta,
    closed_buckets,current_buckets,bucket_delta,detail_snapshot,idempotency_key)
  values(p_business_date,v_closure.id,'scheduled_final',v_result,p_sync_run_id,v_closure.source_fingerprint,
    p_source_fingerprint,v_closed_total,v_current_total,v_current_total-v_closed_total,
    v_closed_buckets,v_current_buckets,v_delta,jsonb_build_object(
      'businessDate',p_business_date,'cutoffAt',p_cutoff_at,'syncRunId',p_sync_run_id,
      'failureCode',case when v_close_result is not null and v_result in ('source_invalid','month_closed')
        then v_close_result->>'status' else coalesce(p_detail->>'failureCode',p_failure) end,
      'reason',coalesce(p_detail->>'reason',case when v_result in ('sync_failed','source_invalid','month_closed') then v_result end),
      'finalSync',coalesce(p_detail->'finalSync',jsonb_build_object('eligible',p_failure is null,'runId',p_sync_run_id)),
      'retryExecuted',coalesce(p_detail->'retryExecuted','false'::jsonb),
      'retryFailureReason',p_detail->>'retryFailureReason','closeResult',v_close_result),v_key)
  on conflict(idempotency_key) do nothing returning id into v_id;
  if v_id is null then select id into v_id from public.pos_sales_business_day_close_checks where idempotency_key=v_key; end if;
  return jsonb_build_object('status',v_result,'checkId',v_id,'closureId',v_closure.id,'revision',v_closure.revision,
    'closeResult',v_close_result);
end $$;

alter table public.pos_sales_business_day_close_checks owner to postgres;
alter table pos_sales_close_private.final_check_leases owner to postgres;
alter function pos_sales_close_private.require_final_actor(bigint) owner to postgres;
alter function public.sales_claim_business_day_final_check_v1(date,bigint) owner to postgres;
alter function public.sales_release_business_day_final_check_v1(date,uuid,bigint) owner to postgres;
alter function public.sales_close_business_day_after_sync_v1(date,text,jsonb,jsonb,bigint,text,boolean,bigint) owner to postgres;
alter function public.sales_finalize_business_day_v1(date,bigint,uuid,timestamptz,bigint,text,jsonb,jsonb,text,jsonb) owner to postgres;
revoke all on function pos_sales_close_private.require_final_actor(bigint) from public,anon,authenticated,service_role;
revoke all on function public.sales_close_business_day_after_sync_v1(date,text,jsonb,jsonb,bigint,text,boolean,bigint),
  public.sales_claim_business_day_final_check_v1(date,bigint),
  public.sales_release_business_day_final_check_v1(date,uuid,bigint),
  public.sales_finalize_business_day_v1(date,bigint,uuid,timestamptz,bigint,text,jsonb,jsonb,text,jsonb)
  from public,anon,authenticated,service_role;
grant execute on function public.sales_close_business_day_after_sync_v1(date,text,jsonb,jsonb,bigint,text,boolean,bigint),
  public.sales_claim_business_day_final_check_v1(date,bigint),
  public.sales_release_business_day_final_check_v1(date,uuid,bigint),
  public.sales_finalize_business_day_v1(date,bigint,uuid,timestamptz,bigint,text,jsonb,jsonb,text,jsonb) to service_role;

commit;
