create table public.store_attendance_policies (
  setting_version_id bigint primary key
    references public.store_setting_versions(id) on delete cascade,
  late_grace_minutes integer not null default 0,
  default_normal_checkout_time time without time zone not null default '00:00',
  created_at timestamptz not null default now(),
  constraint store_attendance_policies_late_grace_check
    check (late_grace_minutes between 0 and 180)
);

insert into public.store_attendance_policies (
  setting_version_id,
  late_grace_minutes,
  default_normal_checkout_time
)
select id, 0, '00:00'
from public.store_setting_versions
on conflict (setting_version_id) do nothing;

create table public.store_business_day_overrides (
  id bigint generated by default as identity primary key,
  business_date date not null,
  actual_close_time time without time zone not null,
  reason text null,
  state text not null default 'active',
  created_by bigint not null references public.users(id),
  created_at timestamptz not null default now(),
  updated_by bigint null references public.users(id),
  updated_at timestamptz null,
  cancelled_by bigint null references public.users(id),
  cancelled_at timestamptz null,
  constraint store_business_day_overrides_state_check
    check (state in ('active', 'cancelled')),
  constraint store_business_day_overrides_cancel_state_check check (
    (state = 'active' and cancelled_by is null and cancelled_at is null)
    or (state = 'cancelled' and cancelled_by is not null and cancelled_at is not null)
  )
);

create unique index store_business_day_overrides_active_date_unique
  on public.store_business_day_overrides (business_date)
  where state = 'active';

create index store_business_day_overrides_date_idx
  on public.store_business_day_overrides (business_date desc, id desc);

create table public.attendance_record_audit_logs (
  id bigint generated by default as identity primary key,
  attendance_record_id bigint not null
    references public.attendance_records(id) on delete restrict,
  action text not null,
  actor_user_id bigint null references public.users(id),
  before_snapshot jsonb null,
  after_snapshot jsonb null,
  reason text null,
  created_at timestamptz not null default now(),
  constraint attendance_record_audit_logs_action_check check (
    action in (
      'manual_update',
      'normalize_late',
      'normalize_early_leave',
      'auto_close',
      'policy_recalculation'
    )
  )
);

create index attendance_record_audit_logs_record_created_idx
  on public.attendance_record_audit_logs (
    attendance_record_id,
    created_at desc,
    id desc
  );

alter table public.store_attendance_policies enable row level security;
alter table public.store_business_day_overrides enable row level security;
alter table public.attendance_record_audit_logs enable row level security;

revoke all on table public.store_attendance_policies
  from public, anon, authenticated;
revoke all on table public.store_business_day_overrides
  from public, anon, authenticated;
revoke all on table public.attendance_record_audit_logs
  from public, anon, authenticated;

grant select, insert, update on table public.store_attendance_policies
  to service_role;
grant select, insert, update on table public.store_business_day_overrides
  to service_role;
grant select, insert on table public.attendance_record_audit_logs
  to service_role;

grant usage, select on sequence public.store_business_day_overrides_id_seq
  to service_role;
grant usage, select on sequence public.attendance_record_audit_logs_id_seq
  to service_role;

create or replace function public.store_setting_snapshot_v1(p_version_id bigint)
returns jsonb
language sql
stable
security invoker
set search_path = pg_catalog, public
as $$
  select jsonb_build_object(
    'id', v.id,
    'timezone', v.timezone,
    'businessDayCutoffTime', to_char(v.business_day_cutoff_time, 'HH24:MI'),
    'effectiveFromBusinessDate', to_char(v.effective_from_business_date, 'YYYY-MM-DD'),
    'revision', v.revision,
    'state', v.state,
    'createdBy', v.created_by,
    'createdAt', v.created_at,
    'cancelledBy', v.cancelled_by,
    'cancelledAt', v.cancelled_at,
    'attendancePolicy', jsonb_build_object(
      'lateGraceMinutes', coalesce(p.late_grace_minutes, 0),
      'defaultNormalCheckoutTime',
        coalesce(to_char(p.default_normal_checkout_time, 'HH24:MI'), '00:00')
    ),
    'hours', coalesce((
      select jsonb_agg(jsonb_build_object(
        'weekday', h.weekday,
        'isClosed', h.is_closed,
        'openTime', case when h.open_time is null then null else to_char(h.open_time, 'HH24:MI') end,
        'closeTime', case when h.close_time is null then null else to_char(h.close_time, 'HH24:MI') end
      ) order by h.weekday)
      from public.store_business_hours h
      where h.setting_version_id = v.id
    ), '[]'::jsonb)
  )
  from public.store_setting_versions v
  left join public.store_attendance_policies p
    on p.setting_version_id = v.id
  where v.id = p_version_id
$$;

drop function if exists public.store_schedule_settings_v1(
  date,
  bigint,
  text,
  time without time zone,
  jsonb,
  bigint
);

create function public.store_schedule_settings_v1(
  p_effective_from_business_date date,
  p_expected_revision bigint,
  p_timezone text,
  p_business_day_cutoff_time time without time zone,
  p_hours jsonb,
  p_actor_user_id bigint,
  p_late_grace_minutes integer,
  p_default_normal_checkout_time time without time zone
) returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_current_business_date date := public.store_business_date_for_timestamp_v1(now());
  v_latest_revision bigint;
  v_version_id bigint;
  v_item jsonb;
  v_weekday integer;
  v_is_closed boolean;
  v_open time;
  v_close time;
begin
  perform pg_advisory_xact_lock(hashtext('store_settings_schedule_v1'));

  select role::text into v_role
  from public.users
  where id = p_actor_user_id and is_active = true;

  if lower(coalesce(v_role, '')) not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;

  select coalesce(max(revision), 0) into v_latest_revision
  from public.store_setting_versions;

  if p_expected_revision is distinct from v_latest_revision then
    return jsonb_build_object(
      'status', 'version_conflict',
      'latestRevision', v_latest_revision
    );
  end if;
  if p_effective_from_business_date <= v_current_business_date then
    return jsonb_build_object('status', 'invalid_effective_date');
  end if;
  if p_timezone <> 'Asia/Ho_Chi_Minh' then
    return jsonb_build_object('status', 'invalid_timezone');
  end if;
  if p_late_grace_minutes not between 0 and 180
    or p_default_normal_checkout_time is null
  then
    return jsonb_build_object('status', 'invalid_attendance_policy');
  end if;
  if p_hours is null
    or jsonb_typeof(p_hours) <> 'array'
    or jsonb_array_length(p_hours) <> 7
  then
    return jsonb_build_object('status', 'invalid_hours');
  end if;
  if exists (
    select 1
    from public.store_setting_versions
    where state = 'active'
      and effective_from_business_date > v_current_business_date
  ) then
    return jsonb_build_object('status', 'scheduled_exists');
  end if;

  insert into public.store_setting_versions (
    timezone,
    business_day_cutoff_time,
    effective_from_business_date,
    revision,
    created_by
  )
  values (
    p_timezone,
    p_business_day_cutoff_time,
    p_effective_from_business_date,
    v_latest_revision + 1,
    p_actor_user_id
  )
  returning id into v_version_id;

  insert into public.store_attendance_policies (
    setting_version_id,
    late_grace_minutes,
    default_normal_checkout_time
  )
  values (
    v_version_id,
    p_late_grace_minutes,
    p_default_normal_checkout_time
  );

  for v_item in select value from jsonb_array_elements(p_hours) loop
    if jsonb_typeof(v_item) <> 'object'
      or not (v_item ?& array['weekday','isClosed','openTime','closeTime'])
      or (select count(*) from jsonb_object_keys(v_item)) <> 4
      or jsonb_typeof(v_item->'weekday') <> 'number'
      or jsonb_typeof(v_item->'isClosed') <> 'boolean'
    then
      raise check_violation using message = 'invalid hours object';
    end if;

    v_weekday := (v_item->>'weekday')::integer;
    v_is_closed := (v_item->>'isClosed')::boolean;
    v_open := nullif(v_item->>'openTime', '')::time;
    v_close := nullif(v_item->>'closeTime', '')::time;

    insert into public.store_business_hours (
      setting_version_id,
      weekday,
      is_closed,
      open_time,
      close_time
    )
    values (v_version_id, v_weekday, v_is_closed, v_open, v_close);
  end loop;

  if (
    select count(*)
    from public.store_business_hours
    where setting_version_id = v_version_id
  ) <> 7 then
    raise check_violation using message = 'seven weekdays required';
  end if;

  insert into public.store_setting_audit_logs (
    setting_version_id,
    action,
    actor_user_id,
    after_snapshot
  )
  values (
    v_version_id,
    'created',
    p_actor_user_id,
    public.store_setting_snapshot_v1(v_version_id)
  );

  return jsonb_build_object(
    'status', 'ok',
    'setting', public.store_setting_snapshot_v1(v_version_id),
    'latestRevision', v_latest_revision + 1
  );
exception
  when check_violation
    or unique_violation
    or not_null_violation
    or invalid_text_representation
    or invalid_datetime_format
    or datetime_field_overflow
  then
    return jsonb_build_object('status', 'invalid_hours');
end
$$;

revoke all on function public.store_schedule_settings_v1(
  date,
  bigint,
  text,
  time without time zone,
  jsonb,
  bigint,
  integer,
  time without time zone
) from public, anon, authenticated;

grant execute on function public.store_schedule_settings_v1(
  date,
  bigint,
  text,
  time without time zone,
  jsonb,
  bigint,
  integer,
  time without time zone
) to service_role;

comment on table public.store_attendance_policies is
  'Attendance policy attached to the same effective version as store business hours.';
comment on table public.store_business_day_overrides is
  'Auditable business-date-specific actual closing time; active rows affect all staff.';
comment on table public.attendance_record_audit_logs is
  'Reserved audit foundation for future attendance mutations; Shadow reads do not write here.';
