-- Ledger V1 phase 8: immutable month close, source drift and corrections.
-- This migration intentionally contains no operational data backfill.

create table public.ledger_month_closures (
  id bigint generated by default as identity primary key,
  month date not null unique check (month = date_trunc('month', month)::date),
  status text not null default 'closed' check (status = 'closed'),
  closed_at timestamptz not null default now(),
  closed_by bigint not null references public.users(id) on delete restrict,
  preflight_snapshot jsonb not null check (jsonb_typeof(preflight_snapshot) = 'object'),
  summary_snapshot jsonb not null check (jsonb_typeof(summary_snapshot) = 'object'),
  snapshot_hash text not null check (snapshot_hash ~ '^[0-9a-f]{64}$'),
  warning_snapshot jsonb not null default '[]'::jsonb check (jsonb_typeof(warning_snapshot) = 'array'),
  created_at timestamptz not null default now()
);
create index ledger_month_closures_closed_by_idx on public.ledger_month_closures(closed_by);
create index ledger_month_closures_closed_at_idx on public.ledger_month_closures(closed_at desc);
alter table public.ledger_month_closures enable row level security;
revoke all on table public.ledger_month_closures from public, anon, authenticated, service_role;
revoke all on sequence public.ledger_month_closures_id_seq from public, anon, authenticated, service_role;
grant select on table public.ledger_month_closures to service_role;

alter table public.ledger_transactions add column economic_effect_sign smallint not null default 1;
alter table public.ledger_transactions add constraint ledger_transactions_economic_effect_sign_check check (economic_effect_sign in (-1, 1));
alter table public.ledger_transactions drop constraint ledger_transactions_type_check;
alter table public.ledger_transactions add constraint ledger_transactions_type_check check(type in('expense','income','sales','transfer','opening','balance_adjustment','investment','owner_settlement','card_settlement','payable_payment','expense_recognition','payroll_payment','prepaid_expense_payment','card_settlement_deposit','correction'));
alter table public.ledger_transactions drop constraint ledger_transactions_amount_check;
alter table public.ledger_transactions add constraint ledger_transactions_amount_check check(amount>0 or(type='correction'and amount=0));
create index ledger_transactions_correction_of_idx on public.ledger_transactions(correction_of_id) where correction_of_id is not null;

alter table public.ledger_candidates drop constraint ledger_candidates_candidate_type_check;
alter table public.ledger_candidates add constraint ledger_candidates_candidate_type_check check(candidate_type in('inventory_purchase','employee_meal','payroll_employee_payment','source_drift'));
alter table public.ledger_candidates drop constraint ledger_candidates_source_type_check;
alter table public.ledger_candidates add constraint ledger_candidates_source_type_check check(source_type in('inventory_purchase_log','attendance_meal_daily','payroll_employee_payment','ledger_source_drift'));
alter table public.ledger_candidates drop constraint ledger_candidates_proposed_amount_check;
alter table public.ledger_candidates add constraint ledger_candidates_proposed_amount_check check((candidate_type='source_drift' and proposed_amount>=0)or(candidate_type<>'source_drift' and proposed_amount>0));

create or replace function public.ledger_month_is_closed_v1(p_month date) returns boolean
language sql stable security definer set search_path=pg_catalog,public as $$
 select exists(select 1 from public.ledger_month_closures where month=date_trunc('month',p_month)::date and status='closed')
$$;

create or replace function public.ledger_assert_month_open_v1(p_month date) returns void
language plpgsql stable security definer set search_path=pg_catalog,public as $$
begin
 if p_month is not null and public.ledger_month_is_closed_v1(p_month) then
  raise exception using errcode='P0001',message='LEDGER_MONTH_CLOSED';
 end if;
end$$;

create or replace function public.ledger_transaction_month_guard_v1() returns trigger
language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_old_month date;v_old_business date;v_new_month date;v_new_business date;
begin
 if tg_op<>'INSERT' then v_old_month:=old.recognition_month;v_old_business:=date_trunc('month',old.business_date)::date;end if;
 if tg_op<>'DELETE' then v_new_month:=new.recognition_month;v_new_business:=date_trunc('month',new.business_date)::date;end if;
 perform public.ledger_assert_month_open_v1(v_old_month);perform public.ledger_assert_month_open_v1(v_old_business);
 perform public.ledger_assert_month_open_v1(v_new_month);perform public.ledger_assert_month_open_v1(v_new_business);
 return case when tg_op='DELETE' then old else new end;
end$$;
create trigger ledger_transactions_month_guard before insert or update or delete on public.ledger_transactions for each row execute function public.ledger_transaction_month_guard_v1();

create or replace function public.ledger_movement_month_guard_v1() returns trigger
language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_id bigint;v_tx public.ledger_transactions%rowtype;
begin
 v_id:=case when tg_op='DELETE' then old.transaction_id else new.transaction_id end;
 select * into v_tx from public.ledger_transactions where id=v_id;
 perform public.ledger_assert_month_open_v1(v_tx.recognition_month);
 perform public.ledger_assert_month_open_v1(date_trunc('month',v_tx.business_date)::date);
 return case when tg_op='DELETE' then old else new end;
end$$;
create trigger ledger_movements_month_guard before insert or update or delete on public.ledger_movements for each row execute function public.ledger_movement_month_guard_v1();

create or replace function public.ledger_dated_write_month_guard_v1() returns trigger
language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_at timestamptz;
begin
 v_at:=case when tg_op='DELETE' then old.occurred_at else new.occurred_at end;
 perform public.ledger_assert_month_open_v1(date_trunc('month',((v_at at time zone 'Asia/Ho_Chi_Minh')-interval '3 hours')::date)::date);
 return case when tg_op='DELETE' then old else new end;
end$$;
create trigger ledger_reserve_entries_month_guard before insert or update or delete on public.ledger_reserve_entries for each row execute function public.ledger_dated_write_month_guard_v1();

create or replace function public.ledger_payable_allocation_month_guard_v1()returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare v_tx public.ledger_transactions%rowtype;v_id bigint;begin v_id:=case when tg_op='DELETE'then old.payment_transaction_id else new.payment_transaction_id end;select*into v_tx from public.ledger_transactions where id=v_id;perform public.ledger_assert_month_open_v1(date_trunc('month',v_tx.business_date)::date);return case when tg_op='DELETE'then old else new end;end$$;
create trigger ledger_payable_allocations_month_guard before insert or update or delete on public.ledger_payable_allocations for each row execute function public.ledger_payable_allocation_month_guard_v1();

create or replace function public.ledger_card_reconciliation_month_guard_v1()returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare v_date date;begin v_date:=case when tg_op='DELETE'then old.deposit_date else new.deposit_date end;perform public.ledger_assert_month_open_v1(date_trunc('month',v_date)::date);return case when tg_op='DELETE'then old else new end;end$$;
create trigger ledger_card_reconciliations_month_guard before insert or update or delete on public.ledger_card_reconciliations for each row execute function public.ledger_card_reconciliation_month_guard_v1();

create or replace function public.ledger_card_line_month_guard_v1()returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare v_id bigint;v_date date;begin v_id:=case when tg_op='DELETE'then old.reconciliation_id else new.reconciliation_id end;select deposit_date into v_date from public.ledger_card_reconciliations where id=v_id;perform public.ledger_assert_month_open_v1(date_trunc('month',v_date)::date);return case when tg_op='DELETE'then old else new end;end$$;
create trigger ledger_card_reconciliation_lines_month_guard before insert or update or delete on public.ledger_card_reconciliation_lines for each row execute function public.ledger_card_line_month_guard_v1();

create or replace function public.ledger_candidate_resolution_month_guard_v1() returns trigger
language plpgsql security definer set search_path=pg_catalog,public as $$
begin
 if old.status='pending' and new.status in('confirmed','dismissed','superseded') then
  perform public.ledger_assert_month_open_v1(new.proposed_recognition_month);
  perform public.ledger_assert_month_open_v1(date_trunc('month',new.business_date)::date);
 end if;
 return new;
end$$;
create trigger ledger_candidates_resolution_month_guard before update on public.ledger_candidates for each row execute function public.ledger_candidate_resolution_month_guard_v1();

create or replace function public.ledger_confirmed_candidate_drift_v1()returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_tx public.ledger_transactions%rowtype;v_amount numeric;
begin
 if new.status='confirmed'and new.resolved_transaction_id is not null and new.source_drift_fingerprint is distinct from old.source_drift_fingerprint and new.source_drift_fingerprint is not null then
  select*into v_tx from public.ledger_transactions where id=new.resolved_transaction_id;
  if v_tx.id is not null and public.ledger_month_is_closed_v1(coalesce(v_tx.recognition_month,date_trunc('month',v_tx.business_date)::date))then
   v_amount:=coalesce((new.source_drift_snapshot->>'purchase_amount')::numeric,(new.source_drift_snapshot->>'total_amount')::numeric,(new.source_drift_snapshot->>'actual_paid_amount')::numeric,v_tx.amount);
   perform public.ledger_record_source_drift_v1(v_tx.id,new.source_drift_fingerprint,v_amount,new.source_drift_snapshot,coalesce(new.resolved_by,v_tx.confirmed_by));
  end if;
 end if;return new;
end$$;
create trigger ledger_confirmed_candidate_drift after update of source_drift_fingerprint on public.ledger_candidates for each row execute function public.ledger_confirmed_candidate_drift_v1();

create or replace function public.ledger_record_source_drift_v1(
 p_original_transaction_id bigint,p_new_fingerprint text,p_new_amount numeric,p_new_snapshot jsonb,p_actor_user_id bigint
) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_role text;v_tx public.ledger_transactions%rowtype;v_key text;v_id bigint;v_delta numeric;v_month date;
begin
 select lower(role::text) into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;
 if coalesce(v_role,'') not in('owner','master') then return jsonb_build_object('status','forbidden');end if;
 select * into v_tx from public.ledger_transactions where id=p_original_transaction_id for update;
 if v_tx.id is null or length(coalesce(p_new_fingerprint,''))<>64 or jsonb_typeof(p_new_snapshot)<>'object' then return jsonb_build_object('status','invalid_input');end if;
 v_month:=coalesce(v_tx.recognition_month,date_trunc('month',v_tx.business_date)::date);
 if not public.ledger_month_is_closed_v1(v_month) then return jsonb_build_object('status','month_open');end if;
 v_delta:=p_new_amount-v_tx.amount;v_key:='drift:'||v_tx.source_type||':'||coalesce(v_tx.source_key,v_tx.id::text)||':'||p_new_fingerprint;
 select id into v_id from public.ledger_candidates where source_type='ledger_source_drift'and source_key=v_key order by id desc limit 1;
 if v_id is not null then return jsonb_build_object('status','unchanged','candidateId',v_id);end if;
 insert into public.ledger_candidates(candidate_type,source_type,source_key,business_date,proposed_amount,proposed_recognition_month,source_snapshot,source_fingerprint,status)
 values('source_drift','ledger_source_drift',v_key,current_date,greatest(abs(v_delta),0),date_trunc('month',current_date)::date,
 jsonb_build_object('sourceType',v_tx.source_type,'sourceKey',v_tx.source_key,'originalTransactionId',v_tx.id,'affectedClosedMonth',v_month,'oldFingerprint',v_tx.source_fingerprint,'newFingerprint',p_new_fingerprint,'oldAmount',v_tx.amount,'newAmount',p_new_amount,'delta',v_delta,'oldSnapshot',v_tx.source_snapshot,'newSourceSnapshot',p_new_snapshot,'detectedAt',now()),p_new_fingerprint,'pending') returning id into v_id;
 insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,after_snapshot,reason) values(p_actor_user_id,'closed_month_source_drift_detected','candidate',v_id,(select source_snapshot from public.ledger_candidates where id=v_id),'Closed source changed; original transaction preserved');
 return jsonb_build_object('status','created','candidateId',v_id,'delta',v_delta);
end$$;

create or replace function public.ledger_close_preflight_v1(p_month date,p_actor_user_id bigint) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_role text;v_blockers jsonb:='[]';v_warnings jsonb:='[]';v_token text;v_count bigint;v_amount numeric;
begin
 select lower(role::text) into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;
 if coalesce(v_role,'') not in('owner','master') then return jsonb_build_object('status','forbidden');end if;
 if p_month is null or p_month<>date_trunc('month',p_month)::date then return jsonb_build_object('status','invalid_month');end if;
 if p_month>=date_trunc('month',now() at time zone 'Asia/Ho_Chi_Minh')::date then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code',case when p_month=date_trunc('month',now() at time zone 'Asia/Ho_Chi_Minh')::date then'CURRENT_MONTH'else'FUTURE_MONTH'end));end if;
 if public.ledger_month_is_closed_v1(p_month) then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','ALREADY_CLOSED'));end if;
 select count(*) into v_count from public.ledger_candidates where proposed_recognition_month=p_month and status='pending'and candidate_type in('inventory_purchase','employee_meal');if v_count>0 then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','PENDING_CANDIDATES','count',v_count));end if;
 if exists(select 1 from public.payroll_payment_batches where payroll_month=p_month and status<>'completed')or((select min(payroll_month)from public.payroll_payment_batches)<=p_month and not exists(select 1 from public.payroll_payment_batches where payroll_month=p_month and status='completed')) then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','PAYROLL_NOT_COMPLETED'));end if;
 select count(*) into v_count from public.ledger_recurring_expense_plans p where p.effective_from<=p_month and(p.effective_to is null or p.effective_to>=p_month)and not exists(select 1 from public.ledger_transactions t where t.source_type='recurring_expense'and t.source_key='recurring:'||p.id||':'||to_char(p_month,'YYYY-MM')and t.status='confirmed');if v_count>0 then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','RECURRING_NOT_SYNCED','count',v_count));end if;
 select count(*) into v_count from public.ledger_candidates where proposed_recognition_month=p_month and status='confirmed'and resolved_transaction_id is null;if v_count>0 then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','CANDIDATE_LINK_BROKEN','count',v_count));end if;
 if exists(select 1 from public.ledger_transactions t where t.type='transfer'and(t.recognition_month=p_month or date_trunc('month',t.business_date)::date=p_month)and coalesce((select sum(m.amount)from public.ledger_movements m where m.transaction_id=t.id),0)<>0) then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','TRANSFER_UNBALANCED'));end if;
 if exists(select 1 from public.ledger_transactions t where((t.source_type='manual'and t.type in('expense','income'))or t.type in('payroll_payment','payable_payment','prepaid_expense_payment','card_settlement_deposit'))and(t.recognition_month=p_month or date_trunc('month',t.business_date)::date=p_month)and not exists(select 1 from public.ledger_movements m where m.transaction_id=t.id))then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','REQUIRED_MOVEMENT_MISSING'));end if;
 if exists(select 1 from public.ledger_payables p where(select coalesce(sum(a.allocated_amount),0)from public.ledger_payable_allocations a where a.payable_id=p.id)>p.original_amount) then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','PAYABLE_OVERALLOCATED'));end if;
 if exists(select 1 from public.ledger_transactions t join public.ledger_card_reconciliation_lines l on l.pos_card_transaction_id=t.id group by t.id,t.amount having sum(l.allocated_gross_amount)>t.amount) then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','CARD_OVERALLOCATED'));end if;
 if exists(select source_type,source_key from public.ledger_transactions where source_key is not null and status='confirmed'group by source_type,source_key having count(*)>1) then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','DUPLICATE_ACTIVE_SOURCE'));end if;
 select coalesce(sum(r.deposit_amount),0) into v_amount from public.ledger_card_reconciliations r where r.status in('unmatched','partial')and date_trunc('month',r.deposit_date)::date<=p_month; if v_amount>0 then v_warnings:=v_warnings||jsonb_build_array(jsonb_build_object('code','CARD_UNMATCHED','amount',v_amount));end if;
 select coalesce(sum(p.original_amount)-sum(coalesce((select sum(a.allocated_amount)from public.ledger_payable_allocations a join public.ledger_transactions pt on pt.id=a.payment_transaction_id where a.payable_id=p.id and pt.business_date<(p_month+interval'1 month')::date),0)),0) into v_amount from public.ledger_payables p join public.ledger_transactions t on t.id=p.expense_transaction_id where t.business_date<(p_month+interval'1 month')::date and p.status<>'cancelled';if v_amount>0 then v_warnings:=v_warnings||jsonb_build_array(jsonb_build_object('code','PAYABLE_OUTSTANDING','amount',v_amount));end if;
 select count(*) into v_count from public.ledger_transactions where type='balance_adjustment'and date_trunc('month',business_date)::date=p_month;if v_count>0 then v_warnings:=v_warnings||jsonb_build_array(jsonb_build_object('code','BALANCE_ADJUSTMENT','count',v_count));end if;
 select count(*) into v_count from public.ledger_reserve_plans p where p.is_active and coalesce((select sum(case e.entry_type when'allocate'then e.amount when'release'then-e.amount when'consume'then-e.amount else e.amount end)from public.ledger_reserve_entries e where e.reserve_plan_id=p.id and e.occurred_at<((p_month+interval'1 month')::date+time'03:00')at time zone'Asia/Ho_Chi_Minh'),0)<p.target_amount;if v_count>0 then v_warnings:=v_warnings||jsonb_build_array(jsonb_build_object('code','RESERVE_SHORTFALL','count',v_count));end if;
 select count(*) into v_count from public.ledger_candidates where candidate_type='source_drift'and status='pending'and(source_snapshot->>'affectedClosedMonth')::date=p_month;if v_count>0 then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object('code','CONFIRMED_SOURCE_DRIFT','count',v_count));end if;
 v_token:=md5((jsonb_build_object('month',p_month,'blockers',v_blockers,'warnings',v_warnings,'transactionState',(select coalesce(jsonb_agg(jsonb_build_array(id,updated_at,amount,status,source_fingerprint)order by id),'[]')from public.ledger_transactions where recognition_month=p_month or date_trunc('month',business_date)::date=p_month),'candidateState',(select coalesce(jsonb_agg(jsonb_build_array(id,updated_at,status,source_fingerprint)order by id),'[]')from public.ledger_candidates where proposed_recognition_month=p_month))::text)||md5('ledger-close-v1:'||(jsonb_build_object('month',p_month,'blockers',v_blockers,'warnings',v_warnings)::text)));
 return jsonb_build_object('status','ok','month',p_month,'canClose',jsonb_array_length(v_blockers)=0,'blockers',v_blockers,'warnings',v_warnings,'preflightHash',v_token);
end$$;

create or replace function public.ledger_close_month_v1(p_month date,p_expected_preflight_hash text,p_preflight_snapshot jsonb,p_summary_snapshot jsonb,p_snapshot_hash text,p_actor_user_id bigint) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_check jsonb;v_id bigint;
begin
 perform pg_advisory_xact_lock(hashtext('ledger_month_close:'||to_char(p_month,'YYYY-MM')));
 v_check:=public.ledger_close_preflight_v1(p_month,p_actor_user_id);
 if v_check->>'status'<>'ok'then return v_check;end if;
 if v_check->>'preflightHash'<>p_expected_preflight_hash then return jsonb_build_object('status','preflight_stale','code','LEDGER_CLOSE_PREFLIGHT_STALE');end if;
 if not(v_check->>'canClose')::boolean then return jsonb_build_object('status','blocked','blockers',v_check->'blockers');end if;
 if jsonb_typeof(p_preflight_snapshot)<>'object'or jsonb_typeof(p_summary_snapshot)<>'object'or p_snapshot_hash!~'^[0-9a-f]{64}$'then return jsonb_build_object('status','invalid_snapshot');end if;
 insert into public.ledger_month_closures(month,closed_by,preflight_snapshot,summary_snapshot,snapshot_hash,warning_snapshot) values(p_month,p_actor_user_id,p_preflight_snapshot,p_summary_snapshot,p_snapshot_hash,coalesce(v_check->'warnings','[]')) returning id into v_id;
 insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,after_snapshot,reason)values(p_actor_user_id,'month_closed','month_closure',v_id,jsonb_build_object('month',p_month,'preflightHash',p_expected_preflight_hash,'snapshotHash',p_snapshot_hash),'Irreversible V1 month close');
 return jsonb_build_object('status','closed','closureId',v_id,'snapshotHash',p_snapshot_hash);
exception when unique_violation then return jsonb_build_object('status','already_closed');end$$;

create or replace function public.ledger_create_correction_v1(p_original_transaction_id bigint,p_economic_delta numeric,p_movement_adjustments jsonb,p_occurred_at timestamptz,p_recognition_month date,p_reason text,p_source_drift_candidate_id bigint,p_actor_user_id bigint) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_role text;v_original public.ledger_transactions%rowtype;v_candidate public.ledger_candidates%rowtype;v_operation uuid:=gen_random_uuid();v_tx_id bigint;v_item jsonb;v_delta numeric:=coalesce(p_economic_delta,0);v_business date;v_source_month date;
begin
 select lower(role::text)into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;if coalesce(v_role,'')not in('owner','master')then return jsonb_build_object('status','forbidden');end if;
 if nullif(btrim(p_reason),'')is null or p_occurred_at is null or jsonb_typeof(coalesce(p_movement_adjustments,'[]'))<>'array'or(v_delta=0 and jsonb_array_length(coalesce(p_movement_adjustments,'[]'))=0)then return jsonb_build_object('status','invalid_input');end if;
 if p_source_drift_candidate_id is not null then select*into v_candidate from public.ledger_candidates where id=p_source_drift_candidate_id and candidate_type='source_drift'for update;if v_candidate.id is null or v_candidate.status<>'pending'or(v_candidate.source_snapshot->>'originalTransactionId')::bigint<>p_original_transaction_id then return jsonb_build_object('status','drift_already_resolved');end if;end if;
 select*into v_original from public.ledger_transactions where id=p_original_transaction_id for update;if v_original.id is null then return jsonb_build_object('status','original_not_found');end if;
 v_source_month:=coalesce(v_original.recognition_month,date_trunc('month',v_original.business_date)::date);if not public.ledger_month_is_closed_v1(v_source_month)then return jsonb_build_object('status','original_month_open');end if;
 v_business:=((p_occurred_at at time zone'Asia/Ho_Chi_Minh')-interval'3 hours')::date;perform public.ledger_assert_month_open_v1(date_trunc('month',v_business)::date);if v_delta<>0 then perform public.ledger_assert_month_open_v1(p_recognition_month);if p_recognition_month is null or p_recognition_month<>date_trunc('month',p_recognition_month)::date or v_original.type not in('income','sales','expense','expense_recognition')then return jsonb_build_object('status','invalid_economic_correction');end if;end if;
 insert into public.ledger_transactions(operation_id,type,occurred_at,business_date,recognition_month,amount,category_id,party_id,status,source_type,source_key,source_snapshot,correction_of_id,memo,created_by,confirmed_by,economic_effect_sign)
 values(v_operation,case when v_delta=0 then'correction'else v_original.type end,p_occurred_at,v_business,case when v_delta=0 then null else p_recognition_month end,abs(v_delta),case when v_delta=0 then null else v_original.category_id end,v_original.party_id,'confirmed','ledger_correction',null,jsonb_build_object('originalTransactionId',v_original.id,'closedMonth',v_source_month,'economicDelta',v_delta,'movementAdjustments',coalesce(p_movement_adjustments,'[]')),v_original.id,btrim(p_reason),p_actor_user_id,p_actor_user_id,case when v_delta<0 then-1 else 1 end)returning id into v_tx_id;
 for v_item in select value from jsonb_array_elements(coalesce(p_movement_adjustments,'[]'))loop if coalesce((v_item->>'signedAmount')::numeric,0)=0 or not exists(select 1 from public.ledger_fund_accounts where id=(v_item->>'fundAccountId')::bigint and is_active=true)then raise exception using errcode='P0001',message='INVALID_MOVEMENT_ADJUSTMENT';end if;insert into public.ledger_movements(transaction_id,fund_account_id,amount)values(v_tx_id,(v_item->>'fundAccountId')::bigint,(v_item->>'signedAmount')::numeric);end loop;
 if v_candidate.id is not null then update public.ledger_candidates set status='confirmed',resolved_transaction_id=v_tx_id,resolved_by=p_actor_user_id,resolved_at=now(),updated_at=now()where id=v_candidate.id;end if;
 insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,before_snapshot,after_snapshot,reason)values(p_actor_user_id,'correction_created','transaction',v_tx_id,to_jsonb(v_original),jsonb_build_object('correctionTransactionId',v_tx_id,'operationId',v_operation,'economicDelta',v_delta,'movementAdjustments',coalesce(p_movement_adjustments,'[]'),'sourceDriftCandidateId',p_source_drift_candidate_id),btrim(p_reason));
 return jsonb_build_object('status','created','transactionId',v_tx_id,'operationId',v_operation);
end$$;

create or replace function public.ledger_sync_pos_sales_v2(p_rows jsonb,p_actor_user_id bigint)returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_role text;v_row jsonb;v_tx public.ledger_transactions%rowtype;v_key text;v_date date;v_result jsonb;v_drift int:=0;v_unchanged int:=0;
begin
 select lower(role::text) into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;if coalesce(v_role,'')not in('owner','master')then return jsonb_build_object('status','forbidden');end if;
 if jsonb_typeof(p_rows)<>'array'then return jsonb_build_object('status','invalid_rows');end if;
 if not exists(select 1 from jsonb_array_elements(p_rows)r where public.ledger_month_is_closed_v1(date_trunc('month',(r->>'businessDate')::date)::date))then return public.ledger_sync_pos_sales_v1(p_rows,p_actor_user_id);end if;
 for v_row in select value from jsonb_array_elements(p_rows)loop v_date:=(v_row->>'businessDate')::date;if not public.ledger_month_is_closed_v1(date_trunc('month',v_date)::date)then continue;end if;v_key:='pos:'||v_date||':'||(v_row->>'bucket');select*into v_tx from public.ledger_transactions where source_type='pos_sales_daily_payment'and source_key=v_key;if v_tx.id is null then continue;elsif v_tx.source_fingerprint=v_row->>'fingerprint'then v_unchanged:=v_unchanged+1;else v_result:=public.ledger_record_source_drift_v1(v_tx.id,v_row->>'fingerprint',(v_row->>'amount')::numeric,v_row->'snapshot',p_actor_user_id);if v_result->>'status'='created'then v_drift:=v_drift+1;else v_unchanged:=v_unchanged+1;end if;end if;end loop;
 return jsonb_build_object('status','ok','createdCount',0,'updatedCount',0,'unchangedCount',v_unchanged,'driftCount',v_drift,'closedMonth',true);
end$$;

create or replace function public.ledger_sync_recurring_expenses_v2(p_month date,p_actor_user_id bigint)returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_role text;v_plan public.ledger_recurring_expense_plans%rowtype;v_tx public.ledger_transactions%rowtype;v_snapshot jsonb;v_fp text;v_result jsonb;v_drift int:=0;v_unchanged int:=0;
begin
 select lower(role::text) into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;if coalesce(v_role,'')not in('owner','master')then return jsonb_build_object('status','forbidden');end if;
 if not public.ledger_month_is_closed_v1(p_month)then return public.ledger_sync_recurring_expenses_v1(p_month,p_actor_user_id);end if;
 for v_plan in select*from public.ledger_recurring_expense_plans where frequency='monthly'and effective_from<=p_month and(effective_to is null or effective_to>=p_month)order by id loop v_snapshot:=jsonb_build_object('planId',v_plan.id,'planName',v_plan.name,'frequency',v_plan.frequency,'recognitionDay',v_plan.recognition_day,'effectiveFrom',v_plan.effective_from,'effectiveTo',v_plan.effective_to,'amount',v_plan.amount);v_fp:=md5(v_snapshot::text);select*into v_tx from public.ledger_transactions where source_type='recurring_expense'and source_key='recurring:'||v_plan.id||':'||to_char(p_month,'YYYY-MM');if v_tx.id is not null and v_tx.source_fingerprint<>v_fp then v_result:=public.ledger_record_source_drift_v1(v_tx.id,v_fp||v_fp,v_plan.amount,v_snapshot,p_actor_user_id);if v_result->>'status'='created'then v_drift:=v_drift+1;end if;else v_unchanged:=v_unchanged+1;end if;end loop;return jsonb_build_object('status','ok','createdCount',0,'updatedCount',0,'unchangedCount',v_unchanged,'driftCount',v_drift,'closedMonth',true);
end$$;

create or replace function public.ledger_sync_payroll_company_cost_v2(p_row jsonb,p_actor_user_id bigint)returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_role text;v_month date;v_tx public.ledger_transactions%rowtype;v_result jsonb;
begin select lower(role::text) into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;if coalesce(v_role,'')not in('owner','master')then return jsonb_build_object('status','forbidden');end if;v_month:=(p_row->>'payrollMonth')::date;if not public.ledger_month_is_closed_v1(v_month)then return public.ledger_sync_payroll_company_cost_v1(p_row,p_actor_user_id);end if;select*into v_tx from public.ledger_transactions where source_type='payroll_completed_batch'and source_key='payroll-batch:'||(p_row->>'batchId')||':company-cost';if v_tx.id is null or v_tx.source_fingerprint=p_row->>'fingerprint'then return jsonb_build_object('status','unchanged','unchangedCount',1,'driftCount',0,'closedMonth',true);end if;v_result:=public.ledger_record_source_drift_v1(v_tx.id,p_row->>'fingerprint',(p_row->>'amount')::numeric,p_row->'snapshot',p_actor_user_id);return jsonb_build_object('status','drift','unchangedCount',0,'driftCount',case when v_result->>'status'='created'then 1 else 0 end,'closedMonth',true);end$$;

revoke all on function public.ledger_transaction_month_guard_v1(),public.ledger_movement_month_guard_v1(),public.ledger_dated_write_month_guard_v1(),public.ledger_payable_allocation_month_guard_v1(),public.ledger_card_reconciliation_month_guard_v1(),public.ledger_card_line_month_guard_v1(),public.ledger_candidate_resolution_month_guard_v1(),public.ledger_confirmed_candidate_drift_v1() from public,anon,authenticated,service_role;
revoke all on function public.ledger_month_is_closed_v1(date),public.ledger_assert_month_open_v1(date),public.ledger_record_source_drift_v1(bigint,text,numeric,jsonb,bigint),public.ledger_close_preflight_v1(date,bigint),public.ledger_close_month_v1(date,text,jsonb,jsonb,text,bigint),public.ledger_create_correction_v1(bigint,numeric,jsonb,timestamptz,date,text,bigint,bigint),public.ledger_sync_pos_sales_v2(jsonb,bigint),public.ledger_sync_recurring_expenses_v2(date,bigint),public.ledger_sync_payroll_company_cost_v2(jsonb,bigint) from public,anon,authenticated;
grant execute on function public.ledger_month_is_closed_v1(date),public.ledger_assert_month_open_v1(date),public.ledger_record_source_drift_v1(bigint,text,numeric,jsonb,bigint),public.ledger_close_preflight_v1(date,bigint),public.ledger_close_month_v1(date,text,jsonb,jsonb,text,bigint),public.ledger_create_correction_v1(bigint,numeric,jsonb,timestamptz,date,text,bigint,bigint),public.ledger_sync_pos_sales_v2(jsonb,bigint),public.ledger_sync_recurring_expenses_v2(date,bigint),public.ledger_sync_payroll_company_cost_v2(jsonb,bigint) to service_role;

comment on table public.ledger_month_closures is 'Immutable V1 month-close records. Reopen/delete is intentionally unsupported.';
comment on column public.ledger_transactions.economic_effect_sign is '+1 increases the transaction economic effect; -1 is a linked correction reducing it.';
