begin;

create extension if not exists btree_gist;

create table public.employee_level_program_versions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  enabled boolean not null,
  effective_from date not null,
  effective_to date null,
  base_date date null,
  revision bigint not null,
  change_reason text not null,
  created_by bigint null references public.users(id) on delete set null,
  created_by_username text not null,
  created_at timestamptz not null default now(),
  constraint employee_level_program_versions_month_start_check check (
    extract(day from effective_from) = 1
    and (effective_to is null or extract(day from effective_to) = 1)
  ),
  constraint employee_level_program_versions_range_check check (
    effective_to is null or effective_to >= effective_from
  ),
  constraint employee_level_program_versions_base_check check (
    enabled or base_date is null
  ),
  constraint employee_level_program_versions_revision_check check (revision > 0),
  constraint employee_level_program_versions_reason_check check (btrim(change_reason) <> ''),
  constraint employee_level_program_versions_actor_check check (btrim(created_by_username) <> ''),
  constraint employee_level_program_versions_user_revision_key unique (user_id, revision),
  constraint employee_level_program_versions_no_overlap exclude using gist (
    user_id with =,
    daterange(effective_from, coalesce(effective_to, 'infinity'::date), '[)') with &&
  )
);

create index employee_level_program_versions_user_period_idx
  on public.employee_level_program_versions (user_id, effective_from desc, revision desc);
create index employee_level_program_versions_created_by_idx
  on public.employee_level_program_versions (created_by)
  where created_by is not null;

alter table public.employee_level_program_versions enable row level security;
revoke all on table public.employee_level_program_versions from public, anon, authenticated, service_role;
revoke all on sequence public.employee_level_program_versions_id_seq from public, anon, authenticated, service_role;
grant select on table public.employee_level_program_versions to service_role;

insert into public.employee_level_program_versions (
  user_id, enabled, effective_from, effective_to, base_date, revision,
  change_reason, created_by, created_by_username
)
select
  u.id,
  case
    when u.is_system_account then false
    when u.role in ('manager', 'leader', 'staff') then true
    when u.role in ('owner', 'master') then u.level_program_enabled is true
    else false
  end,
  greatest(
    date '2026-07-01',
    coalesce(date_trunc('month', u.hire_date)::date, date '2026-07-01')
  ),
  null,
  case
    when u.is_system_account then null
    when u.role in ('manager', 'leader', 'staff') then coalesce(u.level_base_date_override, u.hire_date)
    when u.role in ('owner', 'master') and u.level_program_enabled is true then coalesce(u.level_base_date_override, u.hire_date)
    else null
  end,
  1,
  'legacy_policy_backfill',
  null,
  'migration'
from public.users u;

update public.users u
set level_program_enabled = case
      when v.enabled and u.hire_date is null then null
      else v.enabled
    end,
    level_base_date_override = v.base_date
from public.employee_level_program_versions v
where v.user_id = u.id
  and v.revision = 1;

create or replace function public.employee_update_profile_and_level_v5(
  p_user_id bigint,
  p_updates jsonb,
  p_level_program_enabled boolean,
  p_effective_from date,
  p_change_reason text,
  p_actor_id bigint,
  p_actor_username text
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_before public.users%rowtype;
  v_after public.users%rowtype;
  v_current public.employee_level_program_versions%rowtype;
  v_revision bigint;
  v_base_date date;
  v_current_month date := date_trunc('month', now() at time zone 'Asia/Ho_Chi_Minh')::date;
begin
  select * into v_before from public.users where id = p_user_id for update;
  if not found then raise exception 'EMPLOYEE_NOT_FOUND' using errcode = 'P0002'; end if;

  select * into v_after from jsonb_populate_record(
    null::public.users,
    public.employee_update_profile_and_level_v4(
      p_user_id, p_updates, v_before.level_program_enabled,
      v_before.level_base_date_override, p_actor_id, p_actor_username
    )
  );

  if p_effective_from is null then return to_jsonb(v_after) - 'password'; end if;
  if p_effective_from <> date_trunc('month', p_effective_from)::date
    or p_effective_from < v_current_month
    or p_effective_from > (v_current_month + interval '1 month')::date then
    raise exception 'INVALID_LEVEL_EFFECTIVE_MONTH' using errcode = '22023';
  end if;
  if nullif(btrim(p_change_reason), '') is null then
    raise exception 'CHANGE_REASON_REQUIRED' using errcode = '22023';
  end if;
  if v_after.termination_date is not null then
    raise exception 'TERMINATED_EMPLOYEE_READ_ONLY' using errcode = '22023';
  end if;
  if v_after.is_system_account and p_level_program_enabled then
    raise exception 'SYSTEM_ACCOUNT_NOT_ELIGIBLE' using errcode = '22023';
  end if;

  select * into v_current
  from public.employee_level_program_versions
  where user_id = p_user_id
    and effective_from <= p_effective_from
    and (effective_to is null or effective_to > p_effective_from)
  order by effective_from desc, revision desc
  limit 1 for update;

  if found and v_current.enabled is not distinct from p_level_program_enabled then
    return to_jsonb(v_after) - 'password';
  end if;

  v_base_date := case when p_level_program_enabled then p_effective_from else null end;
  if p_level_program_enabled and v_after.hire_date is null then
    raise exception 'HIRE_DATE_REQUIRED' using errcode = '22023';
  end if;

  update public.employee_level_program_versions
  set effective_to = case
    when effective_from < p_effective_from then p_effective_from
    else effective_from
  end
  where user_id = p_user_id
    and (
      (effective_from <= p_effective_from
        and (effective_to is null or effective_to > p_effective_from))
      or effective_from >= p_effective_from
    );

  select coalesce(max(revision), 0) + 1 into v_revision
  from public.employee_level_program_versions where user_id = p_user_id;

  insert into public.employee_level_program_versions (
    user_id, enabled, effective_from, effective_to, base_date, revision,
    change_reason, created_by, created_by_username
  ) values (
    p_user_id, p_level_program_enabled, p_effective_from, null, v_base_date,
    v_revision, btrim(p_change_reason), p_actor_id, p_actor_username
  );

  update public.users
  set level_program_enabled = p_level_program_enabled,
      level_base_date_override = v_base_date
  where id = p_user_id
  returning * into v_after;

  insert into public.employee_level_audit_logs (
    user_id, action, previous_enabled, next_enabled,
    previous_base_date_override, next_base_date_override,
    previous_effective_base_date, next_effective_base_date,
    previous_level, next_level, actor_id, actor_username, change_reason
  ) values (
    p_user_id,
    case when p_level_program_enabled then 'level_program_enabled' else 'level_program_disabled' end,
    v_current.enabled, p_level_program_enabled,
    v_current.base_date, v_base_date, v_current.base_date, v_base_date,
    null, null, p_actor_id, p_actor_username, btrim(p_change_reason)
  );

  return to_jsonb(v_after) - 'password';
end;
$$;

create or replace function public.employee_create_with_schedule_v2(
  p_employee jsonb,
  p_level_program_enabled boolean,
  p_change_reason text,
  p_actor_id bigint,
  p_actor_username text
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_created public.users%rowtype;
  v_hire_date date := nullif(p_employee ->> 'hire_date', '')::date;
  v_effective_from date;
  v_base_date date;
begin
  if p_level_program_enabled and v_hire_date is null then
    raise exception 'HIRE_DATE_REQUIRED' using errcode = '22023';
  end if;
  if nullif(btrim(p_change_reason), '') is null then
    raise exception 'CHANGE_REASON_REQUIRED' using errcode = '22023';
  end if;

  select * into v_created from jsonb_populate_record(
    null::public.users,
    public.employee_create_with_schedule_v1(p_employee, p_actor_id, p_actor_username)
  );
  if v_created.is_system_account and p_level_program_enabled then
    raise exception 'SYSTEM_ACCOUNT_NOT_ELIGIBLE' using errcode = '22023';
  end if;
  v_effective_from := coalesce(date_trunc('month', v_hire_date)::date,
    date_trunc('month', now() at time zone 'Asia/Ho_Chi_Minh')::date);
  v_base_date := case when p_level_program_enabled then v_hire_date else null end;

  update public.users
  set level_program_enabled = p_level_program_enabled,
      level_base_date_override = v_base_date
  where id = v_created.id returning * into v_created;

  insert into public.employee_level_program_versions (
    user_id, enabled, effective_from, effective_to, base_date, revision,
    change_reason, created_by, created_by_username
  ) values (
    v_created.id, p_level_program_enabled, v_effective_from, null, v_base_date, 1,
    btrim(p_change_reason), p_actor_id, p_actor_username
  );

  return to_jsonb(v_created) - 'password';
end;
$$;

create or replace function public.employee_rehire_with_level_policy_v2(
  p_user_id bigint,
  p_rehire_date date,
  p_level_program_enabled boolean,
  p_change_reason text,
  p_actor_id bigint,
  p_actor_username text,
  p_previous_level smallint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_after public.users%rowtype;
  v_effective_from date := date_trunc('month', p_rehire_date)::date;
  v_revision bigint;
  v_base_date date := case when p_level_program_enabled then p_rehire_date else null end;
begin
  select * into v_after from jsonb_populate_record(
    null::public.users,
    public.employee_rehire_with_level_reset_v1(
      p_user_id, p_rehire_date, p_actor_id, p_actor_username,
      p_change_reason, p_previous_level
    )
  );

  update public.employee_level_program_versions
  set effective_to = case
    when effective_from < v_effective_from then v_effective_from
    else effective_from
  end
  where user_id = p_user_id
    and (
      (effective_from <= v_effective_from
        and (effective_to is null or effective_to > v_effective_from))
      or effective_from >= v_effective_from
    );

  select coalesce(max(revision), 0) + 1 into v_revision
  from public.employee_level_program_versions where user_id = p_user_id;

  insert into public.employee_level_program_versions (
    user_id, enabled, effective_from, effective_to, base_date, revision,
    change_reason, created_by, created_by_username
  ) values (
    p_user_id, p_level_program_enabled, v_effective_from, null, v_base_date,
    v_revision, btrim(p_change_reason), p_actor_id, p_actor_username
  );

  update public.users
  set level_program_enabled = p_level_program_enabled,
      level_base_date_override = v_base_date
  where id = p_user_id returning * into v_after;

  return to_jsonb(v_after) - 'password';
end;
$$;

revoke all on function public.employee_update_profile_and_level_v5(bigint,jsonb,boolean,date,text,bigint,text)
  from public, anon, authenticated;
revoke all on function public.employee_create_with_schedule_v2(jsonb,boolean,text,bigint,text)
  from public, anon, authenticated;
revoke all on function public.employee_rehire_with_level_policy_v2(bigint,date,boolean,text,bigint,text,smallint)
  from public, anon, authenticated;
grant execute on function public.employee_update_profile_and_level_v5(bigint,jsonb,boolean,date,text,bigint,text)
  to service_role;
grant execute on function public.employee_create_with_schedule_v2(jsonb,boolean,text,bigint,text)
  to service_role;
grant execute on function public.employee_rehire_with_level_policy_v2(bigint,date,boolean,text,bigint,text,smallint)
  to service_role;

comment on table public.employee_level_program_versions is
  'Effective-month employee level participation history used by payroll and level presentation.';
comment on column public.users.level_program_enabled is
  'Compatibility cache of the latest scheduled employee-level state; nullable when legacy constraints require it. All level and payroll decisions use employee_level_program_versions.';

commit;
