-- BAR zone content, staff colors, append-only activity logs, and atomic mutations.
-- All access is through server route handlers using the service role. No client RLS policies are created.

create table public.bar_zones (
  id bigint generated by default as identity primary key,
  code text not null unique,
  kind text not null,
  selectable_for_keeping boolean not null,
  note_ko text,
  note_vi text,
  image_path text,
  assignee_user_id bigint references public.users(id) on delete set null,
  is_active boolean not null default true,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by_user_id bigint references public.users(id) on delete set null,
  constraint bar_zones_kind_check check (kind in ('storage', 'equipment')),
  constraint bar_zones_code_check check (
    code in ('A1', 'A2', 'A3', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8')
  ),
  constraint bar_zones_semantics_check check (
    (code = 'A2' and kind = 'equipment' and selectable_for_keeping = false)
    or
    (code <> 'A2' and kind = 'storage' and selectable_for_keeping = true)
  ),
  constraint bar_zones_version_check check (version >= 1)
);

create index bar_zones_assignee_user_id_idx on public.bar_zones(assignee_user_id);
create index bar_zones_is_active_idx on public.bar_zones(is_active);

create table public.bar_staff_profiles (
  user_id bigint primary key references public.users(id) on delete cascade,
  color_key text not null,
  updated_by_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bar_staff_profiles_color_key_check check (
    color_key in ('red', 'orange', 'yellow', 'green', 'teal', 'blue', 'purple', 'pink')
  )
);

create table public.bar_activity_logs (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id bigint not null,
  entity_code_snapshot text,
  action_type text not null,
  before_data jsonb,
  after_data jsonb,
  actor_user_id bigint references public.users(id) on delete set null,
  actor_name_snapshot text not null,
  created_at timestamptz not null default now()
);

create index bar_activity_logs_recent_idx on public.bar_activity_logs(created_at desc, id desc);
create index bar_activity_logs_entity_idx on public.bar_activity_logs(entity_type, entity_id, created_at desc);
create index bar_activity_logs_actor_idx on public.bar_activity_logs(actor_user_id);
create index bar_activity_logs_action_idx on public.bar_activity_logs(action_type);

alter table public.bar_zones enable row level security;
alter table public.bar_staff_profiles enable row level security;
alter table public.bar_activity_logs enable row level security;

insert into public.bar_zones (code, kind, selectable_for_keeping, is_active)
values
  ('A1', 'storage', true, true),
  ('A2', 'equipment', false, true),
  ('A3', 'storage', true, true),
  ('B1', 'storage', true, true),
  ('B2', 'storage', true, true),
  ('B3', 'storage', true, true),
  ('B4', 'storage', true, true),
  ('B5', 'storage', true, true),
  ('B6', 'storage', true, true),
  ('B7', 'storage', true, true),
  ('B8', 'storage', true, true),
  ('C1', 'storage', true, true),
  ('C2', 'storage', true, true),
  ('C3', 'storage', true, true),
  ('C4', 'storage', true, true),
  ('C5', 'storage', true, true),
  ('C6', 'storage', true, true),
  ('C7', 'storage', true, true),
  ('C8', 'storage', true, true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'bar-zone-images',
  'bar-zone-images',
  false,
  256000,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.bar_update_zone(
  p_code text,
  p_expected_version integer,
  p_actor_user_id bigint,
  p_actor_name text,
  p_update_notes boolean,
  p_note_ko text,
  p_note_vi text,
  p_update_assignee boolean,
  p_assignee_user_id bigint,
  p_update_color boolean,
  p_color_key text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_zone public.bar_zones%rowtype;
  v_new_assignee bigint;
  v_old_color text;
  v_staff_name text;
  v_changed boolean := false;
  v_action text;
begin
  select * into v_zone from public.bar_zones where code = p_code for update;
  if not found then
    return jsonb_build_object('status', 'not_found');
  end if;
  if v_zone.version <> p_expected_version then
    return jsonb_build_object('status', 'conflict', 'version', v_zone.version);
  end if;

  v_new_assignee := case when p_update_assignee then p_assignee_user_id else v_zone.assignee_user_id end;

  if p_update_notes and (v_zone.note_ko is distinct from p_note_ko or v_zone.note_vi is distinct from p_note_vi) then
    insert into public.bar_activity_logs (
      entity_type, entity_id, entity_code_snapshot, action_type,
      before_data, after_data, actor_user_id, actor_name_snapshot
    ) values (
      'zone', v_zone.id, v_zone.code, 'zone_content_updated',
      jsonb_build_object('note_ko', v_zone.note_ko, 'note_vi', v_zone.note_vi),
      jsonb_build_object('note_ko', p_note_ko, 'note_vi', p_note_vi),
      p_actor_user_id, p_actor_name
    );
    v_changed := true;
  end if;

  if p_update_assignee and v_zone.assignee_user_id is distinct from p_assignee_user_id then
    v_action := case
      when v_zone.assignee_user_id is null then 'zone_assignee_assigned'
      when p_assignee_user_id is null then 'zone_assignee_removed'
      else 'zone_assignee_changed'
    end;
    insert into public.bar_activity_logs (
      entity_type, entity_id, entity_code_snapshot, action_type,
      before_data, after_data, actor_user_id, actor_name_snapshot
    ) values (
      'zone', v_zone.id, v_zone.code, v_action,
      jsonb_build_object('assignee_user_id', v_zone.assignee_user_id),
      jsonb_build_object('assignee_user_id', p_assignee_user_id),
      p_actor_user_id, p_actor_name
    );
    v_changed := true;
  end if;

  if p_update_color then
    if v_new_assignee is null then
      raise exception 'An assignee is required to update a BAR staff color';
    end if;
    -- Serialize color changes for the same employee even when callers edit different zones.
    perform pg_catalog.pg_advisory_xact_lock(
      pg_catalog.hashtextextended('bar_staff_profile:' || v_new_assignee::text, 0)
    );
    select color_key into v_old_color from public.bar_staff_profiles where user_id = v_new_assignee;
    if v_old_color is distinct from p_color_key then
      select coalesce(nullif(name, ''), nullif(full_name, ''), username)
      into v_staff_name from public.users where id = v_new_assignee;
      insert into public.bar_staff_profiles (user_id, color_key, updated_by_user_id)
      values (v_new_assignee, p_color_key, p_actor_user_id)
      on conflict (user_id) do update set
        color_key = excluded.color_key,
        updated_by_user_id = excluded.updated_by_user_id,
        updated_at = now();
      insert into public.bar_activity_logs (
        entity_type, entity_id, entity_code_snapshot, action_type, before_data, after_data,
        actor_user_id, actor_name_snapshot
      ) values (
        'staff_profile', v_new_assignee, v_staff_name, 'staff_color_changed',
        jsonb_build_object('color_key', v_old_color),
        jsonb_build_object('color_key', p_color_key),
        p_actor_user_id, p_actor_name
      );
      v_changed := true;
    end if;
  end if;

  if v_changed then
    update public.bar_zones set
      note_ko = case when p_update_notes then p_note_ko else note_ko end,
      note_vi = case when p_update_notes then p_note_vi else note_vi end,
      assignee_user_id = case when p_update_assignee then p_assignee_user_id else assignee_user_id end,
      version = version + 1,
      updated_at = now(),
      updated_by_user_id = p_actor_user_id
    where id = v_zone.id
    returning version into p_expected_version;
  end if;

  return jsonb_build_object(
    'status', 'ok',
    'version', case when v_changed then p_expected_version else v_zone.version end,
    'changed', v_changed
  );
end;
$$;

create or replace function public.bar_update_zone_photo(
  p_code text,
  p_expected_version integer,
  p_image_path text,
  p_actor_user_id bigint,
  p_actor_name text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_zone public.bar_zones%rowtype;
  v_action text;
  v_new_version integer;
begin
  select * into v_zone from public.bar_zones where code = p_code for update;
  if not found then
    return jsonb_build_object('status', 'not_found');
  end if;
  if v_zone.version <> p_expected_version then
    return jsonb_build_object('status', 'conflict', 'version', v_zone.version);
  end if;
  if v_zone.image_path is not distinct from p_image_path then
    return jsonb_build_object('status', 'ok', 'version', v_zone.version, 'changed', false, 'old_image_path', v_zone.image_path);
  end if;

  v_action := case
    when v_zone.image_path is null then 'zone_photo_added'
    when p_image_path is null then 'zone_photo_removed'
    else 'zone_photo_replaced'
  end;

  update public.bar_zones set
    image_path = p_image_path,
    version = version + 1,
    updated_at = now(),
    updated_by_user_id = p_actor_user_id
  where id = v_zone.id
  returning version into v_new_version;

  insert into public.bar_activity_logs (
    entity_type, entity_id, entity_code_snapshot, action_type,
    before_data, after_data, actor_user_id, actor_name_snapshot
  ) values (
    'zone', v_zone.id, v_zone.code, v_action,
    jsonb_build_object('image_path', v_zone.image_path),
    jsonb_build_object('image_path', p_image_path),
    p_actor_user_id, p_actor_name
  );

  return jsonb_build_object(
    'status', 'ok', 'version', v_new_version, 'changed', true,
    'old_image_path', v_zone.image_path
  );
end;
$$;

revoke all on function public.bar_update_zone(text, integer, bigint, text, boolean, text, text, boolean, bigint, boolean, text) from public, anon, authenticated;
revoke all on function public.bar_update_zone_photo(text, integer, text, bigint, text) from public, anon, authenticated;
grant execute on function public.bar_update_zone(text, integer, bigint, text, boolean, text, text, boolean, bigint, boolean, text) to service_role;
grant execute on function public.bar_update_zone_photo(text, integer, text, bigint, text) to service_role;
