begin;

create table public.pos_sales_business_day_closures (
  id bigint generated by default as identity primary key,
  business_date date not null,
  revision integer not null check (revision > 0),
  close_method text not null check (close_method in ('manual', 'automatic')),
  closed_at timestamptz not null default now(),
  closed_by bigint not null references public.users(id) on delete restrict,
  sync_run_id bigint null references public.pos_sales_sync_runs(id) on delete restrict,
  source_fingerprint text not null check (source_fingerprint ~ '^[0-9a-f]{64}$'),
  source_snapshot jsonb not null check (jsonb_typeof(source_snapshot) = 'object'),
  ledger_result_snapshot jsonb not null default '{}'::jsonb check (jsonb_typeof(ledger_result_snapshot) = 'object'),
  created_at timestamptz not null default now(),
  unique (business_date, revision)
);
create index pos_sales_business_day_closures_actor_idx on public.pos_sales_business_day_closures(closed_by);
create index pos_sales_business_day_closures_sync_run_idx on public.pos_sales_business_day_closures(sync_run_id) where sync_run_id is not null;
alter table public.pos_sales_business_day_closures enable row level security;
revoke all on table public.pos_sales_business_day_closures from public, anon, authenticated, service_role;
revoke all on sequence public.pos_sales_business_day_closures_id_seq from public, anon, authenticated, service_role;
grant select on table public.pos_sales_business_day_closures to service_role;

create schema pos_sales_close_private;
revoke all on schema pos_sales_close_private from public, anon, authenticated, service_role;
-- Unforgeable transaction-local projection capability. Only the close RPC
-- owner can create it; it is removed before returning and rolled back on error.
create table pos_sales_close_private.projection_permissions (
  transaction_id bigint not null,
  business_date date not null,
  actor_user_id bigint not null references public.users(id),
  primary key (transaction_id, business_date)
);
revoke all on table pos_sales_close_private.projection_permissions from public, anon, authenticated, service_role;

create function pos_sales_close_private.canonical_json(p_value jsonb)
returns text language plpgsql immutable set search_path = pg_catalog, public as $$
declare v_result text;
begin
  case jsonb_typeof(p_value)
    when 'object' then
      select '{' || coalesce(string_agg(to_jsonb(key)::text || ':' || pos_sales_close_private.canonical_json(value), ',' order by key collate "C"), '') || '}'
      into v_result from jsonb_each(p_value);
    when 'array' then
      select '[' || coalesce(string_agg(pos_sales_close_private.canonical_json(value), ',' order by ordinal), '') || ']'
      into v_result from jsonb_array_elements(p_value) with ordinality a(value, ordinal);
    when 'number' then
      if (p_value::text)::numeric <> trunc((p_value::text)::numeric)
        or abs((p_value::text)::numeric) > 9007199254740991 then
        raise exception 'POS_SOURCE_INVALID_AMOUNT' using errcode = '22023';
      end if;
      v_result := ((p_value::text)::numeric)::bigint::text;
    else v_result := p_value::text;
  end case;
  if v_result is null then raise exception 'POS_SOURCE_SNAPSHOT_INCOMPLETE' using errcode = '22023'; end if;
  return v_result;
end $$;

create function pos_sales_close_private.validate_source(p_date date, p_fingerprint text, p_snapshot jsonb, p_rows jsonb)
returns void language plpgsql set search_path = pg_catalog, public as $$
declare v_live jsonb;
begin
  if p_fingerprint is null or p_fingerprint !~ '^[0-9a-f]{64}$'
    or jsonb_typeof(p_snapshot) is distinct from 'object'
    or jsonb_typeof(p_rows) is distinct from 'array' then
    raise exception 'POS_SOURCE_SNAPSHOT_INCOMPLETE' using errcode = '22023';
  end if;
  v_live := pos_sales_close_private.build_source(p_date);
  if p_rows is distinct from v_live->'rows' or p_snapshot is distinct from v_live->'sourceSnapshot'
    or p_fingerprint is distinct from v_live->>'sourceFingerprint' then
    raise exception 'POS_SOURCE_CHANGED_BEFORE_PROJECTION' using errcode = '40001';
  end if;
end $$;

create function pos_sales_close_private.immutable_closure()
returns trigger language plpgsql set search_path = pg_catalog, public as $$
begin
  raise exception 'POS_SALES_DAY_CLOSURE_IMMUTABLE' using errcode = '55000';
end $$;
create trigger pos_sales_day_closure_immutable before update or delete on public.pos_sales_business_day_closures
for each row execute function pos_sales_close_private.immutable_closure();
create trigger pos_sales_day_closure_no_truncate before truncate on public.pos_sales_business_day_closures
for each statement execute function pos_sales_close_private.immutable_closure();

create function pos_sales_close_private.assert_projection_allowed(p_date date)
returns void language plpgsql set search_path = pg_catalog, public as $$
begin
  if exists (select 1 from public.pos_sales_business_day_closures where business_date = p_date)
    and not exists (select 1 from pos_sales_close_private.projection_permissions
      where transaction_id = txid_current() and business_date = p_date) then
    raise exception 'POS_SALES_DAY_CLOSED' using errcode = '55000';
  end if;
end $$;

-- Also protects legacy v1/v2 callers and direct movement changes. Public
-- source-key/RPC contracts stay intact; a closed day can no longer overwrite.
create function pos_sales_close_private.transaction_guard()
returns trigger language plpgsql security definer set search_path = pg_catalog, public as $$
begin
  if tg_op <> 'INSERT' and old.source_type = 'pos_sales_daily_payment' then
    perform pos_sales_close_private.assert_projection_allowed(old.business_date);
  end if;
  if tg_op <> 'DELETE' and new.source_type = 'pos_sales_daily_payment' then
    perform pos_sales_close_private.assert_projection_allowed(new.business_date);
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end $$;
create trigger ledger_pos_daily_close_guard before insert or update or delete on public.ledger_transactions
for each row execute function pos_sales_close_private.transaction_guard();

create function pos_sales_close_private.movement_guard()
returns trigger language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_id bigint; v_date date;
begin
  if tg_op <> 'INSERT' then
    v_id := old.transaction_id;
    select business_date into v_date from public.ledger_transactions where id = v_id and source_type = 'pos_sales_daily_payment';
    if found then perform pos_sales_close_private.assert_projection_allowed(v_date); end if;
  end if;
  if tg_op <> 'DELETE' then
    v_id := new.transaction_id;
    select business_date into v_date from public.ledger_transactions where id = v_id and source_type = 'pos_sales_daily_payment';
    if found then perform pos_sales_close_private.assert_projection_allowed(v_date); end if;
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end $$;
create trigger ledger_pos_movement_daily_close_guard before insert or update or delete on public.ledger_movements
for each row execute function pos_sales_close_private.movement_guard();

create function pos_sales_close_private.project_business_day(p_rows jsonb,p_actor_user_id bigint)
returns jsonb language plpgsql security invoker set search_path=pg_catalog,public as $$
declare
  v_role text; v_item jsonb; v_date date; v_bucket text; v_amount numeric; v_fingerprint text;
  v_snapshot jsonb; v_key text; v_account_id bigint; v_category_id bigint; v_existing public.ledger_transactions%rowtype;
  v_transaction_id bigint; v_now timestamptz:=now(); v_created integer:=0; v_updated integer:=0; v_unchanged integer:=0; v_drift integer:=0;
  v_processed_dates date[]:=array[]::date[];
begin
  select lower(role::text) into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;
  if coalesce(v_role,'') not in ('owner','master','manager') then return jsonb_build_object('status','forbidden'); end if;
  if jsonb_typeof(p_rows)<>'array' then return jsonb_build_object('status','invalid_rows'); end if;
  -- Internal only: a validated close RPC owns the capability for this single day.
  if jsonb_array_length(p_rows) <> 4 or exists (
    select 1 from jsonb_array_elements(p_rows) r where not exists (
      select 1 from pos_sales_close_private.projection_permissions p
      where p.transaction_id = txid_current() and p.business_date = (r->>'businessDate')::date
        and p.actor_user_id = p_actor_user_id
    )
  ) or (select count(distinct r->>'businessDate') from jsonb_array_elements(p_rows) r) <> 1 then
    raise exception 'POS_SALES_INTERNAL_PROJECTION_FORBIDDEN' using errcode = '42501';
  end if;
  select id into v_category_id from public.ledger_categories where kind='income' and name='POS 매출' and is_active=true;
  if v_category_id is null then return jsonb_build_object('status','category_missing'); end if;

  for v_item in select value from jsonb_array_elements(p_rows) loop
    begin
      v_date:=(v_item->>'businessDate')::date; v_bucket:=v_item->>'bucket'; v_amount:=(v_item->>'amount')::numeric;
    exception when others then return jsonb_build_object('status','invalid_rows'); end;
    v_fingerprint:=nullif(v_item->>'fingerprint',''); v_snapshot:=v_item->'snapshot'; v_key:='pos:'||v_date::text||':'||v_bucket;
    if v_bucket not in ('cash','transfer','card','other') or v_amount<0 or v_amount<>trunc(v_amount) or v_fingerprint is null or jsonb_typeof(v_snapshot)<>'object' then return jsonb_build_object('status','invalid_rows'); end if;
    if not (v_date=any(v_processed_dates)) then v_processed_dates:=array_append(v_processed_dates,v_date); end if;
    perform pg_advisory_xact_lock(hashtext('ledger_pos_sync:'||v_key));
    select * into v_existing from public.ledger_transactions where source_type='pos_sales_daily_payment' and source_key=v_key for update;

    if v_existing.id is null and v_amount=0 then v_unchanged:=v_unchanged+1; continue; end if;
    if v_existing.id is null then
      select fund_account_id into v_account_id from public.ledger_payment_method_mappings
      where bucket=v_bucket and is_active=true and effective_from<=v_date and (effective_to is null or effective_to>=v_date)
      order by effective_from desc,id desc limit 1;
      if v_account_id is null then return jsonb_build_object('status','mapping_missing','businessDate',v_date,'bucket',v_bucket); end if;
      insert into public.ledger_transactions(operation_id,type,occurred_at,business_date,recognition_month,amount,category_id,status,source_type,source_key,source_snapshot,source_fingerprint,source_synced_at,memo,created_by,confirmed_by)
      values(gen_random_uuid(),'sales',(v_date+time '03:00') at time zone 'Asia/Ho_Chi_Minh',v_date,date_trunc('month',v_date)::date,v_amount,v_category_id,'confirmed','pos_sales_daily_payment',v_key,v_snapshot||jsonb_build_object('syncedAt',v_now),v_fingerprint,v_now,'POS '||v_bucket,p_actor_user_id,p_actor_user_id)
      returning id into v_transaction_id;
      insert into public.ledger_movements(transaction_id,fund_account_id,amount) values(v_transaction_id,v_account_id,v_amount);
      insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,after_snapshot,reason) values(p_actor_user_id,'pos_sync_created','transaction',v_transaction_id,(select to_jsonb(t) from public.ledger_transactions t where t.id=v_transaction_id),'POS automatic sync');
      v_created:=v_created+1;
    elsif v_existing.source_fingerprint=v_fingerprint and v_existing.status='confirmed' then
      update public.ledger_transactions set source_synced_at=v_now,updated_at=v_now where id=v_existing.id;
      v_unchanged:=v_unchanged+1;
    else
      v_drift:=v_drift+1;
      if v_amount=0 then
        update public.ledger_transactions set status='corrected',source_snapshot=v_snapshot||jsonb_build_object('syncedAt',v_now),source_fingerprint=v_fingerprint,source_synced_at=v_now,updated_at=v_now where id=v_existing.id;
      else
        update public.ledger_transactions set status='confirmed',amount=v_amount,recognition_month=date_trunc('month',v_date)::date,source_snapshot=v_snapshot||jsonb_build_object('syncedAt',v_now),source_fingerprint=v_fingerprint,source_synced_at=v_now,updated_at=v_now,confirmed_by=p_actor_user_id where id=v_existing.id;
        update public.ledger_movements set amount=v_amount where transaction_id=v_existing.id;
      end if;
      insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,before_snapshot,after_snapshot,reason) values(p_actor_user_id,'pos_sync_drift_updated','transaction',v_existing.id,to_jsonb(v_existing),(select to_jsonb(t) from public.ledger_transactions t where t.id=v_existing.id),'POS source drift');
      v_updated:=v_updated+1;
    end if;
  end loop;
  return jsonb_build_object('status','ok','processedBusinessDates',to_jsonb(v_processed_dates),'createdCount',v_created,'updatedCount',v_updated,'unchangedCount',v_unchanged,'driftCount',v_drift);
end $$;

create function public.sales_close_business_day_v1(
  p_business_date date, p_source_fingerprint text, p_source_snapshot jsonb, p_rows jsonb,
  p_actor_user_id bigint, p_close_method text default 'manual',
  p_manual_reclose boolean default false, p_sync_run_id bigint default null
) returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  v_role text; v_existing public.pos_sales_business_day_closures%rowtype;
  v_old_card jsonb; v_new_card jsonb;
  v_result jsonb; v_revision integer; v_id bigint; v_now timestamptz := now();
begin
  select lower(btrim(role::text)) into v_role from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master', 'manager')
    or (v_role = 'manager' and (p_close_method is distinct from 'manual' or p_manual_reclose is distinct from false)) then
    return jsonb_build_object('status', 'forbidden');
  end if;
  if p_business_date is null or p_close_method is null or p_close_method not in ('manual', 'automatic')
    or p_manual_reclose is null or (p_manual_reclose and p_close_method <> 'manual') then
    raise exception 'INVALID_POS_SALES_CLOSE_REQUEST' using errcode = '22023';
  end if;
  -- Same month key as ledger_close_month_v1; lock order: month, day, source,
  -- existing closure, bucket projection. Close and v3 use the same ordering.
  perform pg_advisory_xact_lock(hashtext('ledger_month_close:' || to_char(p_business_date, 'YYYY-MM')));
  perform pg_advisory_xact_lock(hashtext('pos_sales_business_day_close:' || p_business_date::text));
  if public.ledger_month_is_closed_v1(date_trunc('month', p_business_date)::date) then
    return jsonb_build_object('status', 'month_closed');
  end if;
  lock table public.pos_sales_receipts, public.pos_sales_receipt_payments in share mode;
  perform pos_sales_close_private.validate_source(p_business_date, p_source_fingerprint, p_source_snapshot, p_rows);
  if p_sync_run_id is not null and not exists (
    select 1 from public.pos_sales_sync_runs where id = p_sync_run_id and business_date = p_business_date and status = 'success'
  ) then raise exception 'POS_SALES_SUCCESSFUL_SYNC_RUN_REQUIRED' using errcode = '22023'; end if;

  select * into v_existing from public.pos_sales_business_day_closures
  where business_date = p_business_date order by revision desc limit 1 for update;
  if v_existing.id is not null and v_existing.source_fingerprint = p_source_fingerprint then
    return jsonb_build_object('status', 'already_closed', 'closureId', v_existing.id, 'revision', v_existing.revision);
  end if;
  if v_existing.id is not null and v_role = 'manager' then
    return jsonb_build_object('status', 'forbidden');
  end if;
  if v_existing.id is not null and not p_manual_reclose then
    return jsonb_build_object('status', 'source_changed_after_close', 'closureId', v_existing.id,
      'revision', v_existing.revision, 'closedFingerprint', v_existing.source_fingerprint, 'currentFingerprint', p_source_fingerprint);
  end if;

  if v_existing.id is not null then
    select r into v_old_card from jsonb_array_elements(v_existing.source_snapshot->'rows') r where r->>'bucket' = 'card';
    select r into v_new_card from jsonb_array_elements(p_rows) r where r->>'bucket' = 'card';
    if v_old_card is null or v_new_card is null then
      raise exception 'POS_SOURCE_SNAPSHOT_INCOMPLETE' using errcode = '22023';
    end if;
    if v_old_card->>'fingerprint' is distinct from v_new_card->>'fingerprint'
      or (v_old_card->>'amount')::numeric is distinct from (v_new_card->>'amount')::numeric then
      -- Card reconciliation also locks these POS transactions before allocating.
      -- Holding this row lock makes the settlement check/projection atomic.
      -- Preserve the legacy projector's advisory-key-before-row lock order.
      perform pg_advisory_xact_lock(hashtext('ledger_pos_sync:pos:' || p_business_date::text || ':card'));
      perform 1 from public.ledger_transactions
      where source_type = 'pos_sales_daily_payment' and business_date = p_business_date
        and source_key = 'pos:' || p_business_date::text || ':card'
      order by id for update;
      if exists (
        select 1 from public.ledger_card_reconciliation_lines l
        join public.ledger_card_reconciliations r on r.id = l.reconciliation_id
        join public.ledger_transactions t on t.id = l.pos_card_transaction_id
        where t.source_type = 'pos_sales_daily_payment' and t.business_date = p_business_date
          and t.source_key = 'pos:' || p_business_date::text || ':card'
          and r.status <> 'cancelled'
      ) then
        return jsonb_build_object('status', 'card_settlement_locked', 'closureId', v_existing.id, 'revision', v_existing.revision);
      end if;
    end if;
  end if;

  insert into pos_sales_close_private.projection_permissions values (txid_current(), p_business_date, p_actor_user_id);
  v_result := pos_sales_close_private.project_business_day(p_rows, p_actor_user_id);
  if v_result->>'status' is distinct from 'ok' or coalesce((v_result->>'closedMonth')::boolean, false) then
    -- v1 can return a failure after writing earlier buckets. Raising aborts the
    -- entire close transaction, including projection, audit and capability.
    raise exception 'POS_SALES_LEDGER_PROJECTION_FAILED: %', v_result using errcode = 'P0001';
  end if;
  -- Verify the actual projection, including the zero-amount corrected case.
  if exists (
    select 1 from jsonb_array_elements(p_rows) r
    left join public.ledger_transactions t on t.source_type = 'pos_sales_daily_payment'
      and t.source_key = 'pos:' || p_business_date::text || ':' || (r->>'bucket')
    where ((r->>'amount')::numeric > 0 and (t.id is null or t.status <> 'confirmed'
      or t.amount <> (r->>'amount')::numeric or t.source_fingerprint <> r->>'fingerprint'
      or (select coalesce(sum(m.amount), 0) from public.ledger_movements m where m.transaction_id = t.id) <> t.amount))
      or ((r->>'amount')::numeric = 0 and t.status = 'confirmed')
  ) then raise exception 'POS_SALES_LEDGER_PROJECTION_INCOMPLETE' using errcode = 'P0001'; end if;

  delete from pos_sales_close_private.projection_permissions where transaction_id = txid_current() and business_date = p_business_date;
  v_revision := coalesce(v_existing.revision, 0) + 1;
  insert into public.pos_sales_business_day_closures(business_date, revision, close_method, closed_at,
    closed_by, sync_run_id, source_fingerprint, source_snapshot, ledger_result_snapshot)
  values (p_business_date, v_revision, p_close_method, v_now, p_actor_user_id, p_sync_run_id,
    p_source_fingerprint, p_source_snapshot, v_result) returning id into v_id;
  insert into public.ledger_audit_logs(actor_user_id, action, entity_type, entity_id, after_snapshot, reason)
  values (p_actor_user_id, 'pos_sales_day_closed', 'pos_sales_day_closure', v_id,
    jsonb_build_object('businessDate', p_business_date, 'revision', v_revision,
      'previousClosureId', v_existing.id, 'sourceFingerprint', p_source_fingerprint, 'closeMethod', p_close_method),
    case when v_existing.id is null then 'Initial business day close' else 'Explicit manual reclose' end);
  return jsonb_build_object('status', case when v_existing.id is null then 'closed' else 'reclosed' end,
    'closureId', v_id, 'revision', v_revision, 'ledgerResult', v_result);
end $$;

create function public.ledger_sync_pos_sales_v3(p_rows jsonb, p_days jsonb, p_actor_user_id bigint)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  v_role text; v_day jsonb; v_date date; v_month date; v_rows jsonb; v_existing public.pos_sales_business_day_closures%rowtype;
  v_result jsonb; v_drift jsonb := '[]'::jsonb; v_created integer := 0; v_updated integer := 0;
  v_unchanged integer := 0; v_month_drift integer := 0; v_closed_month boolean := false;
begin
  select lower(btrim(role::text)) into v_role from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then return jsonb_build_object('status', 'forbidden'); end if;
  if jsonb_typeof(p_rows) is distinct from 'array' or jsonb_typeof(p_days) is distinct from 'array'
    or jsonb_array_length(p_days) = 0
    or (select count(distinct value->>'businessDate') from jsonb_array_elements(p_days)) <> jsonb_array_length(p_days)
    or exists (select 1 from jsonb_array_elements(p_rows) r where not exists
      (select 1 from jsonb_array_elements(p_days) d where d->>'businessDate' = r->>'businessDate')) then
    raise exception 'INVALID_POS_LEDGER_SOURCE' using errcode = '22023';
  end if;
  for v_month in select distinct date_trunc('month', (value->>'businessDate')::date)::date from jsonb_array_elements(p_days) order by 1 loop
    perform pg_advisory_xact_lock(hashtext('ledger_month_close:' || to_char(v_month, 'YYYY-MM')));
  end loop;
  for v_date in select (value->>'businessDate')::date from jsonb_array_elements(p_days) order by 1 loop
    if v_date is null then raise exception 'INVALID_POS_BUSINESS_DATE' using errcode = '22023'; end if;
    perform pg_advisory_xact_lock(hashtext('pos_sales_business_day_close:' || v_date::text));
  end loop;
  lock table public.pos_sales_receipts, public.pos_sales_receipt_payments in share mode;
  -- Validate every day before any projection; a stale or incomplete page must
  -- not leave a partially synchronized month.
  for v_day in select value from jsonb_array_elements(p_days) order by value->>'businessDate' loop
    v_date := (v_day->>'businessDate')::date;
    select coalesce(jsonb_agg(value order by ordinal), '[]'::jsonb) into v_rows
    from jsonb_array_elements(p_rows) with ordinality a(value, ordinal) where value->>'businessDate' = v_date::text;
    perform pos_sales_close_private.validate_source(v_date, v_day->>'sourceFingerprint', v_day->'sourceSnapshot', v_rows);
  end loop;
  for v_day in select value from jsonb_array_elements(p_days) order by value->>'businessDate' loop
    v_date := (v_day->>'businessDate')::date;
    v_closed_month := v_closed_month or public.ledger_month_is_closed_v1(date_trunc('month', v_date)::date);
    select * into v_existing from public.pos_sales_business_day_closures
    where business_date = v_date order by revision desc limit 1 for update;
    if v_existing.id is not null then
      if v_existing.source_fingerprint = v_day->>'sourceFingerprint' then v_unchanged := v_unchanged + 4;
      else v_drift := v_drift || jsonb_build_array(jsonb_build_object('businessDate', v_date,
        'status', 'source_changed_after_close', 'revision', v_existing.revision,
        'closedFingerprint', v_existing.source_fingerprint, 'currentFingerprint', v_day->>'sourceFingerprint')); end if;
      continue;
    end if;
    select jsonb_agg(value order by ordinal) into v_rows from jsonb_array_elements(p_rows) with ordinality a(value, ordinal)
    where value->>'businessDate' = v_date::text;
    v_result := public.ledger_sync_pos_sales_v2(v_rows, p_actor_user_id);
    if v_result->>'status' is distinct from 'ok' then
      raise exception 'POS_SALES_LEDGER_PROJECTION_FAILED: %', v_result using errcode = 'P0001';
    end if;
    v_created := v_created + coalesce((v_result->>'createdCount')::integer, 0);
    v_updated := v_updated + coalesce((v_result->>'updatedCount')::integer, 0);
    v_unchanged := v_unchanged + coalesce((v_result->>'unchangedCount')::integer, 0);
    v_month_drift := v_month_drift + coalesce((v_result->>'driftCount')::integer, 0);
  end loop;
  return jsonb_build_object('status', 'ok', 'createdCount', v_created, 'updatedCount', v_updated,
    'unchangedCount', v_unchanged, 'driftCount', v_month_drift + jsonb_array_length(v_drift),
    'dailyCloseDrift', v_drift, 'closedMonth', v_closed_month);
end $$;

create function pos_sales_close_private.ordered_object_json(p_value jsonb, p_keys text[])
returns text language sql immutable set search_path = pg_catalog, public as $$
  select '{' || string_agg(to_jsonb(key)::text || ':' || pos_sales_close_private.canonical_json(p_value->key), ',' order by ordinal) || '}'
  from unnest(p_keys) with ordinality a(key, ordinal)
$$;

-- Matches JSON.stringify of the original August bucket snapshot, including
-- its explicit field order. Whole-day fingerprints use sorted canonical JSON.
create function pos_sales_close_private.bucket_fingerprint(p_snapshot jsonb)
returns text language sql immutable set search_path = pg_catalog, public as $$
  select encode(sha256(convert_to(
    '{"businessDate":' || pos_sales_close_private.canonical_json(p_snapshot->'businessDate') ||
    ',"bucket":' || pos_sales_close_private.canonical_json(p_snapshot->'bucket') ||
    ',"receiptCount":' || pos_sales_close_private.canonical_json(p_snapshot->'receiptCount') ||
    ',"payments":[' || coalesce((
      select string_agg(pos_sales_close_private.ordered_object_json(value, array[
        'paymentId','receiptId','refNo','refDate','paymentMethod','paymentAmount',
        'receiptFinalAmount','receiptRevision','receiptUpdatedAt'
      ]), ',' order by ordinal)
      from jsonb_array_elements(p_snapshot->'payments') with ordinality a(value, ordinal)
    ), '') || ']}', 'UTF8')), 'hex')
$$;

-- Validation mirrors the shared Sales classifier, never trusting a supplied
-- bucket or amount. The TypeScript month/day loaders share one pure builder.
create function pos_sales_close_private.payment_bucket(p_type integer, p_name text, p_card text)
returns text language plpgsql immutable set search_path = pg_catalog, public as $$
declare
  -- ECMAScript String.trim whitespace, matching normalizePaymentName.
  v_trim text := array_to_string(array[chr(9),chr(10),chr(11),chr(12),chr(13),chr(32),chr(160),chr(5760),
    chr(8192),chr(8193),chr(8194),chr(8195),chr(8196),chr(8197),chr(8198),chr(8199),chr(8200),chr(8201),chr(8202),
    chr(8232),chr(8233),chr(8239),chr(8287),chr(12288),chr(65279)], '');
  v_name text := lower(btrim(coalesce(p_name, ''), v_trim));
  v_card text := lower(btrim(coalesce(p_card, ''), v_trim));
begin
  if v_name = 'tiền mặt' or v_card = 'tiền mặt' then return 'cash'; end if;
  if v_name = 'chuyển khoản' or v_card = 'chuyển khoản' then return 'transfer'; end if;
  if p_type = 2 or v_card <> '' or v_name like '%visa%' or v_name like '%master%'
    or v_name like '%card%' or v_card like '%visa%' or v_card like '%master%' or v_card like '%card%' then return 'card'; end if;
  if v_name in ('khác', 'khac') or v_card in ('khác', 'khac') then return 'other'; end if;
  return null;
end $$;

create function pos_sales_close_private.build_source(p_date date)
returns jsonb language plpgsql set search_path = pg_catalog, public set timezone = 'UTC' as $$
declare
  v_receipts jsonb; v_payments jsonb; v_rows jsonb := '[]'::jsonb; v_snapshot jsonb;
  v_detail jsonb; v_bucket_snapshot jsonb; v_bucket text; v_amount numeric;
  v_count integer; v_total numeric; v_payment_total numeric; v_totals jsonb := '{}'::jsonb;
begin
  if p_date is null then raise exception 'INVALID_POS_BUSINESS_DATE' using errcode = '22023'; end if;
  if exists (
    select 1 from public.pos_sales_receipts r where r.business_date = p_date and r.payment_status = 3 and r.is_canceled is distinct from true
      and (r.final_amount is null or r.final_amount < 0 or r.final_amount <> trunc(r.final_amount) or r.final_amount > 9007199254740991)
  ) then raise exception 'POS_SOURCE_INVALID_AMOUNT' using errcode = '22023'; end if;
  if exists (
    select 1 from public.pos_sales_receipt_payments p join public.pos_sales_receipts r on r.id = p.receipt_id
    where r.business_date = p_date and r.payment_status = 3 and r.is_canceled is distinct from true
      and (p.business_date is distinct from p_date or p.amount is null or p.amount < 0 or p.amount <> trunc(p.amount)
        or p.amount > 9007199254740991)
  ) then raise exception 'POS_SOURCE_SNAPSHOT_INCOMPLETE' using errcode = '22023'; end if;
  if exists (
    select 1 from public.pos_sales_receipts r
    where r.business_date = p_date and r.payment_status = 3 and r.is_canceled is distinct from true
      and r.final_amount <> coalesce((select sum(p.amount) from public.pos_sales_receipt_payments p where p.receipt_id = r.id), 0)
  ) then raise exception 'POS_PAYMENT_RECONCILIATION_MISMATCH' using errcode = '22023'; end if;
  if exists (
    select 1 from public.pos_sales_receipt_payments p join public.pos_sales_receipts r on r.id = p.receipt_id
    where r.business_date = p_date and r.payment_status = 3 and r.is_canceled is distinct from true
      and pos_sales_close_private.payment_bucket(p.payment_type, p.payment_name, p.card_name) is null
  ) then raise exception 'POS_PAYMENT_BUCKET_ALLOCATION_MISMATCH' using errcode = '22023'; end if;

  select count(*)::integer, coalesce(sum(final_amount), 0), coalesce(jsonb_agg(jsonb_build_object(
    'receiptId', id, 'refNo', ref_no, 'refDate', ref_date, 'finalAmount', final_amount,
    'revision', coalesce(revision, 0), 'updatedAt', updated_at
  ) order by id), '[]'::jsonb)
  into v_count, v_total, v_receipts from public.pos_sales_receipts
  where business_date = p_date and payment_status = 3 and is_canceled is distinct from true;

  select coalesce(sum(p.amount), 0), coalesce(jsonb_agg(jsonb_build_object(
    'paymentId', p.id, 'receiptId', p.receipt_id, 'businessDate', p.business_date,
    'paymentType', p.payment_type, 'paymentName', p.payment_name, 'cardName', p.card_name, 'amount', p.amount
  ) order by p.id), '[]'::jsonb)
  into v_payment_total, v_payments from public.pos_sales_receipt_payments p join public.pos_sales_receipts r on r.id = p.receipt_id
  where r.business_date = p_date and r.payment_status = 3 and r.is_canceled is distinct from true;

  foreach v_bucket in array array['cash', 'transfer', 'card', 'other'] loop
    select coalesce(sum(p.amount), 0), coalesce(jsonb_agg(jsonb_build_object(
      'paymentId', p.id, 'receiptId', p.receipt_id, 'refNo', r.ref_no, 'refDate', r.ref_date,
      'paymentMethod', coalesce(nullif(p.payment_name, ''), nullif(p.card_name, '')),
      'paymentAmount', p.amount, 'receiptFinalAmount', r.final_amount,
      'receiptRevision', coalesce(r.revision, 0), 'receiptUpdatedAt', r.updated_at
    ) order by p.id), '[]'::jsonb)
    into v_amount, v_detail from public.pos_sales_receipt_payments p join public.pos_sales_receipts r on r.id = p.receipt_id
    where r.business_date = p_date and r.payment_status = 3 and r.is_canceled is distinct from true
      and pos_sales_close_private.payment_bucket(p.payment_type, p.payment_name, p.card_name) = v_bucket;
    v_bucket_snapshot := jsonb_build_object('businessDate', p_date, 'bucket', v_bucket,
      'receiptCount', (select count(distinct value->>'receiptId') from jsonb_array_elements(v_detail)), 'payments', v_detail);
    v_rows := v_rows || jsonb_build_array(jsonb_build_object('businessDate', p_date, 'bucket', v_bucket,
      'amount', v_amount, 'fingerprint', pos_sales_close_private.bucket_fingerprint(v_bucket_snapshot), 'snapshot', v_bucket_snapshot));
    v_totals := v_totals || jsonb_build_object(v_bucket, v_amount);
  end loop;
  if v_total <> v_payment_total or v_total <> (select sum((value->>'amount')::numeric) from jsonb_array_elements(v_rows)) then
    raise exception 'POS_PAYMENT_BUCKET_ALLOCATION_MISMATCH' using errcode = '22023';
  end if;
  v_snapshot := jsonb_build_object('schemaVersion', 1, 'businessDate', p_date, 'receiptCount', v_count,
    'receiptTotal', v_total, 'paymentTotal', v_payment_total, 'totalsByBucket', v_totals,
    'receipts', v_receipts, 'payments', v_payments, 'rows', v_rows);
  return jsonb_build_object('sourceSnapshot', v_snapshot, 'rows', v_rows,
    'sourceFingerprint', encode(sha256(convert_to(pos_sales_close_private.canonical_json(v_snapshot), 'UTF8')), 'hex'));
end $$;

alter schema pos_sales_close_private owner to postgres;
alter table pos_sales_close_private.projection_permissions owner to postgres;
alter table public.pos_sales_business_day_closures owner to postgres;
alter function pos_sales_close_private.project_business_day(jsonb,bigint) owner to postgres;
alter function public.sales_close_business_day_v1(date,text,jsonb,jsonb,bigint,text,boolean,bigint) owner to postgres;
alter function public.ledger_sync_pos_sales_v3(jsonb,jsonb,bigint) owner to postgres;
revoke all on all functions in schema pos_sales_close_private from public, anon, authenticated, service_role;
revoke all on function public.sales_close_business_day_v1(date,text,jsonb,jsonb,bigint,text,boolean,bigint),
  public.ledger_sync_pos_sales_v3(jsonb,jsonb,bigint) from public, anon, authenticated, service_role;
grant execute on function public.sales_close_business_day_v1(date,text,jsonb,jsonb,bigint,text,boolean,bigint),
  public.ledger_sync_pos_sales_v3(jsonb,jsonb,bigint) to service_role;

comment on table public.pos_sales_business_day_closures is 'Immutable revision history of reconciled POS business-day closes. Latest revision is authoritative; matching fingerprints are no-ops.';
comment on function public.sales_close_business_day_v1(date,text,jsonb,jsonb,bigint,text,boolean,bigint) is 'Owner/master/manager initial manual close; owner/master manual reclose with card-settlement lock, never after month close.';
comment on function public.ledger_sync_pos_sales_v3(jsonb,jsonb,bigint) is 'Validated POS projection with daily-close no-op/drift protection and existing v2 month-close protection.';

commit;
