-- Recurring reserve allocation planning.
--
-- A reserve plan may carry a monthly rule ("set aside X on day D from month S to E").
-- A daily cron proposes one pending scheduled allocation per plan per month; an
-- owner/master then confirms it, which runs the EXISTING ledger_create_reserve_entry_v1
-- ('allocate'). Reserve entries never create ledger_transactions / ledger_movements and
-- never change a fund account's gross balance — only its available (earmarked) balance.
--
-- V1 scope: monthly frequency only (no column), manual confirm only (no auto-confirm
-- column). Auto-generation is opt-in per plan via recurring_auto_generate.

-- 1. Monthly rule columns on the plan (1:1 with the plan; kept off a separate table).
alter table public.ledger_reserve_plans
  add column recurring_monthly_amount numeric(16, 3) null
    check (recurring_monthly_amount is null
      or (recurring_monthly_amount > 0 and scale(recurring_monthly_amount) <= 3)),
  add column recurring_day smallint null
    check (recurring_day is null or (recurring_day between 1 and 31)),
  add column recurring_start_month date null
    check (recurring_start_month is null
      or recurring_start_month = date_trunc('month', recurring_start_month)::date),
  add column recurring_end_month date null
    check (recurring_end_month is null
      or recurring_end_month = date_trunc('month', recurring_end_month)::date),
  add column recurring_auto_generate boolean not null default false;

alter table public.ledger_reserve_plans
  add constraint ledger_reserve_plans_recurring_complete check (
    (recurring_monthly_amount is null and recurring_day is null
      and recurring_start_month is null and recurring_end_month is null
      and recurring_auto_generate = false)
    or (recurring_monthly_amount is not null and recurring_day is not null
      and recurring_start_month is not null)
  ),
  add constraint ledger_reserve_plans_recurring_period check (
    recurring_start_month is null or recurring_end_month is null
    or recurring_end_month >= recurring_start_month
  );

comment on column public.ledger_reserve_plans.recurring_monthly_amount is
  'Monthly amount to earmark. Null = no recurring rule. Frequency is always monthly in V1.';
comment on column public.ledger_reserve_plans.recurring_auto_generate is
  'When true the daily cron proposes a pending scheduled allocation each month. Never auto-confirms.';

-- 2. One proposed allocation per plan per month; owner/master confirms or skips it.
create table public.ledger_reserve_scheduled_allocations (
  id bigint generated by default as identity primary key,
  reserve_plan_id bigint not null references public.ledger_reserve_plans(id) on delete restrict,
  scheduled_month date not null
    check (scheduled_month = date_trunc('month', scheduled_month)::date),
  scheduled_date date not null,
  planned_amount numeric(16, 3) not null
    check (planned_amount > 0 and scale(planned_amount) <= 3),
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'skipped', 'superseded')),
  reserve_entry_id bigint null references public.ledger_reserve_entries(id) on delete restrict,
  rule_snapshot jsonb not null check (jsonb_typeof(rule_snapshot) = 'object'),
  resolved_by bigint null references public.users(id) on delete restrict,
  resolved_at timestamptz null,
  skip_reason text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ledger_reserve_sched_state check (
    (status = 'pending' and reserve_entry_id is null and resolved_by is null
      and resolved_at is null and skip_reason is null)
    or (status = 'confirmed' and reserve_entry_id is not null and resolved_by is not null
      and resolved_at is not null and skip_reason is null)
    or (status = 'skipped' and reserve_entry_id is null and resolved_by is not null
      and resolved_at is not null and length(btrim(skip_reason)) > 0)
    or (status = 'superseded' and resolved_at is not null)
  )
);

-- Final defense against duplicate proposals: one live row per plan-month.
create unique index ledger_reserve_sched_live_unique
  on public.ledger_reserve_scheduled_allocations(reserve_plan_id, scheduled_month)
  where status <> 'superseded';
create index ledger_reserve_sched_plan_month_idx
  on public.ledger_reserve_scheduled_allocations(reserve_plan_id, scheduled_month desc);
create index ledger_reserve_sched_status_idx
  on public.ledger_reserve_scheduled_allocations(status, scheduled_month desc);
create index ledger_reserve_sched_entry_idx
  on public.ledger_reserve_scheduled_allocations(reserve_entry_id)
  where reserve_entry_id is not null;

alter table public.ledger_reserve_scheduled_allocations enable row level security;
revoke all on table public.ledger_reserve_scheduled_allocations
  from public, anon, authenticated, service_role;
revoke all on sequence public.ledger_reserve_scheduled_allocations_id_seq
  from public, anon, authenticated, service_role;
grant select on table public.ledger_reserve_scheduled_allocations to service_role;

comment on table public.ledger_reserve_scheduled_allocations is
  'Proposed monthly reserve allocations. Confirming one runs ledger_create_reserve_entry_v1 '
  '(allocate); it never books a ledger transaction or movement.';

-- 3a. Set or clear a plan's monthly recurring rule.
create function public.ledger_set_reserve_recurring_v1(
  p_reserve_plan_id bigint,
  p_monthly_amount numeric,
  p_recurring_day smallint,
  p_start_month date,
  p_end_month date,
  p_auto_generate boolean,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_before public.ledger_reserve_plans%rowtype;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;

  select * into v_before
  from public.ledger_reserve_plans
  where id = p_reserve_plan_id and is_active = true
  for update;
  if v_before.id is null then
    return jsonb_build_object('status', 'not_found');
  end if;

  if p_monthly_amount is null then
    update public.ledger_reserve_plans
    set recurring_monthly_amount = null,
        recurring_day = null,
        recurring_start_month = null,
        recurring_end_month = null,
        recurring_auto_generate = false,
        updated_at = now()
    where id = p_reserve_plan_id;
    insert into public.ledger_audit_logs(
      actor_user_id, action, entity_type, entity_id, before_snapshot, after_snapshot, reason
    ) values (
      p_actor_user_id, 'reserve_recurring_set', 'reserve_plan', p_reserve_plan_id,
      to_jsonb(v_before),
      (select to_jsonb(plan) from public.ledger_reserve_plans plan where id = p_reserve_plan_id),
      'cleared'
    );
    return jsonb_build_object('status', 'cleared');
  end if;

  if p_monthly_amount <= 0 or scale(p_monthly_amount) > 3
    or p_recurring_day is null or p_recurring_day < 1 or p_recurring_day > 31
    or p_start_month is null or p_start_month <> date_trunc('month', p_start_month)::date
    or (p_end_month is not null
      and (p_end_month <> date_trunc('month', p_end_month)::date or p_end_month < p_start_month)) then
    return jsonb_build_object('status', 'invalid_input');
  end if;

  -- Auto-generation without a usable fund account would keep proposing allocations that
  -- can never be confirmed. Require the plan to be parked in a reserve-eligible account.
  if coalesce(p_auto_generate, false) = true and not exists (
    select 1 from public.ledger_fund_accounts account
    where account.id = v_before.fund_account_id
      and account.is_active = true
      and account.is_business_fund = true
      and account.type in ('cash', 'bank', 'personal_custody')
      and account.code <> 'card_clearing'
  ) then
    return jsonb_build_object('status', 'auto_generate_requires_fund_account');
  end if;

  update public.ledger_reserve_plans
  set recurring_monthly_amount = p_monthly_amount,
      recurring_day = p_recurring_day,
      recurring_start_month = p_start_month,
      recurring_end_month = p_end_month,
      recurring_auto_generate = coalesce(p_auto_generate, false),
      updated_at = now()
  where id = p_reserve_plan_id;

  insert into public.ledger_audit_logs(
    actor_user_id, action, entity_type, entity_id, before_snapshot, after_snapshot, reason
  ) values (
    p_actor_user_id, 'reserve_recurring_set', 'reserve_plan', p_reserve_plan_id,
    to_jsonb(v_before),
    (select to_jsonb(plan) from public.ledger_reserve_plans plan where id = p_reserve_plan_id),
    null
  );

  return jsonb_build_object('status', 'updated');
end
$$;

-- 3b. Propose pending scheduled allocations for a month.
--   p_require_auto_generate = true  -> cron: only plans with recurring_auto_generate = true,
--                                     and only once the recurring day has arrived.
--   p_require_auto_generate = false -> manual owner/master trigger: any active plan with a
--                                     valid recurring rule, regardless of the day / toggle.
create function public.ledger_generate_reserve_schedule_v1(
  p_month date,
  p_require_auto_generate boolean,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_plan public.ledger_reserve_plans%rowtype;
  v_today date := ((now() at time zone 'Asia/Ho_Chi_Minh') - interval '3 hours')::date;
  v_current numeric;
  v_manual numeric;
  v_planned numeric;
  v_sched_date date;
  v_occ_id bigint;
  v_created int := 0;
  v_skipped_existing int := 0;
  v_skipped_target int := 0;
  v_skipped_fulfilled int := 0;
  v_skipped_notdue int := 0;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;
  if p_month is null or p_month <> date_trunc('month', p_month)::date then
    return jsonb_build_object('status', 'invalid_month');
  end if;
  if public.ledger_month_is_closed_v1(p_month) then
    return jsonb_build_object('status', 'month_closed');
  end if;

  for v_plan in
    select * from public.ledger_reserve_plans
    where is_active = true
      and (coalesce(p_require_auto_generate, true) = false or recurring_auto_generate = true)
      and recurring_monthly_amount is not null
      and recurring_day is not null
      and recurring_start_month is not null
      and recurring_start_month <= p_month
      and (recurring_end_month is null or recurring_end_month >= p_month)
    order by id
  loop
    perform pg_advisory_xact_lock(
      hashtext('ledger_reserve_schedule:' || v_plan.id || ':' || to_char(p_month, 'YYYY-MM')));

    -- Due-day gate applies to the cron only. A manual request creates the current month's
    -- proposal even before the recurring day.
    if coalesce(p_require_auto_generate, true) = true
      and p_month = date_trunc('month', v_today)::date
      and extract(day from v_today)::int < v_plan.recurring_day then
      v_skipped_notdue := v_skipped_notdue + 1;
      continue;
    end if;

    if exists (
      select 1 from public.ledger_reserve_scheduled_allocations
      where reserve_plan_id = v_plan.id and scheduled_month = p_month and status <> 'superseded'
    ) then
      v_skipped_existing := v_skipped_existing + 1;
      continue;
    end if;

    select coalesce(sum(case entry_type
      when 'allocate' then amount when 'release' then -amount
      when 'consume' then -amount else amount end), 0)
    into v_current
    from public.ledger_reserve_entries
    where reserve_plan_id = v_plan.id;

    if v_current >= v_plan.target_amount then
      v_skipped_target := v_skipped_target + 1;
      continue;
    end if;

    -- Manual allocate = allocate entries booked in the month that are not linked to
    -- any scheduled allocation.
    select coalesce(sum(entry.amount), 0) into v_manual
    from public.ledger_reserve_entries entry
    where entry.reserve_plan_id = v_plan.id
      and entry.entry_type = 'allocate'
      and date_trunc('month',
        ((entry.occurred_at at time zone 'Asia/Ho_Chi_Minh') - interval '3 hours')::date)::date = p_month
      and not exists (
        select 1 from public.ledger_reserve_scheduled_allocations sched
        where sched.reserve_entry_id = entry.id
      );

    v_planned := least(
      v_plan.recurring_monthly_amount - v_manual,
      v_plan.target_amount - v_current
    );
    if v_planned is null or v_planned <= 0 then
      v_skipped_fulfilled := v_skipped_fulfilled + 1;
      continue;
    end if;
    v_planned := round(v_planned, 3);

    v_sched_date := least(
      (p_month + (v_plan.recurring_day - 1) * interval '1 day')::date,
      (p_month + interval '1 month' - interval '1 day')::date
    );

    insert into public.ledger_reserve_scheduled_allocations(
      reserve_plan_id, scheduled_month, scheduled_date, planned_amount, rule_snapshot
    ) values (
      v_plan.id, p_month, v_sched_date, v_planned,
      jsonb_build_object(
        'monthlyAmount', v_plan.recurring_monthly_amount,
        'recurringDay', v_plan.recurring_day,
        'startMonth', v_plan.recurring_start_month,
        'endMonth', v_plan.recurring_end_month,
        'targetAmount', v_plan.target_amount,
        'currentReserved', v_current,
        'manualThisMonth', v_manual
      )
    ) returning id into v_occ_id;

    insert into public.ledger_audit_logs(
      actor_user_id, action, entity_type, entity_id, after_snapshot, reason
    ) values (
      p_actor_user_id, 'reserve_schedule_generated', 'reserve_scheduled_allocation', v_occ_id,
      jsonb_build_object('reservePlanId', v_plan.id, 'scheduledMonth', p_month,
        'scheduledDate', v_sched_date, 'plannedAmount', v_planned),
      null
    );

    v_created := v_created + 1;
  end loop;

  return jsonb_build_object('status', 'ok',
    'mode', case when coalesce(p_require_auto_generate, true) then 'cron' else 'manual' end,
    'createdCount', v_created,
    'skippedExisting', v_skipped_existing,
    'skippedTarget', v_skipped_target,
    'skippedFulfilled', v_skipped_fulfilled,
    'skippedNotDue', v_skipped_notdue);
end
$$;

-- 3c. Confirm a pending proposal -> runs the existing reserve allocate entry.
create function public.ledger_confirm_reserve_schedule_v1(
  p_schedule_id bigint,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_occ public.ledger_reserve_scheduled_allocations%rowtype;
  v_plan public.ledger_reserve_plans%rowtype;
  v_now_month date;
  v_current numeric;
  v_manual numeric;
  v_monthly numeric;
  v_target_room numeric;
  v_monthly_room numeric;
  v_amount numeric;
  v_entry jsonb;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;

  select * into v_occ
  from public.ledger_reserve_scheduled_allocations
  where id = p_schedule_id
  for update;
  if v_occ.id is null then
    return jsonb_build_object('status', 'not_found');
  end if;
  if v_occ.status <> 'pending' then
    return jsonb_build_object('status', 'not_pending', 'currentStatus', v_occ.status);
  end if;

  select * into v_plan
  from public.ledger_reserve_plans
  where id = v_occ.reserve_plan_id
  for update;
  if v_plan.id is null or v_plan.is_active = false then
    return jsonb_build_object('status', 'invalid_plan');
  end if;

  -- The allocate entry is always booked now, in the current open ledger month.
  v_now_month := date_trunc('month',
    ((now() at time zone 'Asia/Ho_Chi_Minh') - interval '3 hours')::date)::date;
  if public.ledger_month_is_closed_v1(v_now_month) then
    return jsonb_build_object('status', 'current_month_closed');
  end if;

  select coalesce(sum(case entry_type
    when 'allocate' then amount when 'release' then -amount
    when 'consume' then -amount else amount end), 0)
  into v_current
  from public.ledger_reserve_entries
  where reserve_plan_id = v_plan.id;

  v_target_room := v_plan.target_amount - v_current;
  if v_target_room <= 0 then
    update public.ledger_reserve_scheduled_allocations
    set status = 'skipped', resolved_by = p_actor_user_id, resolved_at = now(),
        skip_reason = '목표 금액 달성', updated_at = now()
    where id = p_schedule_id;
    insert into public.ledger_audit_logs(
      actor_user_id, action, entity_type, entity_id, before_snapshot, after_snapshot, reason
    ) values (
      p_actor_user_id, 'reserve_schedule_skipped', 'reserve_scheduled_allocation', p_schedule_id,
      to_jsonb(v_occ), jsonb_build_object('status', 'skipped', 'autoReason', 'target_reached'),
      '목표 금액 달성'
    );
    return jsonb_build_object('status', 'target_reached');
  end if;

  v_monthly := coalesce(v_plan.recurring_monthly_amount,
    (v_occ.rule_snapshot->>'monthlyAmount')::numeric);
  select coalesce(sum(entry.amount), 0) into v_manual
  from public.ledger_reserve_entries entry
  where entry.reserve_plan_id = v_plan.id
    and entry.entry_type = 'allocate'
    and date_trunc('month',
      ((entry.occurred_at at time zone 'Asia/Ho_Chi_Minh') - interval '3 hours')::date)::date
      = v_occ.scheduled_month
    and not exists (
      select 1 from public.ledger_reserve_scheduled_allocations sched
      where sched.reserve_entry_id = entry.id
    );
  v_monthly_room := coalesce(v_monthly, v_occ.planned_amount) - v_manual;

  v_amount := least(v_occ.planned_amount, v_target_room, greatest(v_monthly_room, 0));
  if v_amount is null or v_amount <= 0 then
    update public.ledger_reserve_scheduled_allocations
    set status = 'skipped', resolved_by = p_actor_user_id, resolved_at = now(),
        skip_reason = '이번 달 수동 적립으로 충족', updated_at = now()
    where id = p_schedule_id;
    insert into public.ledger_audit_logs(
      actor_user_id, action, entity_type, entity_id, before_snapshot, after_snapshot, reason
    ) values (
      p_actor_user_id, 'reserve_schedule_skipped', 'reserve_scheduled_allocation', p_schedule_id,
      to_jsonb(v_occ),
      jsonb_build_object('status', 'skipped', 'autoReason', 'already_fulfilled', 'manualThisMonth', v_manual),
      '이번 달 수동 적립으로 충족'
    );
    return jsonb_build_object('status', 'already_fulfilled', 'manualThisMonth', v_manual);
  end if;
  v_amount := round(v_amount, 3);

  v_entry := public.ledger_create_reserve_entry_v1(
    v_plan.id, 'allocate', v_amount, now(),
    '정기 준비금 적립 ' || to_char(v_occ.scheduled_month, 'YYYY-MM'),
    p_actor_user_id
  );
  if coalesce(v_entry->>'status', '') <> 'created' then
    return v_entry;
  end if;

  update public.ledger_reserve_scheduled_allocations
  set status = 'confirmed',
      reserve_entry_id = (v_entry->>'reserveEntryId')::bigint,
      resolved_by = p_actor_user_id,
      resolved_at = now(),
      updated_at = now()
  where id = p_schedule_id;

  insert into public.ledger_audit_logs(
    actor_user_id, action, entity_type, entity_id, before_snapshot, after_snapshot, reason
  ) values (
    p_actor_user_id, 'reserve_schedule_confirmed', 'reserve_scheduled_allocation', p_schedule_id,
    to_jsonb(v_occ),
    jsonb_build_object('reservePlanId', v_plan.id, 'scheduledMonth', v_occ.scheduled_month,
      'plannedAmount', v_occ.planned_amount, 'confirmedAmount', v_amount,
      'reserveEntryId', (v_entry->>'reserveEntryId')::bigint),
    null
  );

  return jsonb_build_object('status', 'confirmed',
    'reserveEntryId', (v_entry->>'reserveEntryId')::bigint, 'amount', v_amount);
end
$$;

-- 3d. Skip a pending proposal for the month.
create function public.ledger_skip_reserve_schedule_v1(
  p_schedule_id bigint,
  p_reason text,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_occ public.ledger_reserve_scheduled_allocations%rowtype;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;
  if nullif(btrim(p_reason), '') is null then
    return jsonb_build_object('status', 'reason_required');
  end if;

  select * into v_occ
  from public.ledger_reserve_scheduled_allocations
  where id = p_schedule_id
  for update;
  if v_occ.id is null then
    return jsonb_build_object('status', 'not_found');
  end if;
  if v_occ.status <> 'pending' then
    return jsonb_build_object('status', 'not_pending', 'currentStatus', v_occ.status);
  end if;

  update public.ledger_reserve_scheduled_allocations
  set status = 'skipped', resolved_by = p_actor_user_id, resolved_at = now(),
      skip_reason = btrim(p_reason), updated_at = now()
  where id = p_schedule_id;
  insert into public.ledger_audit_logs(
    actor_user_id, action, entity_type, entity_id, before_snapshot, after_snapshot, reason
  ) values (
    p_actor_user_id, 'reserve_schedule_skipped', 'reserve_scheduled_allocation', p_schedule_id,
    to_jsonb(v_occ), jsonb_build_object('status', 'skipped'), btrim(p_reason)
  );
  return jsonb_build_object('status', 'skipped');
end
$$;

revoke all on function public.ledger_set_reserve_recurring_v1(bigint, numeric, smallint, date, date, boolean, bigint)
  from public, anon, authenticated;
revoke all on function public.ledger_generate_reserve_schedule_v1(date, boolean, bigint)
  from public, anon, authenticated;
revoke all on function public.ledger_confirm_reserve_schedule_v1(bigint, bigint)
  from public, anon, authenticated;
revoke all on function public.ledger_skip_reserve_schedule_v1(bigint, text, bigint)
  from public, anon, authenticated;
grant execute on function public.ledger_set_reserve_recurring_v1(bigint, numeric, smallint, date, date, boolean, bigint)
  to service_role;
grant execute on function public.ledger_generate_reserve_schedule_v1(date, boolean, bigint)
  to service_role;
grant execute on function public.ledger_confirm_reserve_schedule_v1(bigint, bigint)
  to service_role;
grant execute on function public.ledger_skip_reserve_schedule_v1(bigint, text, bigint)
  to service_role;
