create table public.business_partner_supplier_aliases (
  id bigint generated by default as identity primary key,
  supplier_name text not null check (length(btrim(supplier_name)) between 1 and 200),
  normalized_name text not null check (length(normalized_name) between 1 and 200),
  status text not null default 'pending' check (status in ('pending', 'linked', 'ignored')),
  business_partner_id bigint null references public.business_partners(id) on delete restrict,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  reviewed_at timestamptz null,
  reviewed_by bigint null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint business_partner_supplier_alias_status_policy check (
    (status = 'linked' and business_partner_id is not null and reviewed_at is not null and reviewed_by is not null)
    or (status = 'ignored' and business_partner_id is null and reviewed_at is not null and reviewed_by is not null)
    or (status = 'pending' and business_partner_id is null and reviewed_at is null and reviewed_by is null)
  )
);

create unique index business_partner_supplier_aliases_normalized_unique
  on public.business_partner_supplier_aliases (normalized_name);
create index business_partner_supplier_aliases_review_idx
  on public.business_partner_supplier_aliases (status, last_seen_at desc, id desc);
create index business_partner_supplier_aliases_partner_idx
  on public.business_partner_supplier_aliases (business_partner_id)
  where business_partner_id is not null;

alter table public.inventory
  add column supplier_partner_id bigint null
  references public.business_partners(id) on delete restrict;
create index inventory_supplier_partner_id_idx
  on public.inventory (supplier_partner_id, is_active, id);
create index inventory_supplier_normalized_idx
  on public.inventory (lower(btrim(supplier)))
  where supplier is not null and btrim(supplier) <> '';

create table public.business_partner_supplier_alias_audit_logs (
  id bigint generated by default as identity primary key,
  supplier_alias_id bigint not null references public.business_partner_supplier_aliases(id) on delete restrict,
  actor_user_id bigint not null references public.users(id) on delete restrict,
  action text not null check (action in ('candidate_created','candidate_linked_new_partner','candidate_linked_existing_partner','candidate_ignored','candidate_reopened')),
  before_snapshot jsonb null check (before_snapshot is null or jsonb_typeof(before_snapshot) = 'object'),
  after_snapshot jsonb null check (after_snapshot is null or jsonb_typeof(after_snapshot) = 'object'),
  created_at timestamptz not null default now()
);
create index business_partner_supplier_alias_audit_alias_idx
  on public.business_partner_supplier_alias_audit_logs (supplier_alias_id, created_at desc, id desc);

insert into public.business_partner_supplier_aliases(supplier_name, normalized_name)
select min(btrim(i.supplier)), lower(btrim(i.supplier))
from public.inventory i
where i.supplier is not null and btrim(i.supplier) <> ''
group by lower(btrim(i.supplier))
on conflict(normalized_name) do nothing;

alter table public.business_partner_supplier_aliases enable row level security;
alter table public.business_partner_supplier_alias_audit_logs enable row level security;

revoke all on table public.business_partner_supplier_aliases, public.business_partner_supplier_alias_audit_logs
  from public, anon, authenticated, service_role;
revoke all on sequence public.business_partner_supplier_aliases_id_seq, public.business_partner_supplier_alias_audit_logs_id_seq
  from public, anon, authenticated, service_role;
grant select on table public.business_partner_supplier_aliases, public.business_partner_supplier_alias_audit_logs
  to service_role;

create function public.business_partner_resolve_inventory_supplier_v1(
  p_supplier_name text,
  p_supplier_partner_id bigint,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_actor_exists boolean;
  v_name text := nullif(btrim(p_supplier_name), '');
  v_normalized text;
  v_partner public.business_partners%rowtype;
  v_alias public.business_partner_supplier_aliases%rowtype;
begin
  select exists(
    select 1 from public.users
    where id = p_actor_user_id and is_active = true and app_login_enabled = true
  ) into v_actor_exists;
  if not v_actor_exists then return jsonb_build_object('status', 'forbidden'); end if;

  if p_supplier_partner_id is not null then
    select * into v_partner from public.business_partners
    where id = p_supplier_partner_id and is_active = true;
    if not found then return jsonb_build_object('status', 'invalid_partner'); end if;
    return jsonb_build_object('status', 'resolved', 'supplierName', v_partner.name, 'supplierPartnerId', v_partner.id);
  end if;

  if v_name is null then
    return jsonb_build_object('status', 'resolved', 'supplierName', null, 'supplierPartnerId', null);
  end if;
  v_normalized := lower(v_name);

  select * into v_partner from public.business_partners
  where lower(btrim(name)) = v_normalized and is_active = true;
  if found then
    return jsonb_build_object(
      'status', 'resolved',
      'supplierName', v_partner.name,
      'supplierPartnerId', v_partner.id
    );
  end if;

  select * into v_alias from public.business_partner_supplier_aliases
  where normalized_name = v_normalized for update;
  if found then
    update public.business_partner_supplier_aliases
      set last_seen_at = now(), updated_at = now()
      where id = v_alias.id;
    if v_alias.status = 'linked' then
      select * into v_partner from public.business_partners
      where id = v_alias.business_partner_id and is_active = true;
      if found then
        return jsonb_build_object('status', 'resolved', 'supplierName', v_partner.name, 'supplierPartnerId', v_partner.id, 'supplierAliasId', v_alias.id, 'aliasStatus', 'linked');
      end if;
    end if;
    return jsonb_build_object('status', 'resolved', 'supplierName', v_alias.supplier_name, 'supplierPartnerId', null, 'supplierAliasId', v_alias.id, 'aliasStatus', v_alias.status);
  end if;

  insert into public.business_partner_supplier_aliases(supplier_name, normalized_name)
  values(v_name, v_normalized) returning * into v_alias;
  insert into public.business_partner_supplier_alias_audit_logs(supplier_alias_id, actor_user_id, action, after_snapshot)
  values(v_alias.id, p_actor_user_id, 'candidate_created', to_jsonb(v_alias));
  return jsonb_build_object('status', 'resolved', 'supplierName', v_alias.supplier_name, 'supplierPartnerId', null, 'supplierAliasId', v_alias.id, 'aliasStatus', 'pending');
exception
  when unique_violation then
    select * into v_alias from public.business_partner_supplier_aliases where normalized_name = v_normalized;
    update public.business_partner_supplier_aliases set last_seen_at = now(), updated_at = now() where id = v_alias.id;
    if v_alias.status = 'linked' then
      select * into v_partner from public.business_partners where id = v_alias.business_partner_id and is_active = true;
      if found then
        return jsonb_build_object('status', 'resolved', 'supplierName', v_partner.name, 'supplierPartnerId', v_partner.id, 'supplierAliasId', v_alias.id, 'aliasStatus', 'linked');
      end if;
    end if;
    return jsonb_build_object('status', 'resolved', 'supplierName', v_alias.supplier_name, 'supplierPartnerId', null, 'supplierAliasId', v_alias.id, 'aliasStatus', v_alias.status);
end;
$$;

create function public.business_partner_review_supplier_alias_v1(
  p_alias_id bigint,
  p_action text,
  p_existing_partner_id bigint,
  p_name text,
  p_partner_type text,
  p_payment_mode text,
  p_default_payment_term_days integer,
  p_phone text,
  p_contact_name text,
  p_memo text,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_alias public.business_partner_supplier_aliases%rowtype;
  v_before jsonb;
  v_partner_id bigint;
  v_audit_action text;
  v_inventory_count integer := 0;
begin
  select lower(role::text) into v_role from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then return jsonb_build_object('status', 'forbidden'); end if;

  select * into v_alias from public.business_partner_supplier_aliases where id = p_alias_id for update;
  if not found then return jsonb_build_object('status', 'not_found'); end if;
  v_before := to_jsonb(v_alias);

  if p_action = 'create_partner' then
    if v_alias.status <> 'pending' then return jsonb_build_object('status', 'invalid_state'); end if;
    insert into public.business_partners(name, partner_type, payment_mode, default_payment_term_days, phone, contact_name, memo, is_active)
    values(btrim(p_name), btrim(p_partner_type), p_payment_mode, p_default_payment_term_days, nullif(btrim(p_phone), ''), nullif(btrim(p_contact_name), ''), nullif(btrim(p_memo), ''), true)
    returning id into v_partner_id;
    insert into public.business_partner_audit_logs(business_partner_id, actor_user_id, action, after_snapshot)
    values(v_partner_id, p_actor_user_id, 'created', (select to_jsonb(p) from public.business_partners p where p.id = v_partner_id));
    v_audit_action := 'candidate_linked_new_partner';
  elsif p_action = 'link_existing' then
    if v_alias.status <> 'pending' then return jsonb_build_object('status', 'invalid_state'); end if;
    select id into v_partner_id from public.business_partners where id = p_existing_partner_id and is_active = true;
    if v_partner_id is null then return jsonb_build_object('status', 'invalid_partner'); end if;
    v_audit_action := 'candidate_linked_existing_partner';
  elsif p_action = 'ignore' then
    if v_alias.status <> 'pending' then return jsonb_build_object('status', 'invalid_state'); end if;
    update public.business_partner_supplier_aliases set status='ignored', business_partner_id=null, reviewed_at=now(), reviewed_by=p_actor_user_id, updated_at=now() where id=p_alias_id returning * into v_alias;
    update public.inventory set supplier_partner_id=null where lower(btrim(supplier))=v_alias.normalized_name and supplier_partner_id is not null;
    v_audit_action := 'candidate_ignored';
  elsif p_action = 'reopen' then
    if v_alias.status <> 'ignored' then return jsonb_build_object('status', 'invalid_state'); end if;
    update public.business_partner_supplier_aliases set status='pending', business_partner_id=null, reviewed_at=null, reviewed_by=null, updated_at=now() where id=p_alias_id returning * into v_alias;
    v_audit_action := 'candidate_reopened';
  else
    return jsonb_build_object('status', 'invalid_action');
  end if;

  if p_action in ('create_partner','link_existing') then
    update public.business_partner_supplier_aliases set status='linked', business_partner_id=v_partner_id, reviewed_at=now(), reviewed_by=p_actor_user_id, updated_at=now() where id=p_alias_id returning * into v_alias;
    update public.inventory set supplier_partner_id=v_partner_id where lower(btrim(supplier))=v_alias.normalized_name and supplier_partner_id is null;
    get diagnostics v_inventory_count = row_count;
  end if;

  insert into public.business_partner_supplier_alias_audit_logs(supplier_alias_id, actor_user_id, action, before_snapshot, after_snapshot)
  values(p_alias_id, p_actor_user_id, v_audit_action, v_before, to_jsonb(v_alias));
  return jsonb_build_object('status', 'reviewed', 'partnerId', v_partner_id, 'inventoryLinkedCount', v_inventory_count);
exception
  when unique_violation then return jsonb_build_object('status', 'duplicate_name');
  when check_violation or foreign_key_violation or not_null_violation then return jsonb_build_object('status', 'invalid_input');
end;
$$;

alter function public.business_partner_resolve_inventory_supplier_v1(text,bigint,bigint) owner to postgres;
alter function public.business_partner_review_supplier_alias_v1(bigint,text,bigint,text,text,text,integer,text,text,text,bigint) owner to postgres;
revoke all on function public.business_partner_resolve_inventory_supplier_v1(text,bigint,bigint) from public, anon, authenticated;
revoke all on function public.business_partner_review_supplier_alias_v1(bigint,text,bigint,text,text,text,integer,text,text,text,bigint) from public, anon, authenticated;
grant execute on function public.business_partner_resolve_inventory_supplier_v1(text,bigint,bigint) to service_role;
grant execute on function public.business_partner_review_supplier_alias_v1(bigint,text,bigint,text,text,text,integer,text,text,text,bigint) to service_role;

comment on table public.business_partner_supplier_aliases is 'Observed Inventory supplier names awaiting administrator normalization.';
comment on column public.inventory.supplier_partner_id is 'Optional canonical Business Partner; supplier remains the historical display snapshot.';
