-- Inventory's existing monthly report preserves three decimal places for
-- quantity * purchase price. Extend ledger money columns without changing
-- the manual/POS validation policies in their RPCs.
alter table public.ledger_transactions drop constraint ledger_transactions_amount_check;
alter table public.ledger_transactions alter column amount type numeric(16,3);
alter table public.ledger_transactions add constraint ledger_transactions_amount_check check(amount>0);
alter table public.ledger_movements drop constraint ledger_movements_amount_check;
alter table public.ledger_movements alter column amount type numeric(16,3);
alter table public.ledger_movements add constraint ledger_movements_amount_check check(amount<>0);

create table public.ledger_inventory_category_mappings(
  id bigint generated by default as identity primary key,
  inventory_category text not null check(length(btrim(inventory_category))>0),
  ledger_category_id bigint not null references public.ledger_categories(id) on delete restrict,
  is_active boolean not null default true,created_at timestamptz not null default now(),
  constraint ledger_inventory_category_mapping_unique unique(inventory_category)
);
create index ledger_inventory_category_mappings_category_idx on public.ledger_inventory_category_mappings(ledger_category_id);

create table public.ledger_supplier_party_mappings(
  id bigint generated by default as identity primary key,
  supplier_name text not null check(length(btrim(supplier_name))>0),
  party_id bigint not null references public.ledger_parties(id) on delete restrict,
  is_active boolean not null default true,created_at timestamptz not null default now(),
  constraint ledger_supplier_party_mapping_unique unique(supplier_name)
);
create index ledger_supplier_party_mappings_party_idx on public.ledger_supplier_party_mappings(party_id);

create table public.ledger_candidates(
  id bigint generated by default as identity primary key,
  candidate_type text not null check(candidate_type in('inventory_purchase')),
  source_type text not null check(source_type in('inventory_purchase_log')),
  source_key text not null,
  business_date date not null,
  proposed_amount numeric(16,3) not null check(proposed_amount>0),
  proposed_category_id bigint null references public.ledger_categories(id) on delete restrict,
  proposed_party_id bigint null references public.ledger_parties(id) on delete restrict,
  proposed_recognition_month date not null check(proposed_recognition_month=date_trunc('month',proposed_recognition_month)::date),
  source_snapshot jsonb not null check(jsonb_typeof(source_snapshot)='object'),
  source_fingerprint text not null check(length(source_fingerprint)=64),
  status text not null default 'pending' check(status in('pending','confirmed','dismissed','superseded')),
  resolved_transaction_id bigint null references public.ledger_transactions(id) on delete restrict,
  resolved_by bigint null references public.users(id) on delete restrict,
  resolved_at timestamptz null,
  dismissal_reason text null,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  constraint ledger_candidate_resolution_state check(
    (status='pending' and resolved_transaction_id is null and resolved_by is null and resolved_at is null and dismissal_reason is null)
    or(status='confirmed' and resolved_transaction_id is not null and resolved_by is not null and resolved_at is not null and dismissal_reason is null)
    or(status='dismissed' and resolved_transaction_id is null and resolved_by is not null and resolved_at is not null and length(btrim(dismissal_reason))>0)
    or(status='superseded' and resolved_transaction_id is null and resolved_by is null and resolved_at is not null)
  )
);
create unique index ledger_candidates_pending_source_unique on public.ledger_candidates(source_type,source_key) where status='pending';
create index ledger_candidates_filter_idx on public.ledger_candidates(candidate_type,status,business_date desc,id desc);
create index ledger_candidates_category_idx on public.ledger_candidates(proposed_category_id);
create index ledger_candidates_party_idx on public.ledger_candidates(proposed_party_id);
create index ledger_candidates_transaction_idx on public.ledger_candidates(resolved_transaction_id);
create index ledger_candidates_resolved_by_idx on public.ledger_candidates(resolved_by);
create index ledger_candidates_created_at_idx on public.ledger_candidates(created_at desc);

create table public.ledger_payables(
  id bigint generated by default as identity primary key,
  expense_transaction_id bigint not null unique references public.ledger_transactions(id) on delete restrict,
  party_id bigint not null references public.ledger_parties(id) on delete restrict,
  original_amount numeric(16,3) not null check(original_amount>0),due_date date null,
  status text not null default 'unpaid' check(status in('unpaid','partially_paid','paid','cancelled')),
  created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index ledger_payables_party_idx on public.ledger_payables(party_id);
create index ledger_payables_status_idx on public.ledger_payables(status,created_at desc);

create table public.ledger_payable_allocations(
  id bigint generated by default as identity primary key,
  payable_id bigint not null references public.ledger_payables(id) on delete restrict,
  payment_transaction_id bigint not null references public.ledger_transactions(id) on delete restrict,
  allocated_amount numeric(16,3) not null check(allocated_amount>0),created_at timestamptz not null default now(),
  constraint ledger_payable_allocation_pair_unique unique(payable_id,payment_transaction_id)
);
create index ledger_payable_allocations_payment_idx on public.ledger_payable_allocations(payment_transaction_id);

alter table public.ledger_inventory_category_mappings enable row level security;
alter table public.ledger_supplier_party_mappings enable row level security;
alter table public.ledger_candidates enable row level security;
alter table public.ledger_payables enable row level security;
alter table public.ledger_payable_allocations enable row level security;
revoke all on table public.ledger_inventory_category_mappings,public.ledger_supplier_party_mappings,public.ledger_candidates,public.ledger_payables,public.ledger_payable_allocations from public,anon,authenticated,service_role;
revoke all on sequence public.ledger_inventory_category_mappings_id_seq,public.ledger_supplier_party_mappings_id_seq,public.ledger_candidates_id_seq,public.ledger_payables_id_seq,public.ledger_payable_allocations_id_seq from public,anon,authenticated,service_role;
grant select on table public.ledger_inventory_category_mappings,public.ledger_supplier_party_mappings,public.ledger_candidates,public.ledger_payables,public.ledger_payable_allocations to service_role;

create or replace function public.ledger_sync_inventory_candidates_v1(p_rows jsonb,p_actor_user_id bigint)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_role text;v_item jsonb;v_key text;v_fingerprint text;v_snapshot jsonb;v_date date;v_amount numeric;v_pending public.ledger_candidates%rowtype;v_latest public.ledger_candidates%rowtype;v_category_id bigint;v_party_id bigint;v_scanned integer:=0;v_created integer:=0;v_unchanged integer:=0;v_superseded integer:=0;
begin
 select lower(role::text) into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;
 if coalesce(v_role,'') not in('owner','master') then return jsonb_build_object('status','forbidden');end if;
 if jsonb_typeof(p_rows)<>'array' then return jsonb_build_object('status','invalid_rows');end if;
 for v_item in select value from jsonb_array_elements(p_rows) loop
  v_scanned:=v_scanned+1;
  begin v_key:=v_item->>'sourceKey';v_fingerprint:=v_item->>'fingerprint';v_snapshot:=v_item->'snapshot';v_date:=(v_item->>'businessDate')::date;v_amount:=(v_item->>'amount')::numeric;exception when others then return jsonb_build_object('status','invalid_rows');end;
 if v_key!~'^inventory-log:[0-9]+$' or length(v_fingerprint)<>64 or jsonb_typeof(v_snapshot)<>'object' or v_amount<=0 then return jsonb_build_object('status','invalid_rows');end if;
  perform pg_advisory_xact_lock(hashtext('ledger_inventory_candidate:'||v_key));
  v_latest:=null;v_pending:=null;v_category_id:=null;v_party_id:=null;
  select * into v_latest from public.ledger_candidates where source_type='inventory_purchase_log' and source_key=v_key order by id desc limit 1 for update;
  if v_latest.status='confirmed' or v_latest.status='dismissed' then v_unchanged:=v_unchanged+1;continue;end if;
  select * into v_pending from public.ledger_candidates where source_type='inventory_purchase_log' and source_key=v_key and status='pending' for update;
  if v_pending.id is not null and v_pending.source_fingerprint=v_fingerprint then v_unchanged:=v_unchanged+1;continue;end if;
  if v_pending.id is not null then update public.ledger_candidates set status='superseded',resolved_at=now(),updated_at=now() where id=v_pending.id;v_superseded:=v_superseded+1;end if;
  select ledger_category_id into v_category_id from public.ledger_inventory_category_mappings where is_active=true and lower(btrim(inventory_category))=lower(btrim(v_snapshot->>'category')) limit 1;
  select party_id into v_party_id from public.ledger_supplier_party_mappings where is_active=true and lower(btrim(supplier_name))=lower(btrim(v_snapshot->>'supplier')) limit 1;
  insert into public.ledger_candidates(candidate_type,source_type,source_key,business_date,proposed_amount,proposed_category_id,proposed_party_id,proposed_recognition_month,source_snapshot,source_fingerprint)
  values('inventory_purchase','inventory_purchase_log',v_key,v_date,v_amount,v_category_id,v_party_id,date_trunc('month',v_date)::date,v_snapshot,v_fingerprint);v_created:=v_created+1;
 end loop;
 return jsonb_build_object('status','ok','scannedLogs',v_scanned,'createdCount',v_created,'unchangedCount',v_unchanged,'supersededCount',v_superseded);
end $$;

create or replace function public.ledger_resolve_inventory_candidate_v1(p_candidate_id bigint,p_resolution text,p_category_id bigint,p_party_id bigint,p_fund_account_id bigint,p_due_date date,p_memo text,p_reason text,p_actor_user_id bigint)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_role text;v_candidate public.ledger_candidates%rowtype;v_transaction_id bigint;v_payable_id bigint;v_operation uuid:=gen_random_uuid();
begin
 select lower(role::text) into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;if coalesce(v_role,'') not in('owner','master') then return jsonb_build_object('status','forbidden');end if;
 select * into v_candidate from public.ledger_candidates where id=p_candidate_id for update;if v_candidate.id is null then return jsonb_build_object('status','not_found');end if;if v_candidate.status<>'pending' then return jsonb_build_object('status','already_resolved');end if;
 if p_resolution='dismiss' then if nullif(btrim(p_reason),'') is null then return jsonb_build_object('status','reason_required');end if;update public.ledger_candidates set status='dismissed',resolved_by=p_actor_user_id,resolved_at=now(),dismissal_reason=btrim(p_reason),updated_at=now() where id=p_candidate_id;insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,before_snapshot,after_snapshot,reason)values(p_actor_user_id,'candidate_dismissed','candidate',p_candidate_id,to_jsonb(v_candidate),(select to_jsonb(c) from public.ledger_candidates c where c.id=p_candidate_id),btrim(p_reason));return jsonb_build_object('status','dismissed');end if;
 if p_resolution not in('immediate','payable') then return jsonb_build_object('status','invalid_resolution');end if;
 if not exists(select 1 from public.ledger_categories where id=p_category_id and kind='expense' and is_active=true) then return jsonb_build_object('status','invalid_category');end if;
 if p_resolution='immediate' and not exists(select 1 from public.ledger_fund_accounts where id=p_fund_account_id and is_active=true) then return jsonb_build_object('status','invalid_account');end if;
 if p_resolution='payable' and (p_party_id is null or not exists(select 1 from public.ledger_parties where id=p_party_id and is_active=true)) then return jsonb_build_object('status','party_required');end if;
 insert into public.ledger_transactions(operation_id,type,occurred_at,business_date,recognition_month,amount,category_id,party_id,status,source_type,source_key,source_snapshot,source_fingerprint,source_synced_at,memo,created_by,confirmed_by)
 values(v_operation,'expense',(v_candidate.business_date+time '03:00') at time zone 'Asia/Ho_Chi_Minh',v_candidate.business_date,v_candidate.proposed_recognition_month,v_candidate.proposed_amount,p_category_id,p_party_id,'confirmed','inventory_purchase_candidate','candidate:'||v_candidate.id,v_candidate.source_snapshot,v_candidate.source_fingerprint,now(),nullif(btrim(p_memo),''),p_actor_user_id,p_actor_user_id)returning id into v_transaction_id;
 if p_resolution='immediate' then insert into public.ledger_movements(transaction_id,fund_account_id,amount)values(v_transaction_id,p_fund_account_id,-v_candidate.proposed_amount);else insert into public.ledger_payables(expense_transaction_id,party_id,original_amount,due_date)values(v_transaction_id,p_party_id,v_candidate.proposed_amount,p_due_date)returning id into v_payable_id;end if;
 update public.ledger_candidates set status='confirmed',resolved_transaction_id=v_transaction_id,resolved_by=p_actor_user_id,resolved_at=now(),updated_at=now() where id=p_candidate_id;
 insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,before_snapshot,after_snapshot,reason)values(p_actor_user_id,case when p_resolution='immediate' then 'candidate_confirmed_immediate' else 'candidate_confirmed_payable' end,'candidate',p_candidate_id,to_jsonb(v_candidate),(select to_jsonb(c) from public.ledger_candidates c where c.id=p_candidate_id),nullif(btrim(p_memo),''));
 return jsonb_build_object('status','confirmed','transactionId',v_transaction_id,'payableId',v_payable_id);
exception when unique_violation then return jsonb_build_object('status','already_resolved');
end $$;

revoke all on function public.ledger_sync_inventory_candidates_v1(jsonb,bigint) from public,anon,authenticated;
revoke all on function public.ledger_resolve_inventory_candidate_v1(bigint,text,bigint,bigint,bigint,date,text,text,bigint) from public,anon,authenticated;
grant execute on function public.ledger_sync_inventory_candidates_v1(jsonb,bigint) to service_role;
grant execute on function public.ledger_resolve_inventory_candidate_v1(bigint,text,bigint,bigint,bigint,date,text,text,bigint) to service_role;
