alter table public.payroll_contract_versions
  add column fixed_raise_amount numeric(16,0) not null default 0,
  add constraint payroll_contract_fixed_raise_nonnegative check (fixed_raise_amount >= 0),
  add constraint payroll_contract_monthly_fixed_raise_only check (pay_type = 'monthly' or fixed_raise_amount = 0);

alter table public.payroll_runs
  add column force_finalized boolean not null default false,
  add column finalized_actor_role text null,
  add column force_finalize_reason text null,
  add column force_finalize_snapshot jsonb null,
  add constraint payroll_run_finalized_actor_role check (finalized_actor_role is null or finalized_actor_role in ('owner','master')),
  add constraint payroll_run_force_finalize_audit check (
    (force_finalized = false and force_finalize_reason is null and force_finalize_snapshot is null)
    or (
      force_finalized = true
      and finalized_by is not null
      and finalized_at is not null
      and finalized_actor_role in ('owner','master')
      and length(btrim(force_finalize_reason)) > 0
      and jsonb_typeof(force_finalize_snapshot) = 'object'
    )
  );

create table public.payroll_monthly_adjustments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  payroll_month date not null check (payroll_month = date_trunc('month', payroll_month)::date),
  kind text not null check (kind in ('incentive', 'penalty')),
  category text not null check (category in ('sales','performance','service','late','early_leave','absence','damage','discipline','manual','other')),
  amount numeric(16,0) not null check (amount >= 1 and amount = trunc(amount)),
  business_date date not null,
  reason text not null check (length(btrim(reason)) > 0),
  note text null,
  source_type text not null default 'manual' check (source_type = 'manual'),
  source_key text null,
  created_by bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  cancelled_at timestamptz null,
  cancelled_by bigint null references public.users(id) on delete restrict,
  cancellation_reason text null,
  constraint payroll_adjustment_business_month check (date_trunc('month', business_date)::date = payroll_month),
  constraint payroll_adjustment_cancel_audit check (
    (cancelled_at is null and cancelled_by is null and cancellation_reason is null)
    or (cancelled_at is not null and cancelled_by is not null and length(btrim(cancellation_reason)) > 0)
  )
);

create index payroll_monthly_adjustments_month_user_idx
  on public.payroll_monthly_adjustments(payroll_month, user_id, created_at desc);
create unique index payroll_monthly_adjustments_source_unique
  on public.payroll_monthly_adjustments(source_type, source_key)
  where source_key is not null;

alter table public.payroll_monthly_adjustments enable row level security;
revoke all on table public.payroll_monthly_adjustments from public, anon, authenticated, service_role;
revoke all on sequence public.payroll_monthly_adjustments_id_seq from public, anon, authenticated, service_role;
grant select, insert, update on table public.payroll_monthly_adjustments to service_role;
grant usage, select on sequence public.payroll_monthly_adjustments_id_seq to service_role;

create or replace function public.payroll_create_contract_version_v2(
  p_user_id bigint, p_pay_type text, p_calculation_basis text,
  p_base_salary numeric, p_fixed_raise_amount numeric,
  p_standard_workdays numeric, p_standard_minutes_per_day integer,
  p_time_block_minutes integer, p_rounding_mode text,
  p_late_adjustment_mode text, p_early_leave_adjustment_mode text,
  p_overtime_mode text, p_paid_leave_mode text, p_effective_from date,
  p_actor_user_id bigint, p_note text default null
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_previous public.payroll_contract_versions%rowtype;
  v_created public.payroll_contract_versions%rowtype;
  v_revision bigint;
begin
  if p_effective_from < date '2026-08-01' then return jsonb_build_object('status','invalid_effective_from'); end if;
  if p_base_salary < 0 or p_base_salary <> trunc(p_base_salary) then return jsonb_build_object('status','invalid_base_salary'); end if;
  if p_fixed_raise_amount < 0 or p_fixed_raise_amount <> trunc(p_fixed_raise_amount) then return jsonb_build_object('status','invalid_fixed_raise'); end if;
  if p_pay_type <> 'monthly' and p_fixed_raise_amount <> 0 then return jsonb_build_object('status','monthly_fixed_raise_only'); end if;
  if p_pay_type = 'hourly' and p_calculation_basis = 'day' then return jsonb_build_object('status','invalid_pay_basis'); end if;
  perform 1 from public.users where id=p_actor_user_id and is_active=true and role in ('owner','master');
  if not found then return jsonb_build_object('status','forbidden'); end if;
  perform 1 from public.users where id=p_user_id;
  if not found then return jsonb_build_object('status','user_not_found'); end if;
  perform pg_advisory_xact_lock(p_user_id);
  select * into v_previous from public.payroll_contract_versions where user_id=p_user_id and effective_to is null order by effective_from desc limit 1 for update;
  if found and p_effective_from <= v_previous.effective_from then return jsonb_build_object('status','period_conflict'); end if;
  select coalesce(max(revision),0)+1 into v_revision from public.payroll_contract_versions where user_id=p_user_id;
  if v_previous.id is not null then update public.payroll_contract_versions set effective_to=p_effective_from where id=v_previous.id; end if;
  insert into public.payroll_contract_versions(user_id,pay_type,calculation_basis,base_salary,fixed_raise_amount,standard_workdays,standard_minutes_per_day,time_block_minutes,rounding_mode,late_adjustment_mode,early_leave_adjustment_mode,overtime_mode,paid_leave_mode,effective_from,revision,created_by,note)
  values(p_user_id,p_pay_type,p_calculation_basis,p_base_salary,p_fixed_raise_amount,p_standard_workdays,p_standard_minutes_per_day,p_time_block_minutes,p_rounding_mode,p_late_adjustment_mode,p_early_leave_adjustment_mode,p_overtime_mode,p_paid_leave_mode,p_effective_from,v_revision,p_actor_user_id,nullif(btrim(p_note),'')) returning * into v_created;
  insert into public.payroll_contract_audit_logs(contract_version_id,user_id,action,actor_user_id,snapshot,reason) values(v_created.id,p_user_id,'created',p_actor_user_id,to_jsonb(v_created),nullif(btrim(p_note),''));
  return jsonb_build_object('status','created','contract',to_jsonb(v_created));
exception when exclusion_violation or unique_violation then return jsonb_build_object('status','period_conflict');
end $$;

revoke all on function public.payroll_create_contract_version_v2(bigint,text,text,numeric,numeric,numeric,integer,integer,text,text,text,text,text,date,bigint,text) from public,anon,authenticated;
grant execute on function public.payroll_create_contract_version_v2(bigint,text,text,numeric,numeric,numeric,integer,integer,text,text,text,text,text,date,bigint,text) to service_role;

create or replace function public.payroll_transition_run_v2(
  p_run_id bigint, p_action text, p_reason text, p_payment_date date,
  p_payment_method text, p_payment_note text, p_actor_user_id bigint
) returns void language plpgsql security definer set search_path=public as $$
declare
  v_run public.payroll_runs%rowtype;
  v_before jsonb;
  v_after jsonb;
  v_audit text;
  v_actor_role text;
  v_unresolved_warnings jsonb;
  v_blocking_count integer;
  v_unresolved_attendance_days integer;
  v_force_snapshot jsonb;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);
  select role into v_actor_role from public.users where id=p_actor_user_id and is_active=true;
  if v_actor_role not in ('owner','master') then raise exception 'PAYROLL_FORBIDDEN' using errcode='42501'; end if;
  select * into v_run from public.payroll_runs where id=p_run_id for update;
  if not found then raise exception 'PAYROLL_RUN_NOT_FOUND'; end if;
  v_before:=to_jsonb(v_run);

  select coalesce(jsonb_agg(jsonb_build_object(
    'reviewId',rv.id,
    'employeeId',re.user_id,
    'employeeName',re.employee_name,
    'warningCode',rv.warning_code,
    'reviewLevel',rv.review_level,
    'businessDate',rv.business_date,
    'sourceSnapshot',rv.source_snapshot
  ) order by rv.business_date nulls first,rv.id),'[]'::jsonb)
  into v_unresolved_warnings
  from public.payroll_run_reviews rv
  join public.payroll_run_employees re on re.id=rv.payroll_run_employee_id
  where re.payroll_run_id=p_run_id and rv.status='open';
  select count(*)::integer into v_blocking_count
  from public.payroll_run_reviews rv
  join public.payroll_run_employees re on re.id=rv.payroll_run_employee_id
  where re.payroll_run_id=p_run_id and rv.status='open' and rv.review_level='blocking';
  select count(distinct rv.business_date)::integer into v_unresolved_attendance_days
  from public.payroll_run_reviews rv
  join public.payroll_run_employees re on re.id=rv.payroll_run_employee_id
  where re.payroll_run_id=p_run_id and rv.status='open' and rv.review_level='blocking'
    and rv.business_date is not null
    and rv.warning_code in ('MISSING_CHECK_IN','MISSING_CHECK_OUT','INVALID_TIME_RANGE','SCHEDULE_HISTORY_UNAVAILABLE');

  if p_action='finalize' then
    if v_run.status<>'draft' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000'; end if;
    if v_blocking_count>0 then raise exception 'PAYROLL_OPEN_REVIEWS' using errcode='22023'; end if;
    v_audit:='run_finalized';
    update public.payroll_runs set status='finalized',finalized_by=p_actor_user_id,finalized_actor_role=v_actor_role,finalized_at=now(),finalize_reason=null,force_finalized=false,force_finalize_reason=null,force_finalize_snapshot=null,updated_at=now() where id=p_run_id;
  elsif p_action='force_finalize' then
    if v_run.status<>'draft' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000'; end if;
    if v_blocking_count=0 then raise exception 'PAYROLL_FORCE_NOT_REQUIRED' using errcode='22023'; end if;
    if nullif(btrim(p_reason),'') is null then raise exception 'PAYROLL_FORCE_REASON_REQUIRED' using errcode='22023'; end if;
    v_force_snapshot:=jsonb_build_object('warnings',v_unresolved_warnings,'unresolvedAttendanceDays',v_unresolved_attendance_days,'engineVersion',v_run.engine_version,'capturedAt',now());
    v_audit:='force_finalized';
    update public.payroll_runs set status='finalized',finalized_by=p_actor_user_id,finalized_actor_role=v_actor_role,finalized_at=now(),finalize_reason=btrim(p_reason),force_finalized=true,force_finalize_reason=btrim(p_reason),force_finalize_snapshot=v_force_snapshot,updated_at=now() where id=p_run_id;
  elsif p_action='cancel_finalization' then
    if v_run.status<>'finalized' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000'; end if;
    if nullif(btrim(p_reason),'') is null then raise exception 'PAYROLL_REASON_REQUIRED' using errcode='22023'; end if;
    v_audit:='finalization_cancelled';
    update public.payroll_runs set status='draft',finalized_by=null,finalized_actor_role=null,finalized_at=null,finalize_reason=null,force_finalized=false,force_finalize_reason=null,force_finalize_snapshot=null,updated_at=now() where id=p_run_id;
  elsif p_action='pay' then
    if v_run.status<>'finalized' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000'; end if;
    if p_payment_date is null or nullif(btrim(p_payment_method),'') is null then raise exception 'PAYROLL_PAYMENT_REQUIRED' using errcode='22023'; end if;
    v_audit:='run_paid';
    update public.payroll_runs set status='paid',paid_by=p_actor_user_id,paid_at=now(),payment_date=p_payment_date,payment_method=p_payment_method,payment_note=nullif(btrim(p_payment_note),''),updated_at=now() where id=p_run_id;
  elsif p_action='cancel' then
    if v_run.status<>'draft' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000'; end if;
    if nullif(btrim(p_reason),'') is null then raise exception 'PAYROLL_REASON_REQUIRED' using errcode='22023'; end if;
    v_audit:='run_cancelled';
    update public.payroll_runs set status='cancelled',cancelled_by=p_actor_user_id,cancelled_at=now(),cancel_reason=btrim(p_reason),updated_at=now() where id=p_run_id;
  else
    raise exception 'PAYROLL_INVALID_TRANSITION' using errcode='22023';
  end if;
  select to_jsonb(r)||jsonb_build_object('transitionActorRole',v_actor_role,'transitionedAt',now()) into v_after from public.payroll_runs r where id=p_run_id;
  insert into public.payroll_run_audit_logs(payroll_run_id,action,actor_user_id,reason,before_snapshot,after_snapshot) values(p_run_id,v_audit,p_actor_user_id,coalesce(nullif(btrim(p_reason),''),p_payment_note),v_before,v_after);
end $$;

revoke all on function public.payroll_transition_run_v2(bigint,text,text,date,text,text,bigint) from public,anon,authenticated;
grant execute on function public.payroll_transition_run_v2(bigint,text,text,date,text,text,bigint) to service_role;

comment on column public.payroll_contract_versions.fixed_raise_amount is 'Effective-dated fixed monthly raise outside contract salary and employee-level raise.';
comment on column public.payroll_runs.force_finalize_snapshot is 'Immutable snapshot of unresolved payroll reviews, unresolved attendance days, and engine version captured at force finalization.';
comment on table public.payroll_monthly_adjustments is 'Append-only monthly incentive and manual penalty ledger. Rows are cancelled, never deleted.';
