-- Partner "중분류" (subtype): a multilingual reference-master classification nested under
-- partner_type, kept as its own table (not free text on business_partners) so it can later
-- narrow Partner comparison/recommendation (partner_type -> subtype -> inventory overlap ->
-- price/spec). NOT a replacement for inventory.category, and NOT the same thing as
-- display_tag (a free single user memo badge) -- both keep their existing separate roles.
--
-- 1. business_partner_subtypes table
-- 2. constraints/indexes
-- 3. initial subtype seed (reference-master data only, no business_partners row touched)
-- 4. business_partners.partner_subtype_id nullable FK
-- 5. eligibility helper + V4 create/update/review RPCs + subtype management RPCs

create table public.business_partner_subtypes (
  id bigint generated by default as identity primary key,
  code text not null check (length(btrim(code)) between 1 and 80),
  partner_type text not null check (length(btrim(partner_type)) between 1 and 80),
  name_ko text null check (name_ko is null or length(btrim(name_ko)) <= 80),
  name_vi text null check (name_vi is null or length(btrim(name_vi)) <= 80),
  sort_order integer not null default 0 check (sort_order between 0 and 100000),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint business_partner_subtypes_name_present check (
    nullif(btrim(name_ko), '') is not null
    or
    nullif(btrim(name_vi), '') is not null
  )
);

create unique index business_partner_subtypes_code_unique
  on public.business_partner_subtypes (lower(btrim(code)));
create index business_partner_subtypes_type_idx
  on public.business_partner_subtypes (partner_type, is_active, sort_order);

alter table public.business_partner_subtypes enable row level security;
revoke all on table public.business_partner_subtypes from public, anon, authenticated, service_role;
revoke all on sequence public.business_partner_subtypes_id_seq from public, anon, authenticated, service_role;
grant select on table public.business_partner_subtypes to service_role;

comment on table public.business_partner_subtypes is
  'Multilingual (KO/VI) reference-master subtype nested under a Partner partner_type. Used to narrow future Partner supply comparison/recommendation; distinct from inventory.category and from business_partners.display_tag.';
comment on column public.business_partner_subtypes.code is
  'Stable internal identifier, independent of display-name changes. Seed rows use explicit semantic codes; subtypes created via the management UI get a server-generated custom_<id> code.';
comment on column public.business_partner_subtypes.partner_type is
  'Same free-text contract as business_partners.partner_type (app-level PARTNER_TYPES is the enum source of truth, not a DB check constraint).';

-- 1차 subtype seed. Reference-master data only -- no business_partners row is touched here,
-- and no existing Partner's partner_subtype_id is backfilled by this migration.
insert into public.business_partner_subtypes (code, partner_type, name_ko, name_vi, sort_order) values
  ('draft_beer', 'alcohol', '생맥주', 'Bia tươi', 10),
  ('bottled_beer', 'alcohol', '병맥주', 'Bia chai', 20),
  ('soju', 'alcohol', '소주', 'Soju', 30),
  ('spirits', 'alcohol', '양주', 'Rượu mạnh', 40),
  ('wine', 'alcohol', '와인', 'Rượu vang', 50),
  ('liqueur', 'alcohol', '리큐르', 'Rượu mùi', 60),
  ('alcohol_other', 'alcohol', '기타 주류', 'Đồ uống có cồn khác', 70),

  ('soft_drink', 'beverage', '탄산음료', 'Nước ngọt có ga', 10),
  ('juice', 'beverage', '주스', 'Nước ép', 20),
  ('water', 'beverage', '생수', 'Nước uống', 30),
  ('beverage_other', 'beverage', '기타 음료', 'Đồ uống khác', 40),

  ('meat', 'food', '육류', 'Thịt', 10),
  ('seafood', 'food', '해산물', 'Hải sản', 20),
  ('dairy_cheese', 'food', '유제품·치즈', 'Sữa & phô mai', 30),
  ('vegetable_fruit', 'food', '채소·과일', 'Rau củ & trái cây', 40),
  ('sauce_seasoning', 'food', '소스·조미료', 'Sốt & gia vị', 50),
  ('dry_food', 'food', '건식재', 'Thực phẩm khô', 60),
  ('frozen_food', 'food', '냉동식품', 'Thực phẩm đông lạnh', 70),
  ('food_other', 'food', '기타 식자재', 'Nguyên liệu khác', 80),

  ('packaging', 'consumable', '포장용품', 'Bao bì', 10),
  ('hygiene', 'consumable', '위생용품', 'Đồ vệ sinh', 20),
  ('cleaning', 'consumable', '청소용품', 'Đồ lau dọn', 30),
  ('disposable', 'consumable', '일회용품', 'Đồ dùng một lần', 40),
  ('bar_consumable', 'consumable', '바 소모품', 'Vật tư quầy bar', 50),
  ('consumable_other', 'consumable', '기타 소모품', 'Vật tư khác', 60),

  ('kitchen_equipment', 'equipment', '주방장비', 'Thiết bị bếp', 10),
  ('bar_equipment', 'equipment', '바장비', 'Thiết bị quầy bar', 20),
  ('facility_equipment', 'equipment', '시설장비', 'Thiết bị cơ sở', 30),
  ('equipment_other', 'equipment', '기타 장비', 'Thiết bị khác', 40),

  ('maintenance', 'service', '유지보수', 'Bảo trì', 10),
  ('delivery', 'service', '배송·운송', 'Giao hàng & vận chuyển', 20),
  ('professional_service', 'service', '전문서비스', 'Dịch vụ chuyên môn', 30),
  ('service_other', 'service', '기타 서비스', 'Dịch vụ khác', 40),

  ('property_rent', 'rent', '임대료', 'Tiền thuê mặt bằng', 10),
  ('rental_equipment', 'rent', '장비임대', 'Thuê thiết bị', 20),
  ('rent_other', 'rent', '기타 임대', 'Thuê khác', 30),

  ('market_purchase', 'other', '시장·주변구매', 'Mua tại chợ / cửa hàng gần', 10),
  ('gas', 'other', '가스', 'Gas', 20),
  ('printing', 'other', '인쇄물', 'In ấn', 30),
  ('miscellaneous', 'other', '잡화', 'Hàng tạp hóa', 40),
  ('other_misc', 'other', '기타', 'Khác', 50);

-- business_partners FK. NULL for every existing row -- this migration inserts subtype
-- master data only, it never assigns any existing Partner a subtype.
alter table public.business_partners
  add column partner_subtype_id bigint null
  references public.business_partner_subtypes(id) on delete restrict;

-- Narrows future "same partner_type, same partner_subtype_id" comparison/recommendation
-- candidate lookups without a full table scan.
create index business_partners_type_subtype_idx
  on public.business_partners (partner_type, partner_subtype_id, is_active);

comment on column public.business_partners.partner_subtype_id is
  'Optional multilingual subtype nested under partner_type, for future supply comparison/recommendation. NULL means unclassified. Existing rows stay NULL after this migration -- classification is applied later by a human, never inferred here.';

-- Eligibility helper, mirroring business_partner_fund_account_is_eligible_v1's shape:
-- NULL is always eligible (unclassified). A non-NULL id must belong to p_partner_type.
-- It must also be is_active=true UNLESS it equals p_current_subtype_id, which lets an
-- update keep a Partner's already-assigned subtype even after that subtype is later
-- deactivated (info screens keep showing it correctly; only *new* assignment requires
-- an active subtype). Create/review-alias call sites omit p_current_subtype_id (NULL
-- default), so a brand-new Partner can only ever be assigned an active subtype.
create function public.business_partner_subtype_is_eligible_v1(
  p_partner_subtype_id bigint,
  p_partner_type text,
  p_current_subtype_id bigint default null
) returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select p_partner_subtype_id is null or exists (
    select 1 from public.business_partner_subtypes
    where id = p_partner_subtype_id
      and partner_type = p_partner_type
      and (is_active = true or id = p_current_subtype_id)
  );
$$;

alter function public.business_partner_subtype_is_eligible_v1(bigint, text, bigint) owner to postgres;
revoke all on function public.business_partner_subtype_is_eligible_v1(bigint, text, bigint) from public, anon, authenticated;
grant execute on function public.business_partner_subtype_is_eligible_v1(bigint, text, bigint) to service_role;

-- V4: full V3 contract + p_partner_subtype_id bigint. V1/V2/V3 signatures/bodies are
-- untouched -- old clients keep creating/updating Partners with subtype NULL forever.
create function public.business_partner_create_v4(
  p_name text,
  p_partner_type text,
  p_payment_mode text,
  p_settlement_mode text,
  p_settlement_rule text,
  p_default_payment_term_days integer,
  p_default_fund_account_id bigint,
  p_partner_subtype_id bigint,
  p_phone text,
  p_contact_name text,
  p_memo text,
  p_is_active boolean,
  p_ledger_party_id bigint,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_id bigint;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;

  if not public.business_partner_fund_account_is_eligible_v1(p_default_fund_account_id) then
    return jsonb_build_object('status', 'invalid_fund_account');
  end if;
  if not public.business_partner_subtype_is_eligible_v1(p_partner_subtype_id, btrim(p_partner_type)) then
    return jsonb_build_object('status', 'invalid_partner_subtype');
  end if;

  if p_ledger_party_id is not null and not exists (
    select 1 from public.ledger_parties where id = p_ledger_party_id and is_active = true
  ) then
    return jsonb_build_object('status', 'invalid_ledger_party');
  end if;
  if p_ledger_party_id is not null and exists (
    select 1 from public.business_partner_ledger_parties where ledger_party_id = p_ledger_party_id
  ) then
    return jsonb_build_object('status', 'ledger_party_already_linked');
  end if;

  insert into public.business_partners(
    name, partner_type, payment_mode, settlement_mode, settlement_rule,
    default_payment_term_days, default_fund_account_id, partner_subtype_id, phone, contact_name, memo, is_active
  ) values (
    btrim(p_name), btrim(p_partner_type), p_payment_mode, p_settlement_mode,
    p_settlement_rule, p_default_payment_term_days, p_default_fund_account_id, p_partner_subtype_id, nullif(btrim(p_phone), ''),
    nullif(btrim(p_contact_name), ''), nullif(btrim(p_memo), ''), p_is_active
  ) returning id into v_id;

  if p_ledger_party_id is not null then
    insert into public.business_partner_ledger_parties(business_partner_id, ledger_party_id)
    values(v_id, p_ledger_party_id);
  end if;

  insert into public.business_partner_audit_logs(
    business_partner_id, actor_user_id, action, after_snapshot
  ) values (
    v_id, p_actor_user_id, 'created',
    (select to_jsonb(p) from public.business_partners p where p.id = v_id)
  );
  return jsonb_build_object('status', 'created', 'partnerId', v_id);
exception
  when unique_violation then return jsonb_build_object('status', 'duplicate_name');
  when check_violation or foreign_key_violation or not_null_violation then return jsonb_build_object('status', 'invalid_input');
end;
$$;

create function public.business_partner_update_v4(
  p_partner_id bigint,
  p_name text,
  p_partner_type text,
  p_payment_mode text,
  p_settlement_mode text,
  p_settlement_rule text,
  p_default_payment_term_days integer,
  p_default_fund_account_id bigint,
  p_partner_subtype_id bigint,
  p_phone text,
  p_contact_name text,
  p_memo text,
  p_is_active boolean,
  p_ledger_party_id bigint,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_before jsonb;
  v_previous_ledger_party_id bigint;
  v_current_subtype_id bigint;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;

  select to_jsonb(p) into v_before
  from public.business_partners p where p.id = p_partner_id for update;
  if v_before is null then return jsonb_build_object('status', 'not_found'); end if;
  v_current_subtype_id := (v_before->>'partner_subtype_id')::bigint;

  if not public.business_partner_fund_account_is_eligible_v1(p_default_fund_account_id) then
    return jsonb_build_object('status', 'invalid_fund_account');
  end if;
  if not public.business_partner_subtype_is_eligible_v1(p_partner_subtype_id, btrim(p_partner_type), v_current_subtype_id) then
    return jsonb_build_object('status', 'invalid_partner_subtype');
  end if;

  if p_ledger_party_id is not null and not exists (
    select 1 from public.ledger_parties where id = p_ledger_party_id and is_active = true
  ) then
    return jsonb_build_object('status', 'invalid_ledger_party');
  end if;
  if p_ledger_party_id is not null and exists (
    select 1 from public.business_partner_ledger_parties
    where ledger_party_id = p_ledger_party_id and business_partner_id <> p_partner_id
  ) then
    return jsonb_build_object('status', 'ledger_party_already_linked');
  end if;

  select ledger_party_id into v_previous_ledger_party_id
  from public.business_partner_ledger_parties where business_partner_id = p_partner_id;

  update public.business_partners set
    name = btrim(p_name),
    partner_type = btrim(p_partner_type),
    payment_mode = p_payment_mode,
    settlement_mode = p_settlement_mode,
    settlement_rule = p_settlement_rule,
    default_payment_term_days = p_default_payment_term_days,
    default_fund_account_id = p_default_fund_account_id,
    partner_subtype_id = p_partner_subtype_id,
    phone = nullif(btrim(p_phone), ''),
    contact_name = nullif(btrim(p_contact_name), ''),
    memo = nullif(btrim(p_memo), ''),
    is_active = p_is_active,
    updated_at = now()
  where id = p_partner_id;

  if p_ledger_party_id is null then
    delete from public.business_partner_ledger_parties where business_partner_id = p_partner_id;
  else
    insert into public.business_partner_ledger_parties(business_partner_id, ledger_party_id, updated_at)
    values(p_partner_id, p_ledger_party_id, now())
    on conflict(business_partner_id) do update
      set ledger_party_id = excluded.ledger_party_id, updated_at = now();
  end if;

  insert into public.business_partner_audit_logs(
    business_partner_id, actor_user_id, action, before_snapshot, after_snapshot
  ) values (
    p_partner_id, p_actor_user_id, 'updated', v_before,
    (select to_jsonb(p) from public.business_partners p where p.id = p_partner_id)
  );
  if v_previous_ledger_party_id is distinct from p_ledger_party_id then
    insert into public.business_partner_audit_logs(
      business_partner_id, actor_user_id, action, before_snapshot, after_snapshot
    ) values (
      p_partner_id, p_actor_user_id,
      case when p_ledger_party_id is null then 'ledger_party_unlinked' else 'ledger_party_linked' end,
      case when v_previous_ledger_party_id is null then null else jsonb_build_object('ledgerPartyId', v_previous_ledger_party_id) end,
      case when p_ledger_party_id is null then null else jsonb_build_object('ledgerPartyId', p_ledger_party_id) end
    );
  end if;
  return jsonb_build_object('status', 'updated', 'partnerId', p_partner_id);
exception
  when unique_violation then return jsonb_build_object('status', 'duplicate_name');
  when check_violation or foreign_key_violation or not_null_violation then return jsonb_build_object('status', 'invalid_input');
end;
$$;

create function public.business_partner_review_supplier_alias_v4(
  p_alias_id bigint,
  p_action text,
  p_existing_partner_id bigint,
  p_name text,
  p_partner_type text,
  p_payment_mode text,
  p_settlement_mode text,
  p_settlement_rule text,
  p_default_payment_term_days integer,
  p_default_fund_account_id bigint,
  p_partner_subtype_id bigint,
  p_phone text,
  p_contact_name text,
  p_memo text,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_alias public.business_partner_supplier_aliases%rowtype;
  v_before jsonb;
  v_partner_id bigint;
  v_audit_action text;
  v_inventory_count integer := 0;
begin
  select lower(role::text) into v_role from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then return jsonb_build_object('status', 'forbidden'); end if;

  select * into v_alias from public.business_partner_supplier_aliases where id = p_alias_id for update;
  if not found then return jsonb_build_object('status', 'not_found'); end if;
  v_before := to_jsonb(v_alias);

  if p_action = 'create_partner' then
    if v_alias.status <> 'pending' then return jsonb_build_object('status', 'invalid_state'); end if;
    if not public.business_partner_fund_account_is_eligible_v1(p_default_fund_account_id) then
      return jsonb_build_object('status', 'invalid_fund_account');
    end if;
    if not public.business_partner_subtype_is_eligible_v1(p_partner_subtype_id, btrim(p_partner_type)) then
      return jsonb_build_object('status', 'invalid_partner_subtype');
    end if;
    insert into public.business_partners(
      name, partner_type, payment_mode, settlement_mode, settlement_rule,
      default_payment_term_days, default_fund_account_id, partner_subtype_id, phone, contact_name, memo, is_active
    ) values (
      btrim(p_name), btrim(p_partner_type), p_payment_mode, p_settlement_mode,
      p_settlement_rule, p_default_payment_term_days, p_default_fund_account_id, p_partner_subtype_id, nullif(btrim(p_phone), ''),
      nullif(btrim(p_contact_name), ''), nullif(btrim(p_memo), ''), true
    ) returning id into v_partner_id;
    insert into public.business_partner_audit_logs(business_partner_id, actor_user_id, action, after_snapshot)
    values(v_partner_id, p_actor_user_id, 'created', (select to_jsonb(p) from public.business_partners p where p.id = v_partner_id));
    v_audit_action := 'candidate_linked_new_partner';
  elsif p_action = 'link_existing' then
    if v_alias.status <> 'pending' then return jsonb_build_object('status', 'invalid_state'); end if;
    select id into v_partner_id from public.business_partners where id = p_existing_partner_id and is_active = true;
    if v_partner_id is null then return jsonb_build_object('status', 'invalid_partner'); end if;
    v_audit_action := 'candidate_linked_existing_partner';
  elsif p_action = 'ignore' then
    if v_alias.status <> 'pending' then return jsonb_build_object('status', 'invalid_state'); end if;
    update public.business_partner_supplier_aliases set status='ignored', business_partner_id=null, reviewed_at=now(), reviewed_by=p_actor_user_id, updated_at=now() where id=p_alias_id returning * into v_alias;
    v_audit_action := 'candidate_ignored';
  elsif p_action = 'reopen' then
    if v_alias.status <> 'ignored' then return jsonb_build_object('status', 'invalid_state'); end if;
    update public.business_partner_supplier_aliases set status='pending', business_partner_id=null, reviewed_at=null, reviewed_by=null, updated_at=now() where id=p_alias_id returning * into v_alias;
    v_audit_action := 'candidate_reopened';
  else
    return jsonb_build_object('status', 'invalid_action');
  end if;

  if p_action in ('create_partner','link_existing') then
    update public.business_partner_supplier_aliases set status='linked', business_partner_id=v_partner_id, reviewed_at=now(), reviewed_by=p_actor_user_id, updated_at=now() where id=p_alias_id returning * into v_alias;
    update public.inventory set supplier_partner_id=v_partner_id where lower(btrim(supplier))=v_alias.normalized_name and supplier_partner_id is null;
    get diagnostics v_inventory_count = row_count;
  end if;

  insert into public.business_partner_supplier_alias_audit_logs(supplier_alias_id, actor_user_id, action, before_snapshot, after_snapshot)
  values(p_alias_id, p_actor_user_id, v_audit_action, v_before, to_jsonb(v_alias));
  return jsonb_build_object('status', 'reviewed', 'partnerId', v_partner_id, 'inventoryLinkedCount', v_inventory_count);
exception
  when unique_violation then return jsonb_build_object('status', 'duplicate_name');
  when check_violation or foreign_key_violation or not_null_violation then return jsonb_build_object('status', 'invalid_input');
end;
$$;

alter function public.business_partner_create_v4(text,text,text,text,text,integer,bigint,bigint,text,text,text,boolean,bigint,bigint) owner to postgres;
alter function public.business_partner_update_v4(bigint,text,text,text,text,text,integer,bigint,bigint,text,text,text,boolean,bigint,bigint) owner to postgres;
alter function public.business_partner_review_supplier_alias_v4(bigint,text,bigint,text,text,text,text,text,integer,bigint,bigint,text,text,text,bigint) owner to postgres;

revoke all on function public.business_partner_create_v4(text,text,text,text,text,integer,bigint,bigint,text,text,text,boolean,bigint,bigint) from public, anon, authenticated;
revoke all on function public.business_partner_update_v4(bigint,text,text,text,text,text,integer,bigint,bigint,text,text,text,boolean,bigint,bigint) from public, anon, authenticated;
revoke all on function public.business_partner_review_supplier_alias_v4(bigint,text,bigint,text,text,text,text,text,integer,bigint,bigint,text,text,text,bigint) from public, anon, authenticated;

grant execute on function public.business_partner_create_v4(text,text,text,text,text,integer,bigint,bigint,text,text,text,boolean,bigint,bigint) to service_role;
grant execute on function public.business_partner_update_v4(bigint,text,text,text,text,text,integer,bigint,bigint,text,text,text,boolean,bigint,bigint) to service_role;
grant execute on function public.business_partner_review_supplier_alias_v4(bigint,text,bigint,text,text,text,text,text,integer,bigint,bigint,text,text,text,bigint) to service_role;

comment on function public.business_partner_create_v4(text,text,text,text,text,integer,bigint,bigint,text,text,text,boolean,bigint,bigint) is
  'V4 adds partner_subtype_id (nullable, must belong to partner_type and be active). V1/V2/V3 remain unchanged for existing clients.';

-- Subtype management (create/update/deactivate). No physical delete: a subtype already
-- referenced by a Partner is deactivated instead, and stays correctly displayable there.
create function public.business_partner_subtype_create_v1(
  p_partner_type text,
  p_name_ko text,
  p_name_vi text,
  p_sort_order integer,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_id bigint;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;

  if nullif(btrim(p_name_ko), '') is null and nullif(btrim(p_name_vi), '') is null then
    return jsonb_build_object('status', 'invalid_name');
  end if;

  -- Server-generated stable code (custom_<id>): the management UI never lets an operator
  -- type a code directly, and KO/VI display names are never relied on as an identity.
  v_id := nextval('public.business_partner_subtypes_id_seq');
  insert into public.business_partner_subtypes(id, code, partner_type, name_ko, name_vi, sort_order, is_active)
  values (v_id, 'custom_' || v_id, btrim(p_partner_type), nullif(btrim(p_name_ko), ''), nullif(btrim(p_name_vi), ''), coalesce(p_sort_order, 0), true);

  return jsonb_build_object('status', 'created', 'subtypeId', v_id, 'code', 'custom_' || v_id);
exception
  when check_violation or not_null_violation then return jsonb_build_object('status', 'invalid_input');
end;
$$;

create function public.business_partner_subtype_update_v1(
  p_subtype_id bigint,
  p_name_ko text,
  p_name_vi text,
  p_sort_order integer,
  p_is_active boolean,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_before jsonb;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;

  select to_jsonb(s) into v_before
  from public.business_partner_subtypes s where s.id = p_subtype_id for update;
  if v_before is null then return jsonb_build_object('status', 'not_found'); end if;

  if nullif(btrim(p_name_ko), '') is null and nullif(btrim(p_name_vi), '') is null then
    return jsonb_build_object('status', 'invalid_name');
  end if;

  -- partner_type and code are immutable here: changing partner_type could silently
  -- orphan every Partner already pointed at this subtype (section 3's category
  -- integrity), and code is a stable identifier independent of display names.
  update public.business_partner_subtypes set
    name_ko = nullif(btrim(p_name_ko), ''),
    name_vi = nullif(btrim(p_name_vi), ''),
    sort_order = coalesce(p_sort_order, sort_order),
    is_active = p_is_active,
    updated_at = now()
  where id = p_subtype_id;

  return jsonb_build_object('status', 'updated', 'subtypeId', p_subtype_id);
exception
  when check_violation or not_null_violation then return jsonb_build_object('status', 'invalid_input');
end;
$$;

alter function public.business_partner_subtype_create_v1(text,text,text,integer,bigint) owner to postgres;
alter function public.business_partner_subtype_update_v1(bigint,text,text,integer,boolean,bigint) owner to postgres;

revoke all on function public.business_partner_subtype_create_v1(text,text,text,integer,bigint) from public, anon, authenticated;
revoke all on function public.business_partner_subtype_update_v1(bigint,text,text,integer,boolean,bigint) from public, anon, authenticated;

grant execute on function public.business_partner_subtype_create_v1(text,text,text,integer,bigint) to service_role;
grant execute on function public.business_partner_subtype_update_v1(bigint,text,text,integer,boolean,bigint) to service_role;

comment on function public.business_partner_subtype_update_v1(bigint,text,text,integer,boolean,bigint) is
  'Edits name_ko/name_vi/sort_order/is_active only. No physical delete RPC exists -- deactivate (is_active=false) is the only removal path, since a subtype may already be referenced by business_partners.partner_subtype_id (ON DELETE RESTRICT).';
