-- 직원 식대 대상 관리 + 식대 현재·예상비용 1차 기능.
--
-- 식대는 출근 당일 현금으로 지급되며(실제 지급 여부는 이번 단계에서 관리하지 않음), 월 급여
-- 지급액·직원 실수령액에는 포함하지 않는다. 그래서 이 Migration은:
--   1) 공통 1일 식대 금액을 effective-dated version 테이블로 관리한다
--      (payroll_settings 단일 행에 컬럼을 추가하지 않는다 — 월 중간 금액 변경 시 과거
--      재현이 불가능해지기 때문).
--   2) 직원별 식대 대상 여부를 급여계약과 분리된 effective-dated version 테이블로 관리한다
--      (계약은 "이미 급여 계산/지급에 사용되면 잠기는" 정책이 있어 식대 온/오프처럼 지급액과
--      무관한 변경까지 막아버리기 때문. 두 테이블 모두 payroll_insurance_setting_versions와
--      동일한 append-only 패턴 — 별도 audit 테이블 없이 version 자체가 이력이다).
--   3) 근태 기록 미사용 직원(attendance_tracking_enabled=false)은 식대 대상으로 설정할 수
--      없게 RPC에서 차단하고, 반대로 이미 식대 대상인 직원의 근태 사용을 끄는 시도도
--      trigger로 차단해 "식대 대상만 남고 근태 미사용"이라는 모순 상태를 막는다.
--
-- 기존 payroll_contract_versions·payroll_insurance_setting_versions·payroll_run_*·
-- payroll_pay_employee_v1 등은 전혀 수정하지 않는다. 새 테이블·새 RPC만 추가한다.

begin;

-- ---------------------------------------------------------------------------
-- 0. Preflight — 의존 객체가 이미 존재하는지 확인
-- ---------------------------------------------------------------------------
do $$
declare
  v_missing text[] := array[]::text[];
begin
  if to_regprocedure('public.payroll_assert_actor_v2(bigint)') is null then
    v_missing := array_append(v_missing, 'public.payroll_assert_actor_v2(bigint)');
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'users' and column_name = 'attendance_tracking_enabled'
  ) then
    v_missing := array_append(v_missing, 'public.users.attendance_tracking_enabled');
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'payroll_contract_versions' and column_name = 'standard_workdays'
  ) then
    v_missing := array_append(v_missing, 'public.payroll_contract_versions.standard_workdays');
  end if;
  if array_length(v_missing, 1) is not null then
    raise exception 'preflight failed: missing dependencies: %', array_to_string(v_missing, ', ');
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 1. 공통 1일 식대 금액 — effective-dated version 테이블 (payroll_insurance_setting_versions
--    패턴 재사용, user_id 없이 회사 전체 공통값)
-- ---------------------------------------------------------------------------

create table if not exists public.payroll_meal_allowance_policy_versions (
  id bigint generated by default as identity primary key,
  daily_amount numeric(16,0) not null,
  effective_from date not null,
  revision bigint not null,
  created_by bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  note text null,
  constraint payroll_meal_allowance_policy_amount_check
    check (daily_amount >= 0 and daily_amount = trunc(daily_amount)),
  constraint payroll_meal_allowance_policy_revision_check check (revision >= 1),
  constraint payroll_meal_allowance_policy_revision_unique unique (revision)
);

create index if not exists payroll_meal_allowance_policy_lookup_idx
  on public.payroll_meal_allowance_policy_versions (effective_from desc, revision desc);

alter table public.payroll_meal_allowance_policy_versions enable row level security;

revoke all on table public.payroll_meal_allowance_policy_versions
  from public, anon, authenticated, service_role;
revoke all on sequence public.payroll_meal_allowance_policy_versions_id_seq
  from public, anon, authenticated, service_role;
grant select, insert on table public.payroll_meal_allowance_policy_versions to service_role;
grant usage, select on sequence public.payroll_meal_allowance_policy_versions_id_seq to service_role;

comment on table public.payroll_meal_allowance_policy_versions is
  'Append-only company-wide daily meal allowance amount. Latest effective_from (ties broken by highest revision) that is <= the target date applies. No row means "not configured" — application treats this as amount 0 with a setup warning, never as an assumed default.';

-- ---------------------------------------------------------------------------
-- 2. 직원별 식대 대상 여부 — effective-dated version 테이블, 급여계약과 완전히 분리
-- ---------------------------------------------------------------------------

create table if not exists public.payroll_meal_allowance_eligibility_versions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  is_eligible boolean not null,
  effective_from date not null,
  revision bigint not null,
  created_by bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  note text null,
  constraint payroll_meal_allowance_eligibility_revision_check check (revision >= 1),
  constraint payroll_meal_allowance_eligibility_revision_unique unique (user_id, revision)
);

create index if not exists payroll_meal_allowance_eligibility_lookup_idx
  on public.payroll_meal_allowance_eligibility_versions (user_id, effective_from desc, revision desc);
create index if not exists payroll_meal_allowance_eligibility_created_by_idx
  on public.payroll_meal_allowance_eligibility_versions (created_by);

alter table public.payroll_meal_allowance_eligibility_versions enable row level security;

revoke all on table public.payroll_meal_allowance_eligibility_versions
  from public, anon, authenticated, service_role;
revoke all on sequence public.payroll_meal_allowance_eligibility_versions_id_seq
  from public, anon, authenticated, service_role;
grant select, insert on table public.payroll_meal_allowance_eligibility_versions to service_role;
grant usage, select on sequence public.payroll_meal_allowance_eligibility_versions_id_seq to service_role;

comment on table public.payroll_meal_allowance_eligibility_versions is
  'Append-only per-employee meal allowance eligibility, independent from payroll_contract_versions (which locks once used in a payroll run). No row for a user means "not eligible". Existing employees are intentionally left with zero rows by this migration — an administrator must turn eligibility on per employee after operational confirmation.';

-- ---------------------------------------------------------------------------
-- 3. 공통 정책 RPC — owner/master만 실행 가능 (기존 payroll_assert_actor_v2 재사용)
-- ---------------------------------------------------------------------------

create or replace function public.payroll_create_meal_allowance_policy_version_v1(
  p_daily_amount numeric,
  p_effective_from date,
  p_actor_user_id bigint,
  p_note text default null
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_revision bigint;
  v_created public.payroll_meal_allowance_policy_versions%rowtype;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);

  if p_daily_amount is null or p_daily_amount < 0 or p_daily_amount <> trunc(p_daily_amount) then
    raise exception 'MEAL_ALLOWANCE_INVALID_AMOUNT' using errcode = '22023';
  end if;
  if p_effective_from is null then
    raise exception 'MEAL_ALLOWANCE_INVALID_EFFECTIVE_FROM' using errcode = '22023';
  end if;

  -- 동시 저장 요청 사이의 revision 경합을 직렬화한다(계약 버전의 pg_advisory_xact_lock(-p_user_id)
  -- 잠금과 같은 목적 — 이 정책에는 user_id가 없으므로 테이블 전용 advisory lock을 쓴다).
  perform pg_advisory_xact_lock(hashtext('payroll_meal_allowance_policy_versions'));

  select coalesce(max(revision), 0) + 1
    into v_revision
  from public.payroll_meal_allowance_policy_versions;

  insert into public.payroll_meal_allowance_policy_versions (
    daily_amount, effective_from, revision, created_by, note
  ) values (
    p_daily_amount, p_effective_from, v_revision, p_actor_user_id, nullif(btrim(p_note), '')
  ) returning * into v_created;

  return to_jsonb(v_created);
end;
$$;

revoke all on function public.payroll_create_meal_allowance_policy_version_v1(numeric, date, bigint, text)
  from public, anon, authenticated;
grant execute on function public.payroll_create_meal_allowance_policy_version_v1(numeric, date, bigint, text)
  to service_role;

comment on function public.payroll_create_meal_allowance_policy_version_v1(numeric, date, bigint, text) is
  '공통 1일 식대 금액의 새 effective-dated version을 추가한다. owner/master만 실행 가능(payroll_assert_actor_v2). 과거 version은 절대 수정하지 않는다 — 정정이 필요하면 새 version을 추가한다.';

-- ---------------------------------------------------------------------------
-- 4. 직원별 식대 대상 RPC — owner/master만 실행 가능, 근태 미사용 직원 차단
-- ---------------------------------------------------------------------------

create or replace function public.payroll_create_meal_allowance_eligibility_version_v1(
  p_user_id bigint,
  p_is_eligible boolean,
  p_effective_from date,
  p_actor_user_id bigint,
  p_note text default null
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_revision bigint;
  v_created public.payroll_meal_allowance_eligibility_versions%rowtype;
  v_target public.users%rowtype;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);

  if p_is_eligible is null then
    raise exception 'MEAL_ALLOWANCE_INVALID_ELIGIBILITY' using errcode = '22023';
  end if;
  if p_effective_from is null then
    raise exception 'MEAL_ALLOWANCE_INVALID_EFFECTIVE_FROM' using errcode = '22023';
  end if;

  select * into v_target
  from public.users
  where id = p_user_id and is_system_account = false
  for share;
  if not found then
    raise exception 'USER_NOT_FOUND' using errcode = 'P0002';
  end if;

  -- 식대비용은 실제 출근 기록을 기준으로 계산되므로, 근태 기록을 사용하지 않는 직원은
  -- 애초에 식대 대상으로 켤 수 없다(1차 정책). 이미 대상이던 직원을 미대상으로 되돌리는
  -- 것(p_is_eligible=false)은 근태 사용 여부와 무관하게 항상 허용한다.
  if p_is_eligible and v_target.attendance_tracking_enabled = false then
    raise exception 'MEAL_ALLOWANCE_REQUIRES_ATTENDANCE_TRACKING' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtext('payroll_meal_allowance_eligibility_versions:' || p_user_id::text));

  select coalesce(max(revision), 0) + 1
    into v_revision
  from public.payroll_meal_allowance_eligibility_versions
  where user_id = p_user_id;

  insert into public.payroll_meal_allowance_eligibility_versions (
    user_id, is_eligible, effective_from, revision, created_by, note
  ) values (
    p_user_id, p_is_eligible, p_effective_from, v_revision, p_actor_user_id, nullif(btrim(p_note), '')
  ) returning * into v_created;

  return to_jsonb(v_created);
end;
$$;

revoke all on function public.payroll_create_meal_allowance_eligibility_version_v1(bigint, boolean, date, bigint, text)
  from public, anon, authenticated;
grant execute on function public.payroll_create_meal_allowance_eligibility_version_v1(bigint, boolean, date, bigint, text)
  to service_role;

comment on function public.payroll_create_meal_allowance_eligibility_version_v1(bigint, boolean, date, bigint, text) is
  '직원별 식대 대상 여부의 새 effective-dated version을 추가한다. owner/master만 실행 가능. 급여계약 잠금과 완전히 독립적이라 지급 완료된 계약을 건드리지 않고도 식대 대상을 변경할 수 있다. attendance_tracking_enabled=false인 직원을 새로 식대 대상(true)으로 설정하는 것은 차단한다.';

-- ---------------------------------------------------------------------------
-- 5. 안전장치 — 이미 식대 대상인 직원의 근태 사용을 끄는 것을 차단
-- ---------------------------------------------------------------------------
-- employee_update_profile_and_level_v7~v9 RPC 체인(그리고 그 API 호출부인
-- app/api/admin/users/route.ts)은 이번 1차 범위에서 건드리지 않는다("기존 RPC를 과도하게
-- 확장하지 않는다"). 대신 public.users에 대한 BEFORE UPDATE trigger 하나만 추가해 "식대
-- 대상만 남긴 채 근태 사용을 끄는" 모순 상태를 어떤 호출 경로로도 만들 수 없게 한다 —
-- 기존 attendance_records_block_new_check_in_when_tracking_disabled trigger와 같은 방어
-- 패턴이다. 애플리케이션이 이 오류 코드를 아직 특별히 안내하지 않더라도(1차 범위 밖),
-- 데이터 정합성 자체는 이 trigger가 항상 보장한다.

-- 안전성 재검토(읽기 전용)에서 확인된 문제: 아래 원래 쿼리는 "effective_from <= 오늘"만
-- 검사해 미래에 예약된 식대 대상(예: 다음 달 1일부터 대상=true)을 놓쳤다. 그 결과 오늘
-- 근태 사용을 꺼도 차단되지 않고, 예약된 날짜가 되면 "식대 대상=true + 근태 미사용"이라는
-- 모순 상태가 그대로 발생할 수 있었다. 최소 수정: 오늘 기준 현재 유효값과, 오늘 이후 각
-- effective_from별 최신 revision 값을 UNION으로 모두 검사해 그중 하나라도 true면 차단한다.
-- 과거에 이미 종료된(현재 유효값보다 앞선) 대상=true 이력은 검사 대상에 포함되지 않으므로
-- 죽은 과거 이력만으로 오탐이 생기지 않는다. 오류 코드·메시지·trigger 이름·연결 구조는
-- 그대로 유지한다.

create or replace function public.users_block_attendance_tracking_disable_when_meal_eligible()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_has_conflicting_eligible_period boolean;
begin
  if tg_op <> 'UPDATE' then
    return new;
  end if;
  if old.attendance_tracking_enabled is distinct from true
    or new.attendance_tracking_enabled is distinct from false then
    return new;
  end if;

  -- PostgreSQL은 UNION 각 분기에 ORDER BY/LIMIT을 적용하려면 그 분기를 괄호로 묶어야
  -- 한다(괄호 없이 쓰면 ORDER BY/LIMIT이 UNION 전체 결과에 걸리는 것으로 파싱되거나 구문
  -- 오류가 난다). 아래 두 분기 모두 괄호로 감싼다 — 판정 로직 자체는 바뀌지 않는다.
  select exists (
    select 1
    from (
      (
        -- 오늘 기준 유효한 최신 상태(동일 effective_from이면 최신 revision).
        select is_eligible
        from public.payroll_meal_allowance_eligibility_versions
        where user_id = new.id
          and effective_from <= (now() at time zone 'Asia/Ho_Chi_Minh')::date
        order by effective_from desc, revision desc
        limit 1
      )

      union all

      (
        -- 오늘 이후 예약된 각 effective_from별 최신 revision 상태(distinct on으로 동일
        -- effective_from 중 최신 revision 한 건만 남긴다).
        select distinct on (effective_from) is_eligible
        from public.payroll_meal_allowance_eligibility_versions
        where user_id = new.id
          and effective_from > (now() at time zone 'Asia/Ho_Chi_Minh')::date
        order by effective_from, revision desc
      )
    ) resolved
    where resolved.is_eligible = true
  )
  into v_has_conflicting_eligible_period;

  if v_has_conflicting_eligible_period then
    raise exception 'MEAL_ALLOWANCE_ELIGIBLE_BLOCKS_ATTENDANCE_TRACKING_DISABLE'
      using errcode = '55000';
  end if;

  return new;
end;
$$;

drop trigger if exists users_block_attendance_tracking_disable_when_meal_eligible on public.users;
create trigger users_block_attendance_tracking_disable_when_meal_eligible
  before update on public.users
  for each row
  execute function public.users_block_attendance_tracking_disable_when_meal_eligible();

revoke all on function public.users_block_attendance_tracking_disable_when_meal_eligible()
  from public, anon, authenticated;

comment on function public.users_block_attendance_tracking_disable_when_meal_eligible() is
  '식대 대상 직원(오늘 날짜 기준 유효하거나, 오늘 이후 예약된 어느 effective_from에서든 payroll_meal_allowance_eligibility_versions.is_eligible=true로 판정되는 경우)의 attendance_tracking_enabled를 true→false로 바꾸는 UPDATE를 차단한다. 먼저 현재·미래 모든 식대 대상 예약을 해제한 뒤에만 근태 사용을 끌 수 있다.';

-- ---------------------------------------------------------------------------
-- 6. 공통 설정 통합 저장 RPC — payroll_settings와 식대 공통 정책을 하나의 transaction으로
-- ---------------------------------------------------------------------------
-- 화면(공통 설정)에서 저장 버튼을 한 번만 눌러도 payroll_settings 갱신과 식대 정책 신규
-- version 생성이 원자적으로 함께(또는 함께 실패)하도록 새 RPC를 추가한다. 기존
-- app/api/admin/payroll/settings/route.ts의 PATCH(순수 payroll_settings update, RPC 없이
-- 직접 update)는 그대로 두고 교체하지 않는다 — 새 UI만 이 RPC를 쓰는 새 쓰기 경로(PUT)를
-- 통해 호출한다.
--
-- 식대 부분은 p_meal_daily_amount/p_meal_effective_from이 둘 다 null이면 완전히 건드리지
-- 않는다("미설정 유지"). 하나만 null이면 오류로 거부한다(둘 다 입력되거나 둘 다 비어야
-- 함). 값이 실제로 달라졌을 때만(금액 또는 적용일이 기존 최신 version과 다를 때만) 새
-- payroll_meal_allowance_policy_versions revision을 만든다 — 매 저장마다 무의미한 revision이
-- 쌓이지 않게 한다.

create or replace function public.payroll_update_common_settings_v1(
  p_actor_user_id bigint,
  p_payment_day integer,
  p_employee_insurance_rate_bp integer,
  p_employer_insurance_rate_bp integer,
  p_director_insurance_enabled boolean,
  p_director_insurance_base_amount numeric,
  p_director_insurance_rate_bp integer,
  p_late_major_threshold_minutes integer,
  p_late_minor_penalty_minutes integer,
  p_late_major_penalty_rate_bp integer,
  p_unauthorized_absence_penalty_days integer,
  p_meal_daily_amount numeric default null,
  p_meal_effective_from date default null,
  p_meal_note text default null
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_settings public.payroll_settings%rowtype;
  v_meal_current_amount numeric;
  v_meal_current_effective_from date;
  v_meal_revision bigint;
  v_meal_created public.payroll_meal_allowance_policy_versions%rowtype;
  v_meal_changed boolean := false;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);

  if p_payment_day is null or p_payment_day < 1 or p_payment_day > 28 then
    raise exception 'INVALID_PAYMENT_DAY' using errcode = '22023';
  end if;
  if p_employee_insurance_rate_bp is null or p_employee_insurance_rate_bp < 0 or p_employee_insurance_rate_bp > 10000 then
    raise exception 'INVALID_INSURANCE_SETTINGS' using errcode = '22023';
  end if;
  if p_employer_insurance_rate_bp is null or p_employer_insurance_rate_bp < 0 or p_employer_insurance_rate_bp > 10000 then
    raise exception 'INVALID_INSURANCE_SETTINGS' using errcode = '22023';
  end if;
  if p_director_insurance_enabled is null then
    raise exception 'INVALID_INSURANCE_SETTINGS' using errcode = '22023';
  end if;
  if p_director_insurance_base_amount is null or p_director_insurance_base_amount < 0 then
    raise exception 'INVALID_INSURANCE_SETTINGS' using errcode = '22023';
  end if;
  if p_director_insurance_rate_bp is null or p_director_insurance_rate_bp < 0 or p_director_insurance_rate_bp > 10000 then
    raise exception 'INVALID_INSURANCE_SETTINGS' using errcode = '22023';
  end if;
  if p_late_major_threshold_minutes is null or p_late_major_threshold_minutes < 1 or p_late_major_threshold_minutes > 1440 then
    raise exception 'INVALID_PENALTY_SETTINGS' using errcode = '22023';
  end if;
  if p_late_minor_penalty_minutes is null or p_late_minor_penalty_minutes < 1 or p_late_minor_penalty_minutes > 1440 then
    raise exception 'INVALID_PENALTY_SETTINGS' using errcode = '22023';
  end if;
  if p_late_major_penalty_rate_bp is null or p_late_major_penalty_rate_bp < 0 or p_late_major_penalty_rate_bp > 10000 then
    raise exception 'INVALID_PENALTY_SETTINGS' using errcode = '22023';
  end if;
  if p_unauthorized_absence_penalty_days is null or p_unauthorized_absence_penalty_days < 1 or p_unauthorized_absence_penalty_days > 31 then
    raise exception 'INVALID_PENALTY_SETTINGS' using errcode = '22023';
  end if;

  -- 식대: 금액·적용일은 함께 입력되거나 함께 비어 있어야 한다.
  if (p_meal_daily_amount is null) is distinct from (p_meal_effective_from is null) then
    raise exception 'INVALID_MEAL_ALLOWANCE_POLICY' using errcode = '22023';
  end if;
  if p_meal_daily_amount is not null
    and (p_meal_daily_amount < 0 or p_meal_daily_amount <> trunc(p_meal_daily_amount)) then
    raise exception 'MEAL_ALLOWANCE_INVALID_AMOUNT' using errcode = '22023';
  end if;

  update public.payroll_settings
  set
    payment_day = p_payment_day,
    employee_insurance_rate_bp = p_employee_insurance_rate_bp,
    employer_insurance_rate_bp = p_employer_insurance_rate_bp,
    director_insurance_enabled = p_director_insurance_enabled,
    director_insurance_base_amount = p_director_insurance_base_amount,
    director_insurance_rate_bp = p_director_insurance_rate_bp,
    late_major_threshold_minutes = p_late_major_threshold_minutes,
    late_minor_penalty_minutes = p_late_minor_penalty_minutes,
    late_major_penalty_rate_bp = p_late_major_penalty_rate_bp,
    unauthorized_absence_penalty_days = p_unauthorized_absence_penalty_days,
    updated_at = now(),
    updated_by = p_actor_user_id
  where id = 1
  returning * into v_settings;

  -- payroll_settings.id=1 행이 없으면(운영상 있을 수 없지만) 여기서 즉시 실패시켜야 한다.
  -- 그렇지 않으면 UPDATE는 0행에 영향을 주고 조용히 넘어가는데 아래 식대 부분만 성공해
  -- "공통설정은 그대로인데 식대 정책만 새로 생겼다"는 부분 반영이 생길 수 있다 — 이 함수
  -- 전체가 하나의 transaction이므로, 여기서 raise exception하면 이미 실행된 UPDATE(0행
  -- 영향이라 사실상 no-op이지만)와 아래에서 만들 식대 revision 모두 롤백된다.
  if not found then
    raise exception 'PAYROLL_SETTINGS_NOT_FOUND' using errcode = 'P0002';
  end if;

  if p_meal_daily_amount is not null then
    -- payroll_create_meal_allowance_policy_version_v1(호환용 별도 POST 경로)와 동시에
    -- 실행될 수 있으므로, "최신값 조회 → 비교 → 다르면 lock" 순서가 아니라 반드시
    -- "lock 먼저 획득 → lock 안에서 최신값 재조회 → 비교"순으로 처리한다. lock 키 문자열은
    -- payroll_create_meal_allowance_policy_version_v1과 동일하게 유지해 두 경로가 서로를
    -- 직렬화하게 한다.
    perform pg_advisory_xact_lock(hashtext('payroll_meal_allowance_policy_versions'));

    select daily_amount, effective_from
      into v_meal_current_amount, v_meal_current_effective_from
    from public.payroll_meal_allowance_policy_versions
    order by effective_from desc, revision desc
    limit 1;

    if v_meal_current_amount is distinct from p_meal_daily_amount
      or v_meal_current_effective_from is distinct from p_meal_effective_from then
      select coalesce(max(revision), 0) + 1
        into v_meal_revision
      from public.payroll_meal_allowance_policy_versions;
      insert into public.payroll_meal_allowance_policy_versions (
        daily_amount, effective_from, revision, created_by, note
      ) values (
        p_meal_daily_amount, p_meal_effective_from, v_meal_revision, p_actor_user_id, nullif(btrim(p_meal_note), '')
      ) returning * into v_meal_created;
      v_meal_changed := true;
    end if;
  end if;

  return jsonb_build_object(
    'settings', to_jsonb(v_settings),
    'mealPolicyChanged', v_meal_changed,
    'mealPolicy', case when v_meal_changed then to_jsonb(v_meal_created) else null end
  );
end;
$$;

revoke all on function public.payroll_update_common_settings_v1(
  bigint, integer, integer, integer, boolean, numeric, integer, integer, integer, integer, integer, numeric, date, text
) from public, anon, authenticated;
grant execute on function public.payroll_update_common_settings_v1(
  bigint, integer, integer, integer, boolean, numeric, integer, integer, integer, integer, integer, numeric, date, text
) to service_role;

comment on function public.payroll_update_common_settings_v1(
  bigint, integer, integer, integer, boolean, numeric, integer, integer, integer, integer, integer, numeric, date, text
) is
  'payroll_settings 갱신과 식대 공통 정책(payroll_meal_allowance_policy_versions) 신규 revision 생성을 하나의 transaction으로 처리한다. owner/master만 실행 가능(payroll_assert_actor_v2). p_meal_daily_amount/p_meal_effective_from이 둘 다 null이면 식대 부분은 건드리지 않고, 값이 기존 최신 version과 동일하면 새 revision을 만들지 않는다. 기존 payroll_settings 직접 update(PATCH)와 payroll_create_meal_allowance_policy_version_v1(POST)은 호환을 위해 그대로 유지된다.';

commit;

-- Postflight (read only):
-- select count(*) from public.payroll_meal_allowance_policy_versions;              -- expect 0 직후 적용 시
-- select count(*) from public.payroll_meal_allowance_eligibility_versions;         -- expect 0 직후 적용 시
-- select relrowsecurity from pg_class where oid = 'public.payroll_meal_allowance_policy_versions'::regclass;
-- select relrowsecurity from pg_class where oid = 'public.payroll_meal_allowance_eligibility_versions'::regclass;
-- select tgname from pg_trigger where tgrelid = 'public.users'::regclass and not tgisinternal;
