alter table public.ledger_transactions drop constraint ledger_transactions_type_check;
alter table public.ledger_transactions add constraint ledger_transactions_type_check
  check (type in ('expense','income','sales','transfer','opening','balance_adjustment','investment','owner_settlement','card_settlement'));
alter table public.ledger_transactions drop constraint ledger_transaction_recognition_policy;
alter table public.ledger_transactions add constraint ledger_transaction_recognition_policy check (
  (type in ('income','expense','sales') and recognition_month is not null and recognition_month = date_trunc('month',recognition_month)::date and category_id is not null)
  or (type not in ('income','expense','sales') and recognition_month is null and category_id is null)
);
alter table public.ledger_transactions
  add column source_fingerprint text null,
  add column source_synced_at timestamptz null,
  add constraint ledger_transaction_source_sync_metadata check (
    (source_type = 'manual' and source_fingerprint is null and source_synced_at is null)
    or (source_type <> 'manual' and source_fingerprint is not null and source_synced_at is not null)
  );

create index ledger_transactions_source_synced_at_idx on public.ledger_transactions(source_synced_at desc) where source_synced_at is not null;

create table public.ledger_payment_method_mappings (
  id bigint generated by default as identity primary key,
  bucket text not null check (bucket in ('cash','transfer','card','other')),
  fund_account_id bigint not null references public.ledger_fund_accounts(id) on delete restrict,
  effective_from date not null,
  effective_to date null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint ledger_payment_mapping_period check (effective_to is null or effective_to >= effective_from),
  constraint ledger_payment_mapping_start_unique unique (bucket,effective_from)
);
create index ledger_payment_method_mappings_account_idx on public.ledger_payment_method_mappings(fund_account_id);
create index ledger_payment_method_mappings_lookup_idx on public.ledger_payment_method_mappings(bucket,effective_from desc,effective_to) where is_active=true;
alter table public.ledger_payment_method_mappings enable row level security;
revoke all on table public.ledger_payment_method_mappings from public,anon,authenticated,service_role;
revoke all on sequence public.ledger_payment_method_mappings_id_seq from public,anon,authenticated,service_role;
grant select on table public.ledger_payment_method_mappings to service_role;

insert into public.ledger_payment_method_mappings(bucket,fund_account_id,effective_from)
select mapping.bucket,account.id,date '2026-08-01'
from (values ('cash','store_cash'),('transfer','baba_corporate_bank'),('card','card_clearing'),('other','cho_personal_custody')) mapping(bucket,account_code)
join public.ledger_fund_accounts account on account.code=mapping.account_code;

insert into public.ledger_categories(name,kind,cost_behavior)
values('POS 매출','income','variable') on conflict (kind,name) do nothing;

create or replace function public.ledger_sync_pos_sales_v1(p_rows jsonb,p_actor_user_id bigint)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare
  v_role text; v_item jsonb; v_date date; v_bucket text; v_amount numeric; v_fingerprint text;
  v_snapshot jsonb; v_key text; v_account_id bigint; v_category_id bigint; v_existing public.ledger_transactions%rowtype;
  v_transaction_id bigint; v_now timestamptz:=now(); v_created integer:=0; v_updated integer:=0; v_unchanged integer:=0; v_drift integer:=0;
  v_processed_dates date[]:=array[]::date[];
begin
  select lower(role::text) into v_role from public.users where id=p_actor_user_id and is_active=true and app_login_enabled=true;
  if coalesce(v_role,'') not in ('owner','master') then return jsonb_build_object('status','forbidden'); end if;
  if jsonb_typeof(p_rows)<>'array' then return jsonb_build_object('status','invalid_rows'); end if;
  select id into v_category_id from public.ledger_categories where kind='income' and name='POS 매출' and is_active=true;
  if v_category_id is null then return jsonb_build_object('status','category_missing'); end if;

  for v_item in select value from jsonb_array_elements(p_rows) loop
    begin
      v_date:=(v_item->>'businessDate')::date; v_bucket:=v_item->>'bucket'; v_amount:=(v_item->>'amount')::numeric;
    exception when others then return jsonb_build_object('status','invalid_rows'); end;
    v_fingerprint:=nullif(v_item->>'fingerprint',''); v_snapshot:=v_item->'snapshot'; v_key:='pos:'||v_date::text||':'||v_bucket;
    if v_bucket not in ('cash','transfer','card','other') or v_amount<0 or v_amount<>trunc(v_amount) or v_fingerprint is null or jsonb_typeof(v_snapshot)<>'object' then return jsonb_build_object('status','invalid_rows'); end if;
    if not (v_date=any(v_processed_dates)) then v_processed_dates:=array_append(v_processed_dates,v_date); end if;
    perform pg_advisory_xact_lock(hashtext('ledger_pos_sync:'||v_key));
    select * into v_existing from public.ledger_transactions where source_type='pos_sales_daily_payment' and source_key=v_key for update;

    if v_existing.id is null and v_amount=0 then v_unchanged:=v_unchanged+1; continue; end if;
    if v_existing.id is null then
      select fund_account_id into v_account_id from public.ledger_payment_method_mappings
      where bucket=v_bucket and is_active=true and effective_from<=v_date and (effective_to is null or effective_to>=v_date)
      order by effective_from desc,id desc limit 1;
      if v_account_id is null then return jsonb_build_object('status','mapping_missing','businessDate',v_date,'bucket',v_bucket); end if;
      insert into public.ledger_transactions(operation_id,type,occurred_at,business_date,recognition_month,amount,category_id,status,source_type,source_key,source_snapshot,source_fingerprint,source_synced_at,memo,created_by,confirmed_by)
      values(gen_random_uuid(),'sales',(v_date+time '03:00') at time zone 'Asia/Ho_Chi_Minh',v_date,date_trunc('month',v_date)::date,v_amount,v_category_id,'confirmed','pos_sales_daily_payment',v_key,v_snapshot||jsonb_build_object('syncedAt',v_now),v_fingerprint,v_now,'POS '||v_bucket,p_actor_user_id,p_actor_user_id)
      returning id into v_transaction_id;
      insert into public.ledger_movements(transaction_id,fund_account_id,amount) values(v_transaction_id,v_account_id,v_amount);
      insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,after_snapshot,reason) values(p_actor_user_id,'pos_sync_created','transaction',v_transaction_id,(select to_jsonb(t) from public.ledger_transactions t where t.id=v_transaction_id),'POS automatic sync');
      v_created:=v_created+1;
    elsif v_existing.source_fingerprint=v_fingerprint and v_existing.status='confirmed' then
      update public.ledger_transactions set source_synced_at=v_now,updated_at=v_now where id=v_existing.id;
      v_unchanged:=v_unchanged+1;
    else
      v_drift:=v_drift+1;
      if v_amount=0 then
        update public.ledger_transactions set status='corrected',source_snapshot=v_snapshot||jsonb_build_object('syncedAt',v_now),source_fingerprint=v_fingerprint,source_synced_at=v_now,updated_at=v_now where id=v_existing.id;
      else
        update public.ledger_transactions set status='confirmed',amount=v_amount,recognition_month=date_trunc('month',v_date)::date,source_snapshot=v_snapshot||jsonb_build_object('syncedAt',v_now),source_fingerprint=v_fingerprint,source_synced_at=v_now,updated_at=v_now,confirmed_by=p_actor_user_id where id=v_existing.id;
        update public.ledger_movements set amount=v_amount where transaction_id=v_existing.id;
      end if;
      insert into public.ledger_audit_logs(actor_user_id,action,entity_type,entity_id,before_snapshot,after_snapshot,reason) values(p_actor_user_id,'pos_sync_drift_updated','transaction',v_existing.id,to_jsonb(v_existing),(select to_jsonb(t) from public.ledger_transactions t where t.id=v_existing.id),'POS source drift');
      v_updated:=v_updated+1;
    end if;
  end loop;
  return jsonb_build_object('status','ok','processedBusinessDates',to_jsonb(v_processed_dates),'createdCount',v_created,'updatedCount',v_updated,'unchangedCount',v_unchanged,'driftCount',v_drift);
end $$;

revoke all on function public.ledger_sync_pos_sales_v1(jsonb,bigint) from public,anon,authenticated;
grant execute on function public.ledger_sync_pos_sales_v1(jsonb,bigint) to service_role;

comment on table public.ledger_payment_method_mappings is 'Effective-dated POS payment bucket to BABA fund-account mapping. Existing movements retain their historical account.';
comment on function public.ledger_sync_pos_sales_v1(jsonb,bigint) is 'Atomically creates or drift-updates daily POS payment-bucket ledger rows without modifying POS source tables.';
