alter table public.pos_sales_receipts
  add column if not exists tax_override_mode text null,
  add column if not exists calculated_vat_amount numeric(14,2) null,
  add column if not exists calculated_final_amount numeric(14,2) null,
  add column if not exists final_amount_override numeric(14,2) null,
  add column if not exists revision bigint not null default 0;

alter table public.pos_sales_receipts
  drop constraint if exists pos_sales_receipts_tax_override_mode_check,
  add constraint pos_sales_receipts_tax_override_mode_check
    check (tax_override_mode is null or tax_override_mode in ('apply', 'exclude_all')),
  drop constraint if exists pos_sales_receipts_calculated_vat_amount_check,
  add constraint pos_sales_receipts_calculated_vat_amount_check
    check (calculated_vat_amount is null or calculated_vat_amount >= 0),
  drop constraint if exists pos_sales_receipts_calculated_final_amount_check,
  add constraint pos_sales_receipts_calculated_final_amount_check
    check (calculated_final_amount is null or calculated_final_amount >= 0),
  drop constraint if exists pos_sales_receipts_final_amount_override_check,
  add constraint pos_sales_receipts_final_amount_override_check
    check (final_amount_override is null or final_amount_override >= 0);

create table if not exists public.pos_sales_receipt_modifications (
  id bigint generated by default as identity primary key,
  receipt_id bigint not null references public.pos_sales_receipts(id) on delete cascade,
  request_id uuid not null,
  revision_before bigint not null,
  revision_after bigint not null,
  modified_by text not null,
  modification_note text null,
  before_state jsonb not null,
  after_state jsonb not null,
  result jsonb not null,
  created_at timestamptz not null default now(),
  unique (receipt_id, request_id)
);

alter table public.pos_sales_receipt_modifications enable row level security;

create or replace function public.admin_update_paid_sales_receipt(
  p_receipt_id bigint,
  p_expected_revision bigint,
  p_request_id uuid,
  p_actor_username text,
  p_modification_note text,
  p_tax_override_mode text,
  p_final_amount_override numeric,
  p_payment_method text,
  p_cash_received_amount numeric,
  p_lines jsonb
) returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_receipt public.pos_sales_receipts%rowtype;
  v_existing_result jsonb;
  v_now timestamptz := clock_timestamp();
  v_original_tax_summary jsonb;
  v_original_amount_summary jsonb;
  v_total numeric(14,2);
  v_calculated_vat numeric(14,2);
  v_calculated_final numeric(14,2);
  v_override numeric(14,2);
  v_final numeric(14,2);
  v_applied_vat numeric(14,2);
  v_receive numeric;
  v_return numeric;
  v_inventory_changed boolean := false;
  v_next_revision bigint;
  v_before jsonb;
  v_after jsonb;
  v_result jsonb;
  v_line jsonb;
  v_line_id bigint;
  v_kept_ids bigint[] := array[]::bigint[];
begin
  if p_request_id is null then raise exception 'receipt_request_id_required'; end if;
  if p_actor_username is null or btrim(p_actor_username) = '' then
    raise exception 'receipt_actor_required';
  end if;
  if p_tax_override_mode not in ('apply', 'exclude_all') then
    raise exception 'receipt_invalid_tax_mode';
  end if;
  if p_payment_method not in ('cash', 'other') then
    raise exception 'receipt_invalid_payment_method';
  end if;
  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'receipt_lines_required';
  end if;
  if p_final_amount_override is not null and
     (p_final_amount_override < 0 or p_final_amount_override > 999999999999 or
      p_final_amount_override <> trunc(p_final_amount_override)) then
    raise exception 'receipt_invalid_final_amount';
  end if;

  select modification.result into v_existing_result
  from public.pos_sales_receipt_modifications modification
  where modification.receipt_id = p_receipt_id
    and modification.request_id = p_request_id;
  if v_existing_result is not null then return v_existing_result; end if;

  select * into v_receipt
  from public.pos_sales_receipts receipt
  where receipt.id = p_receipt_id
  for update;
  if not found then raise exception 'receipt_not_found'; end if;
  select modification.result into v_existing_result
  from public.pos_sales_receipt_modifications modification
  where modification.receipt_id = p_receipt_id
    and modification.request_id = p_request_id;
  if v_existing_result is not null then return v_existing_result; end if;
  if v_receipt.source not in ('cukcuk', 'manual') then raise exception 'receipt_source_not_editable'; end if;
  if v_receipt.payment_status is distinct from 3 then raise exception 'receipt_not_paid'; end if;
  if v_receipt.is_canceled then raise exception 'receipt_canceled'; end if;
  if v_receipt.revision is distinct from p_expected_revision then
    raise exception 'receipt_revision_conflict';
  end if;

  v_original_tax_summary := coalesce(v_receipt.original_tax_summary, jsonb_build_object(
    'totalTaxAmount', v_receipt.vat_amount,
    'taxByRate', coalesce((
      select jsonb_agg(jsonb_build_object(
        'taxRate', bucket.tax_rate,
        'taxAmount', bucket.tax_amount,
        'lineCount', bucket.line_count
      ) order by bucket.tax_rate)
      from (
        select coalesce(line.tax_rate, 0) tax_rate,
               sum(coalesce(line.tax_amount, 0)) tax_amount,
               count(*) line_count
        from public.pos_sales_receipt_lines line
        where line.receipt_id = p_receipt_id and line.is_excluded is not true
        group by coalesce(line.tax_rate, 0)
      ) bucket
    ), '[]'::jsonb)
  ));
  v_original_amount_summary := coalesce(v_receipt.original_amount_summary, jsonb_build_object(
    'totalAmount', v_receipt.total_amount,
    'vatAmount', v_receipt.vat_amount,
    'finalAmount', v_receipt.final_amount,
    'paymentTotalAmount', coalesce((select sum(payment.amount)
      from public.pos_sales_receipt_payments payment where payment.receipt_id = p_receipt_id), v_receipt.final_amount)
  ));

  if exists (
    select 1 from jsonb_array_elements(p_lines) item
    where coalesce(item->>'mapping_status', '') not in ('unmapped','direct','manual','recipe','option','ignore')
       or coalesce((item->>'quantity')::numeric, 0) <= 0
  ) then raise exception 'receipt_invalid_line'; end if;

  select coalesce(sum((item->>'final_amount')::numeric), 0),
         case when p_tax_override_mode = 'exclude_all' then 0 else
           coalesce(sum(round((item->>'final_amount')::numeric * coalesce((item->>'tax_rate')::numeric, 0) / 100)), 0)
         end
    into v_total, v_calculated_vat
  from jsonb_array_elements(p_lines) item;
  v_total := round(v_total);
  v_calculated_vat := round(v_calculated_vat);
  v_calculated_final := v_total + v_calculated_vat;
  v_override := case
    when p_final_amount_override is null or p_final_amount_override = v_calculated_final then null
    else p_final_amount_override end;
  v_final := coalesce(v_override, v_calculated_final);
  v_applied_vat := case when p_tax_override_mode = 'exclude_all' then 0
    else coalesce((v_original_tax_summary->>'totalTaxAmount')::numeric, v_receipt.vat_amount) end;
  v_receive := case when p_payment_method = 'cash' then p_cash_received_amount else v_final end;
  if p_payment_method = 'cash' and
     (v_receive is null or v_receive < v_final or v_receive > 999999999999 or
      v_receive <> trunc(v_receive)) then
    raise exception 'receipt_invalid_cash_received';
  end if;
  v_return := case when p_payment_method = 'cash' then greatest(0, v_receive - v_final) else 0 end;

  v_inventory_changed := exists (
    select 1 from jsonb_array_elements(p_lines) item
    where item->>'id' is null
       or not exists (
         select 1 from public.pos_sales_receipt_lines current_line
         where current_line.id = (item->>'id')::bigint
           and current_line.receipt_id = p_receipt_id
           and current_line.is_excluded is not true
           and current_line.quantity = (item->>'quantity')::numeric
           and coalesce(current_line.item_id, '') = coalesce(item->>'item_id', '')
           and coalesce(current_line.item_code, '') = coalesce(item->>'item_code', '')
           and coalesce(current_line.parent_ref_detail_id, '') = coalesce(item->>'parent_ref_detail_id', '')
       )
  ) or exists (
    select 1 from public.pos_sales_receipt_lines current_line
    where current_line.receipt_id = p_receipt_id and current_line.is_excluded is not true
      and not exists (select 1 from jsonb_array_elements(p_lines) item
                      where item->>'id' is not null and (item->>'id')::bigint = current_line.id)
  );

  v_before := jsonb_build_object(
    'taxOverrideMode', v_receipt.tax_override_mode,
    'totalAmount', v_receipt.total_amount,
    'calculatedVatAmount', v_receipt.calculated_vat_amount,
    'calculatedFinalAmount', v_receipt.calculated_final_amount,
    'finalAmountOverride', v_receipt.final_amount_override,
    'vatAmount', v_receipt.vat_amount,
    'finalAmount', v_receipt.final_amount,
    'revision', v_receipt.revision
  );

  for v_line in select value from jsonb_array_elements(p_lines) loop
    v_line_id := nullif(v_line->>'id', '')::bigint;
    if v_line_id is not null then
      update public.pos_sales_receipt_lines set
        sort_order=(v_line->>'sort_order')::integer, ref_detail_id=v_line->>'ref_detail_id',
        parent_ref_detail_id=nullif(v_line->>'parent_ref_detail_id',''), item_id=nullif(v_line->>'item_id',''),
        item_code=nullif(v_line->>'item_code',''), item_name=v_line->>'item_name', unit_name=nullif(v_line->>'unit_name',''),
        quantity=(v_line->>'quantity')::numeric, unit_price=(v_line->>'unit_price')::numeric,
        amount=(v_line->>'amount')::numeric, discount_amount=(v_line->>'discount_amount')::numeric,
        final_amount=(v_line->>'final_amount')::numeric, tax_rate=nullif(v_line->>'tax_rate','')::numeric,
        tax_amount=(v_line->>'tax_amount')::numeric, pre_tax_amount=(v_line->>'pre_tax_amount')::numeric,
        tax_reduction_amount=coalesce((v_line->>'tax_reduction_amount')::numeric,0),
        ref_detail_type=(v_line->>'ref_detail_type')::integer,
        inventory_item_type=nullif(v_line->>'inventory_item_type','')::integer,
        is_option=(v_line->>'is_option')::boolean, mapping_status=v_line->>'mapping_status',
        raw_json=coalesce(v_line->'raw_json','{}'::jsonb), updated_at=v_now
      where id=v_line_id and receipt_id=p_receipt_id and is_excluded is not true;
      if not found then raise exception 'receipt_line_conflict'; end if;
      v_kept_ids := array_append(v_kept_ids, v_line_id);
    else
      insert into public.pos_sales_receipt_lines (
        source,receipt_id,receipt_ref_id,ref_detail_id,parent_ref_detail_id,business_date,ref_date,sort_order,
        item_id,item_code,item_name,unit_name,quantity,unit_price,amount,discount_amount,final_amount,
        tax_rate,tax_amount,pre_tax_amount,tax_reduction_amount,ref_detail_type,inventory_item_type,is_option,
        is_excluded,mapping_status,payment_status,is_canceled,raw_json,synced_at,updated_at
      ) values (
        'manual',p_receipt_id,v_receipt.ref_id,v_line->>'ref_detail_id',nullif(v_line->>'parent_ref_detail_id',''),
        v_receipt.business_date,v_receipt.ref_date,(v_line->>'sort_order')::integer,nullif(v_line->>'item_id',''),
        nullif(v_line->>'item_code',''),v_line->>'item_name',nullif(v_line->>'unit_name',''),
        (v_line->>'quantity')::numeric,(v_line->>'unit_price')::numeric,(v_line->>'amount')::numeric,
        (v_line->>'discount_amount')::numeric,(v_line->>'final_amount')::numeric,nullif(v_line->>'tax_rate','')::numeric,
        (v_line->>'tax_amount')::numeric,(v_line->>'pre_tax_amount')::numeric,
        coalesce((v_line->>'tax_reduction_amount')::numeric,0),(v_line->>'ref_detail_type')::integer,
        nullif(v_line->>'inventory_item_type','')::integer,(v_line->>'is_option')::boolean,false,
        v_line->>'mapping_status',3,false,coalesce(v_line->'raw_json','{}'::jsonb),v_now,v_now
      ) returning id into v_line_id;
      v_kept_ids := array_append(v_kept_ids, v_line_id);
    end if;
  end loop;

  delete from public.pos_sales_receipt_lines line
  where line.receipt_id=p_receipt_id and line.is_excluded is not true
    and not (line.id = any(v_kept_ids));

  delete from public.pos_sales_receipt_payments where receipt_id=p_receipt_id;
  insert into public.pos_sales_receipt_payments (
    source,receipt_id,receipt_ref_id,business_date,ref_date,payment_type,payment_name,card_id,card_name,
    amount,raw_json,synced_at,updated_at
  ) values (
    'manual',p_receipt_id,v_receipt.ref_id,v_receipt.business_date,v_receipt.ref_date,null,
    case when p_payment_method='cash' then 'Tiền mặt' else 'Khác' end,null,null,v_final,
    jsonb_build_object('source','manual-receipt-edit','paymentMethod',p_payment_method,'requestId',p_request_id),v_now,v_now
  );

  v_next_revision := v_receipt.revision + 1;
  update public.pos_sales_receipts set
    total_amount=v_total,
    discount_amount=(select coalesce(sum((item->>'discount_amount')::numeric),0) from jsonb_array_elements(p_lines) item),
    calculated_vat_amount=v_calculated_vat, calculated_final_amount=v_calculated_final,
    final_amount_override=v_override, tax_override_mode=p_tax_override_mode,
    vat_amount=v_applied_vat, final_amount=v_final, receive_amount=v_receive, return_amount=v_return,
    original_tax_summary=coalesce(original_tax_summary,v_original_tax_summary),
    original_amount_summary=coalesce(original_amount_summary,v_original_amount_summary),
    is_modified=true, modified_at=v_now, modified_by=p_actor_username,
    modification_note=nullif(btrim(p_modification_note),''), revision=v_next_revision,
    inventory_deduction_auto_eligible_at=v_now,
    inventory_deduction_processing_paused=false,
    inventory_deduction_processing_paused_at=null,
    inventory_deduction_processing_error=null,
    inventory_deduction_reprocess_required=v_inventory_changed,
    inventory_deduction_last_checked_at=null,
    inventory_deduction_pending_fingerprint=null,
    inventory_deduction_pending_status=null,
    updated_at=v_now
  where id=p_receipt_id;

  v_after := jsonb_build_object(
    'taxOverrideMode', p_tax_override_mode, 'totalAmount', v_total,
    'calculatedVatAmount', v_calculated_vat, 'calculatedFinalAmount', v_calculated_final,
    'finalAmountOverride', v_override, 'vatAmount', v_applied_vat,
    'finalAmount', v_final, 'paymentMethod', p_payment_method,
    'inventoryContentChanged', v_inventory_changed, 'revision', v_next_revision
  );
  v_result := v_after || jsonb_build_object('receiveAmount',v_receive,'returnAmount',v_return,
    'isModified',true,'modifiedAt',v_now,'modifiedBy',p_actor_username,
    'modificationNote',nullif(btrim(p_modification_note),''));
  insert into public.pos_sales_receipt_modifications (
    receipt_id,request_id,revision_before,revision_after,modified_by,modification_note,before_state,after_state,result
  ) values (p_receipt_id,p_request_id,v_receipt.revision,v_next_revision,p_actor_username,
    nullif(btrim(p_modification_note),''),v_before,v_after,v_result);
  return v_result;
end;
$$;

revoke all on function public.admin_update_paid_sales_receipt(bigint,bigint,uuid,text,text,text,numeric,text,numeric,jsonb)
  from public, anon, authenticated;
grant execute on function public.admin_update_paid_sales_receipt(bigint,bigint,uuid,text,text,text,numeric,text,numeric,jsonb)
  to service_role;

revoke all on table public.pos_sales_receipt_modifications from public, anon, authenticated;
grant select, insert on table public.pos_sales_receipt_modifications to service_role;
grant usage, select on sequence public.pos_sales_receipt_modifications_id_seq to service_role;
