begin;

alter table public.payroll_settings
  add column if not exists employee_insurance_rate_bp smallint not null default 1050,
  add column if not exists employer_insurance_rate_bp smallint not null default 2150,
  add column if not exists director_insurance_enabled boolean not null default true,
  add column if not exists director_insurance_base_amount numeric(16,0) not null default 9000000,
  add column if not exists director_insurance_rate_bp smallint not null default 3200;

alter table public.payroll_settings
  add constraint payroll_settings_employee_insurance_rate_check check (employee_insurance_rate_bp between 0 and 10000),
  add constraint payroll_settings_employer_insurance_rate_check check (employer_insurance_rate_bp between 0 and 10000),
  add constraint payroll_settings_director_insurance_base_check check (director_insurance_base_amount >= 0 and director_insurance_base_amount = trunc(director_insurance_base_amount)),
  add constraint payroll_settings_director_insurance_rate_check check (director_insurance_rate_bp between 0 and 10000);

create table public.payroll_insurance_setting_versions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  is_enrolled boolean not null,
  insurance_base_amount numeric(16,0) not null,
  effective_month date not null,
  revision bigint not null,
  created_by bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  note text null,
  constraint payroll_insurance_setting_month_check check (effective_month = date_trunc('month',effective_month)::date),
  constraint payroll_insurance_setting_revision_check check (revision >= 1),
  constraint payroll_insurance_setting_base_check check (
    insurance_base_amount = trunc(insurance_base_amount)
    and ((is_enrolled and insurance_base_amount >= 1) or (not is_enrolled and insurance_base_amount = 0))
  ),
  constraint payroll_insurance_setting_version_unique unique(user_id,revision)
);

create index payroll_insurance_setting_lookup_idx
  on public.payroll_insurance_setting_versions(user_id,effective_month desc,revision desc);
create index payroll_insurance_setting_created_by_idx
  on public.payroll_insurance_setting_versions(created_by);

alter table public.payroll_insurance_setting_versions enable row level security;
revoke all on table public.payroll_insurance_setting_versions from public,anon,authenticated,service_role;
revoke all on sequence public.payroll_insurance_setting_versions_id_seq from public,anon,authenticated,service_role;
grant select,insert on table public.payroll_insurance_setting_versions to service_role;
grant usage,select on sequence public.payroll_insurance_setting_versions_id_seq to service_role;

do $$
declare v_creator_id bigint;
begin
  select id into v_creator_id from public.users where is_active=true and role in('owner','master') order by case role when 'owner' then 0 else 1 end,id limit 1;
  if v_creator_id is null then raise exception 'PAYROLL_INSURANCE_SEED_ACTOR_NOT_FOUND'; end if;
  if (select count(*) from public.users where username in('quyen','linh_h','uyen','nhon')) <> 4
    or (select count(distinct username) from public.users where username in('quyen','linh_h','uyen','nhon')) <> 4 then
    raise exception 'PAYROLL_INSURANCE_SEED_USERS_NOT_FOUND';
  end if;
  if exists(
    select 1 from public.payroll_insurance_setting_versions v
    join public.users u on u.id=v.user_id
    where u.username in('quyen','linh_h','uyen','nhon') and v.revision=1
      and (v.effective_month<>date '2026-07-01' or not v.is_enrolled or v.insurance_base_amount<>5000000)
  ) then raise exception 'PAYROLL_INSURANCE_SEED_VERSION_CONFLICT';end if;
  insert into public.payroll_insurance_setting_versions(user_id,is_enrolled,insurance_base_amount,effective_month,revision,created_by,note)
  select u.id,true,5000000,date '2026-07-01',1,v_creator_id,'Initial payroll insurance enrollment'
  from public.users u
  where u.username in('quyen','linh_h','uyen','nhon')
    and not exists(select 1 from public.payroll_insurance_setting_versions v where v.user_id=u.id and v.effective_month=date '2026-07-01' and v.revision=1);
end $$;

alter table public.payroll_run_items drop constraint payroll_run_items_category_check;
alter table public.payroll_run_items add constraint payroll_run_items_category_check check (category in ('base_work','paid_leave','overtime','late_deduction','early_leave_deduction','insurance_employee_deduction','incentive','meal','transport','housing','insurance_tax','advance','penalty','other_addition','other_deduction'));
alter table public.payroll_run_items drop constraint payroll_run_item_category_direction_check;
alter table public.payroll_run_items add constraint payroll_run_item_category_direction_check check (
  (category in ('base_work','paid_leave','overtime','incentive','meal','transport','housing','other_addition') and direction='addition') or
  (category in ('late_deduction','early_leave_deduction','insurance_employee_deduction','insurance_tax','advance','penalty','other_deduction') and direction='deduction')
);
alter table public.payroll_run_items add constraint payroll_run_item_employee_insurance_shape_check check (
  category<>'insurance_employee_deduction' or (item_type='automatic' and direction='deduction' and business_date is null)
);
create unique index payroll_run_item_employee_insurance_unique on public.payroll_run_items(payroll_run_employee_id) where item_type='automatic' and category='insurance_employee_deduction';

alter table public.payroll_run_employees
  add column if not exists insurance_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists pre_insurance_payout_amount bigint not null default 0,
  add column if not exists employee_insurance_deduction_amount bigint not null default 0 check (employee_insurance_deduction_amount >= 0),
  add column if not exists employer_insurance_amount bigint not null default 0 check (employer_insurance_amount >= 0);

alter table public.payroll_runs
  add column if not exists insurance_settings_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists total_pre_insurance_payout_amount bigint not null default 0,
  add column if not exists total_employee_insurance_deduction_amount bigint not null default 0 check (total_employee_insurance_deduction_amount >= 0),
  add column if not exists total_employer_insurance_amount bigint not null default 0 check (total_employer_insurance_amount >= 0),
  add column if not exists director_insurance_amount bigint not null default 0 check (director_insurance_amount >= 0),
  add column if not exists total_insurance_remittance_amount bigint not null default 0 check (total_insurance_remittance_amount >= 0),
  add column if not exists total_company_cost_amount bigint not null default 0;

create function public.payroll_create_insurance_setting_version_v1(
  p_user_id bigint,p_is_enrolled boolean,p_insurance_base_amount bigint,p_effective_month date,p_actor_user_id bigint,p_note text
) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_revision bigint;v_created public.payroll_insurance_setting_versions%rowtype;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);
  if p_effective_month<>date_trunc('month',p_effective_month)::date then raise exception 'PAYROLL_INSURANCE_INVALID_MONTH' using errcode='22023';end if;
  if (p_is_enrolled and p_insurance_base_amount<1) or (not p_is_enrolled and p_insurance_base_amount<>0) then raise exception 'PAYROLL_INSURANCE_INVALID_BASE' using errcode='22023';end if;
  perform 1 from public.users where id=p_user_id and is_system_account=false and username<>'mjk';
  if not found then raise exception 'PAYROLL_INSURANCE_USER_NOT_FOUND' using errcode='P0002';end if;
  perform pg_advisory_xact_lock(p_user_id);
  select coalesce(max(revision),0)+1 into v_revision from public.payroll_insurance_setting_versions where user_id=p_user_id;
  insert into public.payroll_insurance_setting_versions(user_id,is_enrolled,insurance_base_amount,effective_month,revision,created_by,note)
  values(p_user_id,p_is_enrolled,p_insurance_base_amount,p_effective_month,v_revision,p_actor_user_id,nullif(btrim(p_note),'')) returning * into v_created;
  return to_jsonb(v_created);
end $$;

create function public.payroll_refresh_totals_v3(p_run_id bigint) returns void language plpgsql security definer set search_path=public as $$
begin
  update public.payroll_run_employees e set
    calculation_status=case when exists(select 1 from public.payroll_run_reviews rv where rv.payroll_run_employee_id=e.id and rv.status='open') then 'requires_review' else 'calculated' end,
    recognized_workdays=coalesce(x.recognized_days,0),recognized_minutes=coalesce(x.recognized_minutes,0),late_minutes=coalesce(x.late_minutes,0),early_leave_minutes=coalesce(x.early_leave_minutes,0),overtime_candidate_minutes=coalesce(x.overtime_minutes,0),
    base_amount=coalesce(x.base_amount,0),addition_amount=coalesce(x.additions,0),deduction_amount=coalesce(x.deductions,0),
    pre_insurance_payout_amount=coalesce(x.base_amount,0)+coalesce(x.additions,0)-coalesce(x.non_insurance_deductions,0),
    employee_insurance_deduction_amount=coalesce(x.employee_insurance_deduction,0),
    employer_insurance_amount=case when coalesce((e.insurance_snapshot->>'isEnrolled')::boolean,false) then coalesce((e.insurance_snapshot->>'employerAmount')::bigint,0) else 0 end,
    net_amount=coalesce(x.base_amount,0)+coalesce(x.additions,0)-coalesce(x.non_insurance_deductions,0)-coalesce(x.employee_insurance_deduction,0),updated_at=now()
  from(select re.id,
    coalesce(sum(i.amount) filter(where i.direction='addition' and i.category in('base_work','paid_leave')),0)::bigint base_amount,
    coalesce(sum(i.amount) filter(where i.direction='addition' and i.category not in('base_work','paid_leave')),0)::bigint additions,
    coalesce(sum(i.amount) filter(where i.direction='deduction'),0)::bigint deductions,
    coalesce(sum(i.amount) filter(where i.direction='deduction' and i.category<>'insurance_employee_deduction'),0)::bigint non_insurance_deductions,
    coalesce(sum(i.amount) filter(where i.category='insurance_employee_deduction'),0)::bigint employee_insurance_deduction,
    coalesce(sum((i.source_snapshot->>'recognizedDays')::numeric) filter(where i.category in('base_work','paid_leave')),0) recognized_days,
    coalesce(sum((i.source_snapshot->>'recognizedMinutes')::integer) filter(where i.category in('base_work','paid_leave')),0)::integer recognized_minutes,
    coalesce(sum((i.source_snapshot->>'lateMinutes')::integer) filter(where i.category='base_work'),0)::integer late_minutes,
    coalesce(sum((i.source_snapshot->>'earlyLeaveMinutes')::integer) filter(where i.category='base_work'),0)::integer early_leave_minutes,
    coalesce(sum((i.source_snapshot->>'overtimeCandidateMinutes')::integer) filter(where i.category='base_work'),0)::integer overtime_minutes
    from public.payroll_run_employees re left join public.payroll_run_items i on i.payroll_run_employee_id=re.id where re.payroll_run_id=p_run_id group by re.id)x where e.id=x.id;
  update public.payroll_runs r set employee_count=x.employee_count,requires_review_count=x.review_count,total_base_amount=x.base_amount,total_addition_amount=x.additions,total_deduction_amount=x.deductions,total_net_amount=x.net_amount,
    total_pre_insurance_payout_amount=x.pre_insurance,total_employee_insurance_deduction_amount=x.employee_insurance,total_employer_insurance_amount=x.employer_insurance,
    director_insurance_amount=coalesce((r.insurance_settings_snapshot->'director'->>'calculatedAmount')::bigint,0),
    total_insurance_remittance_amount=x.employee_insurance+x.employer_insurance+coalesce((r.insurance_settings_snapshot->'director'->>'calculatedAmount')::bigint,0),
    total_company_cost_amount=x.pre_insurance+x.employer_insurance+coalesce((r.insurance_settings_snapshot->'director'->>'calculatedAmount')::bigint,0),updated_at=now()
  from(select count(*)::integer employee_count,count(*) filter(where calculation_status='requires_review')::integer review_count,coalesce(sum(base_amount),0)::bigint base_amount,coalesce(sum(addition_amount),0)::bigint additions,coalesce(sum(deduction_amount),0)::bigint deductions,coalesce(sum(net_amount),0)::bigint net_amount,coalesce(sum(pre_insurance_payout_amount),0)::bigint pre_insurance,coalesce(sum(employee_insurance_deduction_amount),0)::bigint employee_insurance,coalesce(sum(employer_insurance_amount),0)::bigint employer_insurance from public.payroll_run_employees where payroll_run_id=p_run_id)x where r.id=p_run_id;
end $$;

create function public.payroll_insert_payload_v3(p_run_id bigint,p_employees jsonb,p_actor_user_id bigint,p_copy_manual_from_run_id bigint default null) returns void language plpgsql security definer set search_path=public as $$
declare v_employee jsonb;v_employee_id bigint;v_item jsonb;v_review jsonb;
begin
  if jsonb_typeof(p_employees)<>'array' then raise exception 'PAYROLL_INVALID_EMPLOYEES';end if;
  for v_employee in select value from jsonb_array_elements(p_employees) loop
    insert into public.payroll_run_employees(payroll_run_id,user_id,employee_name,contract_snapshot,attendance_snapshot,insurance_snapshot,recognized_workdays,recognized_minutes,late_minutes,early_leave_minutes,overtime_candidate_minutes)
    values(p_run_id,(v_employee->>'userId')::bigint,v_employee->>'employeeName',coalesce(v_employee->'contractSnapshot','[]'::jsonb),v_employee->'attendanceSnapshot',coalesce(v_employee->'insuranceSnapshot','{}'::jsonb),coalesce((v_employee->>'recognizedWorkdays')::numeric,0),coalesce((v_employee->>'recognizedMinutes')::integer,0),coalesce((v_employee->>'lateMinutes')::integer,0),coalesce((v_employee->>'earlyLeaveMinutes')::integer,0),coalesce((v_employee->>'overtimeCandidateMinutes')::integer,0)) returning id into v_employee_id;
    for v_item in select value from jsonb_array_elements(coalesce(v_employee->'items','[]'::jsonb)) loop
      insert into public.payroll_run_items(payroll_run_employee_id,item_type,category,direction,amount,original_amount,business_date,source_snapshot,description,created_by)
      values(v_employee_id,'automatic',v_item->>'category',v_item->>'direction',(v_item->>'amount')::bigint,(v_item->>'originalAmount')::bigint,(v_item->>'businessDate')::date,coalesce(v_item->'sourceSnapshot','{}'::jsonb),v_item->>'description',p_actor_user_id);
    end loop;
    for v_review in select value from jsonb_array_elements(coalesce(v_employee->'reviews','[]'::jsonb)) loop
      insert into public.payroll_run_reviews(payroll_run_employee_id,warning_code,review_level,business_date,source_snapshot)
      values(v_employee_id,v_review->>'warningCode',v_review->>'reviewLevel',(v_review->>'businessDate')::date,coalesce(v_review->'sourceSnapshot','{}'::jsonb));
    end loop;
    if p_copy_manual_from_run_id is not null then
      insert into public.payroll_run_items(payroll_run_employee_id,item_type,category,direction,amount,original_amount,business_date,source_snapshot,description,reason,created_by)
      select v_employee_id,'manual',i.category,i.direction,i.amount,i.original_amount,i.business_date,i.source_snapshot,i.description,i.reason,p_actor_user_id from public.payroll_run_items i join public.payroll_run_employees old_e on old_e.id=i.payroll_run_employee_id where old_e.payroll_run_id=p_copy_manual_from_run_id and old_e.user_id=(v_employee->>'userId')::bigint and i.item_type='manual';
    end if;
  end loop;
  perform public.payroll_refresh_totals_v3(p_run_id);
end $$;

create function public.payroll_create_run_v3(p_month date,p_calculated_at timestamptz,p_engine_version text,p_source_snapshot jsonb,p_employees jsonb,p_actor_user_id bigint) returns bigint language plpgsql security definer set search_path=public as $$
declare v_run_id bigint;v_revision bigint;v_payment_day integer;v_payment_offset integer;v_payment_due_date date;v_schedule_snapshot jsonb;v_insurance_snapshot jsonb;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);
  if p_engine_version<>'monthly-payroll-v5' then raise exception 'PAYROLL_ENGINE_VERSION_MISMATCH' using errcode='22023';end if;
  if p_month<date '2026-07-01' or p_month<>date_trunc('month',p_month)::date then raise exception 'PAYROLL_MONTH_NOT_SUPPORTED' using errcode='22023';end if;
  select payment_day,payment_month_offset into v_payment_day,v_payment_offset from public.payroll_settings where id=1;
  if not found then raise exception 'PAYROLL_SETTINGS_NOT_FOUND';end if;
  v_payment_due_date:=(date_trunc('month',p_month)+(v_payment_offset||' month')::interval+(v_payment_day-1||' day')::interval)::date;v_schedule_snapshot:=jsonb_build_object('paymentDay',v_payment_day,'paymentMonthOffset',v_payment_offset);v_insurance_snapshot:=coalesce(p_source_snapshot->'insuranceSettings','{}'::jsonb);
  perform pg_advisory_xact_lock(82117,(extract(year from p_month)::integer*100+extract(month from p_month)::integer));
  if exists(select 1 from public.payroll_runs where payroll_month=p_month and status in('draft','finalized','paid')) then raise exception 'PAYROLL_ACTIVE_RUN_EXISTS' using errcode='23505';end if;
  select coalesce(max(revision),0)+1 into v_revision from public.payroll_runs where payroll_month=p_month;
  insert into public.payroll_runs(payroll_month,revision,status,calculated_at,engine_version,source_snapshot,created_by,payment_due_date,payment_schedule_snapshot,insurance_settings_snapshot)
  values(p_month,v_revision,'draft',p_calculated_at,p_engine_version,p_source_snapshot||jsonb_build_object('paymentSchedule',v_schedule_snapshot),p_actor_user_id,v_payment_due_date,v_schedule_snapshot,v_insurance_snapshot) returning id into v_run_id;
  perform public.payroll_insert_payload_v3(v_run_id,p_employees,p_actor_user_id,null);
  insert into public.payroll_run_audit_logs(payroll_run_id,action,actor_user_id,after_snapshot) select id,'run_created',p_actor_user_id,to_jsonb(r) from public.payroll_runs r where id=v_run_id;
  return v_run_id;
end $$;

create function public.payroll_recalculate_run_v3(p_run_id bigint,p_calculated_at timestamptz,p_engine_version text,p_source_snapshot jsonb,p_employees jsonb,p_actor_user_id bigint) returns bigint language plpgsql security definer set search_path=public as $$
declare v_old public.payroll_runs%rowtype;v_new_id bigint;v_revision bigint;v_insurance_snapshot jsonb;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);if p_engine_version<>'monthly-payroll-v5' then raise exception 'PAYROLL_ENGINE_VERSION_MISMATCH';end if;
  select * into v_old from public.payroll_runs where id=p_run_id for update;if not found then raise exception 'PAYROLL_RUN_NOT_FOUND';end if;if v_old.status<>'draft' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000';end if;
  perform pg_advisory_xact_lock(82117,(extract(year from v_old.payroll_month)::integer*100+extract(month from v_old.payroll_month)::integer));select coalesce(max(revision),0)+1 into v_revision from public.payroll_runs where payroll_month=v_old.payroll_month;v_insurance_snapshot:=coalesce(p_source_snapshot->'insuranceSettings','{}'::jsonb);
  insert into public.payroll_runs(payroll_month,revision,status,calculated_at,engine_version,source_snapshot,created_by,payment_due_date,payment_schedule_snapshot,insurance_settings_snapshot)
  values(v_old.payroll_month,v_revision,'cancelled',p_calculated_at,p_engine_version,p_source_snapshot||jsonb_build_object('paymentSchedule',v_old.payment_schedule_snapshot),p_actor_user_id,v_old.payment_due_date,v_old.payment_schedule_snapshot,v_insurance_snapshot) returning id into v_new_id;
  perform public.payroll_insert_payload_v3(v_new_id,p_employees,p_actor_user_id,v_old.id);
  insert into public.payroll_run_audit_logs(payroll_run_id,action,actor_user_id,before_snapshot,after_snapshot) values(v_old.id,'run_recalculated',p_actor_user_id,to_jsonb(v_old),jsonb_build_object('replacementRunId',v_new_id,'replacementRevision',v_revision));
  update public.payroll_runs set status='cancelled',cancelled_by=p_actor_user_id,cancelled_at=now(),cancel_reason='Recalculated',updated_at=now() where id=v_old.id;update public.payroll_runs set status='draft',updated_at=now() where id=v_new_id;
  insert into public.payroll_run_audit_logs(payroll_run_id,action,actor_user_id,after_snapshot) select id,'run_created',p_actor_user_id,to_jsonb(r) from public.payroll_runs r where id=v_new_id;return v_new_id;
end $$;

create function public.payroll_mutate_item_v3(p_run_id bigint,p_run_employee_id bigint,p_item_id bigint,p_operation text,p_category text,p_direction text,p_amount bigint,p_description text,p_reason text,p_actor_user_id bigint) returns bigint language plpgsql security definer set search_path=public as $$
declare v_item_id bigint;
begin
  v_item_id:=public.payroll_mutate_item_v2(p_run_id,p_run_employee_id,p_item_id,p_operation,p_category,p_direction,p_amount,p_description,p_reason,p_actor_user_id);perform public.payroll_refresh_totals_v3(p_run_id);return v_item_id;
end $$;

create function public.payroll_resolve_review_v3(p_run_id bigint,p_run_employee_id bigint,p_review_id bigint,p_action text,p_custom_minutes integer,p_reason text,p_actor_user_id bigint) returns void language plpgsql security definer set search_path=public as $$
begin
  perform public.payroll_resolve_review_v2(p_run_id,p_run_employee_id,p_review_id,p_action,p_custom_minutes,p_reason,p_actor_user_id);perform public.payroll_refresh_totals_v3(p_run_id);
end $$;

create function public.payroll_transition_run_v3(p_run_id bigint,p_action text,p_reason text,p_payment_date date,p_payment_method text,p_payment_note text,p_actor_user_id bigint) returns void language plpgsql security definer set search_path=public as $$
declare v_run public.payroll_runs%rowtype;v_settings public.payroll_settings%rowtype;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);
  select * into v_run from public.payroll_runs where id=p_run_id for update;
  if not found then raise exception 'PAYROLL_RUN_NOT_FOUND';end if;
  if p_action in('finalize','force_finalize') and (v_run.engine_version='monthly-payroll-v5' or v_run.insurance_settings_snapshot<>'{}'::jsonb) then
    select * into v_settings from public.payroll_settings where id=1;
    if not found
      or not (v_run.insurance_settings_snapshot ? 'employeeRateBp')
      or (v_run.insurance_settings_snapshot->>'employeeRateBp')::smallint is distinct from v_settings.employee_insurance_rate_bp
      or (v_run.insurance_settings_snapshot->>'employerRateBp')::smallint is distinct from v_settings.employer_insurance_rate_bp
      or (v_run.insurance_settings_snapshot->'director'->>'enabled')::boolean is distinct from v_settings.director_insurance_enabled
      or (v_run.insurance_settings_snapshot->'director'->>'baseAmount')::numeric is distinct from v_settings.director_insurance_base_amount
      or (v_run.insurance_settings_snapshot->'director'->>'rateBp')::smallint is distinct from v_settings.director_insurance_rate_bp
    then raise exception 'PAYROLL_INSURANCE_SNAPSHOT_STALE' using errcode='55000';end if;
    if exists(
      select 1 from public.payroll_run_employees e
      left join lateral(
        select v.id,v.revision,v.effective_month from public.payroll_insurance_setting_versions v
        where v.user_id=e.user_id and v.effective_month<=v_run.payroll_month
        order by v.effective_month desc,v.revision desc limit 1
      ) current_setting on true
      where e.payroll_run_id=p_run_id and (
        not (e.insurance_snapshot ? 'isEnrolled')
        or nullif(e.insurance_snapshot->>'settingVersionId','')::bigint is distinct from current_setting.id
        or nullif(e.insurance_snapshot->>'revision','')::bigint is distinct from current_setting.revision
        or nullif(e.insurance_snapshot->>'effectiveMonth','')::date is distinct from current_setting.effective_month
      )
    ) then raise exception 'PAYROLL_INSURANCE_SNAPSHOT_STALE' using errcode='55000';end if;
  end if;
  perform public.payroll_transition_run_v2(p_run_id,p_action,p_reason,p_payment_date,p_payment_method,p_payment_note,p_actor_user_id);
end $$;

revoke all on function public.payroll_create_insurance_setting_version_v1(bigint,boolean,bigint,date,bigint,text),public.payroll_refresh_totals_v3(bigint),public.payroll_insert_payload_v3(bigint,jsonb,bigint,bigint),public.payroll_create_run_v3(date,timestamptz,text,jsonb,jsonb,bigint),public.payroll_recalculate_run_v3(bigint,timestamptz,text,jsonb,jsonb,bigint),public.payroll_mutate_item_v3(bigint,bigint,bigint,text,text,text,bigint,text,text,bigint),public.payroll_resolve_review_v3(bigint,bigint,bigint,text,integer,text,bigint),public.payroll_transition_run_v3(bigint,text,text,date,text,text,bigint) from public,anon,authenticated;
grant execute on function public.payroll_create_insurance_setting_version_v1(bigint,boolean,bigint,date,bigint,text),public.payroll_create_run_v3(date,timestamptz,text,jsonb,jsonb,bigint),public.payroll_recalculate_run_v3(bigint,timestamptz,text,jsonb,jsonb,bigint),public.payroll_mutate_item_v3(bigint,bigint,bigint,text,text,text,bigint,text,text,bigint),public.payroll_resolve_review_v3(bigint,bigint,bigint,text,integer,text,bigint),public.payroll_transition_run_v3(bigint,text,text,date,text,text,bigint) to service_role;

comment on table public.payroll_insurance_setting_versions is 'Append-only monthly employee insurance settings; latest effective month and highest revision apply.';
comment on column public.payroll_runs.insurance_settings_snapshot is 'Immutable global and director insurance settings captured for payroll engine v5.';
comment on column public.payroll_run_employees.insurance_snapshot is 'Immutable employee insurance setting and calculated contributions captured for payroll engine v5.';

commit;
