begin;

create table public.payroll_part_time_extra_work_decisions (
  id bigint generated by default as identity primary key,
  payroll_month date not null check (payroll_month = date_trunc('month', payroll_month)::date),
  attendance_record_id bigint not null references public.attendance_records(id) on delete restrict,
  user_id bigint not null references public.users(id) on delete restrict,
  business_date date not null,
  decision text not null check (decision in ('approved', 'rejected')),
  candidate_minutes integer not null check (candidate_minutes > 0),
  candidate_amount bigint not null check (candidate_amount >= 0),
  hourly_rate_amount bigint not null check (hourly_rate_amount > 0),
  before_schedule_minutes integer not null check (before_schedule_minutes >= 0),
  after_schedule_minutes integer not null check (after_schedule_minutes >= 0),
  excluded_before_open_minutes integer not null check (excluded_before_open_minutes >= 0),
  excluded_after_close_minutes integer not null check (excluded_after_close_minutes >= 0),
  schedule_start_time time without time zone not null,
  schedule_end_time time without time zone not null,
  store_open_time time without time zone not null,
  store_close_time time without time zone not null,
  source_hash text not null check (source_hash ~ '^[0-9a-f]{64}$'),
  source_snapshot jsonb not null check (jsonb_typeof(source_snapshot) = 'object'),
  decision_reason text null,
  decided_by bigint not null references public.users(id) on delete restrict,
  decided_at timestamptz not null default now(),
  cancelled_at timestamptz null,
  cancelled_by bigint null references public.users(id) on delete restrict,
  cancellation_reason text null,
  constraint payroll_part_time_extra_work_month_check check (date_trunc('month', business_date)::date = payroll_month),
  constraint payroll_part_time_extra_work_minutes_check check (candidate_minutes = before_schedule_minutes + after_schedule_minutes),
  constraint payroll_part_time_extra_work_cancel_check check (
    (cancelled_at is null and cancelled_by is null and cancellation_reason is null)
    or (cancelled_at is not null and cancelled_by is not null and nullif(btrim(cancellation_reason), '') is not null)
  )
);

create unique index payroll_part_time_extra_work_active_attendance_unique
  on public.payroll_part_time_extra_work_decisions(attendance_record_id)
  where cancelled_at is null;
create index payroll_part_time_extra_work_month_user_idx
  on public.payroll_part_time_extra_work_decisions(payroll_month, user_id, business_date);

alter table public.payroll_part_time_extra_work_decisions enable row level security;

comment on table public.payroll_part_time_extra_work_decisions is
  'Append-only owner/master decisions for automatically calculated hourly part-time extra work. Active decisions are cancelled, never deleted.';

commit;
