begin;

alter table public.users
  add column if not exists level_program_enabled boolean null,
  add column if not exists level_base_date_override date null;

alter table public.users
  add constraint users_level_enabled_requires_hire_date_check
    check (
      level_program_enabled is distinct from true
      or hire_date is not null
    ),
  add constraint users_system_account_level_settings_check
    check (
      is_system_account = false
      or (
        level_program_enabled is distinct from true
        and level_base_date_override is null
      )
    ),
  add constraint users_level_base_date_not_before_hire_check
    check (
      level_base_date_override is null
      or hire_date is null
      or level_base_date_override >= hire_date
    ),
  add constraint users_level_base_date_not_after_termination_check
    check (
      level_base_date_override is null
      or termination_date is null
      or level_base_date_override <= termination_date
    );

alter table public.payroll_contract_versions
  add column if not exists level_raise_included_count smallint null;

alter table public.payroll_contract_versions
  add constraint payroll_contract_level_raise_included_count_check
    check (
      level_raise_included_count is null
      or level_raise_included_count between 0 and 7
    );

create table public.employee_level_audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  action text not null,
  previous_enabled boolean null,
  next_enabled boolean null,
  previous_base_date_override date null,
  next_base_date_override date null,
  previous_effective_base_date date null,
  next_effective_base_date date null,
  previous_level smallint null,
  next_level smallint null,
  actor_id bigint null references public.users(id) on delete set null,
  actor_username text not null,
  change_reason text not null,
  created_at timestamptz not null default now(),
  constraint employee_level_audit_logs_action_check check (
    action in (
      'level_program_enabled',
      'level_program_disabled',
      'level_base_date_changed',
      'level_base_date_reset_to_hire_date',
      'level_reset_on_rehire'
    )
  ),
  constraint employee_level_audit_logs_previous_level_check check (
    previous_level is null or previous_level between 1 and 8
  ),
  constraint employee_level_audit_logs_next_level_check check (
    next_level is null or next_level between 1 and 8
  ),
  constraint employee_level_audit_logs_actor_username_check check (
    btrim(actor_username) <> ''
  ),
  constraint employee_level_audit_logs_change_reason_check check (
    btrim(change_reason) <> ''
  )
);

create index employee_level_audit_logs_user_created_idx
  on public.employee_level_audit_logs (user_id, created_at desc, id desc);
create index employee_level_audit_logs_created_idx
  on public.employee_level_audit_logs (created_at desc, id desc);
create index employee_level_audit_logs_actor_created_idx
  on public.employee_level_audit_logs (actor_id, created_at desc, id desc)
  where actor_id is not null;

alter table public.employee_level_audit_logs enable row level security;

revoke all on table public.employee_level_audit_logs
  from public, anon, authenticated, service_role;
revoke all on sequence public.employee_level_audit_logs_id_seq
  from public, anon, authenticated, service_role;

grant select, insert on table public.employee_level_audit_logs to service_role;
grant usage, select on sequence public.employee_level_audit_logs_id_seq to service_role;

comment on column public.users.level_program_enabled is
  'Explicit employee-level program switch. NULL and false are treated as disabled until application policy enables the user.';
comment on column public.users.level_base_date_override is
  'Optional employee-level base date; hire_date remains unchanged and is used as fallback.';
comment on column public.payroll_contract_versions.level_raise_included_count is
  'Number of employee-level raises already included in base_salary; NULL means not yet reviewed.';
comment on table public.employee_level_audit_logs is
  'Append-only audit foundation for employee-level program and base-date changes.';

commit;
