-- Customer bottle keeping management. Apply after 202607150001_add_bar_zone_image_updated_at.sql.
-- Access remains server-only through the service role; RPCs atomically mutate rows and append audit logs.

create table public.bar_keepings (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_identifier text,
  liquor_name text not null,
  note text,
  zone_code text not null references public.bar_zones(code) on update cascade,
  status text not null default 'active',
  close_reason text,
  close_note text,
  remaining_percent integer not null,
  image_path text not null,
  thumbnail_path text not null,
  image_updated_at timestamptz not null default now(),
  stored_at date not null,
  last_used_at timestamptz,
  expires_at date,
  closed_at timestamptz,
  created_by_user_id bigint references public.users(id) on delete set null,
  updated_by_user_id bigint references public.users(id) on delete set null,
  closed_by_user_id bigint references public.users(id) on delete restrict,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bar_keepings_customer_name_check check (char_length(btrim(customer_name)) between 1 and 120),
  constraint bar_keepings_customer_identifier_check check (customer_identifier is null or char_length(customer_identifier) <= 120),
  constraint bar_keepings_liquor_name_check check (char_length(btrim(liquor_name)) between 1 and 160),
  constraint bar_keepings_note_check check (note is null or char_length(note) <= 3000),
  constraint bar_keepings_close_note_check check (close_note is null or char_length(close_note) <= 1000),
  constraint bar_keepings_remaining_check check (remaining_percent between 0 and 100),
  constraint bar_keepings_status_check check (status in ('active', 'closed')),
  constraint bar_keepings_close_reason_check check (close_reason is null or close_reason in ('finished', 'returned', 'discarded', 'expired', 'other')),
  constraint bar_keepings_state_check check (
    (status = 'active' and close_reason is null and close_note is null and closed_at is null and closed_by_user_id is null)
    or (status = 'closed' and close_reason is not null and closed_at is not null and closed_by_user_id is not null)
  ),
  constraint bar_keepings_image_path_check check (image_path ~ '^keeping/[0-9]+-[0-9a-f]{24}/main[.]webp$'),
  constraint bar_keepings_thumbnail_path_check check (thumbnail_path ~ '^keeping/[0-9]+-[0-9a-f]{24}/thumb[.]webp$'),
  constraint bar_keepings_image_path_unique unique (image_path),
  constraint bar_keepings_thumbnail_path_unique unique (thumbnail_path),
  constraint bar_keepings_version_check check (version >= 1)
);

create index bar_keepings_status_recent_idx on public.bar_keepings(status, updated_at desc, id desc);
create index bar_keepings_zone_status_recent_idx on public.bar_keepings(zone_code, status, updated_at desc, id desc);
create index bar_keepings_expiry_idx on public.bar_keepings(expires_at) where status = 'active' and expires_at is not null;
create index bar_keepings_customer_sort_idx on public.bar_keepings(status, customer_name, id);
alter table public.bar_keepings enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('bar-keeping-images', 'bar-keeping-images', false, 716800, array['image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.bar_create_keeping(
  p_customer_name text, p_customer_identifier text, p_liquor_name text, p_note text,
  p_zone_code text, p_remaining_percent integer, p_image_path text, p_thumbnail_path text,
  p_stored_at date, p_expires_at date, p_actor_user_id bigint
) returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_zone public.bar_zones%rowtype; v_row public.bar_keepings%rowtype; v_now timestamptz := clock_timestamp(); v_actor_name text;
begin
  select coalesce(nullif(u.name, ''), nullif(u.full_name, ''), u.username)
  into v_actor_name from public.users as u where u.id = p_actor_user_id and u.is_active = true;
  if not found or v_actor_name is null then return jsonb_build_object('status','invalid_actor'); end if;
  select * into v_zone from public.bar_zones where code = p_zone_code;
  if not found or not v_zone.is_active or not v_zone.selectable_for_keeping then return jsonb_build_object('status','invalid_zone'); end if;
  insert into public.bar_keepings(customer_name, customer_identifier, liquor_name, note, zone_code, remaining_percent,
    image_path, thumbnail_path, image_updated_at, stored_at, expires_at, created_by_user_id, updated_by_user_id, created_at, updated_at)
  values (btrim(p_customer_name), nullif(btrim(p_customer_identifier),''), btrim(p_liquor_name), nullif(btrim(p_note),''), p_zone_code,
    p_remaining_percent, p_image_path, p_thumbnail_path, v_now, p_stored_at, p_expires_at, p_actor_user_id, p_actor_user_id, v_now, v_now)
  returning * into v_row;
  insert into public.bar_activity_logs(entity_type, entity_id, entity_code_snapshot, action_type, before_data, after_data, actor_user_id, actor_name_snapshot, created_at)
  values ('keeping', v_row.id, left(v_row.customer_name || ' · ' || v_row.liquor_name, 240), 'keeping_created', null,
    jsonb_build_object('customer_name',v_row.customer_name,'liquor_name',v_row.liquor_name,'zone_code',v_row.zone_code,'remaining_percent',v_row.remaining_percent),
    p_actor_user_id, v_actor_name, v_now);
  return jsonb_build_object('status','ok','id',v_row.id,'version',v_row.version);
end $$;

create or replace function public.bar_mutate_keeping(
  p_id bigint, p_expected_version integer, p_action text, p_payload jsonb, p_actor_user_id bigint
) returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  v_old public.bar_keepings%rowtype; v_new public.bar_keepings%rowtype; v_zone public.bar_zones%rowtype;
  v_now timestamptz := clock_timestamp(); v_snapshot text; v_new_zone text; v_reason text; v_used_at timestamptz; v_actor_name text;
begin
  select coalesce(nullif(u.name, ''), nullif(u.full_name, ''), u.username)
  into v_actor_name from public.users as u where u.id = p_actor_user_id and u.is_active = true;
  if not found or v_actor_name is null then return jsonb_build_object('status','invalid_actor'); end if;
  select * into v_old from public.bar_keepings where id = p_id for update;
  if not found then return jsonb_build_object('status','not_found'); end if;
  if v_old.version <> p_expected_version then return jsonb_build_object('status','conflict','version',v_old.version); end if;
  if (nullif(p_payload->>'image_path','') is null) <> (nullif(p_payload->>'thumbnail_path','') is null) then return jsonb_build_object('status','invalid_input'); end if;
  v_snapshot := left(v_old.customer_name || ' · ' || v_old.liquor_name, 240);

  if p_action = 'update' then
    if v_old.status = 'closed' and coalesce((p_payload->>'allow_closed')::boolean,false) is not true then return jsonb_build_object('status','invalid_state'); end if;
    update public.bar_keepings set customer_name=btrim(p_payload->>'customer_name'), customer_identifier=nullif(btrim(p_payload->>'customer_identifier'),''),
      liquor_name=btrim(p_payload->>'liquor_name'), note=nullif(btrim(p_payload->>'note'),''), stored_at=(p_payload->>'stored_at')::date,
      expires_at=nullif(p_payload->>'expires_at','')::date, updated_by_user_id=p_actor_user_id, updated_at=v_now, version=version+1 where id=p_id returning * into v_new;
  elsif p_action = 'use' then
    if v_old.status <> 'active' then return jsonb_build_object('status','invalid_state'); end if;
    if coalesce((p_payload->>'finish')::boolean,false) and (p_payload->>'remaining_percent')::integer <> 0 then return jsonb_build_object('status','invalid_input'); end if;
    v_used_at := (p_payload->>'used_at')::timestamptz;
    update public.bar_keepings set remaining_percent=(p_payload->>'remaining_percent')::integer, last_used_at=v_used_at,
      image_path=coalesce(nullif(p_payload->>'image_path',''),image_path), thumbnail_path=coalesce(nullif(p_payload->>'thumbnail_path',''),thumbnail_path),
      image_updated_at=case when nullif(p_payload->>'image_path','') is null then image_updated_at else v_now end,
      status=case when coalesce((p_payload->>'finish')::boolean,false) then 'closed' else status end,
      close_reason=case when coalesce((p_payload->>'finish')::boolean,false) then 'finished' else null end,
      close_note=case when coalesce((p_payload->>'finish')::boolean,false) then nullif(btrim(p_payload->>'note'),'') else null end,
      closed_at=case when coalesce((p_payload->>'finish')::boolean,false) then v_used_at else null end,
      closed_by_user_id=case when coalesce((p_payload->>'finish')::boolean,false) then p_actor_user_id else null end,
      updated_by_user_id=p_actor_user_id, updated_at=v_now, version=version+1 where id=p_id returning * into v_new;
  elsif p_action = 'correct_remaining' then
    if v_old.status <> 'active' then return jsonb_build_object('status','invalid_state'); end if;
    update public.bar_keepings set remaining_percent=(p_payload->>'remaining_percent')::integer, updated_by_user_id=p_actor_user_id, updated_at=v_now, version=version+1 where id=p_id returning * into v_new;
  elsif p_action = 'move' then
    if v_old.status <> 'active' then return jsonb_build_object('status','invalid_state'); end if;
    v_new_zone := p_payload->>'zone_code'; if v_new_zone = v_old.zone_code then return jsonb_build_object('status','same_zone'); end if;
    select * into v_zone from public.bar_zones where code=v_new_zone;
    if not found or not v_zone.is_active or not v_zone.selectable_for_keeping then return jsonb_build_object('status','invalid_zone'); end if;
    update public.bar_keepings set zone_code=v_new_zone, updated_by_user_id=p_actor_user_id, updated_at=v_now, version=version+1 where id=p_id returning * into v_new;
  elsif p_action = 'replace_photo' then
    if nullif(p_payload->>'image_path','') is null then return jsonb_build_object('status','invalid_input'); end if;
    update public.bar_keepings set image_path=p_payload->>'image_path', thumbnail_path=p_payload->>'thumbnail_path', image_updated_at=v_now,
      updated_by_user_id=p_actor_user_id, updated_at=v_now, version=version+1 where id=p_id returning * into v_new;
  elsif p_action = 'close' then
    if v_old.status <> 'active' then return jsonb_build_object('status','invalid_state'); end if;
    v_reason := p_payload->>'close_reason';
    update public.bar_keepings set status='closed', close_reason=v_reason, close_note=nullif(btrim(p_payload->>'close_note'),''),
      closed_at=(p_payload->>'closed_at')::timestamptz, closed_by_user_id=p_actor_user_id,
      image_path=coalesce(nullif(p_payload->>'image_path',''),image_path), thumbnail_path=coalesce(nullif(p_payload->>'thumbnail_path',''),thumbnail_path),
      image_updated_at=case when nullif(p_payload->>'image_path','') is null then image_updated_at else v_now end,
      updated_by_user_id=p_actor_user_id, updated_at=v_now, version=version+1 where id=p_id returning * into v_new;
  elsif p_action = 'reactivate' then
    if v_old.status <> 'closed' then return jsonb_build_object('status','invalid_state'); end if;
    v_new_zone := p_payload->>'zone_code'; select * into v_zone from public.bar_zones where code=v_new_zone;
    if not found or not v_zone.is_active or not v_zone.selectable_for_keeping then return jsonb_build_object('status','invalid_zone'); end if;
    update public.bar_keepings set status='active', close_reason=null, close_note=null, closed_at=null, closed_by_user_id=null,
      zone_code=v_new_zone, remaining_percent=(p_payload->>'remaining_percent')::integer, expires_at=nullif(p_payload->>'expires_at','')::date,
      image_path=coalesce(nullif(p_payload->>'image_path',''),image_path), thumbnail_path=coalesce(nullif(p_payload->>'thumbnail_path',''),thumbnail_path),
      image_updated_at=case when nullif(p_payload->>'image_path','') is null then image_updated_at else v_now end,
      updated_by_user_id=p_actor_user_id, updated_at=v_now, version=version+1 where id=p_id returning * into v_new;
  else return jsonb_build_object('status','invalid_action'); end if;

  insert into public.bar_activity_logs(entity_type,entity_id,entity_code_snapshot,action_type,before_data,after_data,actor_user_id,actor_name_snapshot,created_at)
  values ('keeping',p_id,v_snapshot,case p_action when 'update' then 'keeping_updated' when 'use' then 'keeping_used'
    when 'correct_remaining' then 'keeping_remaining_corrected' when 'move' then 'keeping_zone_changed' when 'replace_photo' then 'keeping_photo_replaced'
    when 'close' then 'keeping_closed' when 'reactivate' then 'keeping_reactivated' end,
    to_jsonb(v_old) || jsonb_build_object('reason',p_payload->>'reason'), to_jsonb(v_new) || jsonb_build_object('reason',p_payload->>'reason','note',p_payload->>'note'),
    p_actor_user_id,v_actor_name,v_now);
  return jsonb_build_object('status','ok','version',v_new.version,'old_image_path',v_old.image_path,'old_thumbnail_path',v_old.thumbnail_path);
exception when check_violation or invalid_text_representation or datetime_field_overflow then
  return jsonb_build_object('status','invalid_input');
end $$;

revoke all on function public.bar_create_keeping(text,text,text,text,text,integer,text,text,date,date,bigint) from public, anon, authenticated;
revoke all on function public.bar_mutate_keeping(bigint,integer,text,jsonb,bigint) from public, anon, authenticated;
grant execute on function public.bar_create_keeping(text,text,text,text,text,integer,text,text,date,date,bigint) to service_role;
grant execute on function public.bar_mutate_keeping(bigint,integer,text,jsonb,bigint) to service_role;
