-- Month-end card fee closures.
--
-- Card deposits are allocated to sale principal FIFO (auto_allocated) and never estimate a
-- fee. Once every card deposit for a sale month has been registered, a user confirms that
-- month: whatever card sale gross is still outstanding at that moment becomes the month's
-- card fee. The amount is always recomputed here under lock; it is never user input.
--
-- Card sale outstanding is now:
--   POS card sale gross
--   - non-cancelled ledger_card_reconciliation_lines (deposits, incl. historical matched)
--   - non-cancelled ledger_card_fee_allocation_lines (month-end fee)
-- Historical matched differences (card_settlement_difference) are untouched: their gross
-- is already consumed by reconciliation lines, so it is never counted again as fee.
--
-- No existing rows are updated and no closure is created for any month by this migration.

create table public.ledger_card_fee_closures(
  id bigint generated by default as identity primary key,
  fee_month date not null check (fee_month = date_trunc('month', fee_month)::date),
  fee_amount numeric(16,3) not null check (fee_amount >= 0),
  expense_transaction_id bigint null unique references public.ledger_transactions(id) on delete restrict,
  status text not null default 'confirmed' check (status in ('confirmed', 'cancelled')),
  confirmed_at timestamptz not null default now(),
  confirmed_by bigint not null references public.users(id) on delete restrict,
  cancelled_at timestamptz null,
  cancelled_by bigint null references public.users(id) on delete restrict,
  cancel_reason text null,
  memo text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- A zero fee still records that the month's card deposits were checked; it books nothing.
  constraint ledger_card_fee_closure_expense check (
    (fee_amount = 0 and expense_transaction_id is null) or (fee_amount > 0 and expense_transaction_id is not null)
  ),
  constraint ledger_card_fee_closure_cancellation check (
    (status = 'cancelled' and cancelled_at is not null and cancelled_by is not null and nullif(btrim(cancel_reason), '') is not null)
    or (status = 'confirmed' and cancelled_at is null and cancelled_by is null and cancel_reason is null)
  )
);
-- At most one active closure per sale month; cancelled history is kept and can be re-confirmed.
create unique index ledger_card_fee_closures_active_month_idx
  on public.ledger_card_fee_closures(fee_month) where status = 'confirmed';
create index ledger_card_fee_closures_month_idx on public.ledger_card_fee_closures(fee_month, status);
create index ledger_card_fee_closures_confirmed_by_idx on public.ledger_card_fee_closures(confirmed_by);
create index ledger_card_fee_closures_cancelled_by_idx on public.ledger_card_fee_closures(cancelled_by);

create table public.ledger_card_fee_allocation_lines(
  id bigint generated by default as identity primary key,
  closure_id bigint not null references public.ledger_card_fee_closures(id) on delete restrict,
  pos_card_transaction_id bigint not null references public.ledger_transactions(id) on delete restrict,
  allocated_fee_amount numeric(16,3) not null check (allocated_fee_amount > 0),
  created_at timestamptz not null default now(),
  constraint ledger_card_fee_allocation_line_unique unique (closure_id, pos_card_transaction_id)
);
create index ledger_card_fee_allocation_lines_closure_idx on public.ledger_card_fee_allocation_lines(closure_id);
create index ledger_card_fee_allocation_lines_pos_transaction_idx on public.ledger_card_fee_allocation_lines(pos_card_transaction_id);

alter table public.ledger_card_fee_closures enable row level security;
alter table public.ledger_card_fee_allocation_lines enable row level security;
revoke all on table public.ledger_card_fee_closures, public.ledger_card_fee_allocation_lines from public, anon, authenticated, service_role;
revoke all on sequence public.ledger_card_fee_closures_id_seq, public.ledger_card_fee_allocation_lines_id_seq from public, anon, authenticated, service_role;
grant select on table public.ledger_card_fee_closures, public.ledger_card_fee_allocation_lines to service_role;

-- Same month-close protection as ledger_card_reconciliations / lines.
create function public.ledger_card_fee_closure_month_guard_v1() returns trigger
language plpgsql security definer set search_path = pg_catalog, public as $$
begin
  perform public.ledger_assert_month_open_v1(case when tg_op = 'DELETE' then old.fee_month else new.fee_month end);
  return case when tg_op = 'DELETE' then old else new end;
end $$;
create trigger ledger_card_fee_closures_month_guard before insert or update or delete on public.ledger_card_fee_closures
for each row execute function public.ledger_card_fee_closure_month_guard_v1();

create function public.ledger_card_fee_line_month_guard_v1() returns trigger
language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_month date;
begin
  select fee_month into v_month from public.ledger_card_fee_closures
  where id = case when tg_op = 'DELETE' then old.closure_id else new.closure_id end;
  perform public.ledger_assert_month_open_v1(v_month);
  return case when tg_op = 'DELETE' then old else new end;
end $$;
create trigger ledger_card_fee_allocation_lines_month_guard before insert or update or delete on public.ledger_card_fee_allocation_lines
for each row execute function public.ledger_card_fee_line_month_guard_v1();

-- Single definition of how much of a POS card sale is already consumed.
create function public.ledger_card_sale_consumed_v1(p_sale_id bigint) returns numeric
language sql stable set search_path = pg_catalog, public as $$
  select coalesce((
      select sum(l.allocated_gross_amount)
      from public.ledger_card_reconciliation_lines l
      join public.ledger_card_reconciliations r on r.id = l.reconciliation_id
      where l.pos_card_transaction_id = p_sale_id and r.status <> 'cancelled'
    ), 0)
    + coalesce((
      select sum(f.allocated_fee_amount)
      from public.ledger_card_fee_allocation_lines f
      join public.ledger_card_fee_closures c on c.id = f.closure_id
      where f.pos_card_transaction_id = p_sale_id and c.status <> 'cancelled'
    ), 0)
$$;

-- POS card sales that are consumed (deposits or fee) or sit in a fee-confirmed month are
-- economically final: block any write path (open-day sync, reclose, direct SQL) that would
-- shrink them below their consumption or change a fee-confirmed month's card gross.
create function public.ledger_card_sale_consumption_guard_v1() returns trigger
language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_consumed numeric; v_effective numeric;
begin
  if tg_op = 'INSERT' then
    if new.source_type = 'pos_sales_daily_payment' and new.source_key like 'pos:%:card'
       and new.status = 'confirmed' and new.amount > 0
       and exists (select 1 from public.ledger_card_fee_closures c
                   where c.status = 'confirmed' and c.fee_month = date_trunc('month', new.business_date)::date) then
      raise exception 'CARD_FEE_MONTH_CONFIRMED' using errcode = '55000';
    end if;
    return new;
  end if;
  if old.source_type = 'pos_sales_daily_payment' and old.source_key like 'pos:%:card'
     and (new.amount is distinct from old.amount or new.status is distinct from old.status
          or new.business_date is distinct from old.business_date) then
    if exists (select 1 from public.ledger_card_fee_closures c
               where c.status = 'confirmed' and c.fee_month = date_trunc('month', old.business_date)::date) then
      raise exception 'CARD_FEE_MONTH_CONFIRMED' using errcode = '55000';
    end if;
    v_consumed := public.ledger_card_sale_consumed_v1(old.id);
    v_effective := case when new.status = 'confirmed' then new.amount else 0 end;
    if v_consumed > 0 and (v_effective < v_consumed or new.business_date is distinct from old.business_date) then
      raise exception 'CARD_SALE_BELOW_ALLOCATED' using errcode = '55000';
    end if;
  end if;
  return new;
end $$;
create trigger ledger_card_sale_consumption_guard before insert or update on public.ledger_transactions
for each row execute function public.ledger_card_sale_consumption_guard_v1();

create function public.ledger_confirm_card_fee_month_v1(
  p_month date,
  p_memo text,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_current_month date := date_trunc('month', now() at time zone 'Asia/Ho_Chi_Minh')::date;
  v_clearing bigint;
  v_balance numeric;
  v_existing public.ledger_card_fee_closures%rowtype;
  v_legacy_count bigint;
  v_legacy_amount numeric;
  v_earlier_month date;
  v_gross numeric;
  v_fee numeric;
  v_category bigint;
  v_closure bigint;
  v_transaction bigint;
  v_last_day date;
  v_sale record;
  v_lines jsonb := '[]'::jsonb;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;
  if p_month is null or p_month <> date_trunc('month', p_month)::date then
    return jsonb_build_object('status', 'invalid_month');
  end if;
  -- Never automatic and never for the running month: deposits for it are still arriving.
  if p_month >= v_current_month then
    return jsonb_build_object('status', case when p_month = v_current_month then 'current_month' else 'future_month' end);
  end if;

  -- Same lock order as card deposit create/match/cancel: month close, then card clearing.
  perform pg_advisory_xact_lock(hashtext('ledger_month_close:' || to_char(p_month, 'YYYY-MM')));
  if public.ledger_month_is_closed_v1(p_month) then
    return jsonb_build_object('status', 'month_closed');
  end if;
  perform pg_advisory_xact_lock(hashtext('ledger_card_clearing_balance'));

  select id into v_clearing
  from public.ledger_fund_accounts
  where code = 'card_clearing' and is_active = true
  for update;
  if v_clearing is null then return jsonb_build_object('status', 'card_clearing_missing'); end if;

  perform 1
  from public.ledger_transactions
  where status = 'confirmed'
    and source_type = 'pos_sales_daily_payment'
    and source_key like 'pos:%:card'
    and business_date >= p_month and business_date < (p_month + interval '1 month')::date
  order by id
  for update;

  select * into v_existing
  from public.ledger_card_fee_closures
  where fee_month = p_month and status = 'confirmed';
  if v_existing.id is not null then
    return jsonb_build_object('status', 'already_confirmed', 'closureId', v_existing.id, 'feeAmount', v_existing.fee_amount);
  end if;

  -- A legacy deposit that could still pay this month's sales has not been allocated yet;
  -- confirming now would book money already received as fee.
  select count(*), coalesce(sum(deposit_amount), 0) into v_legacy_count, v_legacy_amount
  from public.ledger_card_reconciliations
  where status in ('unmatched', 'partial') and deposit_date >= p_month;
  if v_legacy_count > 0 then
    return jsonb_build_object('status', 'legacy_unallocated_deposits', 'count', v_legacy_count, 'amount', v_legacy_amount);
  end if;

  -- FIFO pays older open months first, so they must be resolved first. Closed months are
  -- final history and are never forced here.
  select min(date_trunc('month', t.business_date)::date) into v_earlier_month
  from public.ledger_transactions t
  where t.status = 'confirmed'
    and t.source_type = 'pos_sales_daily_payment'
    and t.source_key like 'pos:%:card'
    and t.business_date < p_month
    and t.amount - public.ledger_card_sale_consumed_v1(t.id) > 0
    and not public.ledger_month_is_closed_v1(date_trunc('month', t.business_date)::date)
    and not exists (
      select 1 from public.ledger_card_fee_closures c
      where c.status = 'confirmed' and c.fee_month = date_trunc('month', t.business_date)::date
    );
  if v_earlier_month is not null then
    return jsonb_build_object('status', 'earlier_month_unconfirmed', 'month', v_earlier_month);
  end if;

  select coalesce(sum(t.amount), 0),
         coalesce(sum(greatest(t.amount - public.ledger_card_sale_consumed_v1(t.id), 0)), 0)
    into v_gross, v_fee
  from public.ledger_transactions t
  where t.status = 'confirmed'
    and t.source_type = 'pos_sales_daily_payment'
    and t.source_key like 'pos:%:card'
    and t.business_date >= p_month and t.business_date < (p_month + interval '1 month')::date;
  if v_gross <= 0 then
    return jsonb_build_object('status', 'no_card_sales');
  end if;

  if v_fee > 0 then
    select coalesce(sum(m.amount), 0) into v_balance
    from public.ledger_movements m
    join public.ledger_transactions t on t.id = m.transaction_id
    where m.fund_account_id = v_clearing and t.status = 'confirmed';
    if v_balance < v_fee then
      return jsonb_build_object('status', 'insufficient_card_pending', 'pendingBalance', v_balance, 'feeAmount', v_fee);
    end if;
    select id into v_category
    from public.ledger_categories
    where kind = 'expense' and name = '카드 정산 차액' and is_active = true;
    if v_category is null then return jsonb_build_object('status', 'category_missing'); end if;
  end if;

  v_closure := nextval(pg_get_serial_sequence('public.ledger_card_fee_closures', 'id'));
  v_last_day := (p_month + interval '1 month')::date - 1;
  if v_fee > 0 then
    -- Recognized in the sale month itself, dated on its last day so month-end fund and card
    -- snapshots of that month already reflect the fee.
    insert into public.ledger_transactions(
      operation_id, type, occurred_at, business_date, recognition_month, amount, category_id,
      status, source_type, source_key, source_snapshot, source_fingerprint, source_synced_at,
      memo, created_by, confirmed_by
    ) values (
      gen_random_uuid(), 'expense_recognition', (v_last_day + time '12:00') at time zone 'Asia/Ho_Chi_Minh',
      v_last_day, p_month, v_fee, v_category, 'confirmed', 'card_fee_month_close',
      'card-fee-closure:' || v_closure,
      jsonb_build_object('closureId', v_closure, 'feeMonth', p_month, 'feeAmount', v_fee),
      md5('card-fee-closure:' || v_closure || ':' || v_fee::text), now(),
      '카드 수수료 월말 확정 ' || to_char(p_month, 'YYYY-MM'), p_actor_user_id, p_actor_user_id
    ) returning id into v_transaction;
    insert into public.ledger_movements(transaction_id, fund_account_id, amount)
    values (v_transaction, v_clearing, -v_fee);
  end if;

  insert into public.ledger_card_fee_closures(
    id, fee_month, fee_amount, expense_transaction_id, status, confirmed_at, confirmed_by, memo
  ) values (
    v_closure, p_month, v_fee, v_transaction, 'confirmed', now(), p_actor_user_id, nullif(btrim(p_memo), '')
  );

  -- Consume every remaining sale balance of the month, oldest business_date then id.
  for v_sale in
    select t.id, t.business_date, t.amount - public.ledger_card_sale_consumed_v1(t.id) as outstanding
    from public.ledger_transactions t
    where t.status = 'confirmed'
      and t.source_type = 'pos_sales_daily_payment'
      and t.source_key like 'pos:%:card'
      and t.business_date >= p_month and t.business_date < (p_month + interval '1 month')::date
      and t.amount - public.ledger_card_sale_consumed_v1(t.id) > 0
    order by t.business_date, t.id
  loop
    insert into public.ledger_card_fee_allocation_lines(closure_id, pos_card_transaction_id, allocated_fee_amount)
    values (v_closure, v_sale.id, v_sale.outstanding);
    v_lines := v_lines || jsonb_build_array(jsonb_build_object(
      'transactionId', v_sale.id, 'businessDate', v_sale.business_date, 'allocatedFeeAmount', v_sale.outstanding
    ));
  end loop;
  if coalesce((select sum(allocated_fee_amount) from public.ledger_card_fee_allocation_lines where closure_id = v_closure), 0) <> v_fee then
    raise exception 'card fee allocation does not match fee amount';
  end if;

  insert into public.ledger_audit_logs(
    actor_user_id, action, entity_type, entity_id, after_snapshot, reason
  ) values (
    p_actor_user_id, 'card_fee_month_confirmed', 'card_fee_closure', v_closure,
    jsonb_build_object(
      'feeMonth', p_month,
      'cardGross', v_gross,
      'feeAmount', v_fee,
      'expenseTransactionId', v_transaction,
      'lines', v_lines,
      'beforePendingBalance', v_balance,
      'afterPendingBalance', case when v_balance is null then null else v_balance - v_fee end,
      'status', 'confirmed'
    ),
    nullif(btrim(p_memo), '')
  );
  return jsonb_build_object(
    'status', 'confirmed',
    'closureId', v_closure,
    'feeMonth', p_month,
    'feeAmount', v_fee,
    'expenseTransactionId', v_transaction,
    'lines', v_lines
  );
exception
  when unique_violation then
    return jsonb_build_object('status', 'already_confirmed');
  when check_violation or foreign_key_violation or not_null_violation then
    return jsonb_build_object('status', 'invalid_input');
end;
$$;

create function public.ledger_cancel_card_fee_month_v1(
  p_closure_id bigint,
  p_reason text,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_month date;
  v_clearing bigint;
  v_closure public.ledger_card_fee_closures%rowtype;
  v_original public.ledger_transactions%rowtype;
  v_reversal bigint;
  v_before jsonb;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;
  if nullif(btrim(p_reason), '') is null then
    return jsonb_build_object('status', 'reason_required');
  end if;

  select fee_month into v_month from public.ledger_card_fee_closures where id = p_closure_id;
  if v_month is null then return jsonb_build_object('status', 'not_found'); end if;
  perform pg_advisory_xact_lock(hashtext('ledger_month_close:' || to_char(v_month, 'YYYY-MM')));
  if public.ledger_month_is_closed_v1(v_month) then
    return jsonb_build_object('status', 'month_closed');
  end if;
  perform pg_advisory_xact_lock(hashtext('ledger_card_clearing_balance'));

  select * into v_closure from public.ledger_card_fee_closures where id = p_closure_id for update;
  if v_closure.status = 'cancelled' then
    return jsonb_build_object('status', 'already_cancelled', 'cancelledAt', v_closure.cancelled_at, 'cancelledBy', v_closure.cancelled_by);
  end if;

  select id into v_clearing from public.ledger_fund_accounts where code = 'card_clearing' for update;
  if v_clearing is null then return jsonb_build_object('status', 'invalid_state'); end if;

  if v_closure.fee_amount > 0 then
    select * into v_original from public.ledger_transactions where id = v_closure.expense_transaction_id for update;
    if v_original.id is null
       or v_original.status <> 'confirmed'
       or v_original.type <> 'expense_recognition'
       or v_original.source_type <> 'card_fee_month_close'
       or v_original.amount <> v_closure.fee_amount
       or v_original.recognition_month <> v_closure.fee_month
       or (select count(*) from public.ledger_movements where transaction_id = v_original.id) <> 1
       or coalesce((select sum(amount) from public.ledger_movements where transaction_id = v_original.id and fund_account_id = v_clearing), 0) <> -v_closure.fee_amount then
      return jsonb_build_object('status', 'invalid_state');
    end if;
    if exists (
      select 1 from public.ledger_transactions
      where source_key = 'card-fee-closure:' || v_closure.id || ':reversal'
         or (correction_of_id = v_original.id and source_type = 'card_fee_month_close_reversal')
    ) then
      return jsonb_build_object('status', 'already_cancelled');
    end if;
  elsif v_closure.expense_transaction_id is not null then
    return jsonb_build_object('status', 'invalid_state');
  end if;

  v_before := jsonb_build_object(
    'closure', to_jsonb(v_closure),
    'lines', coalesce((select jsonb_agg(to_jsonb(f) order by f.id) from public.ledger_card_fee_allocation_lines f where f.closure_id = v_closure.id), '[]'::jsonb),
    'expenseTransaction', case when v_original.id is null then null else to_jsonb(v_original) end
  );

  if v_original.id is not null then
    -- Append-only: reverse the expense and restore card clearing; the original stays.
    insert into public.ledger_transactions(
      operation_id, type, occurred_at, business_date, recognition_month, amount,
      category_id, party_id, status, source_type, source_key, source_snapshot,
      source_fingerprint, source_synced_at, correction_of_id, memo,
      created_by, confirmed_by, economic_effect_sign
    ) values (
      gen_random_uuid(), v_original.type, v_original.occurred_at, v_original.business_date,
      v_original.recognition_month, v_original.amount, v_original.category_id,
      v_original.party_id, 'confirmed', 'card_fee_month_close_reversal',
      'card-fee-closure:' || v_closure.id || ':reversal',
      jsonb_build_object('closureId', v_closure.id, 'originalTransactionId', v_original.id, 'cancelReason', btrim(p_reason)),
      md5('card-fee-closure:' || v_closure.id || ':reversal'), now(),
      v_original.id, '카드 수수료 월말 확정 취소 역분개: ' || btrim(p_reason),
      p_actor_user_id, p_actor_user_id, -1
    ) returning id into v_reversal;
    insert into public.ledger_movements(transaction_id, fund_account_id, amount)
    select v_reversal, fund_account_id, -amount
    from public.ledger_movements
    where transaction_id = v_original.id
    order by id;
  end if;

  -- Lines are kept as history; a cancelled closure no longer consumes sale gross.
  update public.ledger_card_fee_closures
  set status = 'cancelled', cancelled_at = now(), cancelled_by = p_actor_user_id,
      cancel_reason = btrim(p_reason), updated_at = now()
  where id = v_closure.id;

  insert into public.ledger_audit_logs(
    actor_user_id, action, entity_type, entity_id, before_snapshot, after_snapshot, reason
  ) values (
    p_actor_user_id, 'card_fee_month_cancelled', 'card_fee_closure', v_closure.id, v_before,
    jsonb_build_object(
      'feeMonth', v_closure.fee_month,
      'feeAmount', v_closure.fee_amount,
      'reversalTransactionId', v_reversal,
      'preservedLineCount', (select count(*) from public.ledger_card_fee_allocation_lines where closure_id = v_closure.id),
      'status', 'cancelled'
    ),
    btrim(p_reason)
  );
  return jsonb_build_object(
    'status', 'cancelled',
    'closureId', v_closure.id,
    'feeMonth', v_closure.fee_month,
    'reversalTransactionId', v_reversal
  );
end;
$$;

-- Card deposit FIFO: unchanged from 20260927144325 except outstanding also subtracts fee allocations.
create or replace function public.ledger_create_card_deposit_auto_allocate_v1(
  p_deposit_at timestamptz,
  p_amount numeric,
  p_destination_account_id bigint,
  p_memo text,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_clearing bigint;
  v_bank bigint;
  v_balance numeric;
  v_available numeric;
  v_remaining numeric;
  v_allocated numeric;
  v_transaction bigint;
  v_reconciliation bigint;
  v_operation uuid := gen_random_uuid();
  v_date date;
  v_month date;
  v_sale record;
  v_allocations jsonb := '[]'::jsonb;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;
  if p_deposit_at is null or p_amount is null or p_amount <= 0 or scale(p_amount) > 3 then
    return jsonb_build_object('status', 'invalid_amount');
  end if;

  v_date := ((p_deposit_at at time zone 'Asia/Ho_Chi_Minh') - interval '3 hours')::date;
  v_month := date_trunc('month', v_date)::date;
  -- Same lock order as create/match/cancel: month close, then card clearing balance.
  perform pg_advisory_xact_lock(hashtext('ledger_month_close:' || to_char(v_month, 'YYYY-MM')));
  if public.ledger_month_is_closed_v1(v_month) then
    return jsonb_build_object('status', 'month_closed');
  end if;
  perform pg_advisory_xact_lock(hashtext('ledger_card_clearing_balance'));

  select id into v_clearing
  from public.ledger_fund_accounts
  where code = 'card_clearing' and is_active = true
  for update;
  if v_clearing is null then return jsonb_build_object('status', 'card_clearing_missing'); end if;

  -- Card deposits always land in the BABA corporate bank account.
  select id into v_bank
  from public.ledger_fund_accounts
  where code = 'baba_corporate_bank' and is_active = true and type <> 'card_clearing';
  if v_bank is null then return jsonb_build_object('status', 'corporate_bank_missing'); end if;
  if p_destination_account_id is distinct from v_bank then
    return jsonb_build_object('status', 'invalid_destination');
  end if;

  select coalesce(sum(m.amount), 0) into v_balance
  from public.ledger_movements m
  join public.ledger_transactions t on t.id = m.transaction_id
  where m.fund_account_id = v_clearing and t.status = 'confirmed';
  if v_balance < p_amount then
    return jsonb_build_object('status', 'insufficient_card_pending', 'pendingBalance', v_balance);
  end if;

  -- Lock candidate sales in id order (the match RPC's order) before reading balances.
  perform 1
  from public.ledger_transactions
  where status = 'confirmed'
    and source_type = 'pos_sales_daily_payment'
    and source_key like 'pos:%:card'
    and business_date <= v_date
  order by id
  for update;

  -- Outstanding = sale gross minus every non-cancelled allocation (legacy partial lines included)
  -- and every active month-end card fee allocation, so fee-consumed gross is never re-paid.
  select coalesce(sum(outstanding), 0) into v_available
  from (
    select c.id, c.business_date, c.outstanding
    from (
      select t.id, t.business_date,
        t.amount - public.ledger_card_sale_consumed_v1(t.id) as outstanding
      from public.ledger_transactions t
      where t.status = 'confirmed'
        and t.source_type = 'pos_sales_daily_payment'
        and t.source_key like 'pos:%:card'
        and t.business_date <= v_date
    ) c
    where c.outstanding > 0
  ) eligible;
  if v_available < p_amount then
    return jsonb_build_object(
      'status', 'insufficient_unsettled_card_sales',
      'availableOutstanding', v_available,
      'depositAmount', p_amount
    );
  end if;

  insert into public.ledger_transactions(
    operation_id, type, occurred_at, business_date, amount, status, source_type,
    source_snapshot, source_fingerprint, source_synced_at, memo, created_by, confirmed_by
  ) values (
    v_operation, 'card_settlement_deposit', p_deposit_at, v_date, p_amount, 'confirmed',
    'card_settlement_deposit',
    jsonb_build_object(
      'depositAmount', p_amount,
      'destinationFundAccountId', v_bank,
      'allocationMode', 'fifo_auto'
    ),
    md5(v_operation::text || ':' || p_amount::text), now(), nullif(btrim(p_memo), ''),
    p_actor_user_id, p_actor_user_id
  ) returning id into v_transaction;

  insert into public.ledger_movements(transaction_id, fund_account_id, amount)
  values
    (v_transaction, v_clearing, -p_amount),
    (v_transaction, v_bank, p_amount);

  insert into public.ledger_card_reconciliations(
    deposit_transaction_id, deposit_date, destination_fund_account_id, deposit_amount,
    matched_gross_amount, difference_amount, status, memo
  ) values (
    v_transaction, v_date, v_bank, p_amount, p_amount, 0, 'auto_allocated', nullif(btrim(p_memo), '')
  ) returning id into v_reconciliation;

  -- FIFO: oldest business_date first, then id; each sale takes min(remaining, outstanding).
  v_remaining := p_amount;
  for v_sale in
    select eligible.id, eligible.business_date, eligible.outstanding
    from (
      select c.id, c.business_date, c.outstanding
      from (
        select t.id, t.business_date,
          t.amount - public.ledger_card_sale_consumed_v1(t.id) as outstanding
        from public.ledger_transactions t
        where t.status = 'confirmed'
          and t.source_type = 'pos_sales_daily_payment'
          and t.source_key like 'pos:%:card'
          and t.business_date <= v_date
      ) c
      where c.outstanding > 0
    ) eligible
    order by eligible.business_date, eligible.id
  loop
    exit when v_remaining <= 0;
    v_allocated := least(v_remaining, v_sale.outstanding);
    insert into public.ledger_card_reconciliation_lines(reconciliation_id, pos_card_transaction_id, allocated_gross_amount)
    values (v_reconciliation, v_sale.id, v_allocated);
    v_allocations := v_allocations || jsonb_build_array(jsonb_build_object(
      'transactionId', v_sale.id,
      'businessDate', v_sale.business_date,
      'outstandingBefore', v_sale.outstanding,
      'allocatedAmount', v_allocated,
      'outstandingAfter', v_sale.outstanding - v_allocated
    ));
    v_remaining := v_remaining - v_allocated;
  end loop;
  if v_remaining <> 0 then
    -- Unreachable after the availability check; abort so nothing above is kept.
    raise exception 'card auto allocation left % unallocated', v_remaining;
  end if;

  insert into public.ledger_audit_logs(
    actor_user_id, action, entity_type, entity_id, after_snapshot, reason
  ) values (
    p_actor_user_id, 'card_deposit_auto_allocated', 'card_reconciliation', v_reconciliation,
    jsonb_build_object(
      'depositTransactionId', v_transaction,
      'bankAccountId', v_bank,
      'depositAmount', p_amount,
      'beforePendingBalance', v_balance,
      'afterPendingBalance', v_balance - p_amount,
      'allocations', v_allocations,
      'matchedGrossAmount', p_amount,
      'differenceAmount', 0,
      'status', 'auto_allocated'
    ),
    nullif(btrim(p_memo), '')
  );
  return jsonb_build_object(
    'status', 'created',
    'reconciliationId', v_reconciliation,
    'transactionId', v_transaction,
    'totalAllocated', p_amount,
    'allocations', v_allocations
  );
exception
  when check_violation or foreign_key_violation or not_null_violation then
    return jsonb_build_object('status', 'invalid_input');
end;
$$;

-- Legacy manual matching: unchanged from 20260927144325 except the over-allocation guard counts fee allocations.
create or replace function public.ledger_match_card_reconciliation_v1(
  p_reconciliation_id bigint,
  p_allocations jsonb,
  p_confirm boolean,
  p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text;
  v_rec public.ledger_card_reconciliations%rowtype;
  v_item jsonb;
  v_id bigint;
  v_amount numeric;
  v_gross numeric := 0;
  v_other numeric;
  v_sale public.ledger_transactions%rowtype;
  v_clearing bigint;
  v_balance numeric;
  v_diff numeric;
  v_category bigint;
  v_diff_tx bigint;
  v_before jsonb;
  v_ids bigint[] := array[]::bigint[];
  v_deposit_date date;
  v_month date;
begin
  select lower(role::text) into v_role
  from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master') then
    return jsonb_build_object('status', 'forbidden');
  end if;
  if jsonb_typeof(p_allocations) <> 'array' or jsonb_array_length(p_allocations) = 0 then
    return jsonb_build_object('status', 'invalid_allocations');
  end if;

  select deposit_date into v_deposit_date
  from public.ledger_card_reconciliations
  where id = p_reconciliation_id;
  if v_deposit_date is null then return jsonb_build_object('status', 'not_found'); end if;
  v_month := date_trunc('month', v_deposit_date)::date;
  perform pg_advisory_xact_lock(hashtext('ledger_month_close:' || to_char(v_month, 'YYYY-MM')));
  if public.ledger_month_is_closed_v1(v_month) then
    return jsonb_build_object('status', 'month_closed');
  end if;
  perform pg_advisory_xact_lock(hashtext('ledger_card_clearing_balance'));

  select * into v_rec
  from public.ledger_card_reconciliations
  where id = p_reconciliation_id
  for update;
  if v_rec.id is null then return jsonb_build_object('status', 'not_found'); end if;
  if v_rec.deposit_date is distinct from v_deposit_date then return jsonb_build_object('status', 'invalid_state'); end if;
  -- auto_allocated rows own FIFO lines written at registration; they are never re-matched.
  if v_rec.status in ('matched', 'auto_allocated', 'cancelled') then return jsonb_build_object('status', 'immutable'); end if;

  v_before := to_jsonb(v_rec);
  select array_agg(distinct (x->>'transactionId')::bigint order by (x->>'transactionId')::bigint)
    into v_ids
  from jsonb_array_elements(p_allocations) x;
  if cardinality(v_ids) <> jsonb_array_length(p_allocations) then
    return jsonb_build_object('status', 'duplicate_card_sale');
  end if;
  perform 1 from public.ledger_transactions where id = any(v_ids) order by id for update;

  for v_item in select value from jsonb_array_elements(p_allocations) loop
    begin
      v_id := (v_item->>'transactionId')::bigint;
      v_amount := (v_item->>'allocatedGrossAmount')::numeric;
    exception when others then
      return jsonb_build_object('status', 'invalid_allocations');
    end;
    if v_amount <= 0 or scale(v_amount) > 3 then
      return jsonb_build_object('status', 'invalid_allocations');
    end if;
    select * into v_sale
    from public.ledger_transactions
    where id = v_id
      and status = 'confirmed'
      and source_type = 'pos_sales_daily_payment'
      and source_key like 'pos:%:card';
    if v_sale.id is null then return jsonb_build_object('status', 'invalid_card_sale'); end if;
    if v_sale.business_date > v_rec.deposit_date then
      return jsonb_build_object(
        'status', 'future_card_sale',
        'transactionId', v_id,
        'saleBusinessDate', v_sale.business_date,
        'depositDate', v_rec.deposit_date
      );
    end if;
    -- Everything else consuming this sale: other deposits' lines and active card fee
    -- allocations (this reconciliation's own lines are replaced below).
    select public.ledger_card_sale_consumed_v1(v_id) - coalesce(sum(l.allocated_gross_amount), 0) into v_other
    from public.ledger_card_reconciliation_lines l
    where l.pos_card_transaction_id = v_id and l.reconciliation_id = v_rec.id;
    if v_other + v_amount > v_sale.amount then
      return jsonb_build_object('status', 'gross_overallocated', 'transactionId', v_id);
    end if;
    v_gross := v_gross + v_amount;
  end loop;

  if p_confirm and v_gross < v_rec.deposit_amount then
    return jsonb_build_object('status', 'gross_below_deposit', 'matchedGrossAmount', v_gross);
  end if;
  if p_confirm then
    v_diff := v_gross - v_rec.deposit_amount;
    select id into v_clearing
    from public.ledger_fund_accounts
    where code = 'card_clearing' and is_active = true
    for update;
    select coalesce(sum(m.amount), 0) into v_balance
    from public.ledger_movements m
    join public.ledger_transactions t on t.id = m.transaction_id
    where m.fund_account_id = v_clearing and t.status = 'confirmed';
    if v_balance < v_diff then
      return jsonb_build_object('status', 'insufficient_card_pending', 'pendingBalance', v_balance);
    end if;
    if v_diff > 0 then
      select id into v_category
      from public.ledger_categories
      where kind = 'expense' and name = '카드 정산 차액' and is_active = true;
      if v_category is null then return jsonb_build_object('status', 'category_missing'); end if;
    end if;
  end if;

  delete from public.ledger_card_reconciliation_lines where reconciliation_id = v_rec.id;
  insert into public.ledger_card_reconciliation_lines(
    reconciliation_id, pos_card_transaction_id, allocated_gross_amount
  )
  select v_rec.id, (x->>'transactionId')::bigint, (x->>'allocatedGrossAmount')::numeric
  from jsonb_array_elements(p_allocations) x;

  if not p_confirm then
    update public.ledger_card_reconciliations
    set matched_gross_amount = v_gross,
        status = case when v_gross = 0 then 'unmatched' else 'partial' end,
        updated_at = now()
    where id = v_rec.id;
    insert into public.ledger_audit_logs(
      actor_user_id, action, entity_type, entity_id, before_snapshot, after_snapshot, reason
    ) values (
      p_actor_user_id, 'card_reconciliation_partial', 'card_reconciliation', v_rec.id, v_before,
      jsonb_build_object(
        'depositTransactionId', v_rec.deposit_transaction_id,
        'bankAccountId', v_rec.destination_fund_account_id,
        'depositAmount', v_rec.deposit_amount,
        'allocations', p_allocations,
        'matchedGrossAmount', v_gross,
        'differenceAmount', 0,
        'status', 'partial'
      ),
      'Card settlement partial match'
    );
    return jsonb_build_object('status', 'partial', 'matchedGrossAmount', v_gross);
  end if;

  if v_diff > 0 then
    insert into public.ledger_transactions(
      operation_id, type, occurred_at, business_date, recognition_month, amount,
      category_id, status, source_type, source_key, source_snapshot,
      source_fingerprint, source_synced_at, memo, created_by, confirmed_by
    )
    select
      d.operation_id, 'expense_recognition', d.occurred_at, v_rec.deposit_date,
      date_trunc('month', v_rec.deposit_date)::date, v_diff, v_category, 'confirmed',
      'card_settlement_difference', 'card-reconciliation:' || v_rec.id || ':difference',
      jsonb_build_object(
        'reconciliationId', v_rec.id,
        'depositAmount', v_rec.deposit_amount,
        'matchedGrossAmount', v_gross,
        'differenceAmount', v_diff,
        'sales', (
          select jsonb_agg(jsonb_build_object(
            'transactionId', l.pos_card_transaction_id,
            'businessDate', t.business_date,
            'allocatedGrossAmount', l.allocated_gross_amount
          ))
          from public.ledger_card_reconciliation_lines l
          join public.ledger_transactions t on t.id = l.pos_card_transaction_id
          where l.reconciliation_id = v_rec.id
        )
      ),
      md5(v_rec.id::text || ':' || v_gross::text || ':' || v_rec.deposit_amount::text),
      now(), '카드 정산 차액', p_actor_user_id, p_actor_user_id
    from public.ledger_transactions d
    where d.id = v_rec.deposit_transaction_id
    returning id into v_diff_tx;
    insert into public.ledger_movements(transaction_id, fund_account_id, amount)
    values (v_diff_tx, v_clearing, -v_diff);
  end if;

  update public.ledger_card_reconciliations
  set matched_gross_amount = v_gross,
      difference_amount = v_diff,
      status = 'matched',
      confirmed_at = now(),
      confirmed_by = p_actor_user_id,
      updated_at = now()
  where id = v_rec.id;
  insert into public.ledger_audit_logs(
    actor_user_id, action, entity_type, entity_id, before_snapshot, after_snapshot, reason
  ) values (
    p_actor_user_id, 'card_reconciliation_matched', 'card_reconciliation', v_rec.id, v_before,
    jsonb_build_object(
      'depositTransactionId', v_rec.deposit_transaction_id,
      'bankAccountId', v_rec.destination_fund_account_id,
      'depositAmount', v_rec.deposit_amount,
      'allocations', p_allocations,
      'matchedGrossAmount', v_gross,
      'differenceAmount', v_diff,
      'beforePendingBalance', v_balance,
      'afterPendingBalance', v_balance - v_diff,
      'status', 'matched'
    ),
    'Card settlement confirmed'
  );
  return jsonb_build_object(
    'status', 'matched',
    'matchedGrossAmount', v_gross,
    'differenceAmount', v_diff,
    'differenceTransactionId', v_diff_tx
  );
end;
$$;

-- Month-close preflight: patched in place like 20260921170100, so the latest live definition
-- (including PAYMENT_VERIFICATION_UNRESOLVED / PAYMENT_VERIFICATION_LATER_PAID and the
-- paymentVerification split of PAYABLE_OUTSTANDING) is the baseline. Only three card fee
-- changes are applied: fee-aware CARD_OVERALLOCATED, CARD_FEE_NOT_CONFIRMED, cardFeeState in
-- the hash. Any anchor mismatch aborts the migration instead of silently dropping a contract.
do $card_fee_preflight$
declare
  v_oid regprocedure := 'public.ledger_close_preflight_v1(date,bigint)'::regprocedure;
  v_definition text;
  v_declare text := 'declare v_role text;v_blockers jsonb:=''[]'';v_warnings jsonb:=''[]'';v_token text;v_count bigint;v_amount numeric;';
  v_overallocated text := ' if exists(select 1 from public.ledger_transactions t join public.ledger_card_reconciliation_lines l on l.pos_card_transaction_id=t.id join public.ledger_card_reconciliations r on r.id=l.reconciliation_id and r.status<>''cancelled'' group by t.id,t.amount having sum(l.allocated_gross_amount)>t.amount)then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object(''code'',''CARD_OVERALLOCATED''));end if;';
  v_unmatched text := ' select count(*),coalesce(sum(r.deposit_amount),0) into v_count,v_amount from public.ledger_card_reconciliations r where r.status in(''unmatched'',''partial'')and date_trunc(''month'',r.deposit_date)::date=p_month;if v_count>0 then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object(''code'',''CARD_UNMATCHED'',''count'',v_count,''amount'',v_amount));end if;';
  v_card_state text := 'from public.ledger_card_reconciliations r where date_trunc(''month'',r.deposit_date)::date=p_month))::text)';
begin
  v_definition := pg_get_functiondef(v_oid);
  if position('PAYMENT_VERIFICATION_UNRESOLVED' in v_definition) = 0
     or position('PAYMENT_VERIFICATION_LATER_PAID' in v_definition) = 0
     or position('coalesce(t.source_snapshot->>''paymentVerification'','''')<>''pending''' in v_definition) = 0 then
    raise exception 'CARD_FEE_PREFLIGHT_BASELINE_MISSING_PAYMENT_VERIFICATION';
  end if;
  if position('CARD_FEE_NOT_CONFIRMED' in v_definition) > 0 then
    raise exception 'CARD_FEE_PREFLIGHT_ALREADY_PATCHED';
  end if;
  if (length(v_definition) - length(replace(v_definition, v_declare, ''))) / length(v_declare) <> 1
     or (length(v_definition) - length(replace(v_definition, v_overallocated, ''))) / length(v_overallocated) <> 1
     or (length(v_definition) - length(replace(v_definition, v_unmatched, ''))) / length(v_unmatched) <> 1
     or (length(v_definition) - length(replace(v_definition, v_card_state, ''))) / length(v_card_state) <> 1 then
    raise exception 'CARD_FEE_PREFLIGHT_CONTRACT_MISMATCH';
  end if;

  v_definition := replace(v_definition, v_declare, v_declare || 'v_card_gross numeric;v_card_outstanding numeric;');
  -- Deposit lines and month-end fee lines together may never exceed a card sale's gross.
  v_definition := replace(v_definition, v_overallocated,
    ' if exists(select 1 from(select l.pos_card_transaction_id id from public.ledger_card_reconciliation_lines l union select f.pos_card_transaction_id from public.ledger_card_fee_allocation_lines f)s join public.ledger_transactions t on t.id=s.id where public.ledger_card_sale_consumed_v1(t.id)>t.amount)then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object(''code'',''CARD_OVERALLOCATED''));end if;');
  -- A month with card sales closes only after its card fee is confirmed (a zero fee counts).
  v_definition := replace(v_definition, v_unmatched, v_unmatched ||
    ' select coalesce(sum(t.amount),0),coalesce(sum(greatest(t.amount-public.ledger_card_sale_consumed_v1(t.id),0)),0) into v_card_gross,v_card_outstanding from public.ledger_transactions t where t.status=''confirmed''and t.source_type=''pos_sales_daily_payment''and t.source_key like ''pos:%:card''and date_trunc(''month'',t.business_date)::date=p_month;if v_card_gross>0 and not exists(select 1 from public.ledger_card_fee_closures c where c.fee_month=p_month and c.status=''confirmed'')then v_blockers:=v_blockers||jsonb_build_array(jsonb_build_object(''code'',''CARD_FEE_NOT_CONFIRMED'',''amount'',v_card_outstanding));end if;');
  -- Fee confirmations and cancellations change the hash.
  v_definition := replace(v_definition, v_card_state,
    'from public.ledger_card_reconciliations r where date_trunc(''month'',r.deposit_date)::date=p_month),''cardFeeState'',(select coalesce(jsonb_agg(jsonb_build_object(''id'',c.id,''updatedAt'',c.updated_at,''status'',c.status,''feeAmount'',c.fee_amount,''lines'',coalesce((select jsonb_agg(jsonb_build_array(f.pos_card_transaction_id,f.allocated_fee_amount)order by f.pos_card_transaction_id)from public.ledger_card_fee_allocation_lines f where f.closure_id=c.id),''[]''::jsonb))order by c.id),''[]''::jsonb)from public.ledger_card_fee_closures c where c.fee_month=p_month))::text)');
  execute v_definition;
end;
$card_fee_preflight$;

-- POS business-day close: unchanged from 20260912105916 except fee allocations / fee-confirmed months also lock card reclose.
create or replace function public.sales_close_business_day_v1(
  p_business_date date, p_source_fingerprint text, p_source_snapshot jsonb, p_rows jsonb,
  p_actor_user_id bigint, p_close_method text default 'manual',
  p_manual_reclose boolean default false, p_sync_run_id bigint default null
) returns jsonb language plpgsql security definer set search_path = pg_catalog, public as $$
declare
  v_role text; v_existing public.pos_sales_business_day_closures%rowtype;
  v_old_card jsonb; v_new_card jsonb;
  v_result jsonb; v_revision integer; v_id bigint; v_now timestamptz := now();
begin
  select lower(btrim(role::text)) into v_role from public.users
  where id = p_actor_user_id and is_active = true and app_login_enabled = true;
  if coalesce(v_role, '') not in ('owner', 'master', 'manager')
    or (v_role = 'manager' and (p_close_method is distinct from 'manual' or p_manual_reclose is distinct from false)) then
    return jsonb_build_object('status', 'forbidden');
  end if;
  if p_business_date is null or p_close_method is null or p_close_method not in ('manual', 'automatic')
    or p_manual_reclose is null or (p_manual_reclose and p_close_method <> 'manual') then
    raise exception 'INVALID_POS_SALES_CLOSE_REQUEST' using errcode = '22023';
  end if;
  -- Same month key as ledger_close_month_v1; lock order: month, day, source,
  -- existing closure, bucket projection. Close and v3 use the same ordering.
  perform pg_advisory_xact_lock(hashtext('ledger_month_close:' || to_char(p_business_date, 'YYYY-MM')));
  perform pg_advisory_xact_lock(hashtext('pos_sales_business_day_close:' || p_business_date::text));
  if public.ledger_month_is_closed_v1(date_trunc('month', p_business_date)::date) then
    return jsonb_build_object('status', 'month_closed');
  end if;
  lock table public.pos_sales_receipts, public.pos_sales_receipt_payments in share mode;
  perform pos_sales_close_private.validate_source(p_business_date, p_source_fingerprint, p_source_snapshot, p_rows);
  if p_sync_run_id is not null and not exists (
    select 1 from public.pos_sales_sync_runs where id = p_sync_run_id and business_date = p_business_date and status = 'success'
  ) then raise exception 'POS_SALES_SUCCESSFUL_SYNC_RUN_REQUIRED' using errcode = '22023'; end if;

  select * into v_existing from public.pos_sales_business_day_closures
  where business_date = p_business_date order by revision desc limit 1 for update;
  if v_existing.id is not null and v_existing.source_fingerprint = p_source_fingerprint then
    return jsonb_build_object('status', 'already_closed', 'closureId', v_existing.id, 'revision', v_existing.revision);
  end if;
  if v_existing.id is not null and v_role = 'manager' then
    return jsonb_build_object('status', 'forbidden');
  end if;
  if v_existing.id is not null and not p_manual_reclose then
    return jsonb_build_object('status', 'source_changed_after_close', 'closureId', v_existing.id,
      'revision', v_existing.revision, 'closedFingerprint', v_existing.source_fingerprint, 'currentFingerprint', p_source_fingerprint);
  end if;

  if v_existing.id is not null then
    select r into v_old_card from jsonb_array_elements(v_existing.source_snapshot->'rows') r where r->>'bucket' = 'card';
    select r into v_new_card from jsonb_array_elements(p_rows) r where r->>'bucket' = 'card';
    if v_old_card is null or v_new_card is null then
      raise exception 'POS_SOURCE_SNAPSHOT_INCOMPLETE' using errcode = '22023';
    end if;
    if v_old_card->>'fingerprint' is distinct from v_new_card->>'fingerprint'
      or (v_old_card->>'amount')::numeric is distinct from (v_new_card->>'amount')::numeric then
      -- Card reconciliation also locks these POS transactions before allocating.
      -- Holding this row lock makes the settlement check/projection atomic.
      -- Preserve the legacy projector's advisory-key-before-row lock order.
      perform pg_advisory_xact_lock(hashtext('ledger_pos_sync:pos:' || p_business_date::text || ':card'));
      perform 1 from public.ledger_transactions
      where source_type = 'pos_sales_daily_payment' and business_date = p_business_date
        and source_key = 'pos:' || p_business_date::text || ':card'
      order by id for update;
      if exists (
        select 1 from public.ledger_card_reconciliation_lines l
        join public.ledger_card_reconciliations r on r.id = l.reconciliation_id
        join public.ledger_transactions t on t.id = l.pos_card_transaction_id
        where t.source_type = 'pos_sales_daily_payment' and t.business_date = p_business_date
          and t.source_key = 'pos:' || p_business_date::text || ':card'
          and r.status <> 'cancelled'
      ) or exists (
        select 1 from public.ledger_card_fee_allocation_lines f
        join public.ledger_card_fee_closures c on c.id = f.closure_id
        join public.ledger_transactions t on t.id = f.pos_card_transaction_id
        where t.source_type = 'pos_sales_daily_payment' and t.business_date = p_business_date
          and t.source_key = 'pos:' || p_business_date::text || ':card'
          and c.status <> 'cancelled'
      ) or exists (
        select 1 from public.ledger_card_fee_closures c
        where c.status = 'confirmed' and c.fee_month = date_trunc('month', p_business_date)::date
      ) then
        return jsonb_build_object('status', 'card_settlement_locked', 'closureId', v_existing.id, 'revision', v_existing.revision);
      end if;
    end if;
  end if;

  insert into pos_sales_close_private.projection_permissions values (txid_current(), p_business_date, p_actor_user_id);
  v_result := pos_sales_close_private.project_business_day(p_rows, p_actor_user_id);
  if v_result->>'status' is distinct from 'ok' or coalesce((v_result->>'closedMonth')::boolean, false) then
    -- v1 can return a failure after writing earlier buckets. Raising aborts the
    -- entire close transaction, including projection, audit and capability.
    raise exception 'POS_SALES_LEDGER_PROJECTION_FAILED: %', v_result using errcode = 'P0001';
  end if;
  -- Verify the actual projection, including the zero-amount corrected case.
  if exists (
    select 1 from jsonb_array_elements(p_rows) r
    left join public.ledger_transactions t on t.source_type = 'pos_sales_daily_payment'
      and t.source_key = 'pos:' || p_business_date::text || ':' || (r->>'bucket')
    where ((r->>'amount')::numeric > 0 and (t.id is null or t.status <> 'confirmed'
      or t.amount <> (r->>'amount')::numeric or t.source_fingerprint <> r->>'fingerprint'
      or (select coalesce(sum(m.amount), 0) from public.ledger_movements m where m.transaction_id = t.id) <> t.amount))
      or ((r->>'amount')::numeric = 0 and t.status = 'confirmed')
  ) then raise exception 'POS_SALES_LEDGER_PROJECTION_INCOMPLETE' using errcode = 'P0001'; end if;

  delete from pos_sales_close_private.projection_permissions where transaction_id = txid_current() and business_date = p_business_date;
  v_revision := coalesce(v_existing.revision, 0) + 1;
  insert into public.pos_sales_business_day_closures(business_date, revision, close_method, closed_at,
    closed_by, sync_run_id, source_fingerprint, source_snapshot, ledger_result_snapshot)
  values (p_business_date, v_revision, p_close_method, v_now, p_actor_user_id, p_sync_run_id,
    p_source_fingerprint, p_source_snapshot, v_result) returning id into v_id;
  insert into public.ledger_audit_logs(actor_user_id, action, entity_type, entity_id, after_snapshot, reason)
  values (p_actor_user_id, 'pos_sales_day_closed', 'pos_sales_day_closure', v_id,
    jsonb_build_object('businessDate', p_business_date, 'revision', v_revision,
      'previousClosureId', v_existing.id, 'sourceFingerprint', p_source_fingerprint, 'closeMethod', p_close_method),
    case when v_existing.id is null then 'Initial business day close' else 'Explicit manual reclose' end);
  return jsonb_build_object('status', case when v_existing.id is null then 'closed' else 'reclosed' end,
    'closureId', v_id, 'revision', v_revision, 'ledgerResult', v_result);
end $$;

alter function public.ledger_card_fee_closure_month_guard_v1() owner to postgres;
alter function public.ledger_card_fee_line_month_guard_v1() owner to postgres;
alter function public.ledger_card_sale_consumed_v1(bigint) owner to postgres;
alter function public.ledger_card_sale_consumption_guard_v1() owner to postgres;
alter function public.ledger_confirm_card_fee_month_v1(date, text, bigint) owner to postgres;
alter function public.ledger_cancel_card_fee_month_v1(bigint, text, bigint) owner to postgres;

revoke all on function public.ledger_card_fee_closure_month_guard_v1() from public, anon, authenticated, service_role;
revoke all on function public.ledger_card_fee_line_month_guard_v1() from public, anon, authenticated, service_role;
revoke all on function public.ledger_card_sale_consumed_v1(bigint) from public, anon, authenticated, service_role;
revoke all on function public.ledger_card_sale_consumption_guard_v1() from public, anon, authenticated, service_role;
revoke all on function public.ledger_confirm_card_fee_month_v1(date, text, bigint) from public, anon, authenticated;
revoke all on function public.ledger_cancel_card_fee_month_v1(bigint, text, bigint) from public, anon, authenticated;

grant execute on function public.ledger_confirm_card_fee_month_v1(date, text, bigint) to service_role;
grant execute on function public.ledger_cancel_card_fee_month_v1(bigint, text, bigint) to service_role;

comment on table public.ledger_card_fee_closures is
  'Month-end card fee confirmation per POS card sale month. At most one confirmed closure per month; cancelled history is kept.';
comment on table public.ledger_card_fee_allocation_lines is
  'Card sale gross consumed as the month-end card fee; counts toward sale consumption only while its closure is confirmed.';
comment on function public.ledger_confirm_card_fee_month_v1(date, text, bigint) is
  'Manually confirms a past open month''s card fee: recomputes the remaining card sale gross under lock, books it once as card_fee_month_close expense (card_clearing only) and consumes it FIFO. Zero fees record the confirmation only.';
comment on function public.ledger_cancel_card_fee_month_v1(bigint, text, bigint) is
  'Append-only cancellation of a month-end card fee: reverses the expense and card clearing, keeps lines as history and releases the sale gross.';
