create table public.payroll_runs (
  id bigint generated by default as identity primary key,
  payroll_month date not null check (payroll_month >= date '2026-08-01' and payroll_month = date_trunc('month', payroll_month)::date),
  revision bigint not null check (revision >= 1),
  status text not null default 'draft' check (status in ('draft','finalized','paid','cancelled')),
  calculated_at timestamptz not null,
  engine_version text not null,
  source_snapshot jsonb not null,
  employee_count integer not null default 0 check (employee_count >= 0),
  requires_review_count integer not null default 0 check (requires_review_count >= 0),
  total_base_amount bigint not null default 0,
  total_addition_amount bigint not null default 0,
  total_deduction_amount bigint not null default 0 check (total_deduction_amount >= 0),
  total_net_amount bigint not null default 0,
  created_by bigint not null references public.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  finalized_by bigint null references public.users(id), finalized_at timestamptz null, finalize_reason text null,
  paid_by bigint null references public.users(id), paid_at timestamptz null, payment_date date null, payment_method text null, payment_note text null,
  cancelled_by bigint null references public.users(id), cancelled_at timestamptz null, cancel_reason text null,
  constraint payroll_runs_month_revision_unique unique (payroll_month,revision)
);
create unique index payroll_runs_one_active_per_month on public.payroll_runs(payroll_month) where status in ('draft','finalized','paid');

create table public.payroll_run_employees (
  id bigint generated by default as identity primary key,
  payroll_run_id bigint not null references public.payroll_runs(id) on delete restrict,
  user_id bigint not null references public.users(id) on delete restrict,
  employee_name text not null,
  calculation_status text not null default 'calculated' check (calculation_status in ('calculated','requires_review')),
  contract_snapshot jsonb not null default '[]'::jsonb,
  attendance_snapshot jsonb not null,
  recognized_workdays numeric(8,2) not null default 0 check (recognized_workdays >= 0),
  recognized_minutes integer not null default 0 check (recognized_minutes >= 0),
  late_minutes integer not null default 0 check (late_minutes >= 0),
  early_leave_minutes integer not null default 0 check (early_leave_minutes >= 0),
  overtime_candidate_minutes integer not null default 0 check (overtime_candidate_minutes >= 0),
  base_amount bigint not null default 0,
  addition_amount bigint not null default 0,
  deduction_amount bigint not null default 0 check (deduction_amount >= 0),
  net_amount bigint not null default 0,
  admin_note text null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint payroll_run_employee_unique unique(payroll_run_id,user_id)
);

create table public.payroll_run_reviews (
  id bigint generated by default as identity primary key,
  payroll_run_employee_id bigint not null references public.payroll_run_employees(id) on delete restrict,
  warning_code text not null,
  review_level text not null check (review_level in ('blocking','actionable','advisory')),
  business_date date null,
  source_snapshot jsonb not null,
  status text not null default 'open' check (status in ('open','resolved')),
  resolution_action text null,
  resolution_snapshot jsonb null,
  amount_delta bigint not null default 0,
  reason text null,
  resolved_by bigint null references public.users(id), resolved_at timestamptz null,
  created_at timestamptz not null default now(),
  constraint payroll_run_review_resolution_check check ((status='open' and resolution_action is null and resolved_by is null and resolved_at is null) or (status='resolved' and resolution_action is not null and resolved_by is not null and resolved_at is not null)),
  constraint payroll_run_review_unique unique nulls not distinct(payroll_run_employee_id,business_date,warning_code)
);

create table public.payroll_run_items (
  id bigint generated by default as identity primary key,
  payroll_run_employee_id bigint not null references public.payroll_run_employees(id) on delete restrict,
  payroll_run_review_id bigint null references public.payroll_run_reviews(id) on delete restrict,
  item_type text not null check (item_type in ('automatic','manual','review_adjustment')),
  category text not null check (category in ('base_work','paid_leave','overtime','late_deduction','early_leave_deduction','incentive','meal','transport','housing','insurance_tax','advance','penalty','other_addition','other_deduction')),
  direction text not null check (direction in ('addition','deduction')),
  amount bigint not null check (amount >= 0), original_amount bigint null check (original_amount is null or original_amount >= 0),
  business_date date null, source_snapshot jsonb not null default '{}'::jsonb,
  description text not null, reason text null,
  created_by bigint not null references public.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint payroll_run_item_category_direction_check check (
    (category in ('base_work','paid_leave','overtime','incentive','meal','transport','housing','other_addition') and direction='addition') or
    (category in ('late_deduction','early_leave_deduction','insurance_tax','advance','penalty','other_deduction') and direction='deduction')
  )
);
create unique index payroll_run_item_review_unique on public.payroll_run_items(payroll_run_review_id) where payroll_run_review_id is not null;

create table public.payroll_run_audit_logs (
  id bigint generated by default as identity primary key,
  payroll_run_id bigint not null references public.payroll_runs(id) on delete restrict,
  payroll_run_employee_id bigint null references public.payroll_run_employees(id) on delete restrict,
  action text not null check (action in ('run_created','run_recalculated','run_cancelled','item_created','item_updated','item_deleted','review_resolved','run_finalized','finalization_cancelled','run_paid','force_finalized')),
  actor_user_id bigint not null references public.users(id), reason text null,
  before_snapshot jsonb null, after_snapshot jsonb null,
  created_at timestamptz not null default now()
);

create index payroll_run_employees_run_idx on public.payroll_run_employees(payroll_run_id);
create index payroll_run_reviews_employee_status_idx on public.payroll_run_reviews(payroll_run_employee_id,status);
create index payroll_run_items_employee_idx on public.payroll_run_items(payroll_run_employee_id);
create index payroll_run_audit_run_created_idx on public.payroll_run_audit_logs(payroll_run_id,created_at desc);

alter table public.payroll_runs enable row level security;
alter table public.payroll_run_employees enable row level security;
alter table public.payroll_run_reviews enable row level security;
alter table public.payroll_run_items enable row level security;
alter table public.payroll_run_audit_logs enable row level security;
revoke all on table public.payroll_runs,public.payroll_run_employees,public.payroll_run_reviews,public.payroll_run_items,public.payroll_run_audit_logs from public,anon,authenticated,service_role;
revoke all on sequence public.payroll_runs_id_seq,public.payroll_run_employees_id_seq,public.payroll_run_reviews_id_seq,public.payroll_run_items_id_seq,public.payroll_run_audit_logs_id_seq from public,anon,authenticated,service_role;
grant select on table public.payroll_runs,public.payroll_run_employees,public.payroll_run_reviews,public.payroll_run_items,public.payroll_run_audit_logs to service_role;

create function public.payroll_assert_actor_v2(p_actor_user_id bigint) returns void language plpgsql security definer set search_path=public as $$
begin
  perform 1 from public.users where id=p_actor_user_id and is_active=true and role in ('owner','master');
  if not found then raise exception 'PAYROLL_FORBIDDEN' using errcode='42501'; end if;
end $$;

create function public.payroll_refresh_totals_v2(p_run_id bigint) returns void language plpgsql security definer set search_path=public as $$
begin
  update public.payroll_run_employees e set
    calculation_status=case when exists(select 1 from public.payroll_run_reviews rv where rv.payroll_run_employee_id=e.id and rv.status='open') then 'requires_review' else 'calculated' end,
    recognized_workdays=coalesce(x.recognized_days,0),recognized_minutes=coalesce(x.recognized_minutes,0),late_minutes=coalesce(x.late_minutes,0),early_leave_minutes=coalesce(x.early_leave_minutes,0),overtime_candidate_minutes=coalesce(x.overtime_minutes,0),
    base_amount=coalesce(x.base_amount,0),addition_amount=coalesce(x.additions,0),deduction_amount=coalesce(x.deductions,0),
    net_amount=coalesce(x.base_amount,0)+coalesce(x.additions,0)-coalesce(x.deductions,0),updated_at=now()
  from(select re.id,
    coalesce(sum(i.amount) filter(where i.direction='addition' and i.category in ('base_work','paid_leave')),0)::bigint base_amount,
    coalesce(sum(i.amount) filter(where i.direction='addition' and i.category not in ('base_work','paid_leave')),0)::bigint additions,
    coalesce(sum(i.amount) filter(where i.direction='deduction'),0)::bigint deductions,
    coalesce(sum((i.source_snapshot->>'recognizedDays')::numeric) filter(where i.category in('base_work','paid_leave')),0) recognized_days,
    coalesce(sum((i.source_snapshot->>'recognizedMinutes')::integer) filter(where i.category in('base_work','paid_leave')),0)::integer recognized_minutes,
    coalesce(sum((i.source_snapshot->>'lateMinutes')::integer) filter(where i.category='base_work'),0)::integer late_minutes,
    coalesce(sum((i.source_snapshot->>'earlyLeaveMinutes')::integer) filter(where i.category='base_work'),0)::integer early_leave_minutes,
    coalesce(sum((i.source_snapshot->>'overtimeCandidateMinutes')::integer) filter(where i.category='base_work'),0)::integer overtime_minutes
    from public.payroll_run_employees re left join public.payroll_run_items i on i.payroll_run_employee_id=re.id where re.payroll_run_id=p_run_id group by re.id)x where e.id=x.id;
  update public.payroll_runs r set employee_count=x.employee_count,requires_review_count=x.review_count,total_base_amount=x.base_amount,total_addition_amount=x.additions,total_deduction_amount=x.deductions,total_net_amount=x.net_amount,updated_at=now()
  from(select count(*)::integer employee_count,count(*) filter(where calculation_status='requires_review')::integer review_count,coalesce(sum(base_amount),0)::bigint base_amount,coalesce(sum(addition_amount),0)::bigint additions,coalesce(sum(deduction_amount),0)::bigint deductions,coalesce(sum(net_amount),0)::bigint net_amount from public.payroll_run_employees where payroll_run_id=p_run_id)x where r.id=p_run_id;
end $$;

create function public.payroll_insert_payload_v2(p_run_id bigint,p_employees jsonb,p_actor_user_id bigint,p_copy_manual_from_run_id bigint default null) returns void language plpgsql security definer set search_path=public as $$
declare v_employee jsonb;v_employee_id bigint;v_item jsonb;v_review jsonb;
begin
  if jsonb_typeof(p_employees)<>'array' then raise exception 'PAYROLL_INVALID_EMPLOYEES'; end if;
  for v_employee in select value from jsonb_array_elements(p_employees) loop
    insert into public.payroll_run_employees(payroll_run_id,user_id,employee_name,contract_snapshot,attendance_snapshot,recognized_workdays,recognized_minutes,late_minutes,early_leave_minutes,overtime_candidate_minutes)
    values(p_run_id,(v_employee->>'userId')::bigint,v_employee->>'employeeName',coalesce(v_employee->'contractSnapshot','[]'::jsonb),v_employee->'attendanceSnapshot',coalesce((v_employee->>'recognizedWorkdays')::numeric,0),coalesce((v_employee->>'recognizedMinutes')::integer,0),coalesce((v_employee->>'lateMinutes')::integer,0),coalesce((v_employee->>'earlyLeaveMinutes')::integer,0),coalesce((v_employee->>'overtimeCandidateMinutes')::integer,0)) returning id into v_employee_id;
    for v_item in select value from jsonb_array_elements(coalesce(v_employee->'items','[]'::jsonb)) loop
      insert into public.payroll_run_items(payroll_run_employee_id,item_type,category,direction,amount,original_amount,business_date,source_snapshot,description,created_by)
      values(v_employee_id,'automatic',v_item->>'category',v_item->>'direction',(v_item->>'amount')::bigint,(v_item->>'originalAmount')::bigint,(v_item->>'businessDate')::date,coalesce(v_item->'sourceSnapshot','{}'::jsonb),v_item->>'description',p_actor_user_id);
    end loop;
    for v_review in select value from jsonb_array_elements(coalesce(v_employee->'reviews','[]'::jsonb)) loop
      insert into public.payroll_run_reviews(payroll_run_employee_id,warning_code,review_level,business_date,source_snapshot)
      values(v_employee_id,v_review->>'warningCode',v_review->>'reviewLevel',(v_review->>'businessDate')::date,coalesce(v_review->'sourceSnapshot','{}'::jsonb));
    end loop;
    if p_copy_manual_from_run_id is not null then
      insert into public.payroll_run_items(payroll_run_employee_id,item_type,category,direction,amount,original_amount,business_date,source_snapshot,description,reason,created_by)
      select v_employee_id,'manual',i.category,i.direction,i.amount,i.original_amount,i.business_date,i.source_snapshot,i.description,i.reason,p_actor_user_id
      from public.payroll_run_items i join public.payroll_run_employees old_e on old_e.id=i.payroll_run_employee_id
      where old_e.payroll_run_id=p_copy_manual_from_run_id and old_e.user_id=(v_employee->>'userId')::bigint and i.item_type='manual';
    end if;
  end loop;
  perform public.payroll_refresh_totals_v2(p_run_id);
end $$;

create function public.payroll_create_run_v2(p_month date,p_calculated_at timestamptz,p_engine_version text,p_source_snapshot jsonb,p_employees jsonb,p_actor_user_id bigint) returns bigint language plpgsql security definer set search_path=public as $$
declare v_run_id bigint;v_revision bigint;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);
  if p_month<date '2026-08-01' or p_month<>date_trunc('month',p_month)::date then raise exception 'PAYROLL_MONTH_NOT_SUPPORTED' using errcode='22023'; end if;
  perform pg_advisory_xact_lock(82117,(extract(year from p_month)::integer*100+extract(month from p_month)::integer));
  if exists(select 1 from public.payroll_runs where payroll_month=p_month and status in('draft','finalized','paid')) then raise exception 'PAYROLL_ACTIVE_RUN_EXISTS' using errcode='23505'; end if;
  select coalesce(max(revision),0)+1 into v_revision from public.payroll_runs where payroll_month=p_month;
  insert into public.payroll_runs(payroll_month,revision,status,calculated_at,engine_version,source_snapshot,created_by) values(p_month,v_revision,'draft',p_calculated_at,p_engine_version,p_source_snapshot,p_actor_user_id) returning id into v_run_id;
  perform public.payroll_insert_payload_v2(v_run_id,p_employees,p_actor_user_id,null);
  insert into public.payroll_run_audit_logs(payroll_run_id,action,actor_user_id,after_snapshot) select id,'run_created',p_actor_user_id,to_jsonb(r) from public.payroll_runs r where id=v_run_id;
  return v_run_id;
end $$;

create function public.payroll_recalculate_run_v2(p_run_id bigint,p_calculated_at timestamptz,p_engine_version text,p_source_snapshot jsonb,p_employees jsonb,p_actor_user_id bigint) returns bigint language plpgsql security definer set search_path=public as $$
declare v_old public.payroll_runs%rowtype;v_new_id bigint;v_revision bigint;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);select * into v_old from public.payroll_runs where id=p_run_id for update;if not found then raise exception 'PAYROLL_RUN_NOT_FOUND';end if;
  perform pg_advisory_xact_lock(82117,(extract(year from v_old.payroll_month)::integer*100+extract(month from v_old.payroll_month)::integer));
  if v_old.status<>'draft' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000';end if;
  select coalesce(max(revision),0)+1 into v_revision from public.payroll_runs where payroll_month=v_old.payroll_month;
  insert into public.payroll_runs(payroll_month,revision,status,calculated_at,engine_version,source_snapshot,created_by) values(v_old.payroll_month,v_revision,'cancelled',p_calculated_at,p_engine_version,p_source_snapshot,p_actor_user_id) returning id into v_new_id;
  perform public.payroll_insert_payload_v2(v_new_id,p_employees,p_actor_user_id,v_old.id);
  insert into public.payroll_run_audit_logs(payroll_run_id,action,actor_user_id,before_snapshot,after_snapshot) values(v_old.id,'run_recalculated',p_actor_user_id,to_jsonb(v_old),jsonb_build_object('replacementRunId',v_new_id,'replacementRevision',v_revision));
  update public.payroll_runs set status='cancelled',cancelled_by=p_actor_user_id,cancelled_at=now(),cancel_reason='Recalculated',updated_at=now() where id=v_old.id;
  update public.payroll_runs set status='draft',updated_at=now() where id=v_new_id;
  insert into public.payroll_run_audit_logs(payroll_run_id,action,actor_user_id,after_snapshot) select id,'run_created',p_actor_user_id,to_jsonb(r) from public.payroll_runs r where id=v_new_id;
  return v_new_id;
end $$;

create function public.payroll_mutate_item_v2(p_run_id bigint,p_run_employee_id bigint,p_item_id bigint,p_operation text,p_category text,p_direction text,p_amount bigint,p_description text,p_reason text,p_actor_user_id bigint) returns bigint language plpgsql security definer set search_path=public as $$
declare v_status text;v_item public.payroll_run_items%rowtype;v_item_id bigint;v_before jsonb;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);select r.status into v_status from public.payroll_runs r join public.payroll_run_employees e on e.payroll_run_id=r.id where r.id=p_run_id and e.id=p_run_employee_id for update of r;if not found then raise exception 'PAYROLL_EMPLOYEE_RUN_MISMATCH';end if;if v_status<>'draft' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000';end if;
  if p_operation='create' then
    insert into public.payroll_run_items(payroll_run_employee_id,item_type,category,direction,amount,description,reason,created_by) values(p_run_employee_id,'manual',p_category,p_direction,p_amount,p_description,p_reason,p_actor_user_id) returning * into v_item;
    insert into public.payroll_run_audit_logs(payroll_run_id,payroll_run_employee_id,action,actor_user_id,reason,after_snapshot) values(p_run_id,p_run_employee_id,'item_created',p_actor_user_id,p_reason,to_jsonb(v_item));
  elsif p_operation in('update','delete') then
    select * into v_item from public.payroll_run_items where id=p_item_id and payroll_run_employee_id=p_run_employee_id and item_type='manual' for update;if not found then raise exception 'PAYROLL_ITEM_NOT_FOUND';end if;v_before:=to_jsonb(v_item);
    if p_operation='update' then update public.payroll_run_items set category=p_category,direction=p_direction,amount=p_amount,description=p_description,reason=p_reason,updated_at=now() where id=p_item_id returning * into v_item;insert into public.payroll_run_audit_logs(payroll_run_id,payroll_run_employee_id,action,actor_user_id,reason,before_snapshot,after_snapshot) values(p_run_id,p_run_employee_id,'item_updated',p_actor_user_id,p_reason,v_before,to_jsonb(v_item));
    else delete from public.payroll_run_items where id=p_item_id returning id into v_item_id;insert into public.payroll_run_audit_logs(payroll_run_id,payroll_run_employee_id,action,actor_user_id,reason,before_snapshot) values(p_run_id,p_run_employee_id,'item_deleted',p_actor_user_id,p_reason,v_before);end if;
  else raise exception 'PAYROLL_INVALID_ITEM_OPERATION';end if;
  perform public.payroll_refresh_totals_v2(p_run_id);return coalesce(v_item.id,v_item_id);
end $$;

create function public.payroll_resolve_review_v2(p_run_id bigint,p_run_employee_id bigint,p_review_id bigint,p_action text,p_custom_minutes integer,p_reason text,p_actor_user_id bigint) returns void language plpgsql security definer set search_path=public as $$
declare v_status text;v_review public.payroll_run_reviews%rowtype;v_before jsonb;v_amount bigint:=0;v_minutes integer:=0;v_category text;v_direction text:='addition';v_resolution jsonb;v_signed_delta bigint:=0;v_recalculate_automatic boolean:=false;v_selected_items jsonb;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);select r.status into v_status from public.payroll_runs r join public.payroll_run_employees e on e.payroll_run_id=r.id where r.id=p_run_id and e.id=p_run_employee_id for update of r;if not found then raise exception 'PAYROLL_EMPLOYEE_RUN_MISMATCH';end if;if v_status<>'draft' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000';end if;
  select * into v_review from public.payroll_run_reviews where id=p_review_id and payroll_run_employee_id=p_run_employee_id for update;if not found then raise exception 'PAYROLL_REVIEW_NOT_FOUND';end if;if v_review.status<>'open' then raise exception 'PAYROLL_REVIEW_ALREADY_RESOLVED';end if;
  if v_review.warning_code='OVERTIME_APPROVAL_UNAVAILABLE' and p_action in('approve_overtime','exclude_overtime','custom_overtime_minutes') then
    if p_action='custom_overtime_minutes' and (p_custom_minutes is null or p_custom_minutes<0) then raise exception 'PAYROLL_INVALID_CUSTOM_MINUTES' using errcode='22023';end if;
    v_category:='overtime';v_minutes:=case when p_action='approve_overtime' then coalesce((v_review.source_snapshot->>'candidateMinutes')::integer,0) when p_action='custom_overtime_minutes' then p_custom_minutes else 0 end;v_amount:=round(coalesce((v_review.source_snapshot->>'minuteRate')::numeric,0)*v_minutes)::bigint;
  elsif v_review.warning_code='LEAVE_PAYROLL_TREATMENT_UNSPECIFIED' and p_action in('paid_leave','unpaid_leave') then v_category:='paid_leave';v_amount:=case when p_action='paid_leave' then round(coalesce((v_review.source_snapshot->>'dayRate')::numeric,0))::bigint else 0 end;
  elsif v_review.warning_code='PENDING_LEAVE_APPROVAL' and p_action='exclude_pending_leave' then v_amount:=0;
  elsif v_review.warning_code like 'STORED_%_MISMATCH' and p_action in('use_stored_attendance','use_recalculated_attendance','acknowledged') then v_selected_items:=case when p_action='use_stored_attendance' then v_review.source_snapshot->'storedAutomaticItems' when p_action='use_recalculated_attendance' then v_review.source_snapshot->'recalculatedAutomaticItems' else null end;v_recalculate_automatic:=v_selected_items is not null;v_signed_delta:=case when v_recalculate_automatic then coalesce((v_review.source_snapshot->>'amountDelta')::bigint,0) else 0 end;v_amount:=abs(v_signed_delta);
  elsif v_review.warning_code in('LATE_POLICY_REVIEW','EARLY_LEAVE_POLICY_REVIEW') and p_action='acknowledged' then v_amount:=0;
  elsif v_review.warning_code in('MISSING_CHECK_IN','MISSING_CHECK_OUT','INVALID_TIME_RANGE','SCHEDULE_HISTORY_UNAVAILABLE') and p_action='exclude_date' then v_amount:=0;
  else raise exception 'PAYROLL_INVALID_REVIEW_ACTION' using errcode='22023';end if;
  v_before:=to_jsonb(v_review);v_resolution:=jsonb_build_object('action',p_action,'candidateMinutes',v_review.source_snapshot->'candidateMinutes','recognizedMinutes',case when p_action='paid_leave' then coalesce((v_review.source_snapshot->>'standardMinutesPerDay')::integer,0) else v_minutes end,'recognizedDays',case when p_action='paid_leave' then 1 else 0 end,'lateMinutes',0,'earlyLeaveMinutes',0,'overtimeCandidateMinutes',0,'amount',v_amount,'reason',p_reason);
  update public.payroll_run_reviews set status='resolved',resolution_action=p_action,resolution_snapshot=v_resolution,amount_delta=case when v_recalculate_automatic then v_signed_delta when v_direction='deduction' then -v_amount else v_amount end,reason=p_reason,resolved_by=p_actor_user_id,resolved_at=now() where id=p_review_id;
  delete from public.payroll_run_items where payroll_run_review_id=p_review_id;
  if p_action in('exclude_date','exclude_pending_leave') then
    delete from public.payroll_run_items where payroll_run_employee_id=p_run_employee_id and item_type='automatic' and business_date=v_review.business_date;
  elsif v_recalculate_automatic then
    delete from public.payroll_run_items where payroll_run_employee_id=p_run_employee_id and item_type='automatic' and business_date=v_review.business_date;
    insert into public.payroll_run_items(payroll_run_employee_id,item_type,category,direction,amount,original_amount,business_date,source_snapshot,description,created_by)
    select p_run_employee_id,'automatic',x->>'category',x->>'direction',(x->>'amount')::bigint,(x->>'amount')::bigint,v_review.business_date,coalesce(x->'sourceSnapshot','{}'::jsonb)||jsonb_build_object('attendanceResolution',v_resolution),x->>'description',p_actor_user_id from jsonb_array_elements(v_selected_items)x;
  elsif v_amount>0 then insert into public.payroll_run_items(payroll_run_employee_id,payroll_run_review_id,item_type,category,direction,amount,original_amount,business_date,source_snapshot,description,reason,created_by) values(p_run_employee_id,p_review_id,'review_adjustment',v_category,v_direction,v_amount,v_amount,v_review.business_date,v_resolution,'Review resolution adjustment',p_reason,p_actor_user_id);end if;
  perform public.payroll_refresh_totals_v2(p_run_id);insert into public.payroll_run_audit_logs(payroll_run_id,payroll_run_employee_id,action,actor_user_id,reason,before_snapshot,after_snapshot) values(p_run_id,p_run_employee_id,'review_resolved',p_actor_user_id,p_reason,v_before,to_jsonb((select rv from public.payroll_run_reviews rv where id=p_review_id)));
end $$;

create function public.payroll_transition_run_v2(p_run_id bigint,p_action text,p_reason text,p_payment_date date,p_payment_method text,p_payment_note text,p_actor_user_id bigint) returns void language plpgsql security definer set search_path=public as $$
declare v_run public.payroll_runs%rowtype;v_before jsonb;v_audit text;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);select * into v_run from public.payroll_runs where id=p_run_id for update;if not found then raise exception 'PAYROLL_RUN_NOT_FOUND';end if;v_before:=to_jsonb(v_run);
  if p_action='finalize' then if v_run.status<>'draft' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000';end if;if v_run.requires_review_count>0 then raise exception 'PAYROLL_OPEN_REVIEWS' using errcode='22023';end if;v_audit:='run_finalized';update public.payroll_runs set status='finalized',finalized_by=p_actor_user_id,finalized_at=now(),finalize_reason=null,updated_at=now() where id=p_run_id;
  elsif p_action='force_finalize' then if v_run.status<>'draft' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000';end if;if nullif(btrim(p_reason),'') is null then raise exception 'PAYROLL_FORCE_REASON_REQUIRED' using errcode='22023';end if;v_audit:='force_finalized';update public.payroll_runs set status='finalized',finalized_by=p_actor_user_id,finalized_at=now(),finalize_reason=btrim(p_reason),updated_at=now() where id=p_run_id;
  elsif p_action='cancel_finalization' then if v_run.status<>'finalized' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000';end if;if nullif(btrim(p_reason),'') is null then raise exception 'PAYROLL_REASON_REQUIRED' using errcode='22023';end if;v_audit:='finalization_cancelled';update public.payroll_runs set status='draft',finalized_by=null,finalized_at=null,finalize_reason=null,updated_at=now() where id=p_run_id;
  elsif p_action='pay' then if v_run.status<>'finalized' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000';end if;if p_payment_date is null or nullif(btrim(p_payment_method),'') is null then raise exception 'PAYROLL_PAYMENT_REQUIRED' using errcode='22023';end if;v_audit:='run_paid';update public.payroll_runs set status='paid',paid_by=p_actor_user_id,paid_at=now(),payment_date=p_payment_date,payment_method=p_payment_method,payment_note=nullif(btrim(p_payment_note),''),updated_at=now() where id=p_run_id;
  elsif p_action='cancel' then if v_run.status<>'draft' then raise exception 'PAYROLL_RUN_LOCKED' using errcode='55000';end if;if nullif(btrim(p_reason),'') is null then raise exception 'PAYROLL_REASON_REQUIRED' using errcode='22023';end if;v_audit:='run_cancelled';update public.payroll_runs set status='cancelled',cancelled_by=p_actor_user_id,cancelled_at=now(),cancel_reason=p_reason,updated_at=now() where id=p_run_id;
  else raise exception 'PAYROLL_INVALID_TRANSITION' using errcode='22023';end if;
  insert into public.payroll_run_audit_logs(payroll_run_id,action,actor_user_id,reason,before_snapshot,after_snapshot) select p_run_id,v_audit,p_actor_user_id,coalesce(p_reason,p_payment_note),v_before,to_jsonb(r) from public.payroll_runs r where id=p_run_id;
end $$;

revoke all on function public.payroll_assert_actor_v2(bigint),public.payroll_refresh_totals_v2(bigint),public.payroll_insert_payload_v2(bigint,jsonb,bigint,bigint),public.payroll_create_run_v2(date,timestamptz,text,jsonb,jsonb,bigint),public.payroll_recalculate_run_v2(bigint,timestamptz,text,jsonb,jsonb,bigint),public.payroll_mutate_item_v2(bigint,bigint,bigint,text,text,text,bigint,text,text,bigint),public.payroll_resolve_review_v2(bigint,bigint,bigint,text,integer,text,bigint),public.payroll_transition_run_v2(bigint,text,text,date,text,text,bigint) from public,anon,authenticated;
grant execute on function public.payroll_create_run_v2(date,timestamptz,text,jsonb,jsonb,bigint) to service_role;
grant execute on function public.payroll_recalculate_run_v2(bigint,timestamptz,text,jsonb,jsonb,bigint) to service_role;
grant execute on function public.payroll_mutate_item_v2(bigint,bigint,bigint,text,text,text,bigint,text,text,bigint) to service_role;
grant execute on function public.payroll_resolve_review_v2(bigint,bigint,bigint,text,integer,text,bigint) to service_role;
grant execute on function public.payroll_transition_run_v2(bigint,text,text,date,text,text,bigint) to service_role;
