begin;

create function public.payroll_validate_tax_brackets_v1(p_brackets jsonb)
returns boolean
language plpgsql
immutable
set search_path=pg_catalog, public
as $$
declare
  v_index integer;
  v_count integer;
  v_bracket jsonb;
  v_lower numeric;
  v_upper numeric;
  v_rate numeric;
  v_expected_lower numeric := 0;
begin
  if jsonb_typeof(p_brackets) <> 'array' then return false; end if;
  v_count := jsonb_array_length(p_brackets);
  if v_count < 1 then return false; end if;
  for v_index in 0..v_count-1 loop
    v_bracket := p_brackets -> v_index;
    if jsonb_typeof(v_bracket) <> 'object'
      or jsonb_typeof(v_bracket -> 'lowerBoundAmount') <> 'number'
      or jsonb_typeof(v_bracket -> 'rateBp') <> 'number' then return false; end if;
    v_lower := (v_bracket ->> 'lowerBoundAmount')::numeric;
    v_rate := (v_bracket ->> 'rateBp')::numeric;
    if v_lower <> trunc(v_lower) or v_lower < 0 or v_lower > 9007199254740991 or v_lower <> v_expected_lower
      or v_rate <> trunc(v_rate) or v_rate < 0 or v_rate >= 10000 then return false; end if;
    if v_index = v_count - 1 then
      if (v_bracket -> 'upperBoundAmount') is distinct from 'null'::jsonb then return false; end if;
    else
      if jsonb_typeof(v_bracket -> 'upperBoundAmount') <> 'number' then return false; end if;
      v_upper := (v_bracket ->> 'upperBoundAmount')::numeric;
      if v_upper <> trunc(v_upper) or v_upper > 9007199254740991 or v_upper <= v_lower then return false; end if;
      v_expected_lower := v_upper;
    end if;
  end loop;
  return true;
exception when others then
  return false;
end $$;

create table public.payroll_tax_policy_versions (
  id bigint generated by default as identity primary key,
  effective_month date not null,
  personal_deduction_amount numeric(16,0) not null,
  dependent_deduction_amount numeric(16,0) not null,
  brackets jsonb not null,
  revision bigint not null,
  created_by bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  note text null,
  constraint payroll_tax_policy_month_check check (effective_month = date_trunc('month', effective_month)::date),
  constraint payroll_tax_policy_personal_deduction_check check (personal_deduction_amount between 0 and 9007199254740991 and personal_deduction_amount = trunc(personal_deduction_amount)),
  constraint payroll_tax_policy_dependent_deduction_check check (dependent_deduction_amount between 0 and 9007199254740991 and dependent_deduction_amount = trunc(dependent_deduction_amount)),
  constraint payroll_tax_policy_brackets_check check (public.payroll_validate_tax_brackets_v1(brackets)),
  constraint payroll_tax_policy_revision_check check (revision >= 1),
  constraint payroll_tax_policy_revision_unique unique (revision)
);

create index payroll_tax_policy_lookup_idx
  on public.payroll_tax_policy_versions(effective_month desc, revision desc);

create table public.payroll_tax_setting_versions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  effective_month date not null,
  tax_mode text not null,
  dependent_count integer not null,
  burden_mode text not null,
  accounting_name text null,
  insurance_deduction_mode text not null,
  manual_insurance_deduction_amount numeric(16,0) not null default 0,
  revision bigint not null,
  created_by bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  note text null,
  constraint payroll_tax_setting_month_check check (effective_month = date_trunc('month', effective_month)::date),
  constraint payroll_tax_setting_mode_check check (tax_mode in ('not_applicable', 'resident_progressive')),
  constraint payroll_tax_setting_dependent_count_check check (dependent_count between 0 and 1000),
  constraint payroll_tax_setting_burden_mode_check check (burden_mode in ('employee_deducted', 'company_bears')),
  constraint payroll_tax_setting_insurance_mode_check check (insurance_deduction_mode in ('payroll', 'manual', 'none')),
  constraint payroll_tax_setting_manual_insurance_check check (
    manual_insurance_deduction_amount between 0 and 9007199254740991
    and manual_insurance_deduction_amount = trunc(manual_insurance_deduction_amount)
    and ((insurance_deduction_mode = 'manual') or manual_insurance_deduction_amount = 0)
  ),
  constraint payroll_tax_setting_manual_note_check check (insurance_deduction_mode <> 'manual' or nullif(btrim(note), '') is not null),
  constraint payroll_tax_setting_not_applicable_shape_check check (
    tax_mode <> 'not_applicable'
    or (dependent_count = 0 and burden_mode = 'employee_deducted' and insurance_deduction_mode = 'none' and manual_insurance_deduction_amount = 0)
  ),
  constraint payroll_tax_setting_revision_check check (revision >= 1),
  constraint payroll_tax_setting_version_unique unique (user_id, revision)
);

create index payroll_tax_setting_lookup_idx
  on public.payroll_tax_setting_versions(user_id, effective_month desc, revision desc);
create index payroll_tax_setting_created_by_idx
  on public.payroll_tax_setting_versions(created_by);

alter table public.payroll_tax_policy_versions enable row level security;
alter table public.payroll_tax_setting_versions enable row level security;
revoke all on table public.payroll_tax_policy_versions, public.payroll_tax_setting_versions from public, anon, authenticated, service_role;
revoke all on sequence public.payroll_tax_policy_versions_id_seq, public.payroll_tax_setting_versions_id_seq from public, anon, authenticated, service_role;
grant select, insert on table public.payroll_tax_policy_versions, public.payroll_tax_setting_versions to service_role;
grant usage, select on sequence public.payroll_tax_policy_versions_id_seq, public.payroll_tax_setting_versions_id_seq to service_role;

create function public.payroll_lock_paid_tax_policy_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog, public
as $$
begin
  perform pg_advisory_xact_lock(82120, extract(year from new.effective_month)::integer * 100 + extract(month from new.effective_month)::integer);
  if exists (
    select 1
    from public.payroll_payment_batches b
    join public.payroll_employee_payments e on e.payroll_batch_id = b.id
    where b.payroll_month >= new.effective_month and e.payment_status = 'paid'
  ) then
    raise exception 'PAYROLL_TAX_POLICY_LOCKED_FOR_PAID_MONTH' using errcode = '55000';
  end if;
  return new;
end $$;

create function public.payroll_lock_paid_tax_setting_v1()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog, public
as $$
begin
  perform pg_advisory_xact_lock(82119, new.user_id::integer);
  if exists (
    select 1
    from public.payroll_payment_batches b
    join public.payroll_employee_payments e on e.payroll_batch_id = b.id
    where b.payroll_month >= new.effective_month
      and e.user_id = new.user_id
      and e.payment_status = 'paid'
  ) then
    raise exception 'PAYROLL_TAX_SETTING_LOCKED_FOR_PAID_EMPLOYEE' using errcode = '55000';
  end if;
  return new;
end $$;

create trigger payroll_tax_policy_paid_lock
before insert or update on public.payroll_tax_policy_versions
for each row execute function public.payroll_lock_paid_tax_policy_v1();

create trigger payroll_tax_setting_paid_lock
before insert or update on public.payroll_tax_setting_versions
for each row execute function public.payroll_lock_paid_tax_setting_v1();

create function public.payroll_create_tax_policy_version_v1(
  p_effective_month date,
  p_personal_deduction_amount bigint,
  p_dependent_deduction_amount bigint,
  p_brackets jsonb,
  p_actor_user_id bigint,
  p_note text
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog, public
as $$
declare
  v_revision bigint;
  v_created public.payroll_tax_policy_versions%rowtype;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);
  if p_effective_month <> date_trunc('month', p_effective_month)::date
    or p_personal_deduction_amount < 0
    or p_dependent_deduction_amount < 0
    or not public.payroll_validate_tax_brackets_v1(p_brackets) then
    raise exception 'PAYROLL_TAX_POLICY_INVALID' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(82120, 1);
  select coalesce(max(revision), 0) + 1 into v_revision from public.payroll_tax_policy_versions;
  insert into public.payroll_tax_policy_versions(
    effective_month, personal_deduction_amount, dependent_deduction_amount,
    brackets, revision, created_by, note
  ) values (
    p_effective_month, p_personal_deduction_amount, p_dependent_deduction_amount,
    p_brackets, v_revision, p_actor_user_id, nullif(btrim(p_note), '')
  ) returning * into v_created;
  return to_jsonb(v_created);
end $$;

create function public.payroll_create_tax_setting_version_v1(
  p_user_id bigint,
  p_effective_month date,
  p_tax_mode text,
  p_dependent_count integer,
  p_burden_mode text,
  p_accounting_name text,
  p_insurance_deduction_mode text,
  p_manual_insurance_deduction_amount bigint,
  p_actor_user_id bigint,
  p_note text
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog, public
as $$
declare
  v_revision bigint;
  v_created public.payroll_tax_setting_versions%rowtype;
begin
  perform public.payroll_assert_actor_v2(p_actor_user_id);
  if p_effective_month <> date_trunc('month', p_effective_month)::date
    or p_tax_mode not in ('not_applicable', 'resident_progressive')
    or p_dependent_count not between 0 and 1000
    or p_burden_mode not in ('employee_deducted', 'company_bears')
    or p_insurance_deduction_mode not in ('payroll', 'manual', 'none')
    or p_manual_insurance_deduction_amount < 0
    or (p_insurance_deduction_mode <> 'manual' and p_manual_insurance_deduction_amount <> 0)
    or (p_insurance_deduction_mode = 'manual' and nullif(btrim(p_note), '') is null)
    or (p_tax_mode = 'resident_progressive' and nullif(btrim(p_accounting_name), '') is null)
    or (p_tax_mode = 'not_applicable' and not (
      p_dependent_count = 0 and p_burden_mode = 'employee_deducted'
      and p_insurance_deduction_mode = 'none' and p_manual_insurance_deduction_amount = 0
    )) then
    raise exception 'PAYROLL_TAX_SETTING_INVALID' using errcode = '22023';
  end if;
  perform 1 from public.users where id = p_user_id and is_system_account = false;
  if not found then raise exception 'PAYROLL_TAX_SETTING_USER_NOT_FOUND' using errcode = 'P0002'; end if;
  perform pg_advisory_xact_lock(82119, p_user_id::integer);
  select coalesce(max(revision), 0) + 1 into v_revision
  from public.payroll_tax_setting_versions where user_id = p_user_id;
  insert into public.payroll_tax_setting_versions(
    user_id, effective_month, tax_mode, dependent_count, burden_mode,
    accounting_name, insurance_deduction_mode, manual_insurance_deduction_amount,
    revision, created_by, note
  ) values (
    p_user_id, p_effective_month, p_tax_mode, p_dependent_count, p_burden_mode,
    nullif(btrim(p_accounting_name), ''), p_insurance_deduction_mode,
    p_manual_insurance_deduction_amount, v_revision, p_actor_user_id, nullif(btrim(p_note), '')
  ) returning * into v_created;
  return to_jsonb(v_created);
end $$;

alter table public.payroll_payment_batches
  add column employee_pit_total bigint not null default 0 check (employee_pit_total >= 0),
  add column company_pit_total bigint not null default 0 check (company_pit_total >= 0),
  add column advance_total bigint not null default 0 check (advance_total >= 0);

create function public.payroll_refresh_payment_tax_totals_v1(p_run_id bigint)
returns void
language plpgsql
security definer
set search_path=pg_catalog, public
as $$
begin
  update public.payroll_payment_batches b set
    employee_pit_total = x.employee_pit,
    company_pit_total = x.company_pit,
    advance_total = x.advance,
    actual_company_cost_total = x.actual + x.employee_insurance + x.employee_pit + x.advance
      + x.employer_insurance + x.company_pit + b.director_insurance_amount,
    updated_at = now()
  from (
    select
      coalesce(sum(actual_paid_amount), 0)::bigint actual,
      coalesce(sum(employee_insurance_amount), 0)::bigint employee_insurance,
      coalesce(sum(employer_insurance_amount), 0)::bigint employer_insurance,
      coalesce(sum((calculation_snapshot #>> '{employee,tax,employeePitDeductionAmount}')::bigint), 0)::bigint employee_pit,
      coalesce(sum((calculation_snapshot #>> '{employee,tax,companyPitAmount}')::bigint), 0)::bigint company_pit,
      coalesce(sum((calculation_snapshot #>> '{employee,amounts,advanceAmount}')::bigint), 0)::bigint advance
    from public.payroll_employee_payments
    where payroll_batch_id = p_run_id and payment_status = 'paid'
  ) x
  where b.id = p_run_id;
end $$;

create function public.payroll_pay_employee_v2(
  p_month date, p_targets jsonb, p_user_id bigint, p_calculation_snapshot jsonb, p_calculation_hash text,
  p_calculated_net_amount bigint, p_actual_paid_amount bigint, p_difference_reason text, p_payment_date date,
  p_actor_user_id bigint, p_engine_version text, p_common_settings_snapshot jsonb, p_director_insurance_amount bigint
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog, public
as $$
declare
  v_result jsonb;
begin
  v_result := public.payroll_pay_employee_v1(
    p_month, p_targets, p_user_id, p_calculation_snapshot, p_calculation_hash,
    p_calculated_net_amount, p_actual_paid_amount, p_difference_reason, p_payment_date,
    p_actor_user_id, p_engine_version, p_common_settings_snapshot, p_director_insurance_amount
  );
  perform public.payroll_refresh_payment_tax_totals_v1((v_result ->> 'runId')::bigint);
  return v_result;
end $$;

create function public.payroll_cancel_employee_payment_v2(
  p_run_id bigint, p_user_id bigint, p_reason text, p_actor_user_id bigint
) returns jsonb
language plpgsql
security definer
set search_path=pg_catalog, public
as $$
declare
  v_result jsonb;
begin
  v_result := public.payroll_cancel_employee_payment_v1(p_run_id, p_user_id, p_reason, p_actor_user_id);
  perform public.payroll_refresh_payment_tax_totals_v1(p_run_id);
  return v_result;
end $$;

revoke all on function public.payroll_validate_tax_brackets_v1(jsonb) from public, anon, authenticated;
grant execute on function public.payroll_validate_tax_brackets_v1(jsonb) to service_role;
revoke all on function public.payroll_lock_paid_tax_policy_v1() from public, anon, authenticated;
revoke all on function public.payroll_lock_paid_tax_setting_v1() from public, anon, authenticated;
revoke all on function public.payroll_create_tax_policy_version_v1(date, bigint, bigint, jsonb, bigint, text) from public, anon, authenticated;
revoke all on function public.payroll_create_tax_setting_version_v1(bigint, date, text, integer, text, text, text, bigint, bigint, text) from public, anon, authenticated;
revoke all on function public.payroll_refresh_payment_tax_totals_v1(bigint) from public, anon, authenticated;
revoke all on function public.payroll_pay_employee_v2(date, jsonb, bigint, jsonb, text, bigint, bigint, text, date, bigint, text, jsonb, bigint) from public, anon, authenticated;
revoke all on function public.payroll_cancel_employee_payment_v2(bigint, bigint, text, bigint) from public, anon, authenticated;

grant execute on function public.payroll_create_tax_policy_version_v1(date, bigint, bigint, jsonb, bigint, text) to service_role;
grant execute on function public.payroll_create_tax_setting_version_v1(bigint, date, text, integer, text, text, text, bigint, bigint, text) to service_role;
grant execute on function public.payroll_pay_employee_v2(date, jsonb, bigint, jsonb, text, bigint, bigint, text, date, bigint, text, jsonb, bigint) to service_role;
grant execute on function public.payroll_cancel_employee_payment_v2(bigint, bigint, text, bigint) to service_role;

alter function public.payroll_validate_tax_brackets_v1(jsonb) owner to postgres;
alter function public.payroll_lock_paid_tax_policy_v1() owner to postgres;
alter function public.payroll_lock_paid_tax_setting_v1() owner to postgres;
alter function public.payroll_create_tax_policy_version_v1(date, bigint, bigint, jsonb, bigint, text) owner to postgres;
alter function public.payroll_create_tax_setting_version_v1(bigint, date, text, integer, text, text, text, bigint, bigint, text) owner to postgres;
alter function public.payroll_refresh_payment_tax_totals_v1(bigint) owner to postgres;
alter function public.payroll_pay_employee_v2(date, jsonb, bigint, jsonb, text, bigint, bigint, text, date, bigint, text, jsonb, bigint) owner to postgres;
alter function public.payroll_cancel_employee_payment_v2(bigint, bigint, text, bigint) owner to postgres;

comment on table public.payroll_tax_policy_versions is 'Append-only PIT policy versions. Production policy values are registered separately.';
comment on table public.payroll_tax_setting_versions is 'Append-only employee PIT profiles keyed by payroll user_id; accounting_name is display/audit metadata only.';

commit;
