export const adminUsersText = {
  ko: {
    sectionTitle: "직원관리",
    listTab: "직원 현황",
    summaryLabel: "직원 현황",
    createTab: "직원 생성",
    description: "직원 계정, 권한, 파트, 직급, 근무시간을 관리합니다.",
    createDescription: "새 직원 계정을 생성하고 기본 근무 정보를 설정합니다.",
    noPermission: "직원관리는 owner/master만 접근할 수 있습니다.",
    loading: "직원 목록을 불러오는 중...",
    loadFailed: "직원 목록을 불러오지 못했습니다.",
    saveFailed: "직원 정보를 저장하지 못했습니다.",
    saveSuccess: "저장되었습니다.",
    createFailed: "직원 계정을 생성하지 못했습니다.",
    createSuccess: "생성 완료",
    empty: "등록된 직원이 없습니다.",
    active: "활성",
    inactive: "비활성",
    edit: "수정",
    cancel: "취소",
    save: "저장",
    saving: "저장 중...",
    create: "생성하기",
    creating: "생성 중...",
    name: "이름",
    fullName: "전체 이름",
    username: "로그인 ID",
    password: "비밀번호",
    role: "직급",
    roleFieldHelp: "직급에 따라 앱의 접근 권한과 관리 기능이 결정됩니다.",
    part: "파트",
    position: "직급",
    gender: "성별",
    birthDate: "생년월일",
    hireDate: "입사일",
    terminationDate: "퇴사일",
    terminationDeactivationNotice: "퇴사일을 저장하면 계정 사용도 중지됩니다.",
    payrollEligibleOverride: "급여 대상에 포함",
    payrollEligibleOverrideHelp: "사장은 기본적으로 급여 대상에서 제외됩니다. 급여를 받는 경우에만 선택하세요.",
    peopleUnit: "명",
    terminatedOn: "퇴사",
    rehire: "복귀 처리",
    rehireDate: "복귀일",
    rehireWarning: "복귀 처리 전에 이전 근무분의 근태 확인과 급여 지급을 완료해주세요. 복귀 처리하면 입사일이 복귀일로 변경되고 이전 입사일과 퇴사일은 직원 기본정보에서 유지되지 않습니다.",
    workStartTime: "출근 시간",
    workEndTime: "퇴근 시간",
    activeStatus: "계정 사용 가능",
    workTime: "근무시간",
    cannotEdit: "수정 불가",
    masterEditBlocked: "마스터 계정은 수정할 수 없습니다.",
    ownerGroup: "사장",
    adminGroup: "사장",
    kitchenGroup: "주방",
    hallGroup: "홀",
    barGroup: "바",
    cleaningGroup: "청소",
    etcGroup: "기타",
    managerRole: "매니저",
    leaderRole: "리더",
    staffRole: "직원",
    inactiveGroup: "비활성",
    attendanceTracking: "근태 기록 사용",
    attendanceTrackingHelp: "출퇴근 및 근태현황에 포함합니다.",
    attendanceTrackingEnabled: "사용",
    attendanceTrackingDisabled: "미사용",
    appLoginEnabled: "앱 로그인 사용",
    appLoginEnabledHelp: "로그인 미사용이어도 아이디·비밀번호는 등록해야 합니다.",
    appLoginEnabledOn: "사용",
    appLoginEnabledOff: "미사용",
    workTimeRequiredForTracking: "근태 사용 직원은 출근 시간과 퇴근 시간을 입력해야 합니다.",
    attendanceTrackingOpenRecordNotice: "퇴근되지 않은 기록이 있으면 근태 사용을 해제할 수 없습니다.",
    noUsers: "직원 없음",
    required: "로그인 ID, 비밀번호, 이름은 필수입니다.",
    duplicateUsername: "이미 사용 중인 로그인 ID입니다.",
    basicInfo: "기본 정보",
    accessInfo: "권한/소속",
    workInfo: "근무 정보",
    preview: "미리보기",
    employeeLevel: "직원 레벨",
    levelProgramInclude: "레벨 대상에 포함",
    levelProgramIncludeHelp: "사장·마스터 계정은 선택한 경우에만 직원 레벨을 계산합니다.",
    levelUnset: "레벨 미설정",
    longTermLevel: "장기근무 레벨",
    levelEnabled: "적용",
    levelDisabled: "미적용",
    levelPolicyHelp: "9시간 풀타임 직원에게 적용합니다. 파트타임 직원은 미적용으로 설정해주세요.",
    levelEffectiveMonth: "적용 월",
    levelCalculationBasis: "레벨 계산 기준",
    levelHireDateMode: "입사일 기준",
    levelOverrideMode: "직접 기준",
    levelCalculationStartDate: "기준일",
    thisMonth: "이번 달부터",
    nextMonth: "다음 달부터",
    shortShiftNotice: "현재 설정된 근무시간은 약 {hours}시간입니다. 파트타임 직원이라면 레벨 미적용을 권장합니다. (설정된 시간 구간 기준)",
    levelProgramDisabled: "레벨 미적용",
    levelBaseRequired: "레벨 설정 필요",
    levelRoleNotEligible: "레벨 정책 대상 아님",
    levelBeforeBaseDate: "레벨 적용 시작 전",
    levelInvalidDate: "레벨 날짜 확인 필요",
    hireDateBase: "입사일 기준",
    directBase: "직접 설정",
    directBaseShort: "직접 기준",
    levelBaseDate: "레벨 기준일",
    currentLevel: "현재 레벨",
    cumulativeRaise: "누적 인상",
    nextLevel: "다음 레벨",
    nextLevelShort: "다음",
    highestLevel: "최고 레벨",
    negotiationEligible: "급여 협상 가능",
    negotiationEligibleAt: "급여 협상 가능일",
    terminatedLevelReadOnly: "퇴사자의 레벨 설정은 조회만 가능합니다.",
  },
  vi: {
    sectionTitle: "Quản lý nhân viên",
    listTab: "Danh sách nhân viên",
    summaryLabel: "Tình hình nhân viên",
    createTab: "Tạo nhân viên",
    description: "Quản lý tài khoản, quyền, bộ phận, chức vụ và giờ làm.",
    createDescription: "Tạo tài khoản nhân viên mới và thiết lập thông tin làm việc.",
    noPermission: "Chỉ owner/master mới có quyền quản lý nhân viên.",
    loading: "Đang tải danh sách nhân viên...",
    loadFailed: "Không thể tải danh sách nhân viên.",
    saveFailed: "Không thể lưu thông tin nhân viên.",
    saveSuccess: "Đã lưu.",
    createFailed: "Không thể tạo tài khoản nhân viên.",
    createSuccess: "Đã tạo nhân viên.",
    empty: "Chưa có nhân viên.",
    active: "Đang hoạt động",
    inactive: "Ngừng hoạt động",
    edit: "Sửa",
    cancel: "Hủy",
    save: "Lưu",
    saving: "Đang lưu...",
    create: "Tạo nhân viên",
    creating: "Đang tạo...",
    name: "Tên",
    fullName: "Họ tên đầy đủ",
    username: "ID đăng nhập",
    password: "Mật khẩu",
    role: "Chức vụ",
    roleFieldHelp: "Chức vụ quyết định quyền truy cập và chức năng quản lý trong ứng dụng.",
    part: "Bộ phận",
    position: "Chức vụ",
    gender: "Giới tính",
    birthDate: "Ngày sinh",
    hireDate: "Ngày vào làm",
    terminationDate: "Ngày nghỉ việc",
    terminationDeactivationNotice: "Khi lưu ngày nghỉ việc, tài khoản cũng sẽ bị vô hiệu hóa.",
    payrollEligibleOverride: "Bao gồm trong bảng lương",
    payrollEligibleOverrideHelp: "Chủ cửa hàng mặc định không thuộc đối tượng trả lương. Chỉ chọn khi người này nhận lương.",
    peopleUnit: " người",
    terminatedOn: "Nghỉ việc",
    rehire: "Cho làm lại",
    rehireDate: "Ngày làm lại",
    rehireWarning: "Trước khi cho làm lại, vui lòng hoàn tất việc kiểm tra chấm công và trả lương cho thời gian làm việc trước. Ngày vào làm sẽ được đổi thành ngày làm lại; ngày vào làm và ngày nghỉ việc trước đó sẽ không còn được lưu trong thông tin cơ bản.",
    workStartTime: "Giờ vào",
    workEndTime: "Giờ ra",
    activeStatus: "Cho phép sử dụng tài khoản",
    workTime: "Giờ làm",
    cannotEdit: "Không thể chỉnh sửa",
    masterEditBlocked: "Không thể chỉnh sửa tài khoản master.",
    ownerGroup: "Chủ",
    adminGroup: "Chủ",
    kitchenGroup: "Bếp",
    hallGroup: "Sảnh",
    barGroup: "Bar",
    cleaningGroup: "Vệ sinh",
    etcGroup: "Khác",
    managerRole: "Quản lý",
    leaderRole: "Trưởng nhóm",
    staffRole: "Nhân viên",
    inactiveGroup: "Không hoạt động",
    attendanceTracking: "Sử dụng chấm công",
    attendanceTrackingHelp: "Nhân viên này sẽ được tính vào chấm công và bảng theo dõi giờ làm.",
    attendanceTrackingEnabled: "Sử dụng",
    attendanceTrackingDisabled: "Không sử dụng",
    appLoginEnabled: "Cho phép đăng nhập ứng dụng",
    appLoginEnabledHelp: "Ngay cả khi không dùng đăng nhập, vẫn cần đăng ký ID và mật khẩu.",
    appLoginEnabledOn: "Sử dụng",
    appLoginEnabledOff: "Không sử dụng",
    workTimeRequiredForTracking: "Nhân viên sử dụng chấm công phải nhập giờ vào và giờ ra.",
    attendanceTrackingOpenRecordNotice: "Không thể tắt chấm công khi vẫn còn bản ghi chưa chấm công ra.",
    noUsers: "Không có nhân viên",
    required: "ID đăng nhập, mật khẩu và tên là bắt buộc.",
    duplicateUsername: "ID đăng nhập đã được sử dụng.",
    basicInfo: "Thông tin cơ bản",
    accessInfo: "Quyền & bộ phận",
    workInfo: "Thông tin làm việc",
    preview: "Xem trước",
    employeeLevel: "Cấp nhân viên",
    levelProgramInclude: "Bao gồm trong cấp nhân viên",
    levelProgramIncludeHelp: "Tài khoản chủ và master chỉ được tính cấp khi tùy chọn này được bật.",
    levelUnset: "Chưa thiết lập cấp",
    longTermLevel: "Cấp làm việc lâu dài",
    levelEnabled: "Áp dụng",
    levelDisabled: "Không áp dụng",
    levelPolicyHelp: "Áp dụng cho nhân viên toàn thời gian 9 giờ. Vui lòng chọn không áp dụng cho nhân viên bán thời gian.",
    levelEffectiveMonth: "Tháng áp dụng",
    levelCalculationBasis: "Mốc tính cấp",
    levelHireDateMode: "Theo ngày vào làm",
    levelOverrideMode: "Ngày chỉ định",
    levelCalculationStartDate: "Ngày bắt đầu tính",
    thisMonth: "Từ tháng này",
    nextMonth: "Từ tháng sau",
    shortShiftNotice: "Thời gian làm việc hiện tại khoảng {hours} giờ. Nếu là nhân viên bán thời gian, nên chọn không áp dụng cấp. (Dựa trên khung giờ đã thiết lập)",
    levelProgramDisabled: "Không áp dụng cấp",
    levelBaseRequired: "Cần thiết lập cấp",
    levelRoleNotEligible: "Không thuộc đối tượng áp dụng cấp",
    levelBeforeBaseDate: "Chưa đến ngày bắt đầu áp dụng cấp",
    levelInvalidDate: "Cần kiểm tra ngày tính cấp",
    hireDateBase: "Theo ngày vào làm",
    directBase: "Ngày thiết lập riêng",
    directBaseShort: "Mốc trực tiếp",
    levelBaseDate: "Ngày bắt đầu tính cấp",
    currentLevel: "Cấp hiện tại",
    cumulativeRaise: "Tổng mức tăng",
    nextLevel: "Cấp tiếp theo",
    nextLevelShort: "Tiếp theo",
    highestLevel: "Cấp cao nhất",
    negotiationEligible: "Có thể thương lượng lương",
    negotiationEligibleAt: "Ngày có thể thương lượng lương",
    terminatedLevelReadOnly: "Thiết lập cấp của nhân viên đã nghỉ việc chỉ có thể xem.",
  },
} as const;
