export const adminUsersText = {
  ko: {
    sectionTitle: "직원관리",
    listTab: "직원 현황",
    summaryLabel: "직원 현황",
    createTab: "직원 생성",
    description: "직원 계정, 권한, 파트, 직급, 근무시간을 관리합니다.",
    createDescription: "새 직원 계정을 생성하고 기본 근무 정보를 설정합니다.",
    noPermission: "직원관리는 owner/master만 접근할 수 있습니다.",
    loading: "직원 목록을 불러오는 중...",
    loadFailed: "직원 목록을 불러오지 못했습니다.",
    saveFailed: "직원 정보를 저장하지 못했습니다.",
    saveSuccess: "저장되었습니다.",
    createFailed: "직원 계정을 생성하지 못했습니다.",
    createSuccess: "생성 완료",
    empty: "등록된 직원이 없습니다.",
    active: "활성",
    inactive: "비활성",
    edit: "수정",
    cancel: "취소",
    save: "저장",
    saving: "저장 중...",
    create: "생성하기",
    creating: "생성 중...",
    name: "이름",
    fullName: "전체 이름",
    username: "로그인 ID",
    password: "비밀번호",
    role: "권한",
    part: "파트",
    position: "직급",
    gender: "성별",
    birthDate: "생년월일",
    hireDate: "입사일",
    terminationDate: "퇴사일",
    terminationDeactivationNotice: "퇴사일을 저장하면 계정 사용도 중지됩니다.",
    payrollEligibleOverride: "급여 대상에 포함",
    payrollEligibleOverrideHelp: "사장은 기본적으로 급여 대상에서 제외됩니다. 급여를 받는 경우에만 선택하세요.",
    peopleUnit: "명",
    terminatedOn: "퇴사",
    rehire: "복귀 처리",
    rehireDate: "복귀일",
    rehireWarning: "복귀 처리 전에 이전 근무분의 근태 확인과 급여 지급을 완료해주세요. 복귀 처리하면 입사일이 복귀일로 변경되고 이전 입사일과 퇴사일은 직원 기본정보에서 유지되지 않습니다.",
    workStartTime: "출근 시간",
    workEndTime: "퇴근 시간",
    activeStatus: "계정 사용 가능",
    workTime: "근무시간",
    cannotEdit: "수정 불가",
    masterEditBlocked: "마스터 계정은 수정할 수 없습니다.",
    ownerGroup: "사장",
    adminGroup: "사장",
    kitchenGroup: "주방",
    hallGroup: "홀",
    barGroup: "바",
    managerRole: "매니저",
    leaderRole: "리더",
    staffRole: "직원",
    inactiveGroup: "비활성",
    noUsers: "직원 없음",
    required: "로그인 ID, 비밀번호, 이름은 필수입니다.",
    duplicateUsername: "이미 사용 중인 로그인 ID입니다.",
    basicInfo: "기본 정보",
    accessInfo: "권한/소속",
    workInfo: "근무 정보",
    preview: "미리보기",
  },
  vi: {
    sectionTitle: "Quản lý nhân viên",
    listTab: "Danh sách nhân viên",
    summaryLabel: "Tình hình nhân viên",
    createTab: "Tạo nhân viên",
    description: "Quản lý tài khoản, quyền, bộ phận, chức vụ và giờ làm.",
    createDescription: "Tạo tài khoản nhân viên mới và thiết lập thông tin làm việc.",
    noPermission: "Chỉ owner/master mới có quyền quản lý nhân viên.",
    loading: "Đang tải danh sách nhân viên...",
    loadFailed: "Không thể tải danh sách nhân viên.",
    saveFailed: "Không thể lưu thông tin nhân viên.",
    saveSuccess: "Đã lưu.",
    createFailed: "Không thể tạo tài khoản nhân viên.",
    createSuccess: "Đã tạo nhân viên.",
    empty: "Chưa có nhân viên.",
    active: "Đang hoạt động",
    inactive: "Ngừng hoạt động",
    edit: "Sửa",
    cancel: "Hủy",
    save: "Lưu",
    saving: "Đang lưu...",
    create: "Tạo nhân viên",
    creating: "Đang tạo...",
    name: "Tên",
    fullName: "Họ tên đầy đủ",
    username: "ID đăng nhập",
    password: "Mật khẩu",
    role: "Quyền",
    part: "Bộ phận",
    position: "Chức vụ",
    gender: "Giới tính",
    birthDate: "Ngày sinh",
    hireDate: "Ngày vào làm",
    terminationDate: "Ngày nghỉ việc",
    terminationDeactivationNotice: "Khi lưu ngày nghỉ việc, tài khoản cũng sẽ bị vô hiệu hóa.",
    payrollEligibleOverride: "Bao gồm trong bảng lương",
    payrollEligibleOverrideHelp: "Chủ cửa hàng mặc định không thuộc đối tượng trả lương. Chỉ chọn khi người này nhận lương.",
    peopleUnit: " người",
    terminatedOn: "Nghỉ việc",
    rehire: "Cho làm lại",
    rehireDate: "Ngày làm lại",
    rehireWarning: "Trước khi cho làm lại, vui lòng hoàn tất việc kiểm tra chấm công và trả lương cho thời gian làm việc trước. Ngày vào làm sẽ được đổi thành ngày làm lại; ngày vào làm và ngày nghỉ việc trước đó sẽ không còn được lưu trong thông tin cơ bản.",
    workStartTime: "Giờ vào",
    workEndTime: "Giờ ra",
    activeStatus: "Cho phép sử dụng tài khoản",
    workTime: "Giờ làm",
    cannotEdit: "Không thể chỉnh sửa",
    masterEditBlocked: "Không thể chỉnh sửa tài khoản master.",
    ownerGroup: "Chủ",
    adminGroup: "Chủ",
    kitchenGroup: "Bếp",
    hallGroup: "Sảnh",
    barGroup: "Bar",
    managerRole: "Quản lý",
    leaderRole: "Trưởng nhóm",
    staffRole: "Nhân viên",
    inactiveGroup: "Không hoạt động",
    noUsers: "Không có nhân viên",
    required: "ID đăng nhập, mật khẩu và tên là bắt buộc.",
    duplicateUsername: "ID đăng nhập đã được sử dụng.",
    basicInfo: "Thông tin cơ bản",
    accessInfo: "Quyền & bộ phận",
    workInfo: "Thông tin làm việc",
    preview: "Xem trước",
  },
} as const;
