export const adminUsersText = {
  ko: {
    sectionTitle: "직원관리",
    listTab: "직원 현황",
    createTab: "직원 생성",
    description: "직원 계정, 권한, 파트, 직급, 근무시간을 관리합니다.",
    createDescription: "새 직원 계정을 생성하고 기본 근무 정보를 설정합니다.",
    noPermission: "직원관리는 owner/master만 접근할 수 있습니다.",
    loading: "직원 목록을 불러오는 중...",
    loadFailed: "직원 목록을 불러오지 못했습니다.",
    saveFailed: "직원 정보를 저장하지 못했습니다.",
    saveSuccess: "저장되었습니다.",
    createFailed: "직원 계정을 생성하지 못했습니다.",
    createSuccess: "생성 완료",
    empty: "등록된 직원이 없습니다.",
    active: "활성",
    inactive: "비활성",
    edit: "수정",
    cancel: "취소",
    save: "저장",
    saving: "저장 중...",
    create: "생성하기",
    creating: "생성 중...",
    name: "이름",
    fullName: "전체 이름",
    username: "로그인 ID",
    password: "비밀번호",
    role: "권한",
    part: "파트",
    position: "직급",
    gender: "성별",
    birthDate: "생년월일",
    hireDate: "입사일",
    workStartTime: "출근 시간",
    workEndTime: "퇴근 시간",
    activeStatus: "활성 상태",
    workTime: "근무시간",
    cannotEdit: "수정 불가",
    masterEditBlocked: "마스터 계정은 수정할 수 없습니다.",
    ownerGroup: "사장",
    adminGroup: "사장",
    kitchenGroup: "주방",
    hallGroup: "홀",
    barGroup: "바",
    managerRole: "매니저",
    leaderRole: "리더",
    staffRole: "직원",
    inactiveGroup: "비활성",
    noUsers: "직원 없음",
    required: "로그인 ID, 비밀번호, 이름은 필수입니다.",
    duplicateUsername: "이미 사용 중인 로그인 ID입니다.",
    basicInfo: "기본 정보",
    accessInfo: "권한/소속",
    workInfo: "근무 정보",
    preview: "미리보기",
  },
  vi: {
    sectionTitle: "Quản lý nhân viên",
    listTab: "Danh sách nhân viên",
    createTab: "Tạo nhân viên",
    description: "Quản lý tài khoản, quyền, bộ phận, chức vụ và giờ làm.",
    createDescription: "Tạo tài khoản nhân viên mới và thiết lập thông tin làm việc.",
    noPermission: "Chỉ owner/master mới có quyền quản lý nhân viên.",
    loading: "Đang tải danh sách nhân viên...",
    loadFailed: "Không thể tải danh sách nhân viên.",
    saveFailed: "Không thể lưu thông tin nhân viên.",
    saveSuccess: "Đã lưu.",
    createFailed: "Không thể tạo tài khoản nhân viên.",
    createSuccess: "Đã tạo nhân viên.",
    empty: "Chưa có nhân viên.",
    active: "Đang hoạt động",
    inactive: "Ngừng hoạt động",
    edit: "Sửa",
    cancel: "Hủy",
    save: "Lưu",
    saving: "Đang lưu...",
    create: "Tạo nhân viên",
    creating: "Đang tạo...",
    name: "Tên",
    fullName: "Họ tên đầy đủ",
    username: "ID đăng nhập",
    password: "Mật khẩu",
    role: "Quyền",
    part: "Bộ phận",
    position: "Chức vụ",
    gender: "Giới tính",
    birthDate: "Ngày sinh",
    hireDate: "Ngày vào làm",
    workStartTime: "Giờ vào",
    workEndTime: "Giờ ra",
    activeStatus: "Trạng thái hoạt động",
    workTime: "Giờ làm",
    cannotEdit: "Không thể chỉnh sửa",
    masterEditBlocked: "Không thể chỉnh sửa tài khoản master.",
    ownerGroup: "Chủ",
    adminGroup: "Chủ",
    kitchenGroup: "Bếp",
    hallGroup: "Sảnh",
    barGroup: "Bar",
    managerRole: "Quản lý",
    leaderRole: "Trưởng nhóm",
    staffRole: "Nhân viên",
    inactiveGroup: "Không hoạt động",
    noUsers: "Không có nhân viên",
    required: "ID đăng nhập, mật khẩu và tên là bắt buộc.",
    duplicateUsername: "ID đăng nhập đã được sử dụng.",
    basicInfo: "Thông tin cơ bản",
    accessInfo: "Quyền & bộ phận",
    workInfo: "Thông tin làm việc",
    preview: "Xem trước",
  },
} as const;
