export const attendanceStaffText = {
  ko: {
    loading: "불러오는 중...",
    empty: "직원이 없습니다.",
    statusNotChecked: "출근전",
    statusWorking: "근무중",
    statusDone: "퇴근",
    statusEarlyLeave: "조퇴",
    statusLeave: "휴무",
    checkIn: "출근",
    checkOut: "퇴근",
    updateCheckIn: "출근 수정",
    updateCheckOut: "퇴근 수정",
    workTime: "근무",
    late: "지각",
    earlyLeave: "조퇴",
    minute: "분",

    resetDevice: "기기초기화",
    checkInProcess: "출근 처리",
    checkOutProcess: "퇴근 처리",
    standardCheckIn: "정시 출근",
    standardCheckOut: "정시 퇴근",
    manualInput: "직접 입력",
    cancel: "취소",
    submit: "처리",

    noPermission: "권한이 없습니다.",
    inputTimeRequired: "시간을 입력해주세요.",
    checkInUpdateFailed: "출근 시간 수정 실패",
    checkOutUpdateFailed: "퇴근 시간 수정 실패",
    checkInUpdated: "출근 시간이 수정되었습니다.",
    checkOutUpdated: "퇴근 시간이 수정되었습니다.",
    checkInRequiredFirst: "출근 시간이 먼저 있어야 퇴근 시간을 설정할 수 있습니다.",
    resetDeviceConfirm: "기기를 초기화하시겠습니까?",
    resetDeviceFailed: "기기 초기화 실패",
    resetDeviceDone: "기기 초기화 완료",
    confirmSetLeave: "휴무 처리하시겠습니까?",
    setLeaveFailed: "휴무 처리 실패",
    setLeaveDone: "휴무 처리 완료",

    parts: {
      kitchen: "주방",
      hall: "홀",
      bar: "바",
    },

    positions: {
      staff: "직원",
      team_leader: "파트장",
      manager: "매니저",
    },
  },
  vi: {
    loading: "Đang tải...",
    empty: "Không có nhân viên.",
    statusNotChecked: "Chưa vào",
    statusWorking: "Đang làm",
    statusDone: "Đã về",
    statusEarlyLeave: "Về sớm",
    statusLeave: "Nghỉ",
    checkIn: "Vào",
    checkOut: "Về",
    updateCheckIn: "Sửa giờ vào",
    updateCheckOut: "Sửa giờ ra",
    workTime: "Làm",
    late: "Trễ",
    earlyLeave: "Về sớm",
    minute: "p",

    resetDevice: "Đặt lại máy",
    checkInProcess: "Xử lý vào ca",
    checkOutProcess: "Xử lý ra ca",
    standardCheckIn: "Vào đúng giờ",
    standardCheckOut: "Ra đúng giờ",
    manualInput: "Nhập thủ công",
    cancel: "Hủy",
    submit: "Xử lý",

    noPermission: "Bạn không có quyền.",
    inputTimeRequired: "Vui lòng nhập thời gian.",
    checkInUpdateFailed: "Cập nhật giờ vào thất bại",
    checkOutUpdateFailed: "Cập nhật giờ ra thất bại",
    checkInUpdated: "Đã cập nhật giờ vào.",
    checkOutUpdated: "Đã cập nhật giờ ra.",
    checkInRequiredFirst: "Cần có giờ vào trước khi đặt giờ ra.",
    resetDeviceConfirm: "Bạn có muốn đặt lại thiết bị không?",
    resetDeviceFailed: "Đặt lại thiết bị thất bại",
    resetDeviceDone: "Đã đặt lại thiết bị",
    confirmSetLeave: "Bạn có muốn chuyển sang nghỉ không?",
    setLeaveFailed: "Xử lý nghỉ thất bại",
    setLeaveDone: "Đã chuyển sang nghỉ",
    parts: {
      kitchen: "Bếp",
      hall: "Phục vụ",
      bar: "Bar",
    },

    positions: {
      staff: "Nhân viên",
      team_leader: "Trưởng bộ phận",
      manager: "Quản lý",
    },

  },
};