export const attendanceStaffText = {
  ko: {
    loading: "불러오는 중...",
    empty: "직원이 없습니다.",
    statusNotChecked: "출근전",
    statusWorking: "근무중",
    statusDone: "퇴근",
    statusEarlyLeave: "조퇴",
    statusLeave: "휴무",
    checkIn: "출근",
    checkOut: "퇴근",
    workTime: "근무",
    late: "지각",
    earlyLeave: "조퇴",
    minute: "분",
  },
  vi: {
    loading: "Đang tải...",
    empty: "Không có nhân viên.",
    statusNotChecked: "Chưa vào",
    statusWorking: "Đang làm",
    statusDone: "Đã về",
    statusEarlyLeave: "Về sớm",
    statusLeave: "Nghỉ",
    checkIn: "Vào",
    checkOut: "Về",
    workTime: "Làm",
    late: "Trễ",
    earlyLeave: "Về sớm",
    minute: "p",
  },
};