export const keepingNewText = {
  ko: {
    back: "← 키핑 목록",
    searchPlaceholder: "고객명·고객 특징·주류명 검색",
    customerFeature: "고객 특징",
    customerFeaturePlaceholder: "예: 안경, 1234, 생일 손님",
    customerNamePlaceholder: "고객명 입력",
    liquorSource: "주류 구분",
    soldProduct: "판매상품",
    outsideBottle: "외부반입",
    productPlaceholder: "BAR 판매상품 검색",
    outsidePlaceholder: "예: Macallan 18",
    searching: "상품을 찾는 중…",
    noProducts: "일치하는 BAR 판매상품이 없습니다.",
    selectProduct: "목록에서 판매상품을 선택해 주세요.",
    productSearchError: "판매상품을 불러오지 못했습니다.",
    upper: "상단",
    middle: "중단",
    lower: "하단",
    directPercent: "직접 입력",
  },
  vi: {
    back: "← Danh sách ký gửi",
    searchPlaceholder: "Tìm khách, đặc điểm hoặc tên rượu",
    customerFeature: "Dấu hiệu nhận biết",
    customerFeaturePlaceholder: "VD: đeo kính, 1234, khách sinh nhật",
    customerNamePlaceholder: "Nhập tên khách",
    liquorSource: "Loại rượu",
    soldProduct: "Hàng của quán",
    outsideBottle: "Mang từ ngoài",
    productPlaceholder: "Tìm mặt hàng BAR",
    outsidePlaceholder: "VD: Chivas Regal 18",
    searching: "Đang tìm sản phẩm…",
    noProducts: "Không có mặt hàng BAR phù hợp.",
    selectProduct: "Vui lòng chọn sản phẩm trong danh sách.",
    productSearchError: "Không tải được danh sách sản phẩm.",
    upper: "Trên",
    middle: "Giữa",
    lower: "Dưới",
    directPercent: "Nhập trực tiếp",
  },
} as const;
