export const barText = {
  ko: {
    selectZone: "구조도에서 구역을 선택해 주세요.", enlargeMap: "확대해서 구역 선택", selectedZone: "선택한 구역",
    upper: "상단", middle: "중단", lower: "하단", leftShort: "좌", rightShort: "우", unavailable: "없음",
    equipmentShort: "가습기", mapAriaLabel: "BAR 정면도 구역 선택", keepingUnavailable: "키핑 보관 불가 구역", close: "닫기",
    editZone: "구역 수정", photo: "구역 사진", note: "비고", noteKo: "한국어 비고", noteVi: "베트남어 비고", assignee: "담당자", photoUpdated: "사진 업데이트",
    assigneeColor: "담당자 색상", noAssignee: "담당자 없음", inactiveEmployee: "비활성 직원", noZoneInfo: "등록된 구역 정보가 없습니다.",
    save: "저장", saving: "저장 중…", cancel: "취소", replacePhoto: "사진 선택/교체", takePhoto: "카메라 촬영", deletePhoto: "사진 삭제",
    confirmDeletePhoto: "구역 사진을 삭제하시겠습니까?", sessionExpired: "보안을 위해 다시 로그인해 주세요.", conflict: "다른 사용자가 먼저 수정했습니다. 최신 정보를 다시 불러옵니다.",
    loadError: "BAR 정보를 불러오지 못했습니다.", saveError: "저장하지 못했습니다.", photoError: "사진을 처리하지 못했습니다.", unsupportedPhoto: "이 기기에서 지원하지 않는 사진 형식입니다. JPEG, PNG 또는 WebP 사진을 선택해 주세요.",
    keepingTitle: "키핑", keepingDescription: "고객별 키핑 주류를 관리하는 화면입니다.", keepingPreparing: "키핑 관리 기능 준비 중",
    logsTitle: "로그", logsDescription: "BAR 구역 변경 이력입니다.", logsEmpty: "BAR 활동 로그가 없습니다.", logsLoadError: "로그를 불러오지 못했습니다.", loadMore: "더보기",
    recentLogs: "최근 기록", recentLogsEmpty: "이 구역의 기록이 없습니다.", recentLogsLoading: "기록을 불러오는 중…", recentLogsError: "최근 기록을 불러오지 못했습니다.", retry: "다시 시도", viewAllLogs: "전체 기록 보기", allBarLogs: "전체 BAR 기록 보기", zoneLogsSuffix: "구역 기록",
  },
  vi: {
    selectZone: "Vui lòng chọn một khu vực trên sơ đồ.", enlargeMap: "Phóng to để chọn khu vực", selectedZone: "Khu vực đã chọn",
    upper: "Trên", middle: "Giữa", lower: "Dưới", leftShort: "T", rightShort: "P", unavailable: "Không có",
    equipmentShort: "Máy ẩm", mapAriaLabel: "Chọn khu vực trên mặt trước BAR", keepingUnavailable: "Không được lưu rượu tại khu vực này", close: "Đóng",
    editZone: "Sửa khu vực", photo: "Ảnh khu vực", note: "Ghi chú", noteKo: "Ghi chú tiếng Hàn", noteVi: "Ghi chú tiếng Việt", assignee: "Người phụ trách", photoUpdated: "Cập nhật ảnh",
    assigneeColor: "Màu người phụ trách", noAssignee: "Chưa có người phụ trách", inactiveEmployee: "Nhân viên không hoạt động", noZoneInfo: "Chưa có thông tin khu vực.",
    save: "Lưu", saving: "Đang lưu…", cancel: "Hủy", replacePhoto: "Chọn/thay ảnh", takePhoto: "Chụp ảnh", deletePhoto: "Xóa ảnh",
    confirmDeletePhoto: "Bạn có muốn xóa ảnh khu vực không?", sessionExpired: "Vui lòng đăng nhập lại để bảo mật.", conflict: "Người khác đã cập nhật trước. Đang tải dữ liệu mới nhất.",
    loadError: "Không thể tải thông tin BAR.", saveError: "Không thể lưu.", photoError: "Không thể xử lý ảnh.", unsupportedPhoto: "Thiết bị này không hỗ trợ định dạng ảnh. Vui lòng chọn ảnh JPEG, PNG hoặc WebP.",
    keepingTitle: "Giữ rượu", keepingDescription: "Màn hình quản lý rượu giữ theo khách hàng.", keepingPreparing: "Tính năng quản lý giữ rượu đang được chuẩn bị",
    logsTitle: "Nhật ký", logsDescription: "Lịch sử thay đổi khu vực BAR.", logsEmpty: "Chưa có nhật ký hoạt động BAR.", logsLoadError: "Không thể tải nhật ký.", loadMore: "Xem thêm",
    recentLogs: "Nhật ký gần đây", recentLogsEmpty: "Chưa có nhật ký cho khu vực này.", recentLogsLoading: "Đang tải nhật ký…", recentLogsError: "Không thể tải nhật ký gần đây.", retry: "Thử lại", viewAllLogs: "Xem toàn bộ nhật ký", allBarLogs: "Xem toàn bộ nhật ký BAR", zoneLogsSuffix: "Nhật ký khu vực",
  },
} as const;
