export const barText = {
  ko: {
    areaTitle: "BAR 구역 구조도",
    areaDescription: "구조도에서 개별 구역을 선택해 위치 정보를 확인하세요.",
    selectZone: "구조도에서 구역을 선택해 주세요.",
    enlargeMap: "확대해서 구역 선택",
    selectedZone: "선택한 구역",
    upper: "상단",
    middle: "중단",
    lower: "하단",
    leftShort: "좌",
    rightShort: "우",
    unavailable: "없음",
    posDirection: "POS 방향",
    equipmentDirection: "우측 장비 방향",
    equipmentShort: "가습기",
    mapAriaLabel: "BAR 정면도 구역 선택",
    zoneCode: "코드",
    keepingUnavailable: "키핑 보관 불가 구역",
    noPhoto: "등록된 구역 사진이 없습니다.",
    noItems: "주요 물품 정보가 없습니다.",
    futureManagement: "구역 사진 및 물품 관리는 다음 단계에서 지원됩니다.",
    close: "닫기",
    keepingTitle: "키핑",
    keepingDescription: "고객별 키핑 주류를 관리하는 화면입니다.",
    keepingPreparing: "키핑 관리 기능 준비 중",
    logsTitle: "로그",
    logsDescription: "BAR 기능의 변경 및 처리 이력을 확인하는 화면입니다.",
    logsPreparing: "BAR 활동 로그 준비 중",
  },
  vi: {
    areaTitle: "Sơ đồ khu vực BAR",
    areaDescription: "Chọn từng khu vực trên sơ đồ để xem thông tin vị trí.",
    selectZone: "Vui lòng chọn một khu vực trên sơ đồ.",
    enlargeMap: "Phóng to để chọn khu vực",
    selectedZone: "Khu vực đã chọn",
    upper: "Trên",
    middle: "Giữa",
    lower: "Dưới",
    leftShort: "T",
    rightShort: "P",
    unavailable: "Không có",
    posDirection: "Phía POS",
    equipmentDirection: "Phía thiết bị bên phải",
    equipmentShort: "Máy ẩm",
    mapAriaLabel: "Chọn khu vực trên mặt trước BAR",
    zoneCode: "Mã",
    keepingUnavailable: "Khu vực không được phép giữ rượu",
    noPhoto: "Chưa có ảnh khu vực.",
    noItems: "Chưa có thông tin vật dụng chính.",
    futureManagement: "Ảnh và vật dụng của khu vực sẽ được hỗ trợ quản lý ở bước tiếp theo.",
    close: "Đóng",
    keepingTitle: "Giữ rượu",
    keepingDescription: "Màn hình quản lý rượu được giữ theo từng khách hàng.",
    keepingPreparing: "Tính năng quản lý giữ rượu đang được chuẩn bị",
    logsTitle: "Nhật ký",
    logsDescription: "Màn hình xem lịch sử thay đổi và xử lý của chức năng BAR.",
    logsPreparing: "Nhật ký hoạt động BAR đang được chuẩn bị",
  },
} as const;
