export const commonText = {
  ko: {
    create: "생성",

    delete: "삭제",
    deleteConfirm: "삭제하시겠습니까?",
    deleting: "삭제 중...",
    deleteFail: "삭제 실패",
    deleteSuccess: "삭제 성공",

    save: "저장",
    saving: "저장 중...",
    saveFail: "저장 실패",
    saveSuccess: "저장 성공",

    edit: "수정",
    editFail: "수정 실패",
    editSuccess: "수정 성공",

    update: "업데이트",
    note: "비고",

    error: "오류",
    errorDefault: "오류가 발생했습니다.",
    loginAgain: "다시 로그인해주세요.",
    loadFailed: "로드 실패",

    cancel: "취소",
    close: "닫기",
    detail: "상세",
    reset: "초기화",
    resetFilter: "필터 초기화",
    loadMore: "더 보기",
    all: "전체",
    etc: "기타",
    options: "옵션",
    canceled: "취소",
    paid: "결제완료",
    status: "상태",
    modified: "수정됨",
    table: "테이블",
    manage: "관리",
    restore: "복원",
    add: "추가",
    submit: "처리",

    directInput: "직접 입력",
    selectInput: "선택 입력",

    noPermission: "권한이 없습니다.",
    noChanges: "변경사항 없음",
    noData: "데이터 없음",
    noLogs: "로그 없음",
    loading: "불러오는 중...",
    searchLoading: "검색 중...",
    noSearchResult: "검색 결과 없음",

    part: "파트",
    category: "카테고리",
    code: "코드",
    itemName: "품목명",
    productName: "품목명",
    unit: "단위",
    unitPrice: "단가",
    quantity: "수량",
    supplier: "거래처",
    price: "금액",
    total: "총 합계",

    cash: "현금",
    transfer: "이체",
    card: "카드",
    paymentMethod: "결제수단",
    vat: "VAT",
    tax: "세금",
    taxRate: "세율",
    taxAmount: "세금",
    totalTax: "총 세금",
    receivedAmount: "받은 금액",
    changeAmount: "거스름돈",

    kitchen: "주방",
    hall: "홀",
    bar: "바",

    today: "오늘",
    month: "월",
    people: "명",
    days: "일",
    hour: "시간",
    minute: "분",
    calendarWeekdays: ["일", "월", "화", "수", "목", "금", "토"],
  },

  vi: {
    create: "Tạo",

    delete: "Xóa",
    deleteConfirm: "Bạn có chắc muốn xóa không?",
    deleting: "Đang xóa...",
    deleteFail: "Xóa thất bại",
    deleteSuccess: "Xóa thành công",

    save: "Lưu",
    saving: "Đang lưu...",
    saveFail: "Lưu thất bại",
    saveSuccess: "Lưu thành công",

    edit: "Sửa",
    editFail: "Sửa thất bại",
    editSuccess: "Sửa thành công",

    update: "Cập nhật",
    note: "Ghi chú",

    error: "Lỗi",
    errorDefault: "Đã xảy ra lỗi.",
    loginAgain: "Vui lòng đăng nhập lại.",
    loadFailed: "Không thể tải",

    cancel: "Hủy",
    close: "Đóng",
    detail: "Chi tiết",
    reset: "Đặt lại",
    resetFilter: "Đặt lại bộ lọc",
    loadMore: "Xem thêm",
    all: "Tất cả",
    etc: "Khác",
    options: "Tùy chọn",
    canceled: "Đã hủy",
    paid: "Đã thanh toán",
    status: "Trạng thái",
    modified: "Đã sửa",
    table: "Bàn",
    manage: "Quản lý",
    restore: "Khôi phục",
    add: "Thêm",
    submit: "Xử lý",

    directInput: "Nhập trực tiếp",
    selectInput: "Chọn từ danh sách",

    noPermission: "Không có quyền.",
    noChanges: "Không có thay đổi",
    noData: "Không có dữ liệu",
    noLogs: "Không có nhật ký",
    loading: "Đang tải...",
    searchLoading: "Đang tìm...",
    noSearchResult: "Không có kết quả",

    part: "Bộ phận",
    category: "Danh mục",
    code: "Mã",
    itemName: "Tên hàng",
    productName: "Tên món",
    unit: "Đơn vị",
    unitPrice: "Đơn giá",
    quantity: "Số lượng",
    supplier: "Nơi mua",
    price: "Thành tiền",
    total: "Tổng cộng",

    cash: "Tiền mặt",
    transfer: "Chuyển khoản",
    card: "Thẻ",
    paymentMethod: "Thanh toán",
    vat: "VAT",
    tax: "Thuế",
    taxRate: "Thuế suất",
    taxAmount: "Tiền thuế",
    totalTax: "Tổng thuế",
    receivedAmount: "Tiền nhận",
    changeAmount: "Tiền thối",

    kitchen: "Bếp",
    hall: "Sảnh",
    bar: "Bar",

    today: "Hôm nay",
    month: "Tháng",
    people: "người",
    days: "ngày",
    hour: "giờ",
    minute: "p",
    calendarWeekdays: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
  },
};
