export const inventoryLogsText = {
  ko: {
    title: "재고 변경 로그",
    backToInventory: "재고 페이지로 돌아가기",
    searchPlaceholder: "품목명 / 카테고리 검색",
    filterAll: "전체 보기",
    filterUpdate: "수정",
    filterDelete: "삭제",
    partAll: "전체 파트",
    partKitchen: "주방",
    partHall: "홀",
    partBar: "바",
    partEtc: "기타",
    sortDesc: "최신순",
    sortAsc: "오래된순",
    resetFilter: "필터 초기화",
    logCount: "로그 개수",
    noLogs: "로그 없음",
    quantity: "수량",
    price: "단가",
    note: "비고",
    updatedAt: "업데이트",
    filterCreate: "생성",
    loadMore: "더 보기",

    detail: "상세",
    close: "닫기",
    deleteLogConfirm: "이 로그를 삭제할까요?",
    deleteLogFail: "로그 삭제에 실패했습니다.",
    deleteLogSuccess: "로그를 삭제했습니다.",
    createDone: "품목 등록",
    deleteDone: "품목 삭제",
    noChangeDetail: "세부 변경 없음",
    delete: "삭제",
  },
  vi: {
    title: "Lịch sử thay đổi tồn kho",
    backToInventory: "Quay lại trang tồn kho",
    searchPlaceholder: "Tìm theo tên / danh mục",
    filterAll: "Xem tất cả",
    filterUpdate: "Sửa",
    filterDelete: "Xóa",
    partAll: "Tất cả",
    partKitchen: "Bếp",
    partHall: "Pv",
    partBar: "Bar",
    partEtc: "Khác",
    sortDesc: "Mới nhất",
    sortAsc: "Cũ nhất",
    resetFilter: "Đặt lại bộ lọc",
    logCount: "Số lượng log",
    noLogs: "Không có log",
    quantity: "Số lượng",
    price: "Đơn giá",
    note: "Ghi chú",
    updatedAt: "Cập nhật",
    filterCreate: "Tạo mới",
    loadMore: "Xem thêm",

    detail: "Chi tiết",
    close: "Đóng",
    deleteLogConfirm: "Xóa log này?",
    deleteLogFail: "Xóa log thất bại.",
    deleteLogSuccess: "Đã xóa log.",
    createDone: "Đăng ký hàng hóa",
    deleteDone: "Xóa hàng hóa",
    noChangeDetail: "Không có thay đổi chi tiết",
    delete: "Xóa",
  },
} as const;