export const inventoryText = {
    ko: {
        deleteConfirm: "이 재고 데이터를 삭제할까?",
        deleteTargetNotFound: "삭제할 재고를 찾을 수 없음",
        deleteLogSaveFail: "삭제 로그 저장 실패",
        deleteFail: "삭제 실패",
        deleteSuccess: "삭제 성공",
        requiredFields: "품목명, 수량, 단위 입력해라",
        editFail: "수정 실패",
        editSuccess: "수정 성공",
        saveFail: "저장 실패",
        saveSuccess: "저장 성공",
        lowStockBanner: (count: number) => `⚠️ 재고 부족 품목 ${count}개. 확인 필요.`,
        title: "재고관리",
        viewLogs: "재고 로그 보기",
        recentLogs: "최근 변경 로그",
        noLogs: "로그 없음",
        openInventoryForm: "재고등록 열기",
        closeInventoryForm: "재고등록 닫기",
        inputTitle: "재고 입력",
        selectPart: "파트 선택",
        kitchen: "주방",
        hall: "홀",
        bar: "바",
        etc: "기타",
        categoryPlaceholder: "카테고리 (육류 / 소모품 등)",
        codePlaceholder: "코드명 (선택입력)",
        itemNamePlaceholder: "품목명",
        supplierPlaceholder: "구매처",
        purchasePricePlaceholder: "구매단가 (VND)",
        unitPlaceholder: "단위 (예: 병, 개, kg)",
        quantityPlaceholder: "수량",
        lowStockThresholdPlaceholder: "재고부족 기준값",
        notePlaceholder: "비고",
        editSave: "수정 저장",
        save: "재고 저장",
        cancelEdit: "수정 취소",
        listTitle: "재고 목록",
        searchPlaceholder: "품목명 / 카테고리 / 코드 검색",
        allPart: "전체",
        viewAllItems: "전체 품목 보기",
        viewLowStockOnly: "부족 품목만 보기",
        reset: "초기화",
        noData: "데이터 없음",
        low: "부족",
        supplier: "구매처",
        purchasePrice: "구매단가",
        lowStockThreshold: "부족 기준값",
        stockLow: "재고 부족",
        note: "비고",
        edit: "수정",
        delete: "삭제",
        quantityCannotBeNegative: "수량은 0보다 작을 수 없습니다.",
        quickChangeFail: "빠른 수량 변경 실패",
        updatedAt: "업데이트",
        loadMore: "더 보기",
        detail: "상세",
        close: "닫기",
        saveQuantity: "수량 저장",
        snapshotBaseDate: "기준일",
        snapshotDiffLabel: "전일",
        snapshotView: "일자별 재고확인",
        quickReasonTitle: "재고 변경 사유 선택",
        quickReasonCheck: "재고확인",
        quickReasonPurchase: "구매",
        quickReasonService: "서비스",
        quickReasonOther: "기타",
        quickReasonOtherPlaceholder: "기타 사유 입력",
        viewTodayUpdatedOnly: "오늘 변경만",
        viewAllFromTodayFilter: "전체 보기",
    },
    vi: {
        deleteConfirm: "Bạn có muốn xóa dữ liệu tồn kho này không?",
        deleteTargetNotFound: "Không tìm thấy dữ liệu tồn kho để xóa",
        deleteLogSaveFail: "Lưu nhật ký xóa thất bại",
        deleteFail: "Xóa thất bại",
        deleteSuccess: "Xóa thành công",
        requiredFields: "Hãy nhập tên hàng, số lượng và đơn vị",
        editFail: "Sửa thất bại",
        editSuccess: "Sửa thành công",
        saveFail: "Lưu thất bại",
        saveSuccess: "Lưu thành công",
        lowStockBanner: (count: number) => `⚠️ Có ${count} mặt hàng sắp hết. Cần kiểm tra.`,
        title: "Quản lý tồn kho",
        viewLogs: "Xem nhật ký tồn kho",
        recentLogs: "Nhật ký thay đổi gần đây",
        noLogs: "Không có nhật ký",
        openInventoryForm: "Mở đăng ký tồn kho",
        closeInventoryForm: "Đóng đăng ký tồn kho",
        inputTitle: "Nhập tồn kho",
        selectPart: "Chọn bộ phận",
        kitchen: "Bếp",
        hall: "Pv",
        bar: "Bar",
        etc: "Khác",
        categoryPlaceholder: "Danh mục (thịt / vật tư tiêu hao...)",
        codePlaceholder: "Mã hàng (không bắt buộc)",
        itemNamePlaceholder: "Tên mặt hàng",
        supplierPlaceholder: "Nhà cung cấp",
        purchasePricePlaceholder: "Giá mua (VND)",
        unitPlaceholder: "Đơn vị (vd: chai, cái, kg)",
        quantityPlaceholder: "Số lượng",
        lowStockThresholdPlaceholder: "Mức tồn kho tối thiểu",
        notePlaceholder: "Ghi chú",
        editSave: "Lưu chỉnh sửa",
        save: "Lưu tồn kho",
        cancelEdit: "Hủy chỉnh sửa",
        listTitle: "Danh sách tồn kho",
        searchPlaceholder: "Tìm theo tên / danh mục / mã",
        allPart: "Tất cả",
        viewAllItems: "Xem tất cả mặt hàng",
        viewLowStockOnly: "Chỉ xem hàng thiếu",
        reset: "Đặt lại",
        noData: "Không có dữ liệu",
        low: "Thiếu",
        supplier: "Nhà cung cấp",
        purchasePrice: "Giá mua",
        lowStockThreshold: "Mức thiếu hàng",
        stockLow: "Thiếu tồn kho",
        note: "Ghi chú",
        edit: "Sửa",
        delete: "Xóa",
        quantityCannotBeNegative: "Số lượng không thể nhỏ hơn 0.",
        quickChangeFail: "Cập nhật nhanh số lượng thất bại",
        updatedAt: "Cập nhật",
        loadMore: "Xem thêm",
        detail: "Chi tiết",
        close: "Đóng",
        saveQuantity: "Lưu số lượng",
        snapshotBaseDate: "Ngày gốc",
        snapshotDiffLabel: "So với hôm trước",
        snapshotView: "Kiểm tra tồn kho theo ngày",
        quickReasonTitle: "Chọn lý do thay đổi tồn kho",
        quickReasonCheck: "Kiểm kho",
        quickReasonPurchase: "Nhập hàng",
        quickReasonService: "Dùng cho khách",
        quickReasonOther: "Khác",
        quickReasonOtherPlaceholder: "Nhập lý do khác",
        viewTodayUpdatedOnly: "Chỉ hôm nay",
        viewAllFromTodayFilter: "Xem tất cả",
    },
} as const;