export const inventoryText = {
  ko: {
    title: "재고관리",
    listTitle: "재고 목록",

    searchPlaceholder: "품목명 / 카테고리 / 코드 검색",

    lowStockThreshold: "부족 기준값",
    lowStockEnabled: "재고부족 알림 사용",
    lowStockEnabledHelp: "재고부족 알림을 사용하는 품목만 부족품목에 표시됩니다.",
    filterLowStock: "부족품목",
    filterToday: "오늘변경",

    low: "부족",
    stockLow: "재고 부족",
    lowStockBanner: (count: number) =>
      `⚠️ 재고 부족 품목 ${count}개. 확인 필요.`,

    openInventoryForm: "재고등록 열기",
    closeInventoryForm: "재고등록 닫기",
    inputTitle: "재고 입력",

    categoryPlaceholder: "카테고리 (육류 / 소모품 등)",
    unitPlaceholder: "단위 (예: 병, 개, kg)",
    packageContentLabel: "1단위 내용량",
    packageContentHelp:
      "레시피 환산용 기준값입니다. 예: 1병=700ml, 1캔=320ml, 1봉=1000g",
    packageContentQuantityMustBePositive: "1단위 내용량은 0보다 커야 합니다.",
    packageContentPairRequired: "1단위 내용량과 단위를 함께 입력하세요.",
    packageContentUnitInvalid: "1단위 내용량 단위는 ml 또는 g만 사용할 수 있습니다.",
    requiredFields: "품목명, 수량, 단위 입력하세요",

    newCategory: "새 카테고리",
    newCategoryPlaceholder: "새 카테고리 입력",
    newSupplier: "새 거래처",
    newSupplierPlaceholder: "새 거래처 입력",

    purchase: "구매",
    purchasePrice: "구매단가",
    otherReason: "기타 사유 입력",

    quickSave: "빠른저장",
    kegReplace: "🍺 케그 교체",
    kegReplaceShort: "🍺 교체",
    kegRemaining: "잔량",
    kegNotStarted: "교체 전",
    kegProgressLoading: "잔량 계산 중",
    kegElapsedDays: (days: number) => `${days}일 경과`,
    kegReplacementTimeTitle: "케그 교체 시간",
    kegStartTimeTitle: "케그 시작 시간 수정",
    kegInfoSummaryTitle: "케그 정보 요약",
    kegTimeLabel: "날짜/시간",
    kegReplaceSubmit: "교체 확정",
    kegStartTimeSubmit: "시작 시간 저장",
    kegChangeTimeSubmit: "교체 시간 변경",
    kegReplaceConfirm: "이 케그를 교체하고 재고를 -1 Keg 차감할까요?",
    kegPreviousSold: "이전 Keg 판매량",
    kegPreviousRemaining: "잔량",
    kegPreviousLossRate: "로스율",
    kegUsagePeriod: "사용 기간",
    kegStartedAtLabel: "시작 시간",
    kegSoldAmountLabel: "판매 사용량",
    kegRemainingAmountLabel: "현재 잔량",
    kegRemainingPercentLabel: "현재 잔량률",
    kegSalesQuantity: "판매수량",
    kegSalesRegular: "일반",
    kegSalesTower: "타워",
    kegRegularSoldAmountLabel: "잔 판매량",
    kegTowerSoldAmountLabel: "타워 판매량",
    kegStandard: "기준",
    kegAverage: "평균",
    kegAverageUnit: "상품",
    kegRegularAverageLabel: "잔",
    kegPreview: "교체 미리보기",
    kegPreviewCurrentInventory: "현재 재고 → 예상 재고",
    kegPreviewActiveSession: "현재 활성 세션",
    kegPreviewEndedAt: "예상 종료 시각",
    kegPreviewSalesCapacity: "판매량 / Keg 용량",
    kegPreviewOverage: "초과 사용량",
    kegPreviewNoWrites: "실제 재고와 세션은 변경되지 않았습니다",
    kegOverageWarning: (liters: string) =>
        `Keg 용량보다 판매 기준 사용량이 ${liters}L 많습니다. 교체 기록 누락 또는 세션 시작시간을 확인하세요.`,
    kegSalesBreakdownMismatch:
        "저장된 총 판매량과 판매 구성 합계가 다릅니다. 구성 상세를 확인하세요.",
    kegTowerAverageLabel: "타워",
    kegRegularAverageUnit: "잔",
    kegTowerAverageUnit: "타워",
    quickGuide: "새 수량 입력 또는 +/- 버튼 조정 후 빠른저장.",
    quantityNoChange: "수량 변화 없음",
    quantityCannotBeNegative: "수량은 0보다 작을 수 없습니다.",

    reasonTitle: "재고 변경 사유 선택",
    reasonCheck: "재고확인",
    service: "서비스",

    snapshotBaseDate: "기준일",
    snapshotDiff: "전일",
    snapshotView: "일자별 재고확인",

    logView: "재고 로그 보기",
    logRecent: "최근 변경 로그",
    logItemTitle: "품목 로그",

    sortDesc: "최신순",
    sortAsc: "오래된순",
    logCount: "로그 개수",
    createDone: "품목 등록",

    snapshotDates: "날짜 선택",
    resultCount: "품목 수",
    baseDateLabel: "기준 날짜",
    compareNowLabel: "현재 재고와 비교 중",
    snapshotCalendar: "스냅샷 캘린더",
    filterChange: "변화 있는 품목만 보기",
    previousDay: "전일대비",
    legendPurchase: "입고상품 있음",
    snapshotTitle: "일자별 입고 상품",
    existingStockRegistration: "기존재고 추가",
    existingStockRegistrationDesc: "매장에 이미 있던 재고를 앱에 등록합니다.",
    newPurchaseRegistration: "신규입고 품목",
    newPurchaseRegistrationDesc: "새로 구매해서 들어온 품목을 등록합니다.",
    quantityEditQuickSaveOnly: "수량 변경은 빠른저장 버튼을 이용해주세요.",
    stockCheck: "재고확인",
    serviceGift: "서비스/증정",
    otherMovements: "기타 변동사항",
    unclassified: "미분류",
    photoLogLabel: "사진",
    photoAdded: "품목 사진 추가",
    photoChanged: "품목 사진 변경",
    photoDeleted: "품목 사진 삭제",
    photoAddButton: "사진 추가",
    photoChangeButton: "사진 변경",
    photoDeleteButton: "사진 삭제",
    photoCameraButton: "촬영",
    photoLibraryButton: "앨범 선택",
    photoSaved: "사진이 저장되었습니다.",
    photoDeletedSuccess: "사진이 삭제되었습니다.",
    photoCompressing: "사진 압축 중...",
    photoCompressed: (before: string, after: string) =>
      `사진을 업로드용으로 압축했습니다. ${before} → ${after}`,
    photoCompressionFailed:
      "사진을 100KB 이하로 줄일 수 없습니다. 조금 더 단순한 배경에서 다시 찍어주세요.",
    photoUnsupportedFormat:
      "이 사진 형식은 브라우저에서 처리할 수 없습니다. 카메라 설정을 JPG로 변경하거나 다른 사진을 선택해주세요.",
    deleteLinkedAppliedPosDeductionConfirm:
      "해당 품목은 실제 POS 재고 차감 이력과 연결되어 있습니다.\n정말 삭제하시겠습니까?\n삭제하면 POS 차감 이력도 함께 삭제됩니다.",
    deleteLinkedInventoryHistoryConfirm:
      "이 품목에는 재고 변경 이력이 있습니다.\n삭제하면 일자별재고와 월간현황 기록에서도 함께 삭제됩니다.\n정말 삭제하시겠습니까?",
    deleteLinkedFailedPosDeductionConfirm:
      "해당 품목은 POS 검수/실패 기록과 연결되어 있습니다.\n정말 삭제하시겠습니까?\n삭제하면 관련 실패 기록도 함께 정리됩니다.",
    deleteLinkedPosMappingConfirm:
      "해당 품목은 POS 상품과 연결되어 있습니다.\n정말 삭제하시겠습니까?\n삭제하면 POS 상품 매핑도 함께 삭제됩니다.",
    deleteLinkedPosMappingFailed: "POS 상품 매핑 삭제 후 다시 시도해주세요.",
    deleteLinkedPosReferenceFailed: "POS 참조 기록 삭제 후 다시 시도해주세요.",
    duplicateItemRegistered: (location: string) =>
      `해당 상품은 ${location}에 이미 등록되어 있습니다.`,
    duplicateItemRegisteredFallback: "해당 상품은 이미 등록되어 있습니다.",
    editReasonModalTitle: "수정 사유를 선택해주세요.",
    editReasonModalDescription: "선택한 사유는 품목 로그에 표시됩니다.",
    quantityChange: "변화",
    editInfoUpdatedNote: "품목정보 수정",
    noAdditionalChanges: "추가로 저장할 변경사항이 없습니다.",
    syncLog: "동기화",
    editItem: "수정",
    syncCurrentItemHelp: "현재 품목명/카테고리/단위/구매처/단가를 이 기록에 반영합니다.",
    editItemHelp: "재고관리 페이지에서 이 품목을 수정합니다.",
    deactivateItem: "비활성",
    activateItem: "활성화",
    includeInactiveItems: "비활성",
    inactiveItem: "비활성 품목",
    stockCheckNeeded: "확인필요",
    stockCheckDaysOverdue: (days: number) => `${days}일 미확인`,
    stockCheckNoHistory: "확인 이력 없음",
    stockCheckNeededFilterCount: (count: number) => `확인필요 ${count}개`,
    stockCheckNeededOnly: "확인필요만 보기",
    deactivateItemConfirmTitle: "이 품목을 비활성화할까요?",
    deactivateItemConfirmDescription:
      "기본 재고 목록에서 숨겨지지만, 과거 로그와 집계 기록은 유지됩니다.",
    activateItemConfirm: "이 품목을 다시 활성화할까요?",
    deactivateDone: "비활성 처리되었습니다.",
    activateDone: "다시 활성화되었습니다.",
    deactivateFail: "비활성 처리 실패",
    activateFail: "활성화 실패",
  },

  vi: {
    title: "Quản lý kho",
    listTitle: "Danh sách kho",

    searchPlaceholder: "Tìm theo tên hàng / danh mục / mã",

    lowStockThreshold: "Mức cảnh báo thiếu",
    lowStockEnabled: "Bật cảnh báo thiếu hàng",
    lowStockEnabledHelp:
      "Chỉ những mục bật cảnh báo mới hiển thị trong danh sách thiếu hàng.",
    filterLowStock: "Thiếu",
    filterToday: "Đổi hôm nay",

    low: "Thiếu",
    stockLow: "Thiếu hàng",
    lowStockBanner: (count: number) =>
      `⚠️ Có ${count} mặt hàng thiếu. Cần kiểm tra.`,

    openInventoryForm: "Mở đăng ký kho",
    closeInventoryForm: "Đóng đăng ký kho",
    inputTitle: "Nhập kho",

    categoryPlaceholder: "Danh mục (thịt / vật tư...)",
    unitPlaceholder: "Đơn vị (VD: chai, cái, kg)",
    packageContentLabel: "Dung lượng mỗi đơn vị",
    packageContentHelp:
      "Dùng để quy đổi công thức. Ví dụ: 1 chai=700ml, 1 lon=320ml, 1 gói=1000g",
    packageContentQuantityMustBePositive:
      "Dung lượng mỗi đơn vị phải lớn hơn 0.",
    packageContentPairRequired:
      "Vui lòng nhập cả dung lượng và đơn vị.",
    packageContentUnitInvalid: "Đơn vị chỉ có thể là ml hoặc g.",
    requiredFields: "Vui lòng nhập tên hàng, số lượng, đơn vị",

    newCategory: "Danh mục mới",
    newCategoryPlaceholder: "Nhập danh mục mới",
    newSupplier: "Nơi mua mới",
    newSupplierPlaceholder: "Nhập nơi mua mới",

    purchase: "Mua",
    purchasePrice: "Đơn giá mua",
    otherReason: "Nhập lý do khác",

    quickSave: "Lưu nhanh",
    kegReplace: "🍺 Đổi keg",
    kegReplaceShort: "🍺 Đổi",
    kegRemaining: "Còn",
    kegNotStarted: "Chưa đổi",
    kegProgressLoading: "Đang tính mức còn lại",
    kegElapsedDays: (days: number) => `${days} ngày`,
    kegReplacementTimeTitle: "Thời gian đổi keg",
    kegStartTimeTitle: "Sửa thời gian bắt đầu keg",
    kegInfoSummaryTitle: "Tóm tắt keg",
    kegTimeLabel: "Ngày/giờ",
    kegReplaceSubmit: "Xác nhận đổi",
    kegStartTimeSubmit: "Lưu thời gian",
    kegChangeTimeSubmit: "Đổi thời gian thay keg",
    kegReplaceConfirm: "Đổi keg này và trừ tồn kho -1 Keg?",
    kegPreviousSold: "Sản lượng keg trước",
    kegPreviousRemaining: "Còn lại",
    kegPreviousLossRate: "Tỷ lệ hao hụt",
    kegUsagePeriod: "Thời gian sử dụng",
    kegStartedAtLabel: "Thời gian bắt đầu",
    kegSoldAmountLabel: "Lượng đã bán",
    kegRemainingAmountLabel: "Lượng còn lại",
    kegRemainingPercentLabel: "Tỷ lệ còn lại",
    kegSalesQuantity: "Số lượng bán",
    kegSalesRegular: "Ly",
    kegSalesTower: "Tháp",
    kegRegularSoldAmountLabel: "Ly đã bán",
    kegTowerSoldAmountLabel: "Tháp đã bán",
    kegStandard: "Chuẩn",
    kegAverage: "Trung bình",
    kegAverageUnit: "món",
    kegRegularAverageLabel: "Ly",
    kegPreview: "Xem trước thay keg",
    kegPreviewCurrentInventory: "Tồn kho hiện tại → tồn kho dự kiến",
    kegPreviewActiveSession: "Phiên keg đang hoạt động",
    kegPreviewEndedAt: "Thời gian kết thúc dự kiến",
    kegPreviewSalesCapacity: "Lượng bán / dung tích keg",
    kegPreviewOverage: "Lượng vượt dung tích",
    kegPreviewNoWrites: "Tồn kho và phiên keg thực tế chưa được thay đổi",
    kegOverageWarning: (liters: string) =>
        `Lượng sử dụng theo bán hàng vượt dung tích keg ${liters}L. Vui lòng kiểm tra việc thiếu ghi nhận thay keg hoặc thời gian bắt đầu phiên.`,
    kegSalesBreakdownMismatch:
        "Tổng lượng bán đã lưu khác với tổng chi tiết bán hàng. Vui lòng kiểm tra chi tiết.",
    kegTowerAverageLabel: "Tháp",
    kegRegularAverageUnit: "ly",
    kegTowerAverageUnit: "tháp",
    quickGuide: "Nhập số lượng mới hoặc chỉnh bằng nút +/- rồi lưu nhanh.",
    quantityNoChange: "Số lượng không thay đổi",
    quantityCannotBeNegative: "Số lượng không thể nhỏ hơn 0.",

    reasonTitle: "Chọn lý do thay đổi kho",
    reasonCheck: "Kiểm tra kho",
    service: "Dịch vụ",

    snapshotBaseDate: "Ngày chuẩn",
    snapshotDiff: "Hôm trước",
    snapshotView: "Kiểm tra kho theo ngày",

    logView: "Xem nhật ký kho",
    logRecent: "Nhật ký thay đổi gần đây",
    logItemTitle: "Nhật ký mặt hàng",

    sortDesc: "Mới nhất",
    sortAsc: "Cũ nhất",
    logCount: "Số lượng log",
    createDone: "Đăng ký hàng hóa",

    snapshotDates: "Chọn ngày",
    resultCount: "Số lượng mục",
    baseDateLabel: "Ngày đang xem",
    compareNowLabel: "Đang so sánh với tồn kho hiện tại",
    snapshotCalendar: "Lịch snapshot",
    filterChange: "Chỉ xem mặt hàng có thay đổi",
    previousDay: "So với hôm trước",
    legendPurchase: "Có hàng nhập",
    snapshotTitle: "Hàng nhập theo ngày",
    existingStockRegistration: "Thêm tồn kho cũ",
    existingStockRegistrationDesc: "Đăng ký hàng đã có sẵn trong cửa hàng vào ứng dụng.",
    newPurchaseRegistration: "Hàng mới nhập",
    newPurchaseRegistrationDesc: "Đăng ký hàng mới vừa mua về.",
    quantityEditQuickSaveOnly: "Vui lòng đổi số lượng bằng nút lưu nhanh.",
    stockCheck: "Kiểm tra kho",
    serviceGift: "Dịch vụ/tặng",
    otherMovements: "Biến động khác",
    unclassified: "Chưa phân loại",
    photoLogLabel: "Ảnh",
    photoAdded: "Thêm ảnh sản phẩm",
    photoChanged: "Thay đổi ảnh sản phẩm",
    photoDeleted: "Xóa ảnh sản phẩm",
    photoAddButton: "Thêm ảnh",
    photoChangeButton: "Thay đổi ảnh",
    photoDeleteButton: "Xóa ảnh",
    photoCameraButton: "Chụp ảnh",
    photoLibraryButton: "Chọn từ thư viện",
    photoSaved: "Đã lưu ảnh.",
    photoDeletedSuccess: "Đã xóa ảnh.",
    photoCompressing: "Đang nén ảnh...",
    photoCompressed: (before: string, after: string) =>
      `Đã nén ảnh để tải lên. ${before} → ${after}`,
    photoCompressionFailed:
      "Không thể giảm ảnh xuống dưới 100KB. Vui lòng chụp lại với nền đơn giản hơn.",
    photoUnsupportedFormat:
      "Trình duyệt không xử lý được định dạng ảnh này. Vui lòng chọn ảnh JPG hoặc ảnh khác.",
    deleteLinkedAppliedPosDeductionConfirm:
      "Sản phẩm này đang được liên kết với lịch sử trừ kho POS thực tế.\nBạn có chắc chắn muốn xóa không?\nNếu xóa, lịch sử trừ kho POS cũng sẽ bị xóa.",
    deleteLinkedInventoryHistoryConfirm:
      "Sản phẩm này có lịch sử thay đổi kho.\nNếu xóa, dữ liệu trong tồn kho theo ngày và báo cáo tháng cũng sẽ bị xóa.\nBạn có chắc chắn muốn xóa không?",
    deleteLinkedFailedPosDeductionConfirm:
      "Sản phẩm này đang được liên kết với dữ liệu kiểm tra/thất bại của POS.\nBạn có chắc chắn muốn xóa không?\nNếu xóa, các dữ liệu thất bại liên quan cũng sẽ được dọn dẹp.",
    deleteLinkedPosMappingConfirm:
      "Sản phẩm này đang được liên kết với hàng POS.\nBạn có chắc chắn muốn xóa không?\nNếu xóa, liên kết POS cũng sẽ bị xóa.",
    deleteLinkedPosMappingFailed: "Vui lòng xóa liên kết POS rồi thử lại.",
    deleteLinkedPosReferenceFailed:
      "Vui lòng xóa dữ liệu tham chiếu POS rồi thử lại.",
    duplicateItemRegistered: (location: string) =>
      `Sản phẩm này đã được đăng ký trong ${location}.`,
    duplicateItemRegisteredFallback: "Sản phẩm này đã được đăng ký.",
    editReasonModalTitle: "Vui lòng chọn lý do chỉnh sửa.",
    editReasonModalDescription:
      "Lý do đã chọn sẽ được hiển thị trong lịch sử sản phẩm.",
    quantityChange: "Biến",
    editInfoUpdatedNote: "Sửa thông tin sản phẩm",
    noAdditionalChanges: "Không có thay đổi nào khác để lưu.",
    syncLog: "Đồng bộ",
    editItem: "Sửa",
    syncCurrentItemHelp: "Đồng bộ tên hàng/danh mục/đơn vị/nơi mua/đơn giá hiện tại vào lịch sử này.",
    editItemHelp: "Sửa sản phẩm này trong trang quản lý kho.",
    deactivateItem: "Tắt",
    activateItem: "Bật lại",
    includeInactiveItems: "Đã tắt",
    inactiveItem: "Mục đã tắt",
    stockCheckNeeded: "Cần kiểm",
    stockCheckDaysOverdue: (days: number) => `${days} ngày chưa kiểm`,
    stockCheckNoHistory: "Chưa có lịch kiểm",
    stockCheckNeededFilterCount: (count: number) => `Cần kiểm ${count} mục`,
    stockCheckNeededOnly: "Chỉ xem mục cần kiểm",
    deactivateItemConfirmTitle: "Bạn muốn tắt mục này không?",
    deactivateItemConfirmDescription:
      "Mục này sẽ bị ẩn khỏi danh sách tồn kho mặc định, nhưng lịch sử và báo cáo cũ vẫn được giữ lại.",
    activateItemConfirm: "Bạn muốn bật lại mục này không?",
    deactivateDone: "Đã tắt mục này.",
    activateDone: "Đã bật lại mục này.",
    deactivateFail: "Không thể tắt mục này.",
    activateFail: "Không thể bật lại mục này.",
  },
};
