export const mypageText = {
  ko: {
    noLoginInfo: "로그인 정보가 없음",
    fetchFail: "유저 정보 불러오기 실패",
    loading: "불러오는 중...",
    title: "마이페이지",
    name: "이름",
    username: "아이디",
    part: "파트",
    position: "직급",
    language: "언어",
    birthDate: "생년월일",
    hireDate: "입사일",
    koLabel: "한국어",
    viLabel: "베트남어",
  },
  vi: {
    noLoginInfo: "Không có thông tin đăng nhập",
    fetchFail: "Không thể tải thông tin người dùng",
    loading: "Đang tải...",
    title: "Trang cá nhân",
    name: "Tên",
    username: "ID",
    part: "Bộ phận",
    position: "Chức vụ",
    language: "Ngôn ngữ",
    birthDate: "Ngày sinh",
    hireDate: "Ngày vào làm",
    koLabel: "Tiếng Hàn",
    viLabel: "Tiếng Việt",
  },
} as const;