export const salesCloseText = {
  "ko": {
    "title": "영업 마감",
    "close": "영업 마감",
    "closed": "영업 마감 완료",
    "manual": "수동 마감",
    "automatic": "자동 마감",
    "system": "시스템",
    "current": "현재 POS",
    "closedTotal": "마감 당시",
    "finalTotal": "최종 POS",
    "difference": "차이",
    "lastSync": "최근 POS 동기화",
    "pending": "03:05 최종 POS 검증 대기",
    "verified": "✅ 최종 POS 검증 완료",
    "verifiedDetail": "마감 이후 금액 변경 없음",
    "metadata": "ℹ️ POS 정보 변경 확인",
    "metadataDetail": "최종 금액 및 결제수단 금액은 동일",
    "drift": "⚠️ 마감 후 POS 금액 변경 감지",
    "recloseReview": "마감 재확인",
    "ownerReview": "관리자 재확인 필요",
    "reclose": "재마감",
    "cancel": "취소",
    "confirm": "변경 내용을 확인한 뒤 재마감을 확정하세요.",
    "manualCloseConfirmTitle": "영업 마감을 진행하시겠습니까?",
    "manualCloseConfirmDetail": "선택한 영업일의 POS 최신 데이터를 확인한 후 마감 처리합니다. 마감 이후 추가 주문이나 결제가 발생하면 재확인이 필요할 수 있습니다.",
    "proceedClose": "마감 진행",
    "working": "POS 확인 및 마감 중...",
    "loading": "마감 상태 불러오는 중...",
    "failed": "마감을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.",
    "syncFailed": "최종 POS 동기화에 실패했습니다. 마감은 변경되지 않았습니다.",
    "sourceInvalid": "POS 금액과 결제수단을 확인해야 합니다. 마감할 수 없습니다.",
    "cardLocked": "카드 정산이 연결되어 있어 카드 매출 변경을 재마감할 수 없습니다.",
    "monthClosed": "월마감이 완료되어 영업 마감을 변경할 수 없습니다.",
    "forbidden": "영업 마감 권한이 없습니다.",
    "beforeClose": "오후 11시 이후 영업 마감이 가능합니다.",
    "future": "미래 영업일은 마감할 수 없습니다.",
    "settings": "영업시간 설정을 확인해 주세요.",
    "sourceChanged": "확인 이후 POS 정보가 변경되었습니다. 최신 금액을 다시 확인해 주세요.",
    "done": "영업 마감이 완료되었습니다.",
    "unchanged": "이미 동일한 POS 데이터로 마감되어 있습니다.",
    "relogin": "다시 로그인해 주세요.",
    "checkFailed": "⚠️ 최종 POS 검증 실패",
    "ledgerMismatch": "Ledger 반영 상태를 관리자에게 확인해 주세요.",
    "notAvailable": "확인할 수 없음",
    "cash": "현금",
    "transfer": "계좌이체",
    "card": "카드",
    "other": "기타"
  },
  "vi": {
    "title": "Chốt ngày kinh doanh",
    "close": "Chốt ngày",
    "closed": "Đã chốt ngày kinh doanh",
    "manual": "Chốt thủ công",
    "automatic": "Chốt tự động",
    "system": "Hệ thống",
    "current": "POS hiện tại",
    "closedTotal": "Khi chốt",
    "finalTotal": "POS cuối ngày",
    "difference": "Chênh lệch",
    "lastSync": "Đồng bộ POS gần nhất",
    "pending": "Đang chờ kiểm tra POS cuối ngày lúc 03:05",
    "verified": "✅ Đã kiểm tra POS cuối ngày",
    "verifiedDetail": "Số tiền không thay đổi sau khi chốt",
    "metadata": "ℹ️ Thông tin POS đã thay đổi",
    "metadataDetail": "Tổng tiền và số tiền theo phương thức thanh toán không thay đổi",
    "drift": "⚠️ Phát hiện số tiền POS thay đổi sau khi chốt",
    "recloseReview": "Kiểm tra chốt lại",
    "ownerReview": "Cần quản trị viên kiểm tra lại",
    "reclose": "Chốt lại",
    "cancel": "Hủy",
    "confirm": "Kiểm tra các thay đổi trước khi xác nhận chốt lại.",
    "manualCloseConfirmTitle": "Bạn có muốn chốt ngày kinh doanh không?",
    "manualCloseConfirmDetail": "Hệ thống sẽ kiểm tra dữ liệu POS mới nhất của ngày kinh doanh đã chọn trước khi chốt. Nếu có thêm đơn hàng hoặc thanh toán sau khi chốt, có thể cần kiểm tra lại.",
    "proceedClose": "Tiến hành chốt",
    "working": "Đang kiểm tra POS và chốt ngày...",
    "loading": "Đang tải trạng thái chốt ngày...",
    "failed": "Không thể hoàn tất chốt ngày. Vui lòng thử lại sau.",
    "syncFailed": "Đồng bộ POS cuối ngày thất bại. Trạng thái chốt không thay đổi.",
    "sourceInvalid": "Cần kiểm tra số tiền POS và phân bổ thanh toán. Chưa thể chốt ngày.",
    "cardLocked": "Doanh thu thẻ đã được đối soát nên không thể chốt lại khi doanh thu thẻ thay đổi.",
    "monthClosed": "Tháng đã khóa nên không thể thay đổi chốt ngày.",
    "forbidden": "Bạn không có quyền chốt ngày.",
    "beforeClose": "Có thể chốt ngày kinh doanh sau 23:00.",
    "future": "Không thể chốt ngày kinh doanh trong tương lai.",
    "settings": "Vui lòng kiểm tra cấu hình giờ kinh doanh.",
    "sourceChanged": "Thông tin POS đã thay đổi sau khi xem. Vui lòng kiểm tra lại số tiền mới nhất.",
    "done": "Đã chốt ngày kinh doanh.",
    "unchanged": "Ngày này đã được chốt với cùng dữ liệu POS.",
    "relogin": "Vui lòng đăng nhập lại.",
    "checkFailed": "⚠️ Kiểm tra POS cuối ngày thất bại",
    "ledgerMismatch": "Vui lòng nhờ quản trị viên kiểm tra dữ liệu Ledger.",
    "notAvailable": "Chưa có thông tin",
    "cash": "Tiền mặt",
    "transfer": "Chuyển khoản",
    "card": "Thẻ",
    "other": "Khác"
  }
} as const;
