export const salesText = {
  ko: {
    tabs: {
      daily: "일간현황",
      receipts: "영수증 조회",
      monthly: "월간현황",
    },
    common: {
      receipt: "영수증",
      receipts: "영수증",
      soldItems: "판매상품",
      salesItems: "판매상품",
      optionItems: "옵션",
      salesAmount: "판매금액",
      totalPaymentAmount: "총 결제금액",
      actualPaid: "실제 지불",
      totalSales: "총 매출",
      averageReceiptAmount: "객단가",
      paidReceiptBase: "결제 완료 영수증 기준",
      paymentSummary: "결제수단 요약",
      paymentBase: "POS 결제 기준",
      paymentTotal: "결제 합계",
      taxSummary: "세금 요약",
      taxSaving: "절세",
      amountDifference: "차액",
      adjustedReceiptBase: "수정 영수증 기준",
      businessDayBase: "영업일 기준",
      soldItemBase: "판매상품 기준",
      taxDataLoading: "세금 데이터를 불러오고 있습니다.",
      taxDataLoadFailed: "세금 데이터 로드 실패",
      noTaxData: "세금 데이터 없음",
      receiptCountSuffix: "건",
      itemCountSuffix: "개",
      productCountSuffix: "개",
      optionCountSuffix: "개",
      detailLoading: "상세 내용 로드 중",
      detailLoadFailed: "상세 로드 실패",
      noPaymentData: "결제 데이터 없음",
    },
    daily: {
      badge: "TODAY",
      title: "일간현황",
      syncButton: "POS 데이터 불러오기",
      forceSyncButton: "강제 새로고침",
      syncing: "불러오는 중",
      syncSuccess: "POS 데이터 동기화 완료",
      syncSkipped: "최근 동기화가 완료되어 다시 불러오지 않았습니다",
      syncFailed: "POS 데이터 로드 실패",
      noLogin: "로그인 정보 없음",
      hourlySales: "시간대별 매출",
      topItems: "많이 팔린 상품",
      hourlyDataLoading: "시간대별 매출을 불러오고 있습니다.",
      noHourlySalesData: "시간대별 매출 데이터 없음",
      topItemsLoading: "많이 팔린 상품을 불러오고 있습니다.",
      noTopItemsData: "판매상품 데이터 없음",
    },
    monthly: {
      badge: "MONTHLY",
      title: "월간현황",
      previousMonth: "이전",
      nextMonth: "다음",
      dailySales: "일별 매출",
      menuSales: "판매현황",
      salesQuantity: "판매수량",
      itemSalesAmount: "판매금액",
      salesReceiptCount: "영수증 수",
      option: "옵션",
      selection: "선택",
      unlinkedOptions: "미연결 옵션",
      unlinkedOptionsWarning:
        "일부 옵션이 부모 메뉴와 연결되지 않아 별도로 집계되었습니다.",
      unlinkedOptionDetails: "미연결 옵션 상세",
      lineCountLabel: "라인",
      saleDate: "판매일시",
      failureReason: "연결 실패 이유",
      failureReasons: {
        missing_parent_id: "부모 메뉴 ID 없음",
        parent_not_found: "부모 메뉴를 찾을 수 없음",
        parent_not_sales_line: "부모가 판매 메뉴가 아님",
        parent_excluded_or_not_eligible: "부모 메뉴가 집계 대상이 아님",
        parent_missing_ref_detail_id: "부모 메뉴 연결 ID 없음",
        unknown: "확인 필요",
      },
      noMenuSalesData: "판매 데이터가 없습니다.",
      menuSalesDataLoading: "판매현황을 불러오고 있습니다.",
      menuSalesDataLoadFailed: "판매현황 데이터 로드 실패",
      all: "전체",
      food: "음식",
      drink: "주류·음료",
      uncategorized: "미분류",
      categoryManagement: "분류 관리",
      assignToFood: "음식으로 지정",
      assignToDrink: "주류·음료로 지정",
      keepUncategorized: "미분류 유지",
      unclassifiedCategoriesNotice: "분류되지 않은 카테고리가 있습니다.",
      sameCategoryMovesTogether:
        "같은 카테고리명을 가진 메뉴가 함께 이동합니다.",
      categoryGroupSaved: "카테고리 분류가 저장되었습니다.",
      categoryGroupSaveFailed: "카테고리 분류 저장에 실패했습니다.",
      noPermission: "권한이 없습니다.",
      sortHighToLow: "높은순",
      sortLowToHigh: "낮은순",
      category: "카테고리",
      categorySales: "카테고리별 판매",
      allMenuItems: "전체 메뉴",
      menuSalesScrollNotice:
        "내부 목록을 스크롤해서 전체 메뉴를 확인할 수 있습니다.",
      dailyAverageSales: "일평균",
      percentOfMonth: "월매출 비중",
      dailyDataLoading: "일별 매출을 불러오고 있습니다.",
      dailyDataLoadFailed: "일별 매출 데이터 로드 실패",
      noMonthlySalesData: "월간 매출 데이터 없음",
    },
    receipts: {
      badge: "RECEIPTS",
      title: "영수증 조회",
      listTitle: "영수증 목록",
      noReceipts: "영수증 데이터 없음",
      selectedBusinessDateNoReceipts: "선택한 영업일의 영수증이 없습니다.",
      menuSyncButton: "영수증 수정용 메뉴 동기화",
      menuSyncDescription:
        "POS의 최신 메뉴/가격/옵션 정보를 다시 불러옵니다.",
      menuSyncing: "메뉴 동기화 중...",
      menuSyncSuccess: "메뉴 동기화 완료",
      menuSyncApplied: "반영",
      menuSyncDetailFailed: "상세 실패",
      menuSyncCountSuffix: "건",
      menuSyncDetailWarning:
        "일부 상품의 옵션 상세정보를 불러오지 못했습니다. 해당 상품은 옵션이 누락될 수 있습니다.",
      menuSyncFailed: "메뉴 동기화에 실패했습니다.",
      noPermission: "권한이 없습니다.",
      createManualReceiptButton: "자체 영수증 생성",
      manualReceiptModalTitle: "자체 영수증 생성",
      manualReceiptCreating: "생성 중...",
      manualReceiptSaved: "자체 영수증이 생성되었습니다.",
      manualReceiptFailed: "자체 영수증 생성에 실패했습니다.",
      manualReceiptBadge: "자체",
      manualReceiptFreeTextHint: "직접 입력 품목은 재고차감 매핑이 필요할 수 있습니다.",
      manualReceiptNoLines: "품목을 1개 이상 추가해주세요.",
      manualReceiptSaleTime: "판매시간",
      manualReceiptTableOrNote: "테이블명 / 메모",
      manualReceiptVatEnabled: "VAT 적용",
      manualReceiptVatDisabled: "VAT 미적용",
      manualReceiptDirectInput: "직접 입력",
      manualReceiptPosSearch: "POS 상품 검색",
    },
    receiptsEdit: {
      title: "영수증 수정",
      taxRecalculateNotice: "저장 후 세금 합계가 재반영됩니다.",
      addItem: "품목 추가",
      searchProductPlaceholder: "코드 또는 품목명 입력",
      editMemo: "수정 메모",
      memoPlaceholder: "수정 사유를 입력하세요",
      productSearchFailed: "상품 검색 실패",
      saveFailed: "영수증 수정 실패",
      finalAmountTooHigh: "받은 금액이 최종금액보다 적습니다.",
      optionEditProtected:
        "옵션이 포함된 영수증은 현재 수정할 수 없습니다. 옵션 금액과 VAT가 누락될 수 있어 보호 중입니다.",
      existingOptionReadOnlyNotice:
        "기존 옵션은 직접 수정할 수 없습니다. 옵션 변경은 부모 상품을 삭제 후 다시 추가해주세요.",
      selectOptions: "옵션 선택",
      noOptions: "옵션 없음",
      surcharge: "추가금액",
      optionsAvailable: "이 상품에는 선택 가능한 옵션이 있습니다.",
      optionsNotSynced:
        "옵션 정보가 아직 동기화되지 않았습니다. 상품 카탈로그를 최신화해주세요.",
    },
  },
  vi: {
    tabs: {
      daily: "Ngày",
      receipts: "Hóa đơn",
      monthly: "Tháng",
    },
    common: {
      receipt: "Hóa đơn",
      receipts: "Hóa đơn",
      soldItems: "Món bán",
      salesItems: "Món bán",
      optionItems: "Tùy chọn",
      salesAmount: "Tiền hàng",
      totalPaymentAmount: "Tổng thanh toán",
      actualPaid: "Thực trả",
      totalSales: "Doanh thu",
      averageReceiptAmount: "TB / hđ",
      paidReceiptBase: "HĐ đã thanh toán",
      paymentSummary: "Thanh toán",
      paymentBase: "Theo POS",
      paymentTotal: "Tổng thanh toán",
      taxSummary: "Thuế",
      taxSaving: "Giảm thuế",
      amountDifference: "Chênh lệch",
      adjustedReceiptBase: "HĐ đã sửa",
      businessDayBase: "Theo ngày kinh doanh",
      soldItemBase: "Theo món bán",
      taxDataLoading: "Đang tải dữ liệu thuế.",
      taxDataLoadFailed: "Không thể tải dữ liệu thuế",
      noTaxData: "Không có dữ liệu thuế",
      receiptCountSuffix: "hđ",
      itemCountSuffix: "món",
      productCountSuffix: "món",
      optionCountSuffix: "tùy chọn",
      detailLoading: "Đang tải chi tiết",
      detailLoadFailed: "Không thể tải chi tiết",
      noPaymentData: "Không có dữ liệu thanh toán",
    },
    daily: {
      badge: "TODAY",
      title: "Doanh thu ngày",
      syncButton: "Tải dữ liệu POS",
      forceSyncButton: "Làm mới bắt buộc",
      syncing: "Đang tải",
      syncSuccess: "Đã đồng bộ POS",
      syncSkipped: "Đã đồng bộ gần đây nên không tải lại",
      syncFailed: "Không thể tải POS",
      noLogin: "Không có thông tin đăng nhập",
      hourlySales: "Theo giờ",
      topItems: "Món bán nhiều",
      hourlyDataLoading: "Đang tải doanh thu theo giờ.",
      noHourlySalesData: "Không có doanh thu theo giờ",
      topItemsLoading: "Đang tải món bán nhiều.",
      noTopItemsData: "Không có dữ liệu món bán",
    },
    monthly: {
      badge: "MONTHLY",
      title: "Doanh thu tháng",
      previousMonth: "Trước",
      nextMonth: "Sau",
      dailySales: "Doanh thu theo ngày",
      menuSales: "Tình hình bán món",
      salesQuantity: "Số lượng bán",
      itemSalesAmount: "Doanh thu món",
      salesReceiptCount: "Số hóa đơn",
      option: "Tùy chọn",
      selection: "Lựa chọn",
      unlinkedOptions: "Tùy chọn chưa liên kết",
      unlinkedOptionsWarning:
        "Một số tùy chọn chưa liên kết với món chính nên được thống kê riêng.",
      unlinkedOptionDetails: "Chi tiết tùy chọn chưa liên kết",
      lineCountLabel: "Dòng",
      saleDate: "Thời gian bán",
      failureReason: "Lý do chưa liên kết",
      failureReasons: {
        missing_parent_id: "Thiếu ID món chính",
        parent_not_found: "Không tìm thấy món chính",
        parent_not_sales_line: "Dòng cha không phải món bán",
        parent_excluded_or_not_eligible: "Món chính không nằm trong phạm vi thống kê",
        parent_missing_ref_detail_id: "Món chính thiếu ID liên kết",
        unknown: "Cần kiểm tra",
      },
      noMenuSalesData: "Không có dữ liệu bán món.",
      menuSalesDataLoading: "Đang tải tình hình bán món.",
      menuSalesDataLoadFailed: "Không thể tải dữ liệu bán món",
      all: "Tất cả",
      food: "Món ăn",
      drink: "Rượu & đồ uống",
      uncategorized: "Chưa phân loại",
      categoryManagement: "Quản lý phân loại",
      assignToFood: "Chuyển sang món ăn",
      assignToDrink: "Chuyển sang rượu & đồ uống",
      keepUncategorized: "Giữ chưa phân loại",
      unclassifiedCategoriesNotice: "Có danh mục chưa được phân loại.",
      sameCategoryMovesTogether:
        "Các món có cùng tên danh mục sẽ được chuyển cùng nhau.",
      categoryGroupSaved: "Đã lưu phân loại danh mục.",
      categoryGroupSaveFailed: "Lưu phân loại danh mục thất bại.",
      noPermission: "Không có quyền.",
      sortHighToLow: "Cao đến thấp",
      sortLowToHigh: "Thấp đến cao",
      category: "Danh mục",
      categorySales: "Bán theo danh mục",
      allMenuItems: "Tất cả món",
      menuSalesScrollNotice:
        "Có thể cuộn danh sách để xem toàn bộ món.",
      dailyAverageSales: "TB/ngày",
      percentOfMonth: "Tỷ lệ tháng",
      dailyDataLoading: "Đang tải doanh thu theo ngày.",
      dailyDataLoadFailed: "Không thể tải doanh thu theo ngày",
      noMonthlySalesData: "Không có doanh thu tháng",
    },
    receipts: {
      badge: "RECEIPTS",
      title: "Hóa đơn",
      listTitle: "Danh sách hóa đơn",
      noReceipts: "Không có hóa đơn",
      selectedBusinessDateNoReceipts: "Không có hóa đơn cho ngày đã chọn.",
      menuSyncButton: "Đồng bộ menu chỉnh sửa hóa đơn",
      menuSyncDescription:
        "Tải lại thông tin món, giá và tùy chọn mới nhất từ POS.",
      menuSyncing: "Đang đồng bộ menu...",
      menuSyncSuccess: "Đồng bộ menu hoàn tất",
      menuSyncApplied: "đã cập nhật",
      menuSyncDetailFailed: "lỗi chi tiết",
      menuSyncCountSuffix: " mục",
      menuSyncDetailWarning:
        "Một số món chưa tải được thông tin tùy chọn chi tiết. Tùy chọn của các món đó có thể bị thiếu.",
      menuSyncFailed: "Đồng bộ menu thất bại.",
      noPermission: "Không có quyền.",
      createManualReceiptButton: "Tạo hóa đơn thủ công",
      manualReceiptModalTitle: "Tạo hóa đơn thủ công",
      manualReceiptCreating: "Đang tạo...",
      manualReceiptSaved: "Đã tạo hóa đơn thủ công.",
      manualReceiptFailed: "Không thể tạo hóa đơn thủ công.",
      manualReceiptBadge: "Tự tạo",
      manualReceiptFreeTextHint: "Món nhập tay có thể cần liên kết thủ công để trừ kho.",
      manualReceiptNoLines: "Vui lòng thêm ít nhất một món.",
      manualReceiptSaleTime: "Thời gian bán",
      manualReceiptTableOrNote: "Bàn / Ghi chú",
      manualReceiptVatEnabled: "Có VAT",
      manualReceiptVatDisabled: "Không VAT",
      manualReceiptDirectInput: "Nhập tay",
      manualReceiptPosSearch: "Tìm món POS",
    },
    receiptsEdit: {
      title: "Sửa hóa đơn",
      taxRecalculateNotice: "Thuế sẽ được tính lại sau khi lưu.",
      addItem: "Thêm món",
      searchProductPlaceholder: "Nhập mã hoặc tên món",
      editMemo: "Ghi chú sửa",
      memoPlaceholder: "Nhập lý do chỉnh sửa",
      productSearchFailed: "Không thể tìm món",
      saveFailed: "Không thể sửa hóa đơn",
      finalAmountTooHigh: "Tiền nhận nhỏ hơn tổng tiền.",
      optionEditProtected:
        "Hóa đơn có tùy chọn hiện chưa thể chỉnh sửa. Hệ thống đang bảo vệ để tránh sai lệch tiền tùy chọn và VAT.",
      existingOptionReadOnlyNotice:
        "Không thể chỉnh sửa trực tiếp tùy chọn cũ. Nếu muốn đổi tùy chọn, hãy xóa món chính rồi thêm lại.",
      selectOptions: "Chọn tùy chọn",
      noOptions: "Không có tùy chọn",
      surcharge: "Phụ thu",
      optionsAvailable: "Món này có tùy chọn có thể chọn.",
      optionsNotSynced:
        "Chưa đồng bộ thông tin tùy chọn. Vui lòng cập nhật danh mục món.",
    },
  },
} as const;
