export const salesText = {
  ko: {
    tabs: {
      daily: "일간현황",
      receipts: "영수증 조회",
      monthly: "월간현황",
    },
    common: {
      receipt: "영수증",
      receipts: "영수증",
      soldItems: "판매상품",
      salesItems: "판매상품",
      optionItems: "옵션",
      salesAmount: "판매금액",
      totalPaymentAmount: "총 결제금액",
      actualPaid: "실제 지불",
      totalSales: "총 매출",
      averageReceiptAmount: "객단가",
      paidReceiptBase: "결제 완료 영수증 기준",
      paymentSummary: "결제수단 요약",
      paymentBase: "POS 결제 기준",
      paymentTotal: "결제 합계",
      taxSummary: "세금 요약",
      taxSaving: "절세",
      adjustedReceiptBase: "수정 영수증 기준",
      businessDayBase: "영업일 기준",
      soldItemBase: "판매상품 기준",
      taxDataLoading: "세금 데이터를 불러오고 있습니다.",
      taxDataLoadFailed: "세금 데이터 로드 실패",
      noTaxData: "세금 데이터 없음",
      receiptCountSuffix: "건",
      itemCountSuffix: "개",
      productCountSuffix: "개",
      optionCountSuffix: "개",
      detailLoading: "상세 내용 로드 중",
      detailLoadFailed: "상세 로드 실패",
      noPaymentData: "결제 데이터 없음",
    },
    daily: {
      badge: "TODAY",
      title: "일간현황",
      syncButton: "POS 데이터 불러오기",
      syncing: "불러오는 중",
      syncSuccess: "POS 데이터 동기화 완료",
      syncFailed: "POS 데이터 로드 실패",
      noLogin: "로그인 정보 없음",
      hourlySales: "시간대별 매출",
      topItems: "많이 팔린 상품",
      hourlyDataLoading: "시간대별 매출을 불러오고 있습니다.",
      noHourlySalesData: "시간대별 매출 데이터 없음",
      topItemsLoading: "많이 팔린 상품을 불러오고 있습니다.",
      noTopItemsData: "판매상품 데이터 없음",
    },
    monthly: {
      badge: "MONTHLY",
      title: "월간현황",
      previousMonth: "이전",
      nextMonth: "다음",
      dailySales: "일별 매출",
      dailyAverageSales: "일평균",
      percentOfMonth: "월매출 비중",
      dailyDataLoading: "일별 매출을 불러오고 있습니다.",
      dailyDataLoadFailed: "일별 매출 데이터 로드 실패",
      noMonthlySalesData: "월간 매출 데이터 없음",
    },
    receipts: {
      badge: "RECEIPTS",
      title: "영수증 조회",
      listTitle: "영수증 목록",
      noReceipts: "영수증 데이터 없음",
      selectedBusinessDateNoReceipts: "선택한 영업일의 영수증이 없습니다.",
    },
    receiptsEdit: {
      title: "영수증 수정",
      taxRecalculateNotice: "저장 후 세금 합계가 재반영됩니다.",
      addItem: "품목 추가",
      searchProductPlaceholder: "코드 또는 품목명 입력",
      editMemo: "수정 메모",
      memoPlaceholder: "수정 사유를 입력하세요",
      productSearchFailed: "상품 검색 실패",
      saveFailed: "영수증 수정 실패",
      finalAmountTooHigh: "받은 금액이 최종금액보다 적습니다.",
    },
  },
  vi: {
    tabs: {
      daily: "Ngày",
      receipts: "Hóa đơn",
      monthly: "Tháng",
    },
    common: {
      receipt: "Hóa đơn",
      receipts: "Hóa đơn",
      soldItems: "Món bán",
      salesItems: "Món bán",
      optionItems: "Tùy chọn",
      salesAmount: "Tiền hàng",
      totalPaymentAmount: "Tổng thanh toán",
      actualPaid: "Thực trả",
      totalSales: "Doanh thu",
      averageReceiptAmount: "TB / hđ",
      paidReceiptBase: "HĐ đã thanh toán",
      paymentSummary: "Thanh toán",
      paymentBase: "Theo POS",
      paymentTotal: "Tổng thanh toán",
      taxSummary: "Thuế",
      taxSaving: "Giảm thuế",
      adjustedReceiptBase: "HĐ đã sửa",
      businessDayBase: "Theo ngày kinh doanh",
      soldItemBase: "Theo món bán",
      taxDataLoading: "Đang tải dữ liệu thuế.",
      taxDataLoadFailed: "Không thể tải dữ liệu thuế",
      noTaxData: "Không có dữ liệu thuế",
      receiptCountSuffix: "hđ",
      itemCountSuffix: "món",
      productCountSuffix: "món",
      optionCountSuffix: "tùy chọn",
      detailLoading: "Đang tải chi tiết",
      detailLoadFailed: "Không thể tải chi tiết",
      noPaymentData: "Không có dữ liệu thanh toán",
    },
    daily: {
      badge: "TODAY",
      title: "Doanh thu ngày",
      syncButton: "Tải dữ liệu POS",
      syncing: "Đang tải",
      syncSuccess: "Đã đồng bộ POS",
      syncFailed: "Không thể tải POS",
      noLogin: "Không có thông tin đăng nhập",
      hourlySales: "Theo giờ",
      topItems: "Món bán nhiều",
      hourlyDataLoading: "Đang tải doanh thu theo giờ.",
      noHourlySalesData: "Không có doanh thu theo giờ",
      topItemsLoading: "Đang tải món bán nhiều.",
      noTopItemsData: "Không có dữ liệu món bán",
    },
    monthly: {
      badge: "MONTHLY",
      title: "Doanh thu tháng",
      previousMonth: "Trước",
      nextMonth: "Sau",
      dailySales: "Theo ngày",
      dailyAverageSales: "TB/ngày",
      percentOfMonth: "Tỷ lệ tháng",
      dailyDataLoading: "Đang tải doanh thu theo ngày.",
      dailyDataLoadFailed: "Không thể tải doanh thu theo ngày",
      noMonthlySalesData: "Không có doanh thu tháng",
    },
    receipts: {
      badge: "RECEIPTS",
      title: "Hóa đơn",
      listTitle: "Danh sách hóa đơn",
      noReceipts: "Không có hóa đơn",
      selectedBusinessDateNoReceipts: "Không có hóa đơn cho ngày đã chọn.",
    },
    receiptsEdit: {
      title: "Sửa hóa đơn",
      taxRecalculateNotice: "Thuế sẽ được tính lại sau khi lưu.",
      addItem: "Thêm món",
      searchProductPlaceholder: "Nhập mã hoặc tên món",
      editMemo: "Ghi chú sửa",
      memoPlaceholder: "Nhập lý do chỉnh sửa",
      productSearchFailed: "Không thể tìm món",
      saveFailed: "Không thể sửa hóa đơn",
      finalAmountTooHigh: "Tiền nhận nhỏ hơn tổng tiền.",
    },
  },
} as const;
