export const salesText  = {
  ko: {
    title: "매출 입력",
    recentOrders: "최근 주문",
    noRecentOrders: "최근 주문 없음",
    openForm: "매출 입력 열기",
    closeForm: "매출 입력 접기",
    inputTitle: "영수증 입력",
    date: "날짜",
    startTime: "시작시간",
    endTime: "종료시간",
    table: "테이블",
    payment: "결제수단",
    group: "코드 그룹",
    itemAdd: "상품 추가",
    customInput: "직접입력",
    currentOrder: "현재 주문",
    noItems: "품목 없음",
    subtotal: "공급가",
    tax: "세금",
    total: "총액",
    save: "저장",
    reset: "초기화",
    orderList: "주문 목록",
    searchPlaceholder: "테이블 / 코드 / 상품명 검색",
    all: "전체",
  },
  vi: {
    title: "Nhập doanh thu",
    recentOrders: "Đơn gần đây",
    noRecentOrders: "Chưa có dữ liệu",
    openForm: "Mở form nhập doanh thu",
    closeForm: "Đóng form nhập doanh thu",
    inputTitle: "Nhập hóa đơn",
    date: "Ngày",
    startTime: "Bắt đầu",
    endTime: "Kết thúc",
    table: "Bàn",
    payment: "Thanh toán",
    group: "Nhóm mã",
    itemAdd: "Thêm món",
    customInput: "Nhập trực tiếp",
    currentOrder: "Đơn đang nhập",
    noItems: "Chưa có món",
    subtotal: "Cung cấp",
    tax: "Thuế",
    total: "Tổng",
    save: "Lưu",
    reset: "Đặt lại",
    orderList: "Danh sách 주문",
    searchPlaceholder: "Tìm theo bàn / mã / tên",
    all: "Tất cả",
  },
};