export const inventorySnapshotText = {
    ko: {
        title: "일자별 재고확인",
        backToInventory: "재고 페이지로 돌아가기",
        snapshotDates: "날짜 선택",
        searchPlaceholder: "품목명 / 카테고리 / 코드 검색",
        partAll: "전체",
        partKitchen: "주방",
        partHall: "홀",
        partBar: "바",
        partEtc: "기타",
        resultCount: "품목 수",
        noBatches: "데이터 없음",
        noItems: "해당 날짜 재고 없음",
        resetFilter: "필터 초기화",
        baseDateLabel: "기준 날짜",
        compareNowLabel: "현재 재고와 비교 중",
    },
    vi: {
        title: "Kiểm tra tồn kho theo ngày",
        backToInventory: "Quay lại trang tồn kho",
        snapshotDates: "Chọn ngày",
        searchPlaceholder: "Tìm theo tên / danh mục / mã",
        partAll: "Tất cả",
        partKitchen: "Bếp",
        partHall: "Sảnh",
        partBar: "Bar",
        partEtc: "Khác",
        resultCount: "Số lượng mục",
        noBatches: "Không có dữ liệu",
        noItems: "Không có hàng hóa trong ngày này",
        resetFilter: "Đặt lại bộ lọc",
        baseDateLabel: "Ngày đang xem",
        compareNowLabel: "Đang so sánh với tồn kho hiện tại",
    },
} as const;